CREATE OR REPLACE TRIGGER AUD_USER_LOGINS_BIR_TR
  BEFORE INSERT
  ON AUD_USER_LOGINS
  FOR EACH ROW
BEGIN

  IF :NEW.ID IS NULL THEN

    SELECT AUD_USER_LOGINS_SEQ.NEXTVAL
    INTO   :NEW.ID
    FROM   DUAL;

  END IF;
END;
/
SHOW ERRORS;