#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell
#

actions = default;cancelselection;displaycounselsignin;counselsignin;counselsigninoverview;assignlegrep;searchlegrep;deletelegrep;completerepdelete

#
# Default Mapping
#

default.request = /home
default.class = uk.gov.courtservice.xhibit.web.cf.action.DefaultAction

#
# Cancel Selection
#

cancelselection.request = /cancelselection
cancelselection.class = uk.gov.courtservice.xhibit.web.cf.action.CancelSelectionAction

#
# Display Counsel Sign In (this may be redundant - check before removal and check in)
#

displaycounselsignin.request = /displaycounselsignin
displaycounselsignin.class = uk.gov.courtservice.xhibit.web.cf.action.DisplayCounselSignInAction

#
# Cousel Sign in 
#

counselsignin.request = /counselsignin
counselsignin.class = uk.gov.courtservice.xhibit.web.cf.action.CounselSignInAction

#
# Display Counsel Sign In Overview 
#

counselsigninoverview.request = /counselsigninoverview
counselsigninoverview.class = uk.gov.courtservice.xhibit.web.cf.action.CounselSigninOverviewAction

#
# Assign Legal Representative
#

assignlegrep.request = /assignlegrep
assignlegrep.class = uk.gov.courtservice.xhibit.web.cf.action.AssignLegRepAction

#
# Search Legal Representative
#

searchlegrep.request = /searchlegrep
searchlegrep.class = uk.gov.courtservice.xhibit.web.cf.action.SearchLegRepAction

#
#Delete Signed in Legal representatives
#

deletelegrep.request = /deletelegrep
deletelegrep.class = uk.gov.courtservice.xhibit.web.cf.action.DeleteLegRepAction

#
#Complete removal of signed in leg reps
#

completerepdelete.request = /completerepdelete
completerepdelete.class = uk.gov.courtservice.xhibit.web.cf.action.RemoveLegRepAction

