#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, Xdevelopment LLP (2003)
#

responses = home;identifylegrep;displaycounselsignin;assignlegrep;deletelegrep

#
# Home (-->  Search Legal Representative)
#

home.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page = normalwomessages.jsp
home.skeletonBodyKey = identify
home.skeletonTitleKey = signinlegalrep.title

#
# Search Legal Representative
#

identifylegrep.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
identifylegrep.page = normalwomessages.jsp
identifylegrep.skeletonBodyKey = identify
identifylegrep.skeletonTitleKey = signinlegalrep.title

#
# Assign Legal Rep
#

displaycounselsignin.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
displaycounselsignin.page = normalwomessages.jsp
displaycounselsignin.skeletonBodyKey = assign
displaycounselsignin.skeletonTitleKey = assignlegalrep.title

#
# Confirm assignment of legal rep
#

assignlegrep.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
assignlegrep.page = normalwomessages.jsp
assignlegrep.skeletonBodyKey = confirm
assignlegrep.skeletonTitleKey = confirmassignment.title

#
# Delete a Legal Rep
#
deletelegrep.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deletelegrep.page = normalwomessages.jsp
deletelegrep.skeletonBodyKey = deletelegrep
deletelegrep.skeletonTitleKey = signinlegalrep.title


