CREATE OR REPLACE TYPE "DARTS_MESSAGE_ID_ARRAY" AS VARRAY(32) OF INTEGER;
/

CREATE OR REPLACE TYPE "DARTS_MESSAGE_FAIL_ARRAY" AS VARRAY(32) OF VARCHAR2(500);
/

CREATE OR REPLACE TYPE "DARTS_MESSAGE_TYPE" 
AS OBJECT (
  MESSAGE_ID          NUMBER,
  XHIBIT_MESSAGE_CODE VARCHAR2(50),
  EXISS_MESSAGE_CODE  VARCHAR2(50),
  PAYLOAD             CLOB,
  RETRY_COUNT         NUMBER,
  NEXT_RETRY_TIME     DATE,
  CREATION_DATE       DATE,
  LAST_UPDATE_DATE    DATE
 );
/


CREATE OR REPLACE TYPE "DARTS_MESSAGE_ARRAY"
AS TABLE OF DARTS_MESSAGE_TYPE;
/