CREATE OR REPLACE PACKAGE DARTS_SUPPORT_PKG
AS

   PROCEDURE CLEARUP;

   PROCEDURE RESEND_FAILURES;
   
   FUNCTION ERROR_TEST
   RETURN NUMBER;
   
END DARTS_SUPPORT_PKG;
/
show errors
