id=CASE_ID
caseNumber=CASE_NUMBER
caseType=CASE_TYPE
magConvictionDate=MAG_CONVICTION_DATE
caseSubType=CASE_SUB_TYPE
caseTitle=CASE_TITLE
caseDescription=CASE_DESCRIPTION
linkedCaseID=LINKED_CASE_ID
bailMagCode=BAIL_MAG_CODE
refCourtID=REF_COURT_ID
courtID=COURT_ID
chargeImportIndicator=CHARGE_IMPORT_INDICATOR
crestSeveredInd=SEVERED_IND
crestIndictResp=INDICT_RESP
dateIndRec=DATE_IND_REC
prosAgencyRef=PROS_AGENCY_REFERENCE
version=CASE_VERSION
caseClass=CASE_CLASS
judgeReasonForAppeal=JUDGE_REASON_FOR_APPEAL
resultsVerified=RESULTS_VERIFIED
lengthTape=LENGTH_TAPE
noPageProsEvidence=NO_PAGE_PROS_EVIDENCE
noProsWitness=NO_PROS_WITNESS
estPDHTrialLength=EST_PDH_TRIAL_LENGTH
indictmentInfo1=INDICTMENT_INFO_1
indictmentInfo2=INDICTMENT_INFO_2
indictmentInfo3=INDICTMENT_INFO_3
indictmentInfo4=INDICTMENT_INFO_4
indictmentInfo5=INDICTMENT_INFO_5
indictmentInfo6=INDICTMENT_INFO_6
policeOfficerAttending=POLICE_OFFICER_ATTENDING
receiptType=RECEIPT_TYPE
cpsCaseWorker=CPS_CASE_WORKER
exportCharges=EXPORT_CHARGES
indChangeStatus=IND_CHANGE_STATUS