id=DEFENDANT_ID
crestDefendantID=CREST_DEFENDANT_ID
firstName=FIRST_NAME
middleName=MIDDLE_NAME
surname=SURNAME
initials=INITIALS
dateOfBirth=DATE_OF_BIRTH
gender=GENDER
lastConvictionDate=LAST_CONVICTION_DATE
isCompany=IS_COMPANY
version=DEFENDANT_ON_VERSION
addressID=ADDRESS_ID
courtID=COURT_ID