id=DEFENDANT_ON_CASE_ID
finalDrivingLicenceStatus=FINAL_DRIVING_LICENCE_STATUS
ptiurn=PTIURN
isJuvenile=IS_JUVENILE
isMasked=IS_MASKED
maskedName=MASKED_NAME
caseID=CASE_ID
defendantID=DEFENDANT_ID
version=DEFENDANT_ON_CASE_VERSION
obsInd=DEFENDANT_ON_CASE_OBS_IND
resultsVerified=RESULTS_VERIFIED
defendantNumber=DEFENDANT_NUMBER
dateOfCommittal=DATE_OF_COMMITTAL
noOfTICs=NO_OF_TICS