id=REF_HEARING_TYPE_ID
hearingTypeCode=HEARING_TYPE_CODE
hearingTypeDesc=HEARING_TYPE_DESC
category=CATEGORY
seqNo=SEQ_NO
listSequence=LIST_SEQUENCE
version=REF_HEARING_TYPE_VERSION
courtId=COURT_ID
obsInd=REF_HEARING_TYPE_OBS_IND