id=SCHEDULED_HEARING_ID
sequenceNo=SEQUENCE_NO
notBeforeTime=NOT_BEFORE_TIME
originalTime=ORIGINAL_TIME
listingNote=LISTING_NOTE
hearingProgress=HEARING_PROGRESS
sittingID=SITTING_ID
hearingID=HEARING_ID
movedFrom=MOVED_FROM
version=SCHEDULED_HEARING_VERSION
linkedSHID=LINKED_SH_ID
endTime=END_TIME
startTime=START_TIME
dateOfHearing=DATE_OF_HEARING
isCaseActive=IS_CASE_ACTIVE