-- Daily List values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DL', 'DOCUMENT_TYPE_ID', '1');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DL', 'STYLESHEET_NAME', 'http://www.courtservice.gov.uk/transforms/courtservice/dailyListHtml-v2-2.xsl');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DL', 'SCHEMA_NAME', 'http://www.courtservice.gov.uk/schemas/courtservice DailyList-v5-9.xsd');

-- Daily List Distribution values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLD', 'DOCUMENT_TYPE_ID', '23');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLD', 'STYLESHEET_NAME', 'Unknown');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLD', 'SCHEMA_NAME', 'Unknown');

-- Daily Prison List values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLP', 'DOCUMENT_TYPE_ID', '21');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLP', 'STYLESHEET_NAME', 'http://www.courtservice.gov.uk/transforms/courtservice/dailyPrisonListHtml-v2-1.xsl');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'DLP', 'SCHEMA_NAME', 'http://www.courtservice.gov.uk/schemas/courtservice DailyList-v5-9.xsd');

-- Firm List values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FL', 'DOCUMENT_TYPE_ID', '4');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FL', 'STYLESHEET_NAME', 'http://www.courtservice.gov.uk/transforms/courtservice/FirmListHtml.xsl');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FL', 'SCHEMA_NAME', 'http://www.courtservice.gov.uk/schemas/courtservice FirmList-v5-9.xsd');

-- Firm List Distribution values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FLD', 'DOCUMENT_TYPE_ID', '24');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FLD', 'STYLESHEET_NAME', 'Unknown');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'FLD', 'SCHEMA_NAME', 'Unknown');

-- Warned List values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WL', 'DOCUMENT_TYPE_ID', '3');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WL', 'STYLESHEET_NAME', 'http://www.courtservice.gov.uk/transforms/courtservice/WarnedListHtml.xsl');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WL', 'SCHEMA_NAME', 'http://www.courtservice.gov.uk/schemas/courtservice WarnedList-v5-9.xsd');

-- Warned List Distribution values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WLD', 'DOCUMENT_TYPE_ID', '25');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WLD', 'STYLESHEET_NAME', 'Unknown');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'WLD', 'SCHEMA_NAME', 'Unknown');

-- Running List values from CJIT.CJI_DOCUMENT_TYPE
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'RL', 'DOCUMENT_TYPE_ID', '2');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'RL', 'STYLESHEET_NAME', 'http://www.courtservice.gov.uk/transforms/courtservice/RunningListHtml.xsl');
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG (ADAPTOR_TYPE, SERVER_TYPE, DOCUMENT_NAME, SERVER_ADDRESS, PARAMETERS)
VALUES ('CJI', 'DOC_TYPE', 'RL', 'SCHEMA_NAME', 'http://www.courtservice.gov.uk/schemas/courtservice RunningList-v5-9.xsd');
