create or replace TRIGGER "XHIBIT".XHB_DISPOSAL2_BIR_TR
  BEFORE INSERT
  ON XHB_DISPOSAL2
  FOR EACH ROW

  DECLARE v_disposal2id NUMBER;

BEGIN

  IF :NEW.DISPOSAL2_ID IS NULL THEN

    SELECT XHB_DISPOSAL2_SEQ.NEXTVAL
    INTO   v_disposal2id
    FROM   DUAL;
	:NEW.DISPOSAL2_ID :=v_disposal2id;
	
	ELSE
		v_disposal2id := :NEW.DISPOSAL2_ID;

  END IF;
  
  IF :NEW.DIS_ID IS NULL OR :NEW.DIS_ID = -1 THEN
    :NEW.DIS_ID :=v_disposal2id;
  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/