#
# Property file for SourceCodeGenerator
#
# $Id: castorbuilder.properties,v 1.1 2006/08/21 09:48:32 bzjrnl Exp $

# To enable bound properties uncomment the following line. Please
# note that currently *all* fields will be treated as bound properties
# when enabled. This will change in the future when we introduce
# fine grained control over each class and it's properties.
#
#org.exolab.castor.builder.boundproperties=true

# Java class mapping of <xsd:element>'s and <xsd:complexType>'s 
#
org.exolab.castor.builder.javaclassmapping=element

# This property allows one to specify the super class of *all* 
# generated classes
#
#org.exolab.castor.builder.superclass=com.xyz.BaseObject

# XML namespace mapping to Java packages
#
org.exolab.castor.builder.nspackages=\
    http://schemas.cjse.gov.uk/messages/receive/2006-05=uk.gov.cjse.schemas.messages.receive.x200605,\
    http://schemas.cjse.gov.uk/messages/deliver/2006-05=uk.gov.cjse.schemas.messages.deliver.x200605,\
    http://schemas.cjse.gov.uk/messages/exception/2006-06=uk.gov.cjse.schemas.messages.exception.x200606,\
    http://schemas.cjse.gov.uk/messages/messaging/2006-05=uk.gov.cjse.schemas.messages.messaging.x200605,\
    http://schemas.cjse.gov.uk/messages/format/2006-05=uk.gov.cjse.schemas.messages.format.x200605,\
    http://schemas.cjse.gov.uk/messages/metadata/2006-05=uk.gov.cjse.schemas.messages.metadata.x200605,\
    http://www.w3.org/2005/05/xmlmime=org.w3.x2005.x05.xmlmime

# Set to true if you want to generate the equals method
# for each generated class
# false by default
#
#org.exolab.castor.builder.equalsmethod=true

# Set to true if you want to use Object Wrappers instead
# of primitives (e.g Float instead of float).
# false by default.
#
#org.exolab.castor.builder.primitivetowrapper=false

# Set to true if you want the generated class descriptors to
# expose the element and attribute names they contain.
# false by default.
#
#org.exolab.castor.builder.classdescfieldnames=false

# Set to true if you want the generated source code to contain
# Extra methods for the collection fields, such as get/set using
# the collection type in addition to the type-safe array.
# Set this to true if you want your code to be more compatible 
# with Castor JDO. This is false by default.
#
#org.exolab.castor.builder.extraCollectionMethods=true

# Use old-style (Castor 0.9.3.9) of naming that uppercases
# names after an underscore
#
#org.exolab.castor.xml.JavaNaming.upperCaseAfterUnderscore=true

# This property specifies whether generated enumerated type
# classes implement the EnumeratedTypeAccess interface.
# false by default
#org.exolab.castor.builder.enumTypeAccessInterface=true