INSERT INTO WMB_MESSAGE_ROUTE wmr (SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_VALUE, QUEUE_NAME, MAP_NAME, OPERATION)
                          VALUES ('XHIBIT',  'XHB_RECORDSHEET', 'STATUS', 'R', 'TRIGGER.IN', 'Exp_Res_CaseDef_Trigger_Preview', 'INSERT');
INSERT INTO WMB_MESSAGE_ROUTE wmr (SCHEMA_NAME, TABLE_NAME, COLUMN_NAME, COLUMN_VALUE, QUEUE_NAME, MAP_NAME, OPERATION)
                          VALUES ('XHIBIT',  'XHB_RECORDSHEET', 'STATUS', 'R', 'TRIGGER.IN', 'Exp_Res_CaseDef_Trigger_Preview', 'UPDATE');
/