DROP TABLE XHB_RECORDSHEET CASCADE CONSTRAINTS;


  CREATE TABLE "XHB_RECORDSHEET" 
   (	"RECORDSHEET_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"DEFENDANT_ON_CASE_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(1 BYTE) NOT NULL ENABLE, 
	"XML_DATA" CLOB, 
	"CREATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"VERSION" NUMBER(5,0) DEFAULT 1 NOT NULL ENABLE, 
	 CONSTRAINT "XHB_RECORDSHEET_PK" PRIMARY KEY ("RECORDSHEET_ID")
		  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
		  STORAGE (INITIAL 1M
						NEXT 1M
						PCTINCREASE 0)
		  TABLESPACE XHIBITD, 
	 CONSTRAINT "XHB_RECORDSHEET_FK1" FOREIGN KEY ("DEFENDANT_ON_CASE_ID")
		REFERENCES "XHB_DEFENDANT_ON_CASE" ("DEFENDANT_ON_CASE_ID") ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE (INITIAL 1M
                  NEXT 1M
                  PCTINCREASE 0)
 LOB ("XML_DATA") STORE AS (
  TABLESPACE XHIBITD ENABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  NOCACHE LOGGING 
  STORAGE (INITIAL 1M
                NEXT 1M
                PCTINCREASE 0)) ;
 

CREATE SEQUENCE  "XHB_RECORDSHEET_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
 /
