create or replace TRIGGER "XHIBIT".XHB_REFADVOCATE_BIR_TR
  BEFORE INSERT
  ON XHB_REF_ADVOCATE
  FOR EACH ROW

BEGIN

  IF :NEW.REF_ADVOCATE_ID IS NULL THEN

    SELECT XHB_REF_ADVOCATE_SEQ.NEXTVAL
	INTO   :NEW.REF_ADVOCATE_ID
    FROM   DUAL;

  END IF;
  
  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;
  
  IF :NEW.CREST_ADVOCATE_ID IS NULL THEN
    SELECT XHB_REF_ADVOCATE_CREST_SEQ.NEXTVAL
    INTO   :NEW.CREST_ADVOCATE_ID
    FROM DUAL;
  END IF;
END;
/