## Default properties used by the build process.
## If any properties require to be overwritten
## create or modify the file ./../build.properties
## with the values.  This file should NOT be
## altered on a per-server bases as it is checked
## into CVS.

xhibit.tx.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
xhibit.tx.database.driver=oracle.jdbc.xa.client.OracleXADataSource
xhibit.tx.database.user=xhibit
xhibit.tx.database.password=xhibit
xhibit.tx.database.jndi=XhibitOracleTxDataSource

xhibit.jms.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
xhibit.jms.database.driver=oracle.jdbc.OracleDriver
xhibit.jms.database.user=xhibit
xhibit.jms.database.password=xhibit
xhibit.jms.database.jndi=XhibitOracleJmsDataSource

exiss.tx.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
exiss.tx.database.driver=oracle.jdbc.xa.client.OracleXADataSource
exiss.tx.database.user=exiss
exiss.tx.database.password=exiss
exiss.tx.database.jndi=ExissOracleTxDataSource
exiss.tx.database.bigstringclobenabled=true
exiss.pool.capacity=15
exiss.pool.max.capacity=15

exiss.jms.outbridge.user=xhibit_bridge
exiss.jms.outbridge.password={3DES}SwrFsgiIYfWGrRgF6zMrPQ==
exiss.jms.outbridge.idletimemaximum=60
exiss.jms.outbridge.batchsize=9
exiss.jms.outbridge.batchinterval=20000

exiss.weblogic.kernel.default.count=40
exiss.weblogic.kernel.default.max.count=40
exiss.weblogic.kernel.default.min.count=5

exiss.message.builder.execute.queue.count=2
exiss.message.builder.execute.queue.max.count=2
exiss.message.builder.execute.queue.min.count=1

exiss.item.tracking.execute.queue.count=6
exiss.item.tracking.execute.queue.max.count=6
exiss.item.tracking.execute.queue.min.count=1

exiss.inbound.execute.queue.count=3
exiss.inbound.execute.queue.max.count=3
exiss.inbound.execute.queue.min.count=1

exiss.item.tracking.notifier.execute.queue.count=2
exiss.item.tracking.notifier.execute.queue.max.count=2
exiss.item.tracking.notifier.execute.queue.min.count=1

exiss.message.broker.execute.queue.count=2
exiss.message.broker.execute.queue.max.count=2
exiss.message.broker.execute.queue.min.count=1

exiss.deadletter.execute.queue.count=3
exiss.deadletter.execute.queue.max.count=6
exiss.deadletter.execute.queue.min.count=1

darts.execution.group.count=3
darts.execution.group.max.count=3
darts.execution.group.min.count=1

cjit.tx.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
cjit.tx.database.driver=oracle.jdbc.xa.client.OracleXADataSource
cjit.tx.database.user=cjit
cjit.tx.database.password=cjit
cjit.tx.database.jndi=CjitOracleTxDataSource

gdgate.tx.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
gdgate.tx.database.driver=oracle.jdbc.xa.client.OracleXADataSource
gdgate.tx.database.user=gdgate
gdgate.tx.database.password=gdgate
gdgate.tx.database.jndi=GdGateOracleTxDataSource
gdgate.tx.database.bigstringclobenabled=true
gdgate.pool.capacity=25
gdgate.pool.max.capacity=25

scjsegate.jms.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
scjsegate.jms.database.driver=oracle.jdbc.OracleDriver
scjsegate.jms.database.user=scjsegate
scjsegate.jms.database.password=scjsegate
scjsegate.jms.database.jndi=SjseGateOracleJmsDataSource

scjsegate.jms.inbridge.user=xhibit_bridge
scjsegate.jms.inbridge.password={3DES}SwrFsgiIYfWGrRgF6zMrPQ==
scjsegate.jms.inbridge.idletimemaximum=60
scjsegate.jms.inbridge.batchsize=6
scjsegate.jms.inbridge.batchinterval=20000

scjsegate.jms.trackbridge.user=xhibit_bridge
scjsegate.jms.trackbridge.password={3DES}SwrFsgiIYfWGrRgF6zMrPQ==
scjsegate.jms.trackbridge.idletimemaximum=60
scjsegate.jms.trackbridge.batchsize=6
scjsegate.jms.trackbridge.batchinterval=20000

scjsegate.weblogic.kernel.default.count=25
scjsegate.weblogic.kernel.default.max.count=25
scjsegate.weblogic.kernel.default.min.count=5

scjsegate.outbound.message.execute.queue.count=5
scjsegate.outbound.message.execute.queue.max.count=5
scjsegate.outbound.message.execute.queue.min.count=1

scjsegate.outbound.gateway.message.execute.queue.count=3
scjsegate.outbound.gateway.message.execute.queue.max.count=3
scjsegate.outbound.gateway.message.execute.queue.min.count=1

scjsegate.inbound.gateway.message.execute.queue.count=3
scjsegate.inbound.gateway.message.execute.queue.max.count=3
scjsegate.inbound.gateway.message.execute.queue.min.count=1

scjsegate.message.broker.execute.queue.count=3
scjsegate.message.broker.execute.queue.max.count=3
scjsegate.message.broker.execute.queue.min.count=1

darts.tx.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
darts.tx.database.driver=oracle.jdbc.xa.client.OracleXADataSource
darts.tx.database.user=darts
darts.tx.database.password=darts
darts.tx.database.jndi=DartsOracleTxDataSource

active.directory.host=130.177.4.44
active.directory.user=weblogic
active.directory.password=password

#
# This number should be updated when additional libraries are added
# to the library dir.
#

3rdparty.version=9.3.1

#exiss.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#exiss.database.driver=oracle.jdbc.xa.client.OracleXADataSource
#exiss.database.user=exiss
#exiss.database.password=exiss
#exiss.jndi.datasource.name=ExissOracleTxDataSource

#messagestore.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#messagestore.database.driver=oracle.jdbc.xa.client.OracleXADataSource
#messagestore.database.user=cjit
#messagestore.database.password=cjit
#messagestore.jndi.datasource.name=CJITOracleTxDataSource

#jms.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#jms.database.driver=oracle.jdbc.OracleDriver
#jms.database.user=xhibit
#jms.database.password=xhibit
#jms.jndi.datasource.name=JMSOracleTxDataSource

#database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#database.driver=oracle.jdbc.xa.client.OracleXADataSource
#database.user=xhibit
#database.password=xhibit
#jndi.datasource.name=XhibitOracleTxDataSource

#active.directory.host=130.177.4.44
#active.directory.user=weblogic
#active.directory.password=password

#3rdparty.version=9.2.0

#cjsegate.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#cjsegate.database.driver=oracle.jdbc.xa.client.OracleXADataSource
#cjsegate.database.user=cjsegate
#cjsegate.database.password=cjsegate
#cjsegate.jndi.datasource.name=CJSEGateOracleTxDataSource

#cjsegate.jms.database.url=jdbc\:oracle\:thin\:@130.177.4.44\:1521\:CSDBBLD1
#cjsegate.jms.database.driver=oracle.jdbc.OracleDriver
#cjsegate.jms.database.user=cjsegate
#cjsegate.jms.database.password=cjsegate
#cjsegate.jms.jndi.datasource.name=CJSEJMSGateOracleTxDataSource


