INSERT INTO XHB_CONFIG_PROP
(CONFIG_PROP_ID, PROPERTY_NAME,PROPERTY_VALUE)
SELECT XHB_CONFIG_PROP_SEQ.NEXTVAL, qry.* FROM (
SELECT 'CM_MAX_FILE_SIZE_MB' PROPERTY_NAME, '10' PROPERTY_VALUE FROM DUAL UNION
SELECT 'CM_MAX_FILE_ROWS' PROPERTY_NAME, '50000' PROPERTY_VALUE FROM DUAL
) qry
WHERE NOT EXISTS (SELECT NULL FROM XHB_CONFIG_PROP x1 WHERE x1.PROPERTY_NAME = qry.PROPERTY_NAME);

COMMIT;
/