UPDATE XHB_REF_ADVOCATE SET OBS_IND = 'Y' WHERE IS_GLOBAL = 'N';

UPDATE XHB_REF_LEGAL_REPRESENTATIVE SET OBS_IND='Y' where REF_LEGAL_REP_ID IN (SELECT REF_LEGAL_REP_ID from XHB_REF_ADVOCATE WHERE IS_GLOBAL='N');

UPDATE XHB_REF_CHAMBER SET OBS_IND = 'Y' WHERE IS_GLOBAL = 'N';

COMMIT;