CREATE OR REPLACE TRIGGER XHB_CASE_GRP_SEQ_GENTR_BIR_TR
  BEFORE INSERT
  ON XHB_CASE_GROUP_SEQ_GENERATOR
  FOR EACH ROW
  
BEGIN

  IF :NEW.CASE_GROUP_SEQ_GENERATOR_ID IS NULL THEN
  
    SELECT XHB_CASE_GRP_SEQ_GENERATOR_SEQ.NEXTVAL
    INTO   :NEW.CASE_GROUP_SEQ_GENERATOR_ID
    FROM   DUAL;
    
  END IF;

  IF ((:NEW.LAST_UPDATE_BY IS NULL)
     OR (:NEW.CREATED_BY IS NULL)) THEN
     
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATE_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;
    
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END XHB_CASE_GRP_SEQ_GENTR_BIR_TR;
/