ALTER TABLE xhb_case_on_list DROP CONSTRAINT XHB_CASE_ON_LIST_CR_IID_ID_FK;

ALTER TABLE xhb_case_on_list ADD (CONSTRAINT XHB_CASE_ON_LIST_CR_IID_ID_FK FOREIGN KEY (CRACKED_INEFFECTIVE_ID) REFERENCES XHB_REF_CRACKED_EFFECTIVE (REF_CRACKED_EFFECTIVE_ID));

commit;