create or replace TRIGGER xhb_ref_event_desc_bur_tr
  BEFORE UPDATE OR DELETE
  ON xhb_ref_event_description
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  IF UPDATING THEN

    l_trig_event := 'U';

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_REF_CRACKED_EFFECTIVE') = 1) THEN

    INSERT INTO AUD_REF_EVENT_DESCRIPTION (
     REF_EVENT_DESCRIPTION_ID
    ,EXTERNAL_EVENT_CODE
    ,EVENT_DESCRIPTION
    ,EVENT_SUB_DESCRIPTION
    ,SEND_TO_MIS
    ,OBS_IND
    ,LAST_UPDATE_DATE
    ,CREATION_DATE
    ,LAST_UPDATED_BY
    ,CREATED_BY
    ,VERSION
    ,insert_event
    )
    VALUES (
    :OLD.REF_EVENT_DESCRIPTION_ID
    ,:OLD.EXTERNAL_EVENT_CODE
    ,:OLD.EVENT_DESCRIPTION
    ,:OLD.EVENT_SUB_DESCRIPTION
    ,:OLD.SEND_TO_MIS
    ,:OLD.OBS_IND
    ,:OLD.LAST_UPDATE_DATE
    ,:OLD.CREATION_DATE
    ,:OLD.LAST_UPDATED_BY
    ,:OLD.CREATED_BY
    ,:OLD.VERSION
    ,l_trig_event
   );

  END IF;

END xhb_ref_event_desc_bur_tr;
/