CREATE OR REPLACE TRIGGER XHB_PUB_RUNNING_LIST_BIR_TR
  BEFORE INSERT
  ON XHB_PUB_RUNNING_LIST
  FOR EACH ROW
  
BEGIN

  IF :NEW.PUB_RUNNING_LIST_ID IS NULL THEN
  
    SELECT XHB_PUB_RUNNING_LIST_SEQ.NEXTVAL
    INTO   :NEW.PUB_RUNNING_LIST_ID
    FROM   DUAL;
    
  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL)
     OR (:NEW.CREATED_BY IS NULL)) THEN
     
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;
    
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END XHB_PUB_RUNNING_LIST_BIR_TR;
/

