CREATE OR REPLACE TRIGGER XHB_PUB_RUNNING_LIST_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_PUB_RUNNING_LIST
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  IF UPDATING THEN

    l_trig_event := 'U';

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_PUB_RUNNING_LIST') = 1) THEN

    INSERT INTO AUD_PUB_RUNNING_LIST (
    PUB_RUNNING_LIST_ID
    ,COURT_ID
    ,PUBLISHED_DATE
    ,OBS_IND
    ,LAST_UPDATE_DATE
    ,CREATION_DATE
    ,LAST_UPDATED_BY
    ,CREATED_BY
    ,VERSION
    ,insert_event
    )
    VALUES (
    :OLD.PUB_RUNNING_LIST_ID
    ,:OLD.COURT_ID
    ,:OLD.PUBLISHED_DATE
    ,:OLD.OBS_IND
    ,:OLD.LAST_UPDATE_DATE
    ,:OLD.CREATION_DATE
    ,:OLD.LAST_UPDATED_BY
    ,:OLD.CREATED_BY
    ,:OLD.VERSION
    ,l_trig_event
  );

  END IF;

END XHB_PUB_RUNNING_LIST_BUR_TR;
/