CREATE OR REPLACE TRIGGER xhb_mis_event_log_bir_tr
  BEFORE INSERT
  ON XHB_MIS_EVENT_LOG
  FOR EACH ROW
  
BEGIN

  IF :NEW.MIS_EVENT_LOG_ID IS NULL THEN
  
    SELECT XHB_MIS_EVENT_LOG_SEQ.NEXTVAL
    INTO   :NEW.MIS_EVENT_LOG_ID
    FROM   DUAL;
    
  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL)
     OR (:NEW.CREATED_BY IS NULL)) THEN
     
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;
    
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END xhb_mis_event_log_bir_tr;
/