  
  
  CREATE INDEX "XHIBIT"."CASE_ON_LIST_ID_IDX" ON "XHIBIT"."XHB_DEF_ON_CASE_ON_LIST" ("DEFENDANT_ON_CASE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;
 

  CREATE INDEX "XHIBIT"."DEFENDANT_ON_CASE_ID_IDX" ON "XHIBIT"."XHB_DEF_ON_CASE_ON_LIST" ("CASE_ON_LIST_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "USERS" ;