/*    ------------------------------------------------------------------
*     Modify columns to increase length of some columns, doing both XHB and AUD
*/    ------------------------------------------------------------------
ALTER TABLE XHB_CASE_ON_LIST 
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);
ALTER TABLE AUD_CASE_ON_LIST 
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);
	
ALTER TABLE XHB_SITTING_ON_LIST 
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);
ALTER TABLE AUD_SITTING_ON_LIST 
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);

ALTER TABLE XHB_CASE_DIARY_FIXTURE 
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);
ALTER TABLE AUD_CASE_DIARY_FIXTURE
	MODIFY LIST_NOTE_TEXT VARCHAR2(200);

ALTER TABLE XHB_SCHEDULED_HEARING 
	MODIFY LISTING_NOTE VARCHAR2(200);
ALTER TABLE AUD_SCHEDULED_HEARING
	MODIFY LISTING_NOTE VARCHAR2(200);

ALTER TABLE XHB_SITTING 
	MODIFY SITTING_NOTE VARCHAR2(200);
ALTER TABLE AUD_SITTING
	MODIFY SITTING_NOTE VARCHAR2(200);

ALTER TABLE XHB_DIARY_NOTE_ENTRY
	MODIFY DIARY_NOTE_TEXT VARCHAR2(200);
ALTER TABLE AUD_DIARY_NOTE_ENTRY
	MODIFY DIARY_NOTE_TEXT VARCHAR2(200);

/