CREATE OR REPLACE TRIGGER XHB_CPPSTAGINGINBOUND_BIR_TR
  BEFORE INSERT
  ON XHB_CPP_STAGING_INBOUND
  FOR EACH ROW

BEGIN


  IF :NEW.CPP_STAGING_INBOUND_ID IS NULL THEN

    SELECT XHB_CPP_STAGING_INBOUND_SEQ.NEXTVAL
    INTO   :NEW.CPP_STAGING_INBOUND_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/
