CREATE OR REPLACE TRIGGER xhb_cpp_list_bir_tr
  BEFORE INSERT
  ON xhb_cpp_list
  FOR EACH ROW
  
BEGIN

  IF :NEW.CPP_LIST_ID IS NULL THEN
  
    SELECT XHB_CPP_LIST_SEQ.NEXTVAL
    INTO   :NEW.CPP_LIST_ID
    FROM   DUAL;
    
  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL)
     OR (:NEW.CREATED_BY IS NULL)) THEN
     
    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;
    
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END;
/