######################
# CREST IMPORT
######################
SelectColumn=Select To Import
RefDataColumn=Type of Data
StatusColumn=Status

Court=Court
ImportType=Import Type

## Status
N=New
R=Requested
S=Successful
F=Failed
I=In Progress

dataRequested=The data has been requested. For more information check Import/Export Status screen.

#######################
# UnauthorisedCaseStatus
#######################
UnauthorisedCaseStatus.dialog_title=Unauthorised Case Status

UnauthorisedCaseStatusReport.title=Unauthorised Case Status Report

ucColCourtRoom=Court Room
ucColCaseNumber=Case Number
ucColDeftNames=Defendant Name(s)
ucColConclusionDate=Case Conclusion Date

ucCourtCentreName=Court Centre Name
ucCourtCentreId=Court Centre ID
ucBorderName=Unauthorised Cases

ucRefreshButton=Refresh

ucAllCourts=All Courts

#######################
# Reports
#######################
NoParameterReport.dialog_text=Please click OK button to run and view the report.
RunReport.error_title=No Data Found
RunReport.error_message=There were no records found for the entered criteria
RunReport.package_name=XHB_REPORT_PKG
#######################
#DOCAR
#######################
RunDOCARReport.dialog_title=DOCAR - Defendants with Outstanding Court of Appeal Results
RunDOCARReport.dialog_text=The Papers Sent to Court of Appeal Prior to:
RunDOCARReport.dialog_message=Press OK to run and view the report.
#######################
#ADJSS
#######################
ADJSSReport.dialog_title=ADJSS - List of Defendants Put Back for Sentence with Reasons
#######################
#DEFSS
#######################
DEFSSReport.dialog_title=DEFSS - List of Defendants with Deferred Sentences
#######################
#NFIX
#######################
NFIXReport.dialog_title=NFIX - Notification of Fixtures
NFIXReport.print_preview_title=NFIX Report
NFIXReport.base=icon/resource.txt
######################
#######################
#RELCJ
#######################
RELCJReport.dialog_title=RELCJ - Cases With Required Judge
RELCJReport.print_preview_title=RELCJ Report
######################
OUTCReport.dialog_title=OUTC - Outstanding Cases by Various Criteria
OUTCReport.dialog_text=OUTC Report
OUTCReport.panel_label_CaseTypeLabel=Case Type:
OUTCReport.panel_label_DefaultHearingTypeLabel=Default Hearing Type:
OUTCReport.panel_label_RequiredJudgeTypeLabel=Required Judge Type:
OUTCReport.panel_label_SecureCourtroomCheckBoxLabel=Secure Courtroom
OUTCReport.panel_label_ShowNotesBorderLabel=Show Notes
OUTCReport.panel_label_PriorityCheckBoxLabel=Priority
OUTCReport.panel_label_RestrictedCheckBoxLabel=Restricted
OUTCReport.panel_label_StandardCheckBoxLabel=Standard
OUTCReport.panel_label_PreviewLabel=Press OK to preview the report
OUTCReport.panel_label_SortByBorderLabel=Sort By
OUTCReport.panel_label_AgeRadioButtonLabel=Age
OUTCReport.panel_label_CaseNumberRadionButtonLabel=Case Number
OUTCReport.panel_label_BCStatusLabel=B/C Status:
OUTCReport.panel_label_JuvenileOnlyCheckBoxLabel=Juvenile Only
OUTCReport.panel_label_caseClassSelectAnyCheckBoxLabel=Any
OUTCReport.panel_label_caseClassSelectOneCheckBoxLabel=1
OUTCReport.panel_label_caseClassSelectTwoCheckBoxLabel=2
OUTCReport.panel_label_caseClassSelectThreeCheckBoxLabel=3
OUTCReport.panel_label_TimeEstimateLabel=Time Estimate Between :
OUTCReport.panel_label_TimeEstimateAndLabel=and 
OUTCReport.panel_casesOlderThanLabel=Cases Older Than:
OUTCReport.panel_label_weeksOldLabel=Weeks Old.
OUTCReport.panel_label_CaseClassLabel=Case Class:
OUTCReport.panel_dropdowndefault_title=Any
#######################
UNLCReport.dialog_title=UNLC - Unlisted Cases by Various Criteria
UNLCReport.dialog_text=UNLC Report
##########################################
# CourtOfAppeal
#######################
CourtOfAppeal.dialog_title=Court Of Appeal
#######################
#CFIX
#######################
CFIXReport.dialog_title=CFIX - Cumulative List of Fixed Dates
CFIXReport.print_preview_title=CFIX Report
CFIXReport.Hearing_start_label=Enter Hearing From Date
CFIXReport.Hearing_end_label=(Optional)End Date
CFIXReport.Preview_label=Press OK to preview the report
CFIXReport.start_date_after_end_date_message = End date must be equal to or greater than the From date

########################
#LOD
#######################
LODReport.dialog_title=LODR - Listing officer's Diary
LODReport.dialog_from_date=Enter From Date:
LODReport.dialog_to_date=(Optional) To Date:
LODReport.dialog_preview=Press OK to preview the report.

#LFIX
#######################
LFIXReport.dialog_title=List of Fixed Dates (Criminal)
LFIXReport.dialog_text=Reprint report for :-
LFIXReport.dialog_label1 = Click OK to preview the List of Fixed Dates.                                                            
LFIXReport.dialog_label2 = It will show all cases with future fixed hearings since the last time the report was run
LFIXReport.base=icon/resource.txt
#######################
#DARTS
#######################
DARTSReport.dialog_title=XHIBIT Summary of DARTS Retention Cases
DARTSReport.dialog_start_date=Start Date                                                         
DARTSReport.dialog_end_date=End Date (Optional)
DARTSReport.dialog_preview=Press OK to preview the report
DARTSReport.base=icon/resource.txt
DARTSReport.error_title=Date Range Exceeded
DARTSReport.error_message=The start and end date range is limited to 60 days
#######################
#CTLRP
#######################
CTLRPReport.dialog_title=CTLRP - Trials Approaching Custody Time Limits
CTLRPReport.dialog_custody_time_limit=Show Custody Time Limits due to expire on or before:
CTLRPReport.dialog_print_exceptions_report=Print Exceptions Report?
CTLRPReport.dialog_print_reminder_letters=Print Reminder Letters?
CTLRPReport.base=icon/resource.txt
#######################
#NHA
#######################
NHAReport.dialog_title=NHA - Notice of Hearing of Appeal
NHAReport.print_preview_title=NHA Report
NHAReport.base=icon/resource.txt

#######################
#PRLIS
#######################
PRLISReport.dialog_title=PRLIS - Running List
PRLISReport.dialog_text = Click Ok to preview the Running List
PRLISReport.show_all_cases = Show all cases added since the last time the report was published ( %s )
PRLISReport.show_previous_report = Preview a previously published list
PRLISReport.missing_previous_list_selection = A Previously Published List must be selected
PRLISReport.published_lists = Published Running List
PRLISReport.publish_successful_title = Running List Published
PRLISReport.publish_successful = Published successfully on %s

#######################
#OBW
#######################
OBWReport.dialog_title=OBW - Outstanding Bench Warrants
OBWReport.print_preview_title=OBW Report
OBWReport.dialog_text=Show OBWs issued from:-
OBWReport.leave_blank =Or leave blank to show all outstanding warrants.

#######################
#DRSR
#######################
DRSRReport.dialog_title=DRSR - Missing Trial Codes
DRSRReport.print_preview_title=DRSR Report
DRSRReport.panel_label_Select_Month_Label=Select Monthly Period:
#######################
#RAGE
#######################
RAGEReport.dialog_title=RAGE - Cases Over 'N' Weeks Old
RAGEReport.dialog_text= Press OK to preview the report.
RAGEReport.dialog_cases1=Include Cases between
RAGEReport.dialog_cases2=and
RAGEReport.dialog_cases3=weeks old.
RAGEReport.bailStatus=Bail / Custody status:
RAGEReport.dialog_include_case=Include Case Class:
RAGEReport.dialog_include_case_class1=1
RAGEReport.dialog_include_case_class2=2
RAGEReport.dialog_include_case_class3=3
#######################
#RUMO
#######################
RUMOReport.dialog_title=RUMO - Unacknowledged Monetray Orders
RUMOReport.print_preview_title=RUMO Report
#######################
RRECReport.dialog_title=RREC - Cases Received and Disposed Of
RRECReport.dialog_text=Press OK to preview the report.
RRECReport.dialog_runType=Run Type:
RRECReport.dialog_weekEnding=Week Ending
RRECReport.dialog_monthEnding=Month Ending

######################
#NTRSF
######################
NTRSFReport.dialog_title=NTRSF - Notification of Case Transfer
NTRSFReport.dialog_label1=Case Number:
NTRSFReport.dialog_label2=Case Title:
NTRSFReport.dialog_label3=Press OK to run and preview the transfer notification letters
NTRSFReport.base=icon/resource.txt

#######################
#RJS
#######################
RJSReport.dialog_title=Report of Judge Sittings
RJSReport.print_preview_title=RJS Report
RJSReport.panel_label_Select_Month_Label=Month Ending:
RJSReport.panel_label_PreviewLabel=Press OK to preview the report

######################
#Record Courtroom Statistics.
######################
RecordCourtroomStatisticsDialog.title=Record Courtroom Statistics
RecordCourtroomStatistics.savebutton.label=Save Manual Edits
RecordCourtroomStatistics.savebutton.tooltip=Save manual edits made to Sitting Times or Sat In checkboxes
RecordCourtroomStatistics.closebutton.label=Close
RecordCourtroomStatistics.closebutton.tooltip=Close
RecordCourtroomStatistics.ampmcolumn.tooltip=Double-click to edit
RecordCourtroomStatistics.judgeUsage=Judge Usage
RecordCourtroomStatistics.courtRoomUsage=Court Room Usage
RecordCourtroomStatistics.roomusage.col.courtname=Court Room Name
RecordCourtroomStatistics.roomusage.col.sittingdate=Sitting Date
RecordCourtroomStatistics.roomusage.col.amhoursmins=AM Hours:Mins
RecordCourtroomStatistics.roomusage.col.pmhoursmins=PM Hours:Mins
RecordCourtroomStatistics.judgeusage.col.judgename=Judge Name
RecordCourtroomStatistics.judgeusage.col.sittingdate=Sitting Date
RecordCourtroomStatistics.judgeusage.col.roomname=Court Room Name
RecordCourtroomStatistics.judgeusage.col.satincourt=Sat In Court
RecordCourtroomStatistics.judgeusage.col.satinchambers=Sat In Chambers
RecordCourtroomStatistics.sittingdate.label=Sitting Date:
RecordCourtroomStatistics.site.label=Site:

RecordCourtroomStatisticsSaveSuccessTitle = Save Successful
RecordCourtroomStatisticsSaveSuccessMesssage = The changes to the statistics have been saved.

RecordCourtroomStatisticsCancelConfirmationTitle = Are you sure?
RecordCourtroomStatisticsCancelConfirmationMessage = All unsaved data will be lost.\nAre you sure?

RecordCourtroomStatisticsDeleteConfirmationTitle = Are you sure?
RecordCourtroomStatisticsDeleteConfirmationMessage = This entry will be permanently deleted.\nAre you sure?

######################
#Add Court Room Usage
######################
AddCourtRoomUsageDialog.title=Manually Add Court Room Usage
AddCourtRoomUsageDialog.courtroom.label=Court Room : 
AddCourtRoomUsageDialog.am.label=AM:
AddCourtRoomUsageDialog.amhours.label=Hrs
AddCourtRoomUsageDialog.ammins.label=Mins
AddCourtRoomUsageDialog.pm.label=PM:
AddCourtRoomUsageDialog.pmhours.label=Hrs
AddCourtRoomUsageDialog.pmmins.label=Mins

######################
#Add Judge Usage
######################
AddJudgeUsageDialog.title=Manually Add Judge Usage
AddJudgeUsageDialog.courtroom.label=Court Room : 
AddJudgeUsageDialog.judge.label=Judge : 
AddJudgeUsageDialog.satIn.label=Sat In : 

#######################
#INFTRPC
#######################

INFTRPCReport.dialog_title=Cracked/Ineffective Trial Cases
INFTRPCReport.print_preview_title=INFTRP/C
INFTRPCReport.panel_label_Select_Month_Label=Select Monthly Period:
INFTRPCReport.panel_label_PreviewLabel=Press OK to preview the report
INFTRPCReport.panel_label_ReportOptionLabel=Report Option:

#######################
#CTLRL
#######################
CTLRLReport.dialog_title=CTLRL - Custody Time Limit Reminder Letter
CTLRLReport.dialog_letter_already_printed_message=Custody Time Limit Letters for all cases have already been printed

#######################
#RRCA
#######################
RRCAReport.dialog_title=RRCA - Outstanding Trial Cases by Age
RRCAReport.print_preview_title=RRCA Report
RRCAReport.panel_label_Select_Month_Label=Select Monthly Period:
RRCAReport.panel_label_PreviewLabel=Press OK to run and view the report.
 
#######################
#RSIT
#######################
RSITReport.dialog_title=RSIT - Courtroom Sitting Times
RSITReport.print_preview_title=RSIT Report
RSITReport.panel_label_Enter_Site_Label=Enter site to report upon
RSITReport.panel_label_Enter_Date_Label=Enter Week Ending Date
RSITReport.panel_label_Preview_Label=Press OK to preview the report

#######################
#OGRDA
#######################
OGRDAOrder.base=icon/resource.txt
 
#######################
#OGRDA
#######################
OGRROrder.base=icon/resource.txt
 
 
