#####
# Deprecated Codes for original 40701 and 40702 events
#####
E40701_Defendant_Identified=Defendant identified
E40701_No_Reply=No reply
E40701_Defendant_Identified_DB=Y
E40701_No_Reply_DB=N
E40701_RIC=Remanded in custody
E40701_Bail_As_Before=Bail as before
E40701_Bail_Varied=Bail varied
E40701_RIC_DB=1
E40701_Bail_As_Before_DB=2
E40701_Bail_Varied_DB=3
E40701_Granted=Granted
E40701_Refused=Refused
E40701_Not_Requested=Not requested
E40701_Granted_DB=1
E40701_Refused_DB=2
E40701_Not_Requested_DB=3
E40701_Filed=Filed
E40701_To_Be_Filed=To be filed by
E40701_Filed_DB=Y
E40701_To_Be_Filed_DB=N
E40702_Form_Handed_In=Form handed in
E40702_Form_Not_Handed_In=Form NOT handed in
E40702_Form_Handed_In_DB=Y
E40702_Form_Not_Handed_In_DB=N
E40702_Hours=Hour(s)
E40702_Days=Day(s)
E40702_Weeks=Week(s)
E40702_Months=Month(s)
E40702_Years=Year(s)
E40702_Hours_DB=1
E40702_Days_DB=2
E40702_Weeks_DB=3
E40702_Months_DB=4
E40702_Years_DB=5
E40702_Sentence=Sentence
E40702_Directions=Directions
E40702_Trial=Trial
E40702_Mention=Mention
E40702_Further_P_And_D=Further P and D
E40702_Sentence_DB=1
E40702_Directions_DB=2
E40702_Trial_DB=3
E40702_Mention_DB=4
E40702_Further_P_And_D_DB=5
E40702_Fixed_List=Fixed list
E40702_Warned_List=Warned list
E40702_Fixed_List_DB=FI
E40702_Warned_List_DB=WA

######################
# Pleas & Directions
######################
PleaTab=Pleas
DirectionTab=Directions
SaveTitle=Do you want to save?
SaveMessage=Do you want to save the changes you made to Pleas and Directions?
MultipleDefendantWarning=<html><font face=Arial>The chosen defendants currently have different selected options.<br>Selecting a new option in this section will apply to all chosen defendants.</font></html>

######################
# Directions for Case
######################
DirectionsForCase=Directions for Case

PadBorder=P & D
E40710_Form_Handed_In=Form handed in
E40710_Form_Not_Handed_In=Form NOT handed in
E40710_Form_Handed_In_DB=Y
E40710_Form_Not_Handed_In_DB=N

TimeEstimateBorder=Trial Time Estimate
E40711_Hours=Hour(s)
E40711_Days=Day(s)
E40711_Weeks=Week(s)
E40711_Months=Month(s)
E40711_Years=Year(s)
E40711_Hours_DB=1
E40711_Days_DB=2
E40711_Weeks_DB=3
E40711_Months_DB=4
E40711_Years_DB=5

DirectionsBorder=Directions

DefendantsToAttendBorder=Defendants To Attend
AppellantsToAttendBorder=Appellants To Attend

ListBorder=List
E40713_Sentence=Sentence
E40713_Directions=Directions
E40713_Trial=Trial
E40713_Mention=Mention
E40713_Further_P_And_D=Further P and D
E40713_Sentence_DB=1
E40713_Directions_DB=2
E40713_Trial_DB=3
E40713_Mention_DB=4
E40713_Further_P_And_D_DB=5

PlacedInBorder=Placed In
E40713_Fixed_List=Fixed list
E40713_Warned_List=Warned list
E40713_Fixed_List_DB=FI
E40713_Warned_List_DB=WA
WarnedListFor=For week commencing on:
OtherFor=For:

###########################
# Directions by Defendant
###########################
DirectionsByDefendant=Directions by Defendant
DefendantText=Defendant

IdentificationBorder=Identification
E40704_Defendant_Identified=Defendant identified
E40704_No_Reply=No reply
E40704_Defendant_Identified_DB=Y
E40704_No_Reply_DB=N

ArraignmentBorder=Arraignment
Arraigned=Arraigned
NotArraigned=Not arraigned
Arraigned_DB=Y
NotArraigned_DB=N

BailOrCustodyBorder=Bail or Custody
LongAdjournment= Long Adjournment
E40706_RIC=Remanded in custody
E40706_Bail_As_Before=Bail as before
E40706_Bail_Varied=Bail varied
E40706_RIC_DB=1
E40706_Bail_As_Before_DB=2
E40706_Bail_Varied_DB=3
BailNewConditions=New conditions:

CertificateOfAttendanceBorder=Certificate of Attendance
E40707_Granted=Granted
E40707_Refused=Refused
E40707_Not_Requested=Not requested
E40707_Granted_DB=1
E40707_Refused_DB=2
E40707_Not_Requested_DB=3

FormBBorder=Form B
E40708_Filed=Filed
E40708_To_Be_Filed=To be filed by
E40708_Filed_DB=Y
E40708_To_Be_Filed_DB=N

LongAdjournmentBorder = Long Adjournment