# Public Display Configuration screen resources


########################################
###                                  ###
### Public Display Rewrite Resources ###
###                                  ###
########################################

#Note non-standard lack of '.' in property names this is so that internationalization with velocity will be much cleaner.

The_Crown_Court_at = The Crown Court at

List=List

Page=Page
of=of
Last_Updated:=Last updated:

Court_Detail=Court Detail
Court List=Court List
Daily_List=Daily List
All_Court_Status=All Court Status
Summary_By_Name=Summary By Name
Jury_Current_Status=Jury Current Status
All_Case_Status=All Case Status
List=List
Detail=Detail

Judge=Judge
Court=Court
Name/Case_No.=Name/Case No.
Type=Type
Not_Before=Not Before
Case_No.=Case No.
Status=Status
Name=Name
Hearing_Type=Hearing Type
In_Court=In Court

To_be_heard=To be heard
In_Progress=In Progress
Adjourned=Adjourned
Finished=Finished

Moved_from=Moved from
Moved_to=Moved to
at_time = at
at_place = at
Case_progress_as_of=Case progress as of
Notices=Notices
unassigned=Unassigned
SEE_BELOW=SEE BELOW

No_Information_To_Display=No Information To Display
Reporting_Restrictions_apply_see_Court_Manager_for_details.=Reporting Restrictions apply see Court Manager for details.

###########################
## COURT LOG STATIC TEXT ##
###########################

Adjourned = Adjourned
Appellant =Appellant
Appellant_Case_Closed = Appellant Case Closed.
Appellant_Sworn = Appellant Sworn
Bench_Retire_to_consider_Judgment = Bench Retire to consider Judgment
Case_to_be_listed_in_week_commencing = Case to be listed in week commencing
Case_Closed = Case Closed
Case_Opened = Case Opened
Continues = Continues
Court_Closed = Court Closed
Case_Started = Case Started
Day(s) = Day(s)
Defence = Defence
Defence_Closing_Speech = Defence Closing Speech
Defendant_Sworn = Defendant Sworn
Hearing_finished = Hearing finished
Hearing_finished_for = Hearing finished for
Interpreter_Sworn = Interpreter Sworn
Judge's_directions = Judge's directions
Judgment = Judgment
Jury_retire_to_consider_verdict = Jury retire to consider verdict
Jury_Sworn_In = Jury Sworn In
Legal_Submissions = Legal Submissions
Month(s) = Month(s)
Not_Reserved = Not Reserved
Pleas_and_Directions_Hearing_on = Pleas and Directions Hearing on
Prosecution_Case_Closed = Prosecution Case Closed
Prosecution_Closing_Speech = Prosecution Closing Speech
Prosecution_Opening = Prosecution Opening
PSR_Required = PSR Required
Reporting_Restrictions._For_details_please_contact_the_Court_Manager = Reporting Restrictions. For details please contact the Court Manager
Reporting_Restrictions_Lifted = Reporting Restrictions Lifted
Respondent_Case_Opened = Respondent Case Opened
Reserved_to = Reserved to
Resume = Resume
Submissions = Submissions
Summing_Up =  Summing Up
Sworn = Sworn
Trial_Ineffective = Trial Ineffective
Trial_Time_Estimate:
Verdict_to_be_taken = Verdict to be taken
Week(s) = Week(s)
Witness = Witness
Witness_evidence_concluded = Witness evidence concluded
Witness_Number = Witness Number

# Months
Jan = Jan
Feb = Feb
Mar = Mar
Apr = Apr
May = May
Jun = Jun
Jul = Jul
Aug = Aug
Sep = Sep
Oct = Oct
Nov = Nov
Dec = Dec
- = -

#Days
Mon=Mon
Tue=Tue
Wed=Wed
Thu=Thu
Fri=Fri
Sat=Sat
Sun=Sun




