/*    ------------------------------------------------------------------
*     CREATE XHB_COURTEL_LIST TABLE
*     CREATE TRIGGERS
*/    ------------------------------------------------------------------

CREATE TABLE XHB_COURTEL_LIST 
(
  COURTEL_LIST_ID NUMBER NOT NULL 
, XML_DOCUMENT_ID NUMBER NOT NULL 
, FILENAME VARCHAR2(50) 
, SENT_TO_COURTEL VARCHAR2(1) 
, NUM_SERVERS_UPLOADED_TO NUMBER DEFAULT 0 
, NUM_SEND_ATTEMPTS NUMBER 
, LAST_ATTEMPT_DATETIME DATE 
, COURTEL_RESPONSE_SERVER_1 VARCHAR2(256) 
, COURTEL_RESPONSE_SERVER_2 VARCHAR2(256) 
, MESSAGE_TEXT VARCHAR2(256) 
, LAST_UPDATE_DATE DATE 
, CREATION_DATE DATE 
, CREATED_BY VARCHAR2(50) 
, LAST_UPDATED_BY VARCHAR2(50) 
, VERSION NUMBER DEFAULT 1
)
tablespace XHIBITD
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );
  
--Field Comments

COMMENT ON COLUMN XHB_COURTEL_LIST.COURTEL_LIST_ID IS 'XHB_COURTEL_LIST_SEQ.NEXTVAL from DUAL. Cannot be null';
COMMENT ON COLUMN XHB_COURTEL_LIST.XML_DOCUMENT_ID IS 'Foreign key linked to XHB_XML_DOCUMENT. Cannot be null';
COMMENT ON COLUMN XHB_COURTEL_LIST.FILENAME IS 'The filename generated for this document which is sent to Courtel.';
COMMENT ON COLUMN XHB_COURTEL_LIST.SENT_TO_COURTEL IS 'Y or N. Defaults to N. Y would mean this has been successfully sent.';
COMMENT ON COLUMN XHB_COURTEL_LIST.NUM_SERVERS_UPLOADED_TO IS '0, 1 or 2. Defaults to 0';
COMMENT ON COLUMN XHB_COURTEL_LIST.NUM_SEND_ATTEMPTS IS 'How many times have we attempted to send to Courtel?';
COMMENT ON COLUMN XHB_COURTEL_LIST.LAST_ATTEMPT_DATETIME IS 'When was the last time there was an attempt to send the list? Defaults to null';
COMMENT ON COLUMN XHB_COURTEL_LIST.COURTEL_RESPONSE_SERVER_1 IS 'The response from Courtel when an attempt to send to server 1 was made.';
COMMENT ON COLUMN XHB_COURTEL_LIST.COURTEL_RESPONSE_SERVER_2 IS 'The response from Courtel when an attempt to send to server 2 was made.';
COMMENT ON COLUMN XHB_COURTEL_LIST.MESSAGE_TEXT IS 'Message text generated by XHIBIT if needed. For example if network connection is down.';
COMMENT ON COLUMN XHB_COURTEL_LIST.LAST_UPDATE_DATE IS 'Standard field. The date the last time this row was updated.';
COMMENT ON COLUMN XHB_COURTEL_LIST.CREATION_DATE IS 'Standard field. The date this row was created.';
COMMENT ON COLUMN XHB_COURTEL_LIST.CREATED_BY IS 'Standard field. Which user created this row.';
COMMENT ON COLUMN XHB_COURTEL_LIST.LAST_UPDATED_BY IS 'Standard field. Which user last updated this row.';
COMMENT ON COLUMN XHB_COURTEL_LIST.VERSION IS 'Standard field. Every time this row is changed the version will increment.';  

-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE XHB_COURTEL_LIST ADD (CONSTRAINT XHB_XML_DOCUMENT_ID_FK FOREIGN KEY (XML_DOCUMENT_ID) REFERENCES XHB_XML_DOCUMENT(XML_DOCUMENT_ID));
  
-- Create/Recreate primary, unique and foreign key constraints 
alter table XHB_COURTEL_LIST
  add constraint XHB_COURTEL_LIST_PK primary key (COURTEL_LIST_ID) 
  using index 
  tablespace XHIBITD
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );


-- Grant/Revoke object privileges 
grant select, insert, update on XHB_COURTEL_LIST to PUBLIC;



/*	------------------------------------------------------------------
/*	CREATE AUDIT TABLE FOR AUD_COURTEL_LIST
*/	------------------------------------------------------------------

CREATE TABLE AUD_COURTEL_LIST 
(
  COURTEL_LIST_ID NUMBER NOT NULL 
, XML_DOCUMENT_ID NUMBER NOT NULL 
, FILENAME VARCHAR2(50) 
, SENT_TO_COURTEL VARCHAR2(1) 
, NUM_SERVERS_UPLOADED_TO NUMBER DEFAULT 0 
, NUM_SEND_ATTEMPTS NUMBER 
, LAST_ATTEMPT_DATETIME DATE 
, COURTEL_RESPONSE_SERVER_1 VARCHAR2(256) 
, COURTEL_RESPONSE_SERVER_2 VARCHAR2(256) 
, MESSAGE_TEXT VARCHAR2(256) 
, LAST_UPDATE_DATE DATE 
, CREATION_DATE DATE 
, CREATED_BY VARCHAR2(50) 
, LAST_UPDATED_BY VARCHAR2(50) 
, VERSION NUMBER 
, insert_event VARCHAR2(1)
)
tablespace AUDITD
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );


-- Grant/Revoke object privileges
grant select, insert, update on AUD_COURTEL_LIST to PUBLIC;


/*    ------------------------------------------------------------------
*     CREATE ENTRY TO ENABLE AUDITING
*/    ------------------------------------------------------------------

DELETE XHB_SYS_AUDIT WHERE TABLE_TO_AUDIT = 'XHB_COURTEL_LIST';

INSERT INTO XHB_SYS_AUDIT VALUES(NULL, 'XHB_COURTEL_LIST', 'AUD_COURTEL_LIST', 'Y');


-- Create sequence table for XHB_COURTEL_LIST
create sequence XHB_COURTEL_LIST_SEQ
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
nocache;


/*    ------------------------------------------------------------------
*     CREATE DATABASE TRIGGERS
*/    ------------------------------------------------------------------

@@XHB_COURTEL_LIST_bir_tr.sql;
@@XHB_COURTEL_LIST_bur_tr.sql;
@@xhb_xml_document_ai_tr.sql;

commit;
