#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, Xdevelopment LLP (2003)
#
#

actions = default;caseresync;terminalregistration;internetwebpages;unauthorisedcases;ref_list;crimemigration

#
# Default Mapping
#

default.request = /home
default.class = uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Case Resync
caseresync.request=/caseresync/caseResyncAdministration.jsp
caseresync.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Terminal Registration
terminalregistration.request=terminals/index.jsp
terminalregistration.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Unauthorised Cases
unauthorisedcases.request=unauthorisedcases/unauthorisedCasesAdministration.jsp
unauthorisedcases.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Internet Web Pages
internetwebpages.request=/internetwebpages/listInternetWebPages.jsp
internetwebpages.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Manage Ref Data
ref_list.request=/ref_list/editStartTimes.jsp
ref_list.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction

# Crime Migration
crimemigration.request=/crimemigration/bulkUpdate.jsp
crimemigration.class=uk.gov.courtservice.xhibit.web.admin.action.DefaultAction