#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, (2003)
#
#

responses = home;caseresync;terminalregistration;internetwebpages;unauthorisedcases;ref_list

#
# Default Mapping
#

home.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page = normal.jsp
home.skeletonBodyKey = home
home.skeletonTitleKey = home.title

# Case Resync
caseresync.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
caseresync.page=caseresync/caseResyncAdministration.jsp
caseresync.skeletonBodyKey=caseresync
caseresync.skeletonTitleKey=caseresync.title

# Terminal Registration
terminalregistration.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
terminalregistration.page=terminals/index.jsp
terminalregistration.skeletonBodyKey=terminalregistration
terminalregistration.skeletonTitleKey=terminalregistration.title

# Unauthorised Cases
unauthorisedcases.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
unauthorisedcases.page=unauthorisedcases/unauthorisedCasesAdministration.jsp
unauthorisedcases.skeletonBodyKey=unauthorisedcases
unauthorisedcases.skeletonTitleKey=unauthorisedcases.title

# Internet Web Pages
internetwebpages.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
internetwebpages.page=internetwebpages/listInternetWebPages.jsp
internetwebpages.skeletonBodyKey=internetwebpages
internetwebpages.skeletonTitleKey=internetwebpages

# Manage Ref Data
ref_list.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
ref_list.page=ref_list/editStartTimes.jsp
ref_list.skeletonBodyKey=ref_list
ref_list.skeletonTitleKey=ref_list
