/*
 * Filename:    DB_Patch_8_1_cr_tblspace_gdg.sql
 *
 * HISTORY
 * =======
 * DATE		WHO	CHANGE ID	COMMENT
 * ----         ---     ---------       -------
   18/10/2006	K SHAH			changes made to comprise release 8.1
   20/10/2006	S MILEs			added uniform size and auto management
 *
 */ 


set echo on
set term off
column filename new_value spool_filename
  select 'DBPATCH_8_1_cr_tblspace_gdg_'||
    to_char(sysdate,'YYYYMMDDHH24MI')||'.log' filename
  from dual
/
set term on
spool &&spool_filename

CREATE TABLESPACE AUDITD DATAFILE 
  '/u05/oradata/CSDBPRD3/data/AUDITD_01.dbf' SIZE 100M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL 
BLOCKSIZE 8K
UNIFORM SIZE 2M SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE GDGATED DATAFILE 
  '/u01/oradata/CSDBPRD3/data/GDGATED_01.dbf' SIZE 200M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL 
BLOCKSIZE 8K
UNIFORM SIZE 2M SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE GDGATEX DATAFILE 
  '/u06/oradata/CSDBPRD3/index/GDGATEX_01.dbf' SIZE 50M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL 
BLOCKSIZE 8K
UNIFORM SIZE 2M SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE CJSEGATED DATAFILE 
  '/u02/oradata/CSDBPRD3/data/CJSEGATED_01.dbf' SIZE 10M AUTOEXTEND OFF
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL 
BLOCKSIZE 8K
UNIFORM SIZE 2M SEGMENT SPACE MANAGEMENT AUTO;

spool off
