#!/bin/ksh

# This script will zip,backup and ftp LAA data to Staging Server
SCRIPT_HOME=/opt/moj/home/wmbroker/bin/cron/LAA
. $SCRIPT_HOME/../setEnv.sh

ROOT_FOLDER=/var/mqsi
# Folder where files are generated by App
SOURCE_FOLDER=$ROOT_FOLDER/LAA/outbound
ARS_FOLDER=$SOURCE_FOLDER/ARS
SRS_FOLDER=$SOURCE_FOLDER/SRS
TRS_FOLDER=$SOURCE_FOLDER/TRS
CSH1_STAGING_FOLDER=$ROOT_FOLDER/LAA/staging2

# Folder where files are zipped and backed up. Though this is not required, I have seen incidents where LAA have requested old files in the past
ARCHIVAL_FOLDER=$ROOT_FOLDER/LAA/outbound_archive

# Folder where files will be kept for confirmation and deletion via getConfirmationFromLAA.sh script
STAGING_FOLDER=$ROOT_FOLDER/LAA/staging
LOG_FILE_FOLDER=$SCRIPT_HOME
STAGING_SERVER=x.y.198.9
STAGING_SERVER_USERID=XHIBIT2LAA
CURRENT_TIMESTAMP=`date +"%d%m%y%H%M%S"`
CURRENT_DATE=`date +"%d%m%y"`
LOG_FILE=$LOG_FILE_FOLDER/sendDataToLAA.log
CSH1_SERVER=x.y.66.70
CSH1_USERNAME=wmbroker
dateWithTime=`date +"%d%m%y%H%M%S"`

echo "" >> $LOG_FILE
echo "Starting script at $CURRENT_TIMESTAMP" >> $LOG_FILE
#Create folders
mkdir -p $STAGING_FOLDER
mkdir -p $SOURCE_FOLDER
mkdir -p $LOG_FILE_FOLDER
mkdir -p $ARS_FOLDER
mkdir -p $SRS_FOLDER
mkdir -p $TRS_FOLDER
mkdir -p $ARCHIVAL_FOLDER
mkdir -p $ARCHIVAL_FOLDER/$CURRENT_DATE

# Delete old files
echo "Deleting old files.." >> $LOG_FILE
find $ARCHIVAL_FOLDER/ -name "XHIBIT_*.zip" -type f -mtime +100 |xargs rm
echo "Deleted old files.." >> $LOG_FILE

# Move the source files to staging folder for file name manipulation
mv $ARS_FOLDER/* $STAGING_FOLDER/
mv $SRS_FOLDER/* $STAGING_FOLDER/
mv $TRS_FOLDER/* $STAGING_FOLDER/

cd $STAGING_FOLDER/
zip -jr $ARCHIVAL_FOLDER/$CURRENT_DATE/XHIBIT_BEFORE_FORMAT_$CURRENT_TIMESTAMP.zip *.xml

cd $STAGING_FOLDER/
for i in *.xml; do
[ -f "$i" ] || continue;
  FILETYPE=""
  FILENAME=""
  DTSTAMP=""

  FILETYPE=$(echo $i| cut -c 8-10)
  DTSTAMP=$(echo $i| cut -c 14-40)

  if [ "$FILETYPE" = "trl" ]; then
    FILENAME="XHIBIT_TRLRS_$DTSTAMP.xml"
    mv $i $FILENAME
  fi

  if [ "$FILETYPE" = "alp" ]; then
    FILENAME="XHIBIT_APLRS_$DTSTAMP.xml"
    mv $i $FILENAME
  fi

  if [ "$FILETYPE" = "com" ]; then
    FILENAME="XHIBIT_COMRS_$DTSTAMP.xml"
    mv $i $FILENAME
  fi

CURRENT_TIMESTAMP=`date +"%d%m%y%H%M%S"`
echo "$CURRENT_TIMESTAMP Formatting file $STAGING_FOLDER/$FILENAME" >> $LOG_FILE
$SCRIPT_HOME/xmlConverter2.sh $FILENAME $STAGING_FOLDER/ >> $LOG_FILE 2>&1
ERROR_CODE=$?
echo "XML FORMATTER ERROR CODE: $ERROR_CODE" >> $LOG_FILE
if [ "$ERROR_CODE" != 0 ]; then
        echo "ERROR: $CURRENT_TIMESTAMP $STAGING_FOLDER/$FILENAME XML FORMATTER ERROR. error code=$ERROR_CODE" >> $LOG_FILE
fi

done

echo "" >> $LOG_FILE
echo "sftping file to CSH1 at $dateWithTime.." >> $LOG_FILE
sftp $CSH1_USERNAME@$CSH1_SERVER <<EOF
lcd $STAGING_FOLDER
cd $CSH1_STAGING_FOLDER
mput *.xml
EOF

COMMAND_OUTPUT=$?
if [ "$COMMAND_OUTPUT" != "0" ]; then
        echo "sftp to CSH1 failed with error code = $COMMAND_OUTPUT" >> $LOG_FILE
	touch /opt/moj/home/wmbroker/bin/cron/LAA/workspace/sftpfailed.txt
        exit 1
fi

echo "sftp complete.." >> $LOG_FILE

#Zip the source files
echo "Zipping files.." >> $LOG_FILE
cd $STAGING_FOLDER
zip -jr $ARCHIVAL_FOLDER/$CURRENT_DATE/XHIBIT_$CURRENT_TIMESTAMP.zip *

ERROR_CODE=$?

if [ "$ERROR_CODE" != 0 ]; then
        echo "ERROR: Unable to zip files. error code=$ERROR_CODE" >> $LOG_FILE
        exit 1
fi

echo "Zipped files.." >> $LOG_FILE

#Once ftp'ed, remove the source files
echo "Removing processed files.." >> $LOG_FILE
rm $STAGING_FOLDER/*

echo "Removed processed files.." >> $LOG_FILE
CURRENT_TIMESTAMP=`date +"%d%m%y%H%M%S"`
echo "Finishing script at $CURRENT_TIMESTAMP" >> $LOG_FILE
echo "" >> $LOG_FILE
exit 0


