## Custom properties used by the build process.
## This file should NOT be checked into CVS.

# xhibit.tx.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:O10TST1
# xhibit.jms.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:O10TST1
# exiss.tx.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:CSDBPRD2
# cjit.tx.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:CSDBPRD2
# gdgate.tx.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:CSDBPRD3
# scjsegate.jms.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:CSDBPRD3
# darts.tx.database.url=jdbc\:oracle\:thin\:@xdevdba\:1521\:CSDBPRD2

xhibit.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
xhibit.jms.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
exiss.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
cjit.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
gdgate.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
scjsegate.jms.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12
darts.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.85\:1521\:O10TST12

# xhibit.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:TSTXH1
# xhibit.jms.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:TSTXH1
# exiss.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:TSTCJ1
# cjit.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:TSTCJ1
# gdgate.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:CSDBPRD3
# scjsegate.jms.database.url=jdbc\:oracle\:thin\:@10.63.127.15\:1521\:CSDBPRD3
# darts.tx.database.url=jdbc\:oracle\:thin\:@10.63.127.16\:1521\:TSTCJ1

active.directory.host=10.63.127.14

version=8.8.9.0

disable.scheduler=true

## Comment out this line to regenerate all code that is automatically generated
#skip.generate=1

## Uncomment this line to skip the unit tests
#skip.test=1