# revision $ID:$

# These properties are for settings that the junit tests may need, but will be different for each enviroment.

#The server to which contains the midtier application
junit.xhibit.midtierserver=t3\://xdevxp???\:9001

#The usernames to make connections with
junit.xhibit.username=devuser???
junit.xhibit.password=123
