INSERT INTO XHB_CASE ( CASE_ID, CASE_NUMBER, CASE_TYPE, MAG_CONVICTION_DATE, CASE_SUB_TYPE, CASE_TITLE, CASE_DESCRIPTION, LINKED_CASE_ID, BAIL_MAG_CODE, REF_COURT_ID, COURT_ID, CHARGE_IMPORT_INDICATOR, SEVERED_IND, INDICT_RESP, DATE_IND_REC, PROS_AGENCY_REFERENCE, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, CASE_CLASS, JUDGE_REASON_FOR_APPEAL, RESULTS_VERIFIED, LENGTH_TAPE, NO_PAGE_PROS_EVIDENCE, NO_PROS_WITNESS, EST_PDH_TRIAL_LENGTH, INDICTMENT_INFO_1, INDICTMENT_INFO_2, INDICTMENT_INFO_3, INDICTMENT_INFO_4, INDICTMENT_INFO_5, INDICTMENT_INFO_6, POLICE_OFFICER_ATTENDING, CPS_CASE_WORKER, EXPORT_CHARGES, IND_CHANGE_STATUS, MAGISTRATES_CASE_REF ) VALUES ( 
2000, 20020001, 'U',  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM'), ' '
, ' ', ' ', NULL, 'U Case Title for Test Team Data', 140, 3, 'C', NULL, NULL, NULL
, NULL,  TO_Date( '07/07/2003 07:30:31 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_CASE ( CASE_ID, CASE_NUMBER, CASE_TYPE, MAG_CONVICTION_DATE, CASE_SUB_TYPE, CASE_TITLE, CASE_DESCRIPTION, LINKED_CASE_ID, BAIL_MAG_CODE, REF_COURT_ID, COURT_ID, CHARGE_IMPORT_INDICATOR, SEVERED_IND, INDICT_RESP, DATE_IND_REC, PROS_AGENCY_REFERENCE, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, CASE_CLASS, JUDGE_REASON_FOR_APPEAL, RESULTS_VERIFIED, LENGTH_TAPE, NO_PAGE_PROS_EVIDENCE, NO_PROS_WITNESS, EST_PDH_TRIAL_LENGTH, INDICTMENT_INFO_1, INDICTMENT_INFO_2, INDICTMENT_INFO_3, INDICTMENT_INFO_4, INDICTMENT_INFO_5, INDICTMENT_INFO_6, POLICE_OFFICER_ATTENDING, CPS_CASE_WORKER, EXPORT_CHARGES, IND_CHANGE_STATUS, MAGISTRATES_CASE_REF ) VALUES ( 
2001, 20020002, 'U',  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM'), ' '
, ' ', ' ', NULL, 'U Case Title for Test Team Data', 140, 3, 'C', NULL, NULL, NULL
, NULL,  TO_Date( '07/07/2003 07:30:31 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_CASE ( CASE_ID, CASE_NUMBER, CASE_TYPE, MAG_CONVICTION_DATE, CASE_SUB_TYPE, CASE_TITLE, CASE_DESCRIPTION, LINKED_CASE_ID, BAIL_MAG_CODE, REF_COURT_ID, COURT_ID, CHARGE_IMPORT_INDICATOR, SEVERED_IND, INDICT_RESP, DATE_IND_REC, PROS_AGENCY_REFERENCE, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, CASE_CLASS, JUDGE_REASON_FOR_APPEAL, RESULTS_VERIFIED, LENGTH_TAPE, NO_PAGE_PROS_EVIDENCE, NO_PROS_WITNESS, EST_PDH_TRIAL_LENGTH, INDICTMENT_INFO_1, INDICTMENT_INFO_2, INDICTMENT_INFO_3, INDICTMENT_INFO_4, INDICTMENT_INFO_5, INDICTMENT_INFO_6, POLICE_OFFICER_ATTENDING, CPS_CASE_WORKER, EXPORT_CHARGES, IND_CHANGE_STATUS, MAGISTRATES_CASE_REF ) VALUES ( 
2002, 20020003, 'U',  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM'), ' '
, ' ', ' ', NULL, 'U Case Title for Test Team Data', 140, 3, 'C', NULL, NULL, NULL
, NULL,  TO_Date( '07/07/2003 07:30:31 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:32 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 4, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_HEARING ( HEARING_ID, CASE_ID, REF_HEARING_TYPE_ID, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, COURT_ID, MP_HEARING_TYPE, LAST_CALCULATED_DURATION, HEARING_START_DATE, HEARING_END_DATE, LINKED_HEARING_ID ) VALUES ( 
400, 2000, 49,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 1, 3, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_HEARING ( HEARING_ID, CASE_ID, REF_HEARING_TYPE_ID, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, COURT_ID, MP_HEARING_TYPE, LAST_CALCULATED_DURATION, HEARING_START_DATE, HEARING_END_DATE, LINKED_HEARING_ID ) VALUES ( 
401, 2001, 49,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 1, 3, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_HEARING ( HEARING_ID, CASE_ID, REF_HEARING_TYPE_ID, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, COURT_ID, MP_HEARING_TYPE, LAST_CALCULATED_DURATION, HEARING_START_DATE, HEARING_END_DATE, LINKED_HEARING_ID ) VALUES ( 
402, 2002, 49,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM')
, 'XHIBIT', 'XHIBIT', 1, 3, NULL, NULL, NULL, NULL, NULL); 

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
500, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 400, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, 10, NULL, NULL, NULL, 'N'); 

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
501, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 400, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, 11, NULL, NULL, NULL, 'N'); 

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
502, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 401, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, 11, NULL, NULL, NULL, 'N'); 

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
503, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 402, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, 11, NULL, NULL, NULL, 'N');

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
504, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 402, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, NULL, NULL, NULL, NULL, 'N'); 

INSERT INTO XHB_SCHEDULED_HEARING ( SCHEDULED_HEARING_ID, SEQUENCE_NO, NOT_BEFORE_TIME, ORIGINAL_TIME, LISTING_NOTE, HEARING_PROGRESS, SITTING_ID, HEARING_ID, MOVED_FROM, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY, VERSION, LINKED_SH_ID, END_TIME, START_TIME, DATE_OF_HEARING, IS_CASE_ACTIVE ) VALUES ( 
505, 5,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '10/14/2003 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, NULL, 0, 17, 402, NULL,  TO_Date( '10/14/2003 04:03:46 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/07/2003 05:59:33 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'XHIBIT', 'XHIBIT'
, 29, 10, NULL, NULL, NULL, 'N'); 

 












