/*
 * Filename:    DB_Patch_7_6_CJIT_v4.sql
 *
 * System:      All Environments
 * Date:        25/10/05
 *
 */

/*
 * HISTORY
 * =======
 * DATE		WHO	CHANGE ID	COMMENT
 * ----         ---     ---------       -------
 * 07/10/05	SS			extracted CJIT changes from main 7.6 release patch to create a CJIT patch in it's own right.
 * 25/10/05	CR	v3		Changes to tablespace names & storage for CSDBPRD2 database. Removal of changes already in Production.
 * 31/10/05	CR	v4		Creation of CJI_EXPORT table, index, sequence and triggers added.
 */ 

/*
 * Changes to CJI_ table definitions, indexes and foreign keys
 *
 * Additions or deletion of CJI_ tables, indexes and foreign keys
 */



CREATE TABLE CJIT.MTBL_HTTP_CONNECTION_LOG
(
  CONNECTION_TIME  DATE,
  SYSTEM           VARCHAR2(32 BYTE),
  MAPNAME          VARCHAR2(64 BYTE),
  RETURN_CODE      VARCHAR2(192 BYTE),
  REL_ID	   VARCHAR2(250 BYTE)
)
TABLESPACE DATAD
STORAGE (INITIAL 512K NEXT 512K PCTINCREASE 0);

CREATE INDEX MTBL_HTTP_LOG_M1 ON CJIT.MTBL_HTTP_CONNECTION_LOG(CONNECTION_TIME) 
TABLESPACE DATAX 
STORAGE (INITIAL 512K NEXT 512K PCTINCREASE 0);


CREATE TABLE CJIT.MTBL_LOOKUP
(
  LOOKUP_TYPE       VARCHAR2(20)           NOT NULL,
  LOOKUP_CODE       VARCHAR2(20)           NOT NULL,
  LOOKUP1           VARCHAR2(255),
  LOOKUP2           VARCHAR2(255),
  LOOKUP3           VARCHAR2(255),
  LOOKUP4           VARCHAR2(255),
  LOOKUP5           VARCHAR2(255),
  LOOKUP6           VARCHAR2(255),
  LOOKUP7           VARCHAR2(255),
  LOOKUP8           VARCHAR2(255),
  LAST_UPDATE_DATE  DATE                        NOT NULL,
  CREATION_DATE     DATE                        NOT NULL,
  CREATED_BY        VARCHAR2(30)           NOT NULL,
  LAST_UPDATED_BY   VARCHAR2(30)           NOT NULL,
  VERSION           NUMBER(5)                   NOT NULL
)
TABLESPACE DATAD
STORAGE (INITIAL 512K NEXT 512K PCTINCREASE 0);


CREATE TABLE CJI_EXPORT (
       CJI_EXPORT_ID   NUMBER(8)  NOT NULL,
       STATUS            CHAR(1)    NULL,
       CREST_COURT_CODE          NUMBER(8)  NULL,
       EXPORT_TYPE       VARCHAR(2) NULL,
       LAST_UPDATE_DATE  DATE NOT NULL,
       CREATION_DATE     DATE NOT NULL,
       CREATED_BY        VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY   VARCHAR2(30) NOT NULL,
       VERSION           NUMBER(5) NOT NULL)
TABLESPACE DATAD
STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE CJI_EXPORT
ADD (PRIMARY KEY (CJI_EXPORT_ID)
     USING INDEX TABLESPACE DATAX
STORAGE (INITIAL 256K NEXT 256K PCTINCREASE 0));


/*
 * Changes, additions or deletion of views
 */



/*
 * Changes, additions or deletion of sequences
 */

CREATE SEQUENCE CJI_EXPORT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;


/*
 * Changes to CJI_ table triggers as a result of any CJI_ table modifications
 */


CREATE OR REPLACE TRIGGER CJIT.MTBL_LOOKUP_BIR_TR
  BEFORE INSERT
  ON CJIT.MTBL_LOOKUP 
  FOR EACH ROW
BEGIN



  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/

CREATE OR REPLACE TRIGGER CJIT.MTBL_LOOKUP_BUR_TR
  BEFORE UPDATE OR DELETE
  ON CJIT.MTBL_LOOKUP 
  FOR EACH ROW
DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';


   SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;


END;
/



CREATE OR REPLACE TRIGGER CJI_EXPORT_BIR_TR
  BEFORE INSERT
  ON CJI_EXPORT
  FOR EACH ROW

BEGIN

  IF :NEW.CJI_EXPORT_ID IS NULL THEN

    SELECT CJI_EXPORT_SEQ .NEXTVAL
    INTO   :NEW.CJI_EXPORT_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END;
/



/*
 * Changes, additions or deletion of packages/procedures/functions
 */



CREATE OR REPLACE PACKAGE CJIT.mtbl_cjse_pkg AS
    PROCEDURE insert_http_log(p_system IN VARCHAR2,
                              p_mapname IN VARCHAR2,
                              p_map_return_code IN VARCHAR2,
			      p_doc_id IN VARCHAR2);
END mtbl_cjse_pkg;
/

CREATE OR REPLACE PACKAGE BODY CJIT.mtbl_cjse_pkg AS
    PROCEDURE insert_http_log(p_system IN VARCHAR2,
                              p_mapname IN VARCHAR2,
                              p_map_return_code IN VARCHAR2,
			      p_doc_id IN VARCHAR2)
	IS
        l_date       DATE :=	SYSDATE	;				 
    BEGIN
        INSERT INTO CJIT.MTBL_HTTP_CONNECTION_LOG VALUES
	     (l_date,p_system,p_mapname,p_map_return_code,p_doc_id);
    END insert_http_log; 
END mtbl_cjse_pkg;

/

conn / as sysdba;

@@01_grants.sql

conn cjit/cjit


@@m4ora8_1_CJIT.sql
@@m4ora8_2_CJIT.sql
@@m4ora8_col_CJIT.sql




/*
 * Changes, additions or deletion of standing data
 */

insert into CJIT.cji_parameter_value values ('BITSOFFLINEInterval',60);
insert into CJIT.cji_parameter_value values ('AggOFFLINEInterval',60);
insert into CJIT.cji_parameter_value values ('CJIPOFFLINEInterval',60);
commit;


INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'CJIP_EVENT', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', ' -CERT -PKEY -CA  -KPASS',  NULL, NULL
, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'CJIT_SEND', '~HTTP~', '~PROXY~', NULL, NULL, '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', NULL,  NULL, NULL, 'CJIT', 'CJIT', 5); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'POLL_CJIP', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', '-CERT -PKEY -CA  -KPASS',  NULL, NULL, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'CJIT_STATUS', '~HTTP~', '~PROXY~', NULL, NULL, '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', NULL,  TO_Date( '07/21/2005 12:11:30 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/19/2005 02:46:03 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'CJIT', 'CJIT', 5); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'BITS_DOC_REG', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', '-CERT -PKEY -CA  -KPASS',  NULL,  NULL, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'USER_PASS', 'CJIT', '~USER~', '~PASS~', NULL, NULL, NULL, NULL, NULL, NULL
,  NULL, NULL, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'CJIT_INBOUND', '~HTTP~', '~PROXY~', NULL, NULL, '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', NULL, NULL, NULL, 'CJIT', 'CJIT', 5); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'CJIP_DOC_DEREG', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', ' -CERT -PKEY -CA  -KPASS',  NULL, NULL, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'BITS_DOC_SUBMIT', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', '-CERT -PKEY -CA  -KPASS', NULL,  NULL, 'CJIT', 'CJIT', 1); 
INSERT INTO CJIT.MTBL_LOOKUP ( LOOKUP_TYPE, LOOKUP_CODE, LOOKUP1, LOOKUP2, LOOKUP3, LOOKUP4, LOOKUP5,
LOOKUP6, LOOKUP7, LOOKUP8, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY, LAST_UPDATED_BY,
VERSION ) VALUES ( 
'HTTP_SERVER', 'POLL_BITS', '~HTTP~', '~PROXY~', '~KPASS~', '~PEM~', '~USER~', '~PASS~', '-SPROTO SSLv3 -TUNNELING -I 500', '-CERT -PKEY -CA  -KPASS', NULL, NULL, 'CJIT', 'CJIT', 1); 

commit;

/* This script will be used to update Production 7_X_v0_4  to 7_6_v0_1 */



/**********************************/
/* Update to reference new schema */
/**********************************/

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice DailyList-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 1;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice RunningList-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 2;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice WarnedList-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 3;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice FirmList-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 4;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice Indictment-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 5;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice Skeleton-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 6;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice CommunityRehabOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 7;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice CommunityPunishmentOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 8;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice CommunityPunishmentRehabOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 9;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice RemandOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 10;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice BailOrder-v4-2.xsd' 
WHERE DOCUMENT_TYPE_ID = 11;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice ImprisonmentOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 12;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice YoungOffenderOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 13;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice CommittalRecordSheet-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 14;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice AppealRecordSheet-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 15;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice TrialRecordSheet-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 16;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice BenchWarrant-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 20;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice DailyList-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 21;

UPDATE CJI_DOCUMENT_TYPE SET SCHEMA_NAME = 'http://www.courtservice.gov.uk/schemas/courtservice CommunityOrder-v4-2.xsd'
WHERE DOCUMENT_TYPE_ID = 28;

commit;

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 23, 'DLD', 'Daily List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');
INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 24, 'FLD', 'Firm List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');
INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 25, 'WLD', 'Warned List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');
INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 26, 'DLL', 'Daily List Letters', 'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');
INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 27, 'FLL', 'Firm List Letters', 'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');

COMMIT;


/**********************************/
/* Update to reference new stylesheet */
/**********************************/


Update CJI_DOCUMENT_TYPE set stylesheet_name = 
'http://www.courtservice.gov.uk/transforms/courtservice/dailyListHtml.xsl'
 where DOCUMENT_TYPE_ID =1;

Update CJI_DOCUMENT_TYPE set stylesheet_name = 
'http://www.courtservice.gov.uk/transforms/courtservice/runningListHtml.xsl'
 where DOCUMENT_TYPE_ID =2;

Update CJI_DOCUMENT_TYPE set stylesheet_name = 
'http://www.courtservice.gov.uk/transforms/courtservice/warnedListHtml.xsl'
 where DOCUMENT_TYPE_ID =3;

Update CJI_DOCUMENT_TYPE set stylesheet_name = 
'http://www.courtservice.gov.uk/transforms/courtservice/firmListHtml.xsl'
 where DOCUMENT_TYPE_ID =4;


Update CJI_DOCUMENT_TYPE set stylesheet_name = 
'http://www.courtservice.gov.uk/transforms/courtservice/dailyPrisonListHtml.xsl'
 where DOCUMENT_TYPE_ID =21;

commit;


INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 401, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 402, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 403, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 404, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 406, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 407, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 408, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 409, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 410, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 411, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 412, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 413, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 414, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 415, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 416, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 417, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 418, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 419, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 420, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 421, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 422, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 423, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 424, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 425, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 426, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 427, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 428, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 429, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 430, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 431, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 432, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 433, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 434, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 435, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 436, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 437, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 439, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 440, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 441, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 442, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 443, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 444, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 445, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 446, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 447, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 448, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 449, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 450, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 451, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 452, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 453, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 454, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 455, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 456, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 457, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 458, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 459, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 460, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 461, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 462, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 463, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 464, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 465, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 466, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 467, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 468, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 469, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 470, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 471, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 472, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 473, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 474, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 475, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 476, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 477, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 478, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 479, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 480, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 401, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 402, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 403, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 404, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 406, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 407, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 408, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 409, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 410, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 411, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 412, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 413, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 414, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 415, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 416, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 417, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 418, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 419, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 420, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 421, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 422, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 423, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 424, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 425, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 426, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 427, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 428, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 429, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 430, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 431, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 432, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 433, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 434, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 435, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 436, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 437, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 439, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 440, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 441, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 442, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 443, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 444, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 445, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 446, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 447, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 448, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 449, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 450, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 451, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 452, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 453, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 454, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 455, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 456, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 457, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 458, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 459, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 460, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 461, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 462, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 463, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 464, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 465, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 466, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 467, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 468, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 469, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 470, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 471, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 472, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 473, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 474, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 475, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 476, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 477, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 478, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 479, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 480, 'E');

commit;


/*************************/
/* update Version No     */
/*************************/


UPDATE CJI_VERSION Set
SCHEMA_VERSION = '7_6_v0_1',
last_update_date = sysdate,
Updated_by = 'XHIBIT',
Display_name = 'CJSE Database Schema 7_6_v0_1',
Display_seq = 1
Where SCHEMA_NAME = 'CJSE';

commit;







