INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
1, 'EMAIL', '-TV+ -FROM alex.brown@exgb01.exch.eds.com', 'SMTP', 'FAIL_smtp.exgb01.exch.eds.com'
, 'smtpuser', 'password', 'document',  TO_Date( '09/23/2005 11:24:19 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Xhibit', 'Xhibit', 2); 
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
2, 'EMAIL', '-TV+ ', 'MAPI', 'FAIL_smtp.exgb01.exch.eds.com', 'tzmh29', 'password'
, 'document',  TO_Date( '09/23/2005 11:24:24 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'Xhibit', 'Xhibit', 2); 
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
3, 'FTP', NULL, 'FTP', 'FTP://mercator:password@127.0.0.1/', 'mercator', 'password'
, 'InternetInterface',  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Xhibit', 'Xhibit', 1); 
INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
4, 'JMS', '-ICTXFURL t3://130.177.1.143:7001 -ICTXF  weblogic.jndi.WLInitialContextFactory -CFN jmstest.QueueConnectionFactory -QN jmstest.Queue'
, NULL, NULL, NULL, NULL, 'jmsTextMessage',  TO_Date( '07/19/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '07/19/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Xhibit', 'Xhibit'
, 1); 
COMMIT;
