USE CSDBPRD1;

-- THIS SCRIPT IS FOR THE AYLESBURY BUILDING MOVE 2018-02-17
-- PLEASE NOTE: Details need updating in this script before it is run.
-- COURT ROOM NAME TO BE DECIDED AND THE COURT ID PUT INTO THE COURT ROOM PAGES
-- NEW COURT ID's TO BE ADDED TO THE LIST OF COURT IDS ON THE ALL COURT PAGES

-- Aylesbury New Court Room
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - Court Detail - Court X', 'pd://document:78/CourtDetail:XXXX',782);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY  - Court List - Court X', 'pd://document:78/CourtList:XXXX',782);

-- Aylesbury All Court Pages
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - NEW: Daily List', 'pd://document:78/DailyList:1496,1497,1773,4608,4609,XXXX',782);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - NEW: All Court Status', 'pd://document:78/AllCourtStatus:1496,1497,1773,4608,4609,XXXX',782);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - NEW: All Case Status', 'pd://document:78/AllCaseStatus:1496,1497,1773,4608,4609,XXXX',782);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - NEW: Jury Current Status', 'pd://document:78/JuryCurrentStatus:1496,1497,1773,4608,4609,XXXX',782);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('AYLESBURY - NEW: Summary By Name', 'pd://document:78/SummaryByName:1496,1497,1773,4608,4609,XXXX',782);