XHBMessageIdentifier: int 123456
XHBRequestingSystemName: string XHIBIT
XHBRequestingSystemOrgUnitCode: int 448
XHBRequestingSystemEnvironment: string DEVELOPMENT
XHBMessageTypeType: string DL
XHBMessageTypeVersion: string 1.2
XHBMessageSchemaNamespace: string http://schemas.cjse.gov.uk/messages/receive/2006-05
XHBMessageSchemaVersion: string 1.23
XHBOriginatingSystemName: string XHIBIT
XHBOriginatingSystemOrgUnitCode: int 448
XHBOriginatingSystemEnvironment: string DEVELOPMENT
XHBCreationDateTime: 23/06/2006 18:32:07
XHBExpiryDateTime: string 23/06/2007 18:32:07
XHBBoolean: boolean true
XHBDouble: double 3.142
