// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class AddDocumentResponse {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse _return;
    
    public AddDocumentResponse() {
    }
    
    public AddDocumentResponse(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse _return) {
        this._return = _return;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse get_return() {
        return _return;
    }
    
    public void set_return(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse _return) {
        this._return = _return;
    }
}
