// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class DARTSResponse {
    protected java.lang.String code;
    protected java.lang.String message;
    
    public DARTSResponse() {
    }
    
    public DARTSResponse(java.lang.String code, java.lang.String message) {
        this.code = code;
        this.message = message;
    }
    
    public java.lang.String getCode() {
        return code;
    }
    
    public void setCode(java.lang.String code) {
        this.code = code;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
}
