// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;

public interface DARTSServicePort extends java.rmi.Remote {
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse addDocument(java.lang.String messageId, java.lang.String type, java.lang.String subType, java.lang.String document) throws 
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.Exception_Exception, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception,  java.rmi.RemoteException;
    
    public void setToken(String token);
}
