// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class DARTSService_SerializerRegistry implements SerializerConstants {
    public DARTSService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://rt.fs.documentum.emc.com/", "ServiceException");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception.class, type, serializer);
        }
        {
            QName type = new QName("http://com.synapps.mojdarts.service.com", "addDocumentResponse");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.AddDocumentResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.AddDocumentResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://com.synapps.mojdarts.service.com", "Exception");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.Exception_Exception_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.Exception_Exception.class, type, serializer);
        }
        {
            QName type = new QName("http://rt.fs.documentum.emc.com/", "DfsAttributeHolder");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder.class, type, serializer);
        }
        {
            QName type = new QName("http://com.synapps.mojdarts.service.com", "addDocument");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.AddDocument_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.AddDocument.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralFragmentSerializer(SchemaConstants.QNAME_TYPE_URTYPE, NOT_NULLABLE, "");
            registerSerializer(mapping2,javax.xml.soap.SOAPElement.class, SchemaConstants.QNAME_TYPE_URTYPE, serializer);
        }
        {
            QName type = new QName("http://com.synapps.mojdarts.service.com", "Exception");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.Exception_Type_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.Exception_Type.class, type, serializer);
        }
        {
            QName type = new QName("http://response.dfs.moj.synapps.com/", "DARTSResponse");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://rt.fs.documentum.emc.com/", "DfsExceptionHolder");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder.class, type, serializer);
        }
        {
            QName type = new QName("http://rt.fs.documentum.emc.com/", "ServiceException");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Type_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Type.class, type, serializer);
        }
        {
            QName type = new QName("http://rt.fs.documentum.emc.com/", "StackTraceHolder");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
