// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;

import javax.xml.rpc.*;

public interface DARTSService extends javax.xml.rpc.Service {
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSServicePort getDARTSServicePort() throws ServiceException;
}
