// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class DfsAttributeHolder {
    protected java.lang.String name;
    protected java.lang.String type;
    protected java.lang.String value;
    
    public DfsAttributeHolder() {
    }
    
    public DfsAttributeHolder(java.lang.String name, java.lang.String type, java.lang.String value) {
        this.name = name;
        this.type = type;
        this.value = value;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getType() {
        return type;
    }
    
    public void setType(java.lang.String type) {
        this.type = type;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
