// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class DfsExceptionHolder {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder[] attribute;
    protected java.lang.String exceptionClass;
    protected java.lang.String genericType;
    protected java.lang.String message;
    protected java.lang.String messageId;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder[] stackTrace;
    
    public DfsExceptionHolder() {
    }
    
    public DfsExceptionHolder(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder[] attribute, java.lang.String exceptionClass, java.lang.String genericType, java.lang.String message, java.lang.String messageId, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder[] stackTrace) {
        this.attribute = attribute;
        this.exceptionClass = exceptionClass;
        this.genericType = genericType;
        this.message = message;
        this.messageId = messageId;
        this.stackTrace = stackTrace;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder[] getAttribute() {
        return attribute;
    }
    
    public void setAttribute(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsAttributeHolder[] attribute) {
        this.attribute = attribute;
    }
    
    public java.lang.String getExceptionClass() {
        return exceptionClass;
    }
    
    public void setExceptionClass(java.lang.String exceptionClass) {
        this.exceptionClass = exceptionClass;
    }
    
    public java.lang.String getGenericType() {
        return genericType;
    }
    
    public void setGenericType(java.lang.String genericType) {
        this.genericType = genericType;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public java.lang.String getMessageId() {
        return messageId;
    }
    
    public void setMessageId(java.lang.String messageId) {
        this.messageId = messageId;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder[] getStackTrace() {
        return stackTrace;
    }
    
    public void setStackTrace(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.StackTraceHolder[] stackTrace) {
        this.stackTrace = stackTrace;
    }
}
