// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class Exception_Exception extends java.lang.Exception {
    private java.lang.String message;
    
    
    public Exception_Exception(java.lang.String message) {
        super(message);
        this.message = message;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
}
