// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class ServiceException_Type {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[] exceptionBean;
    protected java.lang.String message;
    protected javax.xml.soap.SOAPElement[] messageArgs;
    protected java.lang.String messageId;
    protected java.lang.String stackTraceAsString;
    
    public ServiceException_Type() {
    }
    
    public ServiceException_Type(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[] exceptionBean, java.lang.String message, javax.xml.soap.SOAPElement[] messageArgs, java.lang.String messageId, java.lang.String stackTraceAsString) {
        this.exceptionBean = exceptionBean;
        this.message = message;
        this.messageArgs = messageArgs;
        this.messageId = messageId;
        this.stackTraceAsString = stackTraceAsString;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[] getExceptionBean() {
        return exceptionBean;
    }
    
    public void setExceptionBean(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[] exceptionBean) {
        this.exceptionBean = exceptionBean;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public javax.xml.soap.SOAPElement[] getMessageArgs() {
        return messageArgs;
    }
    
    public void setMessageArgs(javax.xml.soap.SOAPElement[] messageArgs) {
        this.messageArgs = messageArgs;
    }
    
    public java.lang.String getMessageId() {
        return messageId;
    }
    
    public void setMessageId(java.lang.String messageId) {
        this.messageId = messageId;
    }
    
    public java.lang.String getStackTraceAsString() {
        return stackTraceAsString;
    }
    
    public void setStackTraceAsString(java.lang.String stackTraceAsString) {
        this.stackTraceAsString = stackTraceAsString;
    }
}
