// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ServiceException_Exception_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_exceptionBean_QNAME = new QName("", "exceptionBean");
    private static final javax.xml.namespace.QName ns4_DfsExceptionHolder_TYPE_QNAME = new QName("http://rt.fs.documentum.emc.com/", "DfsExceptionHolder");
    private CombinedSerializer ns4_myDfsExceptionHolder_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_message_QNAME = new QName("", "message");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_messageArgs_QNAME = new QName("", "messageArgs");
    private static final javax.xml.namespace.QName ns2_anyType_TYPE_QNAME = SchemaConstants.QNAME_TYPE_URTYPE;
    private CombinedSerializer ns2_ns2_anyType_TYPE_QNAME_Serializer;
    private static final javax.xml.namespace.QName ns1_messageId_QNAME = new QName("", "messageId");
    private static final javax.xml.namespace.QName ns1_stackTraceAsString_QNAME = new QName("", "stackTraceAsString");
    
    public ServiceException_Exception_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ServiceException_Exception_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns4_myDfsExceptionHolder_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder.class, ns4_DfsExceptionHolder_TYPE_QNAME);
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        ns2_ns2_anyType_TYPE_QNAME_Serializer = (CombinedSerializer)registry.getSerializer("", javax.xml.soap.SOAPElement.class, ns2_anyType_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception instance = null;
        Object exceptionBeanTemp = null;
        Object messageTemp = null;
        Object messageArgsTemp = null;
        Object messageIdTemp = null;
        Object stackTraceAsStringTemp = null;
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_exceptionBean_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_exceptionBean_QNAME))) {
                    value = ns4_myDfsExceptionHolder_LiteralSerializer.deserialize(ns1_exceptionBean_QNAME, reader, context);
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            exceptionBeanTemp = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[values.size()];
            exceptionBeanTemp = values.toArray((Object[]) exceptionBeanTemp);
        }
        else {
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_message_QNAME)) {
                messageTemp = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_message_QNAME, reader, context);
                if (messageTemp == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_messageArgs_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_messageArgs_QNAME))) {
                    value = ns2_ns2_anyType_TYPE_QNAME_Serializer.deserialize(ns1_messageArgs_QNAME, reader, context);
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            messageArgsTemp = new javax.xml.soap.SOAPElement[values.size()];
            messageArgsTemp = values.toArray((Object[]) messageArgsTemp);
        }
        else {
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_messageId_QNAME)) {
                messageIdTemp = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_messageId_QNAME, reader, context);
                if (messageIdTemp == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_stackTraceAsString_QNAME)) {
                stackTraceAsStringTemp = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_stackTraceAsString_QNAME, reader, context);
                if (stackTraceAsStringTemp == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                reader.nextElementContent();
            }
        }
        
        instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DfsExceptionHolder[])exceptionBeanTemp, (java.lang.String)messageTemp, (javax.xml.soap.SOAPElement[])messageArgsTemp, (java.lang.String)messageIdTemp, (java.lang.String)stackTraceAsStringTemp);
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.ServiceException_Exception)obj;
        
        if (instance.getExceptionBean() != null) {
            for (int i = 0; i < instance.getExceptionBean().length; ++i) {
                ns4_myDfsExceptionHolder_LiteralSerializer.serialize(instance.getExceptionBean()[i], ns1_exceptionBean_QNAME, null, writer, context);
            }
        }
        if (instance.getMessage() != null) {
            ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getMessage(), ns1_message_QNAME, null, writer, context);
        }
        if (instance.getMessageArgs() != null) {
            for (int i = 0; i < instance.getMessageArgs().length; ++i) {
                ns2_ns2_anyType_TYPE_QNAME_Serializer.serialize(instance.getMessageArgs()[i], ns1_messageArgs_QNAME, null, writer, context);
            }
        }
        if (instance.getMessageId() != null) {
            ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getMessageId(), ns1_messageId_QNAME, null, writer, context);
        }
        if (instance.getStackTraceAsString() != null) {
            ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getStackTraceAsString(), ns1_stackTraceAsString_QNAME, null, writer, context);
        }
    }
}
