// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService;


public class StackTraceHolder {
    protected java.lang.String className;
    protected java.lang.String fileName;
    protected int lineNumber;
    protected java.lang.String methodName;
    
    public StackTraceHolder() {
    }
    
    public StackTraceHolder(java.lang.String className, java.lang.String fileName, int lineNumber, java.lang.String methodName) {
        this.className = className;
        this.fileName = fileName;
        this.lineNumber = lineNumber;
        this.methodName = methodName;
    }
    
    public java.lang.String getClassName() {
        return className;
    }
    
    public void setClassName(java.lang.String className) {
        this.className = className;
    }
    
    public java.lang.String getFileName() {
        return fileName;
    }
    
    public void setFileName(java.lang.String fileName) {
        this.fileName = fileName;
    }
    
    public int getLineNumber() {
        return lineNumber;
    }
    
    public void setLineNumber(int lineNumber) {
        this.lineNumber = lineNumber;
    }
    
    public java.lang.String getMethodName() {
        return methodName;
    }
    
    public void setMethodName(java.lang.String methodName) {
        this.methodName = methodName;
    }
}
