CREATE OR REPLACE PACKAGE BODY xhb_view_schedule_pkg AS
   PROCEDURE get_schedule(results_out      OUT SYS_REFCURSOR,
                          court_id_in      IN  XHB_HEARING_LIST.court_id%TYPE,
                          start_date_in    IN  XHB_HEARING_LIST.start_date%TYPE,
                          court_room_id_in IN  XHB_SITTING.court_room_id%TYPE) AS
   BEGIN
        -- would we want to validate the passed in parameters?
        -- court_id_in and start_date_in to be not null?

        OPEN results_out FOR
            SELECT
                HEARING_LIST.START_DATE,
                  SITTING.SITTING_SEQUENCE_NO, SITTING.IS_FLOATING,
                  COURT_ROOM.COURT_ROOM_ID, COURT_ROOM.COURT_ROOM_NAME, COURT_ROOM.DESCRIPTION, COURT_ROOM.CREST_COURT_ROOM_NO, COURT_ROOM.COURT_SITE_ID, COURT_ROOM.VERSION AS COURT_ROOM_VERSION, COURT_ROOM.DISPLAY_NAME,
                  SCHEDULED_HEARING.SCHEDULED_HEARING_ID, SCHEDULED_HEARING.SEQUENCE_NO, SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME, SCHEDULED_HEARING.LISTING_NOTE, SCHEDULED_HEARING.HEARING_PROGRESS, SCHEDULED_HEARING.SITTING_ID, SCHEDULED_HEARING.HEARING_ID, SCHEDULED_HEARING.MOVED_FROM, SCHEDULED_HEARING.VERSION AS SCHEDULED_HEARING_VERSION, SCHEDULED_HEARING.LINKED_SH_ID, SCHEDULED_HEARING.END_TIME, SCHEDULED_HEARING.START_TIME, SCHEDULED_HEARING.DATE_OF_HEARING, SCHEDULED_HEARING.IS_CASE_ACTIVE,
                  CASE.CASE_ID, CASE.CASE_NUMBER, CASE.CASE_TYPE, CASE.MAG_CONVICTION_DATE, CASE.CASE_SUB_TYPE, CASE.CASE_TITLE, CASE.CASE_DESCRIPTION, CASE.LINKED_CASE_ID, CASE.BAIL_MAG_CODE, CASE.REF_COURT_ID, CASE.COURT_ID, CASE.CHARGE_IMPORT_INDICATOR, CASE.SEVERED_IND, CASE.INDICT_RESP, CASE.DATE_IND_REC, CASE.PROS_AGENCY_REFERENCE, CASE.VERSION AS CASE_VERSION, CASE.CASE_CLASS, CASE.JUDGE_REASON_FOR_APPEAL, CASE.RESULTS_VERIFIED, CASE.LENGTH_TAPE, CASE.NO_PAGE_PROS_EVIDENCE, CASE.NO_PROS_WITNESS, CASE.EST_PDH_TRIAL_LENGTH, CASE.INDICTMENT_INFO_1, CASE.INDICTMENT_INFO_2, CASE.INDICTMENT_INFO_3, CASE.INDICTMENT_INFO_4, CASE.INDICTMENT_INFO_5, CASE.INDICTMENT_INFO_6, CASE.POLICE_OFFICER_ATTENDING, CASE.CPS_CASE_WORKER, CASE.EXPORT_CHARGES, CASE.IND_CHANGE_STATUS, CASE.RECEIPT_TYPE,
                  REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
                  DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID, DEFENDANT_ON_CASE.FINAL_DRIVING_LICENCE_STATUS, DEFENDANT_ON_CASE.PTIURN, DEFENDANT_ON_CASE.IS_JUVENILE, DEFENDANT_ON_CASE.IS_MASKED, DEFENDANT_ON_CASE.MASKED_NAME, DEFENDANT_ON_CASE.CASE_ID, DEFENDANT_ON_CASE.DEFENDANT_ID, DEFENDANT_ON_CASE.VERSION AS DEFENDANT_ON_CASE_VERSION, DEFENDANT_ON_CASE.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, DEFENDANT_ON_CASE.RESULTS_VERIFIED, DEFENDANT_ON_CASE.DEFENDANT_NUMBER, DEFENDANT_ON_CASE.DATE_OF_COMMITTAL, DEFENDANT_ON_CASE.NO_OF_TICS,
                  DEFENDANT.CREST_DEFENDANT_ID, DEFENDANT.FIRST_NAME, DEFENDANT.MIDDLE_NAME, DEFENDANT.SURNAME, DEFENDANT.INITIALS, DEFENDANT.DATE_OF_BIRTH, DEFENDANT.GENDER, DEFENDANT.LAST_CONVICTION_DATE, DEFENDANT.IS_COMPANY, DEFENDANT.VERSION AS DEFENDANT_ON_VERSION, DEFENDANT.ADDRESS_ID, DEFENDANT.COURT_ID,
                  REF_JUDGE.TITLE JUDGE_TITLE, REF_JUDGE.FIRST_NAME JUDGE_FIRST_NAME, REF_JUDGE.MIDDLE_NAME JUDGE_MIDDLE_NAME, REF_JUDGE.SURNAME JUDGE_SURNAME, REF_JUDGE.REF_JUDGE_ID JUDGE_ID, REF_JUDGE.FULL_LIST_TITLE1 JUDGE_FULL_TITLE1,
                  COURT_SITE.COURT_SITE_CODE, COURT_SITE.SHORT_NAME, COURT_SITE.CREST_COURT_ID
            FROM  XHB_HEARING_LIST HEARING_LIST,
                  XHB_SITTING SITTING,
                  XHB_COURT_ROOM COURT_ROOM,
                  XHB_COURT_SITE COURT_SITE,
                  XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
                  XHB_HEARING HEARING,
                  XHB_CASE CASE,
                  XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
                  XHB_DEFENDANT DEFENDANT,
                  XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
                  XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
                  XHB_REF_JUDGE REF_JUDGE
            WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
            AND   SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
            AND   SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
            AND   SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
            AND   SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
            AND   HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
            AND   HEARING.CASE_ID = CASE.CASE_ID
            AND   SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
            AND   SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
            AND   DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
            AND   (DEFENDANT_ON_CASE.OBS_IND IS NULL OR DEFENDANT_ON_CASE.OBS_IND <> 'Y')
            AND   XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
            AND   HEARING_LIST.COURT_ID = court_id_in
            AND   HEARING_LIST.START_DATE = start_date_in
            AND   ((court_room_id_in IS NULL) OR (SITTING.COURT_ROOM_ID = court_room_id_in))
            ORDER BY court_site_code,
                     is_floating,
                     crest_court_room_no,
                     sitting_sequence_no,
                     NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time),
                     SCHEDULED_HEARING.SEQUENCE_NO;
   END get_schedule;


   PROCEDURE get_daily_list(results_out   OUT SYS_REFCURSOR,
                            court_id_in   IN  XHB_HEARING_LIST.court_id%TYPE,
                            start_date_in IN  XHB_HEARING_LIST.start_date%TYPE) AS
   BEGIN
        OPEN results_out FOR
            SELECT
                  'Daily List' DOCUMENT_NAME, SYSDATE UNIQUEID, 'Criminal' LISTCATEGORY,
                  HEARING_LIST.LIST_ID, NVL(HEARING_LIST.LIST_TYPE,'Unspecified List TYPE') DOCUMENTTYPE, HEARING_LIST.START_DATE LIST_START_DATE, HEARING_LIST.END_DATE LIST_END_DATE, LTRIM(NVL(HEARING_LIST.STATUS,'Unspecified Status') || ' ' || NVL(HEARING_LIST.EDITION_NO,-1)) LIST_VERSION, NVL(HEARING_LIST.PRINT_REFERENCE,'Unspecified Print Reference') LIST_PRINT_REF, NVL(HEARING_LIST.PUBLISHED_TIME,'01/JAN/1900') LIST_PUBLISHED, HEARING_LIST.CREST_LIST_ID LIST_CREST_LIST_ID,
                  COURTHOUSE.COURT_ID COURTHOUSE_COURT_ID, COURTHOUSE.COURT_PREFIX COURTHOUSE_TYPE, COURTHOUSE.COURT_CODE COURTHOUSE_CODE, COURTHOUSE.COURT_NAME COURTHOUSE_NAME,
                  COURTHOUSE_ADDRESS.ADDRESS_ID COURTHOUSE_ADDRESS_ID, COURTHOUSE_ADDRESS.ADDRESS_1 COURTHOUSE_ADDRESS_1, COURTHOUSE_ADDRESS.ADDRESS_2 COURTHOUSE_ADDRESS_2, COURTHOUSE_ADDRESS.ADDRESS_3 COURTHOUSE_ADDRESS_3, COURTHOUSE_ADDRESS.ADDRESS_4 COURTHOUSE_ADDRESS_4, COURTHOUSE_ADDRESS.TOWN COURTHOUSE_TOWN, COURTHOUSE_ADDRESS.COUNTY COURTHOUSE_COUNTY, COURTHOUSE_ADDRESS.POSTCODE COURTHOUSE_POSTCODE,
                  COURTSITE.COURT_SITE_ID, COURTSITE.COURT_ID COURTSITE_COURT_ID, COURTSITE.COURT_SITE_CODE COURTSITE_CODE, COURTSITE.COURT_SITE_NAME COURTSITE_NAME, COURTSITE.SHORT_NAME, COURTSITE.CREST_COURT_ID,
                  COURTSITE_ADDRESS.ADDRESS_ID COURTSITE_ADDRESS_ID, COURTSITE_ADDRESS.ADDRESS_1 COURTSITE_ADDRESS_1, COURTSITE_ADDRESS.ADDRESS_2 COURTSITE_ADDRESS_2, COURTSITE_ADDRESS.ADDRESS_3 COURTSITE_ADDRESS_3, COURTSITE_ADDRESS.ADDRESS_4 COURTSITE_ADDRESS_4, COURTSITE_ADDRESS.TOWN COURTSITE_TOWN, COURTSITE_ADDRESS.COUNTY COURTSITE_COUNTY, COURTSITE_ADDRESS.POSTCODE COURTSITE_POSTCODE,
                  COURT_ROOM.COURT_ROOM_ID, COURT_ROOM.COURT_ROOM_NAME, COURT_ROOM.DESCRIPTION, COURT_ROOM.CREST_COURT_ROOM_NO, COURT_ROOM.COURT_SITE_ID, COURT_ROOM.VERSION AS COURT_ROOM_VERSION, COURT_ROOM.DISPLAY_NAME,
                  SITTING.SITTING_ID, SITTING.SITTING_SEQUENCE_NO, SITTING.IS_FLOATING, SITTING.SITTING_NOTE, SITTING.SITTING_TIME,
                  REF_JUDGE.REF_JUDGE_ID JUDGE_ID, REF_JUDGE.TITLE JUDGE_TITLE, REF_JUDGE.FIRST_NAME JUDGE_FIRST_NAME, REF_JUDGE.MIDDLE_NAME JUDGE_MIDDLE_NAME, NVL(REF_JUDGE.SURNAME,' ') JUDGE_SURNAME, REF_JUDGE.FULL_LIST_TITLE1 JUDGE_FULL_TITLE1,
                  REF_JUSTICE1.REF_JUSTICE_ID JUSTICE1_ID, DECODE(REF_JUSTICE1.REF_JUSTICE_ID, NULL, '', REF_JUSTICE1.TITLE) JUSTICE1_TITLE, DECODE(REF_JUSTICE1.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME1, REF_JUSTICE1.JUSTICE_NAME) JUSTICE1_NAME,
                  REF_JUSTICE2.REF_JUSTICE_ID JUSTICE2_ID, DECODE(REF_JUSTICE2.REF_JUSTICE_ID, NULL, '', REF_JUSTICE2.TITLE) JUSTICE2_TITLE, DECODE(REF_JUSTICE2.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME2, REF_JUSTICE2.JUSTICE_NAME) JUSTICE2_NAME,
                  REF_JUSTICE3.REF_JUSTICE_ID JUSTICE3_ID, DECODE(REF_JUSTICE3.REF_JUSTICE_ID, NULL, '', REF_JUSTICE3.TITLE) JUSTICE3_TITLE, DECODE(REF_JUSTICE3.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME3, REF_JUSTICE3.JUSTICE_NAME) JUSTICE3_NAME,
                  REF_JUSTICE4.REF_JUSTICE_ID JUSTICE4_ID, DECODE(REF_JUSTICE4.REF_JUSTICE_ID, NULL, '', REF_JUSTICE4.TITLE) JUSTICE4_TITLE, DECODE(REF_JUSTICE4.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME4, REF_JUSTICE4.JUSTICE_NAME) JUSTICE4_NAME,
                  SCHEDULED_HEARING.SCHEDULED_HEARING_ID, SCHEDULED_HEARING.SEQUENCE_NO, SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME, SCHEDULED_HEARING.LISTING_NOTE, SCHEDULED_HEARING.HEARING_PROGRESS, SCHEDULED_HEARING.SITTING_ID, SCHEDULED_HEARING.HEARING_ID, SCHEDULED_HEARING.MOVED_FROM, SCHEDULED_HEARING.VERSION AS SCHEDULED_HEARING_VERSION, SCHEDULED_HEARING.LINKED_SH_ID, SCHEDULED_HEARING.END_TIME, SCHEDULED_HEARING.START_TIME, SCHEDULED_HEARING.DATE_OF_HEARING, SCHEDULED_HEARING.IS_CASE_ACTIVE,
                  REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
                  CASE.CASE_ID, CASE.CASE_NUMBER, CASE.CASE_TYPE, CASE.MAG_CONVICTION_DATE, CASE.CASE_SUB_TYPE, CASE.CASE_TITLE, CASE.CASE_DESCRIPTION, CASE.LINKED_CASE_ID, CASE.BAIL_MAG_CODE, CASE.REF_COURT_ID, CASE.COURT_ID, CASE.CHARGE_IMPORT_INDICATOR, CASE.SEVERED_IND, CASE.INDICT_RESP, CASE.DATE_IND_REC, CASE.PROS_AGENCY_REFERENCE, CASE.VERSION AS CASE_VERSION, CASE.CASE_CLASS, CASE.JUDGE_REASON_FOR_APPEAL, CASE.RESULTS_VERIFIED, CASE.LENGTH_TAPE, CASE.NO_PAGE_PROS_EVIDENCE, CASE.NO_PROS_WITNESS, CASE.EST_PDH_TRIAL_LENGTH, CASE.INDICTMENT_INFO_1, CASE.INDICTMENT_INFO_2, CASE.INDICTMENT_INFO_3, CASE.INDICTMENT_INFO_4, CASE.INDICTMENT_INFO_5, CASE.INDICTMENT_INFO_6, CASE.POLICE_OFFICER_ATTENDING, CASE.CPS_CASE_WORKER, CASE.EXPORT_CHARGES, CASE.IND_CHANGE_STATUS, CASE.RECEIPT_TYPE,
                  REF_COURT.REF_COURT_ID, REF_COURT.COURT_TYPE, REF_COURT.CREST_CODE, REF_COURT.COURT_SHORT_NAME, REF_COURT.COURT_FULL_NAME,
                  DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID, DEFENDANT_ON_CASE.FINAL_DRIVING_LICENCE_STATUS, DEFENDANT_ON_CASE.PTIURN, DEFENDANT_ON_CASE.IS_JUVENILE, DEFENDANT_ON_CASE.IS_MASKED, DEFENDANT_ON_CASE.MASKED_NAME, DEFENDANT_ON_CASE.CASE_ID, DEFENDANT_ON_CASE.DEFENDANT_ID, DEFENDANT_ON_CASE.VERSION AS DEFENDANT_ON_CASE_VERSION, DEFENDANT_ON_CASE.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, DEFENDANT_ON_CASE.RESULTS_VERIFIED, DEFENDANT_ON_CASE.DEFENDANT_NUMBER, DEFENDANT_ON_CASE.DATE_OF_COMMITTAL, DEFENDANT_ON_CASE.NO_OF_TICS,
                  DEFENDANT.CREST_DEFENDANT_ID, DEFENDANT.FIRST_NAME, DEFENDANT.MIDDLE_NAME, NVL(DEFENDANT.SURNAME,' ') SURNAME, DEFENDANT.INITIALS, DEFENDANT.DATE_OF_BIRTH, DEFENDANT.GENDER, DEFENDANT.LAST_CONVICTION_DATE, DEFENDANT.IS_COMPANY, DEFENDANT.VERSION AS DEFENDANT_ON_VERSION, DEFENDANT.ADDRESS_ID, DEFENDANT.COURT_ID, HEARING_LIST.START_DATE
            FROM  XHB_HEARING_LIST HEARING_LIST,
                  XHB_SITTING SITTING,
                  XHB_COURT_ROOM COURT_ROOM,
                  XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
                  XHB_HEARING HEARING,
                  XHB_CASE CASE,
                  XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
                  XHB_DEFENDANT DEFENDANT,
                  XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
                  XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
                  XHB_REF_JUDGE REF_JUDGE,
                  XHB_REF_JUSTICE REF_JUSTICE1,
                  XHB_REF_JUSTICE REF_JUSTICE2,
                  XHB_REF_JUSTICE REF_JUSTICE3,
                  XHB_REF_JUSTICE REF_JUSTICE4,
                  XHB_REF_COURT REF_COURT,
                  XHB_COURT_SITE COURTSITE,
                  XHB_COURT COURTHOUSE,
                  XHB_ADDRESS COURTSITE_ADDRESS,
                  XHB_ADDRESS COURTHOUSE_ADDRESS
            WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
            AND   SITTING.COURT_ROOM_ID(+) = COURT_ROOM.COURT_ROOM_ID
            AND   SCHEDULED_HEARING.SITTING_ID(+) = SITTING.SITTING_ID
            AND   SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID(+)
            AND   HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID(+)
            AND   HEARING.CASE_ID = CASE.CASE_ID(+)
            AND   SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
            AND   SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
            AND   DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
            AND   XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
            AND   SITTING.REF_JUSTICE1_ID = REF_JUSTICE1.REF_JUSTICE_ID(+)
            AND   SITTING.REF_JUSTICE2_ID = REF_JUSTICE2.REF_JUSTICE_ID(+)
            AND   SITTING.REF_JUSTICE3_ID = REF_JUSTICE3.REF_JUSTICE_ID(+)
            AND   SITTING.REF_JUSTICE4_ID = REF_JUSTICE4.REF_JUSTICE_ID(+)
            AND   CASE.REF_COURT_ID = REF_COURT.REF_COURT_ID(+)
            AND   COURT_ROOM.COURT_SITE_ID = COURTSITE.COURT_SITE_ID
            AND   COURTSITE.ADDRESS_ID = COURTSITE_ADDRESS.ADDRESS_ID(+)
            AND   HEARING_LIST.COURT_ID = COURTHOUSE.COURT_ID
            AND   COURTHOUSE.ADDRESS_ID = COURTHOUSE_ADDRESS.ADDRESS_ID(+)
            AND   HEARING_LIST.COURT_ID = court_id_in
            AND   HEARING_LIST.START_DATE = start_date_in
            ORDER BY court_site_code,
                     is_floating,
                     crest_court_room_no,
                     sitting_sequence_no,
                     NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time),
                     SCHEDULED_HEARING.SEQUENCE_NO;
   END get_daily_list;


PROCEDURE get_unpublished_daily_list(results_out   OUT SYS_REFCURSOR,
                            p_list_id       IN XHB_LIST.LIST_ID%TYPE,
                            show_court_list IN  XHB_CASE_ON_LIST.IS_COURT_ROOM_LIST_ENTRY%TYPE ,
                            court_id_in   IN  XHB_HEARING_LIST.court_id%TYPE) AS
                            
   BEGIN
        OPEN results_out FOR
            SELECT
                  CASE WHEN show_court_list = 0 THEN 'Daily List' ELSE  'Daily Court Room List' END DOCUMENT_NAME, SYSDATE UNIQUEID, 'Criminal' LISTCATEGORY,
                  xl.LIST_ID, NVL(xrld.REF_DATA_VALUE,'Unspecified List TYPE') DOCUMENTTYPE, xl.LIST_START_DATE LIST_START_DATE, xl.LIST_END_DATE LIST_END_DATE, LTRIM(DECODE(xl.DRAFT_OR_FINAL, 'D', 'DRAFT', 'F', 'FINAL', 'Unspecified Status') || ' ' || xl.LIST_NUMBER) LIST_VERSION, 'Unspecified Print Reference' LIST_PRINT_REF, NVL(xl.PUBLISH_DATE,'01/JAN/1900') LIST_PUBLISHED, xl.LIST_ID LIST_CREST_LIST_ID,
                  COURTHOUSE.COURT_ID COURTHOUSE_COURT_ID, COURTHOUSE.COURT_PREFIX COURTHOUSE_TYPE, COURTHOUSE.COURT_CODE COURTHOUSE_CODE, COURTHOUSE.COURT_NAME COURTHOUSE_NAME,
                  COURTHOUSE_ADDRESS.ADDRESS_ID COURTHOUSE_ADDRESS_ID, COURTHOUSE_ADDRESS.ADDRESS_1 COURTHOUSE_ADDRESS_1, COURTHOUSE_ADDRESS.ADDRESS_2 COURTHOUSE_ADDRESS_2, COURTHOUSE_ADDRESS.ADDRESS_3 COURTHOUSE_ADDRESS_3, COURTHOUSE_ADDRESS.ADDRESS_4 COURTHOUSE_ADDRESS_4, COURTHOUSE_ADDRESS.TOWN COURTHOUSE_TOWN, COURTHOUSE_ADDRESS.COUNTY COURTHOUSE_COUNTY, COURTHOUSE_ADDRESS.POSTCODE COURTHOUSE_POSTCODE,
                  COURTSITE.COURT_SITE_ID, COURTSITE.COURT_ID COURTSITE_COURT_ID, COURTSITE.COURT_SITE_CODE COURTSITE_CODE, COURTSITE.COURT_SITE_NAME COURTSITE_NAME, COURTSITE.SHORT_NAME, COURTSITE.CREST_COURT_ID, 
                  COURTSITE_ADDRESS.ADDRESS_ID COURTSITE_ADDRESS_ID, COURTSITE_ADDRESS.ADDRESS_1 COURTSITE_ADDRESS_1, COURTSITE_ADDRESS.ADDRESS_2 COURTSITE_ADDRESS_2, COURTSITE_ADDRESS.ADDRESS_3 COURTSITE_ADDRESS_3, COURTSITE_ADDRESS.ADDRESS_4 COURTSITE_ADDRESS_4, COURTSITE_ADDRESS.TOWN COURTSITE_TOWN, COURTSITE_ADDRESS.COUNTY COURTSITE_COUNTY, COURTSITE_ADDRESS.POSTCODE COURTSITE_POSTCODE,
                  COURT_ROOM.COURT_ROOM_ID, COURT_ROOM.COURT_ROOM_NAME, COURT_ROOM.DESCRIPTION, COURT_ROOM.CREST_COURT_ROOM_NO, COURT_ROOM.COURT_SITE_ID, COURT_ROOM.VERSION AS COURT_ROOM_VERSION, COURT_ROOM.DISPLAY_NAME,
                  xsol.SITTING_ON_LIST_ID SITTING_ID, xsol.SITTING_NUMBER SITTING_SEQUENCE_NO, convert_to_boolean(xcol.FLOATER_CASE) IS_FLOATING, xsol.LIST_NOTE_TEXT SITTING_NOTE, xsol.TIME_LISTED as SITTING_TIME,
                  REF_JUDGE.REF_JUDGE_ID JUDGE_ID, REF_JUDGE.TITLE JUDGE_TITLE, REF_JUDGE.FIRST_NAME JUDGE_FIRST_NAME, REF_JUDGE.MIDDLE_NAME JUDGE_MIDDLE_NAME, NVL(REF_JUDGE.SURNAME,' ') JUDGE_SURNAME, REF_JUDGE.FULL_LIST_TITLE1 JUDGE_FULL_TITLE1,
                  1 JUSTICE1_ID, null JUSTICE1_TITLE, xsol.JP1 JUSTICE1_NAME,
                  2 JUSTICE2_ID, null JUSTICE2_TITLE, xsol.JP2 JUSTICE2_NAME,
                  3 JUSTICE3_ID, null JUSTICE3_TITLE, xsol.JP3 JUSTICE3_NAME,
                  4 JUSTICE4_ID, null JUSTICE4_TITLE, xsol.JP4 JUSTICE4_NAME,
                  xcol.CASE_ON_LIST_ID SCHEDULED_HEARING_ID, xcol.SEQ_NO SEQUENCE_NO,  
                  CASE WHEN xrsc.DE_CODE LIKE 'NOT BEFORE%' OR xrsc.DE_CODE LIKE 'SITTING AT%' THEN xcol.TIME_LISTED ELSE null END NOT_BEFORE_TIME,
                  xcol.TIME_LISTED ORIGINAL_TIME, xrld_predefined_list_note.REF_DATA_VALUE || CASE WHEN(xcol.LIST_NOTE_TEXT IS NOT NULL AND xrld_predefined_list_note.REF_DATA_VALUE IS NOT NULL) THEN ',  ' END || xcol.LIST_NOTE_TEXT LISTING_NOTE,
                  0 HEARING_PROGRESS, xcol.SITTING_ON_LIST_ID SITTING_ID, xcol.CASE_ON_LIST_ID HEARING_ID, null MOVED_FROM, xcol.VERSION AS SCHEDULED_HEARING_VERSION, null LINKED_SH_ID,  null END_TIME,
                   CASE WHEN xrsc.DE_CODE LIKE 'SITTING AT%' THEN xcol.TIME_LISTED END START_TIME,
                   xcol.TIME_LISTED DATE_OF_HEARING, 'Y' IS_CASE_ACTIVE,
                  REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
                  xc.CASE_ID, xc.CASE_NUMBER, xc.CASE_TYPE, xc.MAG_CONVICTION_DATE, xc.CASE_SUB_TYPE, xc.CASE_TITLE, xc.CASE_DESCRIPTION, xc.LINKED_CASE_ID, xc.BAIL_MAG_CODE, xc.REF_COURT_ID, xc.COURT_ID, xc.CHARGE_IMPORT_INDICATOR, xc.SEVERED_IND, xc.INDICT_RESP, xc.DATE_IND_REC, xc.PROS_AGENCY_REFERENCE, xc.VERSION AS CASE_VERSION, xc.CASE_CLASS, xc.JUDGE_REASON_FOR_APPEAL, xc.RESULTS_VERIFIED, xc.LENGTH_TAPE, xc.NO_PAGE_PROS_EVIDENCE, xc.NO_PROS_WITNESS, xc.EST_PDH_TRIAL_LENGTH, xc.INDICTMENT_INFO_1, xc.INDICTMENT_INFO_2, xc.INDICTMENT_INFO_3, xc.INDICTMENT_INFO_4, xc.INDICTMENT_INFO_5, xc.INDICTMENT_INFO_6, xc.POLICE_OFFICER_ATTENDING, xc.CPS_CASE_WORKER, xc.EXPORT_CHARGES, xc.IND_CHANGE_STATUS, xc.RECEIPT_TYPE,
                  REF_COURT.REF_COURT_ID, REF_COURT.COURT_TYPE, REF_COURT.CREST_CODE, REF_COURT.COURT_SHORT_NAME, REF_COURT.COURT_FULL_NAME,
                  xdoc.DEFENDANT_ON_CASE_ID, xdoc.FINAL_DRIVING_LICENCE_STATUS, xdoc.PTIURN, xdoc.IS_JUVENILE, xdoc.IS_MASKED, xdoc.MASKED_NAME, xdoc.CASE_ID, xdoc.DEFENDANT_ID, xdoc.VERSION AS DEFENDANT_ON_CASE_VERSION, xdoc.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, xdoc.RESULTS_VERIFIED, xdoc.DEFENDANT_NUMBER, xdoc.DATE_OF_COMMITTAL, xdoc.NO_OF_TICS,
                  xd.CREST_DEFENDANT_ID, xd.FIRST_NAME, xd.MIDDLE_NAME, NVL(xd.SURNAME,' ') SURNAME, xd.INITIALS,
                  xd.DATE_OF_BIRTH, xd.GENDER, xd.LAST_CONVICTION_DATE, xd.IS_COMPANY, xd.VERSION AS DEFENDANT_ON_VERSION, xd.ADDRESS_ID, xd.COURT_ID, xl.LIST_START_DATE START_DATE
            FROM  XHB_LIST xl,
                  XHB_REF_LISTING_DATA xrld,
                  XHB_SITTING_ON_LIST xsol,
                  XHB_CASE_ON_LIST xcol,
                  XHB_DEF_ON_CASE_ON_LIST xdocol,
                  XHB_COURT_ROOM COURT_ROOM,
                  XHB_CASE xc,
                  XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
                  XHB_DEFENDANT xd,
                  XHB_DEFENDANT_ON_CASE xdoc,
                  XHB_REF_JUDGE REF_JUDGE,
                  XHB_COURT_SITE COURTSITE,
                  XHB_REF_COURT REF_COURT,
                  XHB_COURT COURTHOUSE,
                  XHB_ADDRESS COURTSITE_ADDRESS,
                  XHB_ADDRESS COURTHOUSE_ADDRESS,
                  XHB_REF_SYSTEM_CODE xrsc,
                  XHB_REF_LISTING_DATA xrld_predefined_list_note
            WHERE xl.LIST_ID = p_list_id
            AND   (xl.OBS_IND <> 'Y' or xl.OBS_IND is null)
            AND   xl.LIST_TYPE_ID = xrld.REF_LISTING_DATA_ID
            AND   xl.COURT_ID = COURTHOUSE.COURT_ID
            AND   xl.COURT_ID = court_id_in
            AND   xl.LIST_ID = xsol.LIST_ID
            AND   (xsol.OBS_IND <> 'Y' or xsol.OBS_IND is null)
            AND   (xsol.SITTING_ON_LIST_ID = xcol.SITTING_ON_LIST_ID)
            AND   (xcol.OBS_IND <> 'Y' or xcol.OBS_IND is null)
            AND   xsol.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID(+)
            AND   xsol.JUDGE_REF_ID = REF_JUDGE.REF_JUDGE_ID(+)
            AND   xcol.HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID(+)
            AND   xcol.CASE_ID = xc.CASE_ID(+)
            AND   xcol.CASE_ON_LIST_ID = xdocol.CASE_ON_LIST_ID(+)
            AND   (xdocol.OBS_IND <> 'Y' or xdocol.OBS_IND is null)
            AND   xdocol.DEFENDANT_ON_CASE_ID = xdoc.DEFENDANT_ON_CASE_ID(+)
            AND   (xdoc.OBS_IND <> 'Y' or xdoc.OBS_IND is null)
            AND   xdoc.DEFENDANT_ID = xd.DEFENDANT_ID(+)
            AND   xc.REF_COURT_ID = REF_COURT.REF_COURT_ID(+)
            AND   COURT_ROOM.COURT_SITE_ID = COURTSITE.COURT_SITE_ID
            AND   COURTSITE.ADDRESS_ID = COURTSITE_ADDRESS.ADDRESS_ID(+)
            AND   COURTHOUSE.ADDRESS_ID = COURTHOUSE_ADDRESS.ADDRESS_ID(+)
            AND   xcol.TIME_MARKING_ID =  xrsc.REF_SYSTEM_CODE_ID (+)  
            AND   xcol.LIST_NOTE_PREDEFINED_ID = xrld_predefined_list_note.REF_LISTING_DATA_ID(+)
            AND   xrld_predefined_list_note.REF_DATA_TYPE(+) = 'PREDEFINED_LIST_NOTE'
            AND   NVL(xrld_predefined_list_note.obs_ind(+), '-') <> 'Y'
            AND   (xcol.IS_COURT_ROOM_LIST_ENTRY = 'Y'
            OR    show_court_list = 0)
            UNION
          SELECT
                CASE WHEN show_court_list = 0 THEN 'Daily List' ELSE  'Daily Court Room List' END DOCUMENT_NAME, SYSDATE UNIQUEID, 'Criminal' LISTCATEGORY,
                xl.LIST_ID, NVL(xrld.REF_DATA_VALUE,'Unspecified List TYPE') DOCUMENTTYPE, xl.LIST_START_DATE LIST_START_DATE, xl.LIST_END_DATE LIST_END_DATE, LTRIM(DECODE(xl.DRAFT_OR_FINAL, 'D', 'DRAFT', 'F', 'FINAL', 'Unspecified Status') || ' ' || xl.LIST_NUMBER) LIST_VERSION, 'Unspecified Print Reference' LIST_PRINT_REF, NVL(xl.PUBLISH_DATE,'01/JAN/1900') LIST_PUBLISHED, xl.LIST_ID LIST_CREST_LIST_ID,
                COURTHOUSE.COURT_ID COURTHOUSE_COURT_ID, COURTHOUSE.COURT_PREFIX COURTHOUSE_TYPE, COURTHOUSE.COURT_CODE COURTHOUSE_CODE, COURTHOUSE.COURT_NAME COURTHOUSE_NAME,
                COURTHOUSE_ADDRESS.ADDRESS_ID COURTHOUSE_ADDRESS_ID, COURTHOUSE_ADDRESS.ADDRESS_1 COURTHOUSE_ADDRESS_1, COURTHOUSE_ADDRESS.ADDRESS_2 COURTHOUSE_ADDRESS_2, COURTHOUSE_ADDRESS.ADDRESS_3 COURTHOUSE_ADDRESS_3, COURTHOUSE_ADDRESS.ADDRESS_4 COURTHOUSE_ADDRESS_4, COURTHOUSE_ADDRESS.TOWN COURTHOUSE_TOWN, COURTHOUSE_ADDRESS.COUNTY COURTHOUSE_COUNTY, COURTHOUSE_ADDRESS.POSTCODE COURTHOUSE_POSTCODE,
                COURTSITE.COURT_SITE_ID, COURTSITE.COURT_ID COURTSITE_COURT_ID, COURTSITE.COURT_SITE_CODE COURTSITE_CODE, COURTSITE.COURT_SITE_NAME COURTSITE_NAME, COURTSITE.SHORT_NAME, COURTSITE.CREST_COURT_ID,
                COURTSITE_ADDRESS.ADDRESS_ID COURTSITE_ADDRESS_ID, COURTSITE_ADDRESS.ADDRESS_1 COURTSITE_ADDRESS_1, COURTSITE_ADDRESS.ADDRESS_2 COURTSITE_ADDRESS_2, COURTSITE_ADDRESS.ADDRESS_3 COURTSITE_ADDRESS_3, COURTSITE_ADDRESS.ADDRESS_4 COURTSITE_ADDRESS_4, COURTSITE_ADDRESS.TOWN COURTSITE_TOWN, COURTSITE_ADDRESS.COUNTY COURTSITE_COUNTY, COURTSITE_ADDRESS.POSTCODE COURTSITE_POSTCODE,
                null COURT_ROOM_ID,null COURT_ROOM_NAME, null DESCRIPTION, null CREST_COURT_ROOM_NO, xcol.COURT_SITE_ID, null AS COURT_ROOM_VERSION, null DISPLAY_NAME,
                null SITTING_ID, null SITTING_SEQUENCE_NO, convert_to_boolean(xcol.FLOATER_CASE) IS_FLOATING, NVL(COURTSITE.FLOATER_TEXT, 'The following may be taken in any court.') SITTING_NOTE, null as SITTING_TIME,
                null JUDGE_ID, null JUDGE_TITLE, null JUDGE_FIRST_NAME, null JUDGE_MIDDLE_NAME, ' ' JUDGE_SURNAME, null JUDGE_FULL_TITLE1,
                1 JUSTICE1_ID, null JUSTICE1_TITLE, null JUSTICE1_NAME,
                2 JUSTICE2_ID, null JUSTICE2_TITLE, null JUSTICE2_NAME,
                3 JUSTICE3_ID, null JUSTICE3_TITLE, null JUSTICE3_NAME,
                4 JUSTICE4_ID, null JUSTICE4_TITLE, null JUSTICE4_NAME,
                xcol.CASE_ON_LIST_ID SCHEDULED_HEARING_ID, xcol.SEQ_NO SEQUENCE_NO,  
                CASE WHEN xrsc.DE_CODE LIKE 'NOT BEFORE%' OR xrsc.DE_CODE LIKE 'SITTING AT%' THEN xcol.TIME_LISTED ELSE null END NOT_BEFORE_TIME,
                null ORIGINAL_TIME, xrld_predefined_list_note.REF_DATA_VALUE || CASE WHEN(xcol.LIST_NOTE_TEXT IS NOT NULL AND xrld_predefined_list_note.REF_DATA_VALUE IS NOT NULL) THEN ',  ' END || xcol.LIST_NOTE_TEXT LISTING_NOTE,
                0 HEARING_PROGRESS, xcol.SITTING_ON_LIST_ID SITTING_ID, xcol.CASE_ON_LIST_ID HEARING_ID, null MOVED_FROM, xcol.VERSION AS SCHEDULED_HEARING_VERSION, null LINKED_SH_ID,  null END_TIME,
                CASE WHEN xrsc.DE_CODE LIKE 'SITTING AT%' THEN xcol.TIME_LISTED END START_TIME,
                xcol.TIME_LISTED DATE_OF_HEARING, 'Y' IS_CASE_ACTIVE,
                REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
                xc.CASE_ID, xc.CASE_NUMBER, xc.CASE_TYPE, xc.MAG_CONVICTION_DATE, xc.CASE_SUB_TYPE, xc.CASE_TITLE, xc.CASE_DESCRIPTION, xc.LINKED_CASE_ID, xc.BAIL_MAG_CODE, xc.REF_COURT_ID, xc.COURT_ID, xc.CHARGE_IMPORT_INDICATOR, xc.SEVERED_IND, xc.INDICT_RESP, xc.DATE_IND_REC, xc.PROS_AGENCY_REFERENCE, xc.VERSION AS CASE_VERSION, xc.CASE_CLASS, xc.JUDGE_REASON_FOR_APPEAL, xc.RESULTS_VERIFIED, xc.LENGTH_TAPE, xc.NO_PAGE_PROS_EVIDENCE, xc.NO_PROS_WITNESS, xc.EST_PDH_TRIAL_LENGTH, xc.INDICTMENT_INFO_1, xc.INDICTMENT_INFO_2, xc.INDICTMENT_INFO_3, xc.INDICTMENT_INFO_4, xc.INDICTMENT_INFO_5, xc.INDICTMENT_INFO_6, xc.POLICE_OFFICER_ATTENDING, xc.CPS_CASE_WORKER, xc.EXPORT_CHARGES, xc.IND_CHANGE_STATUS, xc.RECEIPT_TYPE,
                REF_COURT.REF_COURT_ID, REF_COURT.COURT_TYPE, REF_COURT.CREST_CODE, REF_COURT.COURT_SHORT_NAME, REF_COURT.COURT_FULL_NAME,
                xdoc.DEFENDANT_ON_CASE_ID, xdoc.FINAL_DRIVING_LICENCE_STATUS, xdoc.PTIURN, xdoc.IS_JUVENILE, xdoc.IS_MASKED, xdoc.MASKED_NAME, xdoc.CASE_ID, xdoc.DEFENDANT_ID, xdoc.VERSION AS DEFENDANT_ON_CASE_VERSION, xdoc.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, xdoc.RESULTS_VERIFIED, xdoc.DEFENDANT_NUMBER, xdoc.DATE_OF_COMMITTAL, xdoc.NO_OF_TICS,
                xd.CREST_DEFENDANT_ID, xd.FIRST_NAME, xd.MIDDLE_NAME, NVL(xd.SURNAME,' ') SURNAME, xd.INITIALS,
                xd.DATE_OF_BIRTH, xd.GENDER, xd.LAST_CONVICTION_DATE, xd.IS_COMPANY, xd.VERSION AS DEFENDANT_ON_VERSION, xd.ADDRESS_ID, xd.COURT_ID, xl.LIST_START_DATE START_DATE
          FROM  XHB_LIST xl,
                XHB_REF_LISTING_DATA xrld,
                XHB_CASE_ON_LIST xcol,
                XHB_DEF_ON_CASE_ON_LIST xdocol,
                XHB_CASE xc,
                XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
                XHB_DEFENDANT xd,
                XHB_DEFENDANT_ON_CASE xdoc,
                XHB_COURT_SITE COURTSITE,
                XHB_COURT COURTHOUSE,
                XHB_REF_COURT REF_COURT,
                XHB_ADDRESS COURTSITE_ADDRESS,
                XHB_ADDRESS COURTHOUSE_ADDRESS,
                XHB_REF_SYSTEM_CODE xrsc,
                XHB_REF_LISTING_DATA xrld_predefined_list_note
          WHERE xl.LIST_ID = p_list_id
          AND   (xl.OBS_IND <> 'Y' or xl.OBS_IND is null)
          AND   xl.LIST_TYPE_ID = xrld.REF_LISTING_DATA_ID
          AND   xl.COURT_ID = COURTHOUSE.COURT_ID
          AND   xl.COURT_ID = court_id_in
          AND   xcol.SITTING_ON_LIST_ID IS NULL
          AND   xcol.FLOATER_CASE = 'Y' 
          AND   xl.LIST_ID = xcol.LIST_ID
          AND   (xcol.OBS_IND <> 'Y' or xcol.OBS_IND is null)
          AND   xcol.HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID(+)
          AND   xcol.CASE_ID = xc.CASE_ID(+)
          AND   xcol.CASE_ON_LIST_ID = xdocol.CASE_ON_LIST_ID(+)
          AND   (xdocol.OBS_IND <> 'Y' or xdocol.OBS_IND is null)
          AND   xdocol.DEFENDANT_ON_CASE_ID = xdoc.DEFENDANT_ON_CASE_ID(+)
          AND   (xdoc.OBS_IND <> 'Y' or xdoc.OBS_IND is null)
          AND   xdoc.DEFENDANT_ID = xd.DEFENDANT_ID(+)
         AND   xc.REF_COURT_ID = REF_COURT.REF_COURT_ID(+)
          AND   xcol.COURT_SITE_ID = COURTSITE.COURT_SITE_ID
          AND   COURTSITE.ADDRESS_ID = COURTSITE_ADDRESS.ADDRESS_ID(+)
          AND   COURTHOUSE.ADDRESS_ID = COURTHOUSE_ADDRESS.ADDRESS_ID(+)
          AND   xcol.TIME_MARKING_ID =  xrsc.REF_SYSTEM_CODE_ID (+)  
          AND   xcol.LIST_NOTE_PREDEFINED_ID = xrld_predefined_list_note.REF_LISTING_DATA_ID(+)
          AND   xrld_predefined_list_note.REF_DATA_TYPE(+) = 'PREDEFINED_LIST_NOTE'
          AND   NVL(xrld_predefined_list_note.obs_ind(+), '-') <> 'Y'
          AND   (xcol.IS_COURT_ROOM_LIST_ENTRY = 'Y'
          OR    show_court_list = 0)
          
          ORDER BY COURTSITE_CODE,
                   IS_FLOATING,
                   crest_court_room_no,
                   SITTING_SEQUENCE_NO,
                   SEQ_NO; 
   END get_unpublished_daily_list;
   
   FUNCTION convert_to_boolean(p_yn_field VARCHAR2) RETURN NUMBER
   IS
    p_return_bool NUMBER;
   BEGIN
      SELECT CASE WHEN p_yn_field = 'Y' THEN 1
      ELSE  0
      END
      INTO p_return_bool
      FROM DUAL ;
      RETURN p_return_bool;
      
  END convert_to_boolean;    


   -- Function to acquire the daily list (see the "daily_list_with_judge_v") ordered as
   -- per requirements, and filtered by court id and date.
   FUNCTION get_daily_list_with_judge(p_court_id_in   IN XHB_HEARING_LIST.court_id%TYPE,
                                      p_start_date_in IN XHB_HEARING_LIST.start_date%TYPE)
                                      RETURN SYS_REFCURSOR
   IS
       l_return_cursor SYS_REFCURSOR;
   BEGIN
       OPEN l_return_cursor FOR
           -- daily list including the judge details...
           SELECT dlwjv.*
           FROM   DAILY_LIST_WITH_JUDGE_V dlwjv
           WHERE  dlwjv.court_id   = p_court_id_in
           AND    dlwjv.start_date = p_start_date_in
           ORDER BY court_site_code,
                    floating,
                    crest_court_room_no,
                    sitting_sequence_no,
                    not_before_time,
                    sequence_no,
                    scheduled_hearing_id;
       RETURN l_return_cursor;
   END get_daily_list_with_judge;


   -- Function to acquire the daily list (see the "daily_list_with_judge_v") with the
   -- additional information required to see if skeleton schedule exists, the schedule has been
   -- issued, and if there are any witnesses on the case. .Ordered as per requirements, and
   -- filtered by court id and date.
   FUNCTION get_daily_list_with_witness(p_court_id_in   IN XHB_HEARING_LIST.court_id%TYPE,
                                        p_start_date_in IN XHB_HEARING_LIST.start_date%TYPE)
                                        RETURN SYS_REFCURSOR
   IS
       l_return_cursor SYS_REFCURSOR;
   BEGIN
       OPEN l_return_cursor FOR
           -- daily list including witness and judge details...
           SELECT dlwjv.*,
                  DECODE(xss.deliverable, 'Y', DECODE(xsds.code, 'NOTREADY', NULL, 'Y'), 'Y') AS issued,
                  NVL2(xss.skeleton_id, 'Y', NULL) AS skeleton_schedule,
                  NVL2(xss.skeleton_id, DECODE((SELECT COUNT(1) FROM XHB_WITNESS WHERE case_id = xss.case_id AND ROWNUM = 1), 1, 'Y'), NULL) AS witnesses
           FROM   DAILY_LIST_WITH_JUDGE_V      dlwjv,
                  XHB_SKELETON_SCHEDULE        xss,
                  XHB_SKELETON_DELIVERY_STATUS xsds
           WHERE  dlwjv.case_id = xss.case_id(+)
           AND    xss.skeleton_delivery_status_id = xsds.skeleton_delivery_status_id(+)
           AND    dlwjv.court_id   = p_court_id_in
           AND    dlwjv.start_date = p_start_date_in
           ORDER BY court_site_code,
                    floating,
                    crest_court_room_no,
                    sitting_sequence_no,
                    not_before_time,
                    sequence_no,
                    scheduled_hearing_id;
       RETURN l_return_cursor;
   END get_daily_list_with_witness;


   -- Function to acquire the daily list (see the "daily_list_v") ordered by the formatted
   -- defendant name, as per requirements, and filtered by court id and date.
   FUNCTION get_daily_list_by_defendant(p_court_id_in   IN XHB_HEARING_LIST.court_id%TYPE,
                                        p_start_date_in IN XHB_HEARING_LIST.start_date%TYPE)
                                        RETURN SYS_REFCURSOR
   IS
       l_return_cursor SYS_REFCURSOR;
   BEGIN
       OPEN l_return_cursor FOR
           -- daily list ordered by defendant...
           SELECT dlwjv.*
           FROM   DAILY_LIST_V dlwjv
           WHERE  dlwjv.court_id   = p_court_id_in
           AND    dlwjv.start_date = p_start_date_in
           ORDER BY def_name;
       RETURN l_return_cursor;
   END get_daily_list_by_defendant;

   -- Function to acquire the list, based on its type, on the first day after
   -- the start date passed in, but the last one added to the table for that day
   FUNCTION get_next_list_by_type(p_court_id_in   IN XHB_XML_DOCUMENT.court_id%TYPE,
                                  p_start_date_in IN XHB_XML_DOCUMENT.date_created%TYPE,
                                  p_list_type_in  IN XHB_XML_DOCUMENT.document_type%TYPE)
                                  RETURN SYS_REFCURSOR
   IS
       l_return_cursor SYS_REFCURSOR;
   BEGIN
       OPEN l_return_cursor FOR
           SELECT XML_DOCUMENT_ID, XML_DOCUMENT_CLOB_ID
           FROM   XHB_XML_DOCUMENT
           WHERE  court_id   = p_court_id_in
           AND    date_created > p_start_date_in
           AND    document_type = p_list_type_in
           ORDER BY date_created ASC, creation_date DESC;
       RETURN l_return_cursor;
   END get_next_list_by_type;

END xhb_view_schedule_pkg;
/
show errors
