CREATE OR REPLACE TRIGGER XHB_PDDA_MESSAGE_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_PDDA_MESSAGE
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_PDDA_MESSAGE') = 1) THEN
	INSERT INTO AUD_PDDA_MESSAGE
	(PDDA_MESSAGE_ID,
	COURT_ID,
	COURT_ROOM_ID,
	PDDA_MESSAGE_TYPE_ID,
	PDDA_MESSAGE_DATA_ID,
	PDDA_BATCH_ID,
	TIME_SENT,
	CP_DOCUMENT_NAME,
	CP_DOCUMENT_STATUS,
	CP_RESPONSE_GENERATED,
	CPP_STAGING_INBOUND_ID,
	ERROR_MESSAGE,
	OBS_IND,
	LAST_UPDATE_DATE,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATED_BY,
	VERSION,
	INSERT_EVENT)
	VALUES 
	(:OLD.PDDA_MESSAGE_ID,
	:OLD.COURT_ID,
	:OLD.COURT_ROOM_ID,
	:OLD.PDDA_MESSAGE_TYPE_ID,
	:OLD.PDDA_MESSAGE_DATA_ID,
	:OLD.PDDA_BATCH_ID,
	:OLD.TIME_SENT,
	:OLD.CP_DOCUMENT_NAME,
	:OLD.CP_DOCUMENT_STATUS,
	:OLD.CP_RESPONSE_GENERATED,
	:OLD.CPP_STAGING_INBOUND_ID,
	:OLD.ERROR_MESSAGE,
	:OLD.OBS_IND,
	:OLD.LAST_UPDATE_DATE,
	:OLD.CREATION_DATE,
	:OLD.CREATED_BY,
	:OLD.LAST_UPDATED_BY,
	:OLD.VERSION,
	l_trig_event);
  END IF;

END;
/
