INSERT INTO XHB_REF_STATUS_CODES
(STATUS_CODE_TYPE, STATUS_CODE, STATUS_CODE_DESCRIPTION)
SELECT subqry.* FROM (
SELECT 'PDDA_BATCH' STATUS_CODE_TYPE, 'NS' STATUS_CODE, 'Not Sent' STATUS_CODE_DESCRIPTION FROM DUAL UNION
SELECT 'PDDA_BATCH' STATUS_CODE_TYPE, 'RS' STATUS_CODE, 'Ready to be Sent' STATUS_CODE_DESCRIPTION FROM DUAL UNION
SELECT 'PDDA_BATCH' STATUS_CODE_TYPE, 'BF' STATUS_CODE, 'Batch Failed' STATUS_CODE_DESCRIPTION FROM DUAL UNION
SELECT 'PDDA_BATCH' STATUS_CODE_TYPE, 'BS' STATUS_CODE, 'Batch Success' STATUS_CODE_DESCRIPTION FROM DUAL
) subqry 
WHERE NOT EXISTS (SELECT NULL FROM XHB_REF_STATUS_CODES x1 WHERE x1.STATUS_CODE = subqry.STATUS_CODE AND ROWNUM = 1);

commit;
/