INSERT INTO XHB_CONFIG_PROP
(CONFIG_PROP_ID, PROPERTY_NAME,PROPERTY_VALUE)
SELECT XHB_CONFIG_PROP_SEQ.NEXTVAL, qry.* FROM (
SELECT 'PDDA_SWITCHER' PROPERTY_NAME, '3' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_HOSTNAME' PROPERTY_NAME, 'TO_BE_SET' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_USERNAME' PROPERTY_NAME, 'XhibittoBAISPDDA' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_PASSWORD' PROPERTY_NAME, 'somepass' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_UPLOAD_LOCATION' PROPERTY_NAME, '/' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_BATCH_MAX_SIZE' PROPERTY_NAME, '30' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_SFTP_BATCH_TIME_TO_WAIT' PROPERTY_NAME, '120' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_MAX_RESENDS' PROPERTY_NAME, '3' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_CP_SFTP_USERNAME' PROPERTY_NAME, 'BAISXhibittoPDDA' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_CP_SFTP_PASSWORD' PROPERTY_NAME, 'somepass' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_CP_SFTP_UPLOAD_LOCATION' PROPERTY_NAME, '/' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_BAIS_CP_MAX_NUM_MESSAGES_TO_RETRIEVE' PROPERTY_NAME, '20' PROPERTY_VALUE FROM DUAL UNION
SELECT 'PDDA_SWITCHER_DESC' PROPERTY_NAME, '1=Send to PDDA only; 2=Send to PDDA but continue to process in XHIBIT; 3=Do not send to PDDA, process in XHIBIT only' PROPERTY_VALUE FROM DUAL
) qry
WHERE NOT EXISTS (SELECT NULL FROM XHB_CONFIG_PROP x1 WHERE x1.PROPERTY_NAME = qry.PROPERTY_NAME);

COMMIT;
/