/*    ------------------------------------------------------------------
*     CREATE XHB_PDDA_MESSAGE TABLE
*     CREATE TRIGGERS
*/    ------------------------------------------------------------------

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE XHB_PDDA_MESSAGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE XHB_PDDA_MESSAGE (
	PDDA_MESSAGE_ID			NUMBER(8) NOT NULL,
	COURT_ID				NUMBER(8) NOT NULL,
	COURT_ROOM_ID			NUMBER(8),
	PDDA_MESSAGE_GUID		VARCHAR2(36),
	PDDA_MESSAGE_TYPE_ID	NUMBER(8),
	PDDA_MESSAGE_DATA_ID	NUMBER(10),
	PDDA_BATCH_ID			NUMBER(8),
	TIME_SENT				DATE,
	CP_DOCUMENT_NAME		VARCHAR2(50),
	CP_DOCUMENT_STATUS		VARCHAR2(8),
	CP_RESPONSE_GENERATED	VARCHAR2(1),
	CPP_STAGING_INBOUND_ID	NUMBER(8),
	ERROR_MESSAGE			VARCHAR2(4000),
	OBS_IND					VARCHAR2(1),
	LAST_UPDATE_DATE		DATE NOT NULL,
	CREATION_DATE			DATE NOT NULL,
	CREATED_BY				VARCHAR2(30) NOT NULL,
	LAST_UPDATED_BY			VARCHAR2(30) NOT NULL,
	VERSION					NUMBER(5) DEFAULT 1,	
	CONSTRAINT PDDAMSG_COURT_FK
	FOREIGN KEY(COURT_ID)
	REFERENCES XHB_COURT(COURT_ID),
	CONSTRAINT PDDAMSG_COURT_ROOM_FK
	FOREIGN KEY(COURT_ROOM_ID)
	REFERENCES XHB_COURT_ROOM(COURT_ROOM_ID),
	CONSTRAINT PDDAMSG_MESSAGE_TYPE_FK
	FOREIGN KEY(PDDA_MESSAGE_TYPE_ID)
	REFERENCES XHB_REF_PDDA_MESSAGE_TYPE(REF_PDDA_MESSAGE_TYPE_ID),
	CONSTRAINT PDDAMSG_BATCH_FK
	FOREIGN KEY(PDDA_BATCH_ID)
	REFERENCES XHB_PDDA_BATCH(PDDA_BATCH_ID),
	CONSTRAINT PDDAMSG_CPPSTAGING_FK
	FOREIGN KEY(CPP_STAGING_INBOUND_ID)
	REFERENCES XHB_CPP_STAGING_INBOUND(CPP_STAGING_INBOUND_ID)
)
TABLESPACE XHIBITD
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );

-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE XHB_PDDA_MESSAGE
  ADD (CONSTRAINT XHB_PDDA_MESSAGE_PK PRIMARY KEY (PDDA_MESSAGE_ID) 
       USING INDEX TABLESPACE XHIBITX
       STORAGE (INITIAL 1M
                NEXT 1M
                PCTINCREASE 0));
				
-- Add indexes
CREATE INDEX XHB_PDDAMSG_BATCH_IDX ON XHB_PDDA_MESSAGE(PDDA_BATCH_ID)
TABLESPACE XHIBITX STORAGE (INITIAL 256K NEXT 256K PCTINCREASE 0);

CREATE INDEX XHB_PDDAMSG_TIME_SENT_IDX ON XHB_PDDA_MESSAGE(TIME_SENT)
TABLESPACE XHIBITX STORAGE (INITIAL 256K NEXT 256K PCTINCREASE 0);

-- Grant/Revoke object privileges 
GRANT SELECT, INSERT, UPDATE ON XHB_PDDA_MESSAGE TO PUBLIC;


/*	------------------------------------------------------------------
/*	CREATE AUDIT TABLE FOR AUD_PDDA_MESSAGE
*/	------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AUD_PDDA_MESSAGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
CREATE TABLE AUD_PDDA_MESSAGE
(
	PDDA_MESSAGE_ID			NUMBER(8) NOT NULL,
	COURT_ID				NUMBER(8) NOT NULL,
	COURT_ROOM_ID			NUMBER(8),
	PDDA_MESSAGE_GUID		VARCHAR2(36),
	PDDA_MESSAGE_TYPE_ID	NUMBER(8),
	PDDA_MESSAGE_DATA_ID	NUMBER(10),
	PDDA_BATCH_ID			NUMBER(8),
	TIME_SENT				DATE,
	CP_DOCUMENT_NAME		VARCHAR2(50),
	CP_DOCUMENT_STATUS		VARCHAR2(8),
	CP_RESPONSE_GENERATED	VARCHAR2(1),
	CPP_STAGING_INBOUND_ID	NUMBER(8),
	ERROR_MESSAGE			VARCHAR2(4000),
	OBS_IND					VARCHAR2(1),
	LAST_UPDATE_DATE		DATE NOT NULL,
	CREATION_DATE			DATE NOT NULL,
	CREATED_BY				VARCHAR2(30) NOT NULL,
	LAST_UPDATED_BY			VARCHAR2(30) NOT NULL,
	VERSION					NUMBER(5) DEFAULT 1,
	INSERT_EVENT			VARCHAR2(1)
)
TABLESPACE AUDITD
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    minextents 1
    maxextents unlimited
  );

-- Grant/Revoke object privileges
GRANT SELECT, INSERT, UPDATE ON AUD_PDDA_MESSAGE TO PUBLIC;


/*    ------------------------------------------------------------------
*     CREATE ENTRY TO ENABLE AUDITING
*/    ------------------------------------------------------------------

DELETE XHB_SYS_AUDIT WHERE TABLE_TO_AUDIT = 'XHB_PDDA_MESSAGE';

INSERT INTO XHB_SYS_AUDIT VALUES(NULL, 'XHB_PDDA_MESSAGE', 'AUD_PDDA_MESSAGE', 'Y');


/*	------------------------------------------------------------------
/*	CREATE sequence TABLE FOR XHB_PDDA_MESSAGE
*/	------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE XHB_PDDA_MESSAGE_SEQ';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Create sequence table for XHB_PDDA_MESSAGE
CREATE SEQUENCE XHB_PDDA_MESSAGE_SEQ
minvalue 1
maxvalue 999999999999999999999999999
start with 1
increment by 1
nocache;


/*    ------------------------------------------------------------------
*     CREATE DATABASE TRIGGERS
*/    ------------------------------------------------------------------

@xhb_pdda_message_bir_tr.sql;
@xhb_pdda_message_bur_tr.sql;

COMMIT;