CREATE OR REPLACE PACKAGE XHB_PUBLIC_DISPLAY_PKG AS
    -- Require this to be declared in the header as we are calling directly
    -- from SQL in the strored procedures
    FUNCTION convert_string(p_str_in IN VARCHAR2) RETURN xhb_number_table_typ DETERMINISTIC;
    FUNCTION get_log_entry_rowid(p_scheduled_hearing_id_in IN NUMBER,
                                 p_defendant_on_case_id_in IN NUMBER) RETURN ROWID;

    PROCEDURE GET_SUMMARY_BY_NAME (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_SUMMARY_BY_NAME_U (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_JURY_STATUS_DAILY_LIST (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_JURY_STATUS_DAILY_LIST_U (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_COURT_LIST (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_ALL_COURT_STATUS (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_ALL_COURT_STATUS_THIN (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_COURT_DETAIL (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_ID_IN    IN  XHB_COURT_ROOM.COURT_ROOM_ID%TYPE);
    PROCEDURE GET_PUBLIC_NOTICES (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ROOM_ID_IN    IN  XHB_COURT_ROOM.COURT_ROOM_ID%TYPE);
    PROCEDURE GET_ACTIVE_CASES_IN_ROOM (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        LIST_ID_IN      IN  XHB_HEARING_LIST.LIST_ID%TYPE,
        COURT_ROOM_ID_IN    IN  XHB_COURT_ROOM.COURT_ROOM_ID%TYPE,
        SCHEDULED_HEARING_ID_IN IN  XHB_SCHEDULED_HEARING.SCHEDULED_HEARING_ID%TYPE);
    PROCEDURE GET_ALL_CASE_STATUS (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_ALL_CASE_STATUS_U (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_ID_IN     IN  XHB_HEARING_LIST.court_id%TYPE,
        START_DATE_IN       IN  XHB_HEARING_LIST.start_date%TYPE,
        COURT_ROOM_IDS_IN   IN  VARCHAR2);
    PROCEDURE GET_VIP_DISPLAY_DOCS_FOR_SITE (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_SITE_ID_IN    IN  XHB_COURT_SITE.court_site_id%TYPE);
    PROCEDURE GET_VIP_COURT_ROOMS_FOR_SITE (
        RESULTS_OUT     OUT SYS_REFCURSOR,
        COURT_SITE_ID_IN    IN  XHB_COURT_SITE.court_site_id%TYPE);    
    FUNCTION GET_GUID RETURN VARCHAR2;
END XHB_PUBLIC_DISPLAY_PKG;
/
show errors