create or replace TRIGGER XHB_COURTEL_LIST_BIR_TR
  BEFORE INSERT 
  ON XHB_COURTEL_LIST
  FOR EACH ROW

BEGIN

  IF :NEW.COURTEL_LIST_ID IS NULL THEN

    SELECT XHB_COURTEL_LIST_SEQ.NEXTVAL
    INTO   :NEW.COURTEL_LIST_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;
  
  IF(:NEW.LAST_ATTEMPT_DATETIME IS NULL) THEN
    SELECT SYSDATE
    INTO :NEW.LAST_ATTEMPT_DATETIME
    FROM DUAL;
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END XHB_COURTEL_LIST_BIR_TR;
/
