<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="ThinClientShared">

    <description>
        This project contains the files to provide shared funtcionality
        for the thin client cjo applications.
    </description>

    <import file="./../../tools/ant/framework.xml" />

    <property name="project.type.controller.bean"      value="true" />
    <property name="project.type.requires.compilation" value="true" />

    <!--
      =======================================================================
        Framework Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="Framework.jar" />
                <include name="Config.jar" />
            </fileset>
        </path>
        <property name="controller.jar.file.client.includes" value="**/*Factory.class, **/*Impl.class, **/*Delegate*.class, **/*Exception.class"/>
    </target>

    <!--
      =======================================================================
        Release Override
      =======================================================================
      -->
    <target name="release" unless="skip.release" depends="framework.release">
        <log target="release"/>
        <copy todir="${build.dest.dir}">
            <fileset dir="${client.build.dir}" />
        </copy>
    </target>

</project>
