/*
 * Filename:    Xhibit_DB_Patch_8_6_0_1.sql
 *
 *
 * PLEASE CHANGE :  Insert relevant release number in X_X - in Filename above, for generating logfile name
 *                  and in xhb_version updates.
 *
 *
 * HISTORY
 * =======
 * DATE		WHO		COMMENT
 * ----         ---     	-------
 *  06/09/2012	B Hingston	Changes for DB release 8.6.0.1
 *
 */


set echo on
set term off
column filename new_value spool_filename
  select 'Xhibit_DB_Patch_8_6_0_1_'||
    to_char(sysdate,'YYYYMMDDHH24MI')||'.log' filename
  from dual
/
set term on
spool &&spool_filename

@@xhb_post_merc_ref_data_pkg_b.sql


INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (16, 'IO5035C', 0, 'TEST', 'TEST',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Imprisonment Order(5035C)');

INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (17, 'SUS', 0, 'TEST', 'TEST',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Suspended Sentence Order (6057)');

INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (18, 'COMSENT', 0, 'TEST', 'TEST',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Community Order');

INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (19, 'YO5044C', 0, 'TEST', 'TEST',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Young Offenders Order - under 18 (5044C)');

INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (20, 'YO5044D', 0, 'TEST', 'TEST',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Young Offenders Order - 18 to 21 (5044D)');

UPDATE XHB_ORDER_TYPE SET CODE = 'COMSENT_pre_LASBO', DESCRIPTION = 'Community Order_pre_LASBO' WHERE ORDER_TYPE_ID = 9;

UPDATE XHB_ORDER_TYPE SET CODE = 'SUS_pre_LASBO', DESCRIPTION = 'Suspended Sentence Order (6057)_pre_LASBO' WHERE ORDER_TYPE_ID = 10;

UPDATE XHB_ORDER_TYPE SET CODE = 'IO5035C_pre_LASBO', DESCRIPTION = 'Imprisonment Order(5035C)_pre_LASBO' WHERE ORDER_TYPE_ID = 11;

UPDATE XHB_ORDER_TYPE SET CODE = 'YO5044C_pre_LASBO', DESCRIPTION = 'Young Offenders Order - under 18 (5044C)_pre_LASBO' WHERE ORDER_TYPE_ID = 12;

UPDATE XHB_ORDER_TYPE SET CODE = 'YO5044D_pre_LASBO', DESCRIPTION = 'Young Offenders Order - 18 to 21 (5044D)_pre_LASBO' WHERE ORDER_TYPE_ID = 13;

INSERT INTO XHB_ORDER_TEMPLATE VALUES (18,  '/metadata/OrderFOPTransform.xslt', '/metadata/COMSENT_Narrative.xml', '/metadata/COMSENTOrderTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 18, NULL);

INSERT INTO XHB_ORDER_TEMPLATE VALUES (17,  '/metadata/OrderFOPTransform.xslt', '/metadata/SuspendedSentenceOrder_Narrative.xml', '/metadata/SuspendedSentenceOrderTemplate.xml',  1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 17, NULL);

INSERT INTO XHB_ORDER_TEMPLATE VALUES (16, '/metadata/OrderFOPTransform.xslt', '/metadata/ImprisonmentOrder5035C_Narrative.xml', '/metadata/ImprisonmentOrder5035CTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 16, NULL);

INSERT INTO XHB_ORDER_TEMPLATE VALUES (19, '/metadata/OrderFOPTransform.xslt', '/metadata/YoungOffendersOrder5044C_Narrative.xml', '/metadata/YoungOffendersOrder5044CTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 19, NULL);

INSERT INTO XHB_ORDER_TEMPLATE VALUES (20, '/metadata/OrderFOPTransform.xslt', '/metadata/YoungOffendersOrder5044D_Narrative.xml', '/metadata/YoungOffendersOrder5044DTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 20, NULL);

UPDATE XHB_ORDER_TEMPLATE SET NARRATIVE_TEMPLATE_NAME = '/metadata/COMSENT_Narrative_pre_LASBO.xml', EDITOR_TEMPLATE_NAME = '/metadata/COMSENTOrderTemplate_pre_LASBO.xml', OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID = 9;

UPDATE XHB_ORDER_TEMPLATE SET NARRATIVE_TEMPLATE_NAME = '/metadata/SuspendedSentenceOrder_Narrative_pre_LASBO.xml', EDITOR_TEMPLATE_NAME = '/metadata/SuspendedSentenceOrderTemplate_pre_LASBO.xml', OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID = 10;

UPDATE XHB_ORDER_TEMPLATE SET NARRATIVE_TEMPLATE_NAME = '/metadata/ImprisonmentOrder5035C_Narrative_pre_LASBO.xml', EDITOR_TEMPLATE_NAME = '/metadata/ImprisonmentOrder5035CTemplate_pre_LASBO.xml', OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID = 11;

UPDATE XHB_ORDER_TEMPLATE SET NARRATIVE_TEMPLATE_NAME = '/metadata/YoungOffendersOrder5044C_Narrative_pre_LASBO.xml', EDITOR_TEMPLATE_NAME = '/metadata/YoungOffendersOrder5044CTemplate_pre_LASBO.xml', OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID = 12;

UPDATE XHB_ORDER_TEMPLATE SET NARRATIVE_TEMPLATE_NAME = '/metadata/YoungOffendersOrder5044D_Narrative_pre_LASBO.xml', EDITOR_TEMPLATE_NAME = '/metadata/YoungOffendersOrder5044DTemplate_pre_LASBO.xml', OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID = 13;

  -- Custodial/Young Offender Order for 18-21s - not replaced
INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (20, 20, NULL, 0);

  -- Custodial/Young Offender Order for under 18s - not replaced
INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (19, 19, NULL, 0);

  -- Imprisonment Order 5035C - not replaced
INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (16, 16, NULL, 0);

  -- Suspended Sentence Order - replaced by itself
INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (17, 17, 17, 0);

  -- New Community Order replaced by New Community Order
INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (18, 18, 18, 0);

  -- pre LASBO Suspended Sentence Order - replaced by new SUS order
UPDATE XHB_ORDER_TYPE_MAPPING SET REPLACED_BY = 17 WHERE ORDER_TYPE_MAPPING_ID = 10;

  -- pre LASBO Community Order replaced by New Community Order
UPDATE XHB_ORDER_TYPE_MAPPING SET REPLACED_BY = 18 WHERE ORDER_TYPE_MAPPING_ID = 9;

UPDATE XHB_ORDER SET ORDER_TEMPLATE_ID = 18 WHERE ORDER_TEMPLATE_ID = 9 AND CREATION_DATE > '04-Aug-13';

UPDATE XHB_ORDER SET ORDER_TEMPLATE_ID = 17 WHERE ORDER_TEMPLATE_ID = 10 AND CREATION_DATE > '04-Aug-13';

UPDATE XHB_ORDER SET ORDER_TEMPLATE_ID = 16 WHERE ORDER_TEMPLATE_ID = 11 AND CREATION_DATE > '04-Aug-13';

UPDATE XHB_ORDER SET ORDER_TEMPLATE_ID = 19 WHERE ORDER_TEMPLATE_ID = 12 AND CREATION_DATE > '04-Aug-13';

UPDATE XHB_ORDER SET ORDER_TEMPLATE_ID = 20 WHERE ORDER_TEMPLATE_ID = 13 AND CREATION_DATE > '04-Aug-13';

COMMIT;

DELETE FROM XHB_VERSION;

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'JAVACLIENT', '8.6.0.1', sysdate, 'RELEASE', 'Java Client Application', 1); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'JAVASERVER', '8.6.0.1', sysdate, 'RELEASE', 'Java Server Component', 2); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'XHIBIT', '8.6.0.1', sysdate , 'RELEASE', 'Database', 3); 
 
INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'MERCATOR', '8.6', sysdate, 'RELEASE', 'Mercator_Spoke', 4);

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'BROKER', '8.6', sysdate, 'RELEASE', 'CSH Broker Components', 4);

COMMIT;

spool off


