# Middlegen Preferences
cmp20.tables.EXI_ITEM_OUTBOUND.base-class-name=ExiItemOutbound
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.java-name=clobData
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.java-type=java.lang.String
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CLOB_DATA.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.java-name=crestCourtId
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.java-type=java.lang.String
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.CREST_COURT_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.java-name=description
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.java-type=java.lang.String
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.DESCRIPTION.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.java-name=identifier
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.java-type=java.lang.String
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.IDENTIFIER.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.java-name=itemCreated
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.java-type=java.util.Date
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_CREATED.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.java-name=itemExpires
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.java-type=java.util.Date
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_EXPIRES.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.java-name=itemId
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.java-type=java.lang.Long
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.local-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.ITEM_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.java-name=typeId
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.java-type=java.lang.Integer
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.local-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.local-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND.columns.TYPE_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND.generate-pk-class=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.base-class-name=ExiItemOutboundTracking
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.java-name=itemId
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.java-type=java.lang.Long
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.local-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.local-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.ITEM_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.java-name=statusId
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.local-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.local-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.STATUS_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.java-name=trackingDate
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.java-type=java.util.Date
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.local-set=true
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_DATE.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.java-name=trackingId
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.java-type=java.lang.Long
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.local-get=true
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.local-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.remote-get=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.columns.TRACKING_ID.remote-set=false
cmp20.tables.EXI_ITEM_OUTBOUND_TRACKING.generate-pk-class=false
cmp20.tables.EXI_REF_TRACKING_STATUS.base-class-name=ExiRefTrackingStatus
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.java-name=internalCode
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.java-type=java.lang.String
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.local-get=true
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.local-set=true
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.remote-get=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_CODE.remote-set=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.java-name=internalName
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.java-type=java.lang.String
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.local-get=true
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.local-set=true
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.remote-get=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.INTERNAL_NAME.remote-set=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.java-name=statusId
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.local-get=true
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.local-set=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.remote-get=false
cmp20.tables.EXI_REF_TRACKING_STATUS.columns.STATUS_ID.remote-set=false
cmp20.tables.EXI_REF_TRACKING_STATUS.generate-pk-class=false
relations.EXI_ITEM_OUTBOUND-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND-has-EXI_ITEM_OUTBOUND_TRACKING.enabled=true
relations.EXI_ITEM_OUTBOUND-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND-has-EXI_ITEM_OUTBOUND_TRACKING.target-many=true
relations.EXI_ITEM_OUTBOUND-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND_TRACKING-has-EXI_ITEM_OUTBOUND.enabled=true
relations.EXI_ITEM_OUTBOUND-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND_TRACKING-has-EXI_ITEM_OUTBOUND.target-many=false
relations.EXI_REF_TRACKING_STATUS-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND_TRACKING-has-EXI_REF_TRACKING_STATUS.enabled=true
relations.EXI_REF_TRACKING_STATUS-EXI_ITEM_OUTBOUND_TRACKING.EXI_ITEM_OUTBOUND_TRACKING-has-EXI_REF_TRACKING_STATUS.target-many=false
relations.EXI_REF_TRACKING_STATUS-EXI_ITEM_OUTBOUND_TRACKING.EXI_REF_TRACKING_STATUS-has-EXI_ITEM_OUTBOUND_TRACKING.enabled=true
relations.EXI_REF_TRACKING_STATUS-EXI_ITEM_OUTBOUND_TRACKING.EXI_REF_TRACKING_STATUS-has-EXI_ITEM_OUTBOUND_TRACKING.target-many=true
