CREATE OR REPLACE TRIGGER xhb_ref_aggravating_bir_tr
  BEFORE INSERT
  ON XHB_REF_AGGRAVATING_REASONS
  FOR EACH ROW

BEGIN

  IF :NEW.REF_AGGRAVATING_REASONS_ID IS NULL THEN

    SELECT XHB_REF_AGGRAVATING_REASON_SEQ.NEXTVAL
    INTO   :NEW.REF_AGGRAVATING_REASONS_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/
