/******************************************/
/* CJIT Drop Table and Sequences - v0.04x */
/******************************************/

/*************************************/
/* Packages                          */
/*************************************/
DROP PACKAGE cji_delete_documents_pkg ;


/*************************************/
/* Indexes                           */
/*************************************/
Drop INDEX CJI_AHM_DEVICE_ID_FK_IDX;
Drop INDEX CJI_AHM_STATUS_ID_FK_IDX;
Drop INDEX CJI_AHM_AGG_STAT_ST_ID_FK_IDX;
Drop INDEX CJI_AHM_REPLY_STATUS_ID_FK_IDX;
Drop INDEX CJI_AHM_REPLY_MSG_ID_FK_IDX;
Drop INDEX CJI_BITS_MSG_DOC_ID_FK_IDX;
Drop INDEX CJI_BITS_MSG_REQUEST_ID_FK_IDX;
Drop INDEX CJI_BITS_MSG_OP_TYPE_ID_FK_IDX;
Drop INDEX CJI_CJIP_MSG_EVENT_ID_FK_IDX;
Drop INDEX CJI_CJIP_MSG_DOC_ID_FK_IDX;
Drop INDEX CJI_CJIP_MSG_STATUS_ID_FK_IDX;
Drop INDEX CJI_CJIP_RQST_STATUS_ID_FK_IDX;
Drop INDEX CJI_DOC_DOC_TYPE_ID_FK_IDX;
Drop INDEX CJI_DOC_STATUS_ID_FK_IDX;
Drop INDEX CJI_DOC_SEC_CJO_ROLE_ID_FK_IDX;
Drop INDEX CJI_DOC_SEC_DOC_TYPE_ID_FK_IDX;
Drop INDEX CJI_EVENT_OP_ID_FK_IDX;
Drop INDEX CJI_EVENT_STATUS_ID_FK_IDX;

Drop INDEX CJI_AHM_REPLY_STAT_TXT_IDX;
Drop INDEX CJI_AHM_STAT_TXT_IDX;
Drop INDEX CJI_CJIP_MESSAGE_STAT_TXT_IDX;
Drop INDEX CJI_CJIP_REQUEST_STAT_TXT_IDX;
Drop INDEX CJI_DOCUMENT_STAT_TXT_IDX;
Drop INDEX CJI_EVENT_STAT_TXT_IDX;


/*************************************/
/* Sequences                         */
/*************************************/

Drop sequence CJI_DOCUMENT_SEQ;
Drop sequence CJI_EVENT_SEQ;
Drop sequence CJI_AHM_SEQ;
Drop sequence CJI_AHM_REPLY_SEQ;
Drop sequence CJI_CJIP_REQUEST_SEQ;
Drop sequence CJI_BITS_MESSAGE_SEQ;
Drop sequence CJI_CJIP_MESSAGE_SEQ;
Drop sequence CJI_CJIP_OPERATION_MESSAGE_SEQ;

/*************************************/
/* Constraints                       */
/*************************************/


ALTER TABLE CJI_AHM_AGG_STATUS DROP CONSTRAINT FK_CJI_AHM_AGG_STATUS155
/
ALTER TABLE CJI_BITS_MESSAGE DROP CONSTRAINT FK_CJI_BITS_MESSAGE161
/
ALTER TABLE CJI_BITS_MESSAGE DROP CONSTRAINT FK_CJI_BITS_MESSAGE156
/
ALTER TABLE CJI_BITS_MESSAGE DROP CONSTRAINT FK_CJI_BITS_MESSAGE155
/
ALTER TABLE CJI_DOCUMENT_SECURITY DROP CONSTRAINT FK_CJI_DOCUMENT_SECURITY5
/
ALTER TABLE CJI_DOCUMENT_SECURITY DROP CONSTRAINT FK_CJI_DOCUMENT_SECURITY160
/
ALTER TABLE CJI_DOCUMENT DROP CONSTRAINT FK_CJI_DOCUMENT1
/
ALTER TABLE CJI_DOCUMENT DROP CONSTRAINT FK_CJI_DOCUMENT159
/
ALTER TABLE CJI_CJIP_MESSAGE DROP CONSTRAINT FK_CJI_CJIP_MESSAGE155
/
ALTER TABLE CJI_CJIP_MESSAGE DROP CONSTRAINT FK_CJI_CJIP_MESSAGE8
/
ALTER TABLE CJI_CJIP_MESSAGE DROP CONSTRAINT FK_CJI_CJIP_MESSAGE9
/
ALTER TABLE CJI_CJIP_REQUEST DROP CONSTRAINT FK_CJI_CJIP_REQUEST15
/
ALTER TABLE CJI_AHM DROP CONSTRAINT FK_CJI_ADHOC_MESSAGE12
/
ALTER TABLE CJI_AHM DROP CONSTRAINT FK_CJI_ADHOC_MESSAGE158
/
ALTER TABLE CJI_EVENT DROP CONSTRAINT FK_CJI_EVENT162
/
ALTER TABLE CJI_EVENT DROP CONSTRAINT FK_CJI_EVENT7
/
ALTER TABLE CJI_AHM_REPLY DROP CONSTRAINT FK_CJI_ADHOC_MESSAGE_REPLY156
/
ALTER TABLE CJI_AHM_REPLY DROP CONSTRAINT FK_CJI_ADHOC_MESSAGE_REPLY155
/


/*************************************/
/* Drop Table                        */
/*************************************/


DROP TABLE CJI_PARAMETER_VALUE
/
DROP TABLE CJI_CJIP_MESSAGE_STATUS
/
DROP TABLE CJI_AHM_AGG_STATUS
/
DROP TABLE CJI_AHM_REPLY_STATUS
/
DROP TABLE CJI_BITS_MESSAGE
/
DROP TABLE CJI_AHM_STATUS
/
DROP TABLE CJI_CJIP_REQUEST_STATUS
/
DROP TABLE CJI_DOCUMENT_TYPE
/
DROP TABLE CJI_DOCUMENT_SECURITY
/
DROP TABLE CJI_EVENT_STATUS
/
DROP TABLE CJI_DOCUMENT
/
DROP TABLE CJI_CJIP_MESSAGE
/
DROP TABLE CJI_BITS_MESSAGE_OPERATIONS
/
DROP TABLE CJI_DOCUMENT_STATUS
/
DROP TABLE CJI_CJIP_REQUEST
/
DROP TABLE CJI_AHM
/
DROP TABLE CJI_AHM_DEVICE_TYPE
/
DROP TABLE CJI_CJO_ROLE
/
DROP TABLE CJI_EVENT_OPERATION_REQUEST
/
DROP TABLE CJI_EVENT
/
DROP TABLE CJI_AHM_REPLY
/

DROP TABLE CJI_VERSION
/
