INSERT INTO XHB_REF_DISPOSAL_TYPE 
  (REF_DISPOSAL_TYPE_ID,
  COURT_ID,
  TEMPLATE_VERSION,
  DISPOSAL_CODE,
  MENU_GROUP,
  OBS_IND,
  LINE_AVAIL,
  CATEGORY,
  TITLE)
SELECT 
  XHB_REF_DISPOSAL_TYPE_SEQ.NEXTVAL REF_DISPOSAL_TYPE_ID,
  XC.COURT_ID,
  1,
 'AAMRSS',
  'RS',
  'N',
  12,
  'O',
  'Alcohol Abstinence and Monitoring Requirement'
FROM XHB_COURT XC
WHERE NVL(XC.OBS_IND,'N') = 'N'
AND NOT EXISTS (SELECT NULL FROM XHB_REF_DISPOSAL_TYPE xrdm2 
                 WHERE xrdm2.DISPOSAL_CODE = 'AAMRSS'
                   AND xrdm2.COURT_ID = xc.COURT_ID );
COMMIT;
/