INSERT INTO XHB_REF_DISPOSAL_MENU 
  (REF_DISPOSAL_MENU_ID,
  COURT_ID,
  MENU_ITEM_ID,
  ABBREV,
  SEQ_NO,
  MENU_GROUP,
  OBS_IND,
  PARENT,
  DISPOSAL_CODE,
  TITLE)
SELECT 
  XHB_REF_DISPOSAL_MENU_SEQ.NEXTVAL REF_DISPOSAL_MENU_ID,
  XC.COURT_ID,
  NVL((SELECT MAX(MENU_ITEM_ID) FROM XHB_REF_DISPOSAL_MENU),0)+1 MENU_ITEM_ID,
  subqry.DISPOSAL_CODE ABBREV,
  subqry.NEXT_SEQ_NO SEQ_NO,
  'RS' MENU_GROUP,
  'N' OBS_IND,
  subqry.PARENT,
  subqry.DISPOSAL_CODE,
  subqry.TITLE
FROM XHB_COURT XC, 
      (SELECT xrdm.PARENT,
              'AAMRCS' DISPOSAL_CODE,
              'Alcohol Abstinence and Monitoring Requirement' TITLE,
              NVL(MAX(xrdm.SEQ_NO),0)+1 NEXT_SEQ_NO 
         FROM XHB_REF_DISPOSAL_MENU xrdm 
        WHERE xrdm.PARENT = 2619
     GROUP BY xrdm.PARENT) subqry
WHERE NVL(XC.OBS_IND,'N') = 'N'
AND NOT EXISTS (SELECT NULL FROM XHB_REF_DISPOSAL_MENU xrdm2 
                 WHERE xrdm2.DISPOSAL_CODE = subqry.DISPOSAL_CODE 
                   AND xrdm2.COURT_ID = xc.COURT_ID );
COMMIT;
/