SET COLSEP ,
SET PAGESIZE 0
SET TRIMSPOOL ON
SET LINESIZE 1000
SET FEEDBACK OFF
SET HEADING OFF
SPOOL oracle_table_stats.csv

SELECT 'XHB_CONFIG_PROP' AS TABLE_NAME,
       COUNT(*) AS RECORD_COUNT,
       'NO DATE' AS LAST_UPDATE_DATE
FROM XHB_CONFIG_PROP
UNION ALL
SELECT 'XHB_CONFIGURED_PUBLIC_NOTICE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_CONFIGURED_PUBLIC_NOTICE
UNION ALL
SELECT 'XHB_COURT', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_COURT
UNION ALL
SELECT 'XHB_COURT_ROOM', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_COURT_ROOM
UNION ALL
SELECT 'XHB_COURT_SATELLITE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_COURT_SATELLITE
UNION ALL
SELECT 'XHB_COURT_SITE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_COURT_SITE
UNION ALL
SELECT 'XHB_COURT_LOG_EVENT_DESC', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_COURT_LOG_EVENT_DESC
UNION ALL
SELECT 'XHB_REF_COURT', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_COURT
UNION ALL
SELECT 'XHB_REF_HEARING_TYPE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_HEARING_TYPE
UNION ALL
SELECT 'XHB_REF_JUDGE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_JUDGE
UNION ALL
SELECT 'XHB_REF_JUSTICE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_JUSTICE
UNION ALL
SELECT 'XHB_REF_PDDA_MESSAGE_TYPE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_PDDA_MESSAGE_TYPE
UNION ALL
SELECT 'XHB_REF_SYSTEM_CODE', COUNT(*), TO_CHAR(MAX(LAST_UPDATE_DATE), 'YYYY-MM-DD HH24:MI:SS') FROM XHB_REF_SYSTEM_CODE;

SPOOL OFF

exit;
