ALTER TABLE XHIBIT.XHB_DMI_CAD_REF_CODE
 DROP PRIMARY KEY CASCADE;

DROP TABLE XHIBIT.XHB_DMI_CAD_REF_CODE CASCADE CONSTRAINTS;

CREATE TABLE XHIBIT.XHB_DMI_CAD_REF_CODE
(
  DMI_CAD_REF_CODE_ID           NUMBER          NOT NULL,
  DMI_CAD_REF_CODE_DESCRIPTION  VARCHAR2(50 BYTE) NOT NULL,
  CREATION_DATE                 DATE,
  CREATED_BY                    VARCHAR2(20 BYTE),
  OBS_IND                       VARCHAR2(1 BYTE) DEFAULT 'N',
  DMI_CAD_REF_CODE_SHORT_NAME   VARCHAR2(2 BYTE) NOT NULL
)
TABLESPACE XHIBITD
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.DMI_CAD_REF_CODE_ID IS 'PK. cannot be null';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.DMI_CAD_REF_CODE_DESCRIPTION IS 'Description of the PK entry. cannot be null';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.CREATION_DATE IS 'Creation date of the record';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.CREATED_BY IS 'Creator the record';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.OBS_IND IS 'Obsolete indicator of the row.  Default to N';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_REF_CODE.DMI_CAD_REF_CODE_SHORT_NAME IS 'Short name of the PK entry. cannot be null';



CREATE UNIQUE INDEX XHIBIT.XHB_DMI_CAD_REF_CODE_PK ON XHIBIT.XHB_DMI_CAD_REF_CODE
(DMI_CAD_REF_CODE_ID)
LOGGING
TABLESPACE XHIBITD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE XHIBIT.XHB_DMI_CAD_REF_CODE ADD (
  CONSTRAINT XHB_DMI_CAD_REF_CODE_PK
  PRIMARY KEY
  (DMI_CAD_REF_CODE_ID)
  USING INDEX XHIBIT.XHB_DMI_CAD_REF_CODE_PK
  ENABLE VALIDATE);

GRANT INSERT, SELECT, UPDATE ON XHIBIT.XHB_DMI_CAD_REF_CODE TO PUBLIC;

