DROP TABLE XHIBIT.XHB_DMI_CAD_RUN_HISTORY CASCADE CONSTRAINTS;

CREATE TABLE XHIBIT.XHB_DMI_CAD_RUN_HISTORY
(
  DMI_CAD_RUN_HISTORY_ID  NUMBER                NOT NULL,
  CREATION_DATE           DATE,
  CREATED_BY              VARCHAR2(20 BYTE),
  START_RUN_TIME          DATE,
  END_RUN_TIME            DATE,
  DMI_CAD_REF_CODE_ID     NUMBER
)
TABLESPACE XHIBITD
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_HISTORY.DMI_CAD_RUN_HISTORY_ID IS 'PK. cannot be null';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_HISTORY.CREATION_DATE IS 'Creation date of the record';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_HISTORY.CREATED_BY IS 'Creator the record';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_HISTORY.DMI_CAD_REF_CODE_ID IS 'Foreign key reference to xbh_dmi_cad_ref_code.dmi_cad_ref_code_id';



ALTER TABLE XHIBIT.XHB_DMI_CAD_RUN_HISTORY ADD (
  CONSTRAINT DMI_CAD_REF_CODE_ID_FK 
  FOREIGN KEY (DMI_CAD_REF_CODE_ID) 
  REFERENCES XHIBIT.XHB_DMI_CAD_REF_CODE (DMI_CAD_REF_CODE_ID)
  ENABLE VALIDATE);

GRANT INSERT, SELECT, UPDATE ON XHIBIT.XHB_DMI_CAD_RUN_HISTORY TO PUBLIC;

