ALTER TABLE XHIBIT.XHB_DMI_CAD_ERROR_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE XHIBIT.XHB_DMI_CAD_ERROR_LOG CASCADE CONSTRAINTS;

CREATE TABLE XHIBIT.XHB_DMI_CAD_ERROR_LOG
(
  DMI_CAD_RUN_ID  NUMBER                        NOT NULL,
  ERROR_MESSAGE   VARCHAR2(500 BYTE),
  RUN_DATE        DATE
)
TABLESPACE XHIBITD
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX XHIBIT.XHB_DMI_CAD_ERROR_LOG_PK ON XHIBIT.XHB_DMI_CAD_ERROR_LOG
(DMI_CAD_RUN_ID)
LOGGING
TABLESPACE XHIBITD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE XHIBIT.XHB_DMI_CAD_ERROR_LOG ADD (
  CONSTRAINT XHB_DMI_CAD_ERROR_LOG_PK
  PRIMARY KEY
  (DMI_CAD_RUN_ID)
  USING INDEX XHIBIT.XHB_DMI_CAD_ERROR_LOG_PK
  ENABLE VALIDATE);

GRANT INSERT, SELECT, UPDATE ON XHIBIT.XHB_DMI_CAD_ERROR_LOG TO PUBLIC;

