ALTER TABLE XHIBIT.XHB_DMI_CAD_RUN_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE XHIBIT.XHB_DMI_CAD_RUN_LOG CASCADE CONSTRAINTS;

CREATE TABLE XHIBIT.XHB_DMI_CAD_RUN_LOG
(
  DMI_CAD_RUN_LOG_ID      NUMBER                NOT NULL,
  DMI_CAD_RUN_HISTORY_ID  NUMBER                NOT NULL,
  DMI_CAD_REF_CODE_ID     NUMBER                NOT NULL,
  COURT_ID                NUMBER,
  MODULE_NAME             VARCHAR2(100 BYTE),
  LOG_MESSAGE             VARCHAR2(250 BYTE),
  START_TIME              DATE,
  END_TIME                DATE
)
TABLESPACE XHIBITD
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.DMI_CAD_RUN_LOG_ID IS 'PK. cannot be null';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.DMI_CAD_RUN_HISTORY_ID IS 'Foreign key reference to XHB_DMI_CAD_RUN_HISTORY.c to establish master-detail relationship';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.DMI_CAD_REF_CODE_ID IS 'Foreign key relationship to xhb_dmi_cad_ref_code.xhb_dmi_ref_code_id';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.COURT_ID IS 'Foreign key relationship to xhb_court.court id.';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.MODULE_NAME IS 'Name of the PLSQL block that the code is currently processing';

COMMENT ON COLUMN XHIBIT.XHB_DMI_CAD_RUN_LOG.LOG_MESSAGE IS 'Log message';



CREATE UNIQUE INDEX XHIBIT.XHB_DMI_CAD_RUN_LOG_PK ON XHIBIT.XHB_DMI_CAD_RUN_LOG
(DMI_CAD_RUN_LOG_ID)
LOGGING
TABLESPACE XHIBITD
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             5M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE XHIBIT.XHB_DMI_CAD_RUN_LOG ADD (
  CONSTRAINT XHB_DMI_CAD_RUN_LOG_PK
  PRIMARY KEY
  (DMI_CAD_RUN_LOG_ID)
  USING INDEX XHIBIT.XHB_DMI_CAD_RUN_LOG_PK
  ENABLE VALIDATE);

ALTER TABLE XHIBIT.XHB_DMI_CAD_RUN_LOG ADD (
  CONSTRAINT DMI_CAD_RUN_LOG_COURT_ID_FK 
  FOREIGN KEY (COURT_ID) 
  REFERENCES XHIBIT.XHB_COURT (COURT_ID)
  ENABLE VALIDATE,
  CONSTRAINT DMI_CAD_RUN_LOG_REF_CODE_ID_FK 
  FOREIGN KEY (DMI_CAD_REF_CODE_ID) 
  REFERENCES XHIBIT.XHB_DMI_CAD_REF_CODE (DMI_CAD_REF_CODE_ID)
  ENABLE VALIDATE);

GRANT INSERT, SELECT, UPDATE ON XHIBIT.XHB_DMI_CAD_RUN_LOG TO PUBLIC;

