package uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel;

// java
import java.util.Collection;

import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;
import uk.gov.courtservice.xhibit.xmlbinding.generated.cjse.entities.EventParameters;

/**
 * <p>
 * Title: CaseCjseEventLevelPopulator
 * </p>
 * <p>
 * Description: Populates EventParameters for a Case level event
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: Eds
 * </p>
 * 
 * @author S Sangha
 * @version 1.0
 */

public class CaseCjseEventLevelPopulator implements CjseEventLevelPopulator {
    private static final Logger log = CSServices.getLogger(CaseCjseEventLevelPopulator.class);

    public CaseCjseEventLevelPopulator() {
    }

    /**
     * This method populates the passed in instance of EventParameters, a class
     * that has been generated by Castor.
     * 
     * @param eventParameters
     *            The event parameters to populate.
     * @param theCase
     *            A case entity local reference to aid in population of
     *            EventParameters
     * @param eventInfo
     *            The value object containing all relevant event information
     *            allowing population of the EventParameters object.
     * @return the Event Level and Identifier for this event
     */
    public EventLevelAndIdentifier populate(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) {
        // log start of method and check params
        logStartAndCheckParams(eventParameters, theCase, eventInfo);

        // populate the case parameters for this case via helper
        CasePopulatorHelper caseHelper = new CasePopulatorHelper();
        caseHelper.populateCaseAttributes(eventParameters, theCase);

        // get all defendantsOnCase as a collection
        Collection defendantsOnCase = theCase.getXhbDefendantOnCases();

        // populate the defendant parameters for all defendant on the case via
        // helper
        DefendantPopulatorHelper defHelper = new DefendantPopulatorHelper();
        defHelper.populateDefendantAttributes(eventParameters, defendantsOnCase);

        // populate the CRN parameters for all defendants via helper
        CrnPopulatorHelper2 crnHelper2 = new CrnPopulatorHelper2(defendantsOnCase);
        eventParameters.setASNs(crnHelper2.getAsns());
        eventParameters.setCRNIDs(crnHelper2.getCrns());

        EventLevelAndIdentifier levelAndIdentifier = new EventLevelAndIdentifier(CjseEventLevelPopulatorFactory
                .getInstance().getEventLevelForDescription(CjseEventLevelPopulatorFactory.CASE_EVENT_LEVEL), theCase
                .getCaseType()
                + theCase.getCaseNumber());

        return levelAndIdentifier;
    }

    // ---------------------------- Private Methods
    // -----------------------------//
    private void logStartAndCheckParams(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) throws IllegalArgumentException {
        log.debug("populate() start");

        // check parameters
        if (eventInfo == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance "
                    + "must be passed to the populate() method");
        }
        if (eventInfo.getCourtLogViewValue() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance containing a  "
                    + "CourtLogViewValue must be " + "passed to the populate() method");
        }
        if (eventParameters == null) {
            throw new IllegalArgumentException("An EventParameters instance must be passed to the "
                    + "populate() method for court log event type: " + eventInfo.getCourtLogViewValue().getEventType());
        }
        if (theCase == null) {
            throw new IllegalArgumentException("An XhbCase instance must be passed to the "
                    + "populate() method for court log event type: " + eventInfo.getCourtLogViewValue().getEventType());
        }
    }
}