package uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel;

import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;
import uk.gov.courtservice.xhibit.xmlbinding.generated.cjse.entities.EventParameters;

/**
 * <p>
 * Title: Cjse Event Level Populator Interface
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * This interface defines the responsibilities of a Cjse Event Level Populator.
 * It is primarily concerned with the XML population of event parameters,
 * however it has a secondary responsibility to keep track of the integer event
 * level that it is assigned, reflecting the event level that is to be recorded
 * in the subscription event control table.
 * </p>
 * <p>
 * <b>NOTE:</b> Instances of this interface should be thread safe (i.e. no
 * non-shareable instance variables) as we may be using the instances from a
 * static context.
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: Eds
 * </p>
 * 
 * @author Bob Boothby
 * @version 1.0
 */

public interface CjseEventLevelPopulator {

    /**
     * This method populates the passed in instance of EventParameters, a class
     * that has been generated by Castor.
     * 
     * @param eventParameters
     *            The event parameters to populate.
     * @param theCase
     *            the case entity for the case this event is created on
     * @param eventInfo
     *            The value object containing all relevant event information
     *            allowing population of the EventParameters object.
     * @return the Event Level and Identifier for this event
     */
    public EventLevelAndIdentifier populate(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo);
}
