package uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel;

// third party
import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.business.entities.xhb_defendant_on_case.XhbDefendantOnCase;
import uk.gov.courtservice.xhibit.business.entities.xhb_defendant_on_offence.XhbDefendantOnOffence;
import uk.gov.courtservice.xhibit.business.entities.xhb_defendant_on_offence.XhbDefendantOnOffenceBeanHelper2;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;
import uk.gov.courtservice.xhibit.xmlbinding.generated.cjse.entities.EventParameters;

/**
 * <p>
 * Title: CrnCjseEventLevelPopulator
 * </p>
 * <p>
 * Description: Populate the EventParameters for a CRN level event
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: Eds
 * </p>
 * 
 * @author Sarah Tong
 * @version $Id: CrnCjseEventLevelPopulator.java,v 1.2 2006/02/10 15:58:06
 *          rzvddy Exp $
 */

public class CrnCjseEventLevelPopulator implements CjseEventLevelPopulator {
    private static final Logger log = CSServices.getLogger(CrnCjseEventLevelPopulator.class);

    public CrnCjseEventLevelPopulator() {
    }

    /**
     * This method populates the passed in instance of EventParameters, a class
     * that has been generated by Castor.
     * 
     * @param eventParameters
     *            The event parameters to populate.
     * @param theCase
     *            A case entity local reference to aid in population of
     *            EventParameters
     * @param eventInfo
     *            The value object containing all relevant event information
     *            allowing population of the EventParameters object.
     * @return the Event Level and Identifier for this event
     */
    public EventLevelAndIdentifier populate(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) {
        // log start of method and check params
        logStartAndCheckParams(eventParameters, theCase, eventInfo);

        // retrieve defendantOnOffenceId and deduce defendant id
        Integer defendantOnOffenceId = eventInfo.getDefendantOnOffenceId();
        /**
         * @todo Check with Rakesh - will defendant id also be populated here or
         *       only for defendant level events? Look up for now...
         */

        // find the entity
        XhbDefendantOnOffence theDefendantOnOffence = XhbDefendantOnOffenceBeanHelper2
                .findByPrimaryKey(defendantOnOffenceId);

        XhbDefendantOnCase defendantOnCase = theDefendantOnOffence.getXhbDefendantOnCase();

        // populate crn level attributes via helper
        CrnPopulatorHelper2 crnHelper2 = new CrnPopulatorHelper2(defendantOnCase, theDefendantOnOffence);
        eventParameters.setASNs(crnHelper2.getAsns());
        eventParameters.setCRNIDs(crnHelper2.getCrns());

        // populate defendant level attributes via helper
        DefendantPopulatorHelper defHelper = new DefendantPopulatorHelper();
        defHelper.populateDefendantAttributes(eventParameters, defendantOnCase);

        // populate case level attributes via helper
        CasePopulatorHelper caseHelper = new CasePopulatorHelper();
        caseHelper.populateCaseAttributes(eventParameters, theCase);

        // find the event identifier, use CRN if available, otherwise null
        // there will be zero or one CRNs for a defendant on offence
        String eventIdentifier = null;
        if (eventParameters.getCRNIDs() != null && eventParameters.getCRNIDs().getCRNIDCount() == 1) {
            eventIdentifier = eventParameters.getCRNIDs().getCRNID(0);
        }

        EventLevelAndIdentifier levelAndIdentifier = new EventLevelAndIdentifier(CjseEventLevelPopulatorFactory
                .getInstance().getEventLevelForDescription(CjseEventLevelPopulatorFactory.CRN_EVENT_LEVEL),
                eventIdentifier);

        return levelAndIdentifier;

    }

    // ---------------------------- Private Methods
    // -----------------------------//
    private void logStartAndCheckParams(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) throws IllegalArgumentException {
        log.debug("populate() start");

        // check parameters
        if (eventInfo == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance "
                    + "must be passed to the populate() method");
        }
        if (eventInfo.getCourtLogViewValue() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance containing a  "
                    + "CourtLogViewValue must be " + "passed to the populate() method");
        }
        if (eventParameters == null) {
            throw new IllegalArgumentException("An EventParameters instance must be passed to the "
                    + "populate() method for court log event type: " + eventInfo.getCourtLogViewValue().getEventType());
        }
        if (theCase == null) {
            throw new IllegalArgumentException("An XhbCase instance must be passed to the "
                    + "populate() method for court log event type: " + eventInfo.getCourtLogViewValue().getEventType());
        }
        if (eventInfo.getDefendantOnOffenceId() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance with a defendantOnOffenceId "
                    + "must be passed to the populate() method for court log event type: "
                    + eventInfo.getCourtLogViewValue().getEventType());
        }
    }
}