package uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel;

// third party
import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.business.entities.xhb_defendant_on_case.XhbDefendantOnCase;
import uk.gov.courtservice.xhibit.business.entities.xhb_defendant_on_case.XhbDefendantOnCaseBeanHelper2;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;
import uk.gov.courtservice.xhibit.xmlbinding.generated.cjse.entities.EventParameters;

/**
 * <p>
 * Title: DefendantCjseEventLevelPopulator
 * </p>
 * <p>
 * Description: Populate the EventParameters for a DEFENDANT level event.
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: EDS
 * </p>
 * 
 * @author Sarah Tong
 * @version $Id: DefendantCjseEventLevelPopulator.java,v 1.2 2006/02/10 15:58:07
 *          rzvddy Exp $
 */

public class DefendantCjseEventLevelPopulator implements CjseEventLevelPopulator {
    private static final Logger log = CSServices.getLogger(DefendantCjseEventLevelPopulator.class);

    public DefendantCjseEventLevelPopulator() {
    }

    /**
     * This method populates the passed in instance of EventParameters, a class
     * that has been generated by Castor.
     * 
     * @param eventParameters
     *            The event parameters to populate.
     * @param theCase
     *            A case entity local reference to aid in population of
     *            EventParameters
     * @param eventInfo
     *            The value object containing all relevant event information
     *            allowing population of the EventParameters object.
     * @return the Event Level and Identifier for this event
     */
    public EventLevelAndIdentifier populate(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) {
        // log start of method and check params
        logStartAndCheckParams(eventParameters, theCase, eventInfo);

        Integer defendantOnCaseId = eventInfo.getDefendantOnCaseId();

        XhbDefendantOnCase defendantOnCase = XhbDefendantOnCaseBeanHelper2.findByPrimaryKey(defendantOnCaseId);

        // populate the crn parameters via helper
        CrnPopulatorHelper2 crnHelper2 = new CrnPopulatorHelper2(defendantOnCase);
        eventParameters.setASNs(crnHelper2.getAsns());
        eventParameters.setCRNIDs(crnHelper2.getCrns());
        
        // populate the defendant parameters for this defendant via helper
        DefendantPopulatorHelper defHelper = new DefendantPopulatorHelper();
        defHelper.populateDefendantAttributes(eventParameters, defendantOnCase);

        // populate case level attributes via helper
        CasePopulatorHelper caseHelper = new CasePopulatorHelper();
        caseHelper.populateCaseAttributes(eventParameters, theCase);

        // find the event identifier, use ASN if available, otherwise null
        // there may be zero, one or more ASNs for a defendant on a case
        String eventIdentifier = null;
        if (eventParameters.getASNs() != null && eventParameters.getASNs().getASNCount() > 0) {
            eventIdentifier = eventParameters.getASNs().getASN(0);
        }

        EventLevelAndIdentifier levelAndIdentifier = new EventLevelAndIdentifier(CjseEventLevelPopulatorFactory
                .getInstance().getEventLevelForDescription(CjseEventLevelPopulatorFactory.DEFENDANT_EVENT_LEVEL),
                eventIdentifier);

        return levelAndIdentifier;
    }

    // ---------------------------- Private Methods
    // -----------------------------//
    private void logStartAndCheckParams(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) throws IllegalArgumentException {
        log.debug("populate() start");

        // check parameters
        if (eventInfo == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance "
                    + "must be passed to the populate() method");
        }
        if (eventInfo.getCourtLogViewValue() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance containing a  "
                    + "CourtLogViewValue must be " + "passed to the populate() method");
        }
        if (eventParameters == null) {
            throw new IllegalArgumentException("An EventParameters instance must be passed to the "
                    + "populate() method");
        }
        if (theCase == null) {
            throw new IllegalArgumentException("An XhbCase instance must be passed to the " + "populate() method");
        }
        if (eventInfo.getDefendantOnCaseId() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance with a defendantOnCaseId "
                    + "must be passed to the populate() method for court log event type: "
                    + eventInfo.getCourtLogViewValue().getEventType());
        }
    }
}