package uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel;

// jdk
import java.util.Collection;

import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;
import uk.gov.courtservice.xhibit.courtlog.vos.MultiCaseCourtLogViewValue;
import uk.gov.courtservice.xhibit.xmlbinding.generated.cjse.entities.EventParameters;

/**
 * <p>
 * Title: JoinderCjseEventLevelPopulator
 * </p>
 * <p>
 * Description: Special case populator for the Joinder Indictment event.
 * Populates the case level attributes for all cases involved in the Joinder,
 * populates defendant and crn level attirubtes for the main case only. The main
 * case is an arbitrarily chosen case selected when the court log event is
 * created.
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: Eds
 * </p>
 * 
 * @author Bob Boothby, Sarah Tong
 * @version $Id: JoinderCjseEventLevelPopulator.java,v 1.2 2006/02/10 15:58:07
 *          rzvddy Exp $
 */

public class JoinderCjseEventLevelPopulator implements CjseEventLevelPopulator {
    private static final Logger log = CSServices.getLogger(JoinderCjseEventLevelPopulator.class);

    public JoinderCjseEventLevelPopulator() {
    }

    /**
     * This method populates the passed in instance of EventParameters, a class
     * that has been generated by Castor.
     * 
     * @param eventParameters
     *            The event parameters to populate.
     * @param theCase
     *            A case entity local reference to aid in population of
     *            EventParameters
     * @param eventInfo
     *            The value object containing all relevant event information
     *            allowing population of the EventParameters object.
     * @return the Event Level and Identifier for this event
     */
    public EventLevelAndIdentifier populate(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) {
        logStartAndCheckParams(eventParameters, theCase, eventInfo);

        // call CasePopulatorHelper for the case level attributes
        MultiCaseCourtLogViewValue viewValue = (MultiCaseCourtLogViewValue) eventInfo.getCourtLogViewValue();
        CasePopulatorHelper caseHelper = new CasePopulatorHelper();

        Integer[] caseIds = new Integer[viewValue.getCaseIds().length];
        for (int i = 0; i < viewValue.getCaseIds().length; i++) {
            caseIds[i] = viewValue.getCaseIds()[i];
        }
        caseHelper.populateCaseAttributes(eventParameters, caseIds);

        // get the XhbDefendantOnCase local refs for the lead case
        Collection defendantOnCases = theCase.getXhbDefendantOnCases();

        // call DefendantPopulatorHelper for:
        DefendantPopulatorHelper defPopHelper = new DefendantPopulatorHelper();
        defPopHelper.populateDefendantAttributes(eventParameters, defendantOnCases);

        // call CrnPopulatorHelper for:
        CrnPopulatorHelper2 crnHelper2 = new CrnPopulatorHelper2(defendantOnCases);
        eventParameters.setASNs(crnHelper2.getAsns());
        eventParameters.setCRNIDs(crnHelper2.getCrns());
        
        EventLevelAndIdentifier levelAndIdentifier = new EventLevelAndIdentifier(CjseEventLevelPopulatorFactory
                .getInstance().getEventLevelForDescription(CjseEventLevelPopulatorFactory.CASE_EVENT_LEVEL), theCase
                .getCaseType()
                + theCase.getCaseNumber());

        log.debug("populate() finished");

        return levelAndIdentifier;

    }

    // ---------------------------- Private Methods
    // -----------------------------//
    private void logStartAndCheckParams(EventParameters eventParameters, XhbCase theCase,
            CourtLogSubscriptionValue eventInfo) throws IllegalArgumentException {
        log.debug("populate() start");

        // check parameters
        if (eventInfo == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance "
                    + "must be passed to the populate() method");
        }
        if (eventInfo.getCourtLogViewValue() == null) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance containing a  "
                    + "CourtLogViewValue must be " + "passed to the populate() method");
        }
        if (eventParameters == null) {
            throw new IllegalArgumentException("An EventParameters instance must be passed to the "
                    + "populate() method");
        }
        if (theCase == null) {
            throw new IllegalArgumentException("An XhbCase instance must be passed to the " + "populate() method");
        }
        if (!(eventInfo.getCourtLogViewValue() instanceof MultiCaseCourtLogViewValue)) {
            throw new IllegalArgumentException("A CourtLogSubscriptionValue instance containing a CourtLogViewValue "
                    + "which is an instance of MultiCaseCourtLogViewValue must be passed "
                    + "to the populate() method for court log event type: "
                    + eventInfo.getCourtLogViewValue().getEventType());
        }
    }
}