<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by LCMG (LogicaCMG) -->
<xsd:schema xmlns:apd="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails" xmlns="http://www.courtservice.gov.uk/schemas/courtservice" xmlns:cs="http://www.courtservice.gov.uk/schemas/courtservice" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice" elementFormDefault="qualified" attributeFormDefault="unqualified" version="5.8" id="MonetaryOrder">
	<xsd:include schemaLocation="CourtService.xsd"/>
	<xsd:annotation>
		<xsd:appinfo>
			<Metadata xmlns="http://www.govtalk.gov.uk/metadata/egms">
				<Creator>Ministry of Justice</Creator>
				<Created>2016-01-13</Created>
				<Modified>2016-01-13</Modified>
				<Format Schema="http://www.iana.org/assignments/media-types">text/xml</Format>
				<Identifier>MonetaryOrder</Identifier>
				<Language codeListID="ISO639-2" codeListURI="http://www.loc.gov/standards/iso639-2/langcodes.html">eng</Language>
				<Publisher>Ministry of Justice, 102 Petty France, London</Publisher>
				<ConformsTo>http://www.w3.org/2001/XMLSchema</ConformsTo>
				<Copyright>Crown Copyright 2016</Copyright>
				<ProtectiveMarking>unclassified</ProtectiveMarking>
				<Status>final</Status>
				<StatusDescription>definitive version for release</StatusDescription>
				<Version>5.3</Version>
				<Category codeListID="GCL">Justice System</Category>
				<Title>Crown Court Monetary Order</Title>
				<Type>message</Type>
			</Metadata>
		</xsd:appinfo>
	</xsd:annotation>
	<xsd:complexType name="MonetaryOrderStructure">
		<xsd:sequence>
			<xsd:element name="DocumentID" type="DocumentIDstructure"/>
			<xsd:element name="OrderHeader" type="CourtOrderHeaderStructure"/>
			<xsd:element name="CollectionCentre" type="CollectionCentreStructure"/>
			<xsd:element name="CommittingMagistratesCourt" type="CourtHouseStructure"/>
			<xsd:element name="CollectingMagistratesCourt" type="CourtHouseStructure"/>
			<xsd:element name="CollectionOrderMade" type="YesNoType"/>
			<xsd:element name="InCustody" type="YesNoType" default="no"/>
			<xsd:element name="SentenceDate" type="xsd:date"/>
			<xsd:element name="ParentGuardianName" type="xsd:string" minOccurs="0"/>
			<xsd:element name="PaymentRateValue" type="xsd:string" minOccurs="0"/>
			<xsd:element name="AdditionalDetails" type="xsd:string" minOccurs="0"/>
			<xsd:element name="MonetaryDisposals" type="xsd:string"/>
			<xsd:element name="MonetaryTotals" type="xsd:string"/>
			<xsd:element name="Fine-LengthOfSentence" type="ModifiedTermStructure" minOccurs="0"/>
			<xsd:element name="Imprisonment-LengthOfSentence" type="ModifiedTermStructure" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="MonetaryOrder" type="MonetaryOrderStructure"/>
</xsd:schema>
