<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2009 sp1 (http://www.altova.com) by Robert Wright (STL Technologies Ltd) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.dca.gov.uk/xmlschemas/libra" targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0" id="XHIBITDVLAdriversSimpleTypes">
	<xsd:annotation>
		<xsd:appinfo>
			<Metadata xmlns="http://www.govtalk.gov.uk/metadata/egms">
				<Creator>Ministry of Justice</Creator>
				<Created>2015-06-03</Created>
				<Modified>2015-06-03</Modified>
				<Format Schema="http://www.iana.org/assignments/media-types">text/xml</Format>
				<Identifier>CourtService</Identifier>
				<Language codeListID="ISO639-2" codeListURI="http://www.loc.gov/standards/iso639-2/langcodes.html">eng</Language>
				<Publisher>Ministry of Justice, Clive House, 102 Petty France, London, SW1H 9AJ</Publisher>
				<ConformsTo>http://www.w3.org/2001/XMLSchema</ConformsTo>
				<Copyright>Crown Copyright 2015</Copyright>
				<ProtectiveMarking>unclassified</ProtectiveMarking>
				<Status>draft</Status>
				<StatusDescription>initial version for review</StatusDescription>
				<Version>1.0</Version>
				<Category codeListID="GCL">Justice System</Category>
				<Title>XHIBIT DVLA drivers simple types</Title>
				<Type>architectural</Type>
			</Metadata>
		</xsd:appinfo>
	</xsd:annotation>
	<xsd:simpleType name="AlcoholLevelAmountType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,3}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AlcoholLevelMethodType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CaseManagementUnitType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CounterpartIssueType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CourtCodeType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="9999"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CourthouseType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CourtroomType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DisqualificationPendingSentenceType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DisqualificationPeriodType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,6}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DisqualificationUntilTestPassedType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentNumberType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DocumentReferenceType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="14"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DriverGenderType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="DriverLicenceIssueType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="2"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DriverLicenceRecordCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DriverLicenceRecordTypeTextType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="50"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DriverLicenceStatusType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DriverNumberType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[A-Z,0-9]{5}[0-9][0,1,5,6][0-9]([0][1-9]|[1-2][0-9]|[3][0,1])[0-9][A-Z,0-9]{3}[A-Z]{2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="DVLAoffenceCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="4"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="EndorsementsNotifiedType">
		<xsd:restriction base="xsd:string"/>
	</xsd:simpleType>
	<xsd:simpleType name="IdentityType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="20"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LibraCaseAccountNumberType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="12"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LicenceToFollowMarkerType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="9"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="LocationType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="10"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MagistratesCourtCommitteeType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MarkerCodeType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="MarkerTextType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="30"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="NumberOfMatchesType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="50"/>
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="OverallPointsTotalType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PenaltyPointsType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,2}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PersonGivenNameType">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PersonFamilyNameType">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
			<xsd:maxLength value="35"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PettySessionalAreaType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{4}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PopulatedStringType">
		<xsd:restriction base="xsd:string">
			<xsd:minLength value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="PreviouslyNotifiedEndorsementsType">
		<xsd:restriction base="xsd:integer">
			<xsd:minInclusive value="0"/>
			<xsd:maxInclusive value="9"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SentencePeriodType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1,3}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="String3Type">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="3"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TestStatusType">
		<xsd:restriction base="xsd:integer">
			<xsd:pattern value="[0-9]{1}"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TextType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="TransactionKeyTextType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="70"/>
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>
