-- Drop Sequences

DROP SEQUENCE XHB_DOCUMENT_REPLY_SEQ ;

DROP SEQUENCE XHB_RECIPIENT_SEQ ;

DROP SEQUENCE XHB_DOCUMENT_RECIPIENT_SEQ ;

DROP SEQUENCE XHB_FORMATTING_SEQ ;

DROP SEQUENCE XHB_XML_DOCUMENT_SEQ ;

DROP SEQUENCE XHB_DOCUMENT_CONTROL_SEQ ;

DROP SEQUENCE XHB_DOCUMENT_DISTRIBUTION_SEQ ;

DROP SEQUENCE XHB_WLL_CONTROL_SEQ ;

DROP SEQUENCE XHB_WLL_RECIPIENT_SEQ ;

DROP SEQUENCE XHB_WLL_DOCUMENT_SEQ ;

DROP SEQUENCE XHB_INTERNET_HTML_SEQ ;

DROP SEQUENCE XHB_CR_LIVE_STATUS_DESC_SEQ ;

DROP SEQUENCE XHB_CR_LIVE_STATUS_SEQ ;


-- Drop Table

DROP TABLE "XHB_DOCUMENT_REPLY" CASCADE CONSTRAINTS;

DROP TABLE "XHB_RECIPIENT" CASCADE CONSTRAINTS;

DROP TABLE "XHB_DOCUMENT_RECIPIENT" CASCADE CONSTRAINTS;

DROP TABLE "XHB_FORMATTING" CASCADE CONSTRAINTS;

DROP TABLE "XHB_XML_DOCUMENT" CASCADE CONSTRAINTS;

DROP TABLE "XHB_DOCUMENT_CONTROL" CASCADE CONSTRAINTS;

DROP TABLE "XHB_DOCUMENT_DISTRIBUTION" CASCADE CONSTRAINTS;

DROP TABLE "XHB_WLL_CONTROL" CASCADE CONSTRAINTS;

DROP TABLE "XHB_WLL_RECIPIENT" CASCADE CONSTRAINTS;

DROP TABLE "XHB_WLL_DOCUMENT" CASCADE CONSTRAINTS;

DROP TABLE XHB_CR_LIVE_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_CR_LIVE_STATUS_DESC CASCADE CONSTRAINTS;


DROP TABLE XHB_INTERNET_HTML CASCADE CONSTRAINTS;

