DROP SEQUENCE XHB_COURT_LOG_EVENT_DESC_SEQ ;

DROP TABLE XHB_COURT_LOG_EVENT_DESC CASCADE CONSTRAINTS;

CREATE SEQUENCE XHB_COURT_LOG_EVENT_DESC_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;

CREATE TABLE XHB_COURT_LOG_EVENT_DESC (
       EVENT_DESC_ID        NUMBER(8) NOT NULL,
       FLAGGED_EVENT        NUMBER(1) NOT NULL,
       EDITABLE             NUMBER(1) NOT NULL,
       SEND_TO_MERCATOR     NUMBER(1) NOT NULL,
       UPDATE_LINKED_CASES  NUMBER(1) NOT NULL,
       PUBLISH_TO_SUBSCRIBERS NUMBER(1) NOT NULL,
       CLEAR_PUBLIC_DISPLAYS NUMBER(1) NOT NULL,
       E_INFORM             NUMBER(1) NOT NULL,
       PUBLIC_DISPLAY       NUMBER(1) NOT NULL,
       LINKED_CASE_TEXT     VARCHAR2(100) NOT NULL,
       EVENT_DESCRIPTION    VARCHAR2(100) NOT NULL,
       EVENT_TYPE           NUMBER(5) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);



ALTER TABLE XHB_COURT_LOG_EVENT_DESC
       ADD  ( PRIMARY KEY (EVENT_DESC_ID) ) ;

-- Update BEGIN

INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
147, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Case Called On', 10100, 153, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
148, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Defendant Attendance Options', 10200, 30
, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
149, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Prosecution Addresses Judge', 10300, 57
, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
150, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Defence Addresses Judge', 10400, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
151, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Resume', 10500, 18, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
152, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Bench Warrant Options', 20100, 20, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
153, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Freetext', 21300, 46, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
154, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Form B (RDCO) By', 20505, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
155, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', '7 AND 14 Day Orders - ToDo', 1, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
156, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appellant Case Opened', 20606, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
157, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Time Estimate For Trial', 20901, 83, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
158, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Trial - Witness Sworn', 20904, 118, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
159, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appeal - Witness Sworn', 20603, 100, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
160, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Mentions And Applications - Judges Ruling'
, 20703, 4, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:00 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
161, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appeal - Legal Argument', 20611, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
162, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Trial - Legal Argument', 20916, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
163, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Main Body - Legal Argument', 21100, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
164, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Bail And Custody', 20200, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
165, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appellant Attendance', 20601, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
166, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appeal - Interpreter Sworn', 20612, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
167, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Jury Sworn In', 20902, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
168, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Jury/Juror Discharged', 20915, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
169, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Indictment By', 20501, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
170, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'P And D Hearing On', 20502, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
171, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Readiness For Trial', 20503, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
172, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Respondant Case Opened', 20602, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
173, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appeal - Witness Released', 20604, 17, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
174, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Trial - Witness Released', 20905, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
175, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Trial - Cracked or Ineffective', 20918, 3
, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
176, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Reporting Restrictions', 21200, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
177, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Mentions And Applications - Application To Stand Out'
, 20701, 3, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
178, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Mentions And Applications - Defence Application'
, 20702, 3, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
179, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Mentions And Applications - Prosecution Application'
, 20704, 3, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
180, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Defence Case Opened', 20906, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
181, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Defence Case Closed', 20910, 18, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
182, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Jury Returns', 20913, 3, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
183, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Prosecution Case', 20903, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
184, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Trial - Interpretor Sworn', 20917, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
185, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appellant Case Closed', 20608, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
186, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appellant Submissions', 20607, 57, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:01 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
187, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Bench Retire To Consider Judgement', 20609
, 4, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
188, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Respondent Case Closed', 20605, 5, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
189, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Mentions And Applications - Other', 20705
, 4, '<anonymous>', 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
190, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Directions Form Completed', 20504, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
191, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Defence Closing Speech', 20909, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
192, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Jury Out', 20912, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
193, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Jury Retire', 20914, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
194, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Prosecution Case Closed', 20908, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
195, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Prosecution Closing Speech', 20907, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
196, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Summing Up', 20911, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
197, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Verdict To Be Taken', 20919, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
198, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Appeal - Judgement', 20610, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
199, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Short Adjournment Options', 30100, 276, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
200, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Long Adjournment Options', 30200, 118, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
201, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Case Closed', 30300, 45, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
202, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Court Closed', 30400, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
203, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Add Count', 40100, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
204, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Add Count To Defendant', 40101, 6, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
205, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Amend Count', 40102, 3, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
206, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Delete Count', 40103, 4, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
207, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Delete Results For Count', 21001, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
208, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Add Indictment', 40200, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:02 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
209, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Delete Indictment', 40201, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
210, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Amend Defendant', 40300, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
211, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Add Breach', 40400, 65, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
212, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Remove Breach', 40401, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
213, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Amend Breach', 40402, 64, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
214, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Delete Breach', 40403, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
215, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Add Offence', 40500, 65, '<anonymous>', 'Xhibit'
,  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
216, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Amend Offence', 40501, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
217, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Delete Offence', 40502, 4, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
INSERT INTO XHB_COURT_LOG_EVENT_DESC ( EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, EVENT_DESCRIPTION, EVENT_TYPE, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) VALUES ( 
218, 0, 0, 0, 0, 0, 0, 0, 0, 'LC_TEXT_', 'Sign Indictment', 40202, 3, '<anonymous>'
, 'Xhibit',  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '12/07/2002 01:14:03 PM', 'MM/DD/YYYY HH:MI:SS AM')
); 
commit;
