CREATE SEQUENCE TMP_ERROR_LOG_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ADDRESS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_BREACH_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CASE_PROSECTOR_AGENCY_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CASE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CC_INFO_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CHARGE_DIFFERENCES_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CHARGE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CONFIGURED_PUBLIC_NOT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CONTACT_DETAIL_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_LOG_CATEGORY_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_LOG_CAT_DESC_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_LOG_ENTRY_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_LOG_EVENT_DESC_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_ROOM_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_COURT_SITE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CR_LIVE_STATUS_DESC_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_CR_LIVE_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DAILY_LIST_XML_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFENDANT_CHARGE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFENDANT_ON_CASE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFENDANT_ON_OFFENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFENDANT_REFERENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFENDANT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEFINITIVE_PUB_NOTICE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DEF_HEARING_RECORD_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DIRECTION_ATTEND_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DIR_FOR_CASE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DIR_FOR_DEFENDANT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DISPOSAL_DETAIL_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DISPOSAL_REFERENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DISPOSAL_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_DOCUMENT_TYPE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ERROR_DEF_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_EXPORTA_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_FIXED_LIST_XML_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_FORMATTING_IN_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_FORMATTING_OUT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_HEARING_LIST_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_HEARING_RECORD_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_HEARING_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_INTERNET_XML_HTML_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LEG_REP_FOR_SCHED_DEF_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LINKED_CASE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LINKED_HEARING_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LINKED_SH_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LIST_DISTRIBUTION_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_LIST_DIST_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_MESSAGE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_OBJECT_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_OFFENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORDER_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORD_DELIVERY_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORD_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORD_TEMPLATE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORD_TYPE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_ORIGINAL_RESULT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_PLEA_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_PUBLIC_NOTICE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_RECIPIENT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_ADVOCATE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_BREACH_PROC_CODE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_CHAMBER_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_COURT_REPORTER_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_COURT_REPORT_F_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_COURT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_DEFENCE_CATEGORY_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_DISPOSAL_MENU_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_DISPOSAL_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_HEARING_TYPE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_JUDGE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_JUSTICE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_LEGAL_REP_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_OFFENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_PROSECUTOR_AGENCY_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_SOLICITOR_FIRM_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_REF_SYSTEM_CODE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_RUNNING_LIST_XML_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SCHEDULED_HEARING_DEF_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SCHEDULED_HEARING_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SCHED_HEARING_ATTEND_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SH_COURT_REPORTER_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SH_JUDGE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SH_JUSTICE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SH_LEG_REP_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SH_STAFF_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SITTING_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SOLICITOR_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_SYS_AUDIT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_TERMINAL_REFERENCE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_TERMINAL_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_VERDICT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_WARNED_LIST_XML_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_WLL_DIST_STATUS_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_WLL_RECIPIENT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_WL_DISTRIBUTION_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_XGROUP_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;
CREATE SEQUENCE XHB_XROLE_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;

CREATE TABLE MTBL_MERC_AUDIT_LOG (
       MAPNAME              VARCHAR2(64) NULL,
       ERRORCODE            VARCHAR2(64) NULL,
       MAPSTATUS            VARCHAR2(128) NULL,
       MAPMESSAGE           VARCHAR2(256) NULL,
       ELASPEDSECS          NUMBER(10) NULL,
       COMMANDLINE          VARCHAR2(256) NULL,
       OBJECTSFOUND         NUMBER(10) NULL,
       OBJECTSBUILT         NUMBER(10) NULL,
       TIMESTAMP            DATE NULL,
       TRANSACTION_TYPE     VARCHAR2(128) NULL,
       ERROR_ADAPTER_TARGET_REASON VARCHAR2(128) NULL,
       ERROR_ADAPTER_TARGET_CODE VARCHAR2(10) NULL,
       ERROR_ADAPTER_TARGET_TYPE VARCHAR2(12) NULL,
       ERROR_ADAPTER_SOURCE_REASON VARCHAR2(128) NULL,
       ERROR_ADAPTER_SOURCE_CODE VARCHAR2(10) NULL,
       ERROR_ADAPTER_SOURCE_TYPE VARCHAR2(12) NULL,
       MAPTIMESTAMP         DATE NULL,
       ELASP                NUMBER(38) NULL
);


CREATE TABLE MTBL_MERC_DL_STORAGE (
       NAME                 VARCHAR2(64) NULL,
       ADDRESS              VARCHAR2(64) NULL,
       TOID                 VARCHAR2(8) NULL,
       UNIQUEMSGID          VARCHAR2(64) NULL,
       MSGTYPE              VARCHAR2(32) NULL,
       MSGTIME              VARCHAR2(16) NULL,
       MSGDATE              DATE NULL,
       ADDITIONAL1          VARCHAR2(128) NULL,
       ADDITIONAL2          VARCHAR2(128) NULL,
       ADDITIONAL3          VARCHAR2(128) NULL,
       ADDITIONAL4          VARCHAR2(128) NULL,
       FROMID               VARCHAR2(8) NULL,
       MESSAGE              CLOB NULL
);


CREATE TABLE MTBL_MERC_EMAIL_ALERT (
       MAPNAME              VARCHAR2(64) NULL,
       ERRORCODE            VARCHAR2(64) NULL,
       TOEMAILADDRESS1      VARCHAR2(128) NULL,
       TOEMAILADDRESS2      VARCHAR2(128) NULL,
       TOEMAILADDRESS3      VARCHAR2(128) NULL,
       CCEMAILADDRESS       VARCHAR2(128) NULL,
       BCCEMAILADDRESS      VARCHAR2(128) NULL,
       FROMEMAILADDRESS     VARCHAR2(64) NULL,
       SUBJECT              VARCHAR2(64) NULL,
       SERVER               VARCHAR2(64) NULL,
       PROTOCOL             VARCHAR2(16) NULL,
       ADDITIONAL1          VARCHAR2(128) NULL,
       ADDITIONAL2          VARCHAR2(128) NULL,
       ADDITIONAL3          VARCHAR2(128) NULL,
       ADDITIONAL4          VARCHAR2(128) NULL
);


CREATE TABLE MTBL_MERC_TRIGGER (
       MID                  NUMBER(38) NOT NULL,
       CREST_ID             NUMBER(4) NOT NULL,
       MAP_NAME             VARCHAR2(64) NOT NULL,
       COMMAND_LINE         VARCHAR2(128) NULL,
       INTERFACE_NAME       VARCHAR2(64) NULL,
       MAP_RUN              VARCHAR2(1) NULL,
       CREST_IP             VARCHAR2(24) NULL
);


CREATE TABLE MTBL_TRIGGER_SERVER (
       ID                   NUMBER(9) NOT NULL,
       NAME                 VARCHAR2(80) NULL,
       ADDRESS              VARCHAR2(30) NULL,
       STARTUPDATE          DATE NULL,
       SHUTDOWNDATE         DATE NULL
);


CREATE TABLE TMP_ERROR_LOG (
       SEQ_NO               Number NOT NULL,
       OWNER                Varchar2(255) NULL,
       RESOLUTION           Varchar2(4000) NULL,
       COMMUNICATIONS       Varchar2(4000) NULL,
       MERCATOR_LOG_ID      Varchar2(255) NULL,
       BEA_LOG_ID           Varchar2(255) NULL,
       DESCRIPTION          Varchar2(255) NULL,
       ERROR_ID             Varchar2(255) NULL
);


ALTER TABLE TMP_ERROR_LOG
       ADD  ( PRIMARY KEY (SEQ_NO) ) ;


CREATE TABLE XHB_ADDRESS (
       ADDRESS_ID           NUMBER(8) NOT NULL,
       ADDRESS_1            VARCHAR2(30) NULL,
       ADDRESS_2            VARCHAR2(30) NULL,
       ADDRESS_3            VARCHAR2(30) NULL,
       ADDRESS_4            VARCHAR2(30) NULL,
       TOWN                 VARCHAR2(30) NULL,
       COUNTY               VARCHAR2(30) NULL,
       POSTCODE             VARCHAR2(8) NULL,
       COUNTRY              VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_ADDRESS
       ADD  ( PRIMARY KEY (ADDRESS_ID) ) ;


CREATE TABLE XHB_BREACH (
       BREACH_ID            NUMBER(8) NOT NULL,
       ORIGINAL_SENTENCE    VARCHAR2(90) NULL,
       ORIGINAL_SENTENCE_DATE DATE NULL,
       ORIGINAL_COURT_TYPE  VARCHAR2(2) NULL,
       DATE_PUT             DATE NULL,
       BREACH_TYPE          VARCHAR2(2) NULL,
       BRING_BACK           VARCHAR2(1) NULL,
       CHARGE_ID            NUMBER(8) NOT NULL,
       REF_COURT_ID         NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_breach_charge_fk ON XHB_BREACH
(
       CHARGE_ID                      ASC
);

CREATE INDEX xhb_breach_ref_court_fk ON XHB_BREACH
(
       REF_COURT_ID                   ASC
);


ALTER TABLE XHB_BREACH
       ADD  ( PRIMARY KEY (BREACH_ID) ) ;


CREATE TABLE XHB_CASE (
       CASE_ID              NUMBER(8) NOT NULL,
       CASE_NUMBER          NUMBER(8) NULL,
       CASE_TYPE            VARCHAR2(1) NULL,
       MAG_CONVICTION_DATE  DATE NULL,
       CASE_SUB_TYPE        VARCHAR2(1) NULL,
       CASE_TITLE           VARCHAR2(72) NULL,
       CASE_DESCRIPTION     VARCHAR2(70) NULL,
       LINKED_CASE_ID       NUMBER(38) NULL,
       BAIL_MAG_CODE        VARCHAR2(255) NULL,
       REF_COURT_ID         NUMBER(8) NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL,
       CHARGE_IMPORT_INDICATOR VARCHAR2(1) NULL,
       SEVERED_IND          VARCHAR2(1) NULL,
       INDICT_RESP          VARCHAR2(50) NULL,
       DATE_IND_REC         DATE NULL,
       PROS_AGENCY_REFERENCE VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       CASE_CLASS           NUMBER(5) NULL,
       LEASE_TIME           DATE NULL,
       JUDGE_REASON_FOR_APPEAL VARCHAR2(255) NULL,
       RESULTS_VERIFIED     VARCHAR2(1) NULL,
       LENGTH_TAPE          NUMBER(5) NULL,
       NO_PAGE_PROS_EVIDENCE NUMBER(5) NULL,
       NO_PROS_WITNESS      NUMBER(5) NULL,
       EST_PDH_TRIAL_LENGTH NUMBER(5) NULL,
       indictment_info_1    VARCHAR2(78) NULL,
       indictment_info_2    VARCHAR2(78) NULL,
       indictment_info_3    VARCHAR2(78) NULL,
       indictment_info_4    VARCHAR2(78) NULL,
       indictment_info_5    VARCHAR2(78) NULL,
       indictment_info_6    VARCHAR2(78) NULL
);


ALTER TABLE XHB_CASE
       ADD  ( PRIMARY KEY (CASE_ID) ) ;


CREATE TABLE XHB_CASE_PROSECUTOR_AGENCY (
       CASE_PROS_AGENCY_ID  NUMBER(8) NOT NULL,
       PROSECUTOR_TYPE      VARCHAR2(1) NULL,
       CASE_ID              NUMBER(8) NULL,
       REF_PROSECUTOR_AGENCY_ID NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_case_pros_agc_case_fk ON XHB_CASE_PROSECUTOR_AGENCY
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_case_pros_agc_ref_pr_ag_fk ON XHB_CASE_PROSECUTOR_AGENCY
(
       REF_PROSECUTOR_AGENCY_ID       ASC
);


ALTER TABLE XHB_CASE_PROSECUTOR_AGENCY
       ADD  ( PRIMARY KEY (CASE_PROS_AGENCY_ID) ) ;


CREATE TABLE XHB_CC_INFO (
       CC_INFO_ID           NUMBER(8) NOT NULL,
       CC_INFO_TEXT         VARCHAR2(255) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_CC_INFO
       ADD  ( PRIMARY KEY (CC_INFO_ID) ) ;


CREATE TABLE XHB_CHARGE (
       CHARGE_ID            NUMBER(8) NOT NULL,
       CHARGE_TYPE          VARCHAR2(1) NOT NULL,
       PROS_PAPER_SERVED_DATE DATE NULL,
       CREST_CHARGE_ID      NUMBER(38) NULL,
       CREST_CHARGE_SEQ_NO  NUMBER(5) NULL,
       REF_SYSTEM_CODE_ID   NUMBER(8) NULL,
       CASE_ID              NUMBER(38) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       IND_SIGNED_DATE      DATE NULL
);

CREATE INDEX xhb_charge_case_fk ON XHB_CHARGE
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_charge_ref_system_code_fk ON XHB_CHARGE
(
       REF_SYSTEM_CODE_ID             ASC
);


ALTER TABLE XHB_CHARGE
       ADD  ( PRIMARY KEY (CHARGE_ID) ) ;


CREATE TABLE XHB_CHARGE_DIFFERENCES (
       CHARGE_DIFF_ID       NUMBER(8) NOT NULL,
       REPORT               VARCHAR2(255) NULL,
       DIFF_TIME            DATE NOT NULL,
       CASE_ID              NUMBER(8) NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_charge_differences_case_fk ON XHB_CHARGE_DIFFERENCES
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_charge_difference_court_fk ON XHB_CHARGE_DIFFERENCES
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_CHARGE_DIFFERENCES
       ADD  ( PRIMARY KEY (CHARGE_DIFF_ID) ) ;


CREATE TABLE XHB_CONFIGURED_PUBLIC_NOTICE (
       CONFIGURED_PUBLIC_NOTICE_ID NUMBER(8) NOT NULL,
       IS_ACTIVE            VARCHAR2(1) NULL,
       COURT_ROOM_ID        NUMBER(8) NOT NULL,
       PUBLIC_NOTICE_ID     NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_configured_pub_court_rm_fk ON XHB_CONFIGURED_PUBLIC_NOTICE
(
       COURT_ROOM_ID                  ASC
);

CREATE INDEX xhb_configured_pub_pub_not_fk ON XHB_CONFIGURED_PUBLIC_NOTICE
(
       PUBLIC_NOTICE_ID               ASC
);


ALTER TABLE XHB_CONFIGURED_PUBLIC_NOTICE
       ADD  ( PRIMARY KEY (CONFIGURED_PUBLIC_NOTICE_ID) ) ;


CREATE TABLE XHB_CONTACT_DETAIL (
       CONTACT_ID           NUMBER(8) NOT NULL,
       CONTACT_TYPE         VARCHAR2(255) NULL,
       CONTACT_VALUE        VARCHAR2(14) NULL,
       EMAIL_FORMAT         VARCHAR2(1) NULL,
       PAGER_NET            VARCHAR2(1) NULL,
       ADDRESS_ID           NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_contact_detail_address_fk ON XHB_CONTACT_DETAIL
(
       ADDRESS_ID                     ASC
);


ALTER TABLE XHB_CONTACT_DETAIL
       ADD  ( PRIMARY KEY (CONTACT_ID) ) ;


CREATE TABLE XHB_COURT (
       COURT_ID             NUMBER(8) NOT NULL,
       COURT_TYPE           VARCHAR2(255) NOT NULL,
       CIRCUIT              VARCHAR2(255) NULL,
       COURT_NAME           VARCHAR2(255) NOT NULL,
       CREST_COURT_ID       VARCHAR2(3) NOT NULL,
       COURT_PREFIX         VARCHAR2(255) NOT NULL,
       SHORT_NAME           VARCHAR2(5) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       ADDRESS_ID           NUMBER(8) NULL,
       CREST_IP_ADDRESS     VARCHAR2(25) NOT NULL,
       in_service_flag      VARCHAR2(1) NOT NULL,
       obs_ind              VARCHAR2(1) NULL
);

CREATE INDEX xhb_court_address_fk ON XHB_COURT
(
       ADDRESS_ID                     ASC
);


ALTER TABLE XHB_COURT
       ADD  ( PRIMARY KEY (COURT_ID) ) ;


CREATE TABLE XHB_COURT_LOG_CATEGORY (
       CATEGORY_ID          NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CATEGORY_DESC_ID     NUMBER(8) NOT NULL,
       EVENT_DESC_ID        NUMBER(8) NOT NULL
);

CREATE INDEX xhb_crt_lg_cat_crt_lg_evt_d_fk ON XHB_COURT_LOG_CATEGORY
(
       EVENT_DESC_ID                  ASC
);

CREATE INDEX xhb_crt_lg_cat_crt_lg_cat_d_fk ON XHB_COURT_LOG_CATEGORY
(
       CATEGORY_DESC_ID               ASC
);


ALTER TABLE XHB_COURT_LOG_CATEGORY
       ADD  ( PRIMARY KEY (CATEGORY_ID) ) ;


CREATE TABLE XHB_COURT_LOG_CATEGORY_DESC (
       CATEGORY_DESC_ID     NUMBER(8) NOT NULL,
       CATEGORY_DESCRIPTION VARCHAR2(100) NOT NULL,
       CATEGORY_TYPE        NUMBER(5) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_COURT_LOG_CATEGORY_DESC
       ADD  ( PRIMARY KEY (CATEGORY_DESC_ID) ) ;


CREATE TABLE XHB_COURT_LOG_ENTRY (
       ENTRY_ID             NUMBER(8) NOT NULL,
       LOG_ENTRY_XML        VARCHAR2(4000) NOT NULL,
       CASE_ID              NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       DATE_TIME            DATE NOT NULL,
       EVENT_DESC_ID        NUMBER(8) NOT NULL
);

CREATE INDEX xhb_court_log_entry_case_pk ON XHB_COURT_LOG_ENTRY
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_crt_lg_ent_crt_lg_evt_d_fk ON XHB_COURT_LOG_ENTRY
(
       EVENT_DESC_ID                  ASC
);


ALTER TABLE XHB_COURT_LOG_ENTRY
       ADD  ( PRIMARY KEY (ENTRY_ID) ) ;


CREATE TABLE XHB_COURT_LOG_EVENT_DESC (
       EVENT_DESC_ID        NUMBER(8) NOT NULL,
       FLAGGED_EVENT        NUMBER(1) NOT NULL,
       EDITABLE             NUMBER(1) NOT NULL,
       SEND_TO_MERCATOR     NUMBER(1) NOT NULL,
       UPDATE_LINKED_CASES  NUMBER(1) NOT NULL,
       PUBLISH_TO_SUBSCRIBERS NUMBER(1) NOT NULL,
       CLEAR_PUBLIC_DISPLAYS NUMBER(1) NOT NULL,
       E_INFORM             NUMBER(1) NOT NULL,
       PUBLIC_DISPLAY       NUMBER(1) NOT NULL,
       LINKED_CASE_TEXT     VARCHAR2(100) NOT NULL,
       EVENT_DESCRIPTION    VARCHAR2(100) NOT NULL,
       EVENT_TYPE           NUMBER(5) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL);


ALTER TABLE XHB_COURT_LOG_EVENT_DESC
       ADD  ( PRIMARY KEY (EVENT_DESC_ID) ) ;


CREATE TABLE XHB_COURT_ROOM (
       COURT_ROOM_ID        NUMBER(8) NOT NULL,
       COURT_ROOM_NAME      VARCHAR2(255) NULL,
       DESCRIPTION          VARCHAR2(255) NULL,
       LOCATION             VARCHAR2(255) NULL,
       CREST_COURT_ROOM_NO  NUMBER(2) NULL,
       COURT_SITE_ID        NUMBER(38) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       obs_ind              VARCHAR2(1) NULL
);

CREATE INDEX xhb_court_room_court_site_fk ON XHB_COURT_ROOM
(
       COURT_SITE_ID                  ASC
);


ALTER TABLE XHB_COURT_ROOM
       ADD  ( PRIMARY KEY (COURT_ROOM_ID) ) ;


CREATE TABLE XHB_COURT_SITE (
       COURT_SITE_ID        NUMBER(8) NOT NULL,
       COURT_SITE_NAME      VARCHAR2(255) NULL,
       COURT_SITE_CODE      VARCHAR2(1) NULL,
       COURT_ID             NUMBER(38) NOT NULL,
       ADDRESS_ID           NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       obs_ind              VARCHAR2(1) NULL
);

CREATE INDEX xhb_court_site_court_fk ON XHB_COURT_SITE
(
       COURT_ID                       ASC
);

CREATE INDEX xhb_court_site_address_fk ON XHB_COURT_SITE
(
       ADDRESS_ID                     ASC
);


ALTER TABLE XHB_COURT_SITE
       ADD  ( PRIMARY KEY (COURT_SITE_ID) ) ;


CREATE TABLE XHB_CR_LIVE_STATUS (
       cr_live_status_id    NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       cr_live_status_desc_id NUMBER(8) NULL,
       COURT_ROOM_ID        NUMBER(8) NOT NULL,
       SCHEDULED_HEARING_ID NUMBER(8) NOT NULL
);

CREATE INDEX xhb_cr_live_st_cr_live_st_d_fk ON XHB_CR_LIVE_STATUS
(
       cr_live_status_desc_id         ASC
);

CREATE INDEX xhb_cr_live_status_court_rm_fk ON XHB_CR_LIVE_STATUS
(
       COURT_ROOM_ID                  ASC
);

CREATE INDEX xhb_cr_live_status_sch_hear_fk ON XHB_CR_LIVE_STATUS
(
       SCHEDULED_HEARING_ID           ASC
);


ALTER TABLE XHB_CR_LIVE_STATUS
       ADD  ( PRIMARY KEY (cr_live_status_id) ) ;


CREATE TABLE XHB_CR_LIVE_STATUS_DESC (
       cr_live_status_desc_id NUMBER(8) NOT NULL,
       internet_desc        VARCHAR2(255) NULL,
       public_display_desc  VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_CR_LIVE_STATUS_DESC
       ADD  ( PRIMARY KEY (cr_live_status_desc_id) ) ;


CREATE TABLE XHB_DAILY_LIST_XML (
       DAILY_LIST_XML_ID    NUMBER(8) NOT NULL,
       DAILY_LIST_DATE      DATE NULL,
       DAILY_LIST_XML       CLOB NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_daily_list_xml_court_fk ON XHB_DAILY_LIST_XML
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_DAILY_LIST_XML
       ADD  ( PRIMARY KEY (DAILY_LIST_XML_ID) ) ;


CREATE TABLE XHB_DEF_HEARING_RECORD (
       HEARING_RECORD_ID    NUMBER(8) NOT NULL,
       REF_ADJOURNMENT_ID   NUMBER(8) NULL,
       ADJOURNED_DATE       DATE NULL,
       IS_ADJOURNED         VARCHAR2(1) NULL,
       COLLECT_MAGISTRATE_COURT_ID NUMBER(8) NULL,
       START_DATE_NEW_BAIL_STATUS DATE NULL,
       NEW_BAIL_STATUS      VARCHAR2(1) NULL,
       DATE_BAIL_APPLICATION DATE NULL,
       SUBST_BAIL_APPLICATION VARCHAR2(1) NULL,
       ORAL_EVIDENCE        VARCHAR2(1) NULL,
       RESULT_BAIL_APPLICATION VARCHAR2(1) NULL,
       IS_HRA_APPLICATION   VARCHAR2(1) NULL,
       REF_DEF_HEARING_TYPE_ID NUMBER(8) NULL,
       END_BAIL_STATUS      VARCHAR2(1) NULL,
       START_BAIL_STATUS    VARCHAR2(1) NULL,
       DATE_OF_COMMITTAL    DATE NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       HEARING_ID           NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       hearing_dates_freetext_1 VARCHAR2(78) NULL,
       hearing_dates_freetext_2 VARCHAR2(78) NULL,
       hearing_dates_freetext_3 VARCHAR2(78) NULL
);

CREATE INDEX xhb_def_hear_rec_def_on_cas_fk ON XHB_DEF_HEARING_RECORD
(
       DEFENDANT_ON_CASE_ID           ASC
);

CREATE INDEX xhb_def_hear_hearing_fk ON XHB_DEF_HEARING_RECORD
(
       HEARING_ID                     ASC
);


ALTER TABLE XHB_DEF_HEARING_RECORD
       ADD  ( PRIMARY KEY (HEARING_RECORD_ID) ) ;


CREATE TABLE XHB_DEFENDANT (
       DEFENDANT_ID         NUMBER(8) NOT NULL,
       CREST_DEFENDANT_ID   NUMBER(8) NULL,
       FIRST_NAME           VARCHAR2(255) NULL,
       MIDDLE_NAME          VARCHAR2(35) NULL,
       SURNAME              VARCHAR2(35) NULL,
       INITIALS             VARCHAR2(4) NULL,
       DATE_OF_BIRTH        DATE NULL,
       GENDER               NUMBER(1) NULL,
       LAST_CONVICTION_DATE DATE NULL,
       IS_COMPANY           VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       ADDRESS_ID           NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL
);

CREATE INDEX xhb_defendant_address_fk ON XHB_DEFENDANT
(
       ADDRESS_ID                     ASC
);

CREATE INDEX xhb_defendant_court_fk ON XHB_DEFENDANT
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_DEFENDANT
       ADD  ( PRIMARY KEY (DEFENDANT_ID) ) ;


CREATE TABLE XHB_DEFENDANT_CHARGE (
       DEFENDANT_CHARGE_ID  NUMBER(8) NOT NULL,
       CHARGE_ID            NUMBER(8) NOT NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_defend_chg_charge_fk ON XHB_DEFENDANT_CHARGE
(
       CHARGE_ID                      ASC
);

CREATE INDEX xhb_defend_chg_def_case_fk ON XHB_DEFENDANT_CHARGE
(
       DEFENDANT_ON_CASE_ID           ASC
);


ALTER TABLE XHB_DEFENDANT_CHARGE
       ADD  ( PRIMARY KEY (DEFENDANT_CHARGE_ID) ) ;


CREATE TABLE XHB_DEFENDANT_ON_CASE (
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       NO_OF_TICS           NUMBER(4) NULL,
       FINAL_DRIVING_LICENCE_STATUS NUMBER(1) NULL,
       PTIURN               VARCHAR2(11) NULL,
       IS_JUVENILE          VARCHAR2(1) NULL,
       IS_MASKED            VARCHAR2(1) NULL,
       MASKED_NAME          VARCHAR2(255) NULL,
       CASE_ID              NUMBER(8) NOT NULL,
       DEFENDANT_ID         NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       results_verified     VARCHAR2(1) NULL,
       defendant_number     NUMBER(8) NULL,
       date_of_committal    DATE NULL
);

CREATE INDEX xhb_defendant_on_case_case_fk ON XHB_DEFENDANT_ON_CASE
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_defendant_on_case_defen_fk ON XHB_DEFENDANT_ON_CASE
(
       DEFENDANT_ID                   ASC
);


ALTER TABLE XHB_DEFENDANT_ON_CASE
       ADD  ( PRIMARY KEY (DEFENDANT_ON_CASE_ID) ) ;


CREATE TABLE XHB_DEFENDANT_ON_OFFENCE (
       DEFENDANT_ON_OFFENCE_ID NUMBER(8) NOT NULL,
       APPEAL_AGAINST_TYPE  VARCHAR2(1) NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       OFFENCE_ID           NUMBER(8) NOT NULL,
       ORIGINAL_RESULT_ID   NUMBER(8) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       IS_SENTENCE_APPEAL   VARCHAR2(1) NULL,
       IS_CONVICTION_APPEAL VARCHAR2(1) NULL,
       ALT_REF_OFFENCE_ID   NUMBER(8) NULL,
       HAS_OTHER            VARCHAR2(1) NULL,
       is_stayed            VARCHAR2(1) NULL,
       HAS_CONVICTION       VARCHAR2(1) NULL,
       HAS_VERDICT          VARCHAR2(1) NULL
);

CREATE INDEX xhb_defendant_off_offence_fk ON XHB_DEFENDANT_ON_OFFENCE
(
       OFFENCE_ID                     ASC
);

CREATE INDEX xhb_defendant_off_orig_res_fk ON XHB_DEFENDANT_ON_OFFENCE
(
       ORIGINAL_RESULT_ID             ASC
);

CREATE INDEX xhb_defendant_off_def_case_fk ON XHB_DEFENDANT_ON_OFFENCE
(
       DEFENDANT_ON_CASE_ID           ASC
);


ALTER TABLE XHB_DEFENDANT_ON_OFFENCE
       ADD  ( PRIMARY KEY (DEFENDANT_ON_OFFENCE_ID) ) ;


CREATE TABLE XHB_DEFENDANT_REFERENCE (
       DEF_REF_ID           NUMBER(8) NOT NULL,
       REFERENCE_VALUE      VARCHAR2(255) NULL,
       REFERENCE_NAME       VARCHAR2(255) NULL,
       CATEGORY             VARCHAR2(255) NULL,
       DEFENDANT_ID         NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_defendant_reference_def_fk ON XHB_DEFENDANT_REFERENCE
(
       DEFENDANT_ID                   ASC
);


ALTER TABLE XHB_DEFENDANT_REFERENCE
       ADD  ( PRIMARY KEY (DEF_REF_ID) ) ;


CREATE TABLE XHB_DEFINITIVE_PUBLIC_NOTICE (
       definitive_pn_id     NUMBER(8) NOT NULL,
       definitive_pn_desc   VARCHAR2(255) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       priority             NUMBER(8) NULL
);


ALTER TABLE XHB_DEFINITIVE_PUBLIC_NOTICE
       ADD  ( PRIMARY KEY (definitive_pn_id) ) ;


CREATE TABLE XHB_DIRECTION_ATTEND (
       direction_attend_id  NUMBER(8) NOT NULL,
       DIRECTIONS_FOR_CASE_ID NUMBER(8) NOT NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_direction_att_dir_fr_cs_fk ON XHB_DIRECTION_ATTEND
(
       DIRECTIONS_FOR_CASE_ID         ASC
);

CREATE INDEX xhb_direction_att_def_on_cs_fk ON XHB_DIRECTION_ATTEND
(
       DEFENDANT_ON_CASE_ID           ASC
);


ALTER TABLE XHB_DIRECTION_ATTEND
       ADD  ( PRIMARY KEY (direction_attend_id) ) ;


CREATE TABLE XHB_DIRECTIONS_FOR_CASE (
       DIRECTIONS_FOR_CASE_ID NUMBER(8) NOT NULL,
       FREETEXT             VARCHAR2(255) NULL,
       DATE_TIME            DATE NULL,
       LIST_DATE            DATE NULL,
       LIST_TYPE            VARCHAR2(2) NULL,
       LISTED_AS            VARCHAR2(1) NULL,
       DIRECTIONS_TEXT      VARCHAR2(255) NULL,
       TRIAL_TIME_UNIT      NUMBER(5) NULL,
       TRIAL_TIME_ESTIMATE  NUMBER(5) NULL,
       HAS_PANDD_FORM       VARCHAR2(1) NULL,
       CASE_ID              NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_directions_case_case_fk ON XHB_DIRECTIONS_FOR_CASE
(
       CASE_ID                        ASC
);


ALTER TABLE XHB_DIRECTIONS_FOR_CASE
       ADD  ( PRIMARY KEY (DIRECTIONS_FOR_CASE_ID) ) ;


CREATE TABLE XHB_DIRECTIONS_FOR_DEFENDANT (
       DIRECTIONS_FOR_DEFENDANT_ID NUMBER(8) NOT NULL,
       FREETEXT             VARCHAR2(255) NULL,
       DATE_TIME            DATE NULL,
       is_identified        VARCHAR2(1) NULL,
       TO_BE_FILED_BY       DATE NULL,
       FILED_FORM_B         VARCHAR2(2) NULL,
       CERT_ATTENDANCE      VARCHAR2(1) NULL,
       NEW_BAIL_CONDITIONS  VARCHAR2(255) NULL,
       BAIL_STATUS          VARCHAR2(2) NULL,
       ARRAIGNED            VARCHAR2(1) NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_dir_for_def_def_on_case_fk ON XHB_DIRECTIONS_FOR_DEFENDANT
(
       DEFENDANT_ON_CASE_ID           ASC
);


ALTER TABLE XHB_DIRECTIONS_FOR_DEFENDANT
       ADD  ( PRIMARY KEY (DIRECTIONS_FOR_DEFENDANT_ID) ) ;


CREATE TABLE XHB_DISPOSAL (
       DISPOSAL_ID          NUMBER(8) NOT NULL,
       DEF_ON_CASE_OR_OFFENCE VARCHAR2(1) NULL,
       FREETEXT             VARCHAR2(255) NULL,
       DATE_TIME            DATE NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NULL,
       REF_DISPOSAL_ID      NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       DEFENDANT_ON_OFFENCE_ID NUMBER(8) NULL,
       category             VARCHAR2(255) NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_disposal_def_on_case_fk ON XHB_DISPOSAL
(
       DEFENDANT_ON_CASE_ID           ASC
);

CREATE INDEX xhb_disposal_ref_disposal_fk ON XHB_DISPOSAL
(
       REF_DISPOSAL_ID                ASC
);

CREATE INDEX xhb_disposal_def_on_offence_fk ON XHB_DISPOSAL
(
       DEFENDANT_ON_OFFENCE_ID        ASC
);


ALTER TABLE XHB_DISPOSAL
       ADD  ( PRIMARY KEY (DISPOSAL_ID) ) ;


CREATE TABLE XHB_DISPOSAL_DETAIL (
       DISPOSAL_DETAIL_ID   NUMBER(8) NOT NULL,
       UNIT                 VARCHAR2(8) NULL,
       AMOUNT               NUMBER(10,2) NULL,
       FREE_TEXT_DESC       VARCHAR2(255) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       ORIGINAL_RESULT_ID   NUMBER(8) NOT NULL
);

CREATE INDEX xhb_original_result_fk ON XHB_DISPOSAL_DETAIL
(
       ORIGINAL_RESULT_ID             ASC
);


ALTER TABLE XHB_DISPOSAL_DETAIL
       ADD  ( PRIMARY KEY (DISPOSAL_DETAIL_ID) ) ;


CREATE TABLE XHB_DISPOSAL_REFERENCE (
       DIS_REF_ID           NUMBER(8) NOT NULL,
       DISPOSAL_ID          NUMBER(8) NOT NULL,
       REFERENCE_NAME       VARCHAR2(255) NULL,
       REFERENCE_VALUE      VARCHAR2(255) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_disposal_ref_disposal2_fk ON XHB_DISPOSAL_REFERENCE
(
       DISPOSAL_ID                    ASC
);


ALTER TABLE XHB_DISPOSAL_REFERENCE
       ADD  ( PRIMARY KEY (DIS_REF_ID) ) ;


CREATE TABLE XHB_DOCUMENT_TYPE (
       document_type_id     NUMBER(8) NOT NULL,
       description          VARCHAR2(255) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_DOCUMENT_TYPE
       ADD  ( PRIMARY KEY (document_type_id) ) ;


CREATE TABLE XHB_ERROR_DEF (
       ERROR_DEF_ID         NUMBER(8) NOT NULL,
       DESCRIPTION          VARCHAR2(255) NULL,
       SEVERITY             VARCHAR2(255) NULL,
       ERROR_TYPE           VARCHAR2(255) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


CREATE TABLE XHB_EXPORTA (
       EXPORT_A_ID          NUMBER(8) NOT NULL,
       COURT_CLERK_EXPORT   VARCHAR2(255) NULL,
       STATUS_FLAG          VARCHAR2(1) NULL,
       LINKED_HEARING_ID    NUMBER(8) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       HEARING_ID           NUMBER(8) NULL
);

CREATE INDEX xhb_exporta_hearing_fk ON XHB_EXPORTA
(
       HEARING_ID                     ASC
);


ALTER TABLE XHB_EXPORTA
       ADD  ( PRIMARY KEY (EXPORT_A_ID) ) ;


CREATE TABLE XHB_FORMATTING_IN (
       formatting_in_id     NUMBER(8) NOT NULL,
       xml_document         CLOB NOT NULL,
       date_in              DATE NOT NULL,
       court_id             NUMBER(8) NOT NULL,
       format_status        VARCHAR2(2) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_FORMATTING_IN
       ADD  ( PRIMARY KEY (formatting_in_id) ) ;


CREATE TABLE XHB_FORMATTING_OUT (
       formatting_out_id    NUMBER(8) NOT NULL,
       mime_type            VARCHAR2(255) NOT NULL,
       status               VARCHAR2(255) NOT NULL,
       court_id             NUMBER(8) NOT NULL,
       formatted_document   CLOB NOT NULL,
       date_created         DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_FORMATTING_OUT
       ADD  ( PRIMARY KEY (formatting_out_id) ) ;


CREATE TABLE XHB_HEARING (
       HEARING_ID           NUMBER(8) NOT NULL,
       CASE_ID              NUMBER(38) NOT NULL,
       REF_HEARING_TYPE_ID  NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL,
       MP_HEARING_TYPE      VARCHAR2(1) NULL,
       last_calculated_duration NUMBER(20) NULL,
       hearing_start_date   DATE NULL,
       hearing_end_date     DATE NULL,
       linked_hearing_id    NUMBER(8) NULL
);

CREATE INDEX xhb_hearing_case_fk ON XHB_HEARING
(
       CASE_ID                        ASC
);

CREATE INDEX xhb_hearing_ref_hearing_typ_fk ON XHB_HEARING
(
       REF_HEARING_TYPE_ID            ASC
);

CREATE INDEX xhb_hearing_court_fk ON XHB_HEARING
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_HEARING
       ADD  ( PRIMARY KEY (HEARING_ID) ) ;


CREATE TABLE XHB_HEARING_LIST (
       LIST_ID              NUMBER(8) NOT NULL,
       LIST_TYPE            VARCHAR2(1) NULL,
       START_DATE           DATE NULL,
       END_DATE             DATE NULL,
       STATUS               VARCHAR2(5) NULL,
       EDITION_NO           NUMBER(2) NULL,
       PUBLISHED_TIME       DATE NULL,
       PRINT_REFERENCE      VARCHAR2(255) NULL,
       CREST_LIST_ID        NUMBER(8) NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LIST_COURT_TYPE      VARCHAR2(2) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_HEARING_LIST
       ADD  ( PRIMARY KEY (LIST_ID) ) ;


CREATE TABLE XHB_INTERNET_XML_HTML (
       internet_xml_html_id NUMBER(8) NOT NULL,
       xml                  CLOB NULL,
       html                 CLOB NULL,
       status               VARCHAR2(1) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL
);

CREATE INDEX XHB_XML_HTML_COURT_FK ON XHB_INTERNET_XML_HTML
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_INTERNET_XML_HTML
       ADD  ( PRIMARY KEY (internet_xml_html_id) ) ;


CREATE TABLE XHB_LINKED_CASE (
       LINKED_CASE_ID       NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_LINKED_CASE
       ADD  ( PRIMARY KEY (LINKED_CASE_ID) ) ;


CREATE TABLE XHB_LINKED_HEARING (
       LINKED_HEARING_ID    NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_LINKED_HEARING
       ADD  ( PRIMARY KEY (LINKED_HEARING_ID) ) ;


CREATE TABLE XHB_LINKED_SH (
       LINKED_SH_ID         NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_LINKED_SH
       ADD  ( PRIMARY KEY (LINKED_SH_ID) ) ;


CREATE TABLE XHB_LIST_DIST_STATUS (
       list_dist_status_id  NUMBER(8) NOT NULL,
       status               VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       list_distribution_id NUMBER(8) NOT NULL
);

CREATE INDEX xhb_list_dist_status_lis_ds_fk ON XHB_LIST_DIST_STATUS
(
       list_distribution_id           ASC
);


ALTER TABLE XHB_LIST_DIST_STATUS
       ADD  ( PRIMARY KEY (list_dist_status_id) ) ;


CREATE TABLE XHB_LIST_DISTRIBUTION (
       list_distribution_id NUMBER(8) NOT NULL,
       distribution_type    VARCHAR2(255) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_LIST_DISTRIBUTION
       ADD  ( PRIMARY KEY (list_distribution_id) ) ;


CREATE TABLE XHB_MESSAGE (
       MESSAGE_ID           NUMBER(8) NOT NULL,
       MESSAGE_FROM         VARCHAR2(255) NULL,
       MESSAGE_TO           VARCHAR2(255) NULL,
       MESSAGE              VARCHAR2(255) NULL,
       TIME_SENT            DATE NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_MESSAGE
       ADD  ( PRIMARY KEY (MESSAGE_ID) ) ;


CREATE TABLE XHB_OBJECT_STATUS (
       OBJECT_STATUS_ID     NUMBER(8) NOT NULL,
       OBJECT_NAME          VARCHAR2(255) NULL,
       OBJECT_ID            NUMBER(38) NULL,
       CREST_OBJECT_ID      NUMBER(38) NULL,
       COURT_ID             NUMBER(5) NULL,
       ACTION               VARCHAR2(255) NULL,
       STATUS               VARCHAR2(255) NULL,
       TIMESTAMP            DATE NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_OBJECT_STATUS
       ADD  ( PRIMARY KEY (OBJECT_STATUS_ID) ) ;


CREATE TABLE XHB_OFFENCE (
       OFFENCE_ID           NUMBER(8) NOT NULL,
       CREST_OFFENCE_ID     NUMBER(8) NULL,
       CREST_OFFENCE_SEQ_NO NUMBER(5) NULL,
       CREST_OFFENCE_FREETEXT VARCHAR2(240) NULL,
       MULTIPLE             NUMBER(2) NULL,
       CREST_HOO_CLASS_FREETEXT VARCHAR2(3) NULL,
       CREST_HOO_SUBCLASS_FREETEXT VARCHAR2(4) NULL,
       REF_OFFENCE_ID       NUMBER(8) NOT NULL,
       CHARGE_ID            NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       REF_SYSTEM_CODE_ID   NUMBER(8) NULL
);

CREATE INDEX xhb_offence_ref_offence_fk ON XHB_OFFENCE
(
       REF_OFFENCE_ID                 ASC
);

CREATE INDEX xhb_offence_charge_fk ON XHB_OFFENCE
(
       CHARGE_ID                      ASC
);

CREATE INDEX xhb_offence_ref_system_code_fk ON XHB_OFFENCE
(
       REF_SYSTEM_CODE_ID             ASC
);


ALTER TABLE XHB_OFFENCE
       ADD  ( PRIMARY KEY (OFFENCE_ID) ) ;


CREATE TABLE XHB_ORDER (
       ORDER_ID             NUMBER(8) NOT NULL,
       DELIVERY_DATE        DATE NULL,
       SIGNED_BY            VARCHAR2(30) NULL,
       SIGNING_DATE         DATE NULL,
       DATA_XML             CLOB NOT NULL,
       ORDER_DELIVERY_STATUS_ID NUMBER(8) NOT NULL,
       ORDER_STATUS_ID      NUMBER(8) NOT NULL,
       ORDER_TEMPLATE_ID    NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL
);

CREATE INDEX xhb_order_order_status_fk ON XHB_ORDER
(
       ORDER_STATUS_ID                ASC
);

CREATE INDEX xhb_ord_ord_delivery_status_fk ON XHB_ORDER
(
       ORDER_DELIVERY_STATUS_ID       ASC
);

CREATE INDEX xhb_order_order_template_fk ON XHB_ORDER
(
       ORDER_TEMPLATE_ID              ASC
);

CREATE INDEX xhb_ord_def_on_case_fk ON XHB_ORDER
(
       DEFENDANT_ON_CASE_ID           ASC
);


ALTER TABLE XHB_ORDER
       ADD  ( PRIMARY KEY (ORDER_ID) ) ;


CREATE TABLE XHB_ORDER_DELIVERY_STATUS (
       ORDER_DELIVERY_STATUS_ID NUMBER(8) NOT NULL,
       CODE                 VARCHAR2(100) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_ORDER_DELIVERY_STATUS
       ADD  ( PRIMARY KEY (ORDER_DELIVERY_STATUS_ID) ) ;


CREATE TABLE XHB_ORDER_STATUS (
       ORDER_STATUS_ID      NUMBER(8) NOT NULL,
       CODE                 VARCHAR2(100) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_ORDER_STATUS
       ADD  ( PRIMARY KEY (ORDER_STATUS_ID) ) ;


CREATE TABLE XHB_ORDER_TEMPLATE (
       ORDER_TEMPLATE_ID    NUMBER(8) NOT NULL,
       DISPLAY_TRANSFORM_NAME VARCHAR2(255) NOT NULL,
       NARRATIVE_TEMPLATE_NAME VARCHAR2(255) NOT NULL,
       EDITOR_TEMPLATE_NAME VARCHAR2(255) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       ORDER_TYPE_ID        NUMBER(8) NOT NULL,
       obs_ind              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ord_templ_order_type_fk ON XHB_ORDER_TEMPLATE
(
       ORDER_TYPE_ID                  ASC
);


ALTER TABLE XHB_ORDER_TEMPLATE
       ADD  ( PRIMARY KEY (ORDER_TEMPLATE_ID) ) ;


CREATE TABLE XHB_ORDER_TYPE (
       ORDER_TYPE_ID        NUMBER(8) NOT NULL,
       CODE                 VARCHAR2(100) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       REF_DISPOSAL_ID      NUMBER(8) NULL
);

CREATE INDEX xhb_order_type_ref_disposal_fk ON XHB_ORDER_TYPE
(
       REF_DISPOSAL_ID                ASC
);


ALTER TABLE XHB_ORDER_TYPE
       ADD  ( PRIMARY KEY (ORDER_TYPE_ID) ) ;


CREATE TABLE XHB_ORIGINAL_RESULT (
       ORIGINAL_RESULT_ID   NUMBER(8,0) NOT NULL,
       COURT_TYPE           VARCHAR2(1) NULL,
       CREST_DIS_ID         NUMBER(8,0) NULL,
       DEF_ON_CHARGE_OR_OFFENCE VARCHAR2(1) NULL,
       REF_COURT_ID         NUMBER(8,0) NOT NULL,
       DEF_ON_CHARGE_OR_OFFENCE_ID NUMBER(8,0) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       REF_DISPOSAL_ID      NUMBER(8) NOT NULL
);

CREATE INDEX xhb_original_result_ref_dis_fk ON XHB_ORIGINAL_RESULT
(
       REF_DISPOSAL_ID                ASC
);

CREATE INDEX xhb_original_result_ref_crt_fk ON XHB_ORIGINAL_RESULT
(
       REF_COURT_ID                   ASC
);


ALTER TABLE XHB_ORIGINAL_RESULT
       ADD  ( PRIMARY KEY (ORIGINAL_RESULT_ID) ) ;


CREATE TABLE XHB_PLEA (
       plea_id              NUMBER(8) NOT NULL,
       ref_plea_id          NUMBER(8) NULL,
       other_plea_text      VARCHAR2(255) NULL,
       breach_admitted      VARCHAR2(1) NULL,
       alt_ref_offence_id   NUMBER(8) NULL,
       arraignment_date     DATE NULL,
       def_on_charge_or_offence VARCHAR2(1) NULL,
       obs_ind              VARCHAR2(1) NULL,
       DEFENDANT_CHARGE_ID  NUMBER(8) NULL,
       DEFENDANT_ON_OFFENCE_ID NUMBER(8) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_plea_def_charge_fk ON XHB_PLEA
(
       DEFENDANT_CHARGE_ID            ASC
);

CREATE INDEX xhb_plea_def_on_offence_fk ON XHB_PLEA
(
       DEFENDANT_ON_OFFENCE_ID        ASC
);


ALTER TABLE XHB_PLEA
       ADD  ( PRIMARY KEY (plea_id) ) ;


CREATE TABLE XHB_PUBLIC_NOTICE (
       PUBLIC_NOTICE_ID     NUMBER(8) NOT NULL,
       PUBLIC_NOTICE_DESC   VARCHAR2(255) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       definitive_pn_id     NUMBER(8) NOT NULL
);

CREATE INDEX xhb_public_notice_court_fk ON XHB_PUBLIC_NOTICE
(
       COURT_ID                       ASC
);

CREATE INDEX xhb_public_notice_defin_pub_fk ON XHB_PUBLIC_NOTICE
(
       definitive_pn_id               ASC
);


ALTER TABLE XHB_PUBLIC_NOTICE
       ADD  ( PRIMARY KEY (PUBLIC_NOTICE_ID) ) ;


CREATE TABLE XHB_RECIPIENT (
       recipient_id         NUMBER(8) NOT NULL,
       recipient_name       VARCHAR2(255) NOT NULL,
       fax_number           VARCHAR2(255) NULL,
       email_address        VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       REF_COURT_ID         NUMBER(8) NOT NULL
);

CREATE INDEX xhb_recipient_ref_court_fk ON XHB_RECIPIENT
(
       REF_COURT_ID                   ASC
);


ALTER TABLE XHB_RECIPIENT
       ADD  ( PRIMARY KEY (recipient_id) ) ;


CREATE TABLE XHB_REF_ADVOCATE (
       REF_ADVOCATE_ID      NUMBER(8) NOT NULL,
       IS_GLOBAL            VARCHAR2(1) NULL,
       CREST_ADVOCATE_ID    NUMBER(8) NULL,
       CREST_CHAMBER_ID     NUMBER(8) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       INITIALS             VARCHAR2(4) NULL,
       YEAR_OF_CALL         NUMBER(4) NULL,
       VAT_NO               VARCHAR2(9) NULL,
       BAR_NO               NUMBER(5) NULL,
       HONOURS              VARCHAR2(8) NULL,
       ADV_TYPE_IND         VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       REF_LEGAL_REP_ID     NUMBER(8) NOT NULL,
       REF_CHAMBER_ID       NUMBER(8) NOT NULL
);

CREATE INDEX xhb_ref_advocate_ref_chamb_fk ON XHB_REF_ADVOCATE
(
       REF_CHAMBER_ID                 ASC
);

CREATE INDEX xhb_ref_advocate_ref_leg_rp_fk ON XHB_REF_ADVOCATE
(
       REF_LEGAL_REP_ID               ASC
);


ALTER TABLE XHB_REF_ADVOCATE
       ADD  ( PRIMARY KEY (REF_ADVOCATE_ID) ) ;


CREATE TABLE XHB_REF_CHAMBER (
       REF_CHAMBER_ID       NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       IS_GLOBAL            VARCHAR2(1) NULL,
       DX_REF               VARCHAR2(35) NULL,
       LOCATION_CODE        VARCHAR2(2) NULL,
       CREST_CHAMBER_ID     NUMBER(8) NULL,
       FIRM_NAME            VARCHAR2(35) NULL,
       ADDRESS_ID           NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              INTEGER NOT NULL
);

CREATE INDEX xhb_ref_chamber_address_fk ON XHB_REF_CHAMBER
(
       ADDRESS_ID                     ASC
);

CREATE INDEX xhb_ref_chamber_court_fk ON XHB_REF_CHAMBER
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_CHAMBER
       ADD  ( PRIMARY KEY (REF_CHAMBER_ID) ) ;


CREATE TABLE XHB_REF_COURT (
       REF_COURT_ID         NUMBER(8) NOT NULL,
       COURT_FULL_NAME      VARCHAR2(255) NULL,
       COURT_SHORT_NAME     VARCHAR2(5) NULL,
       NAME_PREFIX          VARCHAR2(11) NULL,
       COURT_TYPE           VARCHAR2(1) NULL,
       CREST_CODE           VARCHAR2(4) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       IS_PSD               VARCHAR2(1) NULL,
       DX_REF               VARCHAR2(35) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       ADDRESS_ID           NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL
);

CREATE INDEX xhb_ref_court_address_fk ON XHB_REF_COURT
(
       ADDRESS_ID                     ASC
);

CREATE INDEX xhb_ref_court_court_fk ON XHB_REF_COURT
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_COURT
       ADD  ( PRIMARY KEY (REF_COURT_ID) ) ;


CREATE TABLE XHB_REF_COURT_REPORTER (
       REF_COURT_REPORTER_ID NUMBER(8) NOT NULL,
       FIRST_NAME           VARCHAR2(35) NULL,
       MIDDLE_NAME          VARCHAR2(35) NULL,
       SURNAME              VARCHAR2(35) NULL,
       CREST_COURT_REPORTER_ID NUMBER(38) NULL,
       INITIALS             VARCHAR2(4) NULL,
       REPORT_METHOD        VARCHAR2(1) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       REF_COURT_REPORTER_FIRM_ID NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL
);

CREATE INDEX xhb_ref_crt_rep_report_firm_fk ON XHB_REF_COURT_REPORTER
(
       REF_COURT_REPORTER_FIRM_ID     ASC
);

CREATE INDEX xhb_ref_court_reporter_crt_fk ON XHB_REF_COURT_REPORTER
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_COURT_REPORTER
       ADD  ( PRIMARY KEY (REF_COURT_REPORTER_ID) ) ;


CREATE TABLE XHB_REF_COURT_REPORTER_FIRM (
       REF_COURT_REPORTER_FIRM_ID NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       DISPLAY_FIRST        VARCHAR2(1) NOT NULL,
       DX_REF               VARCHAR2(35) NULL,
       VAT_NO               VARCHAR2(35) NULL,
       FIRM_NAME            VARCHAR2(35) NULL,
       ADDRESS_ID           NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       VERSION              NUMBER NOT NULL,
       CREST_COURT_REPORTER_FIRM_ID NUMBER(9) NULL
);

CREATE INDEX xhb_ref_court_reporter_addr_fk ON XHB_REF_COURT_REPORTER_FIRM
(
       ADDRESS_ID                     ASC
);

CREATE INDEX xhb_ref_court_rep_f_court_fk ON XHB_REF_COURT_REPORTER_FIRM
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_COURT_REPORTER_FIRM
       ADD  ( PRIMARY KEY (REF_COURT_REPORTER_FIRM_ID) ) ;


CREATE TABLE XHB_REF_DISPOSAL (
       REF_DISPOSAL_ID      NUMBER(8) NOT NULL,
       DISPOSAL_CODE        VARCHAR2(7) NOT NULL,
       DISPOSAL_TITLE       VARCHAR2(80) NULL,
       CREST_MENU_GROUP     VARCHAR2(3) NOT NULL,
       CREST_TEMPLATE_VERSION NUMBER(3) NULL,
       DISP_TITLE1          VARCHAR2(255) NULL,
       DISP_TITLE2          VARCHAR2(255) NULL,
       DVLC_CODE            VARCHAR2(4) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_ref_disposal_court_fk ON XHB_REF_DISPOSAL
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_DISPOSAL
       ADD  ( PRIMARY KEY (REF_DISPOSAL_ID) ) ;


CREATE TABLE XHB_REF_DISPOSAL_MENU (
       REF_DISPOSAL_MENU_ID NUMBER(8) NOT NULL,
       TITLE                VARCHAR2(80) NULL,
       DISPOSAL_CODE        VARCHAR2(7) NULL,
       PARENT               NUMBER(5) NULL,
       ABBREV               VARCHAR2(7) NOT NULL,
       MENU_GROUP           VARCHAR2(3) NOT NULL,
       SEQ_NO               NUMBER(2) NOT NULL,
       CREST_MENU_ITEM_ID   NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              INTEGER NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ref_disposal_menu_court_fk ON XHB_REF_DISPOSAL_MENU
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_DISPOSAL_MENU
       ADD  ( PRIMARY KEY (REF_DISPOSAL_MENU_ID) ) ;


CREATE TABLE XHB_REF_HEARING_TYPE (
       REF_HEARING_TYPE_ID  NUMBER(8) NOT NULL,
       HEARING_TYPE_CODE    VARCHAR2(3) NOT NULL,
       HEARING_TYPE_DESC    VARCHAR2(72) NULL,
       CATEGORY             VARCHAR2(1) NULL,
       SEQ_NO               NUMBER(5) NULL,
       LIST_SEQUENCE        NUMBER(5) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ref_hearing_type_court ON XHB_REF_HEARING_TYPE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_HEARING_TYPE
       ADD  ( PRIMARY KEY (REF_HEARING_TYPE_ID) ) ;


CREATE TABLE XHB_REF_JUDGE (
       REF_JUDGE_ID         NUMBER(8) NOT NULL,
       JUDGE_TYPE           VARCHAR2(255) NULL,
       CREST_JUDGE_ID       NUMBER(8) NULL,
       TITLE                VARCHAR2(25) NULL,
       FIRST_NAME           VARCHAR2(35) NULL,
       MIDDLE_NAME          VARCHAR2(35) NULL,
       SURNAME              VARCHAR2(35) NULL,
       FULL_LIST_TITLE1     VARCHAR2(80) NULL,
       FULL_LIST_TITLE2     VARCHAR2(80) NULL,
       FULL_LIST_TITLE3     VARCHAR2(80) NULL,
       STATS_CODE           VARCHAR2(5) NULL,
       INITIALS             VARCHAR2(4) NULL,
       HONOURS              VARCHAR2(35) NULL,
       JUD_VERS             VARCHAR2(2) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       SOURCE_TABLE         VARCHAR2(30) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL
);

CREATE INDEX xhb_ref_judge_court_fk ON XHB_REF_JUDGE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_JUDGE
       ADD  ( PRIMARY KEY (REF_JUDGE_ID) ) ;


CREATE TABLE XHB_REF_JUSTICE (
       REF_JUSTICE_ID       NUMBER(8) NOT NULL,
       JUSTICE_NAME         VARCHAR2(70) NULL,
       CREST_JUSTICE_ID     NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       PSD_COURT_CODE       VARCHAR2(4) NULL,
       TITLE                VARCHAR2(25) NULL,
       INITIALS             VARCHAR2(4) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ref_justice_court_fk ON XHB_REF_JUSTICE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_JUSTICE
       ADD  ( PRIMARY KEY (REF_JUSTICE_ID) ) ;


CREATE TABLE XHB_REF_LEGAL_REPRESENTATIVE (
       REF_LEGAL_REP_ID     NUMBER(8) NOT NULL,
       FIRST_NAME           VARCHAR2(35) NULL,
       MIDDLE_NAME          VARCHAR2(35) NULL,
       SURNAME              VARCHAR2(35) NULL,
       TITLE                VARCHAR2(255) NULL,
       INITIALS             VARCHAR2(4) NULL,
       LEGAL_REP_TYPE       VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ref_legal_rep_court_fk ON XHB_REF_LEGAL_REPRESENTATIVE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_LEGAL_REPRESENTATIVE
       ADD  ( PRIMARY KEY (REF_LEGAL_REP_ID) ) ;


CREATE TABLE XHB_REF_OFFENCE (
       REF_OFFENCE_ID       NUMBER(8) NOT NULL,
       OFFENCE_CODE         VARCHAR2(8) NOT NULL,
       OFFENCE_DESC         VARCHAR2(240) NULL,
       HO_PROC_TYPE         VARCHAR2(2) NULL,
       HO_CLASS             VARCHAR2(3) NULL,
       HO_SUB_CLASS         VARCHAR2(2) NULL,
       DVLC_CODE            VARCHAR2(4) NULL,
       OFFENCE_TYPE         VARCHAR2(1) NULL,
       STATUTE              VARCHAR2(100) NULL,
       OFFENCE_CLASS        VARCHAR2(1) NULL,
       ACT_SECTION          VARCHAR2(25) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       OFFENCE_DESC2        VARCHAR2(240) NULL,
       OFFENCE_GROUP        VARCHAR2(1) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_ref_offence_court_fk ON XHB_REF_OFFENCE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_OFFENCE
       ADD  ( PRIMARY KEY (REF_OFFENCE_ID) ) ;


CREATE TABLE XHB_REF_PROSECUTOR_AGENCY (
       REF_PROSECUTOR_AGENCY_ID NUMBER(8) NOT NULL,
       TITLE                VARCHAR2(25) NULL,
       PROSECUTOR_NAME_1    VARCHAR2(35) NULL,
       PROSECUTOR_NAME_2    VARCHAR2(35) NULL,
       PROSECUTOR_NAME_3    VARCHAR2(35) NOT NULL,
       INITIALS             VARCHAR2(4) NULL,
       ADDRESS_ID           NUMBER(8) NOT NULL,
       CREST_OPPOSER_ID     VARCHAR2(8) NOT NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       CPS_CODE             VARCHAR2(4) NULL,
       DX_REF               VARCHAR2(35) NULL,
       OBS_IND              VARCHAR2(1) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_ref_pros_agcy_court_fk ON XHB_REF_PROSECUTOR_AGENCY
(
       COURT_ID                       ASC
);

CREATE INDEX xhb_ref_pros_agcy_address_fk ON XHB_REF_PROSECUTOR_AGENCY
(
       ADDRESS_ID                     ASC
);


ALTER TABLE XHB_REF_PROSECUTOR_AGENCY
       ADD  ( PRIMARY KEY (REF_PROSECUTOR_AGENCY_ID) ) ;


CREATE TABLE XHB_REF_SOLICITOR (
       SOLICITOR_ID         NUMBER(8) NOT NULL,
       CREST_SOLICITOR_NAME VARCHAR2(40) NULL,
       IS_IN_CREST          VARCHAR2(1) NOT NULL,
       REF_LEGAL_REP_ID     NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       ref_solicitor_firm_id NUMBER(8) NOT NULL
);

CREATE INDEX xhb_solicitor_ref_legal_rep_id ON XHB_REF_SOLICITOR
(
       REF_LEGAL_REP_ID               ASC
);


ALTER TABLE XHB_REF_SOLICITOR
       ADD  ( PRIMARY KEY (SOLICITOR_ID) ) ;


CREATE TABLE XHB_REF_SOLICITOR_FIRM (
       REF_SOLICITOR_FIRM_ID NUMBER(8) NOT NULL,
       SOLICITOR_FIRM_NAME  VARCHAR2(35) NULL,
       CREST_SOF_ID         NUMBER(8) NULL,
       COURT_ID             NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       SHORT_NAME           VARCHAR2(28) NULL,
       DX_REF               VARCHAR2(35) NULL,
       VAT_NO               VARCHAR2(9) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       ADDRESS_ID           NUMBER(8) NULL
);

CREATE INDEX xhb_ref_solicitor_firm_crt_fk ON XHB_REF_SOLICITOR_FIRM
(
       COURT_ID                       ASC
);

CREATE INDEX xhb_ref_solicitor_firm_addr_fk ON XHB_REF_SOLICITOR_FIRM
(
       ADDRESS_ID                     ASC
);


ALTER TABLE XHB_REF_SOLICITOR_FIRM
       ADD  ( PRIMARY KEY (REF_SOLICITOR_FIRM_ID) ) ;


CREATE TABLE XHB_REF_SYSTEM_CODE (
       REF_SYSTEM_CODE_ID   NUMBER(8) NOT NULL,
       CODE                 VARCHAR2(10) NOT NULL,
       CODE_TYPE            VARCHAR2(20) NOT NULL,
       CODE_TITLE           VARCHAR2(30) NULL,
       DE_CODE              VARCHAR2(150) NOT NULL,
       REF_CODE_ORDER       NUMBER(38) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       COURT_ID             NUMBER(38) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL
);

CREATE INDEX xhb_ref_system_code_court_fk ON XHB_REF_SYSTEM_CODE
(
       COURT_ID                       ASC
);


ALTER TABLE XHB_REF_SYSTEM_CODE
       ADD  ( PRIMARY KEY (REF_SYSTEM_CODE_ID) ) ;


CREATE TABLE XHB_SCHED_HEARING_ATTENDEE (
       SH_ATTENDEE_ID       NUMBER(8) NOT NULL,
       ATTENDEE_TYPE        VARCHAR2(2) NOT NULL,
       SCHEDULED_HEARING_ID NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       SH_STAFF_ID          NUMBER(8) NULL,
       SH_LEG_REP_ID        NUMBER(8) NULL,
       SH_JUSTICE_ID        NUMBER(8) NULL,
       REF_JUDGE_ID         NUMBER(8) NULL,
       REF_COURT_REPORTER_ID NUMBER(8) NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);

CREATE INDEX xhb_sched_hear_att_sched_hr_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       SCHEDULED_HEARING_ID           ASC
);

CREATE INDEX xhb_sch_hr_sh_staff_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       SH_STAFF_ID                    ASC
);

CREATE INDEX xhb_sch_hr_sh_leg_rep_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       SH_LEG_REP_ID                  ASC
);

CREATE INDEX xhb_sch_hr_sh_just_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       SH_JUSTICE_ID                  ASC
);

CREATE INDEX xhb_sch_hr_ref_judge_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       REF_JUDGE_ID                   ASC
);

CREATE INDEX xhb_sch_hr_ref_crt_rep_fk ON XHB_SCHED_HEARING_ATTENDEE
(
       REF_COURT_REPORTER_ID          ASC
);


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( PRIMARY KEY (SH_ATTENDEE_ID) ) ;


CREATE TABLE XHB_SCHED_HEARING_DEFENDANT (
       SCHED_HEAR_DEF_ID    NUMBER(8) NOT NULL,
       SCHEDULED_HEARING_ID NUMBER(8) NOT NULL,
       DEFENDANT_ON_CASE_ID NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);

CREATE INDEX xhb_sched_hear_def_df_on_cs_fk ON XHB_SCHED_HEARING_DEFENDANT
(
       DEFENDANT_ON_CASE_ID           ASC
);

CREATE INDEX xhb_sched_hear_def_sched_hr_fk ON XHB_SCHED_HEARING_DEFENDANT
(
       SCHEDULED_HEARING_ID           ASC
);


ALTER TABLE XHB_SCHED_HEARING_DEFENDANT
       ADD  ( PRIMARY KEY (SCHED_HEAR_DEF_ID) ) ;


CREATE TABLE XHB_SCHEDULED_HEARING (
       SCHEDULED_HEARING_ID NUMBER(8) NOT NULL,
       SEQUENCE_NO          NUMBER(3) NOT NULL,
       NOT_BEFORE_TIME      DATE NULL,
       ORIGINAL_TIME        DATE NULL,
       LISTING_NOTE         VARCHAR2(78) NULL,
       HEARING_PROGRESS     NUMBER(1) NULL,
       SITTING_ID           NUMBER(8) NOT NULL,
       HEARING_ID           NUMBER(8) NOT NULL,
       MOVED_FROM           VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LINKED_SH_ID         NUMBER(8) NULL,
       END_TIME             DATE NULL,
       START_TIME           DATE NULL,
       DATE_OF_HEARING      DATE NULL,
       is_case_active       VARCHAR2(1) NULL
);

CREATE INDEX xhb_sched_hear_hearing_fk ON XHB_SCHEDULED_HEARING
(
       HEARING_ID                     ASC
);

CREATE INDEX xhb_sched_hear_sitting_fk ON XHB_SCHEDULED_HEARING
(
       SITTING_ID                     ASC
);


ALTER TABLE XHB_SCHEDULED_HEARING
       ADD  ( PRIMARY KEY (SCHEDULED_HEARING_ID) ) ;


CREATE TABLE XHB_SECURITY_GROUP (
       group_name           VARCHAR2(255) NOT NULL,
       description          VARCHAR2(255) NULL
);


ALTER TABLE XHB_SECURITY_GROUP
       ADD  ( PRIMARY KEY (group_name) ) ;


CREATE TABLE XHB_SECURITY_GROUP_ROLE (
       group_name           VARCHAR2(255) NOT NULL,
       role_name            VARCHAR2(255) NOT NULL
);


ALTER TABLE XHB_SECURITY_GROUP_ROLE
       ADD  ( PRIMARY KEY (group_name, role_name) ) ;


CREATE TABLE XHB_SECURITY_ROLE (
       role_name            VARCHAR2(255) NOT NULL,
       description          VARCHAR2(255) NULL
);


ALTER TABLE XHB_SECURITY_ROLE
       ADD  ( PRIMARY KEY (role_name) ) ;


CREATE TABLE XHB_SH_JUDGE (
       SH_JUDGE_ID          NUMBER(8) NOT NULL,
       DEPUTY_HCJ           VARCHAR2(1) NULL,
       REF_JUDGE_ID         NUMBER(8) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       SH_ATTENDEE_ID       NUMBER(8) NOT NULL
);

CREATE INDEX xhb_sh_judge_ref_judge_fk ON XHB_SH_JUDGE
(
       REF_JUDGE_ID                   ASC
);

CREATE INDEX xhb_sh_judge_sched_hear_att_fk ON XHB_SH_JUDGE
(
       SH_ATTENDEE_ID                 ASC
);


ALTER TABLE XHB_SH_JUDGE
       ADD  ( PRIMARY KEY (SH_JUDGE_ID) ) ;


CREATE TABLE XHB_SH_JUSTICE (
       SH_JUSTICE_ID        NUMBER(8) NOT NULL,
       JUSTICE_NAME         VARCHAR2(70) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       HEARING_ID           NUMBER(8) NULL
);


ALTER TABLE XHB_SH_JUSTICE
       ADD  ( PRIMARY KEY (SH_JUSTICE_ID) ) ;


CREATE TABLE XHB_SH_LEG_REP (
       SH_LEG_REP_ID        NUMBER(8) NOT NULL,
       CREST_SEQUENCE_NO    NUMBER(5) NULL,
       LEGAL_ROLE           VARCHAR2(1) NULL,
       IS_SIGNED_IN         VARCHAR2(1) NULL,
       SOL_FIRM_OR_REF_LEGAL_REP VARCHAR2(1) NULL,
       SCHED_HEAR_DEF_ID    NUMBER(8) NOT NULL,
       REF_LEGAL_REP_ID     NUMBER(8) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CC_INFO_ID           NUMBER(8) NULL,
       REF_SOLICITOR_FIRM_ID NUMBER(8) NOT NULL,
       REF_DEFENCE_CATEGORY_ID NUMBER(8) NULL
);

CREATE INDEX xhb_sh_leg_rep_sch_hear_def_fk ON XHB_SH_LEG_REP
(
       SCHED_HEAR_DEF_ID              ASC
);

CREATE INDEX xhb_sh_leg_rep_cc_info_fk ON XHB_SH_LEG_REP
(
       CC_INFO_ID                     ASC
);

CREATE INDEX xhb_sh_leg_rep_ref_leg_rep_fk ON XHB_SH_LEG_REP
(
       REF_LEGAL_REP_ID               ASC
);

CREATE INDEX xhb_sh_leg_rep_ref_sol_firm_fk ON XHB_SH_LEG_REP
(
       REF_SOLICITOR_FIRM_ID          ASC
);


ALTER TABLE XHB_SH_LEG_REP
       ADD  ( PRIMARY KEY (SH_LEG_REP_ID) ) ;


CREATE TABLE XHB_SH_STAFF (
       SH_STAFF_ID          NUMBER(8) NOT NULL,
       STAFF_ROLE           VARCHAR2(2) NOT NULL,
       STAFF_NAME           VARCHAR2(255) NOT NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL
);


ALTER TABLE XHB_SH_STAFF
       ADD  ( PRIMARY KEY (SH_STAFF_ID) ) ;


CREATE TABLE XHB_SITTING (
       SITTING_ID           NUMBER(8) NOT NULL,
       SITTING_SEQUENCE_NO  NUMBER(1) NULL,
       IS_SITTING_JUDGE     VARCHAR2(1) NULL,
       SITTING_TIME         DATE NULL,
       SITTING_NOTE         VARCHAR2(80) NULL,
       REF_JUSTICE1_ID      NUMBER(38) NULL,
       REF_JUSTICE2_ID      NUMBER(38) NULL,
       REF_JUSTICE3_ID      NUMBER(38) NULL,
       REF_JUSTICE4_ID      NUMBER(38) NULL,
       IS_FLOATING          VARCHAR2(1) NOT NULL,
       LIST_ID              NUMBER(8) NOT NULL,
       REF_JUDGE_ID         NUMBER(8) NULL,
       COURT_ROOM_ID        NUMBER(8) NOT NULL,
       COURT_SITE_ID        NUMBER(8) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL,
       JUSTICENAME4         VARCHAR2(35) NULL,
       JUSTICENAME3         VARCHAR2(35) NULL,
       JUSTICENAME2         VARCHAR2(35) NULL,
       JUSTICENAME1         VARCHAR2(35) NULL
);

CREATE INDEX xhb_sitting_ref_judge_fk ON XHB_SITTING
(
       REF_JUDGE_ID                   ASC
);

CREATE INDEX xhb_sitting_hearing_list_fk ON XHB_SITTING
(
       LIST_ID                        ASC
);

CREATE INDEX xhb_sitting_court_room_fk ON XHB_SITTING
(
       COURT_ROOM_ID                  ASC
);

CREATE INDEX xhb_sitting_court_site_fk ON XHB_SITTING
(
       COURT_SITE_ID                  ASC
);


ALTER TABLE XHB_SITTING
       ADD  ( PRIMARY KEY (SITTING_ID) ) ;


CREATE TABLE XHB_SYS_AUDIT (
       SYS_AUDIT_ID         NUMBER NOT NULL,
       TABLE_TO_AUDIT       VARCHAR2(255) NOT NULL,
       AUDIT_TABLE          VARCHAR2(255) NOT NULL,
       AUDITABLE            VARCHAR2(1) NOT NULL
);


ALTER TABLE XHB_SYS_AUDIT
       ADD  ( PRIMARY KEY (SYS_AUDIT_ID) ) ;


CREATE TABLE XHB_SYS_USER_INFORMATION (
       MERCATOR_USER_NAME   VARCHAR2(255) NOT NULL,
       CONNECTION_POOL_USER_NAME VARCHAR(255) NOT NULL
);

delete from XHB_SYS_USER_INFORMATION;

insert into XHB_SYS_USER_INFORMATION (
select NVL(sys_context('USERENV', 'SESSION_USER'), 'XHIBIT'), 'MERCATOR' from dual
);


CREATE TABLE XHB_TERMINAL (
       TERMINAL_ID          NUMBER(8) NOT NULL,
       LOCATION             VARCHAR2(255) NULL,
       DESCRIPTION          NUMBER(5) NULL,
       TERMINAL_IP          VARCHAR2(15) NOT NULL,
       TERMINAL_NAME        VARCHAR2(255) NOT NULL,
       COURT_ROOM_ID        NUMBER(8) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       courtroom_or_site    VARCHAR2(2) NULL,
       COURT_SITE_ID        NUMBER(8) NULL
);

CREATE INDEX xhb_terminal_court_room_fk ON XHB_TERMINAL
(
       COURT_ROOM_ID                  ASC
);

CREATE INDEX xhb_terminal_court_site_fk ON XHB_TERMINAL
(
       COURT_SITE_ID                  ASC
);


ALTER TABLE XHB_TERMINAL
       ADD  ( PRIMARY KEY (TERMINAL_ID) ) ;


CREATE TABLE XHB_TERMINAL_REFERENCE (
       ter_ref_id           NUMBER(8) NOT NULL,
       reference_value      VARCHAR2(255) NOT NULL,
       reference_name       VARCHAR2(255) NOT NULL,
       category             VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_TERMINAL_REFERENCE
       ADD  ( PRIMARY KEY (ter_ref_id) ) ;


CREATE TABLE XHB_VERDICT (
       VERDICT_ID           NUMBER(8) NOT NULL,
       OBS_IND              VARCHAR2(1) NULL,
       DEF_ON_CHARGE_OR_OFFENCE VARCHAR2(1) NULL,
       JURORS_DISSENTING    NUMBER(5) NULL,
       JURORS_ASSENTING     NUMBER(5) NULL,
       ALT_REF_OFFENCE_ID   NUMBER(8) NULL,
       VERDICT_DATE         DATE NULL,
       REF_VERDICT_ID       NUMBER(8) NULL,
       VERSION              NUMBER NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       other_verdict_text   VARCHAR2(255) NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       DEFENDANT_ON_OFFENCE_ID NUMBER(8) NULL,
       DEFENDANT_CHARGE_ID  NUMBER(8) NULL
);

CREATE INDEX xhb_verdict_def_on_off_fk ON XHB_VERDICT
(
       DEFENDANT_ON_OFFENCE_ID        ASC
);

CREATE INDEX xhb_verdict_def_charge_fk ON XHB_VERDICT
(
       DEFENDANT_CHARGE_ID            ASC
);


ALTER TABLE XHB_VERDICT
       ADD  ( PRIMARY KEY (VERDICT_ID) ) ;


CREATE TABLE XHB_WLL_DIST_STATUS (
       wll_dist_status_id   NUMBER(8) NOT NULL,
       status               VARCHAR2(255) NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_WLL_DIST_STATUS
       ADD  ( PRIMARY KEY (wll_dist_status_id) ) ;


CREATE TABLE XHB_WLL_RECIPIENT (
       wll_recipient_id     NUMBER(8) NOT NULL,
       crest_solicitor_firm_id NUMBER(8) NOT NULL,
       crest_court_id       NUMBER(8) NOT NULL,
       solicitor_firm_name  VARCHAR2(255) NOT NULL,
       solictior_firm_address VARCHAR2(255) NULL,
       solicitor_firm_fax   VARCHAR2(255) NULL,
       solicitor_firm_email VARCHAR2(255) NULL,
       distribution_type    VARCHAR2(1) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_WLL_RECIPIENT
       ADD  ( PRIMARY KEY (wll_recipient_id) ) ;


CREATE TABLE XHB_XGROUP (
       XGROUP_ID            NUMBER(8) NOT NULL,
       ROLES                VARCHAR2(255) NOT NULL,
       TYPE                 VARCHAR2(255) NOT NULL,
       DESCRIPTION          VARCHAR2(255) NOT NULL,
       NAME                 VARCHAR2(255) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_XGROUP
       ADD  ( PRIMARY KEY (XGROUP_ID) ) ;


CREATE TABLE XHB_XROLE (
       XROLE_ID             NUMBER(8) NOT NULL,
       GROUPS               VARCHAR2(255) NOT NULL,
       TYPE                 VARCHAR2(255) NOT NULL,
       DESCRIPTION          VARCHAR2(255) NOT NULL,
       NAME                 VARCHAR2(255) NOT NULL,
       LAST_UPDATE_DATE     DATE NOT NULL,
       CREATION_DATE        DATE NOT NULL,
       CREATED_BY           VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY      VARCHAR2(30) NOT NULL,
       VERSION              NUMBER NOT NULL
);


ALTER TABLE XHB_XROLE
       ADD  ( PRIMARY KEY (XROLE_ID) ) ;

/* Empty table will cause syntax error. */
/*
CREATE TABLE XXX_DUMMY_TABLE_FOR_AUDITING (
);*/

declare
-- Dynamic SQL to create audit tables as below
-- NOTE: FOR PRODUCTION MODIFY TABLESPACE USERS TO AUDITD
--create table jnk
--tablespace USERS
--storage (initial 1M next 1M)
--as select * from xhb_address
cursor c1 is select table_name from user_tables
  where table_name like 'XHB%'
  and table_name not in ('XHB_SYS_AUDIT', 'XHB_SYS_USER_INFORMATION');
l_aud_table varchar2(255);
l_org_table varchar2(255);
l_str1  varchar2(255) := ' ; ';
l_str2  varchar2(255) := ' CREATE TABLE ';
l_str3   varchar2(255) := ' AS SELECT * FROM ';
l_str4   varchar2(255) := ' TABLESPACE USERS ';
l_stmt   varchar2(500);
begin
for record in c1 loop
if c1%FOUND then
  l_org_table := record.table_name;
  l_aud_table := replace(record.table_name, 'XHB', 'AUD');
  l_stmt := l_str2||l_aud_table||l_str4||l_str3||l_org_table;
  DBMS_OUTPUT.PUT_LINE(l_stmt);
  EXECUTE IMMEDIATE l_stmt;
end if;
end loop;
end;
/
