
ALTER TABLE XHB_BREACH
       ADD  ( FOREIGN KEY (REF_COURT_ID)
                             REFERENCES XHB_REF_COURT ) ;


ALTER TABLE XHB_BREACH
       ADD  ( FOREIGN KEY (CHARGE_ID)
                             REFERENCES XHB_CHARGE ) ;


ALTER TABLE XHB_CASE
       ADD  ( FOREIGN KEY (REF_COURT_ID)
                             REFERENCES XHB_REF_COURT ) ;


ALTER TABLE XHB_CASE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_CASE_PROSECUTOR_AGENCY
       ADD  ( FOREIGN KEY (REF_PROSECUTOR_AGENCY_ID)
                             REFERENCES XHB_REF_PROSECUTOR_AGENCY ) ;


ALTER TABLE XHB_CASE_PROSECUTOR_AGENCY
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_CHARGE
       ADD  ( FOREIGN KEY (REF_SYSTEM_CODE_ID)
                             REFERENCES XHB_REF_SYSTEM_CODE ) ;


ALTER TABLE XHB_CHARGE
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_CHARGE_DIFFERENCES
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_CHARGE_DIFFERENCES
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_CONFIGURED_PUBLIC_NOTICE
       ADD  ( FOREIGN KEY (PUBLIC_NOTICE_ID)
                             REFERENCES XHB_PUBLIC_NOTICE ) ;


ALTER TABLE XHB_CONFIGURED_PUBLIC_NOTICE
       ADD  ( FOREIGN KEY (COURT_ROOM_ID)
                             REFERENCES XHB_COURT_ROOM ) ;


ALTER TABLE XHB_CONTACT_DETAIL
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_COURT
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_COURT_LOG_CATEGORY
       ADD  ( FOREIGN KEY (CATEGORY_DESC_ID)
                             REFERENCES XHB_COURT_LOG_CATEGORY_DESC ) ;


ALTER TABLE XHB_COURT_LOG_CATEGORY
       ADD  ( FOREIGN KEY (EVENT_DESC_ID)
                             REFERENCES XHB_COURT_LOG_EVENT_DESC ) ;


ALTER TABLE XHB_COURT_LOG_ENTRY
       ADD  ( FOREIGN KEY (EVENT_DESC_ID)
                             REFERENCES XHB_COURT_LOG_EVENT_DESC ) ;


ALTER TABLE XHB_COURT_LOG_ENTRY
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_COURT_ROOM
       ADD  ( FOREIGN KEY (COURT_SITE_ID)
                             REFERENCES XHB_COURT_SITE ) ;


ALTER TABLE XHB_COURT_SITE
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_COURT_SITE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_CR_LIVE_STATUS
       ADD  ( FOREIGN KEY (SCHEDULED_HEARING_ID)
                             REFERENCES XHB_SCHEDULED_HEARING ) ;


ALTER TABLE XHB_CR_LIVE_STATUS
       ADD  ( FOREIGN KEY (COURT_ROOM_ID)
                             REFERENCES XHB_COURT_ROOM ) ;


ALTER TABLE XHB_CR_LIVE_STATUS
       ADD  ( FOREIGN KEY (cr_live_status_desc_id)
                             REFERENCES XHB_CR_LIVE_STATUS_DESC ) ;


ALTER TABLE XHB_DAILY_LIST_XML
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_DEF_HEARING_RECORD
       ADD  ( FOREIGN KEY (HEARING_ID)
                             REFERENCES XHB_HEARING ) ;


ALTER TABLE XHB_DEF_HEARING_RECORD
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DEFENDANT
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_DEFENDANT
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_DEFENDANT_CHARGE
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DEFENDANT_CHARGE
       ADD  ( FOREIGN KEY (CHARGE_ID)
                             REFERENCES XHB_CHARGE ) ;


ALTER TABLE XHB_DEFENDANT_ON_CASE
       ADD  ( FOREIGN KEY (DEFENDANT_ID)
                             REFERENCES XHB_DEFENDANT ) ;


ALTER TABLE XHB_DEFENDANT_ON_CASE
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_DEFENDANT_ON_OFFENCE
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DEFENDANT_ON_OFFENCE
       ADD  ( FOREIGN KEY (ORIGINAL_RESULT_ID)
                             REFERENCES XHB_ORIGINAL_RESULT ) ;


ALTER TABLE XHB_DEFENDANT_ON_OFFENCE
       ADD  ( FOREIGN KEY (OFFENCE_ID)
                             REFERENCES XHB_OFFENCE ) ;


ALTER TABLE XHB_DEFENDANT_REFERENCE
       ADD  ( FOREIGN KEY (DEFENDANT_ID)
                             REFERENCES XHB_DEFENDANT ) ;


ALTER TABLE XHB_DIRECTION_ATTEND
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DIRECTION_ATTEND
       ADD  ( FOREIGN KEY (DIRECTIONS_FOR_CASE_ID)
                             REFERENCES XHB_DIRECTIONS_FOR_CASE ) ;


ALTER TABLE XHB_DIRECTIONS_FOR_CASE
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_DIRECTIONS_FOR_DEFENDANT
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DISPOSAL
       ADD  ( FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID)
                             REFERENCES XHB_DEFENDANT_ON_OFFENCE ) ;


ALTER TABLE XHB_DISPOSAL
       ADD  ( FOREIGN KEY (REF_DISPOSAL_ID)
                             REFERENCES XHB_REF_DISPOSAL ) ;


ALTER TABLE XHB_DISPOSAL
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_DISPOSAL_DETAIL
       ADD  ( FOREIGN KEY (ORIGINAL_RESULT_ID)
                             REFERENCES XHB_ORIGINAL_RESULT ) ;


ALTER TABLE XHB_DISPOSAL_REFERENCE
       ADD  ( FOREIGN KEY (DISPOSAL_ID)
                             REFERENCES XHB_DISPOSAL ) ;


ALTER TABLE XHB_EXPORTA
       ADD  ( FOREIGN KEY (HEARING_ID)
                             REFERENCES XHB_HEARING ) ;


ALTER TABLE XHB_HEARING
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_HEARING
       ADD  ( FOREIGN KEY (REF_HEARING_TYPE_ID)
                             REFERENCES XHB_REF_HEARING_TYPE ) ;


ALTER TABLE XHB_HEARING
       ADD  ( FOREIGN KEY (CASE_ID)
                             REFERENCES XHB_CASE ) ;


ALTER TABLE XHB_HEARING_LIST
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_INTERNET_XML_HTML
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_LIST_DIST_STATUS
       ADD  ( FOREIGN KEY (list_distribution_id)
                             REFERENCES XHB_LIST_DISTRIBUTION ) ;


ALTER TABLE XHB_OFFENCE
       ADD  ( FOREIGN KEY (REF_SYSTEM_CODE_ID)
                             REFERENCES XHB_REF_SYSTEM_CODE ) ;


ALTER TABLE XHB_OFFENCE
       ADD  ( FOREIGN KEY (CHARGE_ID)
                             REFERENCES XHB_CHARGE ) ;


ALTER TABLE XHB_OFFENCE
       ADD  ( FOREIGN KEY (REF_OFFENCE_ID)
                             REFERENCES XHB_REF_OFFENCE ) ;


ALTER TABLE XHB_ORDER
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_ORDER
       ADD  ( FOREIGN KEY (ORDER_TEMPLATE_ID)
                             REFERENCES XHB_ORDER_TEMPLATE ) ;


ALTER TABLE XHB_ORDER
       ADD  ( FOREIGN KEY (ORDER_DELIVERY_STATUS_ID)
                             REFERENCES XHB_ORDER_DELIVERY_STATUS ) ;


ALTER TABLE XHB_ORDER
       ADD  ( FOREIGN KEY (ORDER_STATUS_ID)
                             REFERENCES XHB_ORDER_STATUS ) ;


ALTER TABLE XHB_ORDER_TEMPLATE
       ADD  ( FOREIGN KEY (ORDER_TYPE_ID)
                             REFERENCES XHB_ORDER_TYPE ) ;


ALTER TABLE XHB_ORDER_TYPE
       ADD  ( FOREIGN KEY (REF_DISPOSAL_ID)
                             REFERENCES XHB_REF_DISPOSAL ) ;


ALTER TABLE XHB_ORIGINAL_RESULT
       ADD  ( FOREIGN KEY (REF_DISPOSAL_ID)
                             REFERENCES XHB_REF_DISPOSAL ) ;


ALTER TABLE XHB_ORIGINAL_RESULT
       ADD  ( FOREIGN KEY (REF_COURT_ID)
                             REFERENCES XHB_REF_COURT ) ;


ALTER TABLE XHB_PLEA
       ADD  ( FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID)
                             REFERENCES XHB_DEFENDANT_ON_OFFENCE ) ;


ALTER TABLE XHB_PLEA
       ADD  ( FOREIGN KEY (DEFENDANT_CHARGE_ID)
                             REFERENCES XHB_DEFENDANT_CHARGE ) ;


ALTER TABLE XHB_PUBLIC_NOTICE
       ADD  ( FOREIGN KEY (definitive_pn_id)
                             REFERENCES XHB_DEFINITIVE_PUBLIC_NOTICE ) ;


ALTER TABLE XHB_PUBLIC_NOTICE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_RECIPIENT
       ADD  ( FOREIGN KEY (REF_COURT_ID)
                             REFERENCES XHB_REF_COURT ) ;


ALTER TABLE XHB_REF_ADVOCATE
       ADD  ( FOREIGN KEY (REF_CHAMBER_ID)
                             REFERENCES XHB_REF_CHAMBER ) ;


ALTER TABLE XHB_REF_ADVOCATE
       ADD  ( FOREIGN KEY (REF_LEGAL_REP_ID)
                             REFERENCES XHB_REF_LEGAL_REPRESENTATIVE ) ;


ALTER TABLE XHB_REF_CHAMBER
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_CHAMBER
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_REF_COURT
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_COURT
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_REF_COURT_REPORTER
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_COURT_REPORTER
       ADD  ( FOREIGN KEY (REF_COURT_REPORTER_FIRM_ID)
                             REFERENCES XHB_REF_COURT_REPORTER_FIRM ) ;


ALTER TABLE XHB_REF_COURT_REPORTER_FIRM
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_COURT_REPORTER_FIRM
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_REF_DISPOSAL
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_DISPOSAL_MENU
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_HEARING_TYPE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_JUDGE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_JUSTICE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_LEGAL_REPRESENTATIVE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_OFFENCE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_PROSECUTOR_AGENCY
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_REF_PROSECUTOR_AGENCY
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_SOLICITOR
       ADD  ( FOREIGN KEY (REF_LEGAL_REP_ID)
                             REFERENCES XHB_REF_LEGAL_REPRESENTATIVE ) ;


ALTER TABLE XHB_REF_SOLICITOR_FIRM
       ADD  ( FOREIGN KEY (ADDRESS_ID)
                             REFERENCES XHB_ADDRESS ) ;


ALTER TABLE XHB_REF_SOLICITOR_FIRM
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_REF_SYSTEM_CODE
       ADD  ( FOREIGN KEY (COURT_ID)
                             REFERENCES XHB_COURT ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (REF_COURT_REPORTER_ID)
                             REFERENCES XHB_REF_COURT_REPORTER ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (REF_JUDGE_ID)
                             REFERENCES XHB_REF_JUDGE ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (SH_JUSTICE_ID)
                             REFERENCES XHB_SH_JUSTICE ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (SH_LEG_REP_ID)
                             REFERENCES XHB_SH_LEG_REP ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (SH_STAFF_ID)
                             REFERENCES XHB_SH_STAFF ) ;


ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
       ADD  ( FOREIGN KEY (SCHEDULED_HEARING_ID)
                             REFERENCES XHB_SCHEDULED_HEARING ) ;


ALTER TABLE XHB_SCHED_HEARING_DEFENDANT
       ADD  ( FOREIGN KEY (SCHEDULED_HEARING_ID)
                             REFERENCES XHB_SCHEDULED_HEARING ) ;


ALTER TABLE XHB_SCHED_HEARING_DEFENDANT
       ADD  ( FOREIGN KEY (DEFENDANT_ON_CASE_ID)
                             REFERENCES XHB_DEFENDANT_ON_CASE ) ;


ALTER TABLE XHB_SCHEDULED_HEARING
       ADD  ( FOREIGN KEY (SITTING_ID)
                             REFERENCES XHB_SITTING ) ;
ALTER TABLE XHB_SCHEDULED_HEARING
       ADD  ( FOREIGN KEY (HEARING_ID)
                             REFERENCES XHB_HEARING ) ;


ALTER TABLE XHB_SH_JUDGE
       ADD  ( FOREIGN KEY (SH_ATTENDEE_ID)
                             REFERENCES XHB_SCHED_HEARING_ATTENDEE ) ;


ALTER TABLE XHB_SH_JUDGE
       ADD  ( FOREIGN KEY (REF_JUDGE_ID)
                             REFERENCES XHB_REF_JUDGE ) ;


ALTER TABLE XHB_SH_LEG_REP
       ADD  ( FOREIGN KEY (REF_SOLICITOR_FIRM_ID)
                             REFERENCES XHB_REF_SOLICITOR_FIRM ) ;


ALTER TABLE XHB_SH_LEG_REP
       ADD  ( FOREIGN KEY (REF_LEGAL_REP_ID)
                             REFERENCES XHB_REF_LEGAL_REPRESENTATIVE ) ;


ALTER TABLE XHB_SH_LEG_REP
       ADD  ( FOREIGN KEY (CC_INFO_ID)
                             REFERENCES XHB_CC_INFO ) ;


ALTER TABLE XHB_SH_LEG_REP
       ADD  ( FOREIGN KEY (SCHED_HEAR_DEF_ID)
                             REFERENCES XHB_SCHED_HEARING_DEFENDANT ) ;


ALTER TABLE XHB_SITTING
       ADD  ( FOREIGN KEY (COURT_SITE_ID)
                             REFERENCES XHB_COURT_SITE ) ;


ALTER TABLE XHB_SITTING
       ADD  ( FOREIGN KEY (COURT_ROOM_ID)
                             REFERENCES XHB_COURT_ROOM ) ;


ALTER TABLE XHB_SITTING
       ADD  ( FOREIGN KEY (LIST_ID)
                             REFERENCES XHB_HEARING_LIST ) ;


ALTER TABLE XHB_SITTING
       ADD  ( FOREIGN KEY (REF_JUDGE_ID)
                             REFERENCES XHB_REF_JUDGE ) ;


ALTER TABLE XHB_TERMINAL
       ADD  ( FOREIGN KEY (COURT_SITE_ID)
                             REFERENCES XHB_COURT_SITE ) ;


ALTER TABLE XHB_TERMINAL
       ADD  ( FOREIGN KEY (COURT_ROOM_ID)
                             REFERENCES XHB_COURT_ROOM ) ;


ALTER TABLE XHB_VERDICT
       ADD  ( FOREIGN KEY (DEFENDANT_CHARGE_ID)
                             REFERENCES XHB_DEFENDANT_CHARGE ) ;


ALTER TABLE XHB_VERDICT
       ADD  ( FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID)
                             REFERENCES XHB_DEFENDANT_ON_OFFENCE ) ;

