DROP SEQUENCE TMP_ERROR_LOG_SEQ ;
DROP SEQUENCE XHB_ADDRESS_SEQ ;
DROP SEQUENCE XHB_BREACH_SEQ ;
DROP SEQUENCE XHB_CASE_PROSECTOR_AGENCY_SEQ ;
DROP SEQUENCE XHB_CASE_SEQ ;
DROP SEQUENCE XHB_CC_INFO_SEQ ;
DROP SEQUENCE XHB_CHARGE_DIFFERENCES_SEQ ;
DROP SEQUENCE XHB_CHARGE_SEQ ;
DROP SEQUENCE XHB_CONFIGURED_PUBLIC_NOT_SEQ ;
DROP SEQUENCE XHB_CONTACT_DETAIL_SEQ ;
DROP SEQUENCE XHB_COURT_LOG_CATEGORY_SEQ ;
DROP SEQUENCE XHB_COURT_LOG_CAT_DESC_SEQ ;
DROP SEQUENCE XHB_COURT_LOG_ENTRY_SEQ ;
DROP SEQUENCE XHB_COURT_LOG_EVENT_DESC_SEQ ;
DROP SEQUENCE XHB_COURT_ROOM_SEQ ;
DROP SEQUENCE XHB_COURT_SEQ ;
DROP SEQUENCE XHB_COURT_SITE_SEQ ;
DROP SEQUENCE XHB_CR_LIVE_STATUS_DESC_SEQ ;
DROP SEQUENCE XHB_CR_LIVE_STATUS_SEQ ;
DROP SEQUENCE XHB_DAILY_LIST_XML_SEQ ;
DROP SEQUENCE XHB_DEFENDANT_CHARGE_SEQ ;
DROP SEQUENCE XHB_DEFENDANT_ON_CASE_SEQ ;
DROP SEQUENCE XHB_DEFENDANT_ON_OFFENCE_SEQ ;
DROP SEQUENCE XHB_DEFENDANT_REFERENCE_SEQ ;
DROP SEQUENCE XHB_DEFENDANT_SEQ ;
DROP SEQUENCE XHB_DEFINITIVE_PUB_NOTICE_SEQ ;
DROP SEQUENCE XHB_DEF_HEARING_RECORD_SEQ ;
DROP SEQUENCE XHB_DIRECTION_ATTEND_SEQ ;
DROP SEQUENCE XHB_DIR_FOR_CASE_SEQ ;
DROP SEQUENCE XHB_DIR_FOR_DEFENDANT_SEQ ;
DROP SEQUENCE XHB_DISPOSAL_DETAIL_SEQ ;
DROP SEQUENCE XHB_DISPOSAL_REFERENCE_SEQ ;
DROP SEQUENCE XHB_DISPOSAL_SEQ ;
DROP SEQUENCE XHB_DOCUMENT_TYPE_SEQ ;
DROP SEQUENCE XHB_ERROR_DEF_SEQ ;
DROP SEQUENCE XHB_EXPORTA_SEQ ;
DROP SEQUENCE XHB_FIXED_LIST_XML_SEQ ;
DROP SEQUENCE XHB_FORMATTING_IN_SEQ ;
DROP SEQUENCE XHB_FORMATTING_OUT_SEQ ;
DROP SEQUENCE XHB_HEARING_LIST_SEQ ;
DROP SEQUENCE XHB_HEARING_RECORD_SEQ ;
DROP SEQUENCE XHB_HEARING_SEQ ;
DROP SEQUENCE XHB_INTERNET_XML_HTML_SEQ ;
DROP SEQUENCE XHB_LEG_REP_FOR_SCHED_DEF_SEQ ;
DROP SEQUENCE XHB_LINKED_CASE_SEQ ;
DROP SEQUENCE XHB_LINKED_HEARING_SEQ ;
DROP SEQUENCE XHB_LINKED_SH_SEQ ;
DROP SEQUENCE XHB_LIST_DISTRIBUTION_SEQ ;
DROP SEQUENCE XHB_LIST_DIST_STATUS_SEQ ;
DROP SEQUENCE XHB_MESSAGE_SEQ ;
DROP SEQUENCE XHB_OBJECT_STATUS_SEQ ;
DROP SEQUENCE XHB_OFFENCE_SEQ ;
DROP SEQUENCE XHB_ORDER_SEQ ;
DROP SEQUENCE XHB_ORD_DELIVERY_STATUS_SEQ ;
DROP SEQUENCE XHB_ORD_STATUS_SEQ ;
DROP SEQUENCE XHB_ORD_TEMPLATE_SEQ ;
DROP SEQUENCE XHB_ORD_TYPE_SEQ ;
DROP SEQUENCE XHB_ORIGINAL_RESULT_SEQ ;
DROP SEQUENCE XHB_PLEA_SEQ ;
DROP SEQUENCE XHB_PUBLIC_NOTICE_SEQ ;
DROP SEQUENCE XHB_RECIPIENT_SEQ ;
DROP SEQUENCE XHB_REF_ADVOCATE_SEQ ;
DROP SEQUENCE XHB_REF_BREACH_PROC_CODE_SEQ ;
DROP SEQUENCE XHB_REF_CHAMBER_SEQ ;
DROP SEQUENCE XHB_REF_COURT_REPORTER_SEQ ;
DROP SEQUENCE XHB_REF_COURT_REPORT_F_SEQ ;
DROP SEQUENCE XHB_REF_COURT_SEQ ;
DROP SEQUENCE XHB_REF_DEFENCE_CATEGORY_SEQ ;
DROP SEQUENCE XHB_REF_DISPOSAL_MENU_SEQ ;
DROP SEQUENCE XHB_REF_DISPOSAL_SEQ ;
DROP SEQUENCE XHB_REF_HEARING_TYPE_SEQ ;
DROP SEQUENCE XHB_REF_JUDGE_SEQ ;
DROP SEQUENCE XHB_REF_JUSTICE_SEQ ;
DROP SEQUENCE XHB_REF_LEGAL_REP_SEQ ;
DROP SEQUENCE XHB_REF_OFFENCE_SEQ ;
DROP SEQUENCE XHB_REF_PROSECUTOR_AGENCY_SEQ ;
DROP SEQUENCE XHB_REF_SOLICITOR_FIRM_SEQ ;
DROP SEQUENCE XHB_REF_SYSTEM_CODE_SEQ ;
DROP SEQUENCE XHB_RUNNING_LIST_XML_SEQ ;
DROP SEQUENCE XHB_SCHEDULED_HEARING_DEF_SEQ ;
DROP SEQUENCE XHB_SCHEDULED_HEARING_SEQ ;
DROP SEQUENCE XHB_SCHED_HEARING_ATTEND_SEQ ;
DROP SEQUENCE XHB_SH_COURT_REPORTER_SEQ ;
DROP SEQUENCE XHB_SH_JUDGE_SEQ ;
DROP SEQUENCE XHB_SH_JUSTICE_SEQ ;
DROP SEQUENCE XHB_SH_LEG_REP_SEQ ;
DROP SEQUENCE XHB_SH_STAFF_SEQ ;
DROP SEQUENCE XHB_SITTING_SEQ ;
DROP SEQUENCE XHB_SOLICITOR_SEQ ;
DROP SEQUENCE XHB_SYS_AUDIT_SEQ ;
DROP SEQUENCE XHB_TERMINAL_REFERENCE_SEQ ;
DROP SEQUENCE XHB_TERMINAL_SEQ ;
DROP SEQUENCE XHB_VERDICT_SEQ ;
DROP SEQUENCE XHB_WARNED_LIST_XML_SEQ ;
DROP SEQUENCE XHB_WLL_DIST_STATUS_SEQ ;
DROP SEQUENCE XHB_WLL_RECIPIENT_SEQ ;
DROP SEQUENCE XHB_WL_DISTRIBUTION_SEQ ;
DROP SEQUENCE XHB_XGROUP_SEQ ;
DROP SEQUENCE XHB_XROLE_SEQ ;

DROP TABLE XHB_WLL_RECIPIENT CASCADE CONSTRAINTS;

DROP TABLE XHB_WLL_DIST_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_RECIPIENT CASCADE CONSTRAINTS;

DROP TABLE XHB_LIST_DIST_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_LIST_DISTRIBUTION CASCADE CONSTRAINTS;

DROP TABLE XHB_INTERNET_XML_HTML CASCADE CONSTRAINTS;

DROP TABLE XHB_FORMATTING_OUT CASCADE CONSTRAINTS;

DROP TABLE XHB_FORMATTING_IN CASCADE CONSTRAINTS;

DROP TABLE XHB_DOCUMENT_TYPE CASCADE CONSTRAINTS;

DROP TABLE XHB_CR_LIVE_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_CR_LIVE_STATUS_DESC CASCADE CONSTRAINTS;

DROP TABLE XHB_TERMINAL_REFERENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_SECURITY_ROLE CASCADE CONSTRAINTS;

DROP TABLE XHB_SECURITY_GROUP_ROLE CASCADE CONSTRAINTS;

DROP TABLE XHB_SECURITY_GROUP CASCADE CONSTRAINTS;

DROP TABLE XHB_PLEA CASCADE CONSTRAINTS;

DROP TABLE XHB_DIRECTION_ATTEND CASCADE CONSTRAINTS;

DROP TABLE XHB_CONFIGURED_PUBLIC_NOTICE CASCADE CONSTRAINTS;

DROP TABLE XHB_PUBLIC_NOTICE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFINITIVE_PUBLIC_NOTICE CASCADE CONSTRAINTS;

DROP TABLE XHB_VERDICT CASCADE CONSTRAINTS;

DROP TABLE XHB_SH_JUDGE CASCADE CONSTRAINTS;

DROP TABLE XHB_SCHED_HEARING_ATTENDEE CASCADE CONSTRAINTS;

DROP TABLE XHB_SH_STAFF CASCADE CONSTRAINTS;

DROP TABLE XHB_SH_LEG_REP CASCADE CONSTRAINTS;

DROP TABLE XHB_SH_JUSTICE CASCADE CONSTRAINTS;

DROP TABLE XHB_ORDER CASCADE CONSTRAINTS;

DROP TABLE XHB_ORDER_TEMPLATE CASCADE CONSTRAINTS;

DROP TABLE XHB_ORDER_TYPE CASCADE CONSTRAINTS;

DROP TABLE XHB_ORDER_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_ORDER_DELIVERY_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_LINKED_SH CASCADE CONSTRAINTS;

DROP TABLE XHB_LINKED_HEARING CASCADE CONSTRAINTS;

DROP TABLE XHB_EXPORTA CASCADE CONSTRAINTS;

DROP TABLE XHB_DISPOSAL_REFERENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_DISPOSAL CASCADE CONSTRAINTS;

DROP TABLE XHB_DIRECTIONS_FOR_DEFENDANT CASCADE CONSTRAINTS;

DROP TABLE XHB_DIRECTIONS_FOR_CASE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEF_HEARING_RECORD CASCADE CONSTRAINTS;

DROP TABLE XHB_CC_INFO CASCADE CONSTRAINTS;

DROP TABLE XHB_XROLE CASCADE CONSTRAINTS;

DROP TABLE XHB_XGROUP CASCADE CONSTRAINTS;
declare
-- Dynamic SQL to drop audit tables as below
--drop table jnk

cursor c1 is select table_name from user_tables
  where table_name like 'AUD%';

l_org_table varchar2(255);
l_str1  varchar2(255) := ' ; ';
l_str2  varchar2(255) := ' DROP TABLE ';
l_stmt   varchar2(500);
begin
for record in c1 loop
if c1%FOUND then
  l_org_table := record.table_name;

  l_stmt := l_str2||l_org_table;
  DBMS_OUTPUT.PUT_LINE(l_stmt);
  EXECUTE IMMEDIATE l_stmt;
end if;
end loop;
end;
/


DROP TABLE XXX_DUMMY_TABLE_FOR_AUDITING CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_LOG_ENTRY CASCADE CONSTRAINTS;

DROP TABLE TMP_ERROR_LOG CASCADE CONSTRAINTS;

DROP TABLE XHB_SCHED_HEARING_DEFENDANT CASCADE CONSTRAINTS;

DROP TABLE XHB_SCHEDULED_HEARING CASCADE CONSTRAINTS;

DROP TABLE XHB_SITTING CASCADE CONSTRAINTS;

DROP TABLE XHB_LINKED_CASE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFENDANT_REFERENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFENDANT_CHARGE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFENDANT_ON_OFFENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFENDANT_ON_CASE CASCADE CONSTRAINTS;

DROP TABLE XHB_DEFENDANT CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_COURT_REPORTER CASCADE CONSTRAINTS;

DROP TABLE XHB_HEARING CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_HEARING_TYPE CASCADE CONSTRAINTS;

DROP TABLE XHB_OFFENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_BREACH CASCADE CONSTRAINTS;

DROP TABLE XHB_CHARGE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_SYSTEM_CODE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_OFFENCE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_DISPOSAL_MENU CASCADE CONSTRAINTS;

DROP TABLE XHB_DISPOSAL_DETAIL CASCADE CONSTRAINTS;

DROP TABLE XHB_ORIGINAL_RESULT CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_DISPOSAL CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_COURT_REPORTER_FIRM CASCADE CONSTRAINTS;

DROP TABLE XHB_CHARGE_DIFFERENCES CASCADE CONSTRAINTS;

DROP TABLE XHB_CASE_PROSECUTOR_AGENCY CASCADE CONSTRAINTS;

DROP TABLE XHB_CASE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_COURT CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_ADVOCATE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_CHAMBER CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_SOLICITOR CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_LEGAL_REPRESENTATIVE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_JUDGE CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_SOLICITOR_FIRM CASCADE CONSTRAINTS;

DROP TABLE XHB_DAILY_LIST_XML CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_JUSTICE CASCADE CONSTRAINTS;

DROP TABLE XHB_HEARING_LIST CASCADE CONSTRAINTS;

DROP TABLE XHB_REF_PROSECUTOR_AGENCY CASCADE CONSTRAINTS;

DROP TABLE XHB_TERMINAL CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_ROOM CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_SITE CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT CASCADE CONSTRAINTS;

DROP TABLE XHB_CONTACT_DETAIL CASCADE CONSTRAINTS;

DROP TABLE XHB_ADDRESS CASCADE CONSTRAINTS;

DROP TABLE XHB_OBJECT_STATUS CASCADE CONSTRAINTS;

DROP TABLE XHB_MESSAGE CASCADE CONSTRAINTS;

DROP TABLE XHB_SYS_USER_INFORMATION CASCADE CONSTRAINTS;

DROP TABLE XHB_ERROR_DEF CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_LOG_CATEGORY CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_LOG_CATEGORY_DESC CASCADE CONSTRAINTS;

DROP TABLE XHB_COURT_LOG_EVENT_DESC CASCADE CONSTRAINTS;

DROP TABLE XHB_SYS_AUDIT CASCADE CONSTRAINTS;

DROP TABLE MTBL_MERC_AUDIT_LOG CASCADE CONSTRAINTS;

DROP TABLE MTBL_MERC_DL_STORAGE CASCADE CONSTRAINTS;

DROP TABLE MTBL_MERC_EMAIL_ALERT CASCADE CONSTRAINTS;

DROP TABLE MTBL_MERC_TRIGGER CASCADE CONSTRAINTS;

DROP TABLE MTBL_TRIGGER_SERVER CASCADE CONSTRAINTS;


