CREATE OR REPLACE TRIGGER XHB_CM_LOGS_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CM_LOGS
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_CM_LOGS') = 1) THEN
	INSERT INTO AUD_CM_LOGS
	(CM_LOGS_ID,
	ORIGINAL_UPLOADED_FILENAME,
	ORIGINAL_UPLOADED_FILE_CLOB_ID,
	PROCESSING_STATUS,
	PROCESSING_DATETIME,
	LOGS_CLOB_ID,
	FILE_CHECKSUM,
	UPLOAD_SIZE,
	NO_OF_CASES_IN_FILE,
	LAST_UPDATE_DATE,
	CREATION_DATE,
	CREATED_BY,
	LAST_UPDATED_BY,
	VERSION,
	INSERT_EVENT)
	VALUES 
	(:OLD.CM_LOGS_ID,
	:OLD.ORIGINAL_UPLOADED_FILENAME,
	:OLD.ORIGINAL_UPLOADED_FILE_CLOB_ID,
	:OLD.PROCESSING_STATUS,
	:OLD.PROCESSING_DATETIME,
	:OLD.LOGS_CLOB_ID,
	:OLD.FILE_CHECKSUM,
	:OLD.UPLOAD_SIZE,
	:OLD.NO_OF_CASES_IN_FILE,
	:OLD.LAST_UPDATE_DATE,
	:OLD.CREATION_DATE,
	:OLD.CREATED_BY,
	:OLD.LAST_UPDATED_BY,
	:OLD.VERSION,
	l_trig_event);
  END IF;

END;
/
