ALTER TRIGGER XHB_MONETARY_ORDER_TRAC_BUR_TR DISABLE;
ALTER TRIGGER XHB_MONETARY_ORDER_TRAC_BIR_TR DISABLE;

ALTER TABLE XHB_MONETARY_ORDER_TRACKING ADD FINED_TEMP NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET FINED_TEMP=FINED;
UPDATE XHB_MONETARY_ORDER_TRACKING SET FINED = NULL;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING MODIFY FINED NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET FINED = FINED_TEMP;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING DROP COLUMN FINED_TEMP;

ALTER TABLE XHB_MONETARY_ORDER_TRACKING ADD COSTS_TEMP NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET COSTS_TEMP=COSTS;
UPDATE XHB_MONETARY_ORDER_TRACKING SET COSTS = NULL;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING MODIFY COSTS NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET COSTS = COSTS_TEMP;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING DROP COLUMN COSTS_TEMP;

ALTER TABLE XHB_MONETARY_ORDER_TRACKING ADD COMPENSATION_TEMP NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET COMPENSATION_TEMP=COMPENSATION;
UPDATE XHB_MONETARY_ORDER_TRACKING SET COMPENSATION = NULL;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING MODIFY COMPENSATION NUMBER(10,2);
UPDATE XHB_MONETARY_ORDER_TRACKING SET COMPENSATION = COMPENSATION_TEMP;
ALTER TABLE XHB_MONETARY_ORDER_TRACKING DROP COLUMN COMPENSATION_TEMP;

ALTER TABLE AUD_MONETARY_ORDER_TRACKING ADD FINED_TEMP NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET FINED_TEMP=FINED;
UPDATE AUD_MONETARY_ORDER_TRACKING SET FINED = NULL;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING MODIFY FINED NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET FINED = FINED_TEMP;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING DROP COLUMN FINED_TEMP;

ALTER TABLE AUD_MONETARY_ORDER_TRACKING ADD COSTS_TEMP NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET COSTS_TEMP=COSTS;
UPDATE AUD_MONETARY_ORDER_TRACKING SET COSTS = NULL;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING MODIFY COSTS NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET COSTS = COSTS_TEMP;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING DROP COLUMN COSTS_TEMP;

ALTER TABLE AUD_MONETARY_ORDER_TRACKING ADD COMPENSATION_TEMP NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET COMPENSATION_TEMP=COMPENSATION;
UPDATE AUD_MONETARY_ORDER_TRACKING SET COMPENSATION = NULL;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING MODIFY COMPENSATION NUMBER(10,2);
UPDATE AUD_MONETARY_ORDER_TRACKING SET COMPENSATION = COMPENSATION_TEMP;
ALTER TABLE AUD_MONETARY_ORDER_TRACKING DROP COLUMN COMPENSATION_TEMP;

ALTER TRIGGER XHB_MONETARY_ORDER_TRAC_BUR_TR ENABLE;
ALTER TRIGGER XHB_MONETARY_ORDER_TRAC_BIR_TR ENABLE;

COMMIT;