--New Detention and Training Order
INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (24, 'DTO', 1, 'XHIBIT', 'XHIBIT',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Detention and Training Order (5044A/B)');


INSERT INTO XHB_ORDER_TEMPLATE VALUES (24,  '/metadata/OrderFOPTransform.xslt', '/metadata/DTO_Narrative.xml', '/metadata/DTOTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 24, NULL);


INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (24, 24, NULL, 0);


--New Youth Rehabilitation Order
INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (25, 'YRO', 1, 'XHIBIT', 'XHIBIT',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Youth Rehabilitation Order');


INSERT INTO XHB_ORDER_TEMPLATE VALUES (25,  '/metadata/OrderFOPTransform.xslt', '/metadata/YRO_Narrative.xml', '/metadata/YROOrderTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 25, NULL);


INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (25, 25, NULL, 0);

--Remove Community Punishemtn, Rehabilitation and Punishemnt and Rehabilitation Orders
UPDATE XHB_ORDER_TEMPLATE SET OBS_IND = 'Y' WHERE ORDER_TEMPLATE_ID IN (3, 4, 6);

commit;
