#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to classes.
#
# Copyright:   Copyright (c) 2015
# Company:     CGI
#
# Author:      Scott Atwell
#
# $Revision: 1.1 $
# $Log: Action.properties,v $
# Revision 1.1  2015/10/05 14:39:57  atwells
# New code to support the NLE data reset tool
#
#



actions = default;reset_data;managecases;reset_data2;updatedata;addcase;removecase

#
# Default Mapping
#

default.request = /home
default.class = uk.gov.courtservice.xhibit.web.dr.action.DefaultAction

#
#  Reset Data (Initially limited to Dates of Birth)
#
reset_data.request = /reset_data
reset_data.class = uk.gov.courtservice.xhibit.web.dr.action.ResetDataAction

#
#  Manage Cases
#
reset_data2.request = /reset_data2
reset_data2.class = uk.gov.courtservice.xhibit.web.dr.action.ManageCasesAction
managecases.request = /managecases
managecases.class = uk.gov.courtservice.xhibit.web.dr.action.ManageCasesAction

#
# Press Update on Reset Data Page
#
updatedata.request = /updatedata
updatedata.class = uk.gov.courtservice.xhibit.web.dr.action.UpdateDataAction

#
# Press Add Case on Manage Cases Page
#
addcase.request = /addcase
addcase.class = uk.gov.courtservice.xhibit.web.dr.action.AddManagedCaseAction

#
# Press Remove Case on Manage Cases Page
#
removecase.request = /removecase
removecase.class = uk.gov.courtservice.xhibit.web.dr.action.RemoveManagedCaseAction



