#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2015
# Company:     CGI
#
# Author:      Scott Atwell
#
# $Revision: 1.1 $
#
# $Log: Response.properties,v $
# Revision 1.1  2015/10/05 14:39:57  atwells
# New code to support the NLE data reset tool
#
#


responses = home;reset_data;managecases;reset_data2;addcase;removecase

#
# Default Mapping
#

home.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page = normal.jsp
home.skeletonBodyKey = home
home.skeletonTitleKey = home.title

#
# Reset data (initially limited to only dates of birth . . .)
#

reset_data.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
reset_data.page = normal.jsp
reset_data.skeletonBodyKey = reset_data
reset_data.skeletonTitleKey = reset_data.title

#
# Manage Cases
#

reset_data2.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
reset_data2.page = normal.jsp
reset_data2.skeletonBodyKey = reset_data2
reset_data2.skeletonTitleKey = reset_data2.title

managecases.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
managecases.page = normal.jsp
managecases.skeletonBodyKey = managecases
managecases.skeletonTitleKey = managecases.title

addcase.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
addcase.page = normal.jsp
addcase.skeletonBodyKey = addcase
addcase.skeletonTitleKey = managecases.title

removecase.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
removecase.page = normal.jsp
removecase.skeletonBodyKey = managecases
removecase.skeletonTitleKey = managecases.title
