INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (11530,'Capture Sentence', 'STS', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (11531,'Capture Sentence', 'DETTO', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13507,'Capture Sentence', 'EXD1820', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13508,'Capture Sentence', 'EXDO21', 'Y');
commit;
