# Set options for stdout appender
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.SimpleLayout

log4j.appender.file=org.apache.log4j.RollingFileAppender
log4j.appender.file.file=build/log/build.log
log4j.appender.file.MaxFileSize=10MB
log4j.appender.file.MaxBackupIndex=3
log4j.appender.file.layout=org.apache.log4j.TTCCLayout
log4j.appender.file.layout.DateFormat=ISO8601

# Set up the root logger
log4j.rootLogger=DEBUG,file

