create or replace PACKAGE XHB_RECORD_SHEET_PKG AS      

  PROCEDURE REQUEST_PREVIEW_GENERATION(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE);
                                   
  FUNCTION GET_PREVIEW_GENERATION_STATUS(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) RETURN XHB_RECORDSHEET.STATUS%TYPE;
  
  FUNCTION GET_GENERATED_PREVIEW_XML(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) RETURN CLOB;
  
  PROCEDURE CANCEL_PREVIEW_GENERATION(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE);

END XHB_RECORD_SHEET_PKG;
/
show errors