create or replace PACKAGE BODY XHB_RECORD_SHEET_PKG AS

  PROCEDURE REQUEST_PREVIEW_GENERATION(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) AS
  BEGIN
  MERGE INTO XHB_RECORDSHEET USING DUAL ON (DEFENDANT_ON_CASE_ID = p_defendant_on_case_id)
    WHEN NOT MATCHED THEN INSERT (DEFENDANT_ON_CASE_ID, STATUS) 
                     VALUES(p_defendant_on_case_id, 'R')
    WHEN MATCHED THEN UPDATE SET STATUS = 'R';
  END REQUEST_PREVIEW_GENERATION;
                                   
  FUNCTION GET_PREVIEW_GENERATION_STATUS(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) RETURN XHB_RECORDSHEET.STATUS%TYPE AS
    status_code XHB_RECORDSHEET.STATUS%TYPE;
  BEGIN
    SELECT STATUS INTO status_code FROM XHB_RECORDSHEET WHERE DEFENDANT_ON_CASE_ID = p_defendant_on_case_id;
    RETURN status_code;
  END GET_PREVIEW_GENERATION_STATUS;
  
  FUNCTION GET_GENERATED_PREVIEW_XML(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) RETURN CLOB AS
    preview_xml CLOB;
  BEGIN
    SELECT XML_DATA INTO preview_xml FROM XHB_RECORDSHEET WHERE DEFENDANT_ON_CASE_ID = p_defendant_on_case_id;
    RETURN preview_xml;
  END GET_GENERATED_PREVIEW_XML;
  
  PROCEDURE CANCEL_PREVIEW_GENERATION(p_defendant_on_case_id IN XHB_RECORDSHEET.DEFENDANT_ON_CASE_ID%TYPE) AS
  BEGIN
    UPDATE XHB_RECORDSHEET SET STATUS = 'C' WHERE DEFENDANT_ON_CASE_ID = p_defendant_on_case_id;
  END CANCEL_PREVIEW_GENERATION;
    
END XHB_RECORD_SHEET_PKG;
/
show errors