#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, Xdevelopment LLP (2003)
#
# $Revision: 1.16 $
# $Log: Action.properties,v $
# Revision 1.16  2014/08/15 17:52:40  atwells
# Reverted back to probation service properties files!!
#
# Revision 1.14  2004/09/24 06:51:45  tzj8k5
# CR65 - All Case Status Page ThinClient
#
# Revision 1.13  2004/08/12 15:56:21  zz7n1c
# Merged from 6_X_BRANCH on 12/08/2004
#
# Revision 1.12.98.1  2004/08/05 15:47:02  tzj8k5
# 56014 - Amendment to error handling in the thinclient
#
# Revision 1.12  2003/06/26 11:28:32  cawleye
# FActorised bits to shared resources.
#
# Revision 1.11  2003/05/16 08:59:39  fz0n8j
# Added logout button.
#
# Revision 1.10  2003/05/09 08:05:53  rz3jq5
# Completion of base functionality.
#
# Revision 1.9  2003/05/01 11:35:10  fz0n8j
# Added bits for terminal
#
# Revision 1.8  2003/03/26 16:54:50  fz0n8j
# Bug fixes.
#
# Revision 1.7  2003/03/24 16:45:22  fz0n8j
# Added/Modified for Email functionality.
#
# Revision 1.6  2003/03/24 08:23:26  fz0n8j
# Added view daily list, and public display
#
# Revision 1.5  2003/03/21 17:28:38  fz0n8j
# *** empty log message ***
#
# Revision 1.4  2003/03/20 17:41:13  fz0n8j
# *** empty log message ***
#
# Revision 1.3  2003/03/19 21:54:15  fz0n8j
# Allow context free
#
# Revision 1.2  2003/03/19 20:13:31  fz0n8j
# Added better response functionality
#
#

actions = default;viewunissuedpsrrequestsummaries;viewissuedpsrrequestsummaries;viewrecipientsummaries;editprobationdetails;updateprobationdetails;addrecipientdetails;insertrecipientdetails;editrecipientdetails;updaterecipientdetails;deleterecipientdetails;deletewarningrecipientdetails;printpsrrequestdetails;printforemail;viewpsrrequestdetails;editpsrrequestdetails;updatepsrrequestdetails;updatepsrrequestdetails;selectrecipient;updatepsrrequestrecipient;confirmissue;issuerequest;viewallcourtstatus;viewsummarybyname;viewdailylist;;viewallcasestatus

#
# Default Mapping
#

default.request = /home
default.class = uk.gov.courtservice.xhibit.web.ps.action.DefaultAction

#
# View Unissued PSR Requset Summaries Action
#

viewunissuedpsrrequestsummaries.request = /viewunissuedpsrrequestsummaries
viewunissuedpsrrequestsummaries.class = uk.gov.courtservice.xhibit.web.ps.action.ViewUnissuedPSRRequestSummariesAction

#
# View Issued PSR Requset Summaries Action
#

viewissuedpsrrequestsummaries.request = /viewissuedpsrrequestsummaries
viewissuedpsrrequestsummaries.class = uk.gov.courtservice.xhibit.web.ps.action.ViewIssuedPSRRequestSummariesAction

#
# Confirm Issue Action
#

confirmissue.request = /confirmissue
confirmissue.class = uk.gov.courtservice.xhibit.web.ps.action.ConfirmIssueAction

#
# Issue Request Action
#

issuerequest.request = /issuerequest
issuerequest.class = uk.gov.courtservice.xhibit.web.ps.action.IssueRequestAction

#
# Print PSR Request Details Action
#

printpsrrequestdetails.request = /printpsrrequestdetails
printpsrrequestdetails.class = uk.gov.courtservice.xhibit.web.ps.action.PrintPSRRequestDetailsAction

#
# Print PSR Request Details Action
#

printforemail.request = /printforemail
printforemail.class = uk.gov.courtservice.xhibit.web.ps.action.PrintForEmailAction

#
# View PSR Request Details Action
#

viewpsrrequestdetails.request = /viewpsrrequestdetails
viewpsrrequestdetails.class = uk.gov.courtservice.xhibit.web.ps.action.ViewPSRRequestDetailsAction

#
# Edit PSR Request Details Action
#

editpsrrequestdetails.request = /editpsrrequestdetails
editpsrrequestdetails.class = uk.gov.courtservice.xhibit.web.ps.action.EditPSRRequestDetailsAction

#
# Update request recipient.class
#

updatepsrrequestrecipient.request = /updatepsrrequestrecipient
updatepsrrequestrecipient.class = uk.gov.courtservice.xhibit.web.ps.action.UpdatePSRRequestRecipientAction

#
# Select recipient.class
#

selectrecipient.request = /selectrecipient
selectrecipient.class = uk.gov.courtservice.xhibit.web.ps.action.SelectRecipientAction

#
# Update PSR Request Details Action
#

updatepsrrequestdetails.request = /updatepsrrequestdetails
updatepsrrequestdetails.class = uk.gov.courtservice.xhibit.web.ps.action.UpdatePSRRequestDetailsAction

#
# View Recipient Summaries Action
#

viewrecipientsummaries.request = /viewrecipientsummaries
viewrecipientsummaries.class = uk.gov.courtservice.xhibit.web.ps.action.ViewRecipientSummariesAction

#
# Edit Probation Details Action
#

editprobationdetails.request = /editprobationdetails
editprobationdetails.class = uk.gov.courtservice.xhibit.web.ps.action.EditProbationDetailsAction

#
# Update Probation Details Action
#

updateprobationdetails.request = /updateprobationdetails
updateprobationdetails.class = uk.gov.courtservice.xhibit.web.ps.action.UpdateProbationDetailsAction

#
# Add Recipient Details Action
#

addrecipientdetails.request = /addrecipientdetails
addrecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.AddRecipientDetailsAction

#
# Insert Recipient Details Action
#

insertrecipientdetails.request = /insertrecipientdetails
insertrecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.InsertRecipientDetailsAction

#
# Edit Recipient Details Action
#

editrecipientdetails.request = /editrecipientdetails
editrecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.EditRecipientDetailsAction

#
# Update Recipient Details Action
#

updaterecipientdetails.request = /updaterecipientdetails
updaterecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.UpdateRecipientDetailsAction

#
# Delete warning Recipient Details Action
#

deletewarningrecipientdetails.request = /deletewarningrecipientdetails
deletewarningrecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.DeleteWarningRecipientDetailsAction

#
# Delete Recipient Details Action
#

deleterecipientdetails.request = /deleterecipientdetails
deleterecipientdetails.class = uk.gov.courtservice.xhibit.web.ps.action.DeleteRecipientDetailsAction

#
#  View Daily List Action
#

viewdailylist.request = /viewdailylist
viewdailylist.class = uk.gov.courtservice.xhibit.web.ps.action.ViewDailyListAction

#
#  View all court status
#

viewallcourtstatus.request = /viewallcourtstatus
viewallcourtstatus.class = uk.gov.courtservice.xhibit.web.ps.action.ViewAllCourtStatusAction

#
#  View all case status
#

viewallcasestatus.request = /viewallcasestatus
viewallcasestatus.class = uk.gov.courtservice.xhibit.web.ps.action.ViewAllCaseStatusAction

#
# View Summary By Name
#

viewsummarybyname.request = /viewsummarybyname
viewsummarybyname.class = uk.gov.courtservice.xhibit.web.ps.action.ViewSummaryByNameAction


