#
# Title:       Pages
#
# Description: This is the default Pages property file, it forms part of an
#              i18n resource bundle. ALL page urls should be accessed through
#              here this means if more complex i18n is required the jsps used
#              can be overriden by implementing a specific instance of the
#              Pages bundle. The preference is to use the same jsps and the
#              messages resource bundle.
#
# Example:     <!- Include the JSTL tag library -->
#              <%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt" %>
#              <!- As pages is not the default message bundle must specify -->
#              <fmt:bundle basename="Pages">
#                  <!- Retrieve the localised page url -->
#                  <fmt:message key="header.text"/>
#              </fmt:bundle>
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, Xdevelopment LLP (2003)
# $Revision: 1.20 $
#
# $Log: Pages.properties,v $
# Revision 1.20  2014/08/15 17:52:40  atwells
# Reverted back to probation service properties files!!
#
# Revision 1.18  2004/11/04 14:35:14  bzjrnl
# Changes to correct problems with cookie access.
#
# Revision 1.17  2004/09/24 06:51:45  tzj8k5
# CR65 - All Case Status Page ThinClient
#
# Revision 1.16  2003/06/26 11:28:32  cawleye
# FActorised bits to shared resources.
#
# Revision 1.15  2003/05/09 08:05:53  rz3jq5
# Completion of base functionality.
#
# Revision 1.14  2003/05/01 19:09:10  fz0n8j
# *** empty log message ***
#
# Revision 1.13  2003/05/01 11:35:11  fz0n8j
# Added bits for terminal
#
# Revision 1.12  2003/04/30 10:03:01  fz0n8j
# Added messaging to probation service. (EFC)
#
# Revision 1.11  2003/04/02 10:35:29  fz0n8j
# Seperate response and jsp so now there is no edit option on issued psrs.
#
# Revision 1.10  2003/03/26 16:54:50  fz0n8j
# Bug fixes.
#
# Revision 1.9  2003/03/20 17:41:14  fz0n8j
# *** empty log message ***
#
# Revision 1.8  2003/03/19 19:38:06  fz0n8j
# Added new pages for psrrequest recipient selection.
#
# Revision 1.7  2003/03/18 17:44:57  fz0n8j
# Changed to create login pages
#
# Revision 1.6  2003/03/17 11:32:00  fz0n8j
# Added revision cvs comments. ecawley
#
# Revision 1.5  2003/03/12 15:32:41  fz0n8j
# *** empty log message ***
#
# Revision 1.4  2003/03/11 16:04:37  fz0n8j
# Added CVS Log and page for printing PSRrequests - ecawley
#
#

#
# Application Pages
#

home = home.jsp
viewunissuedpsrrequestsummaries = viewunissuedpsrrequestsummaries.jsp
viewissuedpsrrequestsummaries = viewissuedpsrrequestsummaries.jsp
viewrecipientsummaries = viewrecipientsummaries.jsp
editprobationdetails = editprobationdetails.jsp
editrecipientdetails = editrecipientdetails.jsp
addrecipientdetails = addrecipientdetails.jsp
recipientdetailsform = recipientdetailsform.jsp
deletewarningrecipientdetails = deletewarningrecipientdetails.jsp
printpsrrequestdetails = printpsrrequestdetails.jsp
viewpsrrequestdetails = viewpsrrequestdetails.jsp
viewissuedpsrrequestdetails = viewissuedpsrrequestdetails.jsp
displaypsrrequestdetails = displaypsrrequestdetails.jsp
editpsrrequestdetails = editpsrrequestdetails.jsp
selectrecipient = selectrecipient.jsp
confirmissue = confirmissue.jsp
viewdailylist = viewdailylist.jsp
viewallcourtstatus = viewallcourtstatus.jsp
viewsummarybyname = viewsummarybyname.jsp
viewallcasestatus = viewallcasestatus.jsp

