#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      William Fardell, (2003)
#
# $Revision: 1.22 $
#
# $Log: Response.properties,v $
# Revision 1.22  2014/08/15 17:52:40  atwells
# Reverted back to probation service properties files!!
#
# Revision 1.20  2005/10/12 14:52:43  tzj8k5
# Int 3 Testing - Issue 37
#
# Revision 1.19  2004/09/24 06:51:45  tzj8k5
# CR65 - All Case Status Page ThinClient
#
# Revision 1.18  2004/08/12 15:56:21  zz7n1c
# Merged from 6_X_BRANCH on 12/08/2004
#
# Revision 1.17.8.2  2004/08/05 15:47:02  tzj8k5
# 56014 - Amendment to error handling in the thinclient
#
# Revision 1.17.8.1  2004/08/05 07:47:23  tzj8k5
# 56339 - DateField validation
#
# Revision 1.17  2004/02/18 16:08:53  rzgbyh
# Merge with End_Hearing_Changes
#
# Revision 1.16.76.1  2004/02/03 14:53:05  xzmw8n
# allow psr date of hearing and arrive no later than fields to become editable.
#
# Revision 1.16  2003/06/26 11:28:32  cawleye
# FActorised bits to shared resources.
#
# Revision 1.15  2003/05/16 08:59:39  fz0n8j
# Added logout button.
#
# Revision 1.14  2003/05/09 08:05:53  rz3jq5
# Completion of base functionality.
#
# Revision 1.13  2003/05/01 19:09:10  fz0n8j
# *** empty log message ***
#
# Revision 1.12  2003/05/01 11:35:11  fz0n8j
# Added bits for terminal
#
# Revision 1.11  2003/04/29 17:15:29  fz0n8j
# Merged devBranch-2b-030404. (WDF)
#
# Revision 1.10.2.1  2003/04/09 16:16:16  fz0n8j
# Print now uses new pdf framework classes, added xsl file.
#
# Revision 1.10  2003/04/02 10:35:29  fz0n8j
# Seperate response and jsp so now there is no edit option on issued psrs.
#
# Revision 1.9  2003/03/31 16:36:39  fz0n8j
# Uses normal response from framework.
#
# Revision 1.8  2003/03/26 16:54:50  fz0n8j
# Bug fixes.
#
# Revision 1.7  2003/03/24 16:45:22  fz0n8j
# Added/Modified for Email functionality.
#
# Revision 1.6  2003/03/24 08:23:26  fz0n8j
# Added view daily list, and public display
#
# Revision 1.5  2003/03/21 17:28:38  fz0n8j
# *** empty log message ***
#
# Revision 1.4  2003/03/20 17:41:14  fz0n8j
# *** empty log message ***
#
# Revision 1.3  2003/03/19 21:14:55  fz0n8j
# Modified for new mappings.
#
# Revision 1.2  2003/03/19 20:13:31  fz0n8j
# Added better response functionality
#
#

responses = home;viewunissuedpsrrequestsummaries;viewissuedpsrrequestsummaries;printpsrrequestdetailscomplete;editpsrrequestdetailscomplete;updatepsrrequestrecipientcomplete;selectrecipientcomplete;selectrecipientinvalid;updatepsrrequestdetailscomplete;viewrecipientsummariescomplete;editprobationdetailscomplete;updateprobationdetailscomplete;updateprobationdetailsinvalid;addrecipientdetailscomplete;insertrecipientdetailscomplete;insertrecipientdetailsinvalid;editrecipientdetailscomplete;editrecipientdetailsnorecord;updaterecipientdetailscomplete;updaterecipientdetailsinvalid;deletewarningrecipientdetailscomplete;deletewarningrecipientdetailsnorecord;deleterecipientdetailscomplete;deleterecipientdetailsnorecord;confirmissue;updatepsrrequestdetailsnorecipient;updatepsrrequestdetailsinvalid;viewpsrrequestdetailscomplete;viewdailylistcomplete;viewallcourtstatuscomplete;viewsummarybynamecomplete;printforemailcomplete;viewissuedpsrrequestdetailscomplete;printpsrrequestdetailspdfcomplete;updatepsrrequestdetailsnohearing;;viewallcasestatuscomplete

#
# Default Mapping
#

home.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page = normal.jsp
home.skeletonBodyKey = home
home.skeletonTitleKey = home.title

#
# View Unissued PSR Requset Summaries response
#

viewunissuedpsrrequestsummaries.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewunissuedpsrrequestsummaries.page = normal.jsp
viewunissuedpsrrequestsummaries.skeletonBodyKey = viewunissuedpsrrequestsummaries
viewunissuedpsrrequestsummaries.skeletonTitleKey = viewunissuedpsrrequestsummaries.title

#
# View Issued PSR Requset Summaries response
#

viewissuedpsrrequestsummaries.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewissuedpsrrequestsummaries.page = normal.jsp
viewissuedpsrrequestsummaries.skeletonBodyKey = viewissuedpsrrequestsummaries
viewissuedpsrrequestsummaries.skeletonTitleKey = viewissuedpsrrequestsummaries.title

#
# Confirm Issue
#

confirmissue.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
confirmissue.page = normal.jsp
confirmissue.skeletonBodyKey = confirmissue
confirmissue.skeletonTitleKey = confirmissue.title

#
# View PSR Request Details Action
#

viewpsrrequestdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewpsrrequestdetailscomplete.page = normal.jsp
viewpsrrequestdetailscomplete.skeletonTitleKey = viewpsrrequestdetails.title
viewpsrrequestdetailscomplete.skeletonBodyKey = viewpsrrequestdetails

#
# View PSR Request Details Action
#

viewissuedpsrrequestdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewissuedpsrrequestdetailscomplete.page = normal.jsp
viewissuedpsrrequestdetailscomplete.skeletonTitleKey = viewpsrrequestdetails.title
viewissuedpsrrequestdetailscomplete.skeletonBodyKey = viewissuedpsrrequestdetails

#
# Print PSR Request Details Action
#

printpsrrequestdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
printpsrrequestdetailscomplete.page = print.jsp
printpsrrequestdetailscomplete.skeletonBodyKey = printpsrrequestdetails

#
# Print PSR Request Details PDF
#

printpsrrequestdetailspdfcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.PDFResponse
printpsrrequestdetailspdfcomplete.xslStyleSheet = psrrequest.xsl

#
# Print for email . ..
#

printforemailcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
printforemailcomplete.page = printforemail.jsp

#
# Edit PSR Request Details Action
#

editpsrrequestdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editpsrrequestdetailscomplete.page = normal.jsp
editpsrrequestdetailscomplete.skeletonTitleKey = editpsrrequestdetails.title
editpsrrequestdetailscomplete.skeletonBodyKey = editpsrrequestdetails

#
# Update request recipient action
#

updatepsrrequestrecipientcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updatepsrrequestrecipientcomplete.page = normal.jsp
updatepsrrequestrecipientcomplete.skeletonTitleKey = updatepsrrequestrecipient.title
updatepsrrequestrecipientcomplete.skeletonBodyKey = editpsrrequestdetails

#
# Select recipient action
#

selectrecipientcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
selectrecipientcomplete.page = normal.jsp
selectrecipientcomplete.skeletonTitleKey = selectrecipient.title
selectrecipientcomplete.skeletonBodyKey = selectrecipient


selectrecipientinvalid.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
selectrecipientinvalid.page = normal.jsp
selectrecipientinvalid.skeletonTitleKey = editpsrrequestdetails.title
selectrecipientinvalid.skeletonBodyKey = editpsrrequestdetails

#
# Update PSR Request Details Action
#

updatepsrrequestdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updatepsrrequestdetailscomplete.page = normal.jsp
updatepsrrequestdetailscomplete.skeletonTitleKey = updatepsrrequestdetails.title
updatepsrrequestdetailscomplete.skeletonBodyKey = editpsrrequestdetails

updatepsrrequestdetailsinvalid.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updatepsrrequestdetailsinvalid.page = normal.jsp
updatepsrrequestdetailsinvalid.skeletonTitleKey = invaliddata
updatepsrrequestdetailsinvalid.skeletonBodyKey = editpsrrequestdetails

updatepsrrequestdetailsnorecipient.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updatepsrrequestdetailsnorecipient.page = normal.jsp
updatepsrrequestdetailsnorecipient.skeletonTitleKey = norecipient
updatepsrrequestdetailsnorecipient.errorMessageKeys = norecipient
updatepsrrequestdetailsnorecipient.skeletonBodyKey = editpsrrequestdetails

updatepsrrequestdetailsnohearing.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updatepsrrequestdetailsnohearing.page = normal.jsp
updatepsrrequestdetailsnohearing.skeletonTitleKey = nohearingdate
updatepsrrequestdetailsnohearing.skeletonBodyKey = editpsrrequestdetails

#
# View Recipient Summaries Action
#

viewrecipientsummariescomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewrecipientsummariescomplete.page = normal.jsp
viewrecipientsummariescomplete.skeletonTitleKey = viewrecipientsummaries.title
viewrecipientsummariescomplete.skeletonBodyKey = viewrecipientsummaries

#
# Edit Probation Details Action
#

editprobationdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editprobationdetailscomplete.page = normal.jsp
editprobationdetailscomplete.skeletonTitleKey = editprobationdetails.title
editprobationdetailscomplete.skeletonBodyKey = editprobationdetails

#
# Update Probation Details Action
#

updateprobationdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updateprobationdetailscomplete.page = normal.jsp
updateprobationdetailscomplete.skeletonTitleKey = updateprobationdetails.title
updateprobationdetailscomplete.skeletonBodyKey = editprobationdetails

updateprobationdetailsinvalid.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updateprobationdetailsinvalid.page = normal.jsp
updateprobationdetailsinvalid.skeletonTitleKey = invalidprobationdetails.title
updateprobationdetailsinvalid.skeletonBodyKey = editprobationdetails

#
# Add Recipient Details Action
#

addrecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
addrecipientdetailscomplete.page = normal.jsp
addrecipientdetailscomplete.skeletonTitleKey = addrecipientdetails.title
addrecipientdetailscomplete.skeletonBodyKey = addrecipientdetails

#
# Insert Recipient Details Action
#

insertrecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
insertrecipientdetailscomplete.page = normal.jsp
insertrecipientdetailscomplete.skeletonTitleKey = insertrecipientdetails.title
insertrecipientdetailscomplete.skeletonBodyKey = viewrecipientsummaries

insertrecipientdetailsinvalid.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
insertrecipientdetailsinvalid.page = normal.jsp
insertrecipientdetailsinvalid.skeletonTitleKey = invalidrecipientdetails.title
insertrecipientdetailsinvalid.skeletonBodyKey = addrecipientdetails

#
# Edit Recipient Details Action
#

editrecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editrecipientdetailscomplete.page = normal.jsp
editrecipientdetailscomplete.skeletonTitleKey = editrecipientdetails.title
editrecipientdetailscomplete.skeletonBodyKey = editrecipientdetails

editrecipientdetailsnorecord.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editrecipientdetailsnorecord.page = normal.jsp
editrecipientdetailsnorecord.skeletonTitleKey = norecord
editrecipientdetailsnorecord.skeletonBodyKey = viewrecipientsummaries

#
# Update Recipient Details Action
#

updaterecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updaterecipientdetailscomplete.page = normal.jsp
updaterecipientdetailscomplete.skeletonTitleKey = updaterecipientdetails.title
updaterecipientdetailscomplete.skeletonBodyKey = viewrecipientsummaries

updaterecipientdetailsinvalid.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
updaterecipientdetailsinvalid.page = normal.jsp
updaterecipientdetailsinvalid.skeletonTitleKey = invalidrecipientdetails.title
updaterecipientdetailsinvalid.skeletonBodyKey = editrecipientdetails

#
# Delete warning Recipient Details Action
#

deletewarningrecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deletewarningrecipientdetailscomplete.page = normal.jsp
deletewarningrecipientdetailscomplete.skeletonTitleKey = deletewarningrecipientdetails.title
deletewarningrecipientdetailscomplete.skeletonBodyKey = deletewarningrecipientdetails

deletewarningrecipientdetailsnorecord.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deletewarningrecipientdetailsnorecord.page = normal.jsp
deletewarningrecipientdetailsnorecord.skeletonTitleKey = norecord
deletewarningrecipientdetailsnorecord.skeletonBodyKey = viewrecipientsummaries

#
# Delete Recipient Details Action
#

deleterecipientdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deleterecipientdetailscomplete.page = normal.jsp
deleterecipientdetailscomplete.skeletonTitleKey = deleterecipientdetails.title
deleterecipientdetailscomplete.skeletonBodyKey = viewrecipientsummaries

deleterecipientdetailsnorecord.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deleterecipientdetailsnorecord.page = normal.jsp
deleterecipientdetailsnorecord.skeletonTitleKey = norecord
deleterecipientdetailsnorecord.skeletonBodyKey = viewrecipientsummaries

#viewdailylistcomplete;viewallcourtstatuscomplete;viewsummarybynamecomplete;

#
# View Daily List
#

viewdailylistcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewdailylistcomplete.page = normal.jsp
viewdailylistcomplete.skeletonBodyKey = viewdailylist
viewdailylistcomplete.skeletonTitleKey = viewdailylist.title

#
# View Summary by name . . .
#

viewsummarybynamecomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewsummarybynamecomplete.page = normal.jsp
viewsummarybynamecomplete.skeletonBodyKey = viewsummarybyname
viewsummarybynamecomplete.skeletonTitleKey = viewsummarybyname.title

#
# View all court status
#

viewallcourtstatuscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewallcourtstatuscomplete.page = normal.jsp
viewallcourtstatuscomplete.skeletonBodyKey = viewallcourtstatus
viewallcourtstatuscomplete.skeletonTitleKey = viewallcourtstatus.title

#
# View all case status
#

viewallcasestatuscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewallcasestatuscomplete.page = normal.jsp
viewallcasestatuscomplete.skeletonBodyKey = viewallcasestatus
viewallcasestatuscomplete.skeletonTitleKey = viewallcasestatus.title
