package uk.gov.courtservice.xhibit.courtlog.cjse.eventmessage;

import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.entities.xhb_case.XhbCase;
import uk.gov.courtservice.xhibit.courtlog.vos.CourtLogSubscriptionValue;

/**
 * <p>
 * Title: CJSE Message Builder
 * </p>
 * <p>
 * Description:
 * </p>
 * <p>
 * This class represents a message as a group of elements (MessageElement). When
 * the message is requested, it builds the message up from each of the elements
 * in turn.
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: Eds
 * </p>
 * 
 * @author Bob Boothby
 * @version 1.0
 */
public class MessageBuilder {
    private static final Logger log = CSServices.getLogger(MessageBuilder.class);

    // The elements of the message.
    private MessageElement[] _messageElements;

    /**
     * Construct a MessageBuilder made up of the given message elements.
     * 
     * @param messageElements
     *            The elements making up the message to be generated by the
     *            message builder.
     */
    public MessageBuilder(MessageElement[] messageElements) {
        _messageElements = messageElements;
    }

    /**
     * Build the message from the elements.
     * 
     * @param value
     *            The value object containing the data to help creation of the
     *            message
     * @return The built message.
     */
    public String getBuiltMessage(CourtLogSubscriptionValue value, XhbCase theCase) {
        log.debug("getBuiltMessage() start");

        StringBuffer returnBuffer = new StringBuffer();
        int elementsLength = _messageElements.length;
        for (int i = 0; i < elementsLength; i++)
            returnBuffer.append(_messageElements[i].getElement(value, theCase));

        log.debug("getBuiltMessage() end, returning message " + returnBuffer.toString());
        return returnBuffer.toString();
    }
    
    /**
     * Check to see if message builder has a certain element.  As the message builders are created using the
     * configuration file CjseEventMessageText_en_GB.properties, this is a simple method to check for
     * which elements are part of the message text structure.
     * 
     * @param element
     *            The messageElement to check.
     *            
     * @return The built message.
     */
    public boolean hasElement(MessageElement elementCheck) {
        
        for(MessageElement x:_messageElements){
            if ( x.getClass().equals(elementCheck.getClass())){
                return true;
            } 
        }
        return false;
    }
    
}