<?xml version="1.0" encoding="UTF-8"?>

<project name="OrdersXMLBindings" default="all" basedir=".">

    <description>
        Description to be done...
    </description>

    <import file="./../../../tools/ant/framework.xml" />

    <property name="project.type.requires.compilation" value="marker" />
    <property name="project.type.builds.jar"           value="marker" />

    <!--
    =======================================================================
        Initialise Override
    =======================================================================
     -->

    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>

        <!-- Generate xml binding using castor -->

        <property name="schemas.dir" location="${top.level.dir}/metadata/schemas/orders" />

        <path id="generate.xml.binding.dependencies">
            <fileset dir="${schemas.dir}" includes="**/*.xsd"/>
        </path>

        <path id="generate.xml.binding.schemas">
            <fileset dir="${schemas.dir}">
                <include name="courtService/BS7666-v1.xsd"/>
                <include name="courtService/apd.xsd"/>
                <include name="Narrative.xsd"/>
                <include name="Orders.xsd"/>
            </fileset>
        </path>

        <!-- classpath for compiling static and generated source (also used to build junit.classpath) -->
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="Framework.jar"/>
                <include name="HearingScheduleEntities.jar"/>
                <include name="OrdersEntities.jar"/>
                <include name="OrdersMidTierCommon.jar"/>
                <include name="PreHearingEntities.jar"/>
                <include name="ResultsController.jar"/>
                <include name="ResultsEntities.jar"/>
                <include name="SysAdminEntities.jar"/>
                <include name="Value.jar"/>
                <include name="XhibitEntities.jar"/>
            </fileset>
        </path>

        <filesetlist id="jar.source.filelist">
            <fileset dir="${source.dir}"
                   includes="${default.jar.includes}"
                   excludes="${default.jar.source.excludes}" />
            <fileset dir="${basedir}">
                <include name="blankschemas/*.xml"/>
            </fileset>
        </filesetlist>
    </target>

 </project>
