MERGE INTO XHB_REF_APP_RES_D20_MAP xrardm USING (
SELECT 'ACA'   APP_RESULT_CODE, 'Allowed'   D20_RESULT FROM DUAL UNION
SELECT 'ADAC'  APP_RESULT_CODE, 'Abandoned' D20_RESULT FROM DUAL UNION
SELECT 'ACD'   APP_RESULT_CODE, 'Dismissed' D20_RESULT FROM DUAL UNION
SELECT 'ASD'   APP_RESULT_CODE, 'Allowed'   D20_RESULT FROM DUAL UNION
SELECT 'AD'    APP_RESULT_CODE, 'Dismissed' D20_RESULT FROM DUAL UNION
SELECT 'ACDSV' APP_RESULT_CODE, 'Varied'    D20_RESULT FROM DUAL UNION
SELECT 'ACALO' APP_RESULT_CODE, 'Varied'    D20_RESULT FROM DUAL UNION
SELECT 'ASASV' APP_RESULT_CODE, 'Varied'    D20_RESULT FROM DUAL UNION
SELECT 'ASDSI' APP_RESULT_CODE, 'Varied'    D20_RESULT FROM DUAL UNION
SELECT 'ADSI'  APP_RESULT_CODE, 'Varied'    D20_RESULT FROM DUAL UNION
SELECT 'AB'    APP_RESULT_CODE, 'Abandoned' D20_RESULT FROM DUAL UNION
SELECT 'REM'   APP_RESULT_CODE, 'Remitted'  D20_RESULT FROM DUAL 
) subqry
    ON (subqry.APP_RESULT_CODE = xrardm.APP_RESULT_CODE)
    WHEN MATCHED THEN
         UPDATE SET xrardm.D20_RESULT = subqry.D20_RESULT
         WHERE xrardm.D20_RESULT != subqry.D20_RESULT 
    WHEN NOT MATCHED THEN  
         INSERT (APP_RESULT_CODE, D20_RESULT)
         VALUES (subqry.APP_RESULT_CODE, subqry.D20_RESULT);

commit;