INSERT INTO XHB_REF_EVENT_DESCRIPTION 
(EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS)
SELECT subqry.EXTERNAL_EVENT_CODE, 'Capture Sentence' EVENT_DESCRIPTION, subqry.DISPOSAL_CODE EVENT_SUB_DESCRIPTION, 'Y' SEND_TO_MIS FROM (
	SELECT 11533 EXTERNAL_EVENT_CODE, 'IMPMESW' DISPOSAL_CODE FROM DUAL UNION
	SELECT 11534 EXTERNAL_EVENT_CODE, 'DLFMESW' DISPOSAL_CODE FROM DUAL UNION
	SELECT 13820 EXTERNAL_EVENT_CODE, 'EWMYR'   DISPOSAL_CODE FROM DUAL UNION
	SELECT 13821 EXTERNAL_EVENT_CODE, 'ACTYR'   DISPOSAL_CODE FROM DUAL
) subqry 
WHERE NOT EXISTS (SELECT 1 FROM XHB_REF_EVENT_DESCRIPTION x2 
                   WHERE x2.EXTERNAL_EVENT_CODE = subqry.EXTERNAL_EVENT_CODE
                     AND x2.EVENT_SUB_DESCRIPTION = subqry.DISPOSAL_CODE);
commit;