# Middlegen Preferences
cmp20.tables.CJI_AHM.base-class-name=CjiAhm
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.java-name=aggregatorId
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.java-type=java.lang.String
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.local-get=true
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.local-set=true
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.remote-get=false
cmp20.tables.CJI_AHM.columns.AGGREGATOR_ID.remote-set=false
cmp20.tables.CJI_AHM.columns.CONTENT.java-name=content
cmp20.tables.CJI_AHM.columns.CONTENT.java-type=java.lang.String
cmp20.tables.CJI_AHM.columns.CONTENT.local-get=true
cmp20.tables.CJI_AHM.columns.CONTENT.local-set=true
cmp20.tables.CJI_AHM.columns.CONTENT.remote-get=false
cmp20.tables.CJI_AHM.columns.CONTENT.remote-set=false
cmp20.tables.CJI_AHM.columns.DEVICE_ID.java-name=deviceId
cmp20.tables.CJI_AHM.columns.DEVICE_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM.columns.DEVICE_ID.local-get=false
cmp20.tables.CJI_AHM.columns.DEVICE_ID.local-set=false
cmp20.tables.CJI_AHM.columns.DEVICE_ID.remote-get=false
cmp20.tables.CJI_AHM.columns.DEVICE_ID.remote-set=false
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.java-name=messageId
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.local-get=true
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.local-set=false
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.remote-get=false
cmp20.tables.CJI_AHM.columns.MESSAGE_ID.remote-set=false
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.java-name=orginalSender
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.java-type=java.lang.String
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.local-get=true
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.local-set=true
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.remote-get=false
cmp20.tables.CJI_AHM.columns.ORGINAL_SENDER.remote-set=false
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.java-name=responseCode
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.java-type=java.lang.String
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.local-get=true
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.local-set=true
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.remote-get=false
cmp20.tables.CJI_AHM.columns.RESPONSE_CODE.remote-set=false
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.java-name=sentAggDate
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.java-type=java.sql.Timestamp
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.local-get=true
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.local-set=true
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.remote-get=false
cmp20.tables.CJI_AHM.columns.SENT_AGG_DATE.remote-set=false
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.java-name=sentProDate
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.java-type=java.sql.Timestamp
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.local-get=true
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.local-set=true
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.remote-get=false
cmp20.tables.CJI_AHM.columns.SENT_PRO_DATE.remote-set=false
cmp20.tables.CJI_AHM.columns.STATUS_ID.java-name=statusId
cmp20.tables.CJI_AHM.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM.columns.STATUS_ID.local-get=false
cmp20.tables.CJI_AHM.columns.STATUS_ID.local-set=false
cmp20.tables.CJI_AHM.columns.STATUS_ID.remote-get=false
cmp20.tables.CJI_AHM.columns.STATUS_ID.remote-set=false
cmp20.tables.CJI_AHM.columns.TEL.java-name=tel
cmp20.tables.CJI_AHM.columns.TEL.java-type=java.lang.String
cmp20.tables.CJI_AHM.columns.TEL.local-get=true
cmp20.tables.CJI_AHM.columns.TEL.local-set=true
cmp20.tables.CJI_AHM.columns.TEL.remote-get=false
cmp20.tables.CJI_AHM.columns.TEL.remote-set=false
cmp20.tables.CJI_AHM.generate-pk-class=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.base-class-name=CjiAhmDeviceType
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.java-name=deviceId
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.local-get=true
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.local-set=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.remote-get=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_ID.remote-set=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.java-name=deviceMobilesysRef
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.java-type=java.lang.String
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.local-get=true
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.local-set=true
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.remote-get=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_MOBILESYS_REF.remote-set=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.java-name=deviceText
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.java-type=java.lang.String
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.local-get=true
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.local-set=true
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.remote-get=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.columns.DEVICE_TEXT.remote-set=false
cmp20.tables.CJI_AHM_DEVICE_TYPE.generate-pk-class=false
cmp20.tables.CJI_AHM_REPLY.base-class-name=CjiAhmReply
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.java-name=aggregatorReplyId
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.java-type=java.lang.String
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.local-get=true
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.local-set=true
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.AGGREGATOR_REPLY_ID.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.java-name=content
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.java-type=java.lang.String
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.local-get=true
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.local-set=true
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.CONTENT.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.java-name=messageId
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.local-get=false
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.local-set=false
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.MESSAGE_ID.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.java-name=receivedDate
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.java-type=java.sql.Timestamp
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.local-get=true
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.local-set=true
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.RECEIVED_DATE.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.java-name=replyId
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.local-get=true
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.local-set=false
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.REPLY_ID.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.java-name=responseCode
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.java-type=java.lang.String
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.local-get=true
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.local-set=true
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.RESPONSE_CODE.remote-set=false
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.java-name=statusId
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.local-get=false
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.local-set=false
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.remote-get=false
cmp20.tables.CJI_AHM_REPLY.columns.STATUS_ID.remote-set=false
cmp20.tables.CJI_AHM_REPLY.generate-pk-class=false
cmp20.tables.CJI_AHM_REPLY_STATUS.base-class-name=CjiAhmReplyStatus
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.java-name=statusId
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.local-get=true
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.local-set=false
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.remote-get=false
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_ID.remote-set=false
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.java-name=statusText
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.java-type=java.lang.String
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.local-get=true
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.local-set=true
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.remote-get=false
cmp20.tables.CJI_AHM_REPLY_STATUS.columns.STATUS_TEXT.remote-set=false
cmp20.tables.CJI_AHM_REPLY_STATUS.generate-pk-class=false
cmp20.tables.CJI_AHM_STATUS.base-class-name=CjiAhmStatus
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.java-name=statusId
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.java-type=java.lang.Integer
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.local-get=true
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.local-set=false
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.remote-get=false
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_ID.remote-set=false
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.java-name=statusText
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.java-type=java.lang.String
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.local-get=true
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.local-set=true
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.remote-get=false
cmp20.tables.CJI_AHM_STATUS.columns.STATUS_TEXT.remote-set=false
cmp20.tables.CJI_AHM_STATUS.generate-pk-class=false
relations.CJI_AHM-CJI_AHM_REPLY.CJI_AHM-has-CJI_AHM_REPLY.enabled=true
relations.CJI_AHM-CJI_AHM_REPLY.CJI_AHM-has-CJI_AHM_REPLY.target-many=true
relations.CJI_AHM-CJI_AHM_REPLY.CJI_AHM_REPLY-has-CJI_AHM.enabled=true
relations.CJI_AHM-CJI_AHM_REPLY.CJI_AHM_REPLY-has-CJI_AHM.target-many=false
relations.CJI_AHM_DEVICE_TYPE-CJI_AHM.CJI_AHM-has-CJI_AHM_DEVICE_TYPE.enabled=true
relations.CJI_AHM_DEVICE_TYPE-CJI_AHM.CJI_AHM-has-CJI_AHM_DEVICE_TYPE.target-many=false
relations.CJI_AHM_DEVICE_TYPE-CJI_AHM.CJI_AHM_DEVICE_TYPE-has-CJI_AHM.enabled=true
relations.CJI_AHM_DEVICE_TYPE-CJI_AHM.CJI_AHM_DEVICE_TYPE-has-CJI_AHM.target-many=true
relations.CJI_AHM_REPLY_STATUS-CJI_AHM_REPLY.CJI_AHM_REPLY-has-CJI_AHM_REPLY_STATUS.enabled=true
relations.CJI_AHM_REPLY_STATUS-CJI_AHM_REPLY.CJI_AHM_REPLY-has-CJI_AHM_REPLY_STATUS.target-many=false
relations.CJI_AHM_REPLY_STATUS-CJI_AHM_REPLY.CJI_AHM_REPLY_STATUS-has-CJI_AHM_REPLY.enabled=true
relations.CJI_AHM_REPLY_STATUS-CJI_AHM_REPLY.CJI_AHM_REPLY_STATUS-has-CJI_AHM_REPLY.target-many=true
relations.CJI_AHM_STATUS-CJI_AHM.CJI_AHM-has-CJI_AHM_STATUS.enabled=true
relations.CJI_AHM_STATUS-CJI_AHM.CJI_AHM-has-CJI_AHM_STATUS.target-many=false
relations.CJI_AHM_STATUS-CJI_AHM.CJI_AHM_STATUS-has-CJI_AHM.enabled=true
relations.CJI_AHM_STATUS-CJI_AHM.CJI_AHM_STATUS-has-CJI_AHM.target-many=true
tables.CJI_AHM.x=337
tables.CJI_AHM.y=266
tables.CJI_AHM_DEVICE_TYPE.x=612
tables.CJI_AHM_DEVICE_TYPE.y=381
tables.CJI_AHM_REPLY.x=554
tables.CJI_AHM_REPLY.y=60
tables.CJI_AHM_REPLY_STATUS.x=846
tables.CJI_AHM_REPLY_STATUS.y=97
tables.CJI_AHM_STATUS.x=47
tables.CJI_AHM_STATUS.y=304
