ALTER TABLE AUD_DISPOSAL_LINE MODIFY DISPOSAL_LINE_ID NUMBER(9);
ALTER TABLE XHB_DISPOSAL_LINE MODIFY DISPOSAL_LINE_ID NUMBER(9);
ALTER TABLE AUD_EMAIL2 MODIFY MAIL_ID NUMBER(9);
ALTER TABLE XHB_EMAIL2 MODIFY MAIL_ID NUMBER(9);
ALTER TABLE XHB_EMAIL MODIFY MAIL_ID NUMBER(9);
ALTER TABLE AUD_EMAIL MODIFY MAIL_ID NUMBER(9);

exit;