INSERT INTO XHB_REF_EVENT_DESCRIPTION 
(EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS)
SELECT subqry.EXTERNAL_EVENT_CODE, 'Capture Sentence' EVENT_DESCRIPTION, subqry.DISPOSAL_CODE EVENT_SUB_DESCRIPTION, 'Y' SEND_TO_MIS FROM (
	SELECT 13823 EXTERNAL_EVENT_CODE, 'SDPOC'   DISPOSAL_CODE FROM DUAL UNION
	SELECT 13824 EXTERNAL_EVENT_CODE, 'SDPOV'   DISPOSAL_CODE FROM DUAL UNION
	SELECT 13825 EXTERNAL_EVENT_CODE, 'SDPOD'   DISPOSAL_CODE FROM DUAL UNION
	SELECT 13826 EXTERNAL_EVENT_CODE, 'SDPOR'   DISPOSAL_CODE FROM DUAL UNION
	SELECT 13827 EXTERNAL_EVENT_CODE, 'SFOP'   DISPOSAL_CODE FROM DUAL
) subqry 
WHERE NOT EXISTS (SELECT 1 FROM XHB_REF_EVENT_DESCRIPTION x2 
                   WHERE x2.EXTERNAL_EVENT_CODE = subqry.EXTERNAL_EVENT_CODE
                     AND x2.EVENT_SUB_DESCRIPTION = subqry.DISPOSAL_CODE);
commit;