-- COURT ROOM ID is nullable for certain listings
ALTER TABLE XHB_CASE_ON_LIST MODIFY COURT_ROOM_ID NUMBER(8) NULL;
ALTER TABLE AUD_CASE_ON_LIST MODIFY COURT_ROOM_ID NUMBER(8) NULL;

-- SITTING ID constraint was referencing wrong table
ALTER TABLE XHB_CASE_ON_LIST DROP CONSTRAINT XHB_CASE_ON_LIST_SITTING_ID_FK;
ALTER TABLE XHB_CASE_ON_LIST ADD (CONSTRAINT XHB_CASE_ON_LIST_SITTING_ID_FK FOREIGN KEY (SITTING_ID) REFERENCES XHB_SITTING_ON_LIST(SITTING_ON_LIST_ID));

COMMIT;