--ctx-2058

--xhb_case
ALTER TABLE xhb_case RENAME COLUMN DATE_TRANS_TO to DATE_TRANS_TO_OLD;


ALTER TABLE xhb_case ADD DATE_TRANS_TO DATE;


UPDATE xhb_case SET DATE_TRANS_TO = DATE_TRANS_TO_OLD;


ALTER TABLE xhb_case DROP COLUMN DATE_TRANS_TO_OLD;



--aud table
ALTER TABLE aud_case RENAME COLUMN DATE_TRANS_TO to DATE_TRANS_TO_OLD;


ALTER TABLE aud_case ADD DATE_TRANS_TO DATE;


--UPDATE aud_case SET DATE_TRANS_TO = DATE_TRANS_TO_OLD;


ALTER TABLE aud_case DROP COLUMN DATE_TRANS_TO_OLD;

commit;