DROP TABLE XHIBIT.XHB_DMI_DISPOSAL_CODES CASCADE CONSTRAINTS;

CREATE TABLE XHIBIT.XHB_DMI_DISPOSAL_CODES
(
  CREST_DISPOSAL_CODE       VARCHAR2(25 BYTE),
  HO_CODE_IND               VARCHAR2(25 BYTE),
  HO_CODE                   VARCHAR2(25 BYTE),
  DVLC_DISP_CODE            VARCHAR2(25 BYTE),
  DISPOSAL_TYPE             VARCHAR2(25 BYTE),
  DRIVING_DISPOSAL_HO_CODE  VARCHAR2(25 BYTE),
  DISPOSAL_DESCRIPTION      VARCHAR2(250 BYTE),
  LAST_UPDATE_DATE          VARCHAR2(25 BYTE)
);


SET DEFINE OFF;
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('APAID', '0', 'NR', 'Legal Aid Contribution Arrears to be Paid');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('AREM', '0', 'NR', 'Legal Aid Contribution Arrears Remitted');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CSOREV', '0', 'NR', 'Community Service Order Revoked');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DCO', '0', 'NR', 'Defendants Costs Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DCOTC', '0', 'NR', 'Defendants Costs Order: Crown Ct Taxed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DCOTCM', '0', 'NR', 'Defendants Costs Order: Crown and  CtTaxed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISCPRO', '0', 'NR', 'Case Discontinued by Prosecution');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISCREM', '0', 'NR', 'Charges Discontinuedd by Prosecution: Rem Charges remitted to Mag Court');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISMISS', '0', 'NR', 'Case Dismissed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EARLREL', '0', 'NR', 'Early Release');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FIRCERT', '0', 'NR', 'Cancellation of Firearms/Shotgun Certificate');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORSEC', '0', 'NR', 'Bail Security Forfeited');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPX', '0', 'A', 'NR', 'Extended Sentence of Imprisonment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('INTHOSP', '0', 'NR', 'Interim Hospital Order: Specified period');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('JDIS', '0', 'NR', 'Jury Discharged: Other than disagreement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LACPD', '0', 'NR', 'Outstanding legal Aid Contributions to bePaid');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LACREF', '0', 'NR', 'Refunded Legal Aid Contributions');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LACREM', '0', 'NR', 'Remitted LA Contributions');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LACRET', '0', 'NR', 'Retained Legal Aid Contributions');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LICPREM', '0', 'NR', 'Licensed Premises Exclusion Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MISSREM', '0', 'NR', 'Charges Dismissed: Remaining Charges remitted to Magistrates Court');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MITCIRC', '0', 'NR', 'No Disqualification: Mitigating Circumstances S.35(1) RTOA 1988');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NODISQU', '0', 'SD', 'No Disqualification from working with children');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NORDB', '0', 'NR', 'No Order on Breach');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NOTLA', '0', 'NR', 'Notification of Disability to Licencing Authority');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NRDCO', '0', 'NR', 'No RDCO order made');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PARLIC', '0', 'NR', 'Revocation of Parole Licence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCCF', '0', 'NR', 'Prosecution Costs paid from Central Funds');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PODIS', '0', 'NR', 'Discharge of Probation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RDCO', '0', 'NR', 'Recovery of Defence Costs Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RECINST', '0', 'NR', 'Recognisance Estreated: Pay by instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RECTIME', '0', 'NR', 'Recognisance Estreated: Time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMJUV', '0', 'NR', 'Remitted to Juvenile Court');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMMAG', '0', 'NR', 'Remitted to Magistrates Court');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMMENT', '0', 'NR', 'Remand for Report on Mental Condition');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMOVE', '0', 'NR', 'Disposal Removed on Appeal');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMTREA', '0', 'NR', 'Remand for Hospital Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SPECREA', '0', 'NR', 'No Disqualification: Special Reasons S.34(1) RTOA 1988');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SSSOD', '0', 'NR', 'Suspended Sentence Supervision Order Discharged');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('STFREE', '0', 'NR', 'Sent for Trial Free Text Disposal');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TCOMP', '0', 'NR', 'Total compensation');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TCOSTS', '0', 'NR', 'Total costs');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TDISQ', '0', 'NR', 'Total period of disqualification (driving)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TFINE', '0', 'NR', 'Total fine');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TIMP', '0', 'NR', 'Total effective sentence of imprisonment/detention');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TORD', '0', 'NR', 'Total order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TPASU', '0', 'NR', 'Total effective partially suspended sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TPAY', '0', 'NR', 'Total monetary order (other)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TPP', '0', 'NR', 'Total penalty points');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TSUSP', '0', 'NR', 'Total effective suspended sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('UTA', '0', 'NR', 'Jury Discharged: Unable to Agree');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DFL', 'N', '021', 'LI', 'Detention for Life (section 226(2) CJA 2003)', 
    'ADDED 05/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DRIVING_DISPOSAL_HO_CODE, DISPOSAL_DESCRIPTION)
 Values
   ('DISPCCA', '1', 'DD', '675', 'Disqualified under s.147 PCC (Sentencing)Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DRIVING_DISPOSAL_HO_CODE, DISPOSAL_DESCRIPTION)
 Values
   ('DISQ', '1', 'DD', '675', 'Disqualified');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISTOA', '1', 'NR', 'Disqualified under S.35(1) Road Traffic Offenders Act 1988');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DTO', 'Y', '100', 'SD', 'Detention and Training Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DTO', 'N', '105', 'SD', 'Detention and Training Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CC', '140', 'W', 'NR', 'Charge and  Added to Care Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DWLT', '15', 'B', 'SD', 'Detained during Her Majestys Pleasure');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CO', '150', 'W', 'NR', 'Care Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COCC', '150', 'W', 'NR', 'Care Order with Charge and ');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CMPRO', 'N', '165', 'SD', 'Community Punishment and  Order (5042a)', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMB', '165', 'SD', 'Combination Order (old version)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('XCSO', '165', 'SD', 'CSO part of COMBINATION ORDER only');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPO', '170', 'M', 'SD', 'Community Punishment Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CSO', '170', 'M', 'SD', 'Community Service Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CMPO', 'N', '170', 'SD', 'Community Punishment Order (5042)', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CWRKSS', 'N', '171', 'SD', 'Compulsory (unpaid) Work');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DRGRQCS', 'N', '171', 'SD', 'Drug Rehabilitation Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DRGRQSS', 'N', '171', 'SD', 'Drug Rehabilitation Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FTPRCS', '171', 'SD', 'Foreign Travel Prohibition Community Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MHTRTCS', 'N', '171', 'SD', 'Mental Health Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MHTRTSS', 'N', '171', 'SD', 'Mental Health Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PACOBCS', 'N', '171', 'SD', 'Programmes Aimed at Changing Offender Behaviour');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PACOBSS', 'N', '171', 'SD', 'Programmes Aimed at Changing Offender Behaviour');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CWRKCS', 'N', '171', 'SD', 'Compulsory (unpaid) Work');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ATCRQSS', 'N', '171', 'SD', 'Attendance Centre Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ATCRQCS', 'N', '171', 'SD', 'Attendance Centre Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ALTRTSS', 'N', '171', 'SD', 'Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ALTRTCS', 'N', '171', 'SD', 'Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SPVRQSS', 'N', '171', 'SD', 'Supervision Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SPVRQCS', 'N', '171', 'SD', 'Supervision Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESRQSS', 'N', '171', 'SD', 'Residence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESRQCS', 'N', '171', 'SD', 'Residence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PSACTSS', 'N', '171', 'SD', 'Participation in Specified Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PRACTCS', 'N', '171', 'SD', 'Prohibition from Certain Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PRACTSS', 'N', '171', 'SD', 'Prohibition from Certain Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PSACTCS', 'N', '171', 'SD', 'Participation in Specified Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PRACTCS', 'Y', '172', 'SD', 'Prohibition from Certain Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PRACTSS', 'Y', '172', 'SD', 'Prohibition from Certain Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PSACTCS', 'Y', '172', 'SD', 'Participation in Specified Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PSACTSS', 'Y', '172', 'SD', 'Participation in Specified Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESRQCS', 'Y', '172', 'SD', 'Residence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESRQSS', 'Y', '172', 'SD', 'Residence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SPVRQCS', 'Y', '172', 'SD', 'Supervision Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SPVRQSS', 'Y', '172', 'SD', 'Supervision Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ALTRTCS', 'Y', '172', 'SD', 'Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ALTRTSS', 'Y', '172', 'SD', 'Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ATCRQCS', 'Y', '172', 'SD', 'Attendance Centre Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ATCRQSS', 'Y', '172', 'SD', 'Attendance Centre Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CWRKCS', 'Y', '172', 'SD', 'Compulsory (unpaid) Work');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CWRKSS', 'Y', '172', 'SD', 'Compulsory (unpaid) Work');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DRGRQCS', 'Y', '172', 'SD', 'Drug Rehabilitation Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DRGRQSS', 'Y', '172', 'SD', 'Drug Rehabilitation Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MHTRTCS', 'Y', '172', 'SD', 'Mental Health Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('MHTRTSS', 'Y', '172', 'SD', 'Mental Health Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PACOBCS', 'Y', '172', 'SD', 'Programmes Aimed at Changing Offender Behaviour');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PACOBSS', 'Y', '172', 'SD', 'Programmes Aimed at Changing Offender Behaviour');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CURFCS', '173', 'SD', 'Curfew');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CURFSS', '173', 'SD', 'Curfew');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COWEM', '175', 'SD', 'Curfew order with electronic monitoring');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CONEM', '177', 'SD', 'Curfew order without electronic monitoring');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ATTCEN', '180', 'K', 'SD', 'Attendance Centre Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ATCO', 'N', '180', 'SD', 'Attendance centre order', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ATCO', 'N', '180', 'SD', 'Attendance centre order', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('FOSTYR', 'N', '181', 'SD', 'Fostering Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('LARYR', 'N', '181', 'SD', 'Local Authority Residence Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('RESRQYR', 'N', '181', 'SD', 'Residence Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('EXCARYR', 'N', '181', 'SD', 'Exclusion Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CURFYR', 'N', '181', 'SD', 'Curfew Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('PRACTYR', 'N', '181', 'SD', 'Prohibited Activity Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ATCRQYR', 'N', '181', 'SD', 'Attendance Centre Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('PACOYR', 'N', '181', 'SD', 'Programme Requirement disposal ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CWRKYR', 'N', '181', 'SD', 'Unpaid Work disposal ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SPVRQYR', 'N', '181', 'SD', 'Supervision Requirement disposal ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('PSACTYR', 'N', '181', 'SD', 'Extended Activity Requirement disposal ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('MHTRTYR', 'N', '181', 'SD', 'Mental Health Treatment Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DRGRQYR', 'N', '181', 'SD', 'Drug Treatment Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DTYR', 'N', '181', 'SD', 'Drug Testing Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ISTYR', 'N', '181', 'SD', 'Intoxicating Substance Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('EDUCYR', 'N', '181', 'SD', 'Education Requirement ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REPAR', '185', 'SD', 'Reparation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('APO', '190', 'SD', 'Action Plan Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DAO', '192', 'SD', 'Drug Abstinence Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('XCSODR', '194', 'SD', 'CSO with Drug Abstinence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPODAR', '194', 'SD', 'Community Punishment Order: Drugs Abstinence Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DTTO', '195', 'SD', 'Drug Treatment and Testing');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DRIVING_DISPOSAL_HO_CODE, DISPOSAL_DESCRIPTION)
 Values
   ('DISTEST', '2', 'DD', '675', 'Disqualified from driving until Test Passed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('CTFL', 'Y', '20', 'P', 'LI', 
    'Custody for Life');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('CTFL', 'N', '20', 'P', 'LI', 
    'Custody for Life');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXNOMON', '200', 'SD', 'Exclusion Order without electronic monitoring');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXCARSS', '201', 'SD', 'Exclusion from Certain Areas');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXCARCS', '201', 'SD', 'Exclusion from Certain Areas');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXCURSS', 'N', '203', 'SD', 'Exclusion and Curfew Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXCURCS', '203', 'SD', 'Exclusion and Curfew Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXMON', '205', 'SD', 'Exclusion Order with electronic monitoring');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('X208', '208', 'SD', 'Dummy disposal');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('XCUSTEX', '210', 'SD', 'CUSTEXT - Extension part');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SORR', '215', 'SD', 'Supervision Order: with residential requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('LIFELIS', 'N', '22', 'A', 'LI', 
    'Life sentence for second listed offence (over 18)', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('LIFELIS', 'Y', '22', 'A', 'LI', 
    'Life sentence for second listed offence (over 18)', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SONR', '220', 'SD', 'Supervision Order : with night restriction');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SORST', '220', 'H', 'SD', 'Supervision Order: with condition of residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SORFA', '225', 'H', 'SD', 'Supervision Order: refrain from activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIFESEC', 'N', '23', 'A', 'LI', 
    'Mandatory Life Sentence for Second Serious Offence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIFESEC', 'Y', '23', 'A', 'LI', 
    'Mandatory Life Sentence for Second Serious Offence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOSA', '230', 'H', 'SD', 'Supervision Order: with school attendance requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOCDS', '235', 'H', 'SD', 'Supervision Order: comply with directionsof supervisor');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOCDO', '235', 'H', 'SD', 'Supervision Order: comply with directionsin order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DOFO18', '24', 'SD', 'Dangerous Offenders (Aged 18 and over)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('INDET', '24', 'SD', 'Indeterminate Sentence of Detention for Public Protection');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('INIMP', '24', 'SD', 'Indeterminate Sentence of Imprisonment for Public Protection');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOCYPA', '240', 'H', 'SD', 'Supervision Order: S.7(7) CYPA 1969');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SPO', 'N', '240', 'SD', 'Supervision Order', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOPCCA', '240', 'H', 'SD', 'Supervision Order: s.63 PCC (Sentencing)Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOPCCC', '240', 'H', 'SD', 'Supervision Order: s.63 PCC (Sentencing)Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIMM', 'Y', '25', 'A', 'LI', 
    'Life Imprisonment (With minimum period (Effective)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('USS', '25', 'SD', 'Sentence to take effect unaltered');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CSSP', '25', 'NR', 'Consecutive Sentence for Serving Prisoner');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('IMP', 'Y', '25', 'A', 'SD', 
    'Imprisonment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ISS', 'Y', '25', 'SD', 'Sentence to take effect reduced');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIFE', 'Y', '25', 'A', 'LI', 
    'Life Imprisonment (Effective)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMIN', 'N', '26', 'SD', 'Imprisonment - minimum imposed after 3 strikes');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMIN', 'Y', '26', 'SD', 'Imprisonment - minimum imposed after 3 strikes');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRDC', '260', 'G', 'SD', 'Community Rehabilitation Order: Day Centre Attendance');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROC', '260', 'SD', 'Comm Punishment Rehab:with Day Centre Attendance');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PODC', '260', 'G', 'SD', 'Probation Order: Day Centre Attendance');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBC', '260', 'SD', 'Combination Order : Day Centre Attendance');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDROC', '260', 'SD', 'Comm Punishment with D/A Rehab: Day Centre Attendance');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRRA', '262', 'SD', 'Comm Rehab:Requirement as to Activities');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PORA', '262', 'SD', 'Probation Order with Activities Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBA', '262', 'SD', 'Combination Order : Activities Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDROA', '262', 'SD', 'Comm Punishment with D/A Rehab: Activities Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROA', '262', 'SD', 'Comm Punishment Rehab:with Activities Requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDROR', '264', 'SD', 'Comm Punishment with D/A Rehab: ResidenceCondition');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRCR', '264', 'G', 'SD', 'Community Rehabilitation Order: Conditionof Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROR', '264', 'SD', 'Comm Punishment Rehab:with Residence Condition');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBR', '264', 'SD', 'Combination Order : Condition of Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('POCR', '264', 'G', 'SD', 'Probation Order: Condition of Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPRNH', '266', 'SD', 'Community Punishment and Rehab Order: NonResident Hospital Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDRHR', '266', 'SD', 'Community Punishment with D/A Rehab Order: Hospital Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDRNH', '266', 'SD', 'Comm Punishment with D/A Rehab Order: NonResident Hosp Treat');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRNH', '266', 'G', 'SD', 'Comm Rehab:Non Resident Hospital Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPRHR', '266', 'SD', 'Community Punishment and Rehabilitation Order: Hospital Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBH', '266', 'SD', 'Combination Order : Hospital Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROH', '266', 'SD', 'Comm Punishment and :with Hospital Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PONH', '266', 'G', 'SD', 'Probation Order: Non Resident Hospital treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRHR', '266', 'G', 'SD', 'Community Rehabilitation Order: HospitalResidence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PORH', '266', 'G', 'SD', 'Probation Order: Hospital Residence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDROD', '268', 'SD', 'Comm Punishment with D/A Rehab with Drugs/Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBD', '268', 'SD', 'Combination Order : Drug/Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PODA', '268', 'SD', 'Probation Order with Drugs/Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRDA', '268', 'SD', 'Community Rehabilitation Order: Drug/Alcohol Treatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROD', '268', 'SD', 'Comm Punishment Rehab with Drugs/AlcoholTreatment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CUSTEXT', '27', 'SD', 'CUSTEXT - Custody part');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CROCUR', '276', 'SD', 'Community Rehabilitation Order with Curfew Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPRCUR', '276', 'SD', 'Community Punishment and Rehabilitation Order: Curfew Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDRCUR', '276', 'SD', 'Community Punishment with D/A Rehab Order: Curfew Req');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDREXC', '277', 'SD', 'Community Punishment with D/A and  Order: Exclusion Req');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPREXC', '277', 'SD', 'Community Punishment and Rehabilitation Order: Exclusion Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CROEXC', '277', 'SD', 'Community Rehabilitation Order with Exclusion Requirements');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDRDAR', '278', 'SD', 'Community Punishment with D/A Rehab Order: Drug Abst. req');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPRDAR', '278', 'SD', 'Community Punishment and Rehabilitation Order: Drug Abstinence req');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CRODAR', '278', 'SD', 'Community Rehabilitation Order: Drug Abstinence requirement');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('EXDO18', '28', 'SD', 'Extended Sentence of Imprisonment (discretionary over 18) - LASPO 2012', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('CPO21CS', '28', 'SD', 'Custody Plus (Adults 21 and )(Consecutive)', 'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CRO', 'N', '280', 'SD', 'Community Rehabilitation Order (5037)', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('COMBG', '280', 'SD', 'Combination Order and General Probation');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PROB', '280', 'G', 'SD', 'General Probation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPROG', '280', 'SD', 'Comm Punishment General Rehab Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CPDROG', '280', 'SD', 'Comm Punishment with D/A General Rehab Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CROG', '280', 'G', 'SD', 'General Community Rehabilitation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ICWD', 'Y', '29', 'SD', 'Intermittent Custody Order Total (Weekday)', 
    'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('EXAO18', '29', 'SD', 'Extended Sentence of Imprisonment (automatic over 18) - LASPO 2012', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ICWE', 'Y', '29', 'SD', 'Intermittent Custody Order Total (Weekend)', 
    'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DRIVING_DISPOSAL_HO_CODE, DISPOSAL_DESCRIPTION)
 Values
   ('LEND', '3', 'DD', '675', 'Licence Endorsed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DRIVING_DISPOSAL_HO_CODE, DISPOSAL_DESCRIPTION)
 Values
   ('LENDPP', '3', 'DD', '675', 'Licence Endorsed with Penalty Points');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('CPO21CC', '30', 'SD', 'Custody Plus (Adults 21 and )(Concurrent)', 'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('PASU', 'Y', '30', 'X', 'NR', 
    'Partially Suspended Sentence', 'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LIFESYO', 'Y', '31', 'LI', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('LIFESYO', 'N', '31', 'LI', 'Mandatory Life Sentence for Second Serious Offence (Young Offender)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ADISQU', '312', 'SD', 'Adult: Disqualification from working with children');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('JDISQU', '313', 'SD', 'Juvenile: Disqualification from working with children');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXPTIME', '315', 'NR', 'Excise Penalty with time to pay and Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('FD', 'Y', '315', 'Q', 'SD', 
    'Fine with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FD', 'N', '315', 'SD', 'Fine with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('FDINST', 'Y', '315', 'Q', 'SD', 
    'Fine by instalments with Imprisonment indefault');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('FDTIME', 'Y', '315', 'Q', 'SD', 
    'Fine with time to pay and with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FDTIME', 'N', '315', 'SD', 'Fine with time to pay and with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FINE', 'N', '315', 'SD', 'Fine');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('FINE', 'Y', '315', 'Q', 'SD', 
    'Fine');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXPD', '315', 'NR', 'Excise Penalty with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXPO', '315', 'NR', 'Excise Penalty');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('EXPINST', '315', 'NR', 'Excise Penalty by instalments with Imprisonment in default');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FDINST', 'N', '315', 'SD', 'Fine by instalments with Imprisonment indefault');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('VISUR', '316', 'SD', 'Victim Surcharge');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ASBOSEN', '317', 'SD', 'Order re anti-social behaviour additional to sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IASBO', '318', 'SD', 'Interim Anti-Social Behaviour Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CRIBO', 'N', '319', 'SD', 'Criminal Behaviour Order', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('LIFELYO', 'N', '32', 'LI', 'Life sentence for second listed offence (under 18)', 
    'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('LIFELYO', 'Y', '32', 'LI', 'Life sentence for second listed offence (under 18)', 
    'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CDO', 'N', '320', 'SD', 'Conditional Discharge (5040)', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CD', '320', 'E', 'SD', 'Conditional Discharge Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ASBOCD', '322', 'SD', 'Order re anti-social behaviour additional to conditional discharge');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IASBOCD', '323', 'SD', 'Interim Anti-Social Behaviour Order (on conditional discharge)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PREDTO', '325', 'SD', 'Pre-sentence Drug Testing Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMYO', 'N', '33', 'SD', 'Imprisonment - Minimum Imposed after 3 Strikes (Young Offender)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMYO', 'Y', '33', 'SD', 'Imprisonment - Minimum Imposed after 3 Strikes (Young Offender)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BOJDG', '330', 'F', 'SD', 'Bind Over to Appear for Judgment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BOJDGD', '330', 'F', 'SD', 'Bind Over to Appear for Judgment on Date given');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BOCOND', '340', 'F', 'SD', 'Bind Over with Conditions');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('BOGB', 'Y', '340', 'F', 'SD', 
    'Bind Over');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FOOTBAN', '343', 'SD', 'Football Banning Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FOOTRES', '345', 'SD', 'Restriction Order S15 Football SpectatorsAct 1989');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FOOTEX', '347', 'SD', 'Football Exclusion Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ISS', 'N', '35', 'SD', 'Sentence to take effect reduced');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIMM', 'N', '35', 'A', 'LI', 
    'Life Imprisonment (With minimum period)(Non-effective)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('LIFE', 'N', '35', 'A', 'LI', 
    'Life Imprisonment (Non-Effective');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('IMP', 'N', '35', 'A', 'SD', 
    'Imprisonment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ODIMP', '350', 'A', 'SD', '1 day imp/detention/Crown Court cells');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('TRO', '355', 'SD', 'Travel Restriction Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ICWE', 'N', '36', 'SD', 'Intermittent Custody Order Total (Weekend)', 
    'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ICWD', 'N', '36', 'SD', 'Intermittent Custody Order Total (Weekday)', 
    'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISWP', '360', 'SD', 'Discharged without penalty (Convicted defendant)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ABDIS', '360', 'J', 'SD', 'Absolute Discharge');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('EXDU18', '38', 'SD', 'Extended Sentence of Imprisonment (discretionary under 18) - LASPO 2012', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('CPU21CS', '38', 'SD', 'Custody Plus (Offenders aged 18-20 yrs)(Consecutive)', 'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTA', 'N', '380', 'NR', 'Prosecution Costs Taxed or Alternative');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTAI', 'N', '380', 'NR', 'Prosecution Costs Taxed or Alternative byinstalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTAT', 'N', '380', 'NR', 'Prosecution Costs Taxed or Alternative with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCINST', 'N', '380', 'NR', 'Prosecution Costs by Instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTINST', 'N', '380', 'NR', 'Prosecution Costs Taxed and paid by instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTTIME', 'N', '380', 'NR', 'Prosecution Costs Taxed with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCT', 'N', '380', 'NR', 'Prosecution Costs Taxed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PC', 'N', '380', 'NR', 'Prosecution Costs');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PCTIME', 'N', '380', 'NR', 'Prosecution Costs with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('EXAU18', '39', 'SD', 'Extended Sentence of Imprisonment (automatic under 18) - LASPO 2012', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('CPU21CC', '39', 'SD', 'Custody Plus (Offenders aged 18-20 yrs)(Concurrent)', 'REMOVED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('IMPE', 'N', '40', 'SD', 'Imprisonment  Extended under s236A of CJA2003 ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PASU', 'N', '40', 'X', 'NR', 
    'Partially Suspended Sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMINE', '41', 'SD', 'Imprisonmt - Min imposed after 3 strikes - Extended (s236A of CJA2003)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IMPMYOE', '42', 'SD', 'Imprisonment - Min Imprisonmnt - Min Imposed after 3 Strikes  -YO Extended  s236A of CJA2003');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('HOSOR', 'N', '425', 'SD', 'Hospital Order with restrictions (5034)', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('YOIE', 'N', '43', 'SD', 'Detention in a Y.O.I  Extended under s236A of CJA2003 ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DET', '45', 'B', 'SD', 'Detention under s.91 PCC (Sentencing) Act2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('HOSPOR', 'Y', '460', 'T', 'SD', 
    'Hospital Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('GOREL', '470', 'T', 'SD', 'Guardianship Order: Relative');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('GOOTH', '470', 'T', 'SD', 'Guardianship Order: Other');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('GOAUTH', '470', 'T', 'SD', 'Guardianship Order: Authority');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('HOLIDIR', 'N', '480', 'SD', 'Hospital and Limitation Direction');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('HOLIDIR', 'Y', '480', 'SD', 'Hospital and Limitation Direction');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('SFORO', 'Y', '50', 'T', 'SD', 
    'Restriction Order under s.41 of Mental Health Act 1983');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('RESL', 'Y', '50', 'T', 'SD', 
    'Restriction Order with time limit');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('RESNL', 'Y', '50', 'T', 'SD', 
    'Restriction Order without time limit');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RDEPD', '520', 'SD', 'Recommendation for Deportation: Detained');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RDEP', '520', 'SD', 'Recommendation for Deportation');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RDEPND', '520', 'SD', 'Recommendation for Deportation: Not Detained');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COM', 'Y', '530', 'Q', 'SD', 
    'Compensation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COMTIME', 'Y', '530', 'Q', 'SD', 
    'Compensation Order with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COMINST', 'Y', '530', 'Q', 'SD', 
    'Compensation Order by instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COM', 'N', '530', 'S', 'SD', 
    'Compensation Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COMTIME', 'N', '530', 'S', 'SD', 
    'Compensation Order with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('COMINST', 'N', '530', 'S', 'SD', 
    'Compensation Order by instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTTIME', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PARENT', 'Y', '540', 'SD', 'PARENT-TO-PAY part of financial disposals');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PC', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PARENT', 'N', '540', 'SD', 'PARENT-TO-PAY part of financial disposals');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCINST', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs by Instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTINST', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed and paid by instalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTIME', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTAT', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed or Alternative with time to pay');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTAI', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed or Alternative byinstalments');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCTA', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed or Alternative');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('PCT', 'Y', '540', 'Q', 'NR', 
    'Prosecution Costs Taxed');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PAREN', '545', 'SD', 'Parenting Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PGBO', '550', 'Q', 'SD', 'Parent/Guardian Bind Over');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESTORD', '560', 'SD', 'Restitution Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DTCO', '580', 'SD', 'Confiscation Order under S1(5) DTOA 1986');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CJCO', '580', 'SD', 'Confiscation Order under S71 CJA 1988');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DTCOR', 'N', '580', 'SD', 'Confiscation Order under s1(5) DTOA 1986', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('POCCON', '580', 'SD', 'Confiscation Order under Proceeds of Crime Act 2002');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DT94CON', '585', 'SD', 'Confiscation Order under s.2 Drug Trafficking Act 1994');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('CRIMCC', 'N', '586', 'SD', 'Criminal Courts Charge ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SLATRO', 'N', '587', 'SD', 'Slavery and Trafficking Reparation Order  ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SLATRTP', 'N', '588', 'SD', 'Slavery and Trafficking Reparation Order with time to pay ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SLATRIN', 'N', '589', 'SD', 'Slavery and Trafficking Reparation Order by instalments', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('FORO', 'N', '590', 'SD', 'Forfeiture Order', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DEPR', '590', 'SD', 'Deprivation of Rights under s.143 PCC (Sentencing) Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORDRUG', '590', 'SD', 'Forfeiture under S.27 Misuse of Drugs Act1971');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORFIRE', '590', 'SD', 'Forfeiture under S.52(1) Firearms Act 1968');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORGERY', '590', 'SD', 'Forgery under s.24 Forgery and Counterfeiting Act 1981');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORPCCA', '590', 'SD', 'Forfeiture other than vehicle under s.143PCC (Sentencing) Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FOROBS', '590', 'SD', 'Forfeiture of Articles under Obscene Publications Act');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FORPOA', '590', 'SD', 'Forfeiture under S.25 Public Order Act 1986');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FOVPCCA', '595', 'SD', 'Forfeiture of vehicle under s.143 PCC (Sentencing) Act 2000');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('FORMODS', 'N', '596', 'SD', 'Forfeiture Order under Modern Slavery Act 2015', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('STPO', 'N', '597', 'SD', 'Slavery and Trafficking Prevention Order ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ISTPO', 'N', '598', 'SD', 'Interim Slavery and Trafficking Prevention ', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CUSMSEC', '60', 'SD', 'Suspended Sentence (CJA 2003) (Consecutive)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NSP', '600', 'SD', 'No Separate Penalty');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CUSMCUR', '62', 'SD', 'Suspended Sentence (CJA 2003) (Concurrent)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NOBSS', '630', 'SD', 'No Order on Breach of Suspended Sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ORDVAR', '630', 'SD', 'Order Varied: Substitute New Period fromToday');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SSSO', '650', 'D', 'SD', 'Suspended Sentence Supervision Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SSSOC', '655', 'SD', 'Suspended Sentence Supervision Order to Continue');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RESOR', '660', 'SD', 'Restraining Order Protection from Harassment Act 1997');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SEXRESO', 'Y', '666', 'SD', 'Restraining Order under s.5A Sexual Offenders Act 1997');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DIRDIS', 'N', '668', 'SD', 'Disqualification under Directors Disqualification Act', 
    'Added 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISQAO', '670', 'SD', 'Disqualification From Driving (Any Offence)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('REHARSS', 'N', '671', 'SD', 'Rehabilitation Activity Requirement (Suspended Sentence)', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('REHARCS', 'N', '672', 'SD', 'Rehabilitation Activity Requirement (Community Sentence)', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISQVC', '675', 'SD', 'Disqualification From Driving (Vehicle Used For Crime)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOPO', 'Y', '680', 'SD', 'Sexual Offences Prevention Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SHPO', 'N', '681', 'SD', 'Sexual Harm Prevention Order', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('ISHPO', 'N', '682', 'SD', 'Interim Sexual Harm Prevention Order', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FINRO', '685', 'SD', 'Financial Reporting Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('BARR', 'N', '686', 'SD', 'May be placed on barring list', 
    'Added 03/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('FGMPO', 'N', '687', 'SD', 'Female Genital Mutilation Protection Order ', 
    'ADDED 05/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('SCPO', 'N', '688', 'SD', 'Serious Crime Prevention Order', 
    'ADDED 05/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('POPSA', 'N', '689', 'SD', 'Prohibition Order Under the Psychoactive Substances Act 2016', 
    'Added 11/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('POPSA', 'N', '689', 'SD', 'Prohibition Order under the psychoactive Substances Act 2016.', 
    'Added 06/2016');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '9', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '8', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '3', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '1', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '2', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '5', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '4', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', 'COU', '690', 'FR', 'FREE Text disposal for trial / sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, 
    LAST_UPDATE_DATE)
 Values
   ('DIRDIS', 'N', '690', 'SD', 'Disqualification under Directors Disqualification Act', 
    'Removed 07/2015');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REWARD', '690', 'NR', 'Reward Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SODIS', '690', 'NR', 'Supervision Order Discharged');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '10', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '13', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '12', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '11', '690', 'FR', 'FREE Text disposal for appeals (G)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION, LAST_UPDATE_DATE)
 Values
   ('CUSMSSE', '70', 'SD', 'Suspended Sentence (CJA 2003 (Not consecutive or concurrent)', 'ADDED 08/2012');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SS', '70', 'C', 'SD', 'Suspended Sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FTPRSS', '70', 'SD', 'Foreign Travel Prohibition Suspended sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('UNDIS', '780', 'SD', 'Found under Disability: Admit to Hospital');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NGINS', '785', 'SD', 'Not Guilty by Reason of Insanity');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('RESL', 'N', '790', 'T', 'NR', 
    'Restriction Order with time limit');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('RESNL', 'N', '790', 'T', 'NR', 
    'Restriction Order without time limit');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('SFORO', 'N', '790', 'T', 'NR', 
    'Restriction Order under s.41 of Mental Health Act 1983');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('CERTINS', '790', 'SD', 'Not tried: Certified insane before arraignment');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('HOSPOR', 'N', '790', 'T', 'SD', 
    'Hospital Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SEXRESO', 'N', '800', 'SD', 'Restraining Order under s.5A Sexual Offenders Act 1997');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOPO', 'N', '802', 'SD', 'Sexual Offences Prevention Order');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NOEV', '810', 'SD', 'Pros Offer No Evidence (Not a Summary offence)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DISCH', '810', 'SD', 'Defendant Discharged');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ACQ', '810', 'SD', 'Acquitted : To be checked by User Team');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NOEVS', '810', 'SD', 'Pros Offer No Evidence (Summary offencesonly)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('PLESS', '812', 'SD', 'Plea stage lesser offence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('VLESS', '814', 'SD', 'Verdict stage lesser offence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ALTCT', '830', 'SD', 'Alternative Count: Jury Discharged from Verdict');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('NGDIR', '840', 'SD', 'Not Guilty by Direction');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('YOI', 'Y', '85', 'P', 'SD', 
    'Detention in a Y.O.I. (consecutive)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('YOI', 'N', '90', 'P', 'SD', 
    'Detention in a Y.O.I. (concurrent)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DVLC_DISP_CODE, DISPOSAL_TYPE, 
    DISPOSAL_DESCRIPTION)
 Values
   ('BOGB', 'N', '920', 'F', 'SD', 
    'Bind Over');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ROWOC', '923', 'SD', 'Restraining Order w/o Conviction (Prot from Harassment Act 1997 s5a)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('SOPOP', '925', 'SD', 'Sexual Offences Prevention Order (Application by Police)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('RSHOP', '926', 'SD', 'Risk of Sexual Harm Order (Application byPolice)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('IRSHO', '927', 'SD', 'Interim Risk of Sexual Harm Order (Application by Police)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('ISOPO', '928', 'SD', 'Interim Sexual Offences Prevention Order(Application by Police)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('REMFILE', '930', 'SD', 'Count/Indictment to Remain on File');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('X932', '932', 'SD', 'Dummy disposal');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DEFDEC', '945', 'SD', 'Defendant Deceased: indictment of no effect');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('DEFSUIC', '950', 'SD', 'Defendant Suicide: Indictment of no effect');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BWBAILN', '980', 'SD', 'Not Backed for Bail: Failed to answer bail');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BWSUMB', '980', 'NR', 'Backed for Bail: Failed to answer summons');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BWBAILB', '980', 'SD', 'Backed for Bail: Failed to answer bail');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('BWSUMN', '980', 'NR', 'Not Backed for Bail: Failed to answer summons');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', 'CHG', '990', 'FR', 'FREE Text disposal for trial / sentence');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '7', '990', 'FR', 'FREE Text disposal for appeals (NG)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE_IND, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('FREE', '6', '990', 'FR', 'FREE Text disposal for appeals (NG)');
Insert into XHIBIT.XHB_DMI_DISPOSAL_CODES
   (CREST_DISPOSAL_CODE, HO_CODE, DISPOSAL_TYPE, DISPOSAL_DESCRIPTION)
 Values
   ('QUASH', '996', 'SD', 'Count/Indictment Quashed');
COMMIT;

