SET DEFINE OFF;
Insert into XHIBIT.XHB_DMI_CAD_REF_CODE
   (DMI_CAD_REF_CODE_ID, DMI_CAD_REF_CODE_DESCRIPTION, CREATION_DATE, CREATED_BY, OBS_IND, 
    DMI_CAD_REF_CODE_SHORT_NAME)
 Values
   (1, 'Process Started', TO_DATE('04/12/2018 09:50:36', 'MM/DD/YYYY HH24:MI:SS'), 'XHIBIT', 'N', 
    'S');
Insert into XHIBIT.XHB_DMI_CAD_REF_CODE
   (DMI_CAD_REF_CODE_ID, DMI_CAD_REF_CODE_DESCRIPTION, CREATION_DATE, CREATED_BY, OBS_IND, 
    DMI_CAD_REF_CODE_SHORT_NAME)
 Values
   (2, 'In Process', TO_DATE('04/12/2018 09:50:54', 'MM/DD/YYYY HH24:MI:SS'), 'XHIBIT', 'N', 
    'P');
Insert into XHIBIT.XHB_DMI_CAD_REF_CODE
   (DMI_CAD_REF_CODE_ID, DMI_CAD_REF_CODE_DESCRIPTION, CREATION_DATE, CREATED_BY, OBS_IND, 
    DMI_CAD_REF_CODE_SHORT_NAME)
 Values
   (3, 'Complete', TO_DATE('04/12/2018 09:51:07', 'MM/DD/YYYY HH24:MI:SS'), 'XHIBIT', 'N', 
    'C');
Insert into XHIBIT.XHB_DMI_CAD_REF_CODE
   (DMI_CAD_REF_CODE_ID, DMI_CAD_REF_CODE_DESCRIPTION, CREATION_DATE, CREATED_BY, OBS_IND, 
    DMI_CAD_REF_CODE_SHORT_NAME)
 Values
   (4, 'Exception Handler Raised', TO_DATE('04/12/2018 09:51:23', 'MM/DD/YYYY HH24:MI:SS'), 'XHIBIT', 'N', 
    'X');
Insert into XHIBIT.XHB_DMI_CAD_REF_CODE
   (DMI_CAD_REF_CODE_ID, DMI_CAD_REF_CODE_DESCRIPTION, CREATION_DATE, CREATED_BY, OBS_IND, 
    DMI_CAD_REF_CODE_SHORT_NAME)
 Values
   (5, 'Error', TO_DATE('04/12/2018 09:51:34', 'MM/DD/YYYY HH24:MI:SS'), 'XHIBIT', 'N', 
    'E');
COMMIT;

