CREATE INDEX XHB_COURTEL_XML_DOC_ID ON XHB_COURTEL_LIST(xml_document_id);

CREATE INDEX XHB_CHARGES_LOG_CASE_ID ON XHB_CHARGES_LOG(case_id);

CREATE INDEX XHB_CASE_COURT_CASE_GROUP ON XHB_CASE(court_id,case_id,case_group_number);

CREATE INDEX XHB_DIARY_NOTE_COURT_DIARYDATE ON XHB_DIARY_NOTE_ENTRY(court_id,diary_date);

CREATE INDEX XHB_DEFCASE_DEF_RESV_OBS_CASE ON XHB_DEFENDANT_ON_CASE(defendant_id,results_verified,obs_ind,case_id);

COMMIT;