/*
 * Filename:    DB_Patch_6.1..1sql
 *
 * System:      System Test, Development Systems
 *              Integration 1 & 2, Merc Dev development
 *
 * Date:        24th June 2004
 *
 */


/*
 * Changes to XHB_ table definitions, indexes and foreign keys
 *
 * Additions or deletion of XHB_ tables, indexes and foreign keys
 *
 */


/*
 * Changes, additions or deletion of views
 */

CREATE OR REPLACE VIEW XHB_COUNSEL_FACILITIES_SH_V AS
SELECT DISTINCT
		sitting.court_room_id                         	COURT_ROOM_ID,
		sitting.is_floating                           	IS_FLOATING,
		sitting.sitting_sequence_no						SITTING_SEQUENCE_NO,
		hearing_list.start_date                       	START_DATE,
		hearing_list.court_id                       	COURT_ID,
		court_room.description                       	COURT_ROOM_DESCRIPTION,
		court_room.display_name                       	COURT_ROOM_DISPLAY_NAME,
		court_room.court_room_name                    	COURT_ROOM_NAME,
		court_room.crest_court_room_no                	CREST_COURT_ROOM_NO,
		court_site.court_site_code						COURT_SITE_CODE,
		court_site.short_name				COURT_SITE_SHORT_NAME,
		ref_hearing_type.hearing_type_code            	HEARING_TYPE_CODE,
		ref_hearing_type.hearing_type_desc            	HEARING_TYPE_DESC,
		sh_staff.staff_name                           	STAFF_NAME,
		sh_staff.staff_role                           	STAFF_ROLE,
		scheduled_hearing.scheduled_hearing_id        	SCHEDULED_HEARING_ID,
		scheduled_hearing.sequence_no					SH_SEQUENCE_NO,
		NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time) TIME_LISTED, 
		sched_hearing_defendant.sched_hear_def_id     	SCHED_HEAR_DEF_ID,
		defendant_on_case.defendant_on_case_id        	DEFENDANT_ON_CASE_ID,
		defendant_on_case.is_masked                   	IS_MASKED,
		defendant_on_case.masked_name 			MASKED_NAME,
		defendant.defendant_id				DEFENDANT_ID,
		defendant.first_name 				DEF_FIRST_NAME,
		defendant.middle_name 				DEF_MIDDLE_NAME,
		defendant.surname 				DEF_SURNAME,
		defendant.initials 				DEF_INITIALS,
		xcase.case_id					CASE_ID,
		xcase.case_number 				CASE_NUMBER,
		xcase.case_type					CASE_TYPE,
		xcase.case_sub_type				CASE_SUB_TYPE,
		xcase.case_title				CASE_TITLE,
		sh_leg_rep.sh_leg_rep_id			SH_LEG_REP_ID,
		sh_leg_rep.legal_role				LEGAL_ROLE,
		sh_leg_rep.sol_firm_or_ref_legal_rep				SOL_FIRM_OR_REF_LEGAL_REP,
		legal_rep.ref_legal_rep_id			REF_LEGAL_REP_ID,
		legal_rep.first_name 				LEG_REP_FIRST_NAME,
		legal_rep.middle_name 				LEG_REP_MIDDLE_NAME,
		legal_rep.surname 				LEG_REP_SURNAME,
		legal_rep.title 				LEG_REP_TITLE,
		legal_rep.initials 				LEG_REP_INITIALS,
		legal_rep.legal_rep_type			LEGAL_REP_TYPE,
		advocate.ref_advocate_id			REF_ADVOCATE_ID,
		chamber.ref_chamber_id				REF_CHAMBER_ID,
		chamber.firm_name 				CHAMBER_FIRM_NAME,
		adv_address.address_id 				ADV_ADDRESS_ID,
		adv_address.address_1 				ADV_ADDRESS_1,
		adv_address.address_2 				ADV_ADDRESS_2,
		adv_address.address_3 				ADV_ADDRESS_3,
		adv_address.address_4  				ADV_ADDRESS_4,
		adv_address.town  				ADV_TOWN,
		adv_address.county 				ADV_COUNTY,
		adv_address.country 				ADV_COUNTRY,
		adv_address.postcode 				ADV_POSTCODE,
		solicitor.solicitor_id				SOLICITOR_ID,
		solfirm.ref_solicitor_firm_id			REF_SOLICITOR_FIRM_ID,
		solfirm.solicitor_firm_name			SOLICITOR_FIRM_NAME,
		sol_address.address_id 				SOL_ADDRESS_ID,
		sol_address.address_1  				SOL_ADDRESS_1,
		sol_address.address_2  				SOL_ADDRESS_2,
		sol_address.address_3  				SOL_ADDRESS_3,
		sol_address.address_4  				SOL_ADDRESS_4,
		sol_address.town  				SOL_TOWN,
		sol_address.county  				SOL_COUNTY,
		sol_address.country  				SOL_COUNTRY,
		sol_address.postcode 				SOL_POSTCODE
             FROM
		XHB_HEARING_LIST             HEARING_LIST,
		XHB_SITTING                  SITTING,
		XHB_COURT_ROOM               COURT_ROOM,
		XHB_COURT_SITE				 COURT_SITE,
		XHB_SCHEDULED_HEARING        SCHEDULED_HEARING,
		XHB_HEARING                  HEARING,
		XHB_REF_HEARING_TYPE         REF_HEARING_TYPE,
		XHB_SCHED_HEARING_ATTENDEE   SH_ATTENDEE,
		XHB_SH_STAFF                 SH_STAFF,
		XHB_SCHED_HEARING_DEFENDANT  SCHED_HEARING_DEFENDANT,
		XHB_DEFENDANT_ON_CASE        DEFENDANT_ON_CASE,
		XHB_DEFENDANT                DEFENDANT,
		XHB_CASE                     XCASE,
		XHB_SH_LEG_REP               SH_LEG_REP,
		XHB_REF_LEGAL_REPRESENTATIVE LEGAL_REP,
		XHB_REF_ADVOCATE             ADVOCATE,
		XHB_REF_CHAMBER              CHAMBER,
		XHB_REF_SOLICITOR            SOLICITOR,
		XHB_REF_SOLICITOR_FIRM       SOLFIRM,
		XHB_ADDRESS                  ADV_ADDRESS,
		XHB_ADDRESS                  SOL_ADDRESS
             WHERE
		( hearing_list.list_id = sitting.list_id ) AND
		( sitting.court_room_id = court_room.court_room_id ) AND
		( court_room.court_site_id = court_site.court_site_id ) AND
		( scheduled_hearing.sitting_id = sitting.sitting_id ) AND
		( scheduled_hearing.scheduled_hearing_id = sched_hearing_defendant.scheduled_hearing_id(+) ) AND
		( scheduled_hearing.hearing_id = hearing.hearing_id ) AND
		( scheduled_hearing.scheduled_hearing_id = sh_attendee.scheduled_hearing_id(+) ) AND
		( sh_attendee.sh_staff_id = sh_staff.sh_staff_id(+) ) AND
		( hearing.case_id = xcase.case_id ) AND
		( hearing.ref_hearing_type_id = ref_hearing_type.ref_hearing_type_id ) AND
		( sched_hearing_defendant.defendant_on_case_id = defendant_on_case.defendant_on_case_id(+) ) AND
		( defendant_on_case.defendant_id = defendant.defendant_id(+) ) AND
		( scheduled_hearing.scheduled_hearing_id = sh_leg_rep.scheduled_hearing_id(+) AND sh_leg_rep.sched_hear_def_id IS NULL) AND
		( sh_leg_rep.ref_legal_rep_id = legal_rep.ref_legal_rep_id(+) ) AND
		( legal_rep.ref_legal_rep_id = advocate.ref_legal_rep_id(+) ) AND
		( advocate.ref_chamber_id = chamber.ref_chamber_id(+) ) AND
		( chamber.address_id = adv_address.address_id(+) ) AND
		( legal_rep.ref_legal_rep_id = solicitor.ref_legal_rep_id(+) ) AND
		( solicitor.ref_solicitor_firm_id = solfirm.ref_solicitor_firm_id(+) ) AND
		( solfirm.address_id = sol_address.address_id(+) );

CREATE OR REPLACE VIEW XHB_COUNSEL_FACILITIES_SHDID_V AS
SELECT DISTINCT
		sitting.court_room_id                         	COURT_ROOM_ID,
		sitting.is_floating                           	IS_FLOATING,
		sitting.sitting_sequence_no						SITTING_SEQUENCE_NO,
		hearing_list.start_date                       	START_DATE,
		hearing_list.court_id                       	COURT_ID,
		court_room.description                       	COURT_ROOM_DESCRIPTION,
		court_room.display_name                       	COURT_ROOM_DISPLAY_NAME,
		court_room.court_room_name                    	COURT_ROOM_NAME,
		court_room.crest_court_room_no                	CREST_COURT_ROOM_NO,
		court_site.court_site_code						COURT_SITE_CODE,
		court_site.short_name				COURT_SITE_SHORT_NAME,
		ref_hearing_type.hearing_type_code            	HEARING_TYPE_CODE,
		ref_hearing_type.hearing_type_desc            	HEARING_TYPE_DESC,
		sh_staff.staff_name                           	STAFF_NAME,
		sh_staff.staff_role                           	STAFF_ROLE,
		scheduled_hearing.scheduled_hearing_id        	SCHEDULED_HEARING_ID,
		scheduled_hearing.sequence_no					SH_SEQUENCE_NO,
		NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time) TIME_LISTED, 
		sched_hearing_defendant.sched_hear_def_id     	SCHED_HEAR_DEF_ID,
		defendant_on_case.defendant_on_case_id        	DEFENDANT_ON_CASE_ID,
		defendant_on_case.is_masked                   	IS_MASKED,
		defendant_on_case.masked_name 			MASKED_NAME,
		defendant.defendant_id				DEFENDANT_ID,
		defendant.first_name 				DEF_FIRST_NAME,
		defendant.middle_name 				DEF_MIDDLE_NAME,
		defendant.surname 				DEF_SURNAME,
		defendant.initials 				DEF_INITIALS,
		xcase.case_id					CASE_ID,
		xcase.case_number 				CASE_NUMBER,
		xcase.case_type					CASE_TYPE,
		xcase.case_sub_type				CASE_SUB_TYPE,
		xcase.case_title				CASE_TITLE,
		sh_leg_rep.sh_leg_rep_id			SH_LEG_REP_ID,
		sh_leg_rep.legal_role				LEGAL_ROLE,
		sh_leg_rep.sol_firm_or_ref_legal_rep				SOL_FIRM_OR_REF_LEGAL_REP,
		legal_rep.ref_legal_rep_id			REF_LEGAL_REP_ID,
		legal_rep.first_name 				LEG_REP_FIRST_NAME,
		legal_rep.middle_name 				LEG_REP_MIDDLE_NAME,
		legal_rep.surname 				LEG_REP_SURNAME,
		legal_rep.title 				LEG_REP_TITLE,
		legal_rep.initials 				LEG_REP_INITIALS,
		legal_rep.legal_rep_type			LEGAL_REP_TYPE,
		advocate.ref_advocate_id			REF_ADVOCATE_ID,
		chamber.ref_chamber_id				REF_CHAMBER_ID,
		chamber.firm_name 				CHAMBER_FIRM_NAME,
		adv_address.address_id 				ADV_ADDRESS_ID,
		adv_address.address_1 				ADV_ADDRESS_1,
		adv_address.address_2 				ADV_ADDRESS_2,
		adv_address.address_3 				ADV_ADDRESS_3,
		adv_address.address_4  				ADV_ADDRESS_4,
		adv_address.town  				ADV_TOWN,
		adv_address.county 				ADV_COUNTY,
		adv_address.country 				ADV_COUNTRY,
		adv_address.postcode 				ADV_POSTCODE,
		solicitor.solicitor_id				SOLICITOR_ID,
		solfirm.ref_solicitor_firm_id			REF_SOLICITOR_FIRM_ID,
		solfirm.solicitor_firm_name			SOLICITOR_FIRM_NAME,
		sol_address.address_id 				SOL_ADDRESS_ID,
		sol_address.address_1  				SOL_ADDRESS_1,
		sol_address.address_2  				SOL_ADDRESS_2,
		sol_address.address_3  				SOL_ADDRESS_3,
		sol_address.address_4  				SOL_ADDRESS_4,
		sol_address.town  				SOL_TOWN,
		sol_address.county  				SOL_COUNTY,
		sol_address.country  				SOL_COUNTRY,
		sol_address.postcode 				SOL_POSTCODE
             FROM
		XHB_HEARING_LIST             HEARING_LIST,
		XHB_SITTING                  SITTING,
		XHB_COURT_ROOM               COURT_ROOM,
		XHB_COURT_SITE				 COURT_SITE,
		XHB_SCHEDULED_HEARING        SCHEDULED_HEARING,
		XHB_HEARING                  HEARING,
		XHB_REF_HEARING_TYPE         REF_HEARING_TYPE,
		XHB_SCHED_HEARING_ATTENDEE   SH_ATTENDEE,
		XHB_SH_STAFF                 SH_STAFF,
		XHB_SCHED_HEARING_DEFENDANT  SCHED_HEARING_DEFENDANT,
		XHB_DEFENDANT_ON_CASE        DEFENDANT_ON_CASE,
		XHB_DEFENDANT                DEFENDANT,
		XHB_CASE                     XCASE,
		XHB_SH_LEG_REP               SH_LEG_REP,
		XHB_REF_LEGAL_REPRESENTATIVE LEGAL_REP,
		XHB_REF_ADVOCATE             ADVOCATE,
		XHB_REF_CHAMBER              CHAMBER,
		XHB_REF_SOLICITOR            SOLICITOR,
		XHB_REF_SOLICITOR_FIRM       SOLFIRM,
		XHB_ADDRESS                  ADV_ADDRESS,
		XHB_ADDRESS                  SOL_ADDRESS
             WHERE
		( hearing_list.list_id = sitting.list_id ) AND
		( sitting.court_room_id = court_room.court_room_id ) AND
		( court_room.court_site_id = court_site.court_site_id ) AND
		( scheduled_hearing.sitting_id = sitting.sitting_id ) AND
		( scheduled_hearing.scheduled_hearing_id = sched_hearing_defendant.scheduled_hearing_id(+) ) AND
		( scheduled_hearing.hearing_id = hearing.hearing_id ) AND
		( scheduled_hearing.scheduled_hearing_id = sh_attendee.scheduled_hearing_id(+) ) AND
		( sh_attendee.sh_staff_id = sh_staff.sh_staff_id(+) ) AND
		( hearing.case_id = xcase.case_id ) AND
		( hearing.ref_hearing_type_id = ref_hearing_type.ref_hearing_type_id ) AND
		( sched_hearing_defendant.defendant_on_case_id = defendant_on_case.defendant_on_case_id(+) ) AND
		( defendant_on_case.defendant_id = defendant.defendant_id(+) ) AND
		( sched_hearing_defendant.sched_hear_def_id = sh_leg_rep.sched_hear_def_id(+)) AND
		( sh_leg_rep.ref_legal_rep_id = legal_rep.ref_legal_rep_id(+) ) AND
		( legal_rep.ref_legal_rep_id = advocate.ref_legal_rep_id(+) ) AND
		( advocate.ref_chamber_id = chamber.ref_chamber_id(+) ) AND
		( chamber.address_id = adv_address.address_id(+) ) AND
		( legal_rep.ref_legal_rep_id = solicitor.ref_legal_rep_id(+) ) AND
		( solicitor.ref_solicitor_firm_id = solfirm.ref_solicitor_firm_id(+) ) AND
		( solfirm.address_id = sol_address.address_id(+) );


/*
 * Changes to AUDIT tables (AUD_) as a result of any XHB_ table modifications
 *
 * The standard procedure is as follows:
 *
 *     1. Drop the audit table (AUD_)
 *     2. Recreate audit table as select * from XHB_ table with no rows
 *     3. Add the INSERT_EVENT column to the end of the audit table
 *
 * Need to create temporary table in a process on the live system:
 *
 *     1. Create a temporary audit table as a copy of the current audit table
 *     2. Drop the original audit table
 *     3. Create new audit table as select * from XHB_ table with no rows
 *     4. Add the INSERT_EVENT column to the end of the audit table
 *     5. Insert the data from the temporary audit table into the new audit table
 */


/*
 * Changes, additions or deletion of sequences
 */


/*
 * Changes to XHB_ table triggers as a result of any XHB_ table modifications
 *
 * Note that these are generally the BUR (update and delete) triggers as the BIR
 * (insert) triggers will only change on renaming the auditing columns within the
 * XHB_ table.  However, always a good idea to recompile the BIR trigger.
 */


/*
 * Changes, additions or deletion of packages/procedures/functions
 */

CREATE OR REPLACE PACKAGE BODY xhb_view_schedule_pkg AS
	   PROCEDURE get_schedule(results_out      OUT SYS_REFCURSOR,
                              court_id_in      IN  XHB_HEARING_LIST.court_id%TYPE,
							  start_date_in    IN  XHB_HEARING_LIST.start_date%TYPE,
							  court_room_id_in IN  XHB_SITTING.court_room_id%TYPE) AS
       BEGIN
	   		-- would we want to validate the passed in parameters?
			-- court_id_in and start_date_in to be not null?

	        OPEN results_out FOR
				SELECT DISTINCT
					HEARING_LIST.START_DATE,
				      SITTING.SITTING_SEQUENCE_NO, SITTING.IS_FLOATING,
				      COURT_ROOM.COURT_ROOM_ID, COURT_ROOM.COURT_ROOM_NAME, COURT_ROOM.DESCRIPTION, COURT_ROOM.CREST_COURT_ROOM_NO, COURT_ROOM.COURT_SITE_ID, COURT_ROOM.VERSION AS COURT_ROOM_VERSION, COURT_ROOM.DISPLAY_NAME,
				      SCHEDULED_HEARING.SCHEDULED_HEARING_ID, SCHEDULED_HEARING.SEQUENCE_NO, SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME, SCHEDULED_HEARING.LISTING_NOTE, SCHEDULED_HEARING.HEARING_PROGRESS, SCHEDULED_HEARING.SITTING_ID, SCHEDULED_HEARING.HEARING_ID, SCHEDULED_HEARING.MOVED_FROM, SCHEDULED_HEARING.VERSION AS SCHEDULED_HEARING_VERSION, SCHEDULED_HEARING.LINKED_SH_ID, SCHEDULED_HEARING.END_TIME, SCHEDULED_HEARING.START_TIME, SCHEDULED_HEARING.DATE_OF_HEARING, SCHEDULED_HEARING.IS_CASE_ACTIVE,
				      CASE.CASE_ID, CASE.CASE_NUMBER, CASE.CASE_TYPE, CASE.MAG_CONVICTION_DATE, CASE.CASE_SUB_TYPE, CASE.CASE_TITLE, CASE.CASE_DESCRIPTION, CASE.LINKED_CASE_ID, CASE.BAIL_MAG_CODE, CASE.REF_COURT_ID, CASE.COURT_ID, CASE.CHARGE_IMPORT_INDICATOR, CASE.SEVERED_IND, CASE.INDICT_RESP, CASE.DATE_IND_REC, CASE.PROS_AGENCY_REFERENCE, CASE.VERSION AS CASE_VERSION, CASE.CASE_CLASS, CASE.JUDGE_REASON_FOR_APPEAL, CASE.RESULTS_VERIFIED, CASE.LENGTH_TAPE, CASE.NO_PAGE_PROS_EVIDENCE, CASE.NO_PROS_WITNESS, CASE.EST_PDH_TRIAL_LENGTH, CASE.INDICTMENT_INFO_1, CASE.INDICTMENT_INFO_2, CASE.INDICTMENT_INFO_3, CASE.INDICTMENT_INFO_4, CASE.INDICTMENT_INFO_5, CASE.INDICTMENT_INFO_6, CASE.POLICE_OFFICER_ATTENDING, CASE.CPS_CASE_WORKER, CASE.EXPORT_CHARGES, CASE.IND_CHANGE_STATUS,
				      REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
				      DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID, DEFENDANT_ON_CASE.FINAL_DRIVING_LICENCE_STATUS, DEFENDANT_ON_CASE.PTIURN, DEFENDANT_ON_CASE.IS_JUVENILE, DEFENDANT_ON_CASE.IS_MASKED, DEFENDANT_ON_CASE.MASKED_NAME, DEFENDANT_ON_CASE.CASE_ID, DEFENDANT_ON_CASE.DEFENDANT_ID, DEFENDANT_ON_CASE.VERSION AS DEFENDANT_ON_CASE_VERSION, DEFENDANT_ON_CASE.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, DEFENDANT_ON_CASE.RESULTS_VERIFIED, DEFENDANT_ON_CASE.DEFENDANT_NUMBER, DEFENDANT_ON_CASE.DATE_OF_COMMITTAL, DEFENDANT_ON_CASE.NO_OF_TICS,
				      DEFENDANT.CREST_DEFENDANT_ID, DEFENDANT.FIRST_NAME, DEFENDANT.MIDDLE_NAME, DEFENDANT.SURNAME, DEFENDANT.INITIALS, DEFENDANT.DATE_OF_BIRTH, DEFENDANT.GENDER, DEFENDANT.LAST_CONVICTION_DATE, DEFENDANT.IS_COMPANY, DEFENDANT.VERSION AS DEFENDANT_ON_VERSION, DEFENDANT.ADDRESS_ID, DEFENDANT.COURT_ID,
				      REF_JUDGE.TITLE JUDGE_TITLE, REF_JUDGE.FIRST_NAME JUDGE_FIRST_NAME, REF_JUDGE.MIDDLE_NAME JUDGE_MIDDLE_NAME, REF_JUDGE.SURNAME JUDGE_SURNAME, REF_JUDGE.REF_JUDGE_ID JUDGE_ID, REF_JUDGE.FULL_LIST_TITLE1 JUDGE_FULL_TITLE1,
					  COURT_SITE.COURT_SITE_CODE, COURT_SITE.SHORT_NAME
				FROM  XHB_HEARING_LIST HEARING_LIST,
				      XHB_SITTING SITTING,
				      XHB_COURT_ROOM COURT_ROOM,
					  XHB_COURT_SITE COURT_SITE,
				      XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				      XHB_HEARING HEARING,
				      XHB_CASE CASE,
				      XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				      XHB_DEFENDANT DEFENDANT,
				      XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				      XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				      XHB_REF_JUDGE REF_JUDGE
				WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
				AND	  SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
				AND	  SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
				AND   SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
				AND   SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
				AND   HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
				AND	  HEARING.CASE_ID = CASE.CASE_ID
				AND   SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND   SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND   DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND   XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND   HEARING_LIST.COURT_ID = court_id_in
				AND   HEARING_LIST.START_DATE = start_date_in
				AND   ((court_room_id_in IS NULL) OR (SITTING.COURT_ROOM_ID = court_room_id_in))
				--ORDER BY SCHEDULED_HEARING.SCHEDULED_HEARING_ID;
				ORDER BY court_site_code,
					  	 is_floating,
						 crest_court_room_no,
				   	  	 sitting_sequence_no,
						 NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time),
						 SCHEDULED_HEARING.SEQUENCE_NO;
       END get_schedule;


	   PROCEDURE get_daily_list(results_out      OUT SYS_REFCURSOR,
                                court_id_in      IN  XHB_HEARING_LIST.court_id%TYPE,
							    start_date_in    IN  XHB_HEARING_LIST.start_date%TYPE) AS
       BEGIN
	   		OPEN results_out FOR
				SELECT DISTINCT
					  'Daily List' DOCUMENT_NAME, SYSDATE UNIQUEID, 'Criminal' LISTCATEGORY,
					  HEARING_LIST.LIST_ID, NVL(HEARING_LIST.LIST_TYPE,'Unspecified List TYPE') DOCUMENTTYPE, HEARING_LIST.START_DATE LIST_START_DATE, HEARING_LIST.END_DATE LIST_END_DATE, LTRIM(NVL(HEARING_LIST.STATUS,'Unspecified Status') || ' ' || NVL(HEARING_LIST.EDITION_NO,-1)) LIST_VERSION, NVL(HEARING_LIST.PRINT_REFERENCE,'Unspecified Print Reference') LIST_PRINT_REF, NVL(HEARING_LIST.PUBLISHED_TIME,'01/JAN/1900') LIST_PUBLISHED, HEARING_LIST.CREST_LIST_ID LIST_CREST_LIST_ID,
					  COURTHOUSE.COURT_ID COURTHOUSE_COURT_ID, COURTHOUSE.COURT_PREFIX COURTHOUSE_TYPE, COURTHOUSE.COURT_CODE COURTHOUSE_CODE, COURTHOUSE.COURT_NAME COURTHOUSE_NAME,
					  COURTHOUSE_ADDRESS.ADDRESS_ID COURTHOUSE_ADDRESS_ID, COURTHOUSE_ADDRESS.ADDRESS_1 COURTHOUSE_ADDRESS_1, COURTHOUSE_ADDRESS.ADDRESS_2 COURTHOUSE_ADDRESS_2, COURTHOUSE_ADDRESS.ADDRESS_3 COURTHOUSE_ADDRESS_3, COURTHOUSE_ADDRESS.ADDRESS_4 COURTHOUSE_ADDRESS_4, COURTHOUSE_ADDRESS.TOWN COURTHOUSE_TOWN, COURTHOUSE_ADDRESS.COUNTY COURTHOUSE_COUNTY, COURTHOUSE_ADDRESS.POSTCODE COURTHOUSE_POSTCODE,
					  COURTSITE.COURT_SITE_ID, COURTSITE.COURT_ID COURTSITE_COURT_ID, COURTSITE.COURT_SITE_CODE COURTSITE_CODE, COURTSITE.COURT_SITE_NAME COURTSITE_NAME, COURTSITE.SHORT_NAME,
					  COURTSITE_ADDRESS.ADDRESS_ID COURTSITE_ADDRESS_ID, COURTSITE_ADDRESS.ADDRESS_1 COURTSITE_ADDRESS_1, COURTSITE_ADDRESS.ADDRESS_2 COURTSITE_ADDRESS_2, COURTSITE_ADDRESS.ADDRESS_3 COURTSITE_ADDRESS_3, COURTSITE_ADDRESS.ADDRESS_4 COURTSITE_ADDRESS_4, COURTSITE_ADDRESS.TOWN COURTSITE_TOWN, COURTSITE_ADDRESS.COUNTY COURTSITE_COUNTY, COURTSITE_ADDRESS.POSTCODE COURTSITE_POSTCODE,
					  COURT_ROOM.COURT_ROOM_ID, COURT_ROOM.COURT_ROOM_NAME, COURT_ROOM.DESCRIPTION, COURT_ROOM.CREST_COURT_ROOM_NO, COURT_ROOM.COURT_SITE_ID, COURT_ROOM.VERSION AS COURT_ROOM_VERSION, COURT_ROOM.DISPLAY_NAME,
					  SITTING.SITTING_ID, SITTING.SITTING_SEQUENCE_NO, SITTING.IS_FLOATING, SITTING.SITTING_NOTE, SITTING.SITTING_TIME,
					  REF_JUDGE.REF_JUDGE_ID JUDGE_ID, REF_JUDGE.TITLE JUDGE_TITLE, REF_JUDGE.FIRST_NAME JUDGE_FIRST_NAME, REF_JUDGE.MIDDLE_NAME JUDGE_MIDDLE_NAME, NVL(REF_JUDGE.SURNAME,' ') JUDGE_SURNAME, REF_JUDGE.FULL_LIST_TITLE1 JUDGE_FULL_TITLE1,
					  REF_JUSTICE1.REF_JUSTICE_ID JUSTICE1_ID, DECODE(REF_JUSTICE1.REF_JUSTICE_ID, NULL, '', REF_JUSTICE1.TITLE) JUSTICE1_TITLE, DECODE(REF_JUSTICE1.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME1, REF_JUSTICE1.JUSTICE_NAME) JUSTICE1_NAME,
					  REF_JUSTICE2.REF_JUSTICE_ID JUSTICE2_ID, DECODE(REF_JUSTICE2.REF_JUSTICE_ID, NULL, '', REF_JUSTICE2.TITLE) JUSTICE2_TITLE, DECODE(REF_JUSTICE2.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME2, REF_JUSTICE2.JUSTICE_NAME) JUSTICE2_NAME,
					  REF_JUSTICE3.REF_JUSTICE_ID JUSTICE3_ID, DECODE(REF_JUSTICE3.REF_JUSTICE_ID, NULL, '', REF_JUSTICE3.TITLE) JUSTICE3_TITLE, DECODE(REF_JUSTICE3.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME3, REF_JUSTICE3.JUSTICE_NAME) JUSTICE3_NAME,
					  REF_JUSTICE4.REF_JUSTICE_ID JUSTICE4_ID, DECODE(REF_JUSTICE4.REF_JUSTICE_ID, NULL, '', REF_JUSTICE4.TITLE) JUSTICE4_TITLE, DECODE(REF_JUSTICE4.REF_JUSTICE_ID, NULL, SITTING.JUSTICENAME4, REF_JUSTICE4.JUSTICE_NAME) JUSTICE4_NAME,
					  SCHEDULED_HEARING.SCHEDULED_HEARING_ID, SCHEDULED_HEARING.SEQUENCE_NO, SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME, SCHEDULED_HEARING.LISTING_NOTE, SCHEDULED_HEARING.HEARING_PROGRESS, SCHEDULED_HEARING.SITTING_ID, SCHEDULED_HEARING.HEARING_ID, SCHEDULED_HEARING.MOVED_FROM, SCHEDULED_HEARING.VERSION AS SCHEDULED_HEARING_VERSION, SCHEDULED_HEARING.LINKED_SH_ID, SCHEDULED_HEARING.END_TIME, SCHEDULED_HEARING.START_TIME, SCHEDULED_HEARING.DATE_OF_HEARING, SCHEDULED_HEARING.IS_CASE_ACTIVE,
					  REF_HEARING_TYPE.REF_HEARING_TYPE_ID, REF_HEARING_TYPE.HEARING_TYPE_CODE, REF_HEARING_TYPE.HEARING_TYPE_DESC, REF_HEARING_TYPE.CATEGORY, REF_HEARING_TYPE.SEQ_NO, REF_HEARING_TYPE.LIST_SEQUENCE, REF_HEARING_TYPE.VERSION AS REF_HEARING_TYPE_VERSION, REF_HEARING_TYPE.COURT_ID, REF_HEARING_TYPE.OBS_IND AS REF_HEARING_TYPE_OBS_IND,
					  CASE.CASE_ID, CASE.CASE_NUMBER, CASE.CASE_TYPE, CASE.MAG_CONVICTION_DATE, CASE.CASE_SUB_TYPE, CASE.CASE_TITLE, CASE.CASE_DESCRIPTION, CASE.LINKED_CASE_ID, CASE.BAIL_MAG_CODE, CASE.REF_COURT_ID, CASE.COURT_ID, CASE.CHARGE_IMPORT_INDICATOR, CASE.SEVERED_IND, CASE.INDICT_RESP, CASE.DATE_IND_REC, CASE.PROS_AGENCY_REFERENCE, CASE.VERSION AS CASE_VERSION, CASE.CASE_CLASS, CASE.JUDGE_REASON_FOR_APPEAL, CASE.RESULTS_VERIFIED, CASE.LENGTH_TAPE, CASE.NO_PAGE_PROS_EVIDENCE, CASE.NO_PROS_WITNESS, CASE.EST_PDH_TRIAL_LENGTH, CASE.INDICTMENT_INFO_1, CASE.INDICTMENT_INFO_2, CASE.INDICTMENT_INFO_3, CASE.INDICTMENT_INFO_4, CASE.INDICTMENT_INFO_5, CASE.INDICTMENT_INFO_6, CASE.POLICE_OFFICER_ATTENDING, CASE.CPS_CASE_WORKER, CASE.EXPORT_CHARGES, CASE.IND_CHANGE_STATUS,
					  REF_COURT.REF_COURT_ID, REF_COURT.COURT_TYPE, REF_COURT.CREST_CODE, REF_COURT.COURT_SHORT_NAME, REF_COURT.COURT_FULL_NAME,
					  DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID, DEFENDANT_ON_CASE.FINAL_DRIVING_LICENCE_STATUS, DEFENDANT_ON_CASE.PTIURN, DEFENDANT_ON_CASE.IS_JUVENILE, DEFENDANT_ON_CASE.IS_MASKED, DEFENDANT_ON_CASE.MASKED_NAME, DEFENDANT_ON_CASE.CASE_ID, DEFENDANT_ON_CASE.DEFENDANT_ID, DEFENDANT_ON_CASE.VERSION AS DEFENDANT_ON_CASE_VERSION, DEFENDANT_ON_CASE.OBS_IND AS DEFENDANT_ON_CASE_OBS_IND, DEFENDANT_ON_CASE.RESULTS_VERIFIED, DEFENDANT_ON_CASE.DEFENDANT_NUMBER, DEFENDANT_ON_CASE.DATE_OF_COMMITTAL, DEFENDANT_ON_CASE.NO_OF_TICS,
					  DEFENDANT.CREST_DEFENDANT_ID, DEFENDANT.FIRST_NAME, DEFENDANT.MIDDLE_NAME, NVL(DEFENDANT.SURNAME,' ') SURNAME, DEFENDANT.INITIALS, DEFENDANT.DATE_OF_BIRTH, DEFENDANT.GENDER, DEFENDANT.LAST_CONVICTION_DATE, DEFENDANT.IS_COMPANY, DEFENDANT.VERSION AS DEFENDANT_ON_VERSION, DEFENDANT.ADDRESS_ID, DEFENDANT.COURT_ID, HEARING_LIST.START_DATE
				FROM  XHB_HEARING_LIST HEARING_LIST,
  					  XHB_SITTING SITTING,
  					  XHB_COURT_ROOM COURT_ROOM,
  					  XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
  					  XHB_HEARING HEARING,
  					  XHB_CASE CASE,
  					  XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
  					  XHB_DEFENDANT DEFENDANT,
  					  XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
  					  XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
  					  XHB_REF_JUDGE REF_JUDGE,
  					  XHB_REF_JUSTICE REF_JUSTICE1,
  					  XHB_REF_JUSTICE REF_JUSTICE2,
  					  XHB_REF_JUSTICE REF_JUSTICE3,
  					  XHB_REF_JUSTICE REF_JUSTICE4,
  					  XHB_REF_COURT REF_COURT,
  					  XHB_COURT_SITE COURTSITE,
  					  XHB_COURT COURTHOUSE,
  					  XHB_ADDRESS COURTSITE_ADDRESS,
  					  XHB_ADDRESS COURTHOUSE_ADDRESS
				WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
				AND	  SITTING.COURT_ROOM_ID(+) = COURT_ROOM.COURT_ROOM_ID
				AND	  SCHEDULED_HEARING.SITTING_ID(+) = SITTING.SITTING_ID
				AND	  SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID(+)
				AND	  HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID(+)
				AND	  HEARING.CASE_ID = CASE.CASE_ID(+)
				AND	  SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND	  SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND	  DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND	  XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND	  SITTING.REF_JUSTICE1_ID = REF_JUSTICE1.REF_JUSTICE_ID(+)
				AND	  SITTING.REF_JUSTICE2_ID = REF_JUSTICE2.REF_JUSTICE_ID(+)
				AND	  SITTING.REF_JUSTICE3_ID = REF_JUSTICE3.REF_JUSTICE_ID(+)
				AND	  SITTING.REF_JUSTICE4_ID = REF_JUSTICE4.REF_JUSTICE_ID(+)
				AND	  CASE.REF_COURT_ID = REF_COURT.REF_COURT_ID(+)
				AND	  COURT_ROOM.COURT_SITE_ID = COURTSITE.COURT_SITE_ID
				AND	  COURTSITE.ADDRESS_ID = COURTSITE_ADDRESS.ADDRESS_ID(+)
				AND	  HEARING_LIST.COURT_ID = COURTHOUSE.COURT_ID
				AND	  COURTHOUSE.ADDRESS_ID = COURTHOUSE_ADDRESS.ADDRESS_ID(+)
				AND	  HEARING_LIST.COURT_ID = court_id_in
				AND	  HEARING_LIST.START_DATE = start_date_in
--				ORDER BY COURTSITE.COURT_SITE_CODE,
--  					  	 SITTING.IS_FLOATING,
--  						 COURT_ROOM.CREST_COURT_ROOM_NO,
--  						 SITTING.SITTING_SEQUENCE_NO,
--  						 SCHEDULED_HEARING.SEQUENCE_NO;
				ORDER BY court_site_code,
					  	 is_floating,
						 crest_court_room_no,
				   	  	 sitting_sequence_no,
						 NVL(scheduled_hearing.not_before_time, scheduled_hearing.original_time),
						 SCHEDULED_HEARING.SEQUENCE_NO;
	   END get_daily_list;
END xhb_view_schedule_pkg;
/
show errors

CREATE OR REPLACE PACKAGE BODY XHB_PUBLIC_DISPLAY_PKG AS
	-- function used to convert a String of comma-delimited numbers into
	-- an array, declared deterministic as it is probable that the passed
	-- in values will be similar/same each call
    FUNCTION convert_string(p_str_in IN VARCHAR2) RETURN xhb_number_table_typ DETERMINISTIC
	AS
		l_size             CONSTANT NUMBER := LENGTH(p_str_in) + 1;
		l_min_index        NUMBER := 1;
		l_max_index        NUMBER;
        l_array            xhb_number_table_typ := xhb_number_table_typ();
	BEGIN
		-- If the passed in parameter is null, then there are no values!
		IF (p_str_in IS NOT NULL) THEN
			LOOP
				l_max_index := INSTR(p_str_in, ',', l_min_index);
				-- l_max_index will be 0 if there are no further occurences, but we need to get
				-- the remaining characters for the last entry
				IF l_max_index = 0 THEN
					l_max_index := l_size;
				END IF;

				l_array.EXTEND;
				l_array(l_array.last) := TO_NUMBER(trim(SUBSTR(p_str_in, l_min_index, (l_max_index - l_min_index))));

				EXIT WHEN l_max_index = l_size;
				l_min_index := l_max_index + 1;
			END LOOP;
		END IF;
       
		RETURN l_array;
	END convert_string;

        -- This stored procedure is used to get the summary by name data
	PROCEDURE GET_SUMMARY_BY_NAME (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT
				SITTING.IS_FLOATING AS IS_FLOATING,
				COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME, 
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
			AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
			AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID
			AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID
			AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID
			AND HEARING_LIST.COURT_ID = COURT_ID_IN
			AND HEARING_LIST.START_DATE = START_DATE_IN	
			AND SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
			AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
			AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)
			AND SITTING.IS_FLOATING='0'
			AND DEFENDANT_ON_CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
			ORDER BY
				DEFENDANT_SURNAME,
				DEFENDANT_FIRST_NAME, 
				DEFENDANT_MIDDLE_NAME;

	END GET_SUMMARY_BY_NAME;

        -- This stored procedure is used to get the summary by name data
	PROCEDURE GET_SUMMARY_BY_NAME_U (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT
				SITTING.IS_FLOATING AS IS_FLOATING,
				COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME, 
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
			AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
			AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID
			AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID
			AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID
			AND HEARING_LIST.COURT_ID = COURT_ID_IN
			AND HEARING_LIST.START_DATE = START_DATE_IN	
			AND SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
			AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
			AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)
			AND DEFENDANT_ON_CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
			ORDER BY
				DEFENDANT_SURNAME,
				DEFENDANT_FIRST_NAME, 
				DEFENDANT_MIDDLE_NAME;
	END GET_SUMMARY_BY_NAME_U;

	-- This stored procedure is used to get the jury current status and daily list WITHOUT unassigned cases
	PROCEDURE GET_JURY_STATUS_DAILY_LIST (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT COURT_SITE.COURT_SITE_CODE AS COURT_SITE_CODE,
				SITTING.IS_FLOATING AS IS_FLOATING,
				COURT_ROOM.CREST_COURT_ROOM_NO AS CREST_COURT_ROOM_NO,
				SITTING.SITTING_SEQUENCE_NO AS SITTING_SEQUENCE_NO,
				NVL(SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME) AS SCHEDULED_HEARING_TIME_SORT,
				SCHEDULED_HEARING.SEQUENCE_NO AS SCHEDULED_HEARING_SEQUENCE_NO,
				COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				TMP_COURT_ROOM.COLUMN_VALUE AS LIST_COURT_ROOM_ID,  -- What court room is currently being listed.
				                                                    -- Used to determine how the case has moved.
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID,
				REF_JUDGE.FULL_LIST_TITLE1 AS FULL_LIST_TITLE1,
				REF_JUDGE.SURNAME AS JUDGE_SURNAME, 
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				REF_HEARING_TYPE.HEARING_TYPE_DESC AS HEARING_DESCRIPTION,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME,
				SCHEDULED_HEARING.HEARING_PROGRESS AS HEARING_PROGRESS,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS,
				SCHEDULED_HEARING.SCHEDULED_HEARING_ID AS SCHEDULED_HEARING_ID
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_REF_JUDGE REF_JUDGE,
				XHB_COURT_SITE COURT_SITE,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                        TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
				AND SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
				AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
				AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
				AND HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
				AND HEARING.CASE_ID = CASE.CASE_ID
				AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
				AND HEARING_LIST.COURT_ID = COURT_ID_IN
				AND HEARING_LIST.START_DATE = START_DATE_IN	
				AND SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
				AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
				AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)	
				AND SITTING.IS_FLOATING = 0
			ORDER BY COURT_SITE_CODE,
				IS_FLOATING,
				COURT_ROOM.CREST_COURT_ROOM_NO,
				SITTING_SEQUENCE_NO,
				NVL(SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME),
				SCHEDULED_HEARING.SEQUENCE_NO;
				
	END GET_JURY_STATUS_DAILY_LIST;

	-- This stored procedure is used to get the jury current status and daily list WITH unassigned cases
	PROCEDURE GET_JURY_STATUS_DAILY_LIST_U (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT COURT_SITE.COURT_SITE_CODE AS COURT_SITE_CODE,
				SITTING.IS_FLOATING AS IS_FLOATING,
				COURT_ROOM.CREST_COURT_ROOM_NO AS CREST_COURT_ROOM_NO,
				SITTING.SITTING_SEQUENCE_NO AS SITTING_SEQUENCE_NO,
				NVL(SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME) AS SCHEDULED_HEARING_TIME_SORT,
				SCHEDULED_HEARING.SEQUENCE_NO AS SCHEDULED_HEARING_SEQUENCE_NO,
				COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				TMP_COURT_ROOM.COLUMN_VALUE AS LIST_COURT_ROOM_ID,  -- What court room is currently being listed.
				                                                    -- Used to determine how the case has moved.
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID,
				REF_JUDGE.FULL_LIST_TITLE1 AS FULL_LIST_TITLE1,
				REF_JUDGE.SURNAME AS JUDGE_SURNAME, 
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				REF_HEARING_TYPE.HEARING_TYPE_DESC AS HEARING_DESCRIPTION,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME,
				SCHEDULED_HEARING.HEARING_PROGRESS AS HEARING_PROGRESS,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_REF_JUDGE REF_JUDGE,
				XHB_COURT_SITE COURT_SITE,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
				AND SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
				AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
				AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
				AND HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
				AND HEARING.CASE_ID = CASE.CASE_ID
				AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
				AND HEARING_LIST.COURT_ID = COURT_ID_IN
				AND HEARING_LIST.START_DATE = START_DATE_IN	
				AND SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
				AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
				AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)	
				AND SITTING.IS_FLOATING = 0
		UNION
			SELECT COURT_SITE.COURT_SITE_CODE AS COURT_SITE_CODE,
				SITTING.IS_FLOATING AS IS_FLOATING,
				COURT_ROOM.CREST_COURT_ROOM_NO AS CREST_COURT_ROOM_NO,
				SITTING.SITTING_SEQUENCE_NO AS SITTING_SEQUENCE_NO,
				NVL(SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME) AS SCHEDULED_HEARING_TIME_SORT,
				SCHEDULED_HEARING.SEQUENCE_NO AS SCHEDULED_HEARING_SEQUENCE_NO, 
				COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				COURT_ROOM.COURT_ROOM_ID AS LIST_COURT_ROOM_ID,  -- What court room is currently being listed.
				                                                    -- Used to determine how the case has moved.
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID,
				REF_JUDGE.FULL_LIST_TITLE1 AS FULL_LIST_TITLE1,
				REF_JUDGE.SURNAME AS JUDGE_SURNAME, 
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				REF_HEARING_TYPE.HEARING_TYPE_DESC AS HEARING_DESCRIPTION,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME,
				SCHEDULED_HEARING.HEARING_PROGRESS AS HEARING_PROGRESS,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_REF_JUDGE REF_JUDGE,
				XHB_COURT_SITE COURT_SITE,
				XHB_CASE_REFERENCE CASE_REFERENCE
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
				AND SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
				AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
				AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
				AND HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
				AND HEARING.CASE_ID = CASE.CASE_ID
				AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
				AND HEARING_LIST.COURT_ID = COURT_ID_IN
				AND HEARING_LIST.START_DATE = START_DATE_IN	
				AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
				AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)	
				AND SITTING.IS_FLOATING = 1
		ORDER BY COURT_SITE_CODE,
			IS_FLOATING,
			CREST_COURT_ROOM_NO,
			SITTING_SEQUENCE_NO,
			SCHEDULED_HEARING_TIME_SORT,
			SCHEDULED_HEARING_SEQUENCE_NO;
				
	END GET_JURY_STATUS_DAILY_LIST_U;

	-- This stored procedure is used to get the court list
	PROCEDURE GET_COURT_LIST (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				MOVED_FROM_COURT_ROOM.DISPLAY_NAME AS MOVED_FROM_COURT_ROOM_NAME, 
				TMP_COURT_ROOM.COLUMN_VALUE AS LIST_COURT_ROOM_ID,  -- What court room is currently being listed.
				                                                    -- Used to determine how the case has moved.
				COURT_ROOM.COURT_ROOM_ID AS COURT_ROOM_ID,
				MOVED_FROM_COURT_ROOM.COURT_ROOM_ID AS MOVED_FROM_COURT_ROOM_ID, 
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				REF_HEARING_TYPE.HEARING_TYPE_DESC AS HEARING_DESCRIPTION,
				SCHEDULED_HEARING.NOT_BEFORE_TIME AS NOT_BEFORE_TIME, 
				SCHEDULED_HEARING.HEARING_PROGRESS AS HEARING_PROGRESS,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_COURT_ROOM MOVED_FROM_COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_REF_JUDGE REF_JUDGE,
				XHB_COURT_SITE COURT_SITE,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                        TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
                	        AND SITTING.IS_FLOATING = '0'
				AND SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
				AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
				AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
				AND HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
				AND HEARING.CASE_ID = CASE.CASE_ID
				AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
				AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
				AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
				AND XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
				AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
				AND HEARING_LIST.COURT_ID = COURT_ID_IN
				AND HEARING_LIST.START_DATE = START_DATE_IN	
				AND (
					SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
                			OR SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
				)
				AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
				AND SCHEDULED_HEARING.MOVED_FROM_COURT_ROOM_ID = MOVED_FROM_COURT_ROOM.COURT_ROOM_ID(+)	
		ORDER BY COURT_SITE_CODE,
				IS_FLOATING,
				COURT_ROOM.CREST_COURT_ROOM_NO,
				SITTING_SEQUENCE_NO,
				NVL(SCHEDULED_HEARING.NOT_BEFORE_TIME, SCHEDULED_HEARING.ORIGINAL_TIME),
				SCHEDULED_HEARING.SEQUENCE_NO;
				
	END GET_COURT_LIST;

	-- This stored procedure is used to get the all court status
	PROCEDURE GET_ALL_COURT_STATUS (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_IDS_IN	IN	VARCHAR2) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME, 
				COURT_ROOM.CREST_COURT_ROOM_NO AS CREST_COURT_ROOM_NO,
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				CR_LIVE_STATUS.PUBLIC_DISPLAY_STATUS AS PUBLIC_DISPLAY_STATUS,
				CR_LIVE_STATUS.TIME_STATUS_SET AS TIME_STATUS_SET,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_COURT_SITE COURT_SITE,
				XHB_CR_LIVE_STATUS CR_LIVE_STATUS,
				XHB_CASE_REFERENCE CASE_REFERENCE,
                TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
			AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
			AND SITTING.COURT_SITE_ID = COURT_SITE.COURT_SITE_ID
			AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
			AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
			AND HEARING.CASE_ID = CASE.CASE_ID
			AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
			AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
			AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
			AND CR_LIVE_STATUS.SCHEDULED_HEARING_ID = SCHEDULED_HEARING.SCHEDULED_HEARING_ID(+)
			AND CR_LIVE_STATUS.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID(+)
			AND SCHEDULED_HEARING.IS_CASE_ACTIVE = 'Y'
			AND HEARING_LIST.COURT_ID = COURT_ID_IN
			AND HEARING_LIST.START_DATE = START_DATE_IN
			AND SITTING.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
			AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+)
			UNION
			SELECT COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				COURT_ROOM.CREST_COURT_ROOM_NO AS CREST_COURT_ROOM_NO,
				NULL AS DEFENDANT_ID,
				NULL AS DEFENDANT_FIRST_NAME,
				NULL AS DEFENDANT_MIDDLE_NAME,
				NULL AS DEFENDANT_SURNAME,
				NULL AS CASE_NUMBER, 
				NULL AS CASE_TITLE,
				NULL AS PUBLIC_DISPLAY_STATUS, 
				NULL AS TIME_STATUS_SET,
				NULL AS REPORTING_RESTRICTIONS
			FROM XHB_COURT_ROOM COURT_ROOM,
                TABLE(cast(convert_string(COURT_ROOM_IDS_IN) AS xhb_number_table_typ)) TMP_COURT_ROOM
			WHERE COURT_ROOM.COURT_ROOM_ID NOT IN (
				SELECT SITTING.COURT_ROOM_ID 
				FROM XHB_HEARING_LIST HEARING_LIST, 
					XHB_SITTING SITTING, 
					XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
					XHB_CR_LIVE_STATUS CR_LIVE_STATUS
				WHERE 
					HEARING_LIST.LIST_ID = SITTING.LIST_ID
					AND SITTING.SITTING_ID = SCHEDULED_HEARING.SITTING_ID
					AND SCHEDULED_HEARING.IS_CASE_ACTIVE = 'Y'
					AND HEARING_LIST.COURT_ID = COURT_ID_IN
					AND HEARING_LIST.START_DATE = START_DATE_IN
					AND CR_LIVE_STATUS.SCHEDULED_HEARING_ID = SCHEDULED_HEARING.SCHEDULED_HEARING_ID )
            AND COURT_ROOM.COURT_ROOM_ID = TMP_COURT_ROOM.COLUMN_VALUE
			ORDER BY CREST_COURT_ROOM_NO;
				
	END GET_ALL_COURT_STATUS;

	-- This stored procedure is used to get the COURT DETAIL
	PROCEDURE GET_COURT_DETAIL (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ID_IN		IN	XHB_HEARING_LIST.court_id%TYPE,
		START_DATE_IN		IN 	XHB_HEARING_LIST.start_date%TYPE,
		COURT_ROOM_ID_IN	IN	XHB_COURT_ROOM.COURT_ROOM_ID%TYPE) AS
	BEGIN
		
		OPEN RESULTS_OUT FOR
			SELECT COURT_ROOM.DISPLAY_NAME AS COURT_ROOM_NAME,
				REF_JUDGE.FULL_LIST_TITLE1 AS FULL_LIST_TITLE1,
				REF_JUDGE.SURNAME AS JUDGE_SURNAME, 
				DEFENDANT.DEFENDANT_ID AS DEFENDANT_ID,
				DEFENDANT.FIRST_NAME AS DEFENDANT_FIRST_NAME, 
				DEFENDANT.MIDDLE_NAME AS DEFENDANT_MIDDLE_NAME, 
				DEFENDANT.SURNAME AS DEFENDANT_SURNAME,
				CASE.CASE_TYPE || CASE.CASE_NUMBER AS CASE_NUMBER,
				CASE.CASE_TITLE AS CASE_TITLE,
				REF_HEARING_TYPE.HEARING_TYPE_DESC AS HEARING_DESCRIPTION,
				CR_LIVE_STATUS.PUBLIC_DISPLAY_STATUS AS PUBLIC_DISPLAY_STATUS,
				CR_LIVE_STATUS.TIME_STATUS_SET AS TIME_STATUS_SET,
				CASE_REFERENCE.REPORTING_RESTRICTIONS AS REPORTING_RESTRICTIONS
			FROM  XHB_HEARING_LIST HEARING_LIST,
				XHB_SITTING SITTING,
				XHB_COURT_ROOM COURT_ROOM,
				XHB_SCHEDULED_HEARING SCHEDULED_HEARING,
				XHB_HEARING HEARING,
				XHB_CASE CASE,
				XHB_REF_HEARING_TYPE REF_HEARING_TYPE,
				XHB_DEFENDANT DEFENDANT,
				XHB_SCHED_HEARING_DEFENDANT SCHED_HEARING_DEFENDANT,
				XHB_DEFENDANT_ON_CASE DEFENDANT_ON_CASE,
				XHB_REF_JUDGE REF_JUDGE,
				XHB_CR_LIVE_STATUS CR_LIVE_STATUS,
				XHB_CASE_REFERENCE CASE_REFERENCE
			WHERE HEARING_LIST.LIST_ID = SITTING.LIST_ID
			AND SITTING.COURT_ROOM_ID = COURT_ROOM.COURT_ROOM_ID
			AND SCHEDULED_HEARING.SITTING_ID = SITTING.SITTING_ID
			AND SCHEDULED_HEARING.HEARING_ID = HEARING.HEARING_ID
			AND HEARING.REF_HEARING_TYPE_ID = REF_HEARING_TYPE.REF_HEARING_TYPE_ID
			AND HEARING.CASE_ID = CASE.CASE_ID
			AND SCHEDULED_HEARING.SCHEDULED_HEARING_ID = SCHED_HEARING_DEFENDANT.SCHEDULED_HEARING_ID(+)
			AND SCHED_HEARING_DEFENDANT.DEFENDANT_ON_CASE_ID = DEFENDANT_ON_CASE.DEFENDANT_ON_CASE_ID(+)
			AND DEFENDANT_ON_CASE.DEFENDANT_ID = DEFENDANT.DEFENDANT_ID(+)
			AND XHB_CUSTOM_PKG.GET_REF_JUDGE_ID(SCHEDULED_HEARING.SCHEDULED_HEARING_ID) = REF_JUDGE.REF_JUDGE_ID(+)
			AND CR_LIVE_STATUS.SCHEDULED_HEARING_ID(+) = SCHEDULED_HEARING.SCHEDULED_HEARING_ID
			AND SCHEDULED_HEARING.IS_CASE_ACTIVE = 'Y'
			AND HEARING_LIST.COURT_ID = COURT_ID_IN
			AND HEARING_LIST.START_DATE = START_DATE_IN
			AND SITTING.COURT_ROOM_ID = COURT_ROOM_ID_IN
			AND CASE.CASE_ID = CASE_REFERENCE.CASE_ID(+);
				
	END GET_COURT_DETAIL;

	-- This stored procedure is used to get the public notices for a court room
	PROCEDURE GET_PUBLIC_NOTICES (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		COURT_ROOM_ID_IN	IN	XHB_COURT_ROOM.COURT_ROOM_ID%TYPE) AS
	BEGIN
		
		OPEN RESULTS_OUT FOR
			SELECT PUBLIC_NOTICE.PUBLIC_NOTICE_DESC AS PUBLIC_NOTICE_DESC,
				CONFIGURED_PUBLIC_NOTICE.IS_ACTIVE AS IS_ACTIVE,
				DEFINITIVE_PUBLIC_NOTICE.PRIORITY AS PRIORITY
			FROM XHB_PUBLIC_NOTICE PUBLIC_NOTICE,
				XHB_CONFIGURED_PUBLIC_NOTICE CONFIGURED_PUBLIC_NOTICE,
				XHB_DEFINITIVE_PUBLIC_NOTICE DEFINITIVE_PUBLIC_NOTICE
			WHERE PUBLIC_NOTICE.PUBLIC_NOTICE_ID = CONFIGURED_PUBLIC_NOTICE.PUBLIC_NOTICE_ID
			AND DEFINITIVE_PUBLIC_NOTICE.DEFINITIVE_PN_ID = PUBLIC_NOTICE.DEFINITIVE_PN_ID
			AND CONFIGURED_PUBLIC_NOTICE.IS_ACTIVE = 1
			AND CONFIGURED_PUBLIC_NOTICE.COURT_ROOM_ID = COURT_ROOM_ID_IN
			AND ROWNUM <= 5
            ORDER BY DEFINITIVE_PUBLIC_NOTICE.PRIORITY;
	END GET_PUBLIC_NOTICES;

	-- This stored procedure is to get all active cases in a court room except for the 
	-- one passed in. Used to identify active cases to turn off
	PROCEDURE GET_ACTIVE_CASES_IN_ROOM (
		RESULTS_OUT		OUT	SYS_REFCURSOR,
		LIST_ID_IN		IN	XHB_HEARING_LIST.LIST_ID%TYPE,
		COURT_ROOM_ID_IN	IN	XHB_COURT_ROOM.COURT_ROOM_ID%TYPE,
		SCHEDULED_HEARING_ID_IN	IN	XHB_SCHEDULED_HEARING.SCHEDULED_HEARING_ID%TYPE) AS
	BEGIN
		OPEN RESULTS_OUT FOR
			SELECT	SH.SCHEDULED_HEARING_ID AS SCHEDULED_HEARING_ID
			FROM	XHB_SCHEDULED_HEARING SH, XHB_SITTING S
			WHERE	SH.IS_CASE_ACTIVE='Y'
			AND	S.SITTING_ID = SH.SITTING_ID
			AND	S.LIST_ID = LIST_ID_IN 
			AND	S.COURT_ROOM_ID = COURT_ROOM_ID_IN
			AND	SH.SCHEDULED_HEARING_ID != SCHEDULED_HEARING_ID_IN;
	END GET_ACTIVE_CASES_IN_ROOM;

END XHB_PUBLIC_DISPLAY_PKG;
/
show errors


/*
 * Changes, additions or deletion of standing data
 */

UPDATE xhb_court SET internet_court_name = 'Snaresbrook' WHERE court_id = 1;


/*
 * Updating of table XHB_VERSION
 */

UPDATE XHB_VERSION SET schema_version = '6.1.1', last_update_date = SYSDATE, updated_by = 'RELEASE' WHERE SCHEMA_NAME = 'XHIBIT';
UPDATE XHB_VERSION SET schema_version = '6.1.1', last_update_date = SYSDATE, updated_by = 'RELEASE' WHERE SCHEMA_NAME = 'JAVA';
UPDATE XHB_VERSION SET schema_version = '6.1.1', last_update_date = SYSDATE, updated_by = 'RELEASE' WHERE SCHEMA_NAME = 'MERCATOR';

COMMIT;
