/*
 * Filename:    DB_Patch_7_4_5_5_Prod.sql
 *
 * System:      Pre-Production & Production
 *
 *
 * Date:        29th April 2005
 */


/*
 * Updating of table XHB_VERSION
 */


DELETE FROM XHB_VERSION WHERE SCHEMA_NAME = 'XHIBIT';

DELETE FROM XHB_VERSION WHERE SCHEMA_NAME = 'JAVASERVER';

DELETE FROM XHB_VERSION WHERE SCHEMA_NAME = 'MERCATOR';

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'XHIBIT', '7.4.5.5', sysdate, 'RELEASE', 'Database', 3); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'JAVASERVER', '7.4.5.5', sysdate, 'RELEASE', 'Java Server Component', 2); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'MERCATOR', '7.4.5.5', sysdate, 'RELEASE', 'Mercator', 4); 

COMMIT;

/