create or replace trigger XHB_JOINDER_IMP_EXP
  AFTER UPDATE ON XHB_JOINDER_XML
  FOR EACH ROW

DECLARE

  l_defCaseId NUMBER(8) := NULL;
  l_caseId NUMBER(8) := NULL;
  l_courtId NUMBER(8) := NULL;
  
BEGIN


  IF (:NEW.STATUS = 'R') THEN

    SELECT CASE_ID
    INTO   l_caseId
    FROM  XHB_DEFENDANT_ON_CASE DC,
          XHB_JOINDER_DEFENDANT_ON_CASE JD
    WHERE JD.JOINDER_ID = :NEW.JOINDER_ID 
    AND   DC.DEFENDANT_ON_CASE_ID = JD.DEFENDANT_ON_CASE_ID_1;

    SELECT COURT_ID
    INTO   l_courtId 
    FROM   XHB_CASE C,
           XHB_DEFENDANT_ON_CASE DC,
           XHB_JOINDER_DEFENDANT_ON_CASE JD
    WHERE  JD.JOINDER_ID = :NEW.JOINDER_ID
    AND    DC.DEFENDANT_ON_CASE_ID = JD.DEFENDANT_ON_CASE_ID_1
    AND    DC.CASE_ID = C.CASE_ID;

    INSERT INTO XHB_IMPORT_EXPORT_STATUS(TYPE_CODE, STATUS_CODE, CASE_ID, COURT_ID)
    VALUES ('CI','R', l_caseId, l_courtId);
  END IF;

END;
/

create or replace trigger XHB_SKELETON_IMP_EXP
  AFTER UPDATE ON XHB_SKELETON_SCHEDULE
  FOR EACH ROW

DECLARE  
  l_courtId NUMBER(8) := NULL;
  l_codeid  NUMBER(8) := NULL;

BEGIN
/*  SELECT skeleton_delivery_status_id INTO l_codeid FROM XHB_SKELETON_DELIVERY_STATUS
   WHERE CODE = 'READY';
*/  
  IF (:NEW.skeleton_delivery_status_id = 2) THEN

    SELECT COURT_ID
    INTO   l_courtId
    FROM   XHB_CASE C
    WHERE  C.CASE_ID = :NEW.CASE_ID;

    INSERT INTO XHB_IMPORT_EXPORT_STATUS(TYPE_CODE, STATUS_CODE, CASE_ID, COURT_ID)
    VALUES ('SS','R', :OLD.CASE_ID, l_courtId);
  END IF;

END;
/

create or replace trigger XHB_ORDER_IMP_EXP
  AFTER UPDATE ON XHB_ORDER
  FOR EACH ROW

DECLARE
 
  l_orderType VARCHAR2(5) := NULL;
  l_caseId NUMBER(8) := NULL;
  l_courtId NUMBER(8) := NULL;
  
BEGIN

  IF (:NEW.ORDER_DELIVERY_STATUS_ID = 2) THEN

    SELECT OTYPE.CODE
    INTO   l_orderType
    FROM   XHB_ORDER_TYPE OTYPE,
           XHB_ORDER_TEMPLATE OTEMP
    WHERE  :NEW.ORDER_TEMPLATE_ID = OTEMP.ORDER_TEMPLATE_ID
    AND    OTEMP.ORDER_TYPE_ID = OTYPE.ORDER_TYPE_ID;    

    SELECT CASE_ID
    INTO   l_caseId
    FROM   XHB_DEFENDANT_ON_CASE DC
    WHERE  DC.DEFENDANT_ON_CASE_ID = :NEW.DEFENDANT_ON_CASE_ID;

    SELECT COURT_ID
    INTO   l_courtId
    FROM   XHB_CASE C,
           XHB_DEFENDANT_ON_CASE DC
    WHERE  DC.DEFENDANT_ON_CASE_ID = :NEW.DEFENDANT_ON_CASE_ID
    AND    DC.CASE_ID = C.CASE_ID;

    INSERT INTO XHB_IMPORT_EXPORT_STATUS(TYPE_CODE, STATUS_CODE, CASE_ID, COURT_ID, DEFENDANT_ON_CASE_ID)
    VALUES (l_orderType,'R', l_caseId, l_courtId, :OLD.DEFENDANT_ON_CASE_ID);

  END IF;

END;
/
