create or replace trigger XHB_JOINDER_IMP_EXP
  AFTER UPDATE ON XHB_JOINDER_XML
  FOR EACH ROW

DECLARE

  l_defCaseId NUMBER(8) := NULL;
  l_caseId NUMBER(8) := NULL;
  l_courtId NUMBER(8) := NULL;
  
BEGIN


  IF (:NEW.STATUS = 'R') THEN

    SELECT CASE_ID
    INTO   l_caseId
    FROM  XHB_DEFENDANT_ON_CASE DC,
          XHB_JOINDER_DEFENDANT_ON_CASE JD
    WHERE JD.JOINDER_ID = :NEW.JOINDER_ID 
    AND   DC.DEFENDANT_ON_CASE_ID = JD.DEFENDANT_ON_CASE_ID_1;

    SELECT COURT_ID
    INTO   l_courtId 
    FROM   XHB_CASE C,
           XHB_DEFENDANT_ON_CASE DC,
           XHB_JOINDER_DEFENDANT_ON_CASE JD
    WHERE  JD.JOINDER_ID = :NEW.JOINDER_ID
    AND    DC.DEFENDANT_ON_CASE_ID = JD.DEFENDANT_ON_CASE_ID_1
    AND    DC.CASE_ID = C.CASE_ID;

    INSERT INTO XHB_IMPORT_EXPORT_STATUS(TYPE_CODE, STATUS_CODE, CASE_ID, COURT_ID)
    VALUES ('CI','R', l_caseId, l_courtId);
  END IF;

END;
/
