create or replace trigger XHB_ORDER_IMP_EXP
  AFTER UPDATE ON XHB_ORDER
  FOR EACH ROW

DECLARE
 
  l_orderType VARCHAR2(5) := NULL;
  l_caseId NUMBER(8) := NULL;
  l_courtId NUMBER(8) := NULL;
  
BEGIN

  IF (:NEW.ORDER_DELIVERY_STATUS_ID = 2) THEN

    SELECT OTYPE.CODE
    INTO   l_orderType
    FROM   XHB_ORDER_TYPE OTYPE,
           XHB_ORDER_TEMPLATE OTEMP
    WHERE  :NEW.ORDER_TEMPLATE_ID = OTEMP.ORDER_TEMPLATE_ID
    AND    OTEMP.ORDER_TYPE_ID = OTYPE.ORDER_TYPE_ID;    

    SELECT CASE_ID
    INTO   l_caseId
    FROM   XHB_DEFENDANT_ON_CASE DC
    WHERE  DC.DEFENDANT_ON_CASE_ID = :NEW.DEFENDANT_ON_CASE_ID;

    SELECT COURT_ID
    INTO   l_courtId
    FROM   XHB_CASE C,
           XHB_DEFENDANT_ON_CASE DC
    WHERE  DC.DEFENDANT_ON_CASE_ID = :NEW.DEFENDANT_ON_CASE_ID
    AND    DC.CASE_ID = C.CASE_ID;

    INSERT INTO XHB_IMPORT_EXPORT_STATUS(TYPE_CODE, STATUS_CODE, CASE_ID, COURT_ID, DEFENDANT_ON_CASE_ID)
    VALUES (l_orderType,'R', l_caseId, l_courtId, :OLD.DEFENDANT_ON_CASE_ID);

  END IF;

END;
/
