SET TERM OFF
/*
 *
 * Filename:    XHIBIT2_Create_Sequences.sql
 *
 * Author:      Nick Sawyer
 *
 * Description: Creates all sequences.
 *
 * Version Information:
 *
 * Revision    Author                 Notes
 *
 * 0.1         Nick Sawyer            Initial revision
 *
 */
SET TERM ON

CREATE SEQUENCE MSEQ_MERC_REFRESH_STORAGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE TMP_ERROR_LOG_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ADDRESS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ATTRIBUTE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_BREACH_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CASE_APP_REASON_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CASE_PROSECTOR_AGENCY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CASE_REFERENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CASE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CC_INFO_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CHARGE_DIFFERENCES_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CHARGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CONFIGURED_PUBLIC_NOT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CONFIG_PROP_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CONTACT_DETAIL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_LOG_CATEGORY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_LOG_CAT_DESC_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_LOG_ENTRY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_LOG_EVENT_DESC_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_ROOM_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_COURT_SITE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CREST_IMPORT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CR_LIVE_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_CRN_SEQ MAXVALUE 99999999999 CYCLE NOORDER;
CREATE SEQUENCE XHB_DEFENDANT_CHARGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEFENDANT_ON_CASE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEFENDANT_ON_OFFENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEFENDANT_REFERENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEFENDANT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEFINITIVE_PUB_NOTICE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DEF_HEARING_RECORD_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DIRECTION_ATTEND_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DIR_FOR_CASE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DIR_FOR_DEFENDANT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPLAY_DOCUMENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPLAY_LOCATION_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPLAY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPLAY_TYPE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPOSAL_DETAIL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPOSAL_LINE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPOSAL_REFERENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPOSAL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DISPOSAL2_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DOCUMENT_CONTROL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DOCUMENT_DISTRIBUTION_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DOCUMENT_RECIPIENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_DOCUMENT_REPLY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_EMAIL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ERROR_DEF_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_EVENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_EXPORTA_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_FIXED_LIST_XML_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_FORMATTING_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_FORMB_RESULT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_HEARING_LEG_REP_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_HEARING_LIST_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_HEARING_RECORD_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_HEARING_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_IMPORT_EXPORT_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_INTERNET_HTML_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_JOINDER_CHARGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_JOINDER_DEF_ON_CASE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_JOINDER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_JOINDER_XML_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LEG_REP_FOR_SCHED_DEF_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LINKED_CASE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LINKED_HEARING_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LINKED_SH_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_MESSAGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_OBJECT_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_OFFENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORDER_DISPOSAL_XREF_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORDER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORD_DELIVERY_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORD_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORD_TEMPLATE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORD_TYPE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ORIGINAL_RESULT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PAGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PANEL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PLEA_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PSR_RECIPIENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PSR_REQUEST_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_PUBLIC_NOTICE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_RECIPIENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_ADVOCATE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_APP_RESULT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_BREACH_PROC_CODE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_CHAMBER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_COURT_REPORTER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_COURT_REPORT_F_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_COURT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_DEFENCE_CATEGORY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_DISPOSAL_LINE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_DISPOSAL_MENU_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_R_DISP_MENU_CASE_TYPE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_DISPOSAL_TYPE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_DISPOSAL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_HEARING_TYPE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_JUDGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_JUSTICE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_LEGAL_REP_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_OFFENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_PROSECUTOR_AGENCY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_SOLICITOR_FIRM_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_REF_SYSTEM_CODE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ROTATION_SET_DD_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ROTATION_SETS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_ROTATION_SET_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_RUNNING_LIST_XML_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SCHEDULED_HEARING_DEF_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SCHEDULED_HEARING_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SCHED_HEARING_ATTEND_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SCREEN_LOCATION_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SCREEN_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SH_COURT_REPORTER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SH_JUDGE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SH_JUSTICE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SH_LEG_REP_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SH_STAFF_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SECURITY_GROUP_ROLE_SEQ MAXVALUE 999999999999999999 MINVALUE 1 NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SITTING_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SKELETON_DAY_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SKELETON_DEL_STATUS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SKELETON_SCHEDULE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SKELETON_SESSION_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SOLICITOR_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SUBSCR_EVENT_CONTROL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_SYS_AUDIT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_TERMINAL_REFERENCE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_TERMINAL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_TIME_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_VERDICT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_WARNED_LIST_XML_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_WITNESS_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_WLL_CONTROL_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_WLL_DOCUMENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_WLL_RECIPIENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_XGROUP_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_XML_DOCUMENT_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_XROLE_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LEGAL_AID_ORDER_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
CREATE SEQUENCE XHB_LEO_ADV_LINK_SEQ NOMAXVALUE NOMINVALUE NOCACHE NOCYCLE NOORDER;
