SET TERM OFF
/*
 * Filename:    XHIBIT2_Create_Foreign_Keys.sql
 *
 * Author:      Nick Sawyer
 *
 * Description: Creates foreign keys.
 *
 * Version Information:
 *
 * Revision    Author                 Notes
 *
 * 0.1         Nick Sawyer            Initial revision
 *
 */
SET TERM ON

ALTER TABLE XHB_ATTRIBUTE
      ADD (CONSTRAINT ATTRIBUTE_EVENT_ID_FK FOREIGN KEY (EVENT_ID) REFERENCES XHB_EVENT);

ALTER TABLE XHB_BREACH
      ADD (CONSTRAINT BREACH_REF_COURT_ID_FK FOREIGN KEY (REF_COURT_ID) REFERENCES XHB_REF_COURT,
           CONSTRAINT BREACH_CHARGE_ID_FK FOREIGN KEY (CHARGE_ID) REFERENCES XHB_CHARGE);

ALTER TABLE XHB_CASE
      ADD (CONSTRAINT CASE_REF_COURT_ID_FK FOREIGN KEY (REF_COURT_ID) REFERENCES XHB_REF_COURT,
           CONSTRAINT CASE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT CASE_CCC_TRANS_TO_REF_CT_ID_FK FOREIGN KEY (CCC_TRANS_TO_REF_COURT_ID) REFERENCES XHB_REF_COURT);

ALTER TABLE XHB_CASE_APP_REASON
      ADD (CONSTRAINT CASE_APP_REASON_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_CASE_PROSECUTOR_AGENCY
      ADD (CONSTRAINT CASE_P_AGENCY_REF_P_AGE_ID_FK FOREIGN KEY (REF_PROSECUTOR_AGENCY_ID) REFERENCES XHB_REF_PROSECUTOR_AGENCY,
           CONSTRAINT CASE_P_AGENCY_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_CASE_REFERENCE
      ADD (CONSTRAINT CASE_REFERENCE_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_CHARGE
      ADD (CONSTRAINT CHARGE_REF_SYSTEM_CODE_ID_FK FOREIGN KEY (REF_SYSTEM_CODE_ID) REFERENCES XHB_REF_SYSTEM_CODE,
           CONSTRAINT CHARGE_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_CHARGE_DIFFERENCES
      ADD (CONSTRAINT CHARGE_DIFFERENCES_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT CHARGE_DIFFERENCES_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_CONFIGURED_PUBLIC_NOTICE
      ADD (CONSTRAINT CON_PUB_NOT_PUBLIC_NOT_ID_FK FOREIGN KEY (PUBLIC_NOTICE_ID) REFERENCES XHB_PUBLIC_NOTICE,
           CONSTRAINT CON_PUB_NOT_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM);

ALTER TABLE XHB_CONTACT_DETAIL
      ADD (CONSTRAINT CONTACT_DETAIL_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_COURT
      ADD (CONSTRAINT COURT_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_COURT_LOG_CATEGORY
      ADD (CONSTRAINT COURT_LOG_CAT_CAT_DESC_ID_FK FOREIGN KEY (CATEGORY_DESC_ID) REFERENCES XHB_COURT_LOG_CATEGORY_DESC,
           CONSTRAINT COURT_LOG_CAT_EVENT_DESC_ID_FK FOREIGN KEY (EVENT_DESC_ID) REFERENCES XHB_COURT_LOG_EVENT_DESC);

ALTER TABLE XHB_COURT_LOG_ENTRY
      ADD (CONSTRAINT CT_LOG_ENTRY_EVENT_DESC_ID_FK FOREIGN KEY (EVENT_DESC_ID) REFERENCES XHB_COURT_LOG_EVENT_DESC,
           CONSTRAINT CT_LOG_ENTRY_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE,
           CONSTRAINT CT_LOG_ENTRY_DEF_ON_CAS_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT CT_LOG_ENTRY_DEF_ON_OFF_ID_FK FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID) REFERENCES XHB_DEFENDANT_ON_OFFENCE,
           CONSTRAINT CT_LOG_ENTRY_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) REFERENCES XHB_SCHEDULED_HEARING);

ALTER TABLE XHB_COURT_ROOM
      ADD (CONSTRAINT COURT_ROOM_COURT_SITE_ID_FK FOREIGN KEY (COURT_SITE_ID) REFERENCES XHB_COURT_SITE);

ALTER TABLE XHB_COURT_SITE
      ADD (CONSTRAINT COURT_SITE_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS,
           CONSTRAINT COURT_SITE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_CR_LIVE_STATUS
      ADD (CONSTRAINT CR_LIVE_STAT_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) REFERENCES XHB_SCHEDULED_HEARING,
           CONSTRAINT CR_LIVE_STAT_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM);

ALTER TABLE XHB_CREST_IMPORT
      ADD (CONSTRAINT CREST_IMPORT_IMPORT_TYPE_FK FOREIGN KEY (IMPORT_TYPE) REFERENCES XHB_CREST_IMPORT_TYPE,
           CONSTRAINT CREST_IMPORT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_DEF_HEARING_RECORD
      ADD (CONSTRAINT DEF_H_REC_HEARING_ID_FK FOREIGN KEY (HEARING_ID) REFERENCES XHB_HEARING,
           CONSTRAINT DEF_H_REC_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT DEF_H_REC_REF_ADJ_ID_FK FOREIGN KEY (REF_ADJOURNMENT_ID) REFERENCES XHB_REF_SYSTEM_CODE,
           CONSTRAINT DEF_H_REC_COL_MAG_COURT_ID_FK FOREIGN KEY (COLLECT_MAGISTRATE_COURT_ID) REFERENCES XHB_REF_COURT,
           CONSTRAINT DEF_H_REC_REF_DEF_H_TYP_ID_FK FOREIGN KEY (REF_DEF_HEARING_TYPE_ID) REFERENCES XHB_REF_SYSTEM_CODE);

ALTER TABLE XHB_DEFENDANT
      ADD (CONSTRAINT DEFENDANT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT DEFENDANT_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_DEFENDANT_CHARGE
      ADD (CONSTRAINT DEF_CHARGE_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT DEF_CHARGE_CHARGE_ID_FK FOREIGN KEY (CHARGE_ID) REFERENCES XHB_CHARGE);

ALTER TABLE XHB_DEFENDANT_ON_CASE
      ADD (CONSTRAINT DEF_ON_CASE_DEFENDANT_ID_FK FOREIGN KEY (DEFENDANT_ID) REFERENCES XHB_DEFENDANT,
           CONSTRAINT DEF_ON_CASE_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE,
           CONSTRAINT DEF_ON_CASE_COL_MAG_CT_ID_FK FOREIGN KEY (COLLECT_MAGISTRATE_COURT_ID) REFERENCES XHB_REF_COURT);

ALTER TABLE XHB_DEFENDANT_ON_OFFENCE
      ADD (CONSTRAINT DEF_ON_OFF_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT DEF_ON_OFF_OFFENCE_ID_FK FOREIGN KEY (OFFENCE_ID) REFERENCES XHB_OFFENCE);

ALTER TABLE XHB_DEFENDANT_REFERENCE
      ADD (CONSTRAINT DEFENDANT_REF_DEFENDANT_ID_FK FOREIGN KEY (DEFENDANT_ID) REFERENCES XHB_DEFENDANT);

ALTER TABLE XHB_DIRECTION_ATTEND
      ADD (CONSTRAINT DIR_ATTEND_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT DIR_ATTEND_DIR_FOR_C_ID_FK FOREIGN KEY (DIRECTIONS_FOR_CASE_ID) REFERENCES XHB_DIRECTIONS_FOR_CASE);

ALTER TABLE XHB_DIRECTIONS_FOR_CASE
      ADD (CONSTRAINT DIRECTIONS_FOR_CASE_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_DIRECTIONS_FOR_DEFENDANT
      ADD (CONSTRAINT DIR_FOR_DEF_DEF_ON_C_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE);

ALTER TABLE XHB_DISPLAY
      ADD (CONSTRAINT DISPLAY_DISPLAY_TYPE_ID_FK FOREIGN KEY (DISPLAY_TYPE_ID) REFERENCES XHB_DISPLAY_TYPE,
           CONSTRAINT DISPLAY_DISPLAY_LOCATION_ID_FK FOREIGN KEY (DISPLAY_LOCATION_ID) REFERENCES XHB_DISPLAY_LOCATION,
           CONSTRAINT DISPLAY_ROTATION_SET_ID_FK FOREIGN KEY (ROTATION_SET_ID) REFERENCES XHB_ROTATION_SETS);

ALTER TABLE XHB_DISPLAY_COURT_ROOM
      ADD (CONSTRAINT DISPLAY_COURT_RM_DISPLAY_ID_FK FOREIGN KEY (DISPLAY_ID) REFERENCES XHB_DISPLAY,
           CONSTRAINT DISPLAY_COURT_RM_CT_RM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM);

ALTER TABLE XHB_DISPLAY_LOCATION
      ADD (CONSTRAINT DISPLAY_LOC_COURT_SITE_ID_FK FOREIGN KEY (COURT_SITE_ID) REFERENCES XHB_COURT_SITE);

ALTER TABLE XHB_DISPOSAL
      ADD (CONSTRAINT DISPOSAL_DEF_ON_OFFENCE_ID_FK FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID) REFERENCES XHB_DEFENDANT_ON_OFFENCE,
           CONSTRAINT DISPOSAL_REF_DISPOSAL_ID_FK FOREIGN KEY (REF_DISPOSAL_ID) REFERENCES XHB_REF_DISPOSAL,
           CONSTRAINT DISPOSAL_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE);

ALTER TABLE XHB_DISPOSAL2
      ADD (CONSTRAINT DISPOSAL2_DEF_ON_OFFENCE_ID_FK FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID) REFERENCES XHB_DEFENDANT_ON_OFFENCE,
           CONSTRAINT DISPOSAL2_REF_DISP_TYPE_ID_FK FOREIGN KEY (REF_DISPOSAL_TYPE_ID) REFERENCES XHB_REF_DISPOSAL_TYPE,
           CONSTRAINT DISPOSAL2_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT DISPOSAL2_PSD_DISPOSAL2_ID_FK FOREIGN KEY (PSD_DISPOSAL2_ID) REFERENCES XHB_DISPOSAL2);

ALTER TABLE XHB_DISPOSAL_DETAIL
      ADD (CONSTRAINT DISPOSAL_DET_ORIG_RESULT_ID_FK FOREIGN KEY (ORIGINAL_RESULT_ID) REFERENCES XHB_ORIGINAL_RESULT);

ALTER TABLE XHB_DISPOSAL_LINE
      ADD (CONSTRAINT DISP_LINE_REF_DISP_LINE_ID_FK FOREIGN KEY (REF_DISPOSAL_LINE_ID) REFERENCES XHB_REF_DISPOSAL_LINE,
           CONSTRAINT DISP_LINE_DISPOSAL2_ID_FK FOREIGN KEY (DISPOSAL2_ID) REFERENCES XHB_DISPOSAL2);

ALTER TABLE XHB_DISPOSAL_REFERENCE
      ADD (CONSTRAINT DISPOSAL_REFERENCE_DISP_ID_FK FOREIGN KEY (DISPOSAL_ID) REFERENCES XHB_DISPOSAL);

ALTER TABLE XHB_DOCUMENT_CONTROL
      ADD (CONSTRAINT DOCUMENT_CONT_XML_DOC_ID_FK FOREIGN KEY (XML_DOCUMENT_ID) REFERENCES XHB_XML_DOCUMENT,
           CONSTRAINT DOCUMENT_CONT_FORMATTING_ID_FK FOREIGN KEY (FORMATTING_ID) REFERENCES XHB_FORMATTING,
           CONSTRAINT DOCUMENT_CONT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_DOCUMENT_DISTRIBUTION
      ADD (CONSTRAINT DOCUMENT_DIST_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT DOCUMENT_DIST_WLL_RECIP_ID_FK FOREIGN KEY (WLL_RECIPIENT_ID) REFERENCES XHB_WLL_RECIPIENT,
           CONSTRAINT DOCUMENT_DIST_RECIPIENT_ID_FK FOREIGN KEY (RECIPIENT_ID) REFERENCES XHB_RECIPIENT);

ALTER TABLE XHB_DOCUMENT_RECIPIENT
      ADD (CONSTRAINT DOCUMENT_REC_DOC_CONTROL_ID_FK FOREIGN KEY (DOC_CONTROL_ID) REFERENCES XHB_DOCUMENT_CONTROL);

ALTER TABLE XHB_DOCUMENT_REPLY
      ADD (CONSTRAINT DOCUMENT_REPLY_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_EMAIL
      ADD (CONSTRAINT EMAIL_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_EVENT
      ADD (CONSTRAINT EVENT_PANEL_ID_FK FOREIGN KEY (PANEL_ID) REFERENCES XHB_PANEL);

ALTER TABLE XHB_EXPORTA
      ADD (CONSTRAINT EXPORTA_HEARING_ID_FK FOREIGN KEY (HEARING_ID) REFERENCES XHB_HEARING);

ALTER TABLE XHB_FORMATTING
      ADD (CONSTRAINT FORMATTING_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_FORMB_RESULT
      ADD (CONSTRAINT FORMB_RESULT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT FORMB_RESULT_REF_PLEA_ID_FK FOREIGN KEY (REF_PLEA_ID) REFERENCES XHB_REF_SYSTEM_CODE,
           CONSTRAINT FORMB_RESULT_REF_VERDICT_ID_FK FOREIGN KEY (REF_VERDICT_ID) REFERENCES XHB_REF_SYSTEM_CODE);

ALTER TABLE XHB_HEARING
      ADD (CONSTRAINT HEARING_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT HEARING_REF_HEARING_TYPE_ID_FK FOREIGN KEY (REF_HEARING_TYPE_ID) REFERENCES XHB_REF_HEARING_TYPE,
           CONSTRAINT HEARING_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_HEARING_LIST
      ADD (CONSTRAINT HEARING_LIST_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_HEARING_LEG_REP
      ADD (CONSTRAINT HEAR_LEG_REP_HEARING_ID_FK FOREIGN KEY (HEARING_ID) REFERENCES XHB_HEARING,
           CONSTRAINT HEAR_LEG_REP_REF_LEG_REP_ID_FK FOREIGN KEY (REF_LEGAL_REP_ID) REFERENCES XHB_REF_LEGAL_REPRESENTATIVE);

ALTER TABLE XHB_IMPORT_EXPORT_STATUS
      ADD (CONSTRAINT IMP_EXP_STATUS_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE,
           CONSTRAINT IMP_EXP_STATUS_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT IMP_EXP_STATUS_DEF_ON_C_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE);

ALTER TABLE XHB_INTERNET_HTML
      ADD (CONSTRAINT INTERNET_HTML_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_JOINDER
      ADD (CONSTRAINT JOINDER_REF_JUDGE_ID_FK FOREIGN KEY (REF_JUDGE_ID) REFERENCES XHB_REF_JUDGE);

ALTER TABLE XHB_JOINDER_CHARGE
      ADD (CONSTRAINT JOINDER_CHARGE_JOINDER_ID_FK FOREIGN KEY (JOINDER_ID) REFERENCES XHB_JOINDER,
           CONSTRAINT JOINDER_CHARGE_CHARGE_ID_FK FOREIGN KEY (CHARGE_ID) REFERENCES XHB_CHARGE);

ALTER TABLE XHB_JOINDER_DEFENDANT_ON_CASE
      ADD (CONSTRAINT J_DEF_ON_CASE_JOINDER_ID_FK FOREIGN KEY (JOINDER_ID) REFERENCES XHB_JOINDER,
           CONSTRAINT J_DEF_ON_CASE_DEF_ON_C_ID_1_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID_1) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT J_DEF_ON_CASE_DEF_ON_C_ID_2_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID_2) REFERENCES XHB_DEFENDANT_ON_CASE); 

ALTER TABLE XHB_JOINDER_XML
      ADD (CONSTRAINT JOINDER_XML_JOINDER_ID_FK FOREIGN KEY (JOINDER_ID) REFERENCES XHB_JOINDER);

ALTER TABLE XHB_OFFENCE
      ADD (CONSTRAINT OFFENCE_REF_SYSTEM_CODE_ID_FK FOREIGN KEY (REF_SYSTEM_CODE_ID) REFERENCES XHB_REF_SYSTEM_CODE,
           CONSTRAINT OFFENCE_CHARGE_ID_FK FOREIGN KEY (CHARGE_ID) REFERENCES XHB_CHARGE,
           CONSTRAINT OFFENCE_REF_OFFENCE_ID_FK FOREIGN KEY (REF_OFFENCE_ID) REFERENCES XHB_REF_OFFENCE);

ALTER TABLE XHB_ORDER
      ADD (CONSTRAINT ORDER_DEFENDANT_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT ORDER_ORDER_TEMPLATE_ID_FK FOREIGN KEY (ORDER_TEMPLATE_ID) REFERENCES XHB_ORDER_TEMPLATE,
           CONSTRAINT ORDER_ORDER_DEL_STATUS_ID_FK FOREIGN KEY (ORDER_DELIVERY_STATUS_ID) REFERENCES XHB_ORDER_DELIVERY_STATUS,
           CONSTRAINT ORDER_ORDER_STATUS_ID_FK FOREIGN KEY (ORDER_STATUS_ID) REFERENCES XHB_ORDER_STATUS);

ALTER TABLE XHB_ORDER_DISPOSAL_XREF
      ADD (CONSTRAINT O_DISP_XREF_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT O_DISP_XREF_RS_REF_DISP_ID_FK FOREIGN KEY (RS_REF_DISPOSAL_TYPE_ID) REFERENCES XHB_REF_DISPOSAL_TYPE,
           CONSTRAINT O_DISP_XREF_CO_REF_DISP_ID_FK FOREIGN KEY (CO_REF_DISPOSAL_TYPE_ID) REFERENCES XHB_REF_DISPOSAL_TYPE);

ALTER TABLE XHB_ORDER_TEMPLATE
      ADD (CONSTRAINT ORDER_TEMP_ORDER_TYPE_ID_FK FOREIGN KEY (ORDER_TYPE_ID) REFERENCES XHB_ORDER_TYPE);

ALTER TABLE XHB_ORDER_TYPE
      ADD (CONSTRAINT ORDER_TYPE_REF_DISP_TYPE_ID_FK FOREIGN KEY (REF_DISPOSAL_TYPE_ID) REFERENCES XHB_REF_DISPOSAL_TYPE);
           
ALTER TABLE XHB_ORIGINAL_RESULT
      ADD (CONSTRAINT ORIG_RESULT_REF_DISPOSAL_ID_FK FOREIGN KEY (REF_DISPOSAL_ID) REFERENCES XHB_REF_DISPOSAL,
           CONSTRAINT ORIG_RESULT_REF_COURT_ID_FK FOREIGN KEY (REF_COURT_ID) REFERENCES XHB_REF_COURT);

ALTER TABLE XHB_PAGE_PANEL
      ADD (CONSTRAINT PAGE_PANEL_PANEL_ID_FK FOREIGN KEY (PANEL_ID) REFERENCES XHB_PANEL,
           CONSTRAINT PAGE_PANEL_PAGE_ID_FK FOREIGN KEY (PAGE_ID) REFERENCES XHB_PAGE);

ALTER TABLE XHB_PAGE_ROTATION_SET
      ADD (CONSTRAINT PAGE_ROT_SET_ROT_SET_ID_FK FOREIGN KEY (ROTATION_SET_ID) REFERENCES XHB_ROTATION_SET,
           CONSTRAINT PAGE_ROT_SET_PAGE_ID_FK FOREIGN KEY (PAGE_ID) REFERENCES XHB_PAGE);

ALTER TABLE XHB_PLEA
      ADD (CONSTRAINT PLEA_DEF_ON_OFFENCE_ID_FK FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID) REFERENCES XHB_DEFENDANT_ON_OFFENCE,
           CONSTRAINT PLEA_DEF_CHARGE_ID_FK FOREIGN KEY (DEFENDANT_CHARGE_ID) REFERENCES XHB_DEFENDANT_CHARGE,
           CONSTRAINT PLEA_REF_PLEA_ID_FK FOREIGN KEY (REF_PLEA_ID) REFERENCES XHB_REF_SYSTEM_CODE,
           CONSTRAINT PLEA_ALT_REF_OFFENCE_ID_FK FOREIGN KEY (ALT_REF_OFFENCE_ID) REFERENCES XHB_REF_OFFENCE);

ALTER TABLE XHB_PSR_RECIPIENT
      ADD (CONSTRAINT PSR_RECIPIENT_REC_ADDR_ID_FK FOREIGN KEY (RECIPIENT_ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_PSR_REQUEST
      ADD (CONSTRAINT PSR_REQUEST_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE,
           CONSTRAINT PSR_REQUEST_PSR_REC_ID_FK FOREIGN KEY (PSR_RECIPIENT_ID) REFERENCES XHB_PSR_RECIPIENT);

ALTER TABLE XHB_PUBLIC_NOTICE
      ADD (CONSTRAINT PUBLIC_NOT_DEFINITIVE_PN_ID_FK FOREIGN KEY (DEFINITIVE_PN_ID) REFERENCES XHB_DEFINITIVE_PUBLIC_NOTICE,
           CONSTRAINT PUBLIC_NOT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_RECIPIENT
      ADD (CONSTRAINT RECIPIENT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_ADVOCATE
      ADD (CONSTRAINT REF_ADV_REF_CHAMBER_ID_FK FOREIGN KEY (REF_CHAMBER_ID) REFERENCES XHB_REF_CHAMBER,
           CONSTRAINT REF_ADV_REF_LEGAL_REP_ID_FK FOREIGN KEY (REF_LEGAL_REP_ID) REFERENCES XHB_REF_LEGAL_REPRESENTATIVE);

ALTER TABLE XHB_REF_APP_RESULT
      ADD (CONSTRAINT REF_APP_RESULT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_CHAMBER
      ADD (CONSTRAINT REF_CHAMBER_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT REF_CHAMBER_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_REF_COURT
      ADD (CONSTRAINT REF_COURT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT REF_COURT_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_REF_COURT_REPORTER
      ADD (CONSTRAINT REF_CT_REP_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT REF_CT_REP_REF_CT_REP_F_ID_FK FOREIGN KEY (REF_COURT_REPORTER_FIRM_ID) REFERENCES XHB_REF_COURT_REPORTER_FIRM);

ALTER TABLE XHB_REF_COURT_REPORTER_FIRM
      ADD (CONSTRAINT REF_CT_REP_FIRM_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT,
           CONSTRAINT REF_CT_REP_FIRM_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS);

ALTER TABLE XHB_REF_DISPOSAL
      ADD (CONSTRAINT REF_DISPOSAL_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_DISPOSAL_LINE              
      ADD (CONSTRAINT REF_DISPOSAL_LINE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_DISPOSAL_MENU
      ADD (CONSTRAINT REF_DISPOSAL_MENU_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_DISP_MENU_CASE_TYPE
      ADD (CONSTRAINT REF_DISP_MENU_CASE_TYPE_MEN_FK FOREIGN KEY (REF_DISPOSAL_MENU_ID) REFERENCES XHB_REF_DISPOSAL_MENU);

ALTER TABLE XHB_REF_DISPOSAL_TYPE
      ADD (CONSTRAINT REF_DISPOSAL_TYPE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_HEARING_TYPE
      ADD (CONSTRAINT REF_HEARING_TYPE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_JUDGE
      ADD (CONSTRAINT REF_JUDGE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_JUSTICE
      ADD (CONSTRAINT REF_JUSTICE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_LEGAL_REPRESENTATIVE
      ADD (CONSTRAINT REF_LEGAL_REP_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_OFFENCE
      ADD (CONSTRAINT REF_OFFENCE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_PROSECUTOR_AGENCY
      ADD (CONSTRAINT REF_PROS_AGENCY_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS,
           CONSTRAINT REF_PROS_AGENCY_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_SOLICITOR
      ADD (CONSTRAINT REF_SOL_REF_LEGAL_REP_ID_FK FOREIGN KEY (REF_LEGAL_REP_ID) REFERENCES XHB_REF_LEGAL_REPRESENTATIVE,
           CONSTRAINT REF_SOL_REF_SOL_FIRM_ID_FK FOREIGN KEY (REF_SOLICITOR_FIRM_ID) REFERENCES XHB_REF_SOLICITOR_FIRM);

ALTER TABLE XHB_REF_SOLICITOR_FIRM
      ADD (CONSTRAINT REF_SOL_FIRM_ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES XHB_ADDRESS,
           CONSTRAINT REF_SOL_FIRM_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_REF_SYSTEM_CODE
      ADD (CONSTRAINT REF_SYSTEM_CODE_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_ROTATION_SET_DD
      ADD (CONSTRAINT ROT_SET_DD_DISPLAY_DOC_ID_FK FOREIGN KEY (DISPLAY_DOCUMENT_ID) REFERENCES XHB_DISPLAY_DOCUMENT,
           CONSTRAINT ROT_SET_DD_ROTATION_SET_ID_FK FOREIGN KEY (ROTATION_SET_ID) REFERENCES XHB_ROTATION_SETS);

ALTER TABLE XHB_ROTATION_SETS
      ADD (CONSTRAINT ROTATION_SETS_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_SCHED_HEARING_ATTENDEE
      ADD (CONSTRAINT SCHED_H_ATT_REF_CT_REP_ID_FK FOREIGN KEY (REF_COURT_REPORTER_ID) REFERENCES XHB_REF_COURT_REPORTER,
           CONSTRAINT SCHED_H_ATT_REF_JUDGE_ID_FK FOREIGN KEY (REF_JUDGE_ID) REFERENCES XHB_REF_JUDGE,
           CONSTRAINT SCHED_H_ATT_SH_JUSTICE_ID_FK FOREIGN KEY (SH_JUSTICE_ID) REFERENCES XHB_SH_JUSTICE,
           CONSTRAINT SCHED_H_ATT_SH_STAFF_ID_FK FOREIGN KEY (SH_STAFF_ID) REFERENCES XHB_SH_STAFF,
           CONSTRAINT SCHED_H_ATT_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) REFERENCES XHB_SCHEDULED_HEARING,
           CONSTRAINT SCHED_H_ATT_REF_JUSTICE_ID_FK FOREIGN KEY (REF_JUSTICE_ID) REFERENCES XHB_REF_JUSTICE);

ALTER TABLE XHB_SCHED_HEARING_DEFENDANT
      ADD (CONSTRAINT SCHED_H_DEF_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) REFERENCES XHB_SCHEDULED_HEARING,
           CONSTRAINT SCHED_H_DEF_DEF_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE);

ALTER TABLE XHB_SCHEDULED_HEARING
      ADD (CONSTRAINT SCHED_HEAR_SITTING_ID_FK FOREIGN KEY (SITTING_ID) REFERENCES XHB_SITTING,
           CONSTRAINT SCHED_HEAR_HEARING_ID_FK FOREIGN KEY (HEARING_ID) REFERENCES XHB_HEARING,
           CONSTRAINT SCHED_HEAR_MOVED_F_CT_RM_ID_FK FOREIGN KEY (MOVED_FROM_COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM);

ALTER TABLE XHB_SCREEN
      ADD (CONSTRAINT SCREEN_SCREEN_LOCATION_ID_FK FOREIGN KEY (SCREEN_LOCATION_ID) REFERENCES XHB_SCREEN_LOCATION,
           CONSTRAINT SCREEN_ROTATION_SET_ID_FK FOREIGN KEY (ROTATION_SET_ID) REFERENCES XHB_ROTATION_SET);

ALTER TABLE XHB_SCREEN_COURT_ROOM
      ADD (CONSTRAINT SCREEN_CT_RM_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM,
           CONSTRAINT SCREEN_CT_RM_SCREEN_ID_FK FOREIGN KEY (SCREEN_ID) REFERENCES XHB_SCREEN);

ALTER TABLE XHB_SCREEN_LOCATION
      ADD (CONSTRAINT SCREEN_LOC_COURT_SITE_ID_FK FOREIGN KEY (COURT_SITE_ID) REFERENCES XHB_COURT_SITE);

ALTER TABLE XHB_SECURITY_GROUP_ROLE
      ADD (CONSTRAINT SECURITY_GROUP_ROLE_GROUP_FK FOREIGN KEY (GROUP_NAME) REFERENCES XHB_SECURITY_GROUP,
           CONSTRAINT SECURITY_GROUP_ROLE_ROLE_FK FOREIGN KEY (ROLE_NAME) REFERENCES XHB_SECURITY_ROLE);

ALTER TABLE XHB_SH_JUDGE
      ADD (CONSTRAINT SH_JUDGE_SH_ATTENDEE_ID_FK FOREIGN KEY (SH_ATTENDEE_ID) REFERENCES XHB_SCHED_HEARING_ATTENDEE,
           CONSTRAINT SH_JUDGE_REF_JUDGE_ID_FK FOREIGN KEY (REF_JUDGE_ID) REFERENCES XHB_REF_JUDGE);

ALTER TABLE XHB_SH_JUSTICE
      ADD (CONSTRAINT SH_JUSTICE_HEARING_ID_FK FOREIGN KEY (HEARING_ID) REFERENCES XHB_HEARING);

ALTER TABLE XHB_SH_LEG_REP
      ADD (CONSTRAINT SH_LEG_REP_SCHED_HEARING_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) REFERENCES XHB_SCHEDULED_HEARING,
           CONSTRAINT SH_LEG_REP_REF_SOL_FIRM_ID_FK FOREIGN KEY (REF_SOLICITOR_FIRM_ID) REFERENCES XHB_REF_SOLICITOR_FIRM,
           CONSTRAINT SH_LEG_REP_REF_LEGAL_REP_ID_FK FOREIGN KEY (REF_LEGAL_REP_ID) REFERENCES XHB_REF_LEGAL_REPRESENTATIVE,
           CONSTRAINT SH_LEG_REP_CC_INFO_ID_FK FOREIGN KEY (CC_INFO_ID) REFERENCES XHB_CC_INFO,
           CONSTRAINT SH_LEG_REP_SCHED_H_DEF_ID_FK FOREIGN KEY (SCHED_HEAR_DEF_ID) REFERENCES XHB_SCHED_HEARING_DEFENDANT,
           CONSTRAINT SH_LEG_REP_REF_DEF_CAT_ID_FK FOREIGN KEY (REF_DEFENCE_CATEGORY_ID) REFERENCES XHB_REF_SYSTEM_CODE,
	   CONSTRAINT SH_LEG_REP_SUB_REF_LEG_REP_FK FOREIGN KEY (SUBSTITUTED_REF_LEGAL_REP_ID) REFERENCES XHB_REF_LEGAL_REPRESENTATIVE (REF_LEGAL_REP_ID));

ALTER TABLE XHB_SITTING
      ADD (CONSTRAINT SITTING_COURT_SITE_ID_FK FOREIGN KEY (COURT_SITE_ID) REFERENCES XHB_COURT_SITE,
           CONSTRAINT SITTING_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM,
           CONSTRAINT SITTING_LIST_ID_FK FOREIGN KEY (LIST_ID) REFERENCES XHB_HEARING_LIST,
           CONSTRAINT SITTING_REF_JUDGE_ID_FK FOREIGN KEY (REF_JUDGE_ID) REFERENCES XHB_REF_JUDGE);

ALTER TABLE XHB_SKELETON_DAY
      ADD (CONSTRAINT SKELETON_DAY_SKELETON_ID_FK FOREIGN KEY (SKELETON_ID) REFERENCES XHB_SKELETON_SCHEDULE);

ALTER TABLE XHB_SKELETON_SCHEDULE
      ADD (CONSTRAINT SKEL_SCHED_SKEL_DEL_STAT_ID_FK FOREIGN KEY (SKELETON_DELIVERY_STATUS_ID) REFERENCES XHB_SKELETON_DELIVERY_STATUS,
           CONSTRAINT SKEL_SCHED_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_SKELETON_SESSION
      ADD (CONSTRAINT SKEL_SESSION_SKELETON_ID_FK FOREIGN KEY (SKELETON_ID) REFERENCES XHB_SKELETON_SCHEDULE,
           CONSTRAINT SKEL_SESSION_SKEL_DAY_ID_FK FOREIGN KEY (SKELETON_DAY_ID) REFERENCES XHB_SKELETON_DAY);

ALTER TABLE XHB_TERMINAL
      ADD (CONSTRAINT TERMINAL_COURT_SITE_ID_FK FOREIGN KEY (COURT_SITE_ID) REFERENCES XHB_COURT_SITE,
           CONSTRAINT TERMINAL_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) REFERENCES XHB_COURT_ROOM);

ALTER TABLE XHB_TERMINAL_REFERENCE
      ADD (CONSTRAINT TERMINAL_REF_TERMINAL_ID_FK FOREIGN KEY (TERMINAL_ID) REFERENCES XHB_TERMINAL);

ALTER TABLE XHB_TIME
      ADD (CONSTRAINT TIME_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE);

ALTER TABLE XHB_VERDICT
      ADD (CONSTRAINT VERDICT_REF_APP_RESULT_ID_FK FOREIGN KEY (REF_APP_RESULT_ID) REFERENCES XHB_REF_APP_RESULT,
           CONSTRAINT VERDICT_DEFENDANT_CHARGE_ID_FK FOREIGN KEY (DEFENDANT_CHARGE_ID) REFERENCES XHB_DEFENDANT_CHARGE,
           CONSTRAINT VERDICT_DEFENDANT_ON_OFF_ID_FK FOREIGN KEY (DEFENDANT_ON_OFFENCE_ID) REFERENCES XHB_DEFENDANT_ON_OFFENCE,
           CONSTRAINT VERDICT_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE,
           CONSTRAINT VERDICT_ALT_REF_OFFENCE_ID_FK FOREIGN KEY (ALT_REF_OFFENCE_ID) REFERENCES XHB_REF_OFFENCE,
           CONSTRAINT VERDICT_REF_VERDICT_ID_FK FOREIGN KEY (REF_VERDICT_ID) REFERENCES XHB_REF_SYSTEM_CODE);

ALTER TABLE XHB_WITNESS
      ADD (CONSTRAINT WITNESS_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE,
           CONSTRAINT WITNESS_SESSION_ID_FK FOREIGN KEY (SESSION_ID) REFERENCES XHB_SKELETON_SESSION);

ALTER TABLE XHB_WLL_CONTROL
      ADD (CONSTRAINT WLL_CONTROL_XML_DOCUMENT_ID_FK FOREIGN KEY (XML_DOCUMENT_ID) REFERENCES XHB_XML_DOCUMENT);

ALTER TABLE XHB_WLL_DOCUMENT
      ADD (CONSTRAINT WLL_DOCUMENT_WLL_CONTROL_ID_FK FOREIGN KEY (WLL_CONTROL_ID) REFERENCES XHB_WLL_CONTROL,
           CONSTRAINT WLL_DOCUMENT_XML_DOC_ID_FK FOREIGN KEY (XML_DOCUMENT_ID) REFERENCES XHB_XML_DOCUMENT,
           CONSTRAINT WLL_DOCUMENT_WLL_REC_ID_FK FOREIGN KEY (WLL_RECIPIENT_ID) REFERENCES XHB_WLL_RECIPIENT);

ALTER TABLE XHB_WLL_RECIPIENT
      ADD (CONSTRAINT WLL_RECIPIENT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_XML_DOCUMENT
      ADD (CONSTRAINT XML_DOCUMENT_COURT_ID_FK FOREIGN KEY (COURT_ID) REFERENCES XHB_COURT);

ALTER TABLE XHB_LEGAL_AID_ORDER
  ADD CONSTRAINT LEGAL_AID_ORDER_DEF_ON_CASE_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID)
  REFERENCES XHB_DEFENDANT_ON_CASE (DEFENDANT_ON_CASE_ID);

ALTER TABLE XHB_LEO_ADV_LINK
  ADD CONSTRAINT LEO_ADV_LINK_LEG_AID_ORDER_FK FOREIGN KEY (LEGAL_AID_ORDER_ID)
  REFERENCES XHB_LEGAL_AID_ORDER (LEGAL_AID_ORDER_ID);

ALTER TABLE XHB_LEO_ADV_LINK
  ADD CONSTRAINT LEO_ADV_LINK_DEF_ON_CASE_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID)
  REFERENCES XHB_DEFENDANT_ON_CASE (DEFENDANT_ON_CASE_ID);

ALTER TABLE XHB_LEO_ADV_LINK
  ADD CONSTRAINT LEO_ADV_LINK_REF_ADVOCATE_FK FOREIGN KEY (REF_ADVOCATE_ID)
  REFERENCES XHB_REF_ADVOCATE (REF_ADVOCATE_ID);


