SET TERM OFF
/*
 * Filename:    XHIBIT2_Create_Indexes_SysTest.sql
 *
 * Author:      Nick Sawyer
 *
 * Description: Creates table indexes on System Test.
 *
 * Version Information:
 *
 * Revision    Author                 Notes
 *
 * 0.1         Nick Sawyer            Initial revision
 *
 */
SET TERM ON

CREATE INDEX ATTRIBUTE_EVENT_FK_IDX ON XHB_ATTRIBUTE (EVENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX BREACH_CHARGE_FK_IDX ON XHB_BREACH (CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX BREACH_REF_COURT_FK_IDX ON XHB_BREACH (REF_COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX CASE_COURT_CASETN_IDX ON XHB_CASE (COURT_ID ASC, CASE_TYPE ASC, CASE_NUMBER ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_COURT_FK_IDX ON XHB_CASE (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_REF_COURT_FK_IDX ON XHB_CASE (REF_COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_CCC_TRAN_TO_REF_CT_FK_IDX ON XHB_CASE (CCC_TRANS_TO_REF_COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_APP_REASON_CASE_FK_IDX ON XHB_CASE_APP_REASON (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_PROS_AGC_CASE_FK_IDX ON XHB_CASE_PROSECUTOR_AGENCY (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_PROS_AGC_REF_PR_AG_FK_IDX ON XHB_CASE_PROSECUTOR_AGENCY (REF_PROSECUTOR_AGENCY_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CASE_REF_CASE_REF_FK_IDX ON XHB_CASE_REFERENCE (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CHARGE_CASE_FK_IDX ON XHB_CHARGE (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CHARGE_REF_SYSTEM_CODE_FK_IDX ON XHB_CHARGE (REF_SYSTEM_CODE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CHARGE_DIFF_CASE_FK_IDX ON XHB_CHARGE_DIFFERENCES (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CHARGE_DIFF_COURT_FK_IDX ON XHB_CHARGE_DIFFERENCES (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CONFIGURED_PUB_COURT_RM_FK_IDX ON XHB_CONFIGURED_PUBLIC_NOTICE (COURT_ROOM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CONFIGURED_PUB_PUB_NOT_FK_IDX ON XHB_CONFIGURED_PUBLIC_NOTICE (PUBLIC_NOTICE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CONTACT_DETAIL_ADDRESS_FK_IDX ON XHB_CONTACT_DETAIL (ADDRESS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX COURT_ADDRESS_FK_IDX ON XHB_COURT (ADDRESS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX COURT_SHORT_NAME_IDX ON XHB_COURT (SHORT_NAME)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CRT_LG_CAT_CRT_LG_EVT_D_FK_IDX ON XHB_COURT_LOG_CATEGORY (EVENT_DESC_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CRT_LG_CAT_CRT_LG_CAT_D_FK_IDX ON XHB_COURT_LOG_CATEGORY (CATEGORY_DESC_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX CRT_LG_CAT_DESC_CAT_DESC_IDX ON XHB_COURT_LOG_CATEGORY_DESC (CATEGORY_DESCRIPTION)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX COURT_LOG_ENTRY_CASE_FK_IDX ON XHB_COURT_LOG_ENTRY (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CRT_LG_ENT_CRT_LG_EVT_D_FK_IDX ON XHB_COURT_LOG_ENTRY (EVENT_DESC_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CRT_LG_ENT_SCHED_H_FK_IDX ON XHB_COURT_LOG_ENTRY (SCHEDULED_HEARING_ID)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX COURT_ROOM_COURT_SITE_FK_IDX ON XHB_COURT_ROOM (COURT_SITE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX COURT_SITE_COURT_FK_IDX ON XHB_COURT_SITE (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX COURT_SITE_ADDRESS_FK_IDX ON XHB_COURT_SITE (ADDRESS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX CR_LIVE_STATUS_COURT_RM_FK_IDX ON XHB_CR_LIVE_STATUS (COURT_ROOM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CR_LIVE_STATUS_SCH_HEAR_FK_IDX ON XHB_CR_LIVE_STATUS (SCHEDULED_HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CREST_IMP_COURT_FK_IDX ON XHB_CREST_IMPORT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX CREST_IMP_IMP_TYPE_FK_IDX ON XHB_CREST_IMPORT (IMPORT_TYPE ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_HEAR_REC_DEF_ON_CAS_FK_IDX ON XHB_DEF_HEARING_RECORD (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_HEAR_HEARING_FK_IDX ON XHB_DEF_HEARING_RECORD (HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_HEAR_REC_REF_ADJOUN_IDX ON XHB_DEF_HEARING_RECORD (REF_ADJOURNMENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_HEAR_REC_REF_COL_MG_FK_IDX ON XHB_DEF_HEARING_RECORD (COLLECT_MAGISTRATE_COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_HEAR_REC_REF_HEARNG_FK_IDX ON XHB_DEF_HEARING_RECORD (REF_DEF_HEARING_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_ADDRESS_FK_IDX ON XHB_DEFENDANT (ADDRESS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_COURT_FK_IDX ON XHB_DEFENDANT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_CHG_CHARGE_FK_IDX ON XHB_DEFENDANT_CHARGE (CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_CHG_DEF_CASE_FK_IDX ON XHB_DEFENDANT_CHARGE (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_ON_CASE_CASE_FK_IDX ON XHB_DEFENDANT_ON_CASE (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_ON_CASE_DEFEN_FK_IDX ON XHB_DEFENDANT_ON_CASE (DEFENDANT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_OFF_OFFENCE_FK_IDX ON XHB_DEFENDANT_ON_OFFENCE (OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEF_ON_OFF_DEF_CASE_FK_IDX ON XHB_DEFENDANT_ON_OFFENCE (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DEFENDANT_REFERENCE_DEF_FK_IDX ON XHB_DEFENDANT_REFERENCE (DEFENDANT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DIRECTION_ATT_DIR_FR_CS_FK_IDX ON XHB_DIRECTION_ATTEND (DIRECTIONS_FOR_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DIRECTION_ATT_DEF_ON_CS_FK_IDX ON XHB_DIRECTION_ATTEND (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DIRECTIONS_CASE_CASE_FK_IDX ON XHB_DIRECTIONS_FOR_CASE (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DIR_FOR_DEF_DEF_ON_CASE_FK_IDX ON XHB_DIRECTIONS_FOR_DEFENDANT (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISPOSAL_DEF_ON_CASE_FK_IDX ON XHB_DISPOSAL (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISPOSAL_REF_DISPOSAL_FK_IDX ON XHB_DISPOSAL (REF_DISPOSAL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISPOSAL_DEF_ON_OFFENCE_FK_IDX ON XHB_DISPOSAL (DEFENDANT_ON_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP2_DEF_ON_OFFENCE_FK_IDX ON XHB_DISPOSAL2 (DEFENDANT_ON_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP2_REF_DISP_TYPE_FK_IDX ON XHB_DISPOSAL2 (REF_DISPOSAL_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP2_DEF_ON_CASE_FK_IDX ON XHB_DISPOSAL2 (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP2_PSD_DISPOSAL2_FK_IDX ON XHB_DISPOSAL2 (PSD_DISPOSAL2_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP_LINE_REF_DISP_LINE_FK_IDX ON XHB_DISPOSAL_LINE (REF_DISPOSAL_LINE_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISP_LINE_DISPOSAL2_FK_IDX ON XHB_DISPOSAL_LINE (DISPOSAL2_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORIGINAL_RESULT_FK_IDX ON XHB_DISPOSAL_DETAIL (ORIGINAL_RESULT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DISPOSAL_REF_DISPOSAL2_FK_IDX ON XHB_DISPOSAL_REFERENCE (DISPOSAL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_CONTROL_COURT_FK_IDX ON XHB_DOCUMENT_CONTROL (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_CTRL_FORMAT_DOC_FK_IDX ON XHB_DOCUMENT_CONTROL (FORMATTING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX XML_DOC_FK_IDX ON XHB_DOCUMENT_CONTROL (XML_DOCUMENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_DIST_RECIP_FK_IDX ON XHB_DOCUMENT_DISTRIBUTION (RECIPIENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_DIST_WLL_RECIP_FK_IDX ON XHB_DOCUMENT_DISTRIBUTION (WLL_RECIPIENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_DIST_COURT_FK_IDX ON XHB_DOCUMENT_DISTRIBUTION (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_RECIPEIENT_DOC_CONTROL_IDX ON XHB_DOCUMENT_RECIPIENT (DOC_CONTROL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX DOC_REPLY_COURT_FK_IDX ON XHB_DOCUMENT_REPLY (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX EMAIL_COURT_FK_IDX ON XHB_EMAIL (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX EVENT_XHB_PANEL_FK_IDX ON XHB_EVENT (PANEL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX EXPORTA_HEARING_FK_IDX ON XHB_EXPORTA (HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX FORMAT_COURT_FK_IDX ON XHB_FORMATTING (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX FORMB_REF_PLEA_FK_IDX ON XHB_FORMB_RESULT (REF_PLEA_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX FORMB_REF_VERDICT_FK_IDX ON XHB_FORMB_RESULT (REF_VERDICT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX FORMB_COURT_FK_IDX ON XHB_FORMB_RESULT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX HEARING_CASE_FK_IDX ON XHB_HEARING (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX HEARING_REF_HEARING_TYP_FK_IDX ON XHB_HEARING (REF_HEARING_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX HEARING_COURT_FK_IDX ON XHB_HEARING (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX HEARING_LIST_COURT_FK_IDX ON XHB_HEARING_LIST (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX NET_HTML_COURT_FK_IDX ON XHB_INTERNET_HTML (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_REF_JUDGE_FK_IDX ON XHB_JOINDER (REF_JUDGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_CHARGE_CHARGE_FK_IDX ON XHB_JOINDER_CHARGE (CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_CHARGE_JOINDER_FK_IDX ON XHB_JOINDER_CHARGE (JOINDER_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_ON_CASE_JOINDER_FK_IDX ON XHB_JOINDER_DEFENDANT_ON_CASE (JOINDER_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_DEF_ON_CASE_1_FK_IDX ON XHB_JOINDER_DEFENDANT_ON_CASE (DEFENDANT_ON_CASE_ID_1 ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_DEF_ON_CASE_2_FK_IDX ON XHB_JOINDER_DEFENDANT_ON_CASE (DEFENDANT_ON_CASE_ID_2 ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JOINDER_JOINDER_XML_FK_IDX ON XHB_JOINDER_XML (JOINDER_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX OFFENCE_REF_OFFENCE_FK_IDX ON XHB_OFFENCE (REF_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX OFFENCE_CHARGE_FK_IDX ON XHB_OFFENCE (CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX OFFENCE_REF_SYSTEM_CODE_FK_IDX ON XHB_OFFENCE (REF_SYSTEM_CODE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORDER_ORDER_STATUS_FK_IDX ON XHB_ORDER (ORDER_STATUS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORD_ORD_DELIVERY_STATUS_FK_IDX ON XHB_ORDER (ORDER_DELIVERY_STATUS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORDER_ORDER_TEMPLATE_FK_IDX ON XHB_ORDER (ORDER_TEMPLATE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORD_DEF_ON_CASE_FK_IDX ON XHB_ORDER (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORDER_DISP_COURT_FK_IDX ON XHB_ORDER_DISPOSAL_XREF (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX O_DISP_XREF_RS_R_D_TYPE_FK_IDX ON XHB_ORDER_DISPOSAL_XREF (RS_REF_DISPOSAL_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX O_DISP_XREF_CO_R_D_TYPE_FK_IDX ON XHB_ORDER_DISPOSAL_XREF (CO_REF_DISPOSAL_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX O_DISP_XREF_CO_R_D_TYPE_IDX ON XHB_ORDER_DISPOSAL_XREF (CO_REF_DISPOSAL_TYPE_ID ASC, COURT_ID ASC, RS_REF_DISPOSAL_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORD_TEMPL_ORDER_TYPE_FK_IDX ON XHB_ORDER_TEMPLATE (ORDER_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX O_TYPE_R_DISP_TYPE_FK_IDX ON XHB_ORDER_TYPE (REF_DISPOSAL_TYPE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORIGINAL_RESULT_REF_DIS_FK_IDX ON XHB_ORIGINAL_RESULT (REF_DISPOSAL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX ORIGINAL_RESULT_REF_CRT_FK_IDX ON XHB_ORIGINAL_RESULT (REF_COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX PAGE_IDX ON XHB_PAGE (NAME ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PAGE_PANEL_XHB_PAGE_FK_IDX ON XHB_PAGE_PANEL (PAGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PAGE_PANEL_PANEL_FK_IDX ON XHB_PAGE_PANEL (PANEL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PAGE_ROTATION_PAGE_FK_IDX ON XHB_PAGE_ROTATION_SET (PAGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PAGE_ROTATION_SET_ROTAT_FK_IDX ON XHB_PAGE_ROTATION_SET (ROTATION_SET_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PLEA_DEF_CHARGE_FK_IDX ON XHB_PLEA (DEFENDANT_CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PLEA_DEF_ON_OFFENCE_FK_IDX ON XHB_PLEA (DEFENDANT_ON_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PLEA_REF_PLEA_FK_IDX ON XHB_PLEA (REF_PLEA_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PLEA_ALT_REF_OFFENCE_FK_IDX ON XHB_PLEA (ALT_REF_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PSR_RECIP_ADDRESS_FK_IDX ON XHB_PSR_RECIPIENT (RECIPIENT_ADDRESS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PSR_REQ_DEF_FK_IDX ON XHB_PSR_REQUEST (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PSR_REQ_PSR_RECIP_FK_IDX ON XHB_PSR_REQUEST (PSR_RECIPIENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PUBLIC_NOTICE_COURT_FK_IDX ON XHB_PUBLIC_NOTICE (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX PUBLIC_NOTICE_DEFIN_PUB_FK_IDX ON XHB_PUBLIC_NOTICE (DEFINITIVE_PN_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX RECIPIENT_REF_COURT_FK_IDX ON XHB_RECIPIENT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_ADVOCATE_REF_CHAMB_FK_IDX ON XHB_REF_ADVOCATE (REF_CHAMBER_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_ADVOCATE_REF_LEG_RP_FK_IDX ON XHB_REF_ADVOCATE (REF_LEGAL_REP_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_ADVOCATE_CREST_ADV_IDX ON XHB_REF_ADVOCATE (CREST_ADVOCATE_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_APP_RES_COURT_FK_IDX ON XHB_REF_APP_RESULT (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_CHAMBER_ADDRESS_FK_IDX ON XHB_REF_CHAMBER (ADDRESS_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_CHAMBER_COURT_FK_IDX ON XHB_REF_CHAMBER (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_ADDRESS_FK_IDX ON XHB_REF_COURT (ADDRESS_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_COURT_FK_IDX ON XHB_REF_COURT (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_CRT_REP_REPORT_FIRM_FK_IDX ON XHB_REF_COURT_REPORTER (REF_COURT_REPORTER_FIRM_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_REPORTER_CRT_FK_IDX ON XHB_REF_COURT_REPORTER (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_REPORTER_ADDR_FK_IDX ON XHB_REF_COURT_REPORTER_FIRM (ADDRESS_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_REP_F_COURT_FK_IDX ON XHB_REF_COURT_REPORTER_FIRM (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISPOSAL_COURT_FK_IDX ON XHB_REF_DISPOSAL (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISP_LINE_COURT_FK_IDX ON XHB_REF_DISPOSAL_LINE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISPOSAL_MENU_COURT_FK_IDX ON XHB_REF_DISPOSAL_MENU (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISP_TYPE_COURT_FK_IDX ON XHB_REF_DISPOSAL_TYPE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_HEARING_TYPE_COURT_IDX ON XHB_REF_HEARING_TYPE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_JUDGE_COURT_FK_IDX ON XHB_REF_JUDGE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_JUSTICE_COURT_FK_IDX ON XHB_REF_JUSTICE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_LEGAL_REP_COURT_FK_IDX ON XHB_REF_LEGAL_REPRESENTATIVE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_OFFENCE_COURT_FK_IDX ON XHB_REF_OFFENCE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX REF_OFF_OCODE_CTID_IDX ON XHB_REF_OFFENCE (OFFENCE_CODE, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_PROS_AGCY_COURT_FK_IDX ON XHB_REF_PROSECUTOR_AGENCY (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_PROS_AGCY_ADDRESS_FK_IDX ON XHB_REF_PROSECUTOR_AGENCY (ADDRESS_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SOLICTOR_FIRM_FK_IDX ON XHB_REF_SOLICITOR (REF_SOLICITOR_FIRM_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SOLICITOR_REF_LEGAL_REP_FK_IDX ON XHB_REF_SOLICITOR (REF_LEGAL_REP_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_SOLICITOR_FIRM_CRT_FK_IDX ON XHB_REF_SOLICITOR_FIRM (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_SOLICITOR_FIRM_ADDR_FK_IDX ON XHB_REF_SOLICITOR_FIRM (ADDRESS_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_SYSTEM_CODE_COURT_FK_IDX ON XHB_REF_SYSTEM_CODE (COURT_ID ASC)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_MOVED_F_CT_RM_IDX ON XHB_SCHEDULED_HEARING (MOVED_FROM_COURT_ROOM_ID)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_ATT_SCHED_HR_FK_IDX ON XHB_SCHED_HEARING_ATTENDEE (SCHEDULED_HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCH_HR_SH_STAFF_FK_IDX ON XHB_SCHED_HEARING_ATTENDEE (SH_STAFF_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCH_HR_SH_JUST_FK_IDX ON XHB_SCHED_HEARING_ATTENDEE (SH_JUSTICE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCH_HR_REF_JUDGE_FK_IDX ON XHB_SCHED_HEARING_ATTENDEE (REF_JUDGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCH_HR_REF_CRT_REP_FK_IDX ON XHB_SCHED_HEARING_ATTENDEE (REF_COURT_REPORTER_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_DEF_DF_ON_CS_FK_IDX ON XHB_SCHED_HEARING_DEFENDANT (DEFENDANT_ON_CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_DEF_SCHED_HR_FK_IDX ON XHB_SCHED_HEARING_DEFENDANT (SCHEDULED_HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_HEARING_FK_IDX ON XHB_SCHEDULED_HEARING (HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_LINKED_SH_ID_FK_IDX ON XHB_SCHEDULED_HEARING (LINKED_SH_ID)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCHED_HEAR_SITTING_FK_IDX ON XHB_SCHEDULED_HEARING (SITTING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX SCREEN_NAME_IDX ON XHB_SCREEN (NAME ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCREEN_ROTATION_SET_FK_IDX ON XHB_SCREEN (ROTATION_SET_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCREEN_SCREEN_LOCATION_FK_IDX ON XHB_SCREEN (SCREEN_LOCATION_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCR_CRT_ROOM_XHB_SCREEN_FK_IDX ON XHB_SCREEN_COURT_ROOM (SCREEN_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCR_CRT_ROOM_COURT_RM_FK_IDX ON XHB_SCREEN_COURT_ROOM (COURT_ROOM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SCREEN_LOC_COURT_S_FK_IDX ON XHB_SCREEN_LOCATION (COURT_SITE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_JUDGE_REF_JUDGE_FK_IDX ON XHB_SH_JUDGE (REF_JUDGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_JUDGE_SCHED_HEAR_ATT_FK_IDX ON XHB_SH_JUDGE (SH_ATTENDEE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX JUSTICE_HEARING_FK_IDX ON XHB_SH_JUSTICE (HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_SCH_HEAR_DEF_FK_IDX ON XHB_SH_LEG_REP (SCHED_HEAR_DEF_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_CC_INFO_FK_IDX ON XHB_SH_LEG_REP (CC_INFO_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_REF_LEG_REP_FK_IDX ON XHB_SH_LEG_REP (REF_LEGAL_REP_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_REF_SOL_FIRM_FK_IDX ON XHB_SH_LEG_REP (REF_SOLICITOR_FIRM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_SCHED_HEAR_FK_IDX ON XHB_SH_LEG_REP (SCHEDULED_HEARING_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SH_LEG_REP_REF_DEFENCE_FK_IDX ON XHB_SH_LEG_REP (REF_DEFENCE_CATEGORY_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SITTING_REF_JUDGE_FK_IDX ON XHB_SITTING (REF_JUDGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SITTING_HEARING_LIST_FK_IDX ON XHB_SITTING (LIST_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SITTING_COURT_ROOM_FK_IDX ON XHB_SITTING (COURT_ROOM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SITTING_COURT_SITE_FK_IDX ON XHB_SITTING (COURT_SITE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SKELETON_SCHED_FK_IDX ON XHB_SKELETON_DAY (SKELETON_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX SKELETON_SCHEDULE_IDX ON XHB_SKELETON_SCHEDULE (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SKEL_SCHED_DELIV_STATUS_FK_IDX ON XHB_SKELETON_SCHEDULE (SKELETON_DELIVERY_STATUS_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SKEL_SESS_SKEL_DAY_FK_IDX ON XHB_SKELETON_SESSION (SKELETON_DAY_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX SKEL_SESS_SKEL_SCHED_FK_IDX ON XHB_SKELETON_SESSION (SKELETON_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX SYS_AUDIT_TABLE_TO_AUD_IDX ON XHB_SYS_AUDIT (TABLE_TO_AUDIT)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX TERMINAL_COURT_ROOM_FK_IDX ON XHB_TERMINAL (COURT_ROOM_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX TERMINAL_COURT_SITE_FK_IDX ON XHB_TERMINAL (COURT_SITE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX TERMINAL_TERMINAL_NAME_IDX ON XHB_TERMINAL (TERMINAL_NAME)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX TERMINAL_FK_IDX ON XHB_TERMINAL_REFERENCE (TERMINAL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE UNIQUE INDEX TIME_CASE_FK_IDX ON XHB_TIME (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_DEF_ON_OFF_FK_IDX ON XHB_VERDICT (DEFENDANT_ON_OFFENCE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_DEF_CHARGE_FK_IDX ON XHB_VERDICT (DEFENDANT_CHARGE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_REF_APP_RES_FK_IDX ON XHB_VERDICT (REF_APP_RESULT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_CASE_FK_IDX ON XHB_VERDICT (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_ALT_REF_OFF_ID_FK_IDX ON XHB_VERDICT (ALT_REF_OFFENCE_ID) 
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX VERDICT_REF_VERDICT_ID_FK_IDX ON XHB_VERDICT (REF_VERDICT_ID)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WITNESS_CASE_FK_IDX ON XHB_WITNESS (CASE_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WITNESS_SKEL_SESSION_FK_IDX ON XHB_WITNESS (SESSION_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WLL_CTRL_XML_DOC_FK_IDX ON XHB_WLL_CONTROL (XML_DOCUMENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WLL_DOC_RECIP_FK_IDX ON XHB_WLL_DOCUMENT (WLL_RECIPIENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WLL_DOC_XML_DOC_FK_IDX ON XHB_WLL_DOCUMENT (XML_DOCUMENT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WLL_DOC_WLL_CTRL_FK_IDX ON XHB_WLL_DOCUMENT (WLL_CONTROL_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX WLL_RECIP_COURT_FK_IDX ON XHB_WLL_RECIPIENT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX XML_DOC_COURT_FK_IDX ON XHB_XML_DOCUMENT (COURT_ID ASC)
  TABLESPACE XHIBITX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX MTBL_MERC_G_LOC_D_COURT_ID_IDX ON MTBL_MERC_GLOBAL_LOCAL_DATA (COURT_ID)
  TABLESPACE MERCATORX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_JUDGE_C_JUD_ID_CT_ID_IDX ON XHB_REF_JUDGE(CREST_JUDGE_ID, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_JUSTICE_C_JP_ID_CT_ID_IDX ON XHB_REF_JUSTICE(CREST_JUSTICE_ID, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_CRT_REP_CCRPT_ID_CT_IDX ON XHB_REF_COURT_REPORTER(CREST_COURT_REPORTER_ID, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_CRT_REP_CCRFID_CT_IDX ON XHB_REF_COURT_REPORTER_FIRM(CREST_COURT_REPORTER_FIRM_ID, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_SOLICITOR_FIRM_COURT_IDX ON XHB_REF_SOLICITOR_FIRM(COURT_ID, CREST_SOF_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_PROS_AGCY_CO_CT_IDX ON XHB_REF_PROSECUTOR_AGENCY(CREST_OPPOSER_ID, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_SYSTEM_CODE_C_T_CT_ID_IDX on XHB_REF_SYSTEM_CODE (CODE, CODE_TYPE,COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DMENU_ABGPSQ_MI_CT_ID_IDX ON XHB_REF_DISPOSAL_MENU(ABBREV, MENU_GROUP, SEQ_NO,MENU_ITEM_ID,COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISP_TYPE_TVDCMGCT_ID_IDX ON XHB_REF_DISPOSAL_TYPE(TEMPLATE_VERSION, DISPOSAL_CODE, MENU_GROUP, COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_HEARING_TYPE_HC_CT_ID_IDX ON XHB_REF_HEARING_TYPE (HEARING_TYPE_CODE,COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_COURT_CT_CD_CRT_ID_IDX on XHB_REF_COURT(CREST_CODE,COURT_ID )
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_APP_RES_AP_CD_CRT_ID_IDX ON XHB_REF_APP_RESULT(APP_RESULT_CODE,COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);

CREATE INDEX REF_DISP_LN_TV_DC_DSQ_CTID_IDX ON XHB_REF_DISPOSAL_LINE(TEMPLATE_VERSION,DISPOSAL_CODE,DIL_SEQ_NO,COURT_ID)
  TABLESPACE XHIBITREFX
  STORAGE (INITIAL 256K
           NEXT 256K
           PCTINCREASE 0);
