CREATE TABLE CJI_EXPORT (
       CJI_EXPORT_ID   NUMBER(8)  NOT NULL,
       STATUS            CHAR(1)    NULL,
       CREST_COURT_CODE          NUMBER(8)  NULL,
       EXPORT_TYPE       VARCHAR(2) NULL,
       LAST_UPDATE_DATE  DATE NOT NULL,
       CREATION_DATE     DATE NOT NULL,
       CREATED_BY        VARCHAR2(30) NOT NULL,
       LAST_UPDATED_BY   VARCHAR2(30) NOT NULL,
       VERSION           NUMBER(5) NOT NULL)
       TABLESPACE DATAD
       STORAGE (INITIAL 1M NEXT 1M PCTINCREASE 0);

ALTER TABLE CJI_EXPORT
       ADD (PRIMARY KEY (CJI_EXPORT_ID)
       USING INDEX TABLESPACE DATAX
       STORAGE (INITIAL 256K NEXT 256K PCTINCREASE 0));

CREATE SEQUENCE CJI_EXPORT_SEQ 
NOMAXVALUE 
NOMINVALUE 
NOCACHE  
NOCYCLE
NOORDER
;

CREATE OR REPLACE TRIGGER CJI_EXPORT_BIR_TR
  BEFORE INSERT
  ON CJI_EXPORT
  FOR EACH ROW

BEGIN

  IF :NEW.CJI_EXPORT_ID IS NULL THEN

    SELECT CJI_EXPORT_SEQ .NEXTVAL
    INTO   :NEW.CJI_EXPORT_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY 
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE, 
         :NEW.CREATION_DATE, 
         :NEW.VERSION 
  FROM   DUAL;

END;
/

INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 401, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 402, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 403, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 404, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 406, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 407, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 408, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 409, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 410, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 411, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 412, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 413, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 414, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 415, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 416, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 417, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 418, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 419, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 420, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 421, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 422, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 423, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 424, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 425, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 426, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 427, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 428, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 429, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 430, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 431, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 432, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 433, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 434, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 435, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 436, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 437, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 439, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 440, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 441, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 442, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 443, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 444, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 445, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 446, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 447, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 448, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 449, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 450, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 451, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 452, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 453, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 454, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 455, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 456, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 457, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 458, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 459, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 460, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 461, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 462, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 463, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 464, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 465, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 466, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 467, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 468, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 469, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 470, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 471, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 472, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 473, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 474, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 475, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 476, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 477, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 478, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 479, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 480, 'D');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 401, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 402, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 403, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 404, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 406, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 407, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 408, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 409, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 410, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 411, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 412, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 413, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 414, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 415, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 416, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 417, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 418, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 419, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 420, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 421, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 422, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 423, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 424, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 425, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 426, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 427, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 428, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 429, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 430, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 431, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 432, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 433, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 434, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 435, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 436, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 437, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 439, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 440, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 441, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 442, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 443, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 444, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 445, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 446, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 447, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 448, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 449, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 450, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 451, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 452, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 453, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 454, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 455, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 456, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 457, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 458, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 459, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 460, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 461, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 462, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 463, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 464, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 465, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 466, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 467, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 468, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 469, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 470, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 471, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 472, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 473, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 474, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 475, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 476, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 477, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 478, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 479, 'E');
INSERT INTO CJI_EXPORT (STATUS, CREST_COURT_CODE, EXPORT_TYPE) VALUES ('S', 480, 'E');
commit;



