INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
1, 'EMAIL', '-TV+ -FROM xhibitiiemailfax@OPSCS.com', 'SMTP', 'CSM00001'
, 'xhibitiiemailfax', 'xhibitfax', 'document',  TO_Date( '09/23/2005 11:24:19 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Xhibit', 'Xhibit', 2); 


INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
2, 'EMAIL', '-TV+ ', 'MAPI', '', '', ''
, 'document',  TO_Date( '09/23/2005 11:24:24 AM', 'MM/DD/YYYY HH:MI:SS AM'),  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
, 'Xhibit', 'Xhibit', 2); 


INSERT INTO XHB_MTBL_ADAPTOR_CONFIG ( MTBL_ADAPTOR_CONFIG_ID, ADAPTOR_TYPE, PARAMETERS, SERVER_TYPE,
SERVER_ADDRESS, USERNAME, PASSWORD, DOCUMENT_NAME, LAST_UPDATE_DATE, CREATION_DATE, CREATED_BY,
LAST_UPDATED_BY, VERSION ) VALUES ( 
3, 'FTP', NULL, 'FTP', 'FTP://xhibit2:mercator@10.30.10.16/', 'xhibit2', 'mercator'
, 'InternetInterface',  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM')
,  TO_Date( '06/30/2005 12:00:00 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'Xhibit', 'Xhibit', 1); 

COMMIT;
