// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ActivityInfo_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_sessionId_QNAME = new QName("", "sessionId");
    private static final javax.xml.namespace.QName ns1_initiatorSessionId_QNAME = new QName("", "initiatorSessionId");
    private static final javax.xml.namespace.QName ns1_activityId_QNAME = new QName("", "activityId");
    private static final javax.xml.namespace.QName ns1_autoCloseConnection_QNAME = new QName("", "autoCloseConnection");
    private static final javax.xml.namespace.QName ns1_closed_QNAME = new QName("", "closed");
    private static final javax.xml.namespace.QName ns1_targetDeploymentId_QNAME = new QName("", "targetDeploymentId");
    private static final javax.xml.namespace.QName ns1_initiatorDeploymentId_QNAME = new QName("", "initiatorDeploymentId");
    
    public ActivityInfo_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ActivityInfo_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_sessionId_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setSessionId((java.lang.String)member);
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_sessionId_QNAME});
        }
        attribute = attributes.getValue(ns1_initiatorSessionId_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setInitiatorSessionId((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_activityId_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setActivityId((java.lang.String)member);
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_activityId_QNAME});
        }
        attribute = attributes.getValue(ns1_autoCloseConnection_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setAutoCloseConnection(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_autoCloseConnection_QNAME});
        }
        attribute = attributes.getValue(ns1_closed_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setClosed(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_closed_QNAME});
        }
        attribute = attributes.getValue(ns1_targetDeploymentId_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setTargetDeploymentId((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_initiatorDeploymentId_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setInitiatorDeploymentId((java.lang.String)member);
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo)obj;
        
        if (instance.getSessionId() != null) {
            writer.writeAttribute(ns1_sessionId_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getSessionId(), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_sessionId_QNAME});
        }
        if (instance.getInitiatorSessionId() != null) {
            writer.writeAttribute(ns1_initiatorSessionId_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getInitiatorSessionId(), writer));
        }
        if (instance.getActivityId() != null) {
            writer.writeAttribute(ns1_activityId_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getActivityId(), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_activityId_QNAME});
        }
        if (new Boolean(instance.isAutoCloseConnection()) != null) {
            writer.writeAttribute(ns1_autoCloseConnection_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isAutoCloseConnection()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_autoCloseConnection_QNAME});
        }
        if (new Boolean(instance.isClosed()) != null) {
            writer.writeAttribute(ns1_closed_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isClosed()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_closed_QNAME});
        }
        if (instance.getTargetDeploymentId() != null) {
            writer.writeAttribute(ns1_targetDeploymentId_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getTargetDeploymentId(), writer));
        }
        if (instance.getInitiatorDeploymentId() != null) {
            writer.writeAttribute(ns1_initiatorDeploymentId_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getInitiatorDeploymentId(), writer));
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo)obj;
        
    }
}
