// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ArrayProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] valueActions;
    
    public ArrayProperty() {
    }
    
    public ArrayProperty(java.lang.String name, boolean isTransient, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] valueActions) {
        this.name = name;
        this.isTransient = isTransient;
        this.valueActions = valueActions;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] getValueActions() {
        return valueActions;
    }
    
    public void setValueActions(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] valueActions) {
        this.valueActions = valueActions;
    }
}
