// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class ArrayProperty_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns4_BooleanArrayProperty_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "BooleanArrayProperty");
    private CombinedSerializer ns4_myBooleanArrayProperty_LiteralSerializer;
    private static final javax.xml.namespace.QName ns4_DateArrayProperty_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "DateArrayProperty");
    private CombinedSerializer ns4_myDateArrayProperty_LiteralSerializer;
    private static final javax.xml.namespace.QName ns4_NumberArrayProperty_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "NumberArrayProperty");
    private CombinedSerializer ns4_myNumberArrayProperty_LiteralSerializer;
    private static final javax.xml.namespace.QName ns4_ObjectIdArrayProperty_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ObjectIdArrayProperty");
    private CombinedSerializer ns4_myObjectIdArrayProperty_LiteralSerializer;
    private static final javax.xml.namespace.QName ns4_StringArrayProperty_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "StringArrayProperty");
    private CombinedSerializer ns4_myStringArrayProperty_LiteralSerializer;
    private CombinedSerializer ns4_myArrayProperty_LiteralSerializer;
    
    public ArrayProperty_InterfaceSOAPSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, encodeType, true, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns4_myBooleanArrayProperty_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanArrayProperty.class, ns4_BooleanArrayProperty_TYPE_QNAME);
        ns4_myBooleanArrayProperty_LiteralSerializer = ns4_myBooleanArrayProperty_LiteralSerializer.getInnermostSerializer();
        ns4_myDateArrayProperty_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateArrayProperty.class, ns4_DateArrayProperty_TYPE_QNAME);
        ns4_myDateArrayProperty_LiteralSerializer = ns4_myDateArrayProperty_LiteralSerializer.getInnermostSerializer();
        ns4_myNumberArrayProperty_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberArrayProperty.class, ns4_NumberArrayProperty_TYPE_QNAME);
        ns4_myNumberArrayProperty_LiteralSerializer = ns4_myNumberArrayProperty_LiteralSerializer.getInnermostSerializer();
        ns4_myObjectIdArrayProperty_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty.class, ns4_ObjectIdArrayProperty_TYPE_QNAME);
        ns4_myObjectIdArrayProperty_LiteralSerializer = ns4_myObjectIdArrayProperty_LiteralSerializer.getInnermostSerializer();
        ns4_myStringArrayProperty_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringArrayProperty.class, ns4_StringArrayProperty_TYPE_QNAME);
        ns4_myStringArrayProperty_LiteralSerializer = ns4_myStringArrayProperty_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ArrayProperty");
        CombinedSerializer interfaceSerializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
        ns4_myArrayProperty_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (ns4_myArrayProperty_LiteralSerializer instanceof Initializable) {
            ((Initializable)ns4_myArrayProperty_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(javax.xml.namespace.QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        javax.xml.namespace.QName elementType = getType(reader);
        if (elementType != null && elementType.equals(ns4_myBooleanArrayProperty_LiteralSerializer.getXmlType())) {
            return ns4_myBooleanArrayProperty_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns4_myDateArrayProperty_LiteralSerializer.getXmlType())) {
            return ns4_myDateArrayProperty_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns4_myNumberArrayProperty_LiteralSerializer.getXmlType())) {
            return ns4_myNumberArrayProperty_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns4_myObjectIdArrayProperty_LiteralSerializer.getXmlType())) {
            return ns4_myObjectIdArrayProperty_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns4_myStringArrayProperty_LiteralSerializer.getXmlType())) {
            return ns4_myStringArrayProperty_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(ns4_myArrayProperty_LiteralSerializer.getXmlType())) {
            Object obj = ns4_myArrayProperty_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new Object[] {"", elementType.toString()});
    }
    
    public void doSerializeInstance(java.lang.Object obj, javax.xml.namespace.QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty)obj;
        
        if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanArrayProperty) {
            ns4_myBooleanArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateArrayProperty) {
            ns4_myDateArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberArrayProperty) {
            ns4_myNumberArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty) {
            ns4_myObjectIdArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringArrayProperty) {
            ns4_myStringArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            ns4_myArrayProperty_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
