// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class BasicIdentity_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_RepositoryIdentity_TYPE_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "RepositoryIdentity");
    private CombinedSerializer ns1_myRepositoryIdentity_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_SsoIdentity_TYPE_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "SsoIdentity");
    private CombinedSerializer ns1_mySsoIdentity_LiteralSerializer;
    private CombinedSerializer ns1_myBasicIdentity_LiteralSerializer;
    
    public BasicIdentity_InterfaceSOAPSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, encodeType, true, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myRepositoryIdentity_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RepositoryIdentity.class, ns1_RepositoryIdentity_TYPE_QNAME);
        ns1_myRepositoryIdentity_LiteralSerializer = ns1_myRepositoryIdentity_LiteralSerializer.getInnermostSerializer();
        ns1_mySsoIdentity_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SsoIdentity.class, ns1_SsoIdentity_TYPE_QNAME);
        ns1_mySsoIdentity_LiteralSerializer = ns1_mySsoIdentity_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "BasicIdentity");
        CombinedSerializer interfaceSerializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity_LiteralSerializer(type, "", ENCODE_TYPE);
        ns1_myBasicIdentity_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (ns1_myBasicIdentity_LiteralSerializer instanceof Initializable) {
            ((Initializable)ns1_myBasicIdentity_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(javax.xml.namespace.QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        javax.xml.namespace.QName elementType = getType(reader);
        if (elementType != null && elementType.equals(ns1_myRepositoryIdentity_LiteralSerializer.getXmlType())) {
            return ns1_myRepositoryIdentity_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns1_mySsoIdentity_LiteralSerializer.getXmlType())) {
            return ns1_mySsoIdentity_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(ns1_myBasicIdentity_LiteralSerializer.getXmlType())) {
            Object obj = ns1_myBasicIdentity_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new Object[] {"", elementType.toString()});
    }
    
    public void doSerializeInstance(java.lang.Object obj, javax.xml.namespace.QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity)obj;
        
        if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RepositoryIdentity) {
            ns1_myRepositoryIdentity_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SsoIdentity) {
            ns1_mySsoIdentity_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            ns1_myBasicIdentity_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
