// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class BinaryContent extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content {
    protected byte[] value;
    
    public BinaryContent() {
    }
    
    public BinaryContent(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType renditionType, java.lang.String format, int pageNumber, java.lang.String pageModifier, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode contentTransferMode, byte[] value) {
        this.renditionType = renditionType;
        this.format = format;
        this.pageNumber = pageNumber;
        this.pageModifier = pageModifier;
        this.contentTransferMode = contentTransferMode;
        this.value = value;
    }
    
    public byte[] getValue() {
        return value;
    }
    
    public void setValue(byte[] value) {
        this.value = value;
    }
}
