// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class BooleanProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    protected boolean value;
    
    public BooleanProperty() {
    }
    
    public BooleanProperty(java.lang.String name, boolean isTransient, boolean value) {
        this.name = name;
        this.isTransient = isTransient;
        this.value = value;
    }
    
    public boolean isValue() {
        return value;
    }
    
    public void setValue(boolean value) {
        this.value = value;
    }
}
