// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class CheckoutProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean checkoutOnlyVDMRoot;
    
    public CheckoutProfile() {
    }
    
    public CheckoutProfile(boolean checkoutOnlyVDMRoot) {
        this.checkoutOnlyVDMRoot = checkoutOnlyVDMRoot;
    }
    
    public boolean isCheckoutOnlyVDMRoot() {
        return checkoutOnlyVDMRoot;
    }
    
    public void setCheckoutOnlyVDMRoot(boolean checkoutOnlyVDMRoot) {
        this.checkoutOnlyVDMRoot = checkoutOnlyVDMRoot;
    }
}
