// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class CheckinProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_deleteLocalFileHint_QNAME = new QName("", "deleteLocalFileHint");
    private static final javax.xml.namespace.QName ns1_makeCurrent_QNAME = new QName("", "makeCurrent");
    private static final javax.xml.namespace.QName ns1_checkinOnlyVDMRoot_QNAME = new QName("", "checkinOnlyVDMRoot");
    
    public CheckinProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public CheckinProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_deleteLocalFileHint_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setDeleteLocalFileHint(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_deleteLocalFileHint_QNAME});
        }
        attribute = attributes.getValue(ns1_makeCurrent_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setMakeCurrent(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_makeCurrent_QNAME});
        }
        attribute = attributes.getValue(ns1_checkinOnlyVDMRoot_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setCheckinOnlyVDMRoot(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_checkinOnlyVDMRoot_QNAME});
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile)obj;
        
        if (new Boolean(instance.isDeleteLocalFileHint()) != null) {
            writer.writeAttribute(ns1_deleteLocalFileHint_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isDeleteLocalFileHint()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_deleteLocalFileHint_QNAME});
        }
        if (new Boolean(instance.isMakeCurrent()) != null) {
            writer.writeAttribute(ns1_makeCurrent_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isMakeCurrent()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_makeCurrent_QNAME});
        }
        if (new Boolean(instance.isCheckinOnlyVDMRoot()) != null) {
            writer.writeAttribute(ns1_checkinOnlyVDMRoot_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isCheckinOnlyVDMRoot()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_checkinOnlyVDMRoot_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile)obj;
        
    }
}
