// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ClusteringProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns3_ClusteringStrategies_QNAME = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ClusteringStrategies");
    private static final javax.xml.namespace.QName ns7_ClusteringStrategy_TYPE_QNAME = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "ClusteringStrategy");
    private CombinedSerializer ns7_myClusteringStrategy_LiteralSerializer;
    
    public ClusteringProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ClusteringProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns7_myClusteringStrategy_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy.class, ns7_ClusteringStrategy_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_ClusteringStrategies_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_ClusteringStrategies_QNAME))) {
                    value = ns7_myClusteringStrategy_LiteralSerializer.deserialize(ns3_ClusteringStrategies_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[values.size()];
            member = values.toArray((Object[]) member);
            instance.setClusteringStrategies((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[])member);
        }
        else {
            instance.setClusteringStrategies(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile)obj;
        
        if (instance.getClusteringStrategies() != null) {
            for (int i = 0; i < instance.getClusteringStrategies().length; ++i) {
                ns7_myClusteringStrategy_LiteralSerializer.serialize(instance.getClusteringStrategies()[i], ns3_ClusteringStrategies_QNAME, null, writer, context);
            }
        }
    }
}
