// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ClusteringProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[] clusteringStrategies;
    
    public ClusteringProfile() {
    }
    
    public ClusteringProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[] clusteringStrategies) {
        this.clusteringStrategies = clusteringStrategies;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[] getClusteringStrategies() {
        return clusteringStrategies;
    }
    
    public void setClusteringStrategies(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy[] clusteringStrategies) {
        this.clusteringStrategies = clusteringStrategies;
    }
}
