// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ClusteringStrategy_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_clusteringRange_QNAME = new QName("", "clusteringRange");
    private static final javax.xml.namespace.QName ns1_clusteringThreshold_QNAME = new QName("", "clusteringThreshold");
    private static final javax.xml.namespace.QName ns1_strategyName_QNAME = new QName("", "strategyName");
    private static final javax.xml.namespace.QName ns1_returnIdentitySet_QNAME = new QName("", "returnIdentitySet");
    private static final javax.xml.namespace.QName ns7_attributes_QNAME = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "attributes");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns7_tokenizers_QNAME = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "tokenizers");
    private static final javax.xml.namespace.QName ns6_PropertySet_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "PropertySet");
    private CombinedSerializer ns6_myPropertySet_LiteralSerializer;
    
    public ClusteringStrategy_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ClusteringStrategy_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        ns6_myPropertySet_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet.class, ns6_PropertySet_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_clusteringRange_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setClusteringRange((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange)member);
        }
        attribute = attributes.getValue(ns1_clusteringThreshold_QNAME);
        if (attribute != null) {
            member = XSDIntEncoder.getInstance().stringToObject(attribute, reader);
            instance.setClusteringThreshold(((java.lang.Integer)member).intValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_clusteringThreshold_QNAME});
        }
        attribute = attributes.getValue(ns1_strategyName_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setStrategyName((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_returnIdentitySet_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setReturnIdentitySet(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_returnIdentitySet_QNAME});
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns7_attributes_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns7_attributes_QNAME))) {
                    value = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns7_attributes_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new java.lang.String[values.size()];
            member = values.toArray((Object[]) member);
            instance.setAttributes((java.lang.String[])member);
        }
        else {
            instance.setAttributes(new java.lang.String[0]);
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns7_tokenizers_QNAME)) {
                member = ns6_myPropertySet_LiteralSerializer.deserialize(ns7_tokenizers_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setTokenizers((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy)obj;
        
        if (instance.getClusteringRange() != null) {
            writer.writeAttribute(ns1_clusteringRange_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange_Encoder.getInstance().objectToString(instance.getClusteringRange(), writer));
        }
        if (new java.lang.Integer(instance.getClusteringThreshold()) != null) {
            writer.writeAttribute(ns1_clusteringThreshold_QNAME, XSDIntEncoder.getInstance().objectToString(new java.lang.Integer(instance.getClusteringThreshold()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_clusteringThreshold_QNAME});
        }
        if (instance.getStrategyName() != null) {
            writer.writeAttribute(ns1_strategyName_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getStrategyName(), writer));
        }
        if (new Boolean(instance.isReturnIdentitySet()) != null) {
            writer.writeAttribute(ns1_returnIdentitySet_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isReturnIdentitySet()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_returnIdentitySet_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy)obj;
        
        if (instance.getAttributes() != null) {
            for (int i = 0; i < instance.getAttributes().length; ++i) {
                ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getAttributes()[i], ns7_attributes_QNAME, null, writer, context);
            }
        }
        if (instance.getTokenizers() != null) {
            ns6_myPropertySet_LiteralSerializer.serialize(instance.getTokenizers(), ns7_tokenizers_QNAME, null, writer, context);
        }
    }
}
