// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ClusteringStrategy extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange clusteringRange;
    protected int clusteringThreshold;
    protected java.lang.String strategyName;
    protected boolean returnIdentitySet;
    protected java.lang.String[] attributes;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet tokenizers;
    
    public ClusteringStrategy() {
    }
    
    public ClusteringStrategy(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange clusteringRange, int clusteringThreshold, java.lang.String strategyName, boolean returnIdentitySet, java.lang.String[] attributes, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet tokenizers) {
        this.clusteringRange = clusteringRange;
        this.clusteringThreshold = clusteringThreshold;
        this.strategyName = strategyName;
        this.returnIdentitySet = returnIdentitySet;
        this.attributes = attributes;
        this.tokenizers = tokenizers;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange getClusteringRange() {
        return clusteringRange;
    }
    
    public void setClusteringRange(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange clusteringRange) {
        this.clusteringRange = clusteringRange;
    }
    
    public int getClusteringThreshold() {
        return clusteringThreshold;
    }
    
    public void setClusteringThreshold(int clusteringThreshold) {
        this.clusteringThreshold = clusteringThreshold;
    }
    
    public java.lang.String getStrategyName() {
        return strategyName;
    }
    
    public void setStrategyName(java.lang.String strategyName) {
        this.strategyName = strategyName;
    }
    
    public boolean isReturnIdentitySet() {
        return returnIdentitySet;
    }
    
    public void setReturnIdentitySet(boolean returnIdentitySet) {
        this.returnIdentitySet = returnIdentitySet;
    }
    
    public java.lang.String[] getAttributes() {
        return attributes;
    }
    
    public void setAttributes(java.lang.String[] attributes) {
        this.attributes = attributes;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet getTokenizers() {
        return tokenizers;
    }
    
    public void setTokenizers(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet tokenizers) {
        this.tokenizers = tokenizers;
    }
}
