// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class ClusteringRange {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _LOWString = "LOW";
    public static final java.lang.String _MEDIUMString = "MEDIUM";
    public static final java.lang.String _HIGHString = "HIGH";
    
    public static final java.lang.String _LOW = new java.lang.String(_LOWString);
    public static final java.lang.String _MEDIUM = new java.lang.String(_MEDIUMString);
    public static final java.lang.String _HIGH = new java.lang.String(_HIGHString);
    
    public static final ClusteringRange LOW = new ClusteringRange(_LOW);
    public static final ClusteringRange MEDIUM = new ClusteringRange(_MEDIUM);
    public static final ClusteringRange HIGH = new ClusteringRange(_HIGH);
    
    protected ClusteringRange(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ClusteringRange fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (LOW.value.equals(value)) {
            return LOW;
        } else if (MEDIUM.value.equals(value)) {
            return MEDIUM;
        } else if (HIGH.value.equals(value)) {
            return HIGH;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ClusteringRange fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ClusteringRange ret = (ClusteringRange)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_LOWString)) {
            return LOW;
        } else if (value.equals(_MEDIUMString)) {
            return MEDIUM;
        } else if (value.equals(_HIGHString)) {
            return HIGH;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ClusteringRange)) {
            return false;
        }
        return ((ClusteringRange)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
