// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class Content {
    protected java.lang.String format;
    protected int pageNumber;
    protected java.lang.String pageModifier;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode contentTransferMode;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType renditionType;
    
    public Content() {
    }
    
    public Content(java.lang.String format, int pageNumber, java.lang.String pageModifier, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode contentTransferMode, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType renditionType) {
        this.format = format;
        this.pageNumber = pageNumber;
        this.pageModifier = pageModifier;
        this.contentTransferMode = contentTransferMode;
        this.renditionType = renditionType;
    }
    
    public java.lang.String getFormat() {
        return format;
    }
    
    public void setFormat(java.lang.String format) {
        this.format = format;
    }
    
    public int getPageNumber() {
        return pageNumber;
    }
    
    public void setPageNumber(int pageNumber) {
        this.pageNumber = pageNumber;
    }
    
    public java.lang.String getPageModifier() {
        return pageModifier;
    }
    
    public void setPageModifier(java.lang.String pageModifier) {
        this.pageModifier = pageModifier;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode getContentTransferMode() {
        return contentTransferMode;
    }
    
    public void setContentTransferMode(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode contentTransferMode) {
        this.contentTransferMode = contentTransferMode;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType getRenditionType() {
        return renditionType;
    }
    
    public void setRenditionType(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType renditionType) {
        this.renditionType = renditionType;
    }
}
