// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ContentProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_formatFilter_QNAME = new QName("", "formatFilter");
    private static final javax.xml.namespace.QName ns1_format_QNAME = new QName("", "format");
    private static final javax.xml.namespace.QName ns1_pageFilter_QNAME = new QName("", "pageFilter");
    private static final javax.xml.namespace.QName ns1_pageNumber_QNAME = new QName("", "pageNumber");
    private static final javax.xml.namespace.QName ns1_pageModifierFilter_QNAME = new QName("", "pageModifierFilter");
    private static final javax.xml.namespace.QName ns1_pageModifier_QNAME = new QName("", "pageModifier");
    private static final javax.xml.namespace.QName ns1_contentReturnType_QNAME = new QName("", "contentReturnType");
    private static final javax.xml.namespace.QName ns1_postTransferAction_QNAME = new QName("", "postTransferAction");
    
    public ContentProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ContentProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_formatFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setFormatFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter)member);
        }
        attribute = attributes.getValue(ns1_format_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setFormat((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_pageFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setPageFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter)member);
        }
        attribute = attributes.getValue(ns1_pageNumber_QNAME);
        if (attribute != null) {
            member = XSDIntEncoder.getInstance().stringToObject(attribute, reader);
            instance.setPageNumber(((java.lang.Integer)member).intValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_pageNumber_QNAME});
        }
        attribute = attributes.getValue(ns1_pageModifierFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setPageModifierFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter)member);
        }
        attribute = attributes.getValue(ns1_pageModifier_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setPageModifier((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_contentReturnType_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setContentReturnType((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_postTransferAction_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setPostTransferAction((java.lang.String)member);
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile)obj;
        
        if (instance.getFormatFilter() != null) {
            writer.writeAttribute(ns1_formatFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter_Encoder.getInstance().objectToString(instance.getFormatFilter(), writer));
        }
        if (instance.getFormat() != null) {
            writer.writeAttribute(ns1_format_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getFormat(), writer));
        }
        if (instance.getPageFilter() != null) {
            writer.writeAttribute(ns1_pageFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter_Encoder.getInstance().objectToString(instance.getPageFilter(), writer));
        }
        if (new java.lang.Integer(instance.getPageNumber()) != null) {
            writer.writeAttribute(ns1_pageNumber_QNAME, XSDIntEncoder.getInstance().objectToString(new java.lang.Integer(instance.getPageNumber()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_pageNumber_QNAME});
        }
        if (instance.getPageModifierFilter() != null) {
            writer.writeAttribute(ns1_pageModifierFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter_Encoder.getInstance().objectToString(instance.getPageModifierFilter(), writer));
        }
        if (instance.getPageModifier() != null) {
            writer.writeAttribute(ns1_pageModifier_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getPageModifier(), writer));
        }
        if (instance.getContentReturnType() != null) {
            writer.writeAttribute(ns1_contentReturnType_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getContentReturnType(), writer));
        }
        if (instance.getPostTransferAction() != null) {
            writer.writeAttribute(ns1_postTransferAction_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getPostTransferAction(), writer));
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile)obj;
        
    }
}
