// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class ContextRegistryService_Impl extends com.sun.xml.rpc.client.BasicService implements ContextRegistryService {
    private static final QName serviceName = new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryService");
    private static final QName ns1_ContextRegistryServicePort_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryServicePort");
    private static final Class contextRegistryServicePort_PortClass = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryServicePort.class;
    
    public ContextRegistryService_Impl() {
        super(serviceName, new QName[] {
                        ns1_ContextRegistryServicePort_QNAME
                    },
            new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_ContextRegistryServicePort_QNAME) &&
                serviceDefInterface.equals(contextRegistryServicePort_PortClass)) {
                return getContextRegistryServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(contextRegistryServicePort_PortClass)) {
                return getContextRegistryServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryServicePort getContextRegistryServicePort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_ContextRegistryServicePort_QNAME));
        handlerChain.setRoles(roles);
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryServicePort_Stub stub = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryServicePort_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
