// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

public interface ContextRegistryServicePort extends java.rmi.Remote {
    public java.lang.String register(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext context, java.lang.String host) throws 
         java.rmi.RemoteException;
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext lookup(java.lang.String token) throws 
         java.rmi.RemoteException;
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse unregister(java.lang.String token) throws 
         java.rmi.RemoteException;
}
