// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;

import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

import org.apache.log4j.Logger;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.services.darts.DartsConfiguration;
import uk.gov.courtservice.xhibit.business.services.darts.DartsException;
import uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.DARTSService.DARTSServicePort_Stub;


public class ContextRegistryServicePort_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContextRegistryServicePort {
    
    private DartsConfiguration config;
    private static final Logger log = CSServices.getLogger(ContextRegistryServicePort_Stub.class);
    
    /*
     *  public constructor
     */
    public ContextRegistryServicePort_Stub(HandlerChain handlerChain) {
        super(handlerChain);

        
        String connectionString = null;
        try {
            config = DartsConfiguration.getInstance();
            connectionString = config.getProperty("darts.contextRoot") + "/darts/runtime/ContextRegistryService";
            if ( log.isDebugEnabled()){ 
                log.debug("Connection to Context Registry service using following to establish connection : " + connectionString);
            }
        } catch (DartsException e) {
            log.error("Could not connect to DARTS configuration: Context Registry service endpoint defaulted to unknown value.");
            connectionString = "http://<UNKNOWN_SERVER>:<UNKNOWN_PORT>/darts/runtime/ContextRegistryService";
        }
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, connectionString);
    }
    
    
    /*
     *  implementation of register
     */
    public java.lang.String register(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext context, java.lang.String host)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(register_OPCODE);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Register _myRegister = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Register();
            _myRegister.setContext(context);
            _myRegister.setHost(host);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_register_register_QNAME);
            _bodyBlock.setValue(_myRegister);
            _bodyBlock.setSerializer(ns1_myRegister_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse)_responseObj;
            }
            
            return _result.get_return();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of unregister
     */
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse unregister(java.lang.String token)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(unregister_OPCODE);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Unregister _myUnregister = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Unregister();
            _myUnregister.setToken(token);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_unregister_unregister_QNAME);
            _bodyBlock.setValue(_myUnregister);
            _bodyBlock.setSerializer(ns1_myUnregister_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse)_responseObj;
            }
            
            return _result;
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    /*
     *  implementation of lookup
     */
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext lookup(java.lang.String token)
        throws java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(lookup_OPCODE);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Lookup _myLookup = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Lookup();
            _myLookup.setToken(token);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_lookup_lookup_QNAME);
            _bodyBlock.setValue(_myLookup);
            _bodyBlock.setSerializer(ns1_myLookup_LiteralSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse _result = null;
            java.lang.Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse)((SOAPDeserializationState) _responseObj).getInstance();
            } else {
                _result = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse)_responseObj;
            }
            
            return _result.get_return();
            
        } catch (RemoteException e) {
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case register_OPCODE:
                _deserialize_register(bodyReader, deserializationContext, state);
                break;
            case unregister_OPCODE:
                _deserialize_unregister(bodyReader, deserializationContext, state);
                break;
            case lookup_OPCODE:
                _deserialize_lookup(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the register operation.
     */
    private void _deserialize_register(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myRegisterResponseObj =
            ns1_myRegisterResponse_LiteralSerializer.deserialize(ns1_register_registerResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_register_registerResponse_QNAME);
        bodyBlock.setValue(myRegisterResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the unregister operation.
     */
    private void _deserialize_unregister(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myUnregisterResponseObj =
            ns1_myUnregisterResponse_LiteralSerializer.deserialize(ns1_unregister_unregisterResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_unregister_unregisterResponse_QNAME);
        bodyBlock.setValue(myUnregisterResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     * This method deserializes the body of the lookup operation.
     */
    private void _deserialize_lookup(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myLookupResponseObj =
            ns1_myLookupResponse_LiteralSerializer.deserialize(ns1_lookup_lookupResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_lookup_lookupResponse_QNAME);
        bodyBlock.setValue(myLookupResponseObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    
    
    protected java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return null;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myUnregister_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Unregister.class, ns1_unregister_TYPE_QNAME);
        ns1_myUnregisterResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse.class, ns1_unregisterResponse_TYPE_QNAME);
        ns1_myLookupResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse.class, ns1_lookupResponse_TYPE_QNAME);
        ns1_myLookup_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Lookup.class, ns1_lookup_TYPE_QNAME);
        ns1_myRegister_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Register.class, ns1_register_TYPE_QNAME);
        ns1_myRegisterResponse_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse.class, ns1_registerResponse_TYPE_QNAME);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryServicePort");
    private static final int register_OPCODE = 0;
    private static final int unregister_OPCODE = 1;
    private static final int lookup_OPCODE = 2;
    private static final javax.xml.namespace.QName ns1_register_register_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "register");
    private static final javax.xml.namespace.QName ns1_register_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "register");
    private CombinedSerializer ns1_myRegister_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_register_registerResponse_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "registerResponse");
    private static final javax.xml.namespace.QName ns1_registerResponse_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "registerResponse");
    private CombinedSerializer ns1_myRegisterResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_unregister_unregister_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "unregister");
    private static final javax.xml.namespace.QName ns1_unregister_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "unregister");
    private CombinedSerializer ns1_myUnregister_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_unregister_unregisterResponse_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "unregisterResponse");
    private static final javax.xml.namespace.QName ns1_unregisterResponse_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "unregisterResponse");
    private CombinedSerializer ns1_myUnregisterResponse_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_lookup_lookup_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "lookup");
    private static final javax.xml.namespace.QName ns1_lookup_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "lookup");
    private CombinedSerializer ns1_myLookup_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_lookup_lookupResponse_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "lookupResponse");
    private static final javax.xml.namespace.QName ns1_lookupResponse_TYPE_QNAME = new QName("http://services.rt.fs.documentum.emc.com/", "lookupResponse");
    private CombinedSerializer ns1_myLookupResponse_LiteralSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://services.rt.fs.documentum.emc.com/"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
