// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ContentProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter formatFilter;
    protected java.lang.String format;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter pageFilter;
    protected int pageNumber;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter pageModifierFilter;
    protected java.lang.String pageModifier;
    protected java.lang.String contentReturnType;
    protected java.lang.String postTransferAction;
    
    public ContentProfile() {
    }
    
    public ContentProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter formatFilter, java.lang.String format, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter pageFilter, int pageNumber, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter pageModifierFilter, java.lang.String pageModifier, java.lang.String contentReturnType, java.lang.String postTransferAction) {
        this.formatFilter = formatFilter;
        this.format = format;
        this.pageFilter = pageFilter;
        this.pageNumber = pageNumber;
        this.pageModifierFilter = pageModifierFilter;
        this.pageModifier = pageModifier;
        this.contentReturnType = contentReturnType;
        this.postTransferAction = postTransferAction;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter getFormatFilter() {
        return formatFilter;
    }
    
    public void setFormatFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter formatFilter) {
        this.formatFilter = formatFilter;
    }
    
    public java.lang.String getFormat() {
        return format;
    }
    
    public void setFormat(java.lang.String format) {
        this.format = format;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter getPageFilter() {
        return pageFilter;
    }
    
    public void setPageFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter pageFilter) {
        this.pageFilter = pageFilter;
    }
    
    public int getPageNumber() {
        return pageNumber;
    }
    
    public void setPageNumber(int pageNumber) {
        this.pageNumber = pageNumber;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter getPageModifierFilter() {
        return pageModifierFilter;
    }
    
    public void setPageModifierFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter pageModifierFilter) {
        this.pageModifierFilter = pageModifierFilter;
    }
    
    public java.lang.String getPageModifier() {
        return pageModifier;
    }
    
    public void setPageModifier(java.lang.String pageModifier) {
        this.pageModifier = pageModifier;
    }
    
    public java.lang.String getContentReturnType() {
        return contentReturnType;
    }
    
    public void setContentReturnType(java.lang.String contentReturnType) {
        this.contentReturnType = contentReturnType;
    }
    
    public java.lang.String getPostTransferAction() {
        return postTransferAction;
    }
    
    public void setPostTransferAction(java.lang.String postTransferAction) {
        this.postTransferAction = postTransferAction;
    }
}
