// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class ContextRegistryService_SerializerRegistry implements SerializerConstants {
    public ContextRegistryService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "SchemaProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SchemaProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SchemaProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ContentProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PageFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "CheckinProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckinProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://core.datamodel.fs.documentum.emc.com/", "VersionStrategy");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "ActivityInfo");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo.class, type, serializer);
        }
        {
            QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "RepositoryIdentity");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RepositoryIdentity_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RepositoryIdentity.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "CopyProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PermissionTypeFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "DepthFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://core.datamodel.fs.documentum.emc.com/", "RichText");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "NumberProperty");
            CombinedSerializer serializer = new LiteralFragmentSerializer(type, NULLABLE, "");
            registerSerializer(mapping2,javax.xml.soap.SOAPElement.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "TargetRoleFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "RichTextProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "PropertySet");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "RichTextProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://core.datamodel.fs.documentum.emc.com/", "ObjectId");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty_InterfaceSOAPSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "FormatFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.FormatFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "LifecycleExecutionProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LifecycleExecutionProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LifecycleExecutionProfile.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(SchemaConstants.QNAME_TYPE_BASE64_BINARY,
                "", XSDBase64BinaryEncoder.getInstance());
            registerSerializer(mapping2,byte[].class, SchemaConstants.QNAME_TYPE_BASE64_BINARY, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "SearchProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SearchProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SearchProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ValueActionType");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ListUpdateMethod");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "DateProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "RenditionType");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "StringArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "NumberProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://core.datamodel.fs.documentum.emc.com/", "PermissionType");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ObjectIdArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PermissionProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "UcfContent");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "StringProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.StringProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ValueAction");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "unregisterResponse");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UnregisterResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ContentTransferProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "CheckoutProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckoutProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CheckoutProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "BooleanProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "DateArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DateArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "Property");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "lookup");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Lookup_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Lookup.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "UrlContent");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UrlContent_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UrlContent.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "DeleteVersionStrategy");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DeleteVersionStrategy_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DeleteVersionStrategy.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "MoveProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.MoveProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.MoveProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "DeleteProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DeleteProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DeleteProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "unregister");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Unregister_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Unregister.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "Content");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "RelationshipProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PropertyProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "register");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Register_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Register.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "ContentTransferMode");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode.class, type, serializer);
        }
        {
            QName type = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "ClusteringRange");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringRange.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "RelationshipNameFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "Identity");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity.class, type, serializer);
        }
        {
            QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "BasicIdentity");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity_InterfaceSOAPSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "DataHandlerContent");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DataHandlerContent_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DataHandlerContent.class, type, serializer);
        }
        {
            QName type = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "BinaryContent");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BinaryContent_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BinaryContent.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "VdmUpdateProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VdmUpdateProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VdmUpdateProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "Profile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "VdmRetrieveProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VdmRetrieveProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VdmRetrieveProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "ServiceContext");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PageModifierFilter");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PageModifierFilter.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "PropertyFilterMode");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode.class, type, serializer);
        }
        {
            QName type = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "ClusteringStrategy");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "NumberArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.NumberArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "NumberArrayProperty");
            CombinedSerializer serializer = new LiteralFragmentSerializer(type, NULLABLE, "");
            registerSerializer(mapping2,javax.xml.soap.SOAPElement.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "BooleanArrayProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanArrayProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BooleanArrayProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "SsoIdentity");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SsoIdentity_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.SsoIdentity.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ResultDataMode");
            CombinedSerializer serializer = new LiteralSimpleTypeSerializer(type, "",
                uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode_Encoder.getInstance());
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "registerResponse");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RegisterResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ObjectIdProperty");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdProperty_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdProperty.class, type, serializer);
        }
        {
            QName type = new QName("http://services.rt.fs.documentum.emc.com/", "lookupResponse");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.LookupResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ClusteringProfile");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringProfile.class, type, serializer);
        }
        {
            QName type = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "GroupingStrategy");
            CombinedSerializer serializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2,uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
