// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class CopyProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_nonCurrentObjectAllowed_QNAME = new QName("", "nonCurrentObjectAllowed");
    private static final javax.xml.namespace.QName ns1_deepCopyFolders_QNAME = new QName("", "deepCopyFolders");
    private static final javax.xml.namespace.QName ns1_copyOnlyVDMRoot_QNAME = new QName("", "copyOnlyVDMRoot");
    private static final javax.xml.namespace.QName ns1_leaveAssemblies_QNAME = new QName("", "leaveAssemblies");
    private static final javax.xml.namespace.QName ns1_leaveRelationships_QNAME = new QName("", "leaveRelationships");
    private static final javax.xml.namespace.QName ns1_copyChildrenAsReferences_QNAME = new QName("", "copyChildrenAsReferences");
    
    public CopyProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public CopyProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_nonCurrentObjectAllowed_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setNonCurrentObjectAllowed(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_nonCurrentObjectAllowed_QNAME});
        }
        attribute = attributes.getValue(ns1_deepCopyFolders_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setDeepCopyFolders(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_deepCopyFolders_QNAME});
        }
        attribute = attributes.getValue(ns1_copyOnlyVDMRoot_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setCopyOnlyVDMRoot(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_copyOnlyVDMRoot_QNAME});
        }
        attribute = attributes.getValue(ns1_leaveAssemblies_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setLeaveAssemblies(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_leaveAssemblies_QNAME});
        }
        attribute = attributes.getValue(ns1_leaveRelationships_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setLeaveRelationships(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_leaveRelationships_QNAME});
        }
        attribute = attributes.getValue(ns1_copyChildrenAsReferences_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setCopyChildrenAsReferences(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_copyChildrenAsReferences_QNAME});
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile)obj;
        
        if (new Boolean(instance.isNonCurrentObjectAllowed()) != null) {
            writer.writeAttribute(ns1_nonCurrentObjectAllowed_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isNonCurrentObjectAllowed()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_nonCurrentObjectAllowed_QNAME});
        }
        if (new Boolean(instance.isDeepCopyFolders()) != null) {
            writer.writeAttribute(ns1_deepCopyFolders_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isDeepCopyFolders()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_deepCopyFolders_QNAME});
        }
        if (new Boolean(instance.isCopyOnlyVDMRoot()) != null) {
            writer.writeAttribute(ns1_copyOnlyVDMRoot_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isCopyOnlyVDMRoot()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_copyOnlyVDMRoot_QNAME});
        }
        if (new Boolean(instance.isLeaveAssemblies()) != null) {
            writer.writeAttribute(ns1_leaveAssemblies_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isLeaveAssemblies()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_leaveAssemblies_QNAME});
        }
        if (new Boolean(instance.isLeaveRelationships()) != null) {
            writer.writeAttribute(ns1_leaveRelationships_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isLeaveRelationships()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_leaveRelationships_QNAME});
        }
        if (new Boolean(instance.isCopyChildrenAsReferences()) != null) {
            writer.writeAttribute(ns1_copyChildrenAsReferences_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isCopyChildrenAsReferences()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_copyChildrenAsReferences_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.CopyProfile)obj;
        
    }
}
