// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class DateProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    protected java.util.Calendar value;
    
    public DateProperty() {
    }
    
    public DateProperty(java.lang.String name, boolean isTransient, java.util.Calendar value) {
        this.name = name;
        this.isTransient = isTransient;
        this.value = value;
    }
    
    public java.util.Calendar getValue() {
        return value;
    }
    
    public void setValue(java.util.Calendar value) {
        this.value = value;
    }
}
