// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class DateArrayProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty {
    protected java.util.Calendar[] values;
    
    public DateArrayProperty() {
    }
    
    public DateArrayProperty(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] valueActions, java.lang.String name, boolean isTransient, java.util.Calendar[] values) {
        this.valueActions = valueActions;
        this.name = name;
        this.isTransient = isTransient;
        this.values = values;
    }
    
    public java.util.Calendar[] getValues() {
        return values;
    }
    
    public void setValues(java.util.Calendar[] values) {
        this.values = values;
    }
}
