// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import com.sun.xml.rpc.encoding.simpletype.*;
import javax.xml.namespace.QName;
import com.sun.xml.rpc.streaming.*;

public class DepthFilter_Encoder extends SimpleTypeEncoderBase {
    
    private static final SimpleTypeEncoder encoder = XSDStringEncoder.getInstance();
    private static final DepthFilter_Encoder instance = new DepthFilter_Encoder();
    
    private DepthFilter_Encoder() {
    }
    
    public static SimpleTypeEncoder getInstance() {
        return instance;
    }
    
    public java.lang.String objectToString(java.lang.Object obj, XMLWriter writer) throws java.lang.Exception {
        java.lang.String value = ((DepthFilter)obj).getValue();
        return encoder.objectToString(value, writer);
    }
    
    public java.lang.Object stringToObject(java.lang.String str, XMLReader reader) throws java.lang.Exception {
        return DepthFilter.fromValue((java.lang.String)encoder.stringToObject(str, reader));
    }
    
}
