// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class GroupingStrategy_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns3_ClusteringStrategy_TYPE_QNAME = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "ClusteringStrategy");
    private CombinedSerializer ns3_myClusteringStrategy_LiteralSerializer;
    private CombinedSerializer ns3_myGroupingStrategy_LiteralSerializer;
    
    public GroupingStrategy_InterfaceSOAPSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, encodeType, true, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myClusteringStrategy_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy.class, ns3_ClusteringStrategy_TYPE_QNAME);
        ns3_myClusteringStrategy_LiteralSerializer = ns3_myClusteringStrategy_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://query.core.datamodel.fs.documentum.emc.com/", "GroupingStrategy");
        CombinedSerializer interfaceSerializer = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
        ns3_myGroupingStrategy_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (ns3_myGroupingStrategy_LiteralSerializer instanceof Initializable) {
            ((Initializable)ns3_myGroupingStrategy_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(javax.xml.namespace.QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        javax.xml.namespace.QName elementType = getType(reader);
        if (elementType != null && elementType.equals(ns3_myClusteringStrategy_LiteralSerializer.getXmlType())) {
            return ns3_myClusteringStrategy_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(ns3_myGroupingStrategy_LiteralSerializer.getXmlType())) {
            Object obj = ns3_myGroupingStrategy_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new Object[] {"", elementType.toString()});
    }
    
    public void doSerializeInstance(java.lang.Object obj, javax.xml.namespace.QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.GroupingStrategy)obj;
        
        if (obj instanceof uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ClusteringStrategy) {
            ns3_myClusteringStrategy_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            ns3_myGroupingStrategy_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
