// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class ListUpdateMethod {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _REPLACEString = "REPLACE";
    public static final java.lang.String _MERGEString = "MERGE";
    
    public static final java.lang.String _REPLACE = new java.lang.String(_REPLACEString);
    public static final java.lang.String _MERGE = new java.lang.String(_MERGEString);
    
    public static final ListUpdateMethod REPLACE = new ListUpdateMethod(_REPLACE);
    public static final ListUpdateMethod MERGE = new ListUpdateMethod(_MERGE);
    
    protected ListUpdateMethod(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ListUpdateMethod fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (REPLACE.value.equals(value)) {
            return REPLACE;
        } else if (MERGE.value.equals(value)) {
            return MERGE;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ListUpdateMethod fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ListUpdateMethod ret = (ListUpdateMethod)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_REPLACEString)) {
            return REPLACE;
        } else if (value.equals(_MERGEString)) {
            return MERGE;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ListUpdateMethod)) {
            return false;
        }
        return ((ListUpdateMethod)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
