// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class Lookup {
    protected java.lang.String token;
    
    public Lookup() {
    }
    
    public Lookup(java.lang.String token) {
        this.token = token;
    }
    
    public java.lang.String getToken() {
        return token;
    }
    
    public void setToken(java.lang.String token) {
        this.token = token;
    }
}
