// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class MoveProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean isNonCurrentObjectAllowed;
    
    public MoveProfile() {
    }
    
    public MoveProfile(boolean isNonCurrentObjectAllowed) {
        this.isNonCurrentObjectAllowed = isNonCurrentObjectAllowed;
    }
    
    public boolean isIsNonCurrentObjectAllowed() {
        return isNonCurrentObjectAllowed;
    }
    
    public void setIsNonCurrentObjectAllowed(boolean isNonCurrentObjectAllowed) {
        this.isNonCurrentObjectAllowed = isNonCurrentObjectAllowed;
    }
}
