// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class NumberProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    
    public NumberProperty() {
    }
    
    public NumberProperty(java.lang.String name, boolean isTransient) {
        this.name = name;
        this.isTransient = isTransient;
    }
}
