// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ObjectIdProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId value;
    
    public ObjectIdProperty() {
    }
    
    public ObjectIdProperty(java.lang.String name, boolean isTransient, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId value) {
        this.name = name;
        this.isTransient = isTransient;
        this.value = value;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId getValue() {
        return value;
    }
    
    public void setValue(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId value) {
        this.value = value;
    }
}
