// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ObjectIdArrayProperty_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_name_QNAME = new QName("", "name");
    private static final javax.xml.namespace.QName ns1_isTransient_QNAME = new QName("", "isTransient");
    private static final javax.xml.namespace.QName ns6_ValueActions_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ValueActions");
    private static final javax.xml.namespace.QName ns6_ValueAction_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "ValueAction");
    private CombinedSerializer ns6_myValueAction_LiteralSerializer;
    private static final javax.xml.namespace.QName ns6_Values_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "Values");
    private static final javax.xml.namespace.QName ns4_ObjectId_TYPE_QNAME = new QName("http://core.datamodel.fs.documentum.emc.com/", "ObjectId");
    private CombinedSerializer ns4_myObjectId_LiteralSerializer;
    
    public ObjectIdArrayProperty_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ObjectIdArrayProperty_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns6_myValueAction_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction.class, ns6_ValueAction_TYPE_QNAME);
        ns4_myObjectId_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId.class, ns4_ObjectId_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_name_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setName((java.lang.String)member);
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_name_QNAME});
        }
        attribute = attributes.getValue(ns1_isTransient_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setIsTransient(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_isTransient_QNAME});
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_ValueActions_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_ValueActions_QNAME))) {
                    value = ns6_myValueAction_LiteralSerializer.deserialize(ns6_ValueActions_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[values.size()];
            member = values.toArray((Object[]) member);
            instance.setValueActions((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[])member);
        }
        else {
            instance.setValueActions(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[0]);
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_Values_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_Values_QNAME))) {
                    value = ns4_myObjectId_LiteralSerializer.deserialize(ns6_Values_QNAME, reader, context);
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[values.size()];
            member = values.toArray((Object[]) member);
            instance.setValues((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[])member);
        }
        else if(!(reader.getState() == XMLReader.END)) {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty)obj;
        
        if (instance.getName() != null) {
            writer.writeAttribute(ns1_name_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getName(), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_name_QNAME});
        }
        if (new Boolean(instance.isIsTransient()) != null) {
            writer.writeAttribute(ns1_isTransient_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isIsTransient()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_isTransient_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectIdArrayProperty)obj;
        
        if (instance.getValueActions() != null) {
            for (int i = 0; i < instance.getValueActions().length; ++i) {
                ns6_myValueAction_LiteralSerializer.serialize(instance.getValueActions()[i], ns6_ValueActions_QNAME, null, writer, context);
            }
        }
        if (instance.getValues() != null) {
            for (int i = 0; i < instance.getValues().length; ++i) {
                ns4_myObjectId_LiteralSerializer.serialize(instance.getValues()[i], ns6_Values_QNAME, null, writer, context);
            }
        }
    }
}
