// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ObjectIdArrayProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ArrayProperty {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[] values;
    
    public ObjectIdArrayProperty() {
    }
    
    public ObjectIdArrayProperty(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueAction[] valueActions, java.lang.String name, boolean isTransient, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[] values) {
        this.valueActions = valueActions;
        this.name = name;
        this.isTransient = isTransient;
        this.values = values;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[] getValues() {
        return values;
    }
    
    public void setValues(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ObjectId[] values) {
        this.values = values;
    }
}
