// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class PermissionProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter permissionTypeFilter;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType permissionType;
    protected boolean isUseCompoundPermissions;
    
    public PermissionProfile() {
    }
    
    public PermissionProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter permissionTypeFilter, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType permissionType, boolean isUseCompoundPermissions) {
        this.permissionTypeFilter = permissionTypeFilter;
        this.permissionType = permissionType;
        this.isUseCompoundPermissions = isUseCompoundPermissions;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter getPermissionTypeFilter() {
        return permissionTypeFilter;
    }
    
    public void setPermissionTypeFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter permissionTypeFilter) {
        this.permissionTypeFilter = permissionTypeFilter;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType getPermissionType() {
        return permissionType;
    }
    
    public void setPermissionType(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType permissionType) {
        this.permissionType = permissionType;
    }
    
    public boolean isIsUseCompoundPermissions() {
        return isUseCompoundPermissions;
    }
    
    public void setIsUseCompoundPermissions(boolean isUseCompoundPermissions) {
        this.isUseCompoundPermissions = isUseCompoundPermissions;
    }
}
