// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class PermissionType {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _BASICString = "BASIC";
    public static final java.lang.String _EXTENDEDString = "EXTENDED";
    public static final java.lang.String _CUSTOMString = "CUSTOM";
    
    public static final java.lang.String _BASIC = new java.lang.String(_BASICString);
    public static final java.lang.String _EXTENDED = new java.lang.String(_EXTENDEDString);
    public static final java.lang.String _CUSTOM = new java.lang.String(_CUSTOMString);
    
    public static final PermissionType BASIC = new PermissionType(_BASIC);
    public static final PermissionType EXTENDED = new PermissionType(_EXTENDED);
    public static final PermissionType CUSTOM = new PermissionType(_CUSTOM);
    
    protected PermissionType(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static PermissionType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (BASIC.value.equals(value)) {
            return BASIC;
        } else if (EXTENDED.value.equals(value)) {
            return EXTENDED;
        } else if (CUSTOM.value.equals(value)) {
            return CUSTOM;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static PermissionType fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        PermissionType ret = (PermissionType)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_BASICString)) {
            return BASIC;
        } else if (value.equals(_EXTENDEDString)) {
            return EXTENDED;
        } else if (value.equals(_CUSTOMString)) {
            return CUSTOM;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PermissionType)) {
            return false;
        }
        return ((PermissionType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
