// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class PermissionProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_permissionTypeFilter_QNAME = new QName("", "permissionTypeFilter");
    private static final javax.xml.namespace.QName ns1_permissionType_QNAME = new QName("", "permissionType");
    private static final javax.xml.namespace.QName ns1_isUseCompoundPermissions_QNAME = new QName("", "isUseCompoundPermissions");
    
    public PermissionProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public PermissionProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_permissionTypeFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setPermissionTypeFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter)member);
        }
        attribute = attributes.getValue(ns1_permissionType_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setPermissionType((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType)member);
        }
        attribute = attributes.getValue(ns1_isUseCompoundPermissions_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setIsUseCompoundPermissions(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_isUseCompoundPermissions_QNAME});
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile)obj;
        
        if (instance.getPermissionTypeFilter() != null) {
            writer.writeAttribute(ns1_permissionTypeFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionTypeFilter_Encoder.getInstance().objectToString(instance.getPermissionTypeFilter(), writer));
        }
        if (instance.getPermissionType() != null) {
            writer.writeAttribute(ns1_permissionType_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionType_Encoder.getInstance().objectToString(instance.getPermissionType(), writer));
        }
        if (new Boolean(instance.isIsUseCompoundPermissions()) != null) {
            writer.writeAttribute(ns1_isUseCompoundPermissions_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isIsUseCompoundPermissions()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_isUseCompoundPermissions_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PermissionProfile)obj;
        
    }
}
