// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class PropertyProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode filterMode;
    protected boolean isProcessIncludedUnknown;
    protected java.lang.String[] includeProperties;
    protected java.lang.String[] excludeProperties;
    
    public PropertyProfile() {
    }
    
    public PropertyProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode filterMode, boolean isProcessIncludedUnknown, java.lang.String[] includeProperties, java.lang.String[] excludeProperties) {
        this.filterMode = filterMode;
        this.isProcessIncludedUnknown = isProcessIncludedUnknown;
        this.includeProperties = includeProperties;
        this.excludeProperties = excludeProperties;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode getFilterMode() {
        return filterMode;
    }
    
    public void setFilterMode(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode filterMode) {
        this.filterMode = filterMode;
    }
    
    public boolean isIsProcessIncludedUnknown() {
        return isProcessIncludedUnknown;
    }
    
    public void setIsProcessIncludedUnknown(boolean isProcessIncludedUnknown) {
        this.isProcessIncludedUnknown = isProcessIncludedUnknown;
    }
    
    public java.lang.String[] getIncludeProperties() {
        return includeProperties;
    }
    
    public void setIncludeProperties(java.lang.String[] includeProperties) {
        this.includeProperties = includeProperties;
    }
    
    public java.lang.String[] getExcludeProperties() {
        return excludeProperties;
    }
    
    public void setExcludeProperties(java.lang.String[] excludeProperties) {
        this.excludeProperties = excludeProperties;
    }
}
