// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class Property {
    protected java.lang.String name;
    protected boolean isTransient;
    
    public Property() {
    }
    
    public Property(java.lang.String name, boolean isTransient) {
        this.name = name;
        this.isTransient = isTransient;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public boolean isIsTransient() {
        return isTransient;
    }
    
    public void setIsTransient(boolean isTransient) {
        this.isTransient = isTransient;
    }
}
