// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class PropertySet {
    protected boolean isInternal;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[] properties;
    
    public PropertySet() {
    }
    
    public PropertySet(boolean isInternal, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[] properties) {
        this.isInternal = isInternal;
        this.properties = properties;
    }
    
    public boolean isIsInternal() {
        return isInternal;
    }
    
    public void setIsInternal(boolean isInternal) {
        this.isInternal = isInternal;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[] getProperties() {
        return properties;
    }
    
    public void setProperties(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[] properties) {
        this.properties = properties;
    }
}
