// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class PropertySet_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_isInternal_QNAME = new QName("", "isInternal");
    private static final javax.xml.namespace.QName ns6_Properties_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "Properties");
    private static final javax.xml.namespace.QName ns6_Property_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "Property");
    private CombinedSerializer ns6_myProperty_InterfaceSOAPSerializer;
    
    public PropertySet_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public PropertySet_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns6_myProperty_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property.class, ns6_Property_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_isInternal_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setIsInternal(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_isInternal_QNAME});
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_Properties_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns6_Properties_QNAME))) {
                    value = ns6_myProperty_InterfaceSOAPSerializer.deserialize(ns6_Properties_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[values.size()];
            member = values.toArray((Object[]) member);
            instance.setProperties((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[])member);
        }
        else {
            instance.setProperties(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet)obj;
        
        if (new Boolean(instance.isIsInternal()) != null) {
            writer.writeAttribute(ns1_isInternal_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isIsInternal()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_isInternal_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet)obj;
        
        if (instance.getProperties() != null) {
            for (int i = 0; i < instance.getProperties().length; ++i) {
                ns6_myProperty_InterfaceSOAPSerializer.serialize(instance.getProperties()[i], ns6_Properties_QNAME, null, writer, context);
            }
        }
    }
}
