// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class PropertyFilterMode {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _NONEString = "NONE";
    public static final java.lang.String _IMPLIEDString = "IMPLIED";
    public static final java.lang.String _SPECIFIED_BY_INCLUDEString = "SPECIFIED_BY_INCLUDE";
    public static final java.lang.String _SPECIFIED_BY_EXCLUDEString = "SPECIFIED_BY_EXCLUDE";
    public static final java.lang.String _ALL_NON_SYSTEMString = "ALL_NON_SYSTEM";
    public static final java.lang.String _ALLString = "ALL";
    
    public static final java.lang.String _NONE = new java.lang.String(_NONEString);
    public static final java.lang.String _IMPLIED = new java.lang.String(_IMPLIEDString);
    public static final java.lang.String _SPECIFIED_BY_INCLUDE = new java.lang.String(_SPECIFIED_BY_INCLUDEString);
    public static final java.lang.String _SPECIFIED_BY_EXCLUDE = new java.lang.String(_SPECIFIED_BY_EXCLUDEString);
    public static final java.lang.String _ALL_NON_SYSTEM = new java.lang.String(_ALL_NON_SYSTEMString);
    public static final java.lang.String _ALL = new java.lang.String(_ALLString);
    
    public static final PropertyFilterMode NONE = new PropertyFilterMode(_NONE);
    public static final PropertyFilterMode IMPLIED = new PropertyFilterMode(_IMPLIED);
    public static final PropertyFilterMode SPECIFIED_BY_INCLUDE = new PropertyFilterMode(_SPECIFIED_BY_INCLUDE);
    public static final PropertyFilterMode SPECIFIED_BY_EXCLUDE = new PropertyFilterMode(_SPECIFIED_BY_EXCLUDE);
    public static final PropertyFilterMode ALL_NON_SYSTEM = new PropertyFilterMode(_ALL_NON_SYSTEM);
    public static final PropertyFilterMode ALL = new PropertyFilterMode(_ALL);
    
    protected PropertyFilterMode(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static PropertyFilterMode fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (NONE.value.equals(value)) {
            return NONE;
        } else if (IMPLIED.value.equals(value)) {
            return IMPLIED;
        } else if (SPECIFIED_BY_INCLUDE.value.equals(value)) {
            return SPECIFIED_BY_INCLUDE;
        } else if (SPECIFIED_BY_EXCLUDE.value.equals(value)) {
            return SPECIFIED_BY_EXCLUDE;
        } else if (ALL_NON_SYSTEM.value.equals(value)) {
            return ALL_NON_SYSTEM;
        } else if (ALL.value.equals(value)) {
            return ALL;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static PropertyFilterMode fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        PropertyFilterMode ret = (PropertyFilterMode)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_NONEString)) {
            return NONE;
        } else if (value.equals(_IMPLIEDString)) {
            return IMPLIED;
        } else if (value.equals(_SPECIFIED_BY_INCLUDEString)) {
            return SPECIFIED_BY_INCLUDE;
        } else if (value.equals(_SPECIFIED_BY_EXCLUDEString)) {
            return SPECIFIED_BY_EXCLUDE;
        } else if (value.equals(_ALL_NON_SYSTEMString)) {
            return ALL_NON_SYSTEM;
        } else if (value.equals(_ALLString)) {
            return ALL;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof PropertyFilterMode)) {
            return false;
        }
        return ((PropertyFilterMode)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
