// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class PropertyProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_filterMode_QNAME = new QName("", "filterMode");
    private static final javax.xml.namespace.QName ns1_isProcessIncludedUnknown_QNAME = new QName("", "isProcessIncludedUnknown");
    private static final javax.xml.namespace.QName ns3_IncludeProperties_QNAME = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "IncludeProperties");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns3_ExcludeProperties_QNAME = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "ExcludeProperties");
    
    public PropertyProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public PropertyProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_filterMode_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setFilterMode((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode)member);
        }
        attribute = attributes.getValue(ns1_isProcessIncludedUnknown_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setIsProcessIncludedUnknown(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_isProcessIncludedUnknown_QNAME});
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_IncludeProperties_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_IncludeProperties_QNAME))) {
                    value = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns3_IncludeProperties_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new java.lang.String[values.size()];
            member = values.toArray((Object[]) member);
            instance.setIncludeProperties((java.lang.String[])member);
        }
        else {
            instance.setIncludeProperties(new java.lang.String[0]);
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_ExcludeProperties_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns3_ExcludeProperties_QNAME))) {
                    value = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns3_ExcludeProperties_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new java.lang.String[values.size()];
            member = values.toArray((Object[]) member);
            instance.setExcludeProperties((java.lang.String[])member);
        }
        else {
            instance.setExcludeProperties(new java.lang.String[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile)obj;
        
        if (instance.getFilterMode() != null) {
            writer.writeAttribute(ns1_filterMode_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyFilterMode_Encoder.getInstance().objectToString(instance.getFilterMode(), writer));
        }
        if (new Boolean(instance.isIsProcessIncludedUnknown()) != null) {
            writer.writeAttribute(ns1_isProcessIncludedUnknown_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isIsProcessIncludedUnknown()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_isProcessIncludedUnknown_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertyProfile)obj;
        
        if (instance.getIncludeProperties() != null) {
            for (int i = 0; i < instance.getIncludeProperties().length; ++i) {
                ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getIncludeProperties()[i], ns3_IncludeProperties_QNAME, null, writer, context);
            }
        }
        if (instance.getExcludeProperties() != null) {
            for (int i = 0; i < instance.getExcludeProperties().length; ++i) {
                ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getExcludeProperties()[i], ns3_ExcludeProperties_QNAME, null, writer, context);
            }
        }
    }
}
