// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class RelationshipProfile_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_resultDataMode_QNAME = new QName("", "resultDataMode");
    private static final javax.xml.namespace.QName ns1_nameFilter_QNAME = new QName("", "nameFilter");
    private static final javax.xml.namespace.QName ns1_relationName_QNAME = new QName("", "relationName");
    private static final javax.xml.namespace.QName ns1_targetRoleFilter_QNAME = new QName("", "targetRoleFilter");
    private static final javax.xml.namespace.QName ns1_targetRole_QNAME = new QName("", "targetRole");
    private static final javax.xml.namespace.QName ns1_depthFilter_QNAME = new QName("", "depthFilter");
    private static final javax.xml.namespace.QName ns1_depth_QNAME = new QName("", "depth");
    
    public RelationshipProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public RelationshipProfile_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_resultDataMode_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setResultDataMode((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode)member);
        }
        attribute = attributes.getValue(ns1_nameFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setNameFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter)member);
        }
        attribute = attributes.getValue(ns1_relationName_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setRelationName((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_targetRoleFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setTargetRoleFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter)member);
        }
        attribute = attributes.getValue(ns1_targetRole_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setTargetRole((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_depthFilter_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setDepthFilter((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter)member);
        }
        attribute = attributes.getValue(ns1_depth_QNAME);
        if (attribute != null) {
            member = XSDIntEncoder.getInstance().stringToObject(attribute, reader);
            instance.setDepth(((java.lang.Integer)member).intValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_depth_QNAME});
        }
        
        reader.nextElementContent();
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile)obj;
        
        if (instance.getResultDataMode() != null) {
            writer.writeAttribute(ns1_resultDataMode_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode_Encoder.getInstance().objectToString(instance.getResultDataMode(), writer));
        }
        if (instance.getNameFilter() != null) {
            writer.writeAttribute(ns1_nameFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter_Encoder.getInstance().objectToString(instance.getNameFilter(), writer));
        }
        if (instance.getRelationName() != null) {
            writer.writeAttribute(ns1_relationName_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getRelationName(), writer));
        }
        if (instance.getTargetRoleFilter() != null) {
            writer.writeAttribute(ns1_targetRoleFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter_Encoder.getInstance().objectToString(instance.getTargetRoleFilter(), writer));
        }
        if (instance.getTargetRole() != null) {
            writer.writeAttribute(ns1_targetRole_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getTargetRole(), writer));
        }
        if (instance.getDepthFilter() != null) {
            writer.writeAttribute(ns1_depthFilter_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter_Encoder.getInstance().objectToString(instance.getDepthFilter(), writer));
        }
        if (new java.lang.Integer(instance.getDepth()) != null) {
            writer.writeAttribute(ns1_depth_QNAME, XSDIntEncoder.getInstance().objectToString(new java.lang.Integer(instance.getDepth()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_depth_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipProfile)obj;
        
    }
}
