// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class RelationshipProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode resultDataMode;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter nameFilter;
    protected java.lang.String relationName;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter targetRoleFilter;
    protected java.lang.String targetRole;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter depthFilter;
    protected int depth;
    
    public RelationshipProfile() {
    }
    
    public RelationshipProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode resultDataMode, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter nameFilter, java.lang.String relationName, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter targetRoleFilter, java.lang.String targetRole, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter depthFilter, int depth) {
        this.resultDataMode = resultDataMode;
        this.nameFilter = nameFilter;
        this.relationName = relationName;
        this.targetRoleFilter = targetRoleFilter;
        this.targetRole = targetRole;
        this.depthFilter = depthFilter;
        this.depth = depth;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode getResultDataMode() {
        return resultDataMode;
    }
    
    public void setResultDataMode(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ResultDataMode resultDataMode) {
        this.resultDataMode = resultDataMode;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter getNameFilter() {
        return nameFilter;
    }
    
    public void setNameFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RelationshipNameFilter nameFilter) {
        this.nameFilter = nameFilter;
    }
    
    public java.lang.String getRelationName() {
        return relationName;
    }
    
    public void setRelationName(java.lang.String relationName) {
        this.relationName = relationName;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter getTargetRoleFilter() {
        return targetRoleFilter;
    }
    
    public void setTargetRoleFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.TargetRoleFilter targetRoleFilter) {
        this.targetRoleFilter = targetRoleFilter;
    }
    
    public java.lang.String getTargetRole() {
        return targetRole;
    }
    
    public void setTargetRole(java.lang.String targetRole) {
        this.targetRole = targetRole;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter getDepthFilter() {
        return depthFilter;
    }
    
    public void setDepthFilter(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.DepthFilter depthFilter) {
        this.depthFilter = depthFilter;
    }
    
    public int getDepth() {
        return depth;
    }
    
    public void setDepth(int depth) {
        this.depth = depth;
    }
}
