// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class RenditionType {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _CLIENTString = "CLIENT";
    public static final java.lang.String _SERVERString = "SERVER";
    public static final java.lang.String _PRIMARYString = "PRIMARY";
    
    public static final java.lang.String _CLIENT = new java.lang.String(_CLIENTString);
    public static final java.lang.String _SERVER = new java.lang.String(_SERVERString);
    public static final java.lang.String _PRIMARY = new java.lang.String(_PRIMARYString);
    
    public static final RenditionType CLIENT = new RenditionType(_CLIENT);
    public static final RenditionType SERVER = new RenditionType(_SERVER);
    public static final RenditionType PRIMARY = new RenditionType(_PRIMARY);
    
    protected RenditionType(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static RenditionType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (CLIENT.value.equals(value)) {
            return CLIENT;
        } else if (SERVER.value.equals(value)) {
            return SERVER;
        } else if (PRIMARY.value.equals(value)) {
            return PRIMARY;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static RenditionType fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        RenditionType ret = (RenditionType)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_CLIENTString)) {
            return CLIENT;
        } else if (value.equals(_SERVERString)) {
            return SERVER;
        } else if (value.equals(_PRIMARYString)) {
            return PRIMARY;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof RenditionType)) {
            return false;
        }
        return ((RenditionType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
