// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class RepositoryIdentity extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.BasicIdentity {
    protected java.lang.String repositoryName;
    protected java.lang.String domain;
    
    public RepositoryIdentity() {
    }
    
    public RepositoryIdentity(java.lang.String userName, java.lang.String password, java.lang.String repositoryName, java.lang.String domain) {
        this.userName = userName;
        this.password = password;
        this.repositoryName = repositoryName;
        this.domain = domain;
    }
    
    public java.lang.String getRepositoryName() {
        return repositoryName;
    }
    
    public void setRepositoryName(java.lang.String repositoryName) {
        this.repositoryName = repositoryName;
    }
    
    public java.lang.String getDomain() {
        return domain;
    }
    
    public void setDomain(java.lang.String domain) {
        this.domain = domain;
    }
}
