// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class RichTextProperty_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_name_QNAME = new QName("", "name");
    private static final javax.xml.namespace.QName ns1_isTransient_QNAME = new QName("", "isTransient");
    private static final javax.xml.namespace.QName ns6_Value_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "Value");
    private static final javax.xml.namespace.QName ns4_RichText_TYPE_QNAME = new QName("http://core.datamodel.fs.documentum.emc.com/", "RichText");
    private CombinedSerializer ns4_myRichText_LiteralSerializer;
    
    public RichTextProperty_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public RichTextProperty_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns4_myRichText_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText.class, ns4_RichText_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_name_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setName((java.lang.String)member);
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_name_QNAME});
        }
        attribute = attributes.getValue(ns1_isTransient_QNAME);
        if (attribute != null) {
            member = XSDBooleanEncoder.getInstance().stringToObject(attribute, reader);
            instance.setIsTransient(((Boolean)member).booleanValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_isTransient_QNAME});
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns6_Value_QNAME)) {
                member = ns4_myRichText_LiteralSerializer.deserialize(ns6_Value_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setValue((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty)obj;
        
        if (instance.getName() != null) {
            writer.writeAttribute(ns1_name_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getName(), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_name_QNAME});
        }
        if (new Boolean(instance.isIsTransient()) != null) {
            writer.writeAttribute(ns1_isTransient_QNAME, XSDBooleanEncoder.getInstance().objectToString(new Boolean(instance.isIsTransient()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_isTransient_QNAME});
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichTextProperty)obj;
        
        if (instance.getValue() != null) {
            ns4_myRichText_LiteralSerializer.serialize(instance.getValue(), ns6_Value_QNAME, null, writer, context);
        }
    }
}
