// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class RichTextProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean transferContent;
    protected java.lang.String imageUrlTemplate;
    protected java.lang.String anchorUrlTemplate;
    
    public RichTextProfile() {
    }
    
    public RichTextProfile(boolean transferContent, java.lang.String imageUrlTemplate, java.lang.String anchorUrlTemplate) {
        this.transferContent = transferContent;
        this.imageUrlTemplate = imageUrlTemplate;
        this.anchorUrlTemplate = anchorUrlTemplate;
    }
    
    public boolean isTransferContent() {
        return transferContent;
    }
    
    public void setTransferContent(boolean transferContent) {
        this.transferContent = transferContent;
    }
    
    public java.lang.String getImageUrlTemplate() {
        return imageUrlTemplate;
    }
    
    public void setImageUrlTemplate(java.lang.String imageUrlTemplate) {
        this.imageUrlTemplate = imageUrlTemplate;
    }
    
    public java.lang.String getAnchorUrlTemplate() {
        return anchorUrlTemplate;
    }
    
    public void setAnchorUrlTemplate(java.lang.String anchorUrlTemplate) {
        this.anchorUrlTemplate = anchorUrlTemplate;
    }
}
