// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class RichText {
    protected java.lang.String format;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content body;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[] contents;
    
    public RichText() {
    }
    
    public RichText(java.lang.String format, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content body, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[] contents) {
        this.format = format;
        this.body = body;
        this.contents = contents;
    }
    
    public java.lang.String getFormat() {
        return format;
    }
    
    public void setFormat(java.lang.String format) {
        this.format = format;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content getBody() {
        return body;
    }
    
    public void setBody(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content body) {
        this.body = body;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[] getContents() {
        return contents;
    }
    
    public void setContents(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[] contents) {
        this.contents = contents;
    }
}
