// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class RichText_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_format_QNAME = new QName("", "format");
    private static final javax.xml.namespace.QName ns4_Body_QNAME = new QName("http://core.datamodel.fs.documentum.emc.com/", "Body");
    private static final javax.xml.namespace.QName ns5_Content_TYPE_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "Content");
    private CombinedSerializer ns5_myContent_InterfaceSOAPSerializer;
    private static final javax.xml.namespace.QName ns4_Contents_QNAME = new QName("http://core.datamodel.fs.documentum.emc.com/", "Contents");
    
    public RichText_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public RichText_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns5_myContent_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content.class, ns5_Content_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_format_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setFormat((java.lang.String)member);
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns4_Body_QNAME)) {
                member = ns5_myContent_InterfaceSOAPSerializer.deserialize(ns4_Body_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setBody((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns4_Contents_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns4_Contents_QNAME))) {
                    value = ns5_myContent_InterfaceSOAPSerializer.deserialize(ns4_Contents_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[values.size()];
            member = values.toArray((Object[]) member);
            instance.setContents((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[])member);
        }
        else {
            instance.setContents(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText)obj;
        
        if (instance.getFormat() != null) {
            writer.writeAttribute(ns1_format_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getFormat(), writer));
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RichText)obj;
        
        if (instance.getBody() != null) {
            ns5_myContent_InterfaceSOAPSerializer.serialize(instance.getBody(), ns4_Body_QNAME, null, writer, context);
        }
        if (instance.getContents() != null) {
            for (int i = 0; i < instance.getContents().length; ++i) {
                ns5_myContent_InterfaceSOAPSerializer.serialize(instance.getContents()[i], ns4_Contents_QNAME, null, writer, context);
            }
        }
    }
}
