// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class SchemaProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean includeTypes;
    protected boolean includeProperties;
    protected boolean includeValues;
    protected boolean includeRelationships;
    protected java.lang.String scope;
    
    public SchemaProfile() {
    }
    
    public SchemaProfile(boolean includeTypes, boolean includeProperties, boolean includeValues, boolean includeRelationships, java.lang.String scope) {
        this.includeTypes = includeTypes;
        this.includeProperties = includeProperties;
        this.includeValues = includeValues;
        this.includeRelationships = includeRelationships;
        this.scope = scope;
    }
    
    public boolean isIncludeTypes() {
        return includeTypes;
    }
    
    public void setIncludeTypes(boolean includeTypes) {
        this.includeTypes = includeTypes;
    }
    
    public boolean isIncludeProperties() {
        return includeProperties;
    }
    
    public void setIncludeProperties(boolean includeProperties) {
        this.includeProperties = includeProperties;
    }
    
    public boolean isIncludeValues() {
        return includeValues;
    }
    
    public void setIncludeValues(boolean includeValues) {
        this.includeValues = includeValues;
    }
    
    public boolean isIncludeRelationships() {
        return includeRelationships;
    }
    
    public void setIncludeRelationships(boolean includeRelationships) {
        this.includeRelationships = includeRelationships;
    }
    
    public java.lang.String getScope() {
        return scope;
    }
    
    public void setScope(java.lang.String scope) {
        this.scope = scope;
    }
}
