// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class SearchProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean isAsyncCall;
    
    public SearchProfile() {
    }
    
    public SearchProfile(boolean isAsyncCall) {
        this.isAsyncCall = isAsyncCall;
    }
    
    public boolean isIsAsyncCall() {
        return isAsyncCall;
    }
    
    public void setIsAsyncCall(boolean isAsyncCall) {
        this.isAsyncCall = isAsyncCall;
    }
}
