// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class ServiceContext_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_token_QNAME = new QName("", "token");
    private static final javax.xml.namespace.QName ns1_locale_QNAME = new QName("", "locale");
    private static final javax.xml.namespace.QName ns8_Identities_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "Identities");
    private static final javax.xml.namespace.QName ns8_Identity_TYPE_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "Identity");
    private CombinedSerializer ns8_myIdentity_InterfaceSOAPSerializer;
    private static final javax.xml.namespace.QName ns8_Profiles_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "Profiles");
    private static final javax.xml.namespace.QName ns3_Profile_TYPE_QNAME = new QName("http://profiles.core.datamodel.fs.documentum.emc.com/", "Profile");
    private CombinedSerializer ns3_myProfile_InterfaceSOAPSerializer;
    private static final javax.xml.namespace.QName ns8_RuntimeProperties_QNAME = new QName("http://context.core.datamodel.fs.documentum.emc.com/", "RuntimeProperties");
    private static final javax.xml.namespace.QName ns6_PropertySet_TYPE_QNAME = new QName("http://properties.core.datamodel.fs.documentum.emc.com/", "PropertySet");
    private CombinedSerializer ns6_myPropertySet_LiteralSerializer;
    
    public ServiceContext_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ServiceContext_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns8_myIdentity_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity.class, ns8_Identity_TYPE_QNAME);
        ns3_myProfile_InterfaceSOAPSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile.class, ns3_Profile_TYPE_QNAME);
        ns6_myPropertySet_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet.class, ns6_PropertySet_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_token_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setToken((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_locale_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setLocale((java.lang.String)member);
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns8_Identities_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns8_Identities_QNAME))) {
                    value = ns8_myIdentity_InterfaceSOAPSerializer.deserialize(ns8_Identities_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[values.size()];
            member = values.toArray((Object[]) member);
            instance.setIdentities((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[])member);
        }
        else {
            instance.setIdentities(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[0]);
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns8_Profiles_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns8_Profiles_QNAME))) {
                    value = ns3_myProfile_InterfaceSOAPSerializer.deserialize(ns8_Profiles_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[values.size()];
            member = values.toArray((Object[]) member);
            instance.setProfiles((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[])member);
        }
        else {
            instance.setProfiles(new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[0]);
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns8_RuntimeProperties_QNAME)) {
                member = ns6_myPropertySet_LiteralSerializer.deserialize(ns8_RuntimeProperties_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setRuntimeProperties((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext)obj;
        
        if (instance.getToken() != null) {
            writer.writeAttribute(ns1_token_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getToken(), writer));
        }
        if (instance.getLocale() != null) {
            writer.writeAttribute(ns1_locale_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getLocale(), writer));
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ServiceContext)obj;
        
        if (instance.getIdentities() != null) {
            for (int i = 0; i < instance.getIdentities().length; ++i) {
                ns8_myIdentity_InterfaceSOAPSerializer.serialize(instance.getIdentities()[i], ns8_Identities_QNAME, null, writer, context);
            }
        }
        if (instance.getProfiles() != null) {
            for (int i = 0; i < instance.getProfiles().length; ++i) {
                ns3_myProfile_InterfaceSOAPSerializer.serialize(instance.getProfiles()[i], ns8_Profiles_QNAME, null, writer, context);
            }
        }
        if (instance.getRuntimeProperties() != null) {
            ns6_myPropertySet_LiteralSerializer.serialize(instance.getRuntimeProperties(), ns8_RuntimeProperties_QNAME, null, writer, context);
        }
    }
}
