// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ServiceContext {
    protected java.lang.String token;
    protected java.lang.String locale;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[] identities;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[] profiles;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet runtimeProperties;
    
    public ServiceContext() {
    }
    
    public ServiceContext(java.lang.String token, java.lang.String locale, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[] identities, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[] profiles, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet runtimeProperties) {
        this.token = token;
        this.locale = locale;
        this.identities = identities;
        this.profiles = profiles;
        this.runtimeProperties = runtimeProperties;
    }
    
    public java.lang.String getToken() {
        return token;
    }
    
    public void setToken(java.lang.String token) {
        this.token = token;
    }
    
    public java.lang.String getLocale() {
        return locale;
    }
    
    public void setLocale(java.lang.String locale) {
        this.locale = locale;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[] getIdentities() {
        return identities;
    }
    
    public void setIdentities(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Identity[] identities) {
        this.identities = identities;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[] getProfiles() {
        return profiles;
    }
    
    public void setProfiles(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile[] profiles) {
        this.profiles = profiles;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet getRuntimeProperties() {
        return runtimeProperties;
    }
    
    public void setRuntimeProperties(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.PropertySet runtimeProperties) {
        this.runtimeProperties = runtimeProperties;
    }
}
