// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class StringProperty extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Property {
    protected java.lang.String value;
    
    public StringProperty() {
    }
    
    public StringProperty(java.lang.String name, boolean isTransient, java.lang.String value) {
        this.name = name;
        this.isTransient = isTransient;
        this.value = value;
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }
}
