// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class TargetRoleFilter {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _SPECIFIEDString = "SPECIFIED";
    public static final java.lang.String _ANYString = "ANY";
    
    public static final java.lang.String _SPECIFIED = new java.lang.String(_SPECIFIEDString);
    public static final java.lang.String _ANY = new java.lang.String(_ANYString);
    
    public static final TargetRoleFilter SPECIFIED = new TargetRoleFilter(_SPECIFIED);
    public static final TargetRoleFilter ANY = new TargetRoleFilter(_ANY);
    
    protected TargetRoleFilter(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static TargetRoleFilter fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (SPECIFIED.value.equals(value)) {
            return SPECIFIED;
        } else if (ANY.value.equals(value)) {
            return ANY;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static TargetRoleFilter fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        TargetRoleFilter ret = (TargetRoleFilter)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_SPECIFIEDString)) {
            return SPECIFIED;
        } else if (value.equals(_ANYString)) {
            return ANY;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof TargetRoleFilter)) {
            return false;
        }
        return ((TargetRoleFilter)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
