// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.xsd.XSDConstants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.encoding.literal.DetailFragmentDeserializer;
import com.sun.xml.rpc.encoding.simpletype.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.util.List;
import java.util.ArrayList;

public class UcfContent_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_format_QNAME = new QName("", "format");
    private static final javax.xml.namespace.QName ns1_pageNumber_QNAME = new QName("", "pageNumber");
    private static final javax.xml.namespace.QName ns1_pageModifier_QNAME = new QName("", "pageModifier");
    private static final javax.xml.namespace.QName ns1_contentTransferMode_QNAME = new QName("", "contentTransferMode");
    private static final javax.xml.namespace.QName ns5_renditionType_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "renditionType");
    private static final javax.xml.namespace.QName ns5_RenditionType_TYPE_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "RenditionType");
    private CombinedSerializer ns5myns5_RenditionType__RenditionType_LiteralSerializer;
    private static final javax.xml.namespace.QName ns5_LocalFilePath_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "LocalFilePath");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns5_ActivityInfo_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "ActivityInfo");
    private static final javax.xml.namespace.QName ns5_ActivityInfo_TYPE_QNAME = new QName("http://content.core.datamodel.fs.documentum.emc.com/", "ActivityInfo");
    private CombinedSerializer ns5_myActivityInfo_LiteralSerializer;
    
    public UcfContent_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public UcfContent_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns5myns5_RenditionType__RenditionType_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType.class, ns5_RenditionType_TYPE_QNAME);
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        ns5_myActivityInfo_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo.class, ns5_ActivityInfo_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent instance = new uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        Attributes attributes = reader.getAttributes();
        java.lang.String attribute = null;
        attribute = attributes.getValue(ns1_format_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setFormat((java.lang.String)member);
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_format_QNAME});
        }
        attribute = attributes.getValue(ns1_pageNumber_QNAME);
        if (attribute != null) {
            member = XSDIntEncoder.getInstance().stringToObject(attribute, reader);
            instance.setPageNumber(((java.lang.Integer)member).intValue());
        }
        else {
            throw new DeserializationException("literal.missingRequiredAttribute", new Object[] {ns1_pageNumber_QNAME});
        }
        attribute = attributes.getValue(ns1_pageModifier_QNAME);
        if (attribute != null) {
            member = XSDStringEncoder.getInstance().stringToObject(attribute, reader);
            instance.setPageModifier((java.lang.String)member);
        }
        attribute = attributes.getValue(ns1_contentTransferMode_QNAME);
        if (attribute != null) {
            member = uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode_Encoder.getInstance().stringToObject(attribute, reader);
            instance.setContentTransferMode((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode)member);
        }
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_renditionType_QNAME)) {
                member = ns5myns5_RenditionType__RenditionType_LiteralSerializer.deserialize(ns5_renditionType_QNAME, reader, context);
                instance.setRenditionType((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_LocalFilePath_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns5_LocalFilePath_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setLocalFilePath((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns5_LocalFilePath_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns5_ActivityInfo_QNAME)) {
                member = ns5_myActivityInfo_LiteralSerializer.deserialize(ns5_ActivityInfo_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setActivityInfo((uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ActivityInfo)member);
                reader.nextElementContent();
            }
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent)obj;
        
        if (instance.getFormat() != null) {
            writer.writeAttribute(ns1_format_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getFormat(), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_format_QNAME});
        }
        if (new java.lang.Integer(instance.getPageNumber()) != null) {
            writer.writeAttribute(ns1_pageNumber_QNAME, XSDIntEncoder.getInstance().objectToString(new java.lang.Integer(instance.getPageNumber()), writer));
        }
        else {
            throw new DeserializationException("literal.requiredAttributeConstraint", new Object[] {ns1_pageNumber_QNAME});
        }
        if (instance.getPageModifier() != null) {
            writer.writeAttribute(ns1_pageModifier_QNAME, XSDStringEncoder.getInstance().objectToString(instance.getPageModifier(), writer));
        }
        if (instance.getContentTransferMode() != null) {
            writer.writeAttribute(ns1_contentTransferMode_QNAME, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode_Encoder.getInstance().objectToString(instance.getContentTransferMode(), writer));
        }
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent instance = (uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.UcfContent)obj;
        
        ns5myns5_RenditionType__RenditionType_LiteralSerializer.serialize(instance.getRenditionType(), ns5_renditionType_QNAME, null, writer, context);
        if (instance.getLocalFilePath() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getLocalFilePath(), ns5_LocalFilePath_QNAME, null, writer, context);
        if (instance.getActivityInfo() != null) {
            ns5_myActivityInfo_LiteralSerializer.serialize(instance.getActivityInfo(), ns5_ActivityInfo_QNAME, null, writer, context);
        }
    }
}
