// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class UrlContent extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Content {
    protected java.lang.String url;
    
    public UrlContent() {
    }
    
    public UrlContent(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.RenditionType renditionType, java.lang.String format, int pageNumber, java.lang.String pageModifier, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ContentTransferMode contentTransferMode, java.lang.String url) {
        this.renditionType = renditionType;
        this.format = format;
        this.pageNumber = pageNumber;
        this.pageModifier = pageModifier;
        this.contentTransferMode = contentTransferMode;
        this.url = url;
    }
    
    public java.lang.String getUrl() {
        return url;
    }
    
    public void setUrl(java.lang.String url) {
        this.url = url;
    }
}
