// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class ValueAction {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType type;
    protected int index;
    
    public ValueAction() {
    }
    
    public ValueAction(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType type, int index) {
        this.type = type;
        this.index = index;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType getType() {
        return type;
    }
    
    public void setType(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ValueActionType type) {
        this.type = type;
    }
    
    public int getIndex() {
        return index;
    }
    
    public void setIndex(int index) {
        this.index = index;
    }
}
