// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class ValueActionType {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _APPENDString = "APPEND";
    public static final java.lang.String _INSERTString = "INSERT";
    public static final java.lang.String _DELETEString = "DELETE";
    public static final java.lang.String _SETString = "SET";
    
    public static final java.lang.String _APPEND = new java.lang.String(_APPENDString);
    public static final java.lang.String _INSERT = new java.lang.String(_INSERTString);
    public static final java.lang.String _DELETE = new java.lang.String(_DELETEString);
    public static final java.lang.String _SET = new java.lang.String(_SETString);
    
    public static final ValueActionType APPEND = new ValueActionType(_APPEND);
    public static final ValueActionType INSERT = new ValueActionType(_INSERT);
    public static final ValueActionType DELETE = new ValueActionType(_DELETE);
    public static final ValueActionType SET = new ValueActionType(_SET);
    
    protected ValueActionType(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static ValueActionType fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (APPEND.value.equals(value)) {
            return APPEND;
        } else if (INSERT.value.equals(value)) {
            return INSERT;
        } else if (DELETE.value.equals(value)) {
            return DELETE;
        } else if (SET.value.equals(value)) {
            return SET;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static ValueActionType fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        ValueActionType ret = (ValueActionType)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_APPENDString)) {
            return APPEND;
        } else if (value.equals(_INSERTString)) {
            return INSERT;
        } else if (value.equals(_DELETEString)) {
            return DELETE;
        } else if (value.equals(_SETString)) {
            return SET;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof ValueActionType)) {
            return false;
        }
        return ((ValueActionType)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
