// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class VdmRetrieveProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected boolean shouldFollowAssembly;
    protected java.lang.String binding;
    
    public VdmRetrieveProfile() {
    }
    
    public VdmRetrieveProfile(boolean shouldFollowAssembly, java.lang.String binding) {
        this.shouldFollowAssembly = shouldFollowAssembly;
        this.binding = binding;
    }
    
    public boolean isShouldFollowAssembly() {
        return shouldFollowAssembly;
    }
    
    public void setShouldFollowAssembly(boolean shouldFollowAssembly) {
        this.shouldFollowAssembly = shouldFollowAssembly;
    }
    
    public java.lang.String getBinding() {
        return binding;
    }
    
    public void setBinding(java.lang.String binding) {
        this.binding = binding;
    }
}
