// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


public class VdmUpdateProfile extends uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.Profile {
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy versionStrategy;
    protected boolean retainLock;
    protected uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod updateMethod;
    protected boolean convertToSimple;
    protected java.lang.String[] labels;
    
    public VdmUpdateProfile() {
    }
    
    public VdmUpdateProfile(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy versionStrategy, boolean retainLock, uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod updateMethod, boolean convertToSimple, java.lang.String[] labels) {
        this.versionStrategy = versionStrategy;
        this.retainLock = retainLock;
        this.updateMethod = updateMethod;
        this.convertToSimple = convertToSimple;
        this.labels = labels;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy getVersionStrategy() {
        return versionStrategy;
    }
    
    public void setVersionStrategy(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.VersionStrategy versionStrategy) {
        this.versionStrategy = versionStrategy;
    }
    
    public boolean isRetainLock() {
        return retainLock;
    }
    
    public void setRetainLock(boolean retainLock) {
        this.retainLock = retainLock;
    }
    
    public uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod getUpdateMethod() {
        return updateMethod;
    }
    
    public void setUpdateMethod(uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum.ListUpdateMethod updateMethod) {
        this.updateMethod = updateMethod;
    }
    
    public boolean isConvertToSimple() {
        return convertToSimple;
    }
    
    public void setConvertToSimple(boolean convertToSimple) {
        this.convertToSimple = convertToSimple;
    }
    
    public java.lang.String[] getLabels() {
        return labels;
    }
    
    public void setLabels(java.lang.String[] labels) {
        this.labels = labels;
    }
}
