// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R2)
// Generated source version: 1.1.3

package uk.gov.courtservice.xhibit.business.services.dartswebserviceclient.documentum;


import java.util.Map;
import java.util.HashMap;

public class VersionStrategy {
    private java.lang.String value;
    private static java.util.Map valueMap = new HashMap();
    public static final java.lang.String _IMPLIEDString = "IMPLIED";
    public static final java.lang.String _NEXT_MAJORString = "NEXT_MAJOR";
    public static final java.lang.String _NEXT_MINORString = "NEXT_MINOR";
    public static final java.lang.String _SAME_VERSIONString = "SAME_VERSION";
    
    public static final java.lang.String _IMPLIED = new java.lang.String(_IMPLIEDString);
    public static final java.lang.String _NEXT_MAJOR = new java.lang.String(_NEXT_MAJORString);
    public static final java.lang.String _NEXT_MINOR = new java.lang.String(_NEXT_MINORString);
    public static final java.lang.String _SAME_VERSION = new java.lang.String(_SAME_VERSIONString);
    
    public static final VersionStrategy IMPLIED = new VersionStrategy(_IMPLIED);
    public static final VersionStrategy NEXT_MAJOR = new VersionStrategy(_NEXT_MAJOR);
    public static final VersionStrategy NEXT_MINOR = new VersionStrategy(_NEXT_MINOR);
    public static final VersionStrategy SAME_VERSION = new VersionStrategy(_SAME_VERSION);
    
    protected VersionStrategy(java.lang.String value) {
        this.value = value;
        valueMap.put(this.toString(), this);
    }
    
    public java.lang.String getValue() {
        return value;
    }
    
    public static VersionStrategy fromValue(java.lang.String value)
        throws java.lang.IllegalStateException {
        if (IMPLIED.value.equals(value)) {
            return IMPLIED;
        } else if (NEXT_MAJOR.value.equals(value)) {
            return NEXT_MAJOR;
        } else if (NEXT_MINOR.value.equals(value)) {
            return NEXT_MINOR;
        } else if (SAME_VERSION.value.equals(value)) {
            return SAME_VERSION;
        }
        throw new java.lang.IllegalArgumentException();
    }
    
    public static VersionStrategy fromString(java.lang.String value)
        throws java.lang.IllegalStateException {
        VersionStrategy ret = (VersionStrategy)valueMap.get(value);
        if (ret != null) {
            return ret;
        }
        if (value.equals(_IMPLIEDString)) {
            return IMPLIED;
        } else if (value.equals(_NEXT_MAJORString)) {
            return NEXT_MAJOR;
        } else if (value.equals(_NEXT_MINORString)) {
            return NEXT_MINOR;
        } else if (value.equals(_SAME_VERSIONString)) {
            return SAME_VERSION;
        }
        throw new IllegalArgumentException();
    }
    
    public java.lang.String toString() {
        return value.toString();
    }
    
    private java.lang.Object readResolve()
        throws java.io.ObjectStreamException {
        return fromValue(getValue());
    }
    
    public boolean equals(java.lang.Object obj) {
        if (!(obj instanceof VersionStrategy)) {
            return false;
        }
        return ((VersionStrategy)obj).value.equals(value);
    }
    
    public int hashCode() {
        return value.hashCode();
    }
}
