Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISQ';
Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISTEST';
Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISTOA';
Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISPCCA';
Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISQAO';
Update XHB_REF_DISPOSAL_MENU set OBS_IND = 'Y' where DISPOSAL_CODE = 'DISQVC';

COMMIT;