<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Surtar Bachra (Electronic Data Systems LTD) -->
<xs:schema xmlns="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:ord="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="OrderTypes.xsd"/>
	<xs:complexType name="BenchWarrantStructure">
		<xs:annotation>
			<xs:documentation>Schema V4.1 (08/06/2005)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OrderHeader" type="XHIBITCourtOrderHeaderStructure"/>
			<!-- Added to allow for failure to Attend/Comply Bench Warrants CCN1388 -->
			<xs:element name="WarrantType" type="WarrantAfterFailureType" minOccurs="0"/>
			<xs:element name="AssociatedOrder" type="AssociatedOrderType" minOccurs="0"/>
			<xs:element name="Release" type="BailDecisionType"/>
			<xs:element name="PreConditions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Surety">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="Plural" type="xs:string"/>
									<xs:element name="MonetaryValue" type="MonetaryValueType"/>
								</xs:sequence>
								<xs:attributeGroup ref="OptionalConditionAttributeGroup"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="PreConditionDetails" type="ord:AdditionalOptionalInfoType" minOccurs="0"/>
					</xs:sequence>
					<xs:attributeGroup ref="ConditionAttributeGroup"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="PostConditions">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="PostConditionDetails" type="xs:string"/>
					</xs:sequence>
					<xs:attributeGroup ref="OptionalConditionAttributeGroup"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="NextAppearance" type="XHIBITCourtAppearanceStructure"/>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="BenchWarrantOrder" type="ord:BenchWarrantStructure">
		<xs:annotation>
			<xs:documentation>Schema V1.0 (26/02/2010)</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>
