<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Surtar Bachra (Electronic Data Systems LTD) -->
<xsd:schema targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:ord="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" elementFormDefault="qualified" attributeFormDefault="unqualified">
    <xsd:include schemaLocation="OrderTypes.xsd"/>
    <xsd:complexType name="CommunityOrderStructure">
        <xsd:sequence>
            <xsd:element name="OrderHeader" type="XHIBITCourtOrderHeaderStructure"/>
            <xsd:element name="ResponsibleOfficer1" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>ResponsibleOfficer1</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="ResponsibleOfficer2" type="xsd:string">
                <xsd:annotation>
                    <xsd:documentation>ResponsibleOfficer2</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="CompletionDate" type="xsd:date">
                <xsd:annotation>
                    <xsd:documentation>CompletionDate</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="OrderRequirements">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="UnpaidWorkRequirement" type="XHIBITUnpaidWorkStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section A</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="ActivityRequirement" type="XHIBITActivityStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section B</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="ProgrammeRequirement" type="XHIBITProgrammeStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section C</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="ProhibitedActivityRequirement" type="XHIBITProhibitedStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section D</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="CurfewRequirement" type="XHIBITCurfewStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section E</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="ExclusionRequirement" type="XHIBITExclusionStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section F</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="ResidenceRequirement" type="XHIBITResidenceStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section G</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="MentalHealthTreatmentRequirement" type="XHIBITMentalHealthStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section H</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="DrugRehabilitationRequirement" type="XHIBITDrugRehabStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section I</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="AlcoholTreatmentRequirement" type="XHIBITAlcoholStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section J</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="SupervisionRequirement" type="XHIBITSupervisionStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section K</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                        <xsd:element name="AttendanceCentreRequirement" type="XHIBITAttendanceStructure">
                            <xsd:annotation>
                                <xsd:documentation>Section L</xsd:documentation>
                            </xsd:annotation>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="ElectronicMonitoringRequirement">
                <xsd:annotation>
                    <xsd:documentation>OrderRequirements / ElectronicMonitoringProvision</xsd:documentation>
                </xsd:annotation>
                <xsd:complexType>
                    <xsd:attributeGroup ref="ConditionAttributeGroup"/>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="PettySessionalArea" type="XHIBITCourtHouseStructure">
                <xsd:annotation>
                    <xsd:documentation>LocalJusticeArea</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="WarningDetentionType" type="DetentionTypeType">
                <xsd:annotation>
                    <xsd:documentation>WarningDetentionType</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
            <xsd:element name="LinkedOffences" type="LinkedOffenceStructure" minOccurs="0">
                <xsd:annotation>
                    <xsd:documentation>Linked Offences for the defendant</xsd:documentation>
                </xsd:annotation>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:element name="CommunityOrder" type="ord:CommunityOrderStructure">
        <xsd:annotation>
            <xsd:documentation>Schema V4.1 (08/06/2005)</xsd:documentation>
        </xsd:annotation>
    </xsd:element>
</xsd:schema>
