<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 sp1 (http://www.altova.com) by LCMG (LogicaCMG) -->
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Surtar Bachra (Electronic Data Systems LTD) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:apd="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails" xmlns="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="OrderTypes.xsd"/>
	<xs:import namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails" schemaLocation="courtService/apd.xsd"/>
	<xs:complexType name="XHIBITDetentionAndTrainingOrderRequirements">
		<xs:sequence>
			<xs:element name="TrailMonitoringRequirement" type="XHIBITTrailMonitoringStructure"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="OrderMadeUnderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Section100"/>
			<xs:enumeration value="Section233"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="DetentionAndTrainingOrderStructure">
		<xs:annotation>
			<xs:documentation>Schema V1.1 (01/05/2020)</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OrderHeader" type="XHIBITCourtOrderHeaderStructure"/>
			<xs:element name="OrderMadeUnder" type="OrderMadeUnderType"/>
			<xs:element name="ConvictionDate" type="xs:date"/>
			<xs:element name="CommittingCourt">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="XHIBITCourtHouseStructure">
							<xs:attributeGroup ref="ConditionAttributeGroup"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="RiskVulnerabilityFactors">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="XHIBITRiskFactorsStructure">
							<xs:attributeGroup ref="ConditionAttributeGroup"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="OrderPeriod" type="XHIBITDetentionAndTrainingPeriodStructure"/>
			<xs:element name="AdditionalNotes">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attributeGroup ref="ConditionAttributeGroup"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="AssociatedCases" type="AssociatedCaseStructure"/>
			<xs:element name="CreditForBail">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CreditForTimeOnBailSection" type="CreditForTimeOnBailSectionType"/>
						<xs:element name="Term" type="XHIBITPeriodStructure"/>
					</xs:sequence>
					<xs:attributeGroup ref="ConditionAttributeGroup"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="DTOrderRequirements" type="XHIBITDetentionAndTrainingOrderRequirements"/>
		</xs:sequence> 
	</xs:complexType>
	<xs:element name="DetentionAndTrainingOrder" type="DetentionAndTrainingOrderStructure">
		<xs:annotation>
			<xs:documentation>Schema V1.1 (01/05/2020)</xs:documentation>
		</xs:annotation>
	</xs:element>
</xs:schema>
