/*
 * Filename:    DB_Patch_7_7_5.sql
 *
 * System:      System Test, Development Systems
 *              Integration 1 & 2, Merc Dev development
 *
 * Date:        13th February 2006
 */
/*
 * HISTORY
 * =======
 * DATE		WHO	CHANGE ID	COMMENT
 * ----         ---     ---------       -------
 * 13/02/2006	K SHAH			Database changes made to comprise release 7.7.5 
 * 15/02/2006   K SHAH			Amended to add translation script and remove delete stats
 * 17/02/2006   K SHAH			Amended to drop package xhb_cr_live_status_pkg
 *
 */ 

set echo on
spool DB_Patch_7_7_5.log


/*
 * Changes to XHB_ table definitions, indexes and foreign keys
 *
 * Additions or deletion of XHB_ tables, indexes and foreign keys
 */

DROP TABLE XHIBIT.XHB_CASE_OVERNIGHT_REFRESH;

CREATE TABLE XHIBIT.XHB_CASE_OVERNIGHT_REFRESH
(
  CASE_OVERNIGHT_REFRESH_ID NUMBER(8) NOT NULL,
  CASE_TYPE_NUMBER VARCHAR2(9) NOT NULL,
  COURT_ID NUMBER(8) NOT NULL,
  LAST_UPDATE_DATE DATE NOT NULL,
  CREATION_DATE DATE NOT NULL,
  CREATED_BY VARCHAR2(30) NOT NULL,
  LAST_UPDATED_BY VARCHAR2(30) NOT NULL,
  VERSION NUMBER(5) NOT NULL)
tablespace XHIBITD;

DROP PUBLIC SYNONYM XHB_CASE_OVERNIGHT_REFRESH;

create public synonym XHB_CASE_OVERNIGHT_REFRESH for XHIBIT.XHB_CASE_OVERNIGHT_REFRESH;

GRANT DELETE, INSERT, SELECT, UPDATE ON  XHIBIT.XHB_CASE_OVERNIGHT_REFRESH TO PUBLIC;

ALTER TABLE XHB_CASE_OVERNIGHT_REFRESH
      ADD CONSTRAINT XHB_CASE_OVERNIGHT_REFRESH_PK PRIMARY KEY (CASE_OVERNIGHT_REFRESH_ID) 
      USING INDEX TABLESPACE XHIBITX;

ALTER TABLE XHB_CASE_OVERNIGHT_REFRESH
      ADD (FOREIGN KEY (COURT_ID)
           REFERENCES XHB_COURT);


/* XHB_CR_LIVE_INTERNET */
  
 CREATE TABLE XHB_CR_LIVE_INTERNET
 (
   CR_LIVE_INTERNET_ID    NUMBER(8)              NOT NULL,
   COURT_ROOM_ID          NUMBER(8)              NOT NULL,
   SCHEDULED_HEARING_ID   NUMBER(8),
   TIME_STATUS_SET        DATE                   NOT NULL,
   STATUS  				 VARCHAR2(4000 BYTE),
   CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
   CREATION_DATE          DATE                   NOT NULL,
   LAST_UPDATED_BY        VARCHAR2(30 BYTE)      NOT NULL,
   LAST_UPDATE_DATE       DATE                   NOT NULL,
   VERSION                NUMBER(5)              NOT NULL
 )
 TABLESPACE XHIBITD;

CREATE UNIQUE INDEX CR_LIVE_INT_COURT_RM_FK_IDX ON XHB_CR_LIVE_INTERNET
(COURT_ROOM_ID)
TABLESPACE XHIBITX;

ALTER TABLE XHB_CR_LIVE_INTERNET
ADD CONSTRAINT CR_LIVE_INTERNET_PK PRIMARY KEY
(CR_LIVE_INTERNET_ID) USING INDEX
TABLESPACE XHIBITX;

CREATE INDEX CR_LIVE_INT_SCH_HEAR_FK_IDX ON XHB_CR_LIVE_INTERNET
(SCHEDULED_HEARING_ID)
TABLESPACE XHIBITX;

ALTER TABLE XHB_CR_LIVE_INTERNET ADD (
  CONSTRAINT CR_LIVE_INT_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) 
    REFERENCES XHB_COURT_ROOM (COURT_ROOM_ID));

ALTER TABLE XHB_CR_LIVE_INTERNET ADD (
  CONSTRAINT CR_LIVE_INT_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) 
    REFERENCES XHB_SCHEDULED_HEARING (SCHEDULED_HEARING_ID));

DROP PUBLIC SYNONYM XHB_CR_LIVE_INTERNET;

create public synonym XHB_CR_LIVE_INTERNET for XHIBIT.XHB_CR_LIVE_INTERNET;

GRANT DELETE, INSERT, SELECT, UPDATE ON  XHIBIT.XHB_CR_LIVE_INTERNET TO PUBLIC;


/* XHB_CR_LIVE_DISPLAY */

CREATE TABLE XHB_CR_LIVE_DISPLAY
(
  CR_LIVE_DISPLAY_ID     NUMBER(8)              NOT NULL,
  COURT_ROOM_ID          NUMBER(8)              NOT NULL,
  SCHEDULED_HEARING_ID   NUMBER(8),
  TIME_STATUS_SET        DATE                   NOT NULL,
  STATUS  				 VARCHAR2(4000 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATION_DATE          DATE                   NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(30 BYTE)      NOT NULL,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  VERSION                NUMBER(5)              NOT NULL
)
TABLESPACE XHIBITD;

CREATE UNIQUE INDEX CR_LIVE_DISP_COURT_RM_FK_IDX ON XHB_CR_LIVE_DISPLAY
(COURT_ROOM_ID)
TABLESPACE XHIBITX;


ALTER TABLE XHB_CR_LIVE_DISPLAY
ADD CONSTRAINT CR_LIVE_DISPLAY_PK PRIMARY KEY (CR_LIVE_DISPLAY_ID)
USING INDEX
TABLESPACE XHIBITX;


CREATE INDEX CR_LIVE_DISP_SCH_HEAR_FK_IDX ON XHB_CR_LIVE_DISPLAY
(SCHEDULED_HEARING_ID)
TABLESPACE XHIBITX;


ALTER TABLE XHB_CR_LIVE_DISPLAY ADD (
  CONSTRAINT CR_LIVE_DISP_COURT_ROOM_ID_FK FOREIGN KEY (COURT_ROOM_ID) 
    REFERENCES XHB_COURT_ROOM (COURT_ROOM_ID));

ALTER TABLE XHB_CR_LIVE_DISPLAY ADD (
  CONSTRAINT CR_LIVE_DISP_SCHED_HEAR_ID_FK FOREIGN KEY (SCHEDULED_HEARING_ID) 
    REFERENCES XHB_SCHEDULED_HEARING (SCHEDULED_HEARING_ID));




/*
 * Changes, additions or deletion of views
 */


/*
 * Changes to AUDIT tables (AUD_) as a result of any XHB_ table modifications
 */

/* AUD_CR_LIVE_INTERNET */

CREATE TABLE AUD_CR_LIVE_INTERNET
(  
  CR_LIVE_INTERNET_ID     NUMBER(8)              NOT NULL,
  COURT_ROOM_ID          NUMBER(8)              NOT NULL,
  SCHEDULED_HEARING_ID   NUMBER(8),
  TIME_STATUS_SET        DATE                   NOT NULL,
  STATUS       			 VARCHAR2(4000 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATION_DATE          DATE                   NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(30 BYTE)      NOT NULL,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  VERSION                NUMBER(5)              NOT NULL,
  INSERT_EVENT           VARCHAR2(1 BYTE)       NOT NULL
)
TABLESPACE AUDITD;

DROP PUBLIC SYNONYM AUD_CR_LIVE_INTERNET;

CREATE PUBLIC SYNONYM AUD_CR_LIVE_INTERNET FOR XHIBIT.AUD_CR_LIVE_INTERNET;


GRANT DELETE, INSERT, SELECT, UPDATE ON  XHIBIT.AUD_CR_LIVE_INTERNET TO PUBLIC;


/* AUD_CR_LIVE_DISPLAY */

CREATE TABLE AUD_CR_LIVE_DISPLAY
(  
  CR_LIVE_DISPLAY_ID     NUMBER(8)              NOT NULL,
  COURT_ROOM_ID          NUMBER(8)              NOT NULL,
  SCHEDULED_HEARING_ID   NUMBER(8),
  TIME_STATUS_SET        DATE                   NOT NULL,
  STATUS       			 VARCHAR2(4000 BYTE),
  CREATED_BY             VARCHAR2(30 BYTE)      NOT NULL,
  CREATION_DATE          DATE                   NOT NULL,
  LAST_UPDATED_BY        VARCHAR2(30 BYTE)      NOT NULL,
  LAST_UPDATE_DATE       DATE                   NOT NULL,
  VERSION                NUMBER(5)              NOT NULL,
  INSERT_EVENT           VARCHAR2(1 BYTE)       NOT NULL
)
TABLESPACE AUDITD;

DROP PUBLIC SYNONYM AUD_CR_LIVE_DISPLAY;

CREATE PUBLIC SYNONYM AUD_CR_LIVE_DISPLAY FOR XHIBIT.AUD_CR_LIVE_DISPLAY;


GRANT DELETE, INSERT, SELECT, UPDATE ON  XHIBIT.AUD_CR_LIVE_DISPLAY TO PUBLIC;

/*
 * Changes, additions or deletion of sequences
 */

CREATE SEQUENCE XHIBIT.XHB_CASE_OVERNT_REFRESH_ID_SEQ
  START WITH 0
  NOMAXVALUE
  MINVALUE 0
  NOCYCLE
  NOCACHE
  NOORDER;

/* XHB_CR_LIVE_INTERNET_SEQ */

CREATE SEQUENCE XHB_CR_LIVE_INTERNET_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
/* XHB_CR_LIVE_DISPLAY_SEQ */

CREATE SEQUENCE XHB_CR_LIVE_DISPLAY_SEQ
  INCREMENT BY 1
  START WITH 1
  NOMAXVALUE
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


/*
 * Changes to XHB_ table triggers as a result of any XHB_ table modifications
 */

CREATE OR REPLACE TRIGGER XHIBIT.XHB_CASE_OVERNT_REFRESH_BIR_TR

  BEFORE INSERT
  ON XHB_CASE_OVERNIGHT_REFRESH 
  FOR EACH ROW

BEGIN

  IF :NEW.CASE_OVERNIGHT_REFRESH_ID IS NULL THEN

    SELECT XHB_CASE_OVERNT_REFRESH_ID_SEQ.NEXTVAL
    INTO   :NEW.CASE_OVERNIGHT_REFRESH_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;
  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/

SHOW ERRORS;


/* XHB_CR_LIVE_INTERNET_BIR_TR */

CREATE OR REPLACE TRIGGER XHB_CR_LIVE_INTERNET_BIR_TR
  BEFORE INSERT
  ON XHB_CR_LIVE_INTERNET
  FOR EACH ROW
BEGIN

  IF :NEW.CR_LIVE_INTERNET_ID IS NULL THEN

    SELECT XHB_CR_LIVE_INTERNET_SEQ.NEXTVAL
    INTO   :NEW.CR_LIVE_INTERNET_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/
SHOW ERRORS;


/* XHB_CR_LIVE_DISPLAY_BIR_TR */

CREATE OR REPLACE TRIGGER XHB_CR_LIVE_DISPLAY_BIR_TR
  BEFORE INSERT
  ON XHB_CR_LIVE_DISPLAY
  FOR EACH ROW
BEGIN

  IF :NEW.CR_LIVE_DISPLAY_ID IS NULL THEN

    SELECT XHB_CR_LIVE_DISPLAY_SEQ.NEXTVAL
    INTO   :NEW.CR_LIVE_DISPLAY_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END;
/
SHOW ERRORS;


/* XHB_CR_LIVE_INTERNET_BUR_TR */

CREATE OR REPLACE TRIGGER XHB_CR_LIVE_INTERNET_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CR_LIVE_INTERNET
  FOR EACH ROW
DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (Xhb_Custom_Pkg.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (Xhb_Custom_Pkg.IS_CONNECTION_POOL_USER = 0) THEN

        SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
        INTO   :NEW.LAST_UPDATED_BY
        FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (Xhb_Custom_Pkg.IS_AUDIT_REQUIRED('XHB_CR_LIVE_INTERNET') = 1) THEN

    INSERT INTO AUD_CR_LIVE_INTERNET
	   ( CR_LIVE_INTERNET_ID,
  	     COURT_ROOM_ID,
	     SCHEDULED_HEARING_ID,
	     TIME_STATUS_SET,
     	     STATUS,
	     CREATED_BY,
	     CREATION_DATE,
	     LAST_UPDATED_BY,
	     LAST_UPDATE_DATE,
	     VERSION,
  	     INSERT_EVENT)
    VALUES (:OLD.CR_LIVE_INTERNET_ID,
            :OLD.COURT_ROOM_ID,
            :OLD.SCHEDULED_HEARING_ID,
            :OLD.TIME_STATUS_SET,
            :OLD.STATUS,
            :OLD.CREATED_BY,
            :OLD.CREATION_DATE,
            :OLD.LAST_UPDATED_BY,
            :OLD.LAST_UPDATE_DATE,
            :OLD.VERSION,
            l_trig_event);

  END IF;

END;
/
SHOW ERRORS;


/* XHB_CR_LIVE_DISPLAY_BUR_TR */

CREATE OR REPLACE TRIGGER XHB_CR_LIVE_DISPLAY_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CR_LIVE_DISPLAY
  FOR EACH ROW
DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (Xhb_Custom_Pkg.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (Xhb_Custom_Pkg.IS_CONNECTION_POOL_USER = 0) THEN

        SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
        INTO   :NEW.LAST_UPDATED_BY
        FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (Xhb_Custom_Pkg.IS_AUDIT_REQUIRED('XHB_CR_LIVE_DISPLAY') = 1) THEN

    INSERT INTO AUD_CR_LIVE_DISPLAY
	   (CR_LIVE_DISPLAY_ID,
	    COURT_ROOM_ID,
	    SCHEDULED_HEARING_ID,
	    TIME_STATUS_SET,
	    STATUS,
	    CREATED_BY,
	    CREATION_DATE,
	    LAST_UPDATED_BY,
 	    LAST_UPDATE_DATE,
	    VERSION,
	    INSERT_EVENT)
    VALUES (:OLD.CR_LIVE_DISPLAY_ID,
            :OLD.COURT_ROOM_ID,
            :OLD.SCHEDULED_HEARING_ID,
            :OLD.TIME_STATUS_SET,
            :OLD.STATUS,
            :OLD.CREATED_BY,
            :OLD.CREATION_DATE,
            :OLD.LAST_UPDATED_BY,
            :OLD.LAST_UPDATE_DATE,
            :OLD.VERSION,
            l_trig_event);

  END IF;

END;
/
SHOW ERRORS;


/*
 * Changes, additions or deletion of packages/procedures/functions
 */

drop package xhibit.xhb_cr_live_status_pkg;

/*
 * Changes, additions or deletion of standing data
 */


/*
 * Changes, additions or deletion of data
 */

/* XHB_SYS_AUDIT */

INSERT INTO XHB_SYS_AUDIT 
   (TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE) 
 VALUES 
   ('XHB_CR_LIVE_INTERNET', 'AUD_CR_LIVE_INTERNET', 'Y');
   
   
INSERT INTO XHB_SYS_AUDIT 
   (TABLE_TO_AUDIT, AUDIT_TABLE, AUDITABLE) 
 VALUES 
   ('XHB_CR_LIVE_DISPLAY', 'AUD_CR_LIVE_DISPLAY', 'Y');
   
   
COMMIT;


/*
 * Updating of table XHB_VERSION
 */

/*
 * Updating of table XHB_VERSION
 */

DELETE FROM XHB_VERSION;

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'JAVACLIENT', '7.7.5', sysdate, 'RELEASE', 'Java Client Application', 1); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'JAVASERVER', '7.7.5', sysdate, 'RELEASE', 'Java Server Component', 2); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'XHIBIT', '7.7.5', sysdate , 'RELEASE', 'Database', 3); 

INSERT INTO XHB_VERSION ( SCHEMA_NAME, SCHEMA_VERSION, LAST_UPDATE_DATE, UPDATED_BY, DISPLAY_NAME, DISPLAY_SEQ ) 
VALUES ( 'MERCATOR', '7.7.5', sysdate, 'RELEASE', 'Mercator', 4); 

COMMIT;




*/  Create new or recreate stored procedures  */


@@code_release_control_77.sql
@@translation.sql

spool off