# Comma-separated list of servers
servers=default mercator helpweb dev guidev intenv

# Default server name
defaultServer=default

# Default login configuration name
defaultLoginConfig=xhibit

# Properties for the default server
default.AUTHENTICATION_URL=t3://midtier:7001
default.PROVIDER_URL=t3://midtier:7001
default.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

# Properties for the mercator server
mercator.AUTHENTICATION_URL=t3://mercator:7001
mercator.PROVIDER_URL=t3://mercator:7001
mercator.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

# Properties for the helpweb server
helpweb.AUTHENTICATION_URL=http://csa00100:5001
helpweb.PROVIDER_URL=http://csa00100:5001
helpweb.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

# Security implementation class to use
securityClass=uk.gov.courtservice.framework.security.WLSSecurityImpl

# XHibit datasource JNDI name
xhibit.datasourcename=@xhibit.tx.database.jndi@

# Exiss datasource JNDI name
exiss.datasourcename=@exiss.tx.database.jndi@

# Cjit datasource JNDI name
cjit.datasourcename=@cjit.tx.database.jndi@

# Gdgate datasource JNDI name
gdgate.datasourcename=@gdgate.tx.database.jndi@

# Darts datasource JNDI name
darts.datasourcename=@darts.tx.database.jndi@

# This is for testing, can be removed in production
xhibitprops.test.key=xhibitPropsTestValue

# Name of the list resource bundle that contains the business delegates
delegatebundle=uk.gov.courtservice.framework.client.delegate.BusinessDelegateBundle

# Name of the user session class
userSessionClass=uk.gov.courtservice.xhibit.client.util.security.CSUserSessionImpl

# URL prefix for Public Displays application
pubDispServer=http://presentation:7001/PublicDisplay/
helpWebsite=http://presentation:7001/xhibithelp/index.htm

# The filter class by the ENC local cache
encFilter.class=uk.gov.courtservice.framework.services.config.WlsEncFilter

# The URL for the Weblogic admin server which can be overridden using commandline property
admin.server.url=t3://adminserver:7001

# The name of the xhibit domain
xhibit.domain.name=xhibit

# Active directory defaults
activeDirectory.principal=weblogic
activeDirectory.credential=password
activeDirectory.url=ldap://130.177.3.42:389
activeDirectory.mbean=Security:Name=myrealmActiveDirectoryAuthenticator

####
# Development Servers
####

# Properties for the default server
intenv.AUTHENTICATION_URL=t3://csa00100:7001
intenv.PROVIDER_URL=t3://csa00100:7001
intenv.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

# Properties for the development server
dev.AUTHENTICATION_URL=t3://localhost:7001
dev.PROVIDER_URL=t3://localhost:7001
dev.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory

# Properties for the gui development server
guidev.AUTHENTICATION_URL=t3://uksps103:7001
guidev.PROVIDER_URL=t3://uksps103:7001
guidev.INITIAL_CONTEXT_FACTORY=weblogic.jndi.WLInitialContextFactory
