--New Release FRom Prison Order
INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (27, 'RPO', 1, 'XHIBIT', 'XHIBIT',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Release From Prison Order (5048)');


INSERT INTO XHB_ORDER_TEMPLATE VALUES (27,  '/metadata/OrderFOPTransform.xslt', '/metadata/RPO_Narrative.xml', '/metadata/RPOTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 27, NULL);


INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (27, 27, NULL, 0);


--New Notice of Acquittal Order
INSERT INTO XHB_ORDER_TYPE 
(ORDER_TYPE_ID, CODE, VERSION,  LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE, REF_DISPOSAL_TYPE_ID, DESCRIPTION)
VALUES (28, 'NAO', 1, 'XHIBIT', 'XHIBIT',TRUNC(SYSDATE), TRUNC(SYSDATE), NULL, 'Notice of Acquittal Order (5048A)');


INSERT INTO XHB_ORDER_TEMPLATE VALUES (28,  '/metadata/OrderFOPTransform.xslt', '/metadata/NAO_Narrative.xml', '/metadata/NAOTemplate.xml', 1, 'JUNIT', 'JUNIT', TRUNC(SYSDATE), TRUNC(SYSDATE), 28, NULL);


INSERT INTO XHB_ORDER_TYPE_MAPPING (ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, REPLACED_BY, VERSION)
VALUES (28, 28, NULL, 0);



commit;
