/* This script will be used to update Production from 0_4y to the latest level - 0_4z */
/* This update is adds a version table to the CJSE database in order to keep track of schema versions */

/* Added new rows to the CJI_DOCUMENT_TYPE table  */

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION,
 BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 23, 'DLD', 'Daily List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION,
 BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 24, 'FLD', 'Firm List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION, 
 BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 25, 'WLD', 'Warned List for Distribution',  'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION,
 BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 26, 'DLL', 'Daily List Letters', 'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');

INSERT INTO CJI_DOCUMENT_TYPE ( DOCUMENT_TYPE_ID, INTERNAL_CODE, INTERNAL_NAME, EXTERNAL_NAME, STYLESHEET_NAME, SECURITY_CLASSIFICATION,
 BITS_DOCUMENT_CONFIG, BITS_TRANSFORM_CONFIG, REGISTERED_IN_CJSE, REGISTER_AGAINST_LOCATION, REGISTER_AGAINST_CRN, REGISTER_AGAINST_DEFENDANT, SCHEMA_NAME )
VALUES ( 27, 'FLL', 'Firm List Letters', 'Unknown', 'Unknown', 'NPM', 'Unknown', 'Unknown', 'N', 'N', 'N', 'N', 'Unknown');



UPDATE CJI_VERSION Set
SCHEMA_VERSION = '0_4z',
last_update_date = sysdate,
Updated_by = 'XHIBIT',
Display_name = 'CJSE Database Schema 0_4z',
Display_seq = 1
Where SCHEMA_NAME = 'CJSE';
