-- Create Sequence
CREATE SEQUENCE HK_CPP_RUN_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER NOCYCLE;

-- Results Table
CREATE TABLE XHB_HK_CPP_RESULTS (
	HK_CPP_RUN_ID				NUMBER(10)	PRIMARY KEY,
	RUN_START_DATE				DATE,
	RUN_END_DATE				DATE,
	LIST_STATUS					VARCHAR2(1), 
	LIST_ERROR_MESSAGE			VARCHAR2(2000),
	LIST_ERROR					NUMBER(6),
	LIST_DELETED				NUMBER(6),
	IWP_STATUS					VARCHAR2(1), 
	IWP_ERROR_MESSAGE			VARCHAR2(2000),
	IWP_ERROR					NUMBER(6),
	IWP_DELETED					NUMBER(6),
	PD_STATUS					VARCHAR2(1), 
	PD_ERROR_MESSAGE			VARCHAR2(2000),
	PD_ERROR					NUMBER(6),
	PD_DELETED					NUMBER(6),
	STAGING_STATUS				VARCHAR2(1), 
	STAGING_ERROR_MESSAGE		VARCHAR2(2000),
	STAGING_ERROR				NUMBER(6),
	STAGING_DELETED				NUMBER(6)
);

-- Error Table
CREATE TABLE XHB_HK_CPP_ERROR_LOG (
	HK_CPP_RUN_ID	NUMBER(10)	NOT NULL,
	ERROR_MESSAGE	VARCHAR2(500)
);