sittingId=SITTING_ID
sittingSeqNo=SITTING_SEQUENCE_NO
sittingAt=SITTING_TIME
floating=IS_FLOATING
sittingNote=SITTING_NOTE
courtRoomId=COURT_ROOM_ID
courtRoomName=COURT_ROOM_NAME
crestCourtRoomNo=CREST_COURT_ROOM_NO
courtRoomDisplayName=DISPLAY_NAME



