/***************************************/
/* CJIT Table and Sequence SQL - v0.04t*/
/***************************************/


CREATE TABLE CJI_PARAMETER_VALUE (
	PARAMETER_NAME VARCHAR2 ( 30 ) NOT NULL,
	PARAMETER_VALUE VARCHAR2 ( 255 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_PARAMETER_VALUE
       ADD  (PRIMARY KEY (PARAMETER_NAME)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_CJIP_MESSAGE_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_CJIP_MESSAGE_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_AHM_AGG_STATUS (
	AGG_STATUS_ID NUMBER ( 5 ) NOT NULL,
	STATUS_ID NUMBER ( 8 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_AHM_AGG_STATUS
       ADD  (PRIMARY KEY (AGG_STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_AHM_REPLY_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_AHM_REPLY_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_BITS_MESSAGE (
	MESSAGE_CORRELATION_ID VARCHAR2 ( 20 ) NOT NULL,
	DOCUMENT_ID NUMBER NOT NULL,
	SENT_DATE DATE NOT NULL,
	RESPONSE_CLASS VARCHAR2 ( 20 ),
	RESPONSE_CODE NUMBER ( 8 ),
	RESPONSE_DESCRIPTION VARCHAR2 ( 50 ),
	ESCALATIONS CLOB,
	RECEIVE_DATE DATE,
	OPERATION_TYPE_ID NUMBER NOT NULL,
	OPERATION_CORRELATION_ID VARCHAR2 ( 38 ),
	REQUEST_ID NUMBER
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_BITS_MESSAGE
       ADD  (PRIMARY KEY (MESSAGE_CORRELATION_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_AHM_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_AHM_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_CJIP_REQUEST_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_CJIP_REQUEST_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_DOCUMENT_TYPE (
	DOCUMENT_TYPE_ID NUMBER ( 8 ) NOT NULL,
	INTERNAL_CODE CHAR ( 3 ) NOT NULL,
	INTERNAL_NAME VARCHAR2 ( 100 ) NOT NULL,
	EXTERNAL_NAME VARCHAR2 ( 50 ) NOT NULL,
	STYLESHEET_NAME VARCHAR2 ( 255 ),
	SCHEMA_NAME VARCHAR2 ( 255 ),
	SECURITY_CLASSIFICATION VARCHAR2 ( 50 ) NOT NULL,
	BITS_DOCUMENT_CONFIG VARCHAR2 ( 50 ),
	BITS_TRANSFORM_CONFIG VARCHAR2 ( 50 ),
	REGISTERED_IN_CJSE VARCHAR2 ( 1 ) NOT NULL,
	REGISTER_AGAINST_LOCATION VARCHAR2 ( 1 ) NOT NULL,
	REGISTER_AGAINST_CRN VARCHAR2 ( 1 ) NOT NULL,
	REGISTER_AGAINST_DEFENDANT VARCHAR2 ( 1 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_DOCUMENT_TYPE
       ADD  (PRIMARY KEY (DOCUMENT_TYPE_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_DOCUMENT_SECURITY (
	DOCUMENT_SECURITY_ID NUMBER ( 8 ) NOT NULL,
	DOCUMENT_TYPE_ID NUMBER ( 8 ) NOT NULL,
	CJO_ROLE_ID NUMBER ( 8 ) NOT NULL,
	CREATION_DATE DATE NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_DOCUMENT_SECURITY
       ADD  (PRIMARY KEY (DOCUMENT_SECURITY_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_EVENT_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_EVENT_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_DOCUMENT (
	DOCUMENT_ID NUMBER ( 8 ) NOT NULL,
	EXT_DOCUMENT_ID VARCHAR2 ( 21 ),
	CONTENT CLOB,
	DOCUMENT_TYPE_ID NUMBER ( 8 ) NOT NULL,
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STYLESHEET_NAME VARCHAR2 ( 255 ),
	CREATION_DATE DATE,
	BITS_REGISTERING_LOCATION VARCHAR2 ( 50 ),
	BITS_DOCUMENT_NAME VARCHAR2 ( 50 ),
	BITS_DOCUMENT_DESCRIPTION VARCHAR2 ( 200 ),
	BITS_DOCUMENT_COMMENT VARCHAR2 ( 512 ),
	BITS_REGISTRATION_DATE DATE,
	SRC_DOCUMENT_KEY VarChar2(255)
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_DOCUMENT
       ADD  (PRIMARY KEY (DOCUMENT_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_CJIP_MESSAGE (
	CORRELATION_ID VARCHAR2 ( 38 ) NOT NULL,
	MESSAGE_CORRELATION_ID VARCHAR2 ( 38 ),
	OPERATION_REQUEST VARCHAR2 ( 50 ),
	OPERATION_DATA CLOB,
	SENT_DATE DATE,
	RECEIVED_DATE DATE,
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	RESPONSE_STATUS VARCHAR2 ( 20 ),
	RESPONSE_CODE NUMBER ( 8 ),
	RESPONSE_DESCRIPTION VARCHAR2 ( 1000 ),
	EVENT_ID NUMBER ( 8 ),
	DOCUMENT_ID NUMBER ( 8 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_CJIP_MESSAGE
       ADD  (PRIMARY KEY (CORRELATION_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_BITS_MESSAGE_OPERATIONS (
	OPERATION_TYPE_ID NUMBER ( 8 ) NOT NULL,
	OPERATION_TYPE_TEXT VARCHAR2 ( 50 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_BITS_MESSAGE_OPERATIONS
       ADD  (PRIMARY KEY (OPERATION_TYPE_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_DOCUMENT_STATUS (
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	STATUS_TEXT VARCHAR2 ( 30 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_DOCUMENT_STATUS
       ADD  (PRIMARY KEY (STATUS_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_CJIP_REQUEST (
	REQUEST_ID NUMBER ( 8 ) NOT NULL,
	EXT_CORRELATION_ID VARCHAR2 ( 50 ),
	EXT_MESSAGE_CORRELATION_ID VARCHAR2 ( 50 ),
	OPERATION_REQUEST VARCHAR2 ( 30 ),
	OPERATION_DATA CLOB,
	RECEIVED_DATE DATE,
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	EXT_DOCUMENT_ID VARCHAR2 ( 21 ),
	SENT_DATE DATE,
	RESPONSE_STATUS VARCHAR2 ( 20 ),
	RESPONSE_CODE NUMBER ( 8 ),
	RESPONSE_DESCRIPTION VARCHAR2 ( 1000 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/

ALTER TABLE CJI_CJIP_REQUEST
       ADD  (PRIMARY KEY (REQUEST_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/

CREATE TABLE CJI_AHM (
	MESSAGE_ID NUMBER ( 8 ) NOT NULL,
	AGGREGATOR_ID VARCHAR2 ( 40 ),
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	CONTENT CLOB NOT NULL,
	RESPONSE_CODE VARCHAR2 ( 50 ),
	TEL VARCHAR2 ( 20 ) NOT NULL,
	DEVICE_ID NUMBER ( 8 ) NOT NULL,
	SENT_AGG_DATE DATE NOT NULL,
	SENT_PRO_DATE DATE,
	ORGINAL_SENDER VARCHAR2 ( 100 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/
ALTER TABLE CJI_AHM
       ADD  (PRIMARY KEY (MESSAGE_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/

CREATE TABLE CJI_AHM_DEVICE_TYPE (
	DEVICE_ID NUMBER ( 8 ) NOT NULL,
	DEVICE_TEXT VARCHAR2 ( 30 ) NOT NULL,
	DEVICE_MOBILESYS_REF VARCHAR2 ( 30 ) NOT NULL
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/
ALTER TABLE CJI_AHM_DEVICE_TYPE
       ADD  (PRIMARY KEY (DEVICE_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/

CREATE TABLE CJI_CJO_ROLE (
	CJO_ROLE_ID NUMBER ( 8 ) NOT NULL,
	CODE VARCHAR2 ( 3 ),
	NAME VARCHAR2 ( 20 ),
	EXTERNAL_NAME VARCHAR2 ( 50 ),
	DESCRIPTION VARCHAR2 ( 50 ),
	ROLE_IN_USE VARCHAR2 ( 1 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/
ALTER TABLE CJI_CJO_ROLE
       ADD  (PRIMARY KEY (CJO_ROLE_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/


CREATE TABLE CJI_EVENT_OPERATION_REQUEST (
	OPERATION_ID NUMBER ( 8 ) NOT NULL,
	OPERATION_TEXT VARCHAR2 ( 50 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/
ALTER TABLE CJI_EVENT_OPERATION_REQUEST
       ADD  (PRIMARY KEY (OPERATION_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/

CREATE TABLE CJI_EVENT (
	EVENT_ID NUMBER ( 8 ) NOT NULL,
	OPERATION_DATA CLOB,
	STATUS_ID NUMBER ( 8 ) NOT NULL,
	EVENT_TYPE NUMBER ( 8 ),
	IDENTIFIER VARCHAR2 ( 30 ),
	RECEIVED_DATE DATE,
	OPERATION_ID NUMBER ( 8 ) NOT NULL,
	BITS_REGISTERING_LOCATION VARCHAR2 ( 50 )
	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )

/
ALTER TABLE CJI_EVENT
       ADD  (PRIMARY KEY (EVENT_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/
CREATE TABLE CJI_AHM_REPLY (
	REPLY_ID NUMBER NOT NULL,
	AGGREGATOR_REPLY_ID VARCHAR2 ( 40 ),
	STATUS_ID NUMBER NOT NULL,
	RECEIVED_DATE DATE NOT NULL,
	CONTENT VARCHAR2 ( 1000 ),
	RESPONSE_CODE VARCHAR2 ( 50 ),
	MESSAGE_ID NUMBER	)
TABLESPACE DATAD
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  )
/
ALTER TABLE CJI_AHM_REPLY
       ADD  (PRIMARY KEY (REPLY_ID)
       USING INDEX
      TABLESPACE DATAX
   STORAGE  (
   INITIAL 1M
   NEXT 1M
   PCTINCREASE 0 
  ) ) 
/

ALTER TABLE CJI_AHM_AGG_STATUS ADD ( CONSTRAINT FK_CJI_AHM_AGG_STATUS155 FOREIGN KEY (STATUS_ID) REFERENCES CJI_AHM_STATUS (STATUS_ID))
/
ALTER TABLE CJI_BITS_MESSAGE ADD ( CONSTRAINT FK_CJI_BITS_MESSAGE161 FOREIGN KEY (OPERATION_TYPE_ID) REFERENCES CJI_BITS_MESSAGE_OPERATIONS (OPERATION_TYPE_ID))
/
ALTER TABLE CJI_BITS_MESSAGE ADD ( CONSTRAINT FK_CJI_BITS_MESSAGE156 FOREIGN KEY (REQUEST_ID) REFERENCES CJI_CJIP_REQUEST (REQUEST_ID))
/
ALTER TABLE CJI_BITS_MESSAGE ADD ( CONSTRAINT FK_CJI_BITS_MESSAGE155 FOREIGN KEY (DOCUMENT_ID) REFERENCES CJI_DOCUMENT (DOCUMENT_ID))
/
ALTER TABLE CJI_DOCUMENT_SECURITY ADD ( CONSTRAINT FK_CJI_DOCUMENT_SECURITY5 FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES CJI_DOCUMENT_TYPE (DOCUMENT_TYPE_ID))
/
ALTER TABLE CJI_DOCUMENT_SECURITY ADD ( CONSTRAINT FK_CJI_DOCUMENT_SECURITY160 FOREIGN KEY (CJO_ROLE_ID) REFERENCES CJI_CJO_ROLE (CJO_ROLE_ID))
/
ALTER TABLE CJI_DOCUMENT ADD ( CONSTRAINT FK_CJI_DOCUMENT1 FOREIGN KEY (DOCUMENT_TYPE_ID) REFERENCES CJI_DOCUMENT_TYPE (DOCUMENT_TYPE_ID))
/
ALTER TABLE CJI_DOCUMENT ADD ( CONSTRAINT FK_CJI_DOCUMENT159 FOREIGN KEY (STATUS_ID) REFERENCES CJI_DOCUMENT_STATUS (STATUS_ID))
/
ALTER TABLE CJI_CJIP_MESSAGE ADD ( CONSTRAINT FK_CJI_CJIP_MESSAGE155 FOREIGN KEY (EVENT_ID) REFERENCES CJI_EVENT (EVENT_ID))
/
ALTER TABLE CJI_CJIP_MESSAGE ADD ( CONSTRAINT FK_CJI_CJIP_MESSAGE8 FOREIGN KEY (DOCUMENT_ID) REFERENCES CJI_DOCUMENT (DOCUMENT_ID))
/
ALTER TABLE CJI_CJIP_MESSAGE ADD ( CONSTRAINT FK_CJI_CJIP_MESSAGE9 FOREIGN KEY (STATUS_ID) REFERENCES CJI_CJIP_MESSAGE_STATUS (STATUS_ID))
/
ALTER TABLE CJI_CJIP_REQUEST ADD ( CONSTRAINT FK_CJI_CJIP_REQUEST15 FOREIGN KEY (STATUS_ID) REFERENCES CJI_CJIP_REQUEST_STATUS (STATUS_ID))
/
ALTER TABLE CJI_AHM ADD ( CONSTRAINT FK_CJI_ADHOC_MESSAGE12 FOREIGN KEY (DEVICE_ID) REFERENCES CJI_AHM_DEVICE_TYPE (DEVICE_ID))
/
ALTER TABLE CJI_AHM ADD ( CONSTRAINT FK_CJI_ADHOC_MESSAGE158 FOREIGN KEY (STATUS_ID) REFERENCES CJI_AHM_STATUS (STATUS_ID))
/
ALTER TABLE CJI_EVENT ADD ( CONSTRAINT FK_CJI_EVENT162 FOREIGN KEY (OPERATION_ID) REFERENCES CJI_EVENT_OPERATION_REQUEST (OPERATION_ID))
/
ALTER TABLE CJI_EVENT ADD ( CONSTRAINT FK_CJI_EVENT7 FOREIGN KEY (STATUS_ID) REFERENCES CJI_EVENT_STATUS (STATUS_ID))
/
ALTER TABLE CJI_AHM_REPLY ADD ( CONSTRAINT FK_CJI_ADHOC_MESSAGE_REPLY156 FOREIGN KEY (MESSAGE_ID) REFERENCES CJI_AHM (MESSAGE_ID))
/
ALTER TABLE CJI_AHM_REPLY ADD ( CONSTRAINT FK_CJI_ADHOC_MESSAGE_REPLY155 FOREIGN KEY (STATUS_ID) REFERENCES CJI_AHM_REPLY_STATUS (STATUS_ID))
/
COMMENT ON TABLE CJI_PARAMETER_VALUE IS 'This table is to hold any key/value pairs that may be required by the system.'
/
COMMENT ON TABLE CJI_CJIP_REQUEST IS 'This table is used to store all information passed to the CSH when the CJIP requests the contents of a document, as well as the CSH''s responses to those requests.'
/
COMMENT ON COLUMN CJI_PARAMETER_VALUE.PARAMETER_NAME IS 'Name of Parameter'
/
COMMENT ON COLUMN CJI_PARAMETER_VALUE.PARAMETER_VALUE IS 'Value of Parameter'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.MESSAGE_CORRELATION_ID IS 'Primary key. Value derived from a Sequence'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.DOCUMENT_ID IS 'Key to Document Table'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.SENT_DATE IS 'Date BITS registry message sent.
(Date that the record was written into the table)'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.RESPONSE_CLASS IS 'From CJSE Status Mesage:
For example: ''completed-with-errors'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.RESPONSE_CODE IS 'From CJSE Status Mesage:
For example: 102400'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.RESPONSE_DESCRIPTION IS 'From CJSE Status Mesage:
For example: ''Not all entities were created'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.ESCALATIONS IS 'From CJSE Status Mesage:
XML Escalation Text.'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.RECEIVE_DATE IS 'Date CJSE status information received from BITS'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.OPERATION_TYPE_ID IS 'Which operation is being performed :

Registration or Servicing a Request'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.OPERATION_CORRELATION_ID IS 'Relates to ''Document Requests'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE.REQUEST_ID IS 'Links to CJIP Request 
- only valid for document requests'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.DOCUMENT_TYPE_ID IS 'Primary key - unique key
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.INTERNAL_CODE IS 'Internal Code eg. DL
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.INTERNAL_NAME IS 'Internal Document Name e.g. Daily List
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.EXTERNAL_NAME IS 'External Document Type Code. E.g. COMMPUNISHMENTANDREHABORDER

Used by CJSE
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.STYLESHEET_NAME IS 'Used when filling CJI_DOCUMENT with name of Stylesheet to use

'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.SECURITY_CLASSIFICATION IS 'Security Classification  - Used in Document'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.BITS_DOCUMENT_CONFIG IS 'Defines BITS File to use. Eg DailyListConfig
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.BITS_TRANSFORM_CONFIG IS 'Name of BITS Trabsformation Config File to use'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.REGISTERED_IN_CJSE IS 'Boolean, If Y then this document should be sent to CJSE
Otherwise the Mercator maps should ignore the document
'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.REGISTER_AGAINST_LOCATION IS '"Y" if this document should be registered against a Location'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.REGISTER_AGAINST_CRN IS '"Y" if this document should be registered against a CRN'
/
COMMENT ON COLUMN CJI_DOCUMENT_TYPE.REGISTER_AGAINST_DEFENDANT IS '"Y" if this document should be registered against a Defendant'
/
COMMENT ON COLUMN CJI_DOCUMENT_SECURITY.DOCUMENT_SECURITY_ID IS 'Primary key ID. Used internally.'
/
COMMENT ON COLUMN CJI_DOCUMENT_SECURITY.DOCUMENT_TYPE_ID IS 'Foreign Key to CJI_DOCUMENT_TYPE Table.  Type of document stored - DailyList, Firm List etc.
'
/
COMMENT ON COLUMN CJI_DOCUMENT_SECURITY.CJO_ROLE_ID IS 'Used to access the Role - e.g.CC, POLice
'
/
COMMENT ON COLUMN CJI_DOCUMENT_SECURITY.CREATION_DATE IS 'Date and time that this record was created or amended'
/
COMMENT ON COLUMN CJI_EVENT_STATUS.STATUS_ID IS 'Aribitary Key'
/
COMMENT ON COLUMN CJI_EVENT_STATUS.STATUS_TEXT IS 'Status - such as New or Sent'
/
COMMENT ON COLUMN CJI_DOCUMENT.DOCUMENT_ID IS 'Generated by using the next number in a defined sequence - CJI_DOCUMENT_SEQ'
/
COMMENT ON COLUMN CJI_DOCUMENT.EXT_DOCUMENT_ID IS 'CJIT Team Field only'
/
COMMENT ON COLUMN CJI_DOCUMENT.CONTENT IS 'The XML Document is written to this field
'
/
COMMENT ON COLUMN CJI_DOCUMENT.DOCUMENT_TYPE_ID IS 'The type of Document is written here.
Defines which Document Type it is e.g.Daily List'
/
COMMENT ON COLUMN CJI_DOCUMENT.STATUS_ID IS 'Status of Document, New, Delete etc
'
/
COMMENT ON COLUMN CJI_DOCUMENT.STYLESHEET_NAME IS 'Defines the Stylesheet that the document should be transformed with
'
/
COMMENT ON COLUMN CJI_DOCUMENT.CREATION_DATE IS 'Date and time stamp of when the document is written to the Document Store

'
/
COMMENT ON COLUMN CJI_DOCUMENT.BITS_REGISTERING_LOCATION IS 'The 3 Digit Court Identifier e.g. 453  (Snaresbrook)
that the document belongs to'
/
COMMENT ON COLUMN CJI_DOCUMENT.BITS_DOCUMENT_NAME IS 'Name of the document.  For example:
Daily List 12/12/2000 Version X

Assume that the court clerks give the document title if not  the name of the Document and a Date will suffice'
/
COMMENT ON COLUMN CJI_DOCUMENT.BITS_DOCUMENT_DESCRIPTION IS 'An expansion of the Document Name. For example: Daily List  Snaresbrook Crown Court 12/12/2000 Version X 
'
/
COMMENT ON COLUMN CJI_DOCUMENT.BITS_DOCUMENT_COMMENT IS 'Used for Narrative Text in the Notifications Section - Initially not used'
/
COMMENT ON COLUMN CJI_DOCUMENT.BITS_REGISTRATION_DATE IS 'Date that the Documeny was registered with CJSE.  IF empty then Registration has not occured yet or has failed'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.CORRELATION_ID IS 'Primary key. Operation Correlation ID.
- Taken from a sequence'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.MESSAGE_CORRELATION_ID IS 'Batch Message Correlation ID. - based on a sequence
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.OPERATION_REQUEST IS 'OperationType: Eg: CreateDefendantOperation. May or may not be filled in from CJI_EVENT_OPERATION_REQUEST table.
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.OPERATION_DATA IS 'XML Used to satisfy the Operation
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.SENT_DATE IS 'Date and Time of Message Sent to CJIP
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.RECEIVED_DATE IS 'Date and Time of CJIP status response Received
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.STATUS_ID IS 'Status table linkh
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.RESPONSE_STATUS IS 'Status of message received from CJIP. E.g.: Completed CompletedWithErrors MessageFailed RetriableFailed SystemFailed TransactionFailed StatusUpdate 
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.RESPONSE_CODE IS 'Status of message received from CJIP. 
E.g. 0
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.RESPONSE_DESCRIPTION IS 'Status of message received from CJIP. 
Returned Message Description
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.EVENT_ID IS 'Primary key ID. Used internally. If it is an Event Operation this will be populated - otherwise it will be NULL
'
/
COMMENT ON COLUMN CJI_CJIP_MESSAGE.DOCUMENT_ID IS 'Used only for document Operations.
 If it is an Document Request Operation this will be populated - otherwise it will be NULL
'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE_OPERATIONS.OPERATION_TYPE_ID IS 'Arbitary Key'
/
COMMENT ON COLUMN CJI_BITS_MESSAGE_OPERATIONS.OPERATION_TYPE_TEXT IS 'Registration Request or Document Request Fulfilment'
/
COMMENT ON COLUMN CJI_DOCUMENT_STATUS.STATUS_ID IS 'Status ID - arbitarilyu assigned'
/
COMMENT ON COLUMN CJI_DOCUMENT_STATUS.STATUS_TEXT IS 'Status that the document is in - for example: New, Delete, registered'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.REQUEST_ID IS 'Primary key. Internal use only..'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.EXT_CORRELATION_ID IS 'Operation Correlation ID supplied by requesting system. One per operation.'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.EXT_MESSAGE_CORRELATION_ID IS 'Message Correlation ID supplied by requesting system. One per batched message.'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.OPERATION_REQUEST IS 'Specific request type. Eg GetDocumentContent'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.OPERATION_DATA IS 'XML of request operation.'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.RECEIVED_DATE IS 'Date and Time of CJIP request received
'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.STATUS_ID IS 'Status table
'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.EXT_DOCUMENT_ID IS 'Document ID to be retreived. Should match a EXT_DOCUMENT_ID from the DOCUMENT table but is not a foreign key.
'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.SENT_DATE IS 'Date document sent to CJIP.'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.RESPONSE_STATUS IS ' Status of message passed back to CJIP. E.g. Completed CompletedWithErrors MessageFailed RetriableFailed SystemFailed TransactionFailed StatusUpdate
'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.RESPONSE_CODE IS 'E.g. 0
'
/
COMMENT ON COLUMN CJI_CJIP_REQUEST.RESPONSE_DESCRIPTION IS 'Returned Message Description'
/
COMMENT ON COLUMN CJI_AHM.MESSAGE_ID IS 'Primary key. - generated from a Sequence'
/
COMMENT ON COLUMN CJI_AHM.AGGREGATOR_ID IS 'Aggregator ID of message.
'
/
COMMENT ON COLUMN CJI_AHM.CONTENT IS 'Message Type (eg. Register Document).  Will hold text of SMS.'
/
COMMENT ON COLUMN CJI_AHM.RESPONSE_CODE IS 'Response code generated by XHIBIT to define location of message origin'
/
COMMENT ON COLUMN CJI_AHM.TEL IS 'Telephone number to send to.'
/
COMMENT ON COLUMN CJI_AHM.DEVICE_ID IS 'Device Type Lookup'
/
COMMENT ON COLUMN CJI_AHM.SENT_AGG_DATE IS 'Date and Time of Message sent to Aggregator'
/
COMMENT ON COLUMN CJI_AHM.SENT_PRO_DATE IS 'Date and Time of Message sent to Mobile by the Aggregator
'
/
COMMENT ON COLUMN CJI_AHM.ORGINAL_SENDER IS 'Text description of original sender - e.g. Snaresbrook - room 1'
/
COMMENT ON COLUMN CJI_CJO_ROLE.CJO_ROLE_ID IS 'Primary key ID. Arbitary Key value
'
/
COMMENT ON COLUMN CJI_CJO_ROLE.CODE IS 'Abbreviation of name e.g. POL;CC;CPS 
Code used internally.
'
/
COMMENT ON COLUMN CJI_CJO_ROLE.NAME IS 'CJO Role Name.  Used internally within Court Service.
'
/
COMMENT ON COLUMN CJI_CJO_ROLE.EXTERNAL_NAME IS 'CJO External Role Name - passed to CJSE
'
/
COMMENT ON COLUMN CJI_CJO_ROLE.DESCRIPTION IS 'Description of Role
'
/
COMMENT ON COLUMN CJI_CJO_ROLE.ROLE_IN_USE IS 'Used to switch off a CJO
Boolean "Y" means in use'
/
COMMENT ON COLUMN CJI_EVENT_OPERATION_REQUEST.OPERATION_ID IS 'Aribary Key'
/
COMMENT ON COLUMN CJI_EVENT_OPERATION_REQUEST.OPERATION_TEXT IS 'Operation Text - as sent to CJIP'
/
COMMENT ON COLUMN CJI_EVENT.EVENT_ID IS 'Primary key ID. Used internally. Based on a Sequence
'
/
COMMENT ON COLUMN CJI_EVENT.OPERATION_DATA IS 'XML of Event
- based on ''BusinessEventParamaters'
/
COMMENT ON COLUMN CJI_EVENT.STATUS_ID IS 'Status of event. New or sent.
'
/
COMMENT ON COLUMN CJI_EVENT.EVENT_TYPE IS 'ID of specific event type.e.g. for ''Bench Warrant Executed'' it may be 1538
'
/
COMMENT ON COLUMN CJI_EVENT.IDENTIFIER IS 'CaseID or CRN ID (or DefendantID, DocumentID) sent to CJIP as part of XML.
'
/
COMMENT ON COLUMN CJI_EVENT.RECEIVED_DATE IS 'Event Received from Xhibit Date Time Stamp
'
/
COMMENT ON COLUMN CJI_EVENT.OPERATION_ID IS 'Link'
/
COMMENT ON COLUMN CJI_AHM_REPLY.REPLY_ID IS 'Primary key. Internal use only. From a Sequence'
/
COMMENT ON COLUMN CJI_AHM_REPLY.AGGREGATOR_REPLY_ID IS 'Aggregator ID of reply.'
/
COMMENT ON COLUMN CJI_AHM_REPLY.RECEIVED_DATE IS 'DateTime Stamp of Message Received - time written into the database
'
/
COMMENT ON COLUMN CJI_AHM_REPLY.CONTENT IS 'Content of Reply'
/
COMMENT ON COLUMN CJI_AHM_REPLY.RESPONSE_CODE IS 'Response Code used in the reply - empty if not found
'
/
COMMENT ON COLUMN CJI_AHM_REPLY.MESSAGE_ID IS 'Primary key of related message.  If Response_code was not found then this will be NULL'
/

/*************************************/
/* Sequences                         */
/*************************************/

Create sequence CJI_DOCUMENT_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_EVENT_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_AHM_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_AHM_REPLY_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_CJIP_REQUEST_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_BITS_MESSAGE_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_CJIP_MESSAGE_SEQ INCREMENT BY 1 START WITH 1;
Create sequence CJI_CJIP_OPERATION_MESSAGE_SEQ INCREMENT BY 1 START WITH 1;
