INSERT INTO XHB_REF_DISPOSAL_TYPE
(REF_DISPOSAL_TYPE_ID,
TEMPLATE_VERSION,
DISPOSAL_CODE,
MENU_GROUP,
COURT_ID,
OBS_IND,
CATEGORY,
LINE_AVAIL,
DISP_TITLE2,
DISP_TITLE1,
TITLE)
SELECT 
XHB_REF_DISPOSAL_TYPE_SEQ.NEXTVAL REF_DISPOSAL_TYPE_ID,
xrdt.TEMPLATE_VERSION+1 TEMPLATE_VERSION,
xrdt.DISPOSAL_CODE,
xrdt.MENU_GROUP,
xrdt.COURT_ID,
'N' OBS_IND,
xrdt.CATEGORY,
xrdt.LINE_AVAIL,
xrdt.DISP_TITLE2,
xrdt.DISP_TITLE1,
xrdt.TITLE
FROM XHB_REF_DISPOSAL_TYPE xrdt,
     (SELECT 'STS' DISPOSAL_CODE, 
             2 TEMPLATE_VERSION 
        FROM DUAL) subqry
WHERE xrdt.DISPOSAL_CODE = subqry.DISPOSAL_CODE
  AND xrdt.TEMPLATE_VERSION = subqry.TEMPLATE_VERSION-1
  AND NOT EXISTS (SELECT NULL FROM XHB_REF_DISPOSAL_TYPE xrdt2 
                   WHERE xrdt2.DISPOSAL_CODE = xrdt.DISPOSAL_CODE 
                     AND xrdt2.COURT_ID = xrdt.COURT_ID
                     AND xrdt2.TEMPLATE_VERSION = xrdt.TEMPLATE_VERSION+1);

INSERT INTO XHB_REF_DISPOSAL_LINE
  (REF_DISPOSAL_LINE_ID,
  DISPOSAL_CODE,
  TEMPLATE_VERSION,
  DIL_SEQ_NO,
  COURT_ID,
  LINE_INSERT,
  MULTIPLE_CHOICE,
  MANDATORY,
  FORM_PRINT,
  SCREEN_PRINT,
  INPUT_FLAG,
  OBS_IND,
  VALIDATION,
  DBSOURCE,
  CONC_FLAG,
  FORMAT,
  DATA,
  DBDESTIN,
  CHAR_MAX,
  MCGROUP2,
  MCGROUP1,
  PROMPT)
SELECT
  XHB_REF_DISPOSAL_LINE_SEQ.NEXTVAL REF_DISPOSAL_LINE_ID,
  xrdl.DISPOSAL_CODE,
  subqry.TEMPLATE_VERSION,
  xrdl.DIL_SEQ_NO,
  xrdl.COURT_ID,
  xrdl.LINE_INSERT,
  xrdl.MULTIPLE_CHOICE,
  xrdl.MANDATORY,
  xrdl.FORM_PRINT,
  xrdl.SCREEN_PRINT,
  xrdl.INPUT_FLAG,
  'N' OBS_IND,
  xrdl.VALIDATION,
  xrdl.DBSOURCE,
  xrdl.CONC_FLAG,
  xrdl.FORMAT,
  CASE
    WHEN xrdl.DIL_SEQ_NO = 21 THEN 'The court ordered that the defendant be sentenced to imprisonment'
    WHEN xrdl.DIL_SEQ_NO = 57 THEN 'under section 282a Sentencing Act 2020 as follows: An extended sentence of'
    ELSE xrdl.DATA END DATA,
  xrdl.DBDESTIN,
  xrdl.CHAR_MAX,
  xrdl.MCGROUP2,
  xrdl.MCGROUP1,
  xrdl.PROMPT
FROM XHB_REF_DISPOSAL_LINE xrdl,
     (SELECT 'STS' DISPOSAL_CODE, 
             2 TEMPLATE_VERSION 
        FROM DUAL) subqry
WHERE xrdl.DISPOSAL_CODE = subqry.DISPOSAL_CODE
  AND xrdl.DIL_SEQ_NO NOT IN (30, 40, 45, 50, 55)
  AND xrdl.template_version = subqry.TEMPLATE_VERSION-1
  AND NOT EXISTS (SELECT NULL FROM XHB_REF_DISPOSAL_LINE xrdl2 
                   WHERE xrdl2.DISPOSAL_CODE = subqry.DISPOSAL_CODE 
                     AND xrdl2.COURT_ID = xrdl.COURT_ID
                     AND xrdl2.TEMPLATE_VERSION = subqry.TEMPLATE_VERSION
                     AND xrdl2.DIL_SEQ_NO = xrdl.DIL_SEQ_NO);

COMMIT;
/