INSERT INTO XHB_REF_EVENT_DESCRIPTION 
(EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS)
SELECT subqry.EXTERNAL_EVENT_CODE, 'Capture Sentence' EVENT_DESCRIPTION, subqry.DISPOSAL_CODE EVENT_SUB_DESCRIPTION, 'Y' SEND_TO_MIS FROM (
	SELECT 11532 EXTERNAL_EVENT_CODE, 'STS1821' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12811 EXTERNAL_EVENT_CODE, 'ALTCT' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12812 EXTERNAL_EVENT_CODE, 'JDIS' DISPOSAL_CODE  FROM DUAL UNION
	SELECT 12813 EXTERNAL_EVENT_CODE, 'DISCH' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12814 EXTERNAL_EVENT_CODE, 'NGDIR' DISPOSAL_CODE  FROM DUAL UNION
	SELECT 12815 EXTERNAL_EVENT_CODE, 'NGINS' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12816 EXTERNAL_EVENT_CODE, 'NOEV' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12817 EXTERNAL_EVENT_CODE, 'NOEVS' DISPOSAL_CODE  FROM DUAL UNION
	SELECT 12818 EXTERNAL_EVENT_CODE, 'UTA' DISPOSAL_CODE FROM DUAL UNION
	SELECT 12514 EXTERNAL_EVENT_CODE, 'DTCO' DISPOSAL_CODE FROM DUAL
) subqry 
WHERE NOT EXISTS (SELECT 1 FROM XHB_REF_EVENT_DESCRIPTION x2 
                   WHERE x2.EXTERNAL_EVENT_CODE = subqry.EXTERNAL_EVENT_CODE
                     AND x2.EVENT_SUB_DESCRIPTION = subqry.DISPOSAL_CODE);
commit;