<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="ActiveDirectory">

    <description>
        Code to access user information from AD and terminal info from AD and XHB_TERMINAL.
    </description>

    <import file="./../../tools/ant/framework.xml" />

    <property name="project.type.controller.bean"      value="marker" />
    <property name="project.type.requires.compilation" value="marker" />

    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="Framework.jar" />
                <include name="XhibitEnvironment.jar" />
                <include name="XhibitSecurityProviders.jar"/>
            </fileset>
        </path>
    </target>

    <!--
      =======================================================================
        Release Override
      =======================================================================
      -->
    <target name="release" unless="skip.release" depends="framework.release">
        <log target="release"/>
        <copy todir="${build.dest.dir}">
            <fileset dir="${client.build.dir}" />
        </copy>
    </target>

</project>
