ALTER TABLE XHB_CASE_DIARY_TIME_RQMT ADD
(
	PRE_DEF_NOTE_CLASSIFICATION_ID      NUMBER(8),
	FREETXT_NOTE_CLASSIFICATION_ID      NUMBER(8),
    VACATION_PRE_DEFINED_REASON_ID      NUMBER(8),
    VACATION_FREETEXT_REASON            VARCHAR2(200),
    STATUS                              VARCHAR2(1)
);

ALTER TABLE XHB_CASE_DIARY_TIME_RQMT ADD (CONSTRAINT CDTR_LIST_NOTE_PRE_DEFND_ID_FK FOREIGN KEY (LIST_NOTE_PRE_DEFINED_ID) REFERENCES XHB_REF_LISTING_DATA(REF_LISTING_DATA_ID));
ALTER TABLE XHB_CASE_DIARY_TIME_RQMT ADD (CONSTRAINT CDTR_PRE_DEF_NOTE_CLASS_ID_FK FOREIGN KEY (PRE_DEF_NOTE_CLASSIFICATION_ID) REFERENCES XHB_REF_LISTING_DATA(REF_LISTING_DATA_ID));
ALTER TABLE XHB_CASE_DIARY_TIME_RQMT ADD (CONSTRAINT CDTR_FREETXT_NOTE_CLASS_ID_FK FOREIGN KEY (FREETXT_NOTE_CLASSIFICATION_ID) REFERENCES XHB_REF_LISTING_DATA(REF_LISTING_DATA_ID));
ALTER TABLE XHB_CASE_DIARY_TIME_RQMT ADD (CONSTRAINT CDTR_VAC_PRE_DEFD_REASON_ID_FK FOREIGN KEY (VACATION_PRE_DEFINED_REASON_ID) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));

ALTER TABLE AUD_CASE_DIARY_TIME_RQMT ADD
(
	PRE_DEF_NOTE_CLASSIFICATION_ID      NUMBER(8),
	FREETXT_NOTE_CLASSIFICATION_ID      NUMBER(8),
    VACATION_PRE_DEFINED_REASON_ID      NUMBER(8),
    VACATION_FREETEXT_REASON            VARCHAR2(200),
    STATUS                              VARCHAR2(1)
);

@@xhb_case_diary_time_rqmt_bur_tr.sql;

COMMIT;