ALTER TABLE XHB_TIME_RQMT_DEFT_ATTENDING ADD (CONSTRAINT TRDA_DEFENDANT_ON_CASE_ID_FK FOREIGN KEY (DEFENDANT_ON_CASE_ID) REFERENCES XHB_DEFENDANT_ON_CASE(DEFENDANT_ON_CASE_ID));
ALTER TABLE XHB_TIME_RQMT_DEFT_ATTENDING ADD (CONSTRAINT TRDA_CASE_DIRY_TIME_RQMT_ID_FK FOREIGN KEY (CASE_DIARY_TIME_RQMT_ID) REFERENCES XHB_CASE_DIARY_TIME_RQMT(CASE_DIARY_TIME_RQMT_ID));

COMMIT;