ALTER TABLE XHB_CASE ADD
(
	CRACKED_INEFFECTIVE_ID	NUMBER(8),
	DEFAULT_HEARING_TYPE	NUMBER(8)
);

ALTER TABLE XHB_CASE ADD (CONSTRAINT CASE_CRACKED_INEFFECTIVE_ID_FK FOREIGN KEY (CRACKED_INEFFECTIVE_ID) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));
ALTER TABLE XHB_CASE ADD (CONSTRAINT CASE_DEFAULT_HEARING_TYPE_FK FOREIGN KEY (DEFAULT_HEARING_TYPE) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));

ALTER TABLE AUD_CASE ADD
(
	CRACKED_INEFFECTIVE_ID	NUMBER(8),
	DEFAULT_HEARING_TYPE	NUMBER(8)
);

@@xhb_case_bur_tr.sql;

COMMIT;