ALTER TABLE XHB_CASE_LISTING_ENTRY MODIFY
(
	REF_JUDGE_TYPE_ID	NUMBER(8)
);

ALTER TABLE XHB_CASE_LISTING_ENTRY ADD (CONSTRAINT CASE_LISTING_JUDGE_TYPE_ID_FK FOREIGN KEY (REF_JUDGE_TYPE_ID) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));
ALTER TABLE XHB_CASE_LISTING_ENTRY ADD (CONSTRAINT CASE_LISTING_TICKET_TYPE_ID_FK FOREIGN KEY (TICKET_TYPE_ID) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));

ALTER TABLE AUD_CASE_LISTING_ENTRY MODIFY
(
	REF_JUDGE_TYPE_ID	NUMBER(8)
);

COMMIT;