ALTER TABLE XHB_DIARY_NOTE_ENTRY MODIFY
(
	CASE_LISTING_ENTRY_ID NULL,
	DIARY_START_DATE NULL,
	DIARY_END_DATE NULL
);

ALTER TABLE XHB_DIARY_NOTE_ENTRY ADD (CONSTRAINT DNE_DIARY_NOTE_PRE_DEFND_ID_FK FOREIGN KEY (DIARY_NOTE_PRE_DEFINED_ID) REFERENCES XHB_REF_LISTING_DATA(REF_LISTING_DATA_ID));

ALTER TABLE AUD_DIARY_NOTE_ENTRY MODIFY
(
	CASE_LISTING_ENTRY_ID NULL,
	DIARY_START_DATE NULL,
	DIARY_END_DATE NULL
);

@@xhb_diary_note_entry_bur_tr.sql;

COMMIT;