<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="InstantMessaging">

    <description>
        Framework code for instant messaging
    </description>

    <import file="./../../tools/ant/framework.xml" />

    <property name="project.type.builds.jar" value="marker" />
    <property name="project.type.requires.compilation" value="marker" />
    
    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}" includes="Framework.jar" />
        </path>
    </target>

</project>


