create or replace TRIGGER xhb_ref_broadcast_case_bur_tr
  BEFORE UPDATE OR DELETE
  ON XHB_REFUSED_BROADCAST_CASE
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  IF UPDATING THEN

    l_trig_event := 'U';

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

 /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_REFUSED_BROADCAST_CASE') = 1) THEN

    INSERT INTO AUD_REFUSED_BROADCAST_CASE
    VALUES (:old.REFUSED_BROADCAST_CASE_ID,
	:old.CASE_ID,
	:old.TELE_APP_REFUSED_REASON_ID,
	:old.OBS_IND,
	:old.LAST_UPDATE_DATE,
	:old.CREATION_DATE,
	:old.LAST_UPDATED_BY,
	:old.CREATED_BY,
	:old.VERSION,
        l_trig_event);
  END IF;

END;
/