ALTER TABLE XHB_CASE ADD TELEVISED_APPLICATION_MADE VARCHAR2(1);
ALTER TABLE XHB_CASE ADD TELEVISED_APP_MADE_DATE DATE;
ALTER TABLE XHB_CASE ADD TELEVISED_APP_GRANTED VARCHAR2(1);
ALTER TABLE XHB_CASE ADD TELEVISED_APP_REFUSED_FREETEXT VARCHAR2(280);
ALTER TABLE XHB_CASE ADD TELEVISED_REMARKS_FILMED VARCHAR2(1);

ALTER TABLE AUD_CASE ADD TELEVISED_APPLICATION_MADE VARCHAR2(1);
ALTER TABLE AUD_CASE ADD TELEVISED_APP_MADE_DATE DATE;
ALTER TABLE AUD_CASE ADD TELEVISED_APP_GRANTED VARCHAR2(1);
ALTER TABLE AUD_CASE ADD TELEVISED_APP_REFUSED_FREETEXT VARCHAR2(280);
ALTER TABLE AUD_CASE ADD TELEVISED_REMARKS_FILMED VARCHAR2(1);


@xhb_case_ai_tr.sql;
@xhb_case_bur_tr.sql;

commit;