insert into XHB_ORDER_TYPE_MAPPING(ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) values 
(29, 29, 1, 'XHIBIT', 'XHIBIT', sysdate, sysdate);

insert into XHB_ORDER_TYPE_MAPPING(ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) values 
(30, 30, 1, 'XHIBIT', 'XHIBIT', sysdate, sysdate);

insert into XHB_ORDER_TYPE_MAPPING(ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) values 
(31, 31, 1, 'XHIBIT', 'XHIBIT', sysdate, sysdate);

insert into XHB_ORDER_TYPE_MAPPING(ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) values 
(32, 32, 1, 'XHIBIT', 'XHIBIT', sysdate, sysdate);

insert into XHB_ORDER_TYPE_MAPPING(ORDER_TYPE_MAPPING_ID, ORDER_TYPE_ID, VERSION, LAST_UPDATED_BY, CREATED_BY, CREATION_DATE, LAST_UPDATE_DATE) values 
(33, 33, 1, 'XHIBIT', 'XHIBIT', sysdate, sysdate);

commit;
/