create or replace TRIGGER XHB_DEFENDANTONCASE_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHIBIT.XHB_DEFENDANT_ON_CASE   FOR EACH ROW
/* ERwin Builtin Tue May 06 14:13:58 2003 */
/* default body for XHB_DEFENDANTONCASE_BUR_TR */
/* J Riley 19/06/2018 ctx-2156 Added column NATIONALITY to audit table update (previously omitted)  */
/* M Groen 17/05/2019 ctx-4216 Added column CTL_APPLIES to audit table update   */
/* M Groen 17/05/2019 ctx-4216 Added columns DRIVING_DISQ_SUSPENDED_DATE, MAG_COURT_FIRST_HEARING_DATE,
		MAG_COURT_FINAL_HEARING_DATE, to audit table update (previously omitted)  */
/* C Vincent 17/06/2019 ctx-4216 ignore updates to DIFFERENCE_REPORT and COA_STATUS which will only
		be made by the broker and can cause optimistic locking errors.  CTX-4313 */
DECLARE

  l_trig_event VARCHAR2(1) := NULL;
  l_ignore_audit	VARCHAR2(1) := 'N';

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN
  
	l_trig_event := 'U';
  
	IF (:OLD.DIFFERENCE_REPORT != :NEW.DIFFERENCE_REPORT)
	OR (:OLD.DIFFERENCE_REPORT IS NULL AND :NEW.DIFFERENCE_REPORT IS NOT NULL)
	OR (:OLD.DIFFERENCE_REPORT IS NOT NULL AND :NEW.DIFFERENCE_REPORT IS NULL) THEN
		l_ignore_audit := 'Y';
	ELSIF (:OLD.COA_STATUS != :NEW.COA_STATUS)
	OR (:OLD.COA_STATUS IS NULL AND :NEW.COA_STATUS IS NOT NULL)
	OR (:OLD.COA_STATUS IS NOT NULL AND :NEW.COA_STATUS IS NULL) THEN
		l_ignore_audit := 'Y';
	ELSE

		/* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
		IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

		  IF (:OLD.VERSION != :NEW.VERSION) THEN
		  /* Someone has pulled the rug out from below! */

			RAISE OPTIMISTIC_LOCK_PROB;

		  END IF;

		END IF;

		SELECT :OLD.VERSION + 1,
			   SYSDATE
		INTO   :NEW.VERSION,
			   :NEW.LAST_UPDATE_DATE
		FROM   DUAL;

		/* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
		IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

		  SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
		  INTO   :NEW.LAST_UPDATED_BY
		  FROM   DUAL;

		END IF;
	END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_DEFENDANT_ON_CASE') = 1 AND l_ignore_audit = 'N') THEN

    INSERT INTO AUD_DEFENDANT_ON_CASE
		(DEFENDANT_ON_CASE_ID,
		NO_OF_TICS,
		FINAL_DRIVING_LICENCE_STATUS,
		PTIURN,
		IS_JUVENILE,
		IS_MASKED,
		MASKED_NAME,
		CASE_ID,
		DEFENDANT_ID,
		LAST_UPDATE_DATE,
		CREATION_DATE,
		CREATED_BY,
		LAST_UPDATED_BY,
		VERSION,
		OBS_IND,
		RESULTS_VERIFIED,
		DEFENDANT_NUMBER,
		DATE_OF_COMMITTAL,
		PNC_ID,
		COLLECT_MAGISTRATE_COURT_ID,
		INSERT_EVENT,
		CURRENT_BC_STATUS,
		ASN,
		BENCH_WARRANT_EXEC_DATE,
		COMM_BC_STATUS,
		BC_STATUS_BW_EXECUTED,
		SPECIAL_CIR_FOUND,
		CUSTODIAL,
		SUSPENDED,
		SERIOUS_DRUG_OFFENCE,
		RECOMMENDED_DEPORTATION,
		DATE_EXPORTED,
		FIRST_FIXED_TRIAL,
		FIRST_HEARING_TYPE,
        NATIONALITY, 
		PUBLIC_DISPLAY_HIDE,
		AMENDED_DATE_EXPORTED,
		AMENDED_REASON,
		HATE_IND,
		HATE_TYPE,
		HATE_SENT_IND,
		DRIVING_DISQ_SUSPENDED_DATE,
		MAG_COURT_FIRST_HEARING_DATE,
		MAG_COURT_FINAL_HEARING_DATE,
		CUSTODY_TIME_LIMIT,
		FORM_NG_SENT_DATE,
		CACD_APPEAL_RESULT_DATE,
		SECTION28_NAME1,
		SECTION28_NAME2,
		SECTION28_PHONE1,
		SECTION28_PHONE2,
		DIFFERENCE_REPORT,
   		DATE_RCPT_NOTICE_APPEAL,
    	CACD_APPEAL_RESULT,
    	COA_STATUS,
		CTL_APPLIES)
    VALUES (:OLD.DEFENDANT_ON_CASE_ID,
		:OLD.NO_OF_TICS,
		:OLD.FINAL_DRIVING_LICENCE_STATUS,
		:OLD.PTIURN,
		:OLD.IS_JUVENILE,
		:OLD.IS_MASKED,
		:OLD.MASKED_NAME,
		:OLD.CASE_ID,
		:OLD.DEFENDANT_ID,
		:OLD.LAST_UPDATE_DATE,
		:OLD.CREATION_DATE,
		:OLD.CREATED_BY,
		:OLD.LAST_UPDATED_BY,
		:OLD.VERSION,
		:OLD.OBS_IND,
		:OLD.RESULTS_VERIFIED,
		:OLD.DEFENDANT_NUMBER,
		:OLD.DATE_OF_COMMITTAL,
		:OLD.PNC_ID,
		:OLD.COLLECT_MAGISTRATE_COURT_ID,
		l_trig_event,
		:OLD.CURRENT_BC_STATUS,
		:OLD.ASN,
		:OLD.BENCH_WARRANT_EXEC_DATE,
		:OLD.COMM_BC_STATUS,
		:OLD.BC_STATUS_BW_EXECUTED,
		:OLD.SPECIAL_CIR_FOUND,
		:OLD.CUSTODIAL,
		:OLD.SUSPENDED,
		:OLD.SERIOUS_DRUG_OFFENCE,
		:OLD.RECOMMENDED_DEPORTATION,
		:OLD.DATE_EXPORTED,
		:OLD.FIRST_FIXED_TRIAL,
		:OLD.FIRST_HEARING_TYPE,
        :OLD.NATIONALITY, 
		:OLD.PUBLIC_DISPLAY_HIDE,
		:OLD.AMENDED_DATE_EXPORTED,
		:OLD.AMENDED_REASON,
		:OLD.HATE_IND,
		:OLD.HATE_TYPE,
		:OLD.HATE_SENT_IND,
		:OLD.DRIVING_DISQ_SUSPENDED_DATE,
		:OLD.MAG_COURT_FIRST_HEARING_DATE,
		:OLD.MAG_COURT_FINAL_HEARING_DATE,
		:OLD.CUSTODY_TIME_LIMIT,
		:old.FORM_NG_SENT_DATE,
		:old.CACD_APPEAL_RESULT_DATE,
		:OLD.SECTION28_NAME1,
		:OLD.SECTION28_NAME2,
		:OLD.SECTION28_PHONE1,
		:OLD.SECTION28_PHONE2,
		:OLD.DIFFERENCE_REPORT,
		:OLD.DATE_RCPT_NOTICE_APPEAL,
		:OLD.CACD_APPEAL_RESULT,
		:OLD.COA_STATUS,
		:OLD.CTL_APPLIES
    );

  END IF;

END;
/