<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="ProbationService">

    <description>
        This project contains the files for the midtier for the probation
        service cjo application
    </description>

    <import file="./../../tools/ant/framework.xml" />

    <property name="project.type.controller.bean"      value="marker" />
    <property name="project.type.requires.compilation" value="marker" />

    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="EmailHelper.jar" />
                <include name="Framework.jar" />
                <include name="Config.jar" />
                <include name="SysAdminEntities.jar" />
                <include name="Value.jar" />
                <include name="ViewScheduleController.jar" />
                <include name="XhibitEntities.jar" />
                <include name="XhibitValues.jar" />
            </fileset>
        </path>
    </target>

    <!--
      =======================================================================
        Release Override
      =======================================================================
      -->
    <target name="release" unless="skip.release" depends="framework.release">
        <log target="release"/>
        <copy todir="${build.dest.dir}">
            <fileset dir="${client.build.dir}" />
        </copy>
    </target>

</project>
