#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      Edward Cawley, Xdevelopment LLP (2003)
#

responses = selectcourt;updatecourtcomplete;selectterminal;updateterminalcomplete;selectcourtcourtsite;updatecourtcourtsitecomplete;loggedout;errordetailscomplete;errorsummarycomplete

#
# Select Court
#

selectcourt.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
selectcourt.page = cookie.jsp
selectcourt.skeletonTitleKey = selectcourt.title
selectcourt.skeletonBodyKey = selectcourt

#
# Update Court Complete
#


updatecourtcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.RedirectResponse
updatecourtcomplete.url = home

#
# Select Terminal
#

selectterminal.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
selectterminal.page = cookie.jsp
selectterminal.skeletonTitleKey = selectterminal.title
selectterminal.skeletonBodyKey = selectterminal

#
# Update Terminal Complete
#

updateterminalcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.RedirectResponse
updateterminalcomplete.url = home

#
# Select Court & Court Site
#

selectcourtcourtsite.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
selectcourtcourtsite.page = cookie.jsp
selectcourtcourtsite.skeletonTitleKey = selectcourtcourtsite.title
selectcourtcourtsite.skeletonBodyKey = selectcourtcourtsite

#
# Update Court & Court Site Complete
#

updatecourtcourtsitecomplete.class = uk.gov.courtservice.xhibit.web.framework.response.RedirectResponse
updatecourtcourtsitecomplete.url = home

#
# Logged out
#

loggedout.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
loggedout.page = login.jsp

#
# Error summary Information
#
errorsummarycomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
errorsummarycomplete.page = normal.jsp
errorsummarycomplete.skeletonBodyKey = errormessage
errorsummarycomplete.skeletonTitleKey = error.title

#
# Stack Trace Detailed Information
#
errordetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
errordetailscomplete.page = normal.jsp
errordetailscomplete.skeletonBodyKey = stacktrace
errordetailscomplete.skeletonTitleKey = detailederror.title

