#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      Edward Cawley, Xdevelopment LLP (2003)
#

actions = updatecourt;updateterminal;logout;errordetails;errorsummary

#
#  Update Court action
#

updatecourt.request = /updatecourt
updatecourt.class = uk.gov.courtservice.xhibit.web.action.UpdateCourtCookieAction

#
#  Update Terminal action
#

updateterminal.request = /updateterminal
updateterminal.class = uk.gov.courtservice.xhibit.web.action.UpdateTerminalCookieAction


#
#  Update Court and Court Site action
#

#updatecourtcourtsite.request = /updatecourtcourtsite
#updatecourtcourtsite.class = uk.gov.courtservice.xhibit.web.action.UpdateCourtCourtSiteCookieAction

#
#  Logout action
#

logout.request = /logout
logout.class = uk.gov.courtservice.xhibit.web.action.LogoutAction

#
# View Error details
#
errordetails.request = /errordetails
errordetails.class = uk.gov.courtservice.xhibit.web.action.ErrorDetailsAction

#
#  View Error summary information
#

errorsummary.request = /errorsummary
errorsummary.class = uk.gov.courtservice.xhibit.web.action.ErrorSummaryAction

