#
# Title:       shared Pages
#
# Description: This is the default Pages property file, it forms part of an
#              i18n resource bundle. ALL page urls should be accessed through
#              here this means if more complex i18n is required the jsps used
#              can be overriden by implementing a specific instance of the
#              Pages bundle. The preference is to use the same jsps and the
#              messages resource bundle.
#
# Example:     <!- Include the JSTL tag library -->
#              <%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt" %>
#              <!- As pages is not the default message bundle must specify -->
#              <fmt:bundle basename="Pages">
#                  <!- Retrieve the localised page url -->
#                  <fmt:message key="header.text"/>
#              </fmt:bundle>
#
#

#
# Login (and login error) pages
#

loginMenu = loginmenu.jsp
loginBody = loginbody.jsp

#
# Framework pages
#

skeleton = skeleton.jsp
skeletonwithmessages = skeletonwithmessages.jsp
terminalskeleton = terminalskeleton.jsp
header = header.jsp
footer = footer.jsp
menu = menu.jsp
error = errormessage.jsp
button = button.jsp
buttonSpacer = buttonspacer.jsp

#
# shared pages
#

selectterminal = selectterminal.jsp
selectcourt = selectcourt.jsp
selectcourtcourtsite = selectcourtcourtsite.jsp
stacktrace = stacktrace.jsp
errormessage = errormessage.jsp

# end of shared pages
