#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#

actions = default;displaymessages;sendinstantmessage;instantmessagesent;sendadhocmessage;sendwitnessadhocmessage;adhocmessagesent;errordetails;adhocwitnessmessagesent

#
# Default Mapping
#

default.request=/home
default.class=uk.gov.courtservice.xhibit.web.messaging.action.DefaultAction

#
# View Messages Action
#
displaymessages.request=/displaymessages
displaymessages.class=uk.gov.courtservice.xhibit.web.messaging.action.DisplayMessagesAction

#
# Send Instant Message Action
#
sendinstantmessage.request=/sendinstantmessage
sendinstantmessage.class=uk.gov.courtservice.xhibit.web.messaging.action.SendInstantMessageAction

#
# Instant Message Sent Action
#
instantmessagesent.request=/instantmessagesent
instantmessagesent.class=uk.gov.courtservice.xhibit.web.messaging.action.InstantMessageSentAction

#
# Send Ad Hoc Mesage Action
#
sendadhocmessage.request=/sendadhocmessage
sendadhocmessage.class=uk.gov.courtservice.xhibit.web.messaging.action.SendAdHocMessageAction

#
# Send Witness Ad Hoc Mesage Action
#
sendwitnessadhocmessage.request=/sendwitnessadhocmessage
sendwitnessadhocmessage.class=uk.gov.courtservice.xhibit.web.messaging.action.SendWitnessAdHocMessageAction

#
# Ad Hoc Witness Mesage Sent Action
#
adhocwitnessmessagesent.request=/adhocwitnessmessagesent
adhocwitnessmessagesent.class=uk.gov.courtservice.xhibit.web.messaging.action.AdHocWitnessMessageSent

#
# Ad Hoc Message Sent Action
#
adhocmessagesent.request=/adhocmessagesent
adhocmessagesent.class=uk.gov.courtservice.xhibit.web.messaging.action.AdHocMessageSentAction

#
# Error details action
#

errordetails.request = /errordetails
errordetails.class = uk.gov.courtservice.xhibit.web.messaging.action.ErrorDetailsAction

