#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#

responses = home;displaymessagescomplete;sendinstantmessagecomplete;instantmessagesentcomplete;sendadhocmessagecomplete;adhocmessagesentcomplete;errordetailscomplete;sendwitnessadhocmessagecomplete

#
# Default Mapping
#

home.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page=NewMessageCheck.jsp
home.skeletonBodyKey=home
home.skeletonTitleKey=home.title

#
# Display Messages
#
displaymessagescomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
displaymessagescomplete.page=messagebox.jsp
displaymessagescomplete.skeletonBodyKey=displaymessages
displaymessagescomplete.skeletonTitleKey=displaymessages.title

#
# Send Instant Message
#
sendinstantmessagecomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
sendinstantmessagecomplete.page=messagebox.jsp
sendinstantmessagecomplete.skeletonBodyKey=sendinstantmessage
sendinstantmessagecomplete.skeletonTitleKey=sendinstantmessage.title

#
# Instant Message Sent
#
instantmessagesentcomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
instantmessagesentcomplete.page=messagebox.jsp
instantmessagesentcomplete.skeletonBodyKey=sentmessage
instantmessagesentcomplete.skeletonTitleKey=sentmessage.title

#
# Send Ad Hoc Message
#
sendadhocmessagecomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
sendadhocmessagecomplete.page=messagebox.jsp
sendadhocmessagecomplete.skeletonBodyKey=sendadhocmessage
sendadhocmessagecomplete.skeletonTitleKey=sendadhocmessage.title

#
# Send Ad Hoc Message
#
sendwitnessadhocmessagecomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
sendwitnessadhocmessagecomplete.page=messagebox.jsp
sendwitnessadhocmessagecomplete.skeletonBodyKey=sendwitnessadhocmessage
sendwitnessadhocmessagecomplete.skeletonTitleKey=sendwitnessadhocmessage.title



#
# Ad Hoc Message Sent
#
adhocmessagesentcomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
adhocmessagesentcomplete.page=messagebox.jsp
adhocmessagesentcomplete.skeletonBodyKey=sentmessage
adhocmessagesentcomplete.skeletonTitleKey=sentmessage.title


#
# Error Details
#
errordetailscomplete.class=uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
errordetailscomplete.page=stacktrace.jsp
