USE CSDBPRD1;

-- Blackfriars Court 4
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('BLACKFRIARS - Court Detail - Court 4', 'pd://document:53/CourtDetail:916',429);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('BLACKFRIARS - Court List - Court 4', 'pd://document:53/CourtList:916',429);

-- Preston Sessions House Court 1
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court Detail - Court 1', 'pd://document:15/CourtDetail:207',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court List - Court 1', 'pd://document:15/CourtList:207',90);

-- Preston Sessions House Court 2
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court Detail - Court 2', 'pd://document:15/CourtDetail:208',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court List - Court 2', 'pd://document:15/CourtList:208',90);

-- Preston Sessions House Court 3
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court Detail - Court 3', 'pd://document:15/CourtDetail:209',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Court List - Court 3', 'pd://document:15/CourtList:209',90);

-- Preston Sessions House General Pages
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - All Court Status', 'pd://document:15/AllCourtStatus:207,208,209,u',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - All Case Status', 'pd://document:15/AllCaseStatus:207,208,209,u',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Jury Current Status', 'pd://document:15/JurtCurrentStatus:207,208,209,u',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Summary By Name', 'pd://document:15/SummaryByName:207,208,209,u',90);
INSERT INTO XHB_DISP_MGR_URL (DESCRIPTION,URL,COURT_SITE_ID) VALUES ('PRESTON SESSIONS HOUSE - Daily List', 'pd://document:15/DailyList:207,208,209,u',90);

-- Southend
UPDATE XHB_DISP_MGR_URL SET URL = 'pd://document:10/AllCaseStatus:121,122,123,124,125,126,127,u' WHERE URL = 'pd://document:10/AllCaseStatus:126,127,u';