##
#Configuration file for scheduled tasks.
#
#Deliberately not part of the Config.jar as it is
#likely to be edited by the application deployer.
##

##
#Current tasks for scheduling.
##
scheduledtasks.midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask,cppstagingtask
scheduledtasks.midM2=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask,cppstagingtask
scheduledtasks.midM3=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask,cppstagingtask

##
# Test/Dev
##
scheduledtasks.DevTest_as1_midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest_as2_midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest_as3_midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest_as4_midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask

scheduledtasks.DevTest1midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest2midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest3midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.DevTest4midM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask

##
# NLE
##
scheduledtasks.PREPRODmidM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PREPRODmidM2=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PREPRODmidM3=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PREPRODmidM4=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.PREPRODmidM5=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask

##
# Live
##

scheduledtasks.PRODmidM1=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PRODmidM2=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PRODmidM3=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask
scheduledtasks.PRODmidM4=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,courtellisttask,cppformattingtask,pddatask
scheduledtasks.PRODmidM5=transformtask,listdistributiontask,ahmpollertask,courtlogtask,dartsmessagetask1,dartsmessagetask2,dartsmessagetask3,dartsprioritymessagetask,cppformattingtask,pddatask

##
#Configuration for courtlogtask.
#¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
#This task initializes the court log queue.
#This task is run only once
##
courtlogtask.strategy=uk.gov.courtservice.framework.scheduler.JavaTaskStrategy
courtlogtask.class=uk.gov.courtservice.xhibit.courtlog.async.CourtLogTask

##
#Configuration for Transforming documents
#Description: This task is to query XHB_FORMATTING for documents to process
##
transformtask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
transformtask.remotehome=uk.gov.courtservice.xhibit.business.services.formatting.FormattingControllerHome
transformtask.lookup=FormattingControllerHome
transformtask.fixedrate=false
transformtask.delay=60000
transformtask.period=5000

##
#Configuration for production of letters
#Description: This task is to query XHB_WLL_CONTROL for ditribution lists to create letters from.
##
listdistributiontask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
listdistributiontask.remotehome=uk.gov.courtservice.xhibit.business.services.listdistribution.ListDistribution2ControllerHome
listdistributiontask.lookup=ListDistribution2ControllerHome
listdistributiontask.fixedrate=false
listdistributiontask.delay=62500
listdistributiontask.period=5000

##
#Configuration for production of letters
#Description: This task is to query XHB_CPP_STAGING_INBOUND to process any incoming documents from Common Platform (CPP)
##
cppstagingtask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
cppstagingtask.remotehome=uk.gov.courtservice.xhibit.business.services.cpp.CPPInitialProcessingControllerHome
cppstagingtask.lookup=CPPInitialProcessingControllerHome
cppstagingtask.fixedrate=false
cppstagingtask.delay=62500
cppstagingtask.period=5000

##
#Configuration for production of letters
#Description: This task is to generate jms messages from db events.
##
messagegeneratortask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
messagegeneratortask.remotehome=uk.gov.courtservice.xhibit.business.services.messagegenerator.MessageGeneratorControllerHome
messagegeneratortask.lookup=MessageGeneratorControllerHome
messagegeneratortask.fixedrate=false
messagegeneratortask.delay=65000
messagegeneratortask.period=5000

##
#Configuration of courtel task
#Description: courtel task.
##
courtellisttask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
courtellisttask.remotehome=uk.gov.courtservice.xhibit.business.services.courtel.controller.CourtelListControllerHome
courtellisttask.lookup=CourtelListControllerHome
courtellisttask.fixedrate=false
courtellisttask.delay=65000
courtellisttask.period=5000

##
#Configuration for PDDA message polling
#Description: This task is to generate jms messages from db events.
##
pddatask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
pddatask.remotehome=uk.gov.courtservice.xhibit.business.services.publicnotice.PublicNoticeControllerHome
pddatask.lookup=PublicNoticeControllerHome
pddatask.fixedrate=false
pddatask.delay=5000
pddatask.period=5000

##
#Configuration for DARTS message polling
#Description: This task is to generate jms messages from db events.
##
cppformattingtask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
cppformattingtask.remotehome=uk.gov.courtservice.xhibit.business.services.cppformatting.CppFormattingControllerHome
cppformattingtask.lookup=CppFormattingControllerHome
cppformattingtask.fixedrate=false
cppformattingtask.delay=65000
cppformattingtask.period=30000
## First Sender
#dartsmessagetask1.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#dartsmessagetask1.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsNormalSenderHome
#dartsmessagetask1.lookup=DartsNormalSenderSessionHome
#dartsmessagetask1.fixedrate=false
#dartsmessagetask1.delay=65000
#dartsmessagetask1.period=5000
## Second Sender
#dartsmessagetask2.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#dartsmessagetask2.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsNormalSenderHome
#dartsmessagetask2.lookup=DartsNormalSenderSessionHome
#dartsmessagetask2.fixedrate=false
#dartsmessagetask2.delay=65000
#dartsmessagetask2.period=5000
## Third Sender
#dartsmessagetask3.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#dartsmessagetask3.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsNormalSenderHome
#dartsmessagetask3.lookup=DartsNormalSenderSessionHome
#dartsmessagetask3.fixedrate=false
#dartsmessagetask3.delay=65000
#dartsmessagetask3.period=5000

##
#Configuration for DARTS message polling
#Description: This task is to generate jms messages from db events.
##
#dartsprioritymessagetask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#dartsprioritymessagetask.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsPrioritySenderHome
#dartsprioritymessagetask.lookup=DartsPrioritySenderSessionHome
#dartsprioritymessagetask.fixedrate=false
#dartsprioritymessagetask.delay=65000
#dartsprioritymessagetask.period=5000

##
#Configuration for DARTS message polling
#Description: This task is to generate jms messages from db events.
##
## First Sender
##
#Configuration for DARTS message polling
#Description: This task is to generate jms messages from db events.
##
## First Sender
dartsmessagetask1.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
dartsmessagetask1.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsNormalSenderWSHome
dartsmessagetask1.lookup=DartsNormalSenderSessionHomeWS
dartsmessagetask1.fixedrate=false
dartsmessagetask1.delay=65000
dartsmessagetask1.period=5000
## Second Sender
dartsmessagetask2.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
dartsmessagetask2.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsSwitchSenderWSHome
dartsmessagetask2.lookup=DartsSwitchSenderSessionHomeWS
dartsmessagetask2.fixedrate=false
dartsmessagetask2.delay=65000
dartsmessagetask2.period=5000
## Third Sender
dartsmessagetask3.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
dartsmessagetask3.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsSwitchSenderWSHome
dartsmessagetask3.lookup=DartsSwitchSenderSessionHomeWS
dartsmessagetask3.fixedrate=false
dartsmessagetask3.delay=65000
dartsmessagetask3.period=5000

##
#Configuration for DARTS message polling
#Description: This task is to generate jms messages from db events.
##
dartsprioritymessagetask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
dartsprioritymessagetask.remotehome=uk.gov.courtservice.xhibit.business.services.dartsmessagesender.DartsPrioritySenderWSHome
dartsprioritymessagetask.lookup=DartsPrioritySenderSessionHomeWS
dartsprioritymessagetask.fixedrate=false
dartsprioritymessagetask.delay=65000
dartsprioritymessagetask.period=5000



##
#Configuration for ahmpollertask.
#¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
#This task periodically polls the
#message store DB for incoming
#replies to AdHoc messages.
##
ahmpollertask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
ahmpollertask.remotehome=uk.gov.courtservice.xhibit.business.services.messaging.MessagingControllerHome
ahmpollertask.lookup=MessagingControllerHome
ahmpollertask.fixedrate=false
ahmpollertask.delay=120000
ahmpollertask.period=30000

##
#Configuration for terminal synchronizer task.
#
#This task periodically synchrronizes the terminal table with AD.
##
#terminaltask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#terminaltask.remotehome=uk.gov.courtservice.xhibit.business.services.userterminal.UserTerminalControllerHome
#terminaltask.lookup=UserTerminalControllerHome
#terminaltask.fixedrate=false
terminaltask.delay=0
#terminaltask.period=43200000

##
#Configuration for scheduling the GdgMessageGenerator in the GDG gateway
#Description: This task is to generate jms messages from db events.
##
#gdgmessagegeneratortask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#gdgmessagegeneratortask.remotehome=uk.gov.courtservice.xhibit.services.gdgateway.messagegenerator.GdgMessageGeneratorControllerHome
#gdgmessagegeneratortask.lookup=GdgMessageGeneratorControllerHome
#gdgmessagegeneratortask.fixedrate=false
#gdgmessagegeneratortask.delay=65000
#gdgmessagegeneratortask.period=5000


############################################################
#An example of how some scheduled tasks might be configured.
############################################################
###############################
##Current tasks for scheduling.
###############################
#scheduledtasks=javatask,sessionbeantask
# 
#############################
##Configuration for javatask.
#############################
#
#javatask.strategy=uk.gov.courtservice.framework.scheduler.JavaTaskStrategy     #Optional property saying which type
#                                                                               #of task we are dealing with.
#                                                                               #Defaults to JavaTaskStrategy.
#
#javatask.class=uk.gov.courtservice.xhibit.business.tasks.ATask                 #Required property saying which task class to use
#
#javatask.fixedrate=false                                                       #Optional, determines whether to use 'Beginning to
#                                                                               #Beginning' or 'End to Beginning' in timing the
#                                                                               #periodicity of the task.
#                                                                               #Defaults to false.
#
#javatask.delay=0                                                               #Optional, how long to wait before first running in ms.
#                                                                               #Defaults to 0.
#
#javatask.period=10000                                                          #Optional, how long to wait between running the task in ms.
#                                                                               #Where this delay is measured from is determined by
#                                                                               #the fixedrate property.
#                                                                               #A value of 0 means run once and terminate.
#                                                                               #Defaults to 0
####################################
##Configuration for sessionbeantask.
####################################
#sessionbeantask.strategy=uk.gov.courtservice.framework.scheduler.RemoteSessionTaskStrategy
#
#sessionbeantask.remotehome=uk.gov.courtservice.xhibit.business.services.ASessionRemoteHome #Required property giving the class of the
#                                                                                           #Home interface.
#
#sessionbeantask.lookup=ASession                                                            #Required property giving the JNDI lookup of
#                                                                                           #the session bean to use.
#
#sessionbeantask.fixedrate=false
#
#sessionbeantask.delay=0
#
#sessionbeantask.period=10000
