INSERT INTO XHB_CONFIG_PROP (CONFIG_PROP_ID, PROPERTY_NAME, PROPERTY_VALUE)
VALUES ((select max(config_prop_id)+1 from xhb_config_prop), 'DARTS_DVR_RELEASE_DATE', TO_CHAR(SYSDATE,'DD/MM/YYYY'));

COMMIT;
/