CREATE OR REPLACE TRIGGER XHB_DARRETENTIONPOLICY_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_DAR_RETENTION_POLICY
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_DAR_RETENTION_POLICY') = 1) THEN
	INSERT INTO AUD_DAR_RETENTION_POLICY
	(DAR_RETENTION_POLICY_ID,
	DISPOSAL2_ID,
	CASE_ID,
	DEFENDANT_ON_CASE_ID,
	DEFENDANT_ON_OFFENCE_ID,
	REF_DISP_RETENTION_POLICY_ID,
	REF_DAR_RETENTION_POLICY_ID,
	DURATION_DAYS,
	DURATION_MONTHS,
	DURATION_YEARS,
	HAS_LIFE,
	IS_CONSECUTIVE,
	IS_UPDATED,
	OBS_IND,
	CREATED_BY,
	LAST_UPDATED_BY,
	CREATION_DATE,
	LAST_UPDATE_DATE,
	VERSION,
	INSERT_EVENT)
	VALUES 
	(:OLD.DAR_RETENTION_POLICY_ID,
	:OLD.DISPOSAL2_ID,
	:OLD.CASE_ID,
	:OLD.DEFENDANT_ON_CASE_ID,
	:OLD.DEFENDANT_ON_OFFENCE_ID,
	:OLD.REF_DISP_RETENTION_POLICY_ID,
	:OLD.REF_DAR_RETENTION_POLICY_ID,
	:OLD.DURATION_DAYS,
	:OLD.DURATION_MONTHS,
	:OLD.DURATION_YEARS,
	:OLD.HAS_LIFE,
	:OLD.IS_CONSECUTIVE,
	:OLD.IS_UPDATED,
	:OLD.OBS_IND,
	:OLD.CREATED_BY,
	:OLD.LAST_UPDATED_BY,
	:OLD.CREATION_DATE,
	:OLD.LAST_UPDATE_DATE,
	:OLD.VERSION,
	l_trig_event);
  END IF;

END;
/
