---- Convicted of a sexual offence
INSERT INTO xhb_court_log_event_desc 
(EVENT_DESC_ID, FLAGGED_EVENT, EDITABLE, SEND_TO_MERCATOR, UPDATE_LINKED_CASES, PUBLISH_TO_SUBSCRIBERS, 
CLEAR_PUBLIC_DISPLAYS, E_INFORM, PUBLIC_DISPLAY, LINKED_CASE_TEXT, 
EVENT_DESCRIPTION, EVENT_TYPE, PUBLIC_NOTICE, SHORT_DESCRIPTION)
SELECT qry.* FROM (
SELECT 4022 EVENT_DESC_ID, 0 FLAGGED_EVENT, 1 EDITABLE, 0 SEND_TO_MERCATOR, 1 UPDATE_LINKED_CASES, 1 PUBLISH_TO_SUBSCRIBERS, 
0 CLEAR_PUBLIC_DISPLAYS, 0 E_INFORM, 0 PUBLIC_DISPLAY, 'LC_TEXT_' LINKED_CASE_TEXT,
'Convicted of a sexual offence' EVENT_DESCRIPTION, 21600 EVENT_TYPE, 0 PUBLIC_NOTICE, 'Conviction_Of_A_Sexual_Offence' SHORT_DESCRIPTION FROM DUAL
) qry
WHERE NOT EXISTS (SELECT NULL FROM xhb_court_log_event_desc x1 WHERE x1.EVENT_TYPE = qry.EVENT_TYPE);


INSERT INTO xhb_court_log_category
(CATEGORY_DESC_ID,EVENT_DESC_ID)
SELECT qry.* FROM (
SELECT 14 CATEGORY_DESC_ID, 4022 EVENT_DESC_ID FROM DUAL
) qry
WHERE NOT EXISTS (SELECT NULL FROM xhb_court_log_category x1 WHERE x1.CATEGORY_DESC_ID = qry.CATEGORY_DESC_ID AND x1.EVENT_DESC_ID = qry.EVENT_DESC_ID);

commit;
