MERGE INTO XHB_REF_DAR_RETENTION_POLICIES X2 USING (
SELECT 1 POLICY_NO, '1 Year Fixed' POLICY_DESCRIPTION FROM DUAL UNION
SELECT 2 POLICY_NO, '7 Years Fixed (Non-Custodial)' POLICY_DESCRIPTION FROM DUAL UNION
SELECT 3 POLICY_NO, '7 Years (Custodial)' POLICY_DESCRIPTION FROM DUAL UNION
SELECT 4 POLICY_NO, '99 Years / Life Fixed (Custodial)' POLICY_DESCRIPTION FROM DUAL
ORDER BY 1) X1
ON (X2.POLICY_NO = X1.POLICY_NO)
    WHEN MATCHED THEN
         UPDATE SET x2.POLICY_DESCRIPTION = x1.POLICY_DESCRIPTION
         WHERE x2.POLICY_DESCRIPTION != x1.POLICY_DESCRIPTION
    WHEN NOT MATCHED THEN  
         INSERT (POLICY_NO, POLICY_DESCRIPTION)
         VALUES (x1.POLICY_NO, x1.POLICY_DESCRIPTION);

COMMIT;