<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="ListDistributionCommon">
    
    <description>
        Common classes for List Distribution
    </description>

    <import file="./../../tools/ant/framework.xml" />

    <property name="project.author" value="Will Fardell"/>

    <property name="project.type.builds.jar" value="marker"/>
    <property name="project.type.requires.compilation" value="marker"/>

    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="Framework.jar" />
                <include name="XhibitXmlBinding.jar"/>
                <include name="XhibitEntities.jar" />
                <include name="XhibitValues.jar" />
            </fileset>
        </path>
    </target>
</project>
