<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="Common">

    <description>
        Build script to build individual common components.
    </description>

    <import file="./../tools/ant/framework.xml" />

    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="child.path">
            <pathelement location="court_log/build.xml" />
            <pathelement location="value/build.xml" />
            <pathelement location="publicdisplay/build.xml" />
            <pathelement location="progress/build.xml" />
            <pathelement location="results/build.xml" />
            <pathelement location="rolemapping/build.xml" />
            <pathelement location="listdistribution/build.xml" />
            <pathelement location="translation/build.xml" />
            <pathelement location="exiss/build.xml" />
        </path>
    </target>

    <!--
      =======================================================================
        Package Override
            - create the value jar
      =======================================================================
      -->
    <target name="package" unless="skip.package" depends="framework.package">
        <log target="package"/>
        <mkdir dir="${lib.build.dir}" />
        <jar destfile="${lib.build.dir}/Value.jar">
            <zipgroupfileset dir="${basedir}" includes="*/**/build/lib/*.jar" />
        </jar>
    </target>

</project>

