-- Create indexes for all of the foreign keys on the CJIT database, this will
-- prevent full-table locks when deleting from related tables...
CREATE INDEX CJI_AHM_DEVICE_ID_FK_IDX ON CJI_AHM(DEVICE_ID);
CREATE INDEX CJI_AHM_STATUS_ID_FK_IDX ON CJI_AHM(STATUS_ID);
CREATE INDEX CJI_AHM_AGG_STAT_ST_ID_FK_IDX ON CJI_AHM_AGG_STATUS(STATUS_ID);
CREATE INDEX CJI_AHM_REPLY_STATUS_ID_FK_IDX ON CJI_AHM_REPLY(STATUS_ID);
CREATE INDEX CJI_AHM_REPLY_MSG_ID_FK_IDX ON CJI_AHM_REPLY(MESSAGE_ID);
CREATE INDEX CJI_BITS_MSG_DOC_ID_FK_IDX ON CJI_BITS_MESSAGE(DOCUMENT_ID);
CREATE INDEX CJI_BITS_MSG_REQUEST_ID_FK_IDX ON CJI_BITS_MESSAGE(REQUEST_ID);
CREATE INDEX CJI_BITS_MSG_OP_TYPE_ID_FK_IDX ON CJI_BITS_MESSAGE(OPERATION_TYPE_ID);
CREATE INDEX CJI_CJIP_MSG_EVENT_ID_FK_IDX ON CJI_CJIP_MESSAGE(EVENT_ID);
CREATE INDEX CJI_CJIP_MSG_DOC_ID_FK_IDX ON CJI_CJIP_MESSAGE(DOCUMENT_ID);
CREATE INDEX CJI_CJIP_MSG_STATUS_ID_FK_IDX ON CJI_CJIP_MESSAGE(STATUS_ID);
CREATE INDEX CJI_CJIP_RQST_STATUS_ID_FK_IDX ON CJI_CJIP_REQUEST(STATUS_ID);
CREATE INDEX CJI_DOC_DOC_TYPE_ID_FK_IDX ON CJI_DOCUMENT(DOCUMENT_TYPE_ID);
CREATE INDEX CJI_DOC_STATUS_ID_FK_IDX ON CJI_DOCUMENT(STATUS_ID);
CREATE INDEX CJI_DOC_SEC_CJO_ROLE_ID_FK_IDX ON CJI_DOCUMENT_SECURITY(CJO_ROLE_ID);
CREATE INDEX CJI_DOC_SEC_DOC_TYPE_ID_FK_IDX ON CJI_DOCUMENT_SECURITY(DOCUMENT_TYPE_ID);
CREATE INDEX CJI_EVENT_OP_ID_FK_IDX ON CJI_EVENT(OPERATION_ID);
CREATE INDEX CJI_EVENT_STATUS_ID_FK_IDX ON CJI_EVENT(STATUS_ID);

-- Create unique constraints for the status text fields on the lookup tables to prevent
-- duplicates and provide the CBO additional information about the data,,,
CREATE UNIQUE INDEX CJI_AHM_REPLY_STAT_TXT_IDX ON CJI_AHM_REPLY_STATUS(STATUS_TEXT);
CREATE UNIQUE INDEX CJI_AHM_STAT_TXT_IDX ON CJI_AHM_STATUS(STATUS_TEXT);
CREATE UNIQUE INDEX CJI_CJIP_MESSAGE_STAT_TXT_IDX ON CJI_CJIP_MESSAGE_STATUS(STATUS_TEXT);
CREATE UNIQUE INDEX CJI_CJIP_REQUEST_STAT_TXT_IDX ON CJI_CJIP_REQUEST_STATUS(STATUS_TEXT);
CREATE UNIQUE INDEX CJI_DOCUMENT_STAT_TXT_IDX ON CJI_DOCUMENT_STATUS(STATUS_TEXT);
CREATE UNIQUE INDEX CJI_EVENT_STAT_TXT_IDX ON CJI_EVENT_STATUS(STATUS_TEXT);