INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13818,'Capture Sentence', 'AAMRSS', 'Y');

INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13819,'Capture Sentence', 'AAMRCS', 'Y');



commit;

