INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13816,'Capture Sentence', 'TMCS', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (13817,'Capture Sentence', 'TMSS', 'Y');
commit;
