DECLARE

  OBJECT_ALREADY_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT(OBJECT_ALREADY_EXISTS, -955);
  
  PROCEDURE run_sql(p_sql IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql; 
  -- Ignore ORA-00955: name is already used by an existing object
  EXCEPTION WHEN OBJECT_ALREADY_EXISTS THEN NULL;
  END run_sql;
BEGIN
  run_sql('CREATE INDEX XHB_CPP_STAGING_CLOB ON XHB_CPP_STAGING_INBOUND (CLOB_ID)');
  run_sql('CREATE INDEX XHB_CPP_STAGING_VALIDATION ON XHB_CPP_STAGING_INBOUND (VALIDATION_STATUS, TIME_LOADED, OBS_IND)');
  run_sql('CREATE INDEX XHB_CPP_STAGING_PROCESSING ON XHB_CPP_STAGING_INBOUND (PROCESSING_STATUS, VALIDATION_STATUS)');
END;
/