CREATE OR REPLACE TRIGGER XHB_CASE_ON_LIST_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CASE_ON_LIST
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  IF UPDATING THEN

    l_trig_event := 'U';

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_CASE_ON_LIST') = 1) THEN

    INSERT INTO AUD_CASE_ON_LIST (
    CASE_ON_LIST_ID,
    CASE_ID,
    LIST_ID,
    SITTING_ID,
    COURT_SITE_ID,
    COURT_ROOM_ID,
    RESERVED,
    FLOATER_CASE,
    TIME_MARKING_ID,
    TIME_LISTED,
    IS_COURT_ROOM_LIST_ENTRY,
    HEARING_TYPE_ID,
    REASON_FOR_REMOVAL,
    CRACKED_INEFFECTIVE_ID,
    OBS_IND,
    CREATED_BY,
    LAST_UPDATED_BY,
    CREATION_DATE,
    LAST_UPDATE_DATE,
    VERSION,
    insert_event,
    seq_no)
    VALUES (
    :OLD.CASE_ON_LIST_ID,
    :OLD.CASE_ID,
    :OLD.LIST_ID,
    :OLD.SITTING_ID,
    :OLD.COURT_SITE_ID,
    :OLD.COURT_ROOM_ID,
    :OLD.RESERVED,
    :OLD.FLOATER_CASE,
    :OLD.TIME_MARKING_ID,
    :OLD.TIME_LISTED,
    :OLD.IS_COURT_ROOM_LIST_ENTRY,
    :OLD.HEARING_TYPE_ID,
    :OLD.REASON_FOR_REMOVAL,
    :OLD.CRACKED_INEFFECTIVE_ID,
    :OLD.OBS_IND,
    :OLD.CREATED_BY,
    :OLD.LAST_UPDATED_BY,
    :OLD.CREATION_DATE,
    :OLD.LAST_UPDATE_DATE,
    :OLD.VERSION,
    l_trig_event,
    :old.seq_no);

  END IF;

END XHB_CASE_ON_LIST_BUR_TR;
/