--ctx-1725
--xhb table changes
ALTER TABLE XHB_DIARY_NOTE_ENTRY ADD CASE_ID NUMBER(8);

--Create FK constraints
ALTER TABLE XHB_DIARY_NOTE_ENTRY ADD (CONSTRAINT CASE_DIARY_FIXT_CASE_ID_FK FOREIGN KEY (CASE_ID) REFERENCES XHB_CASE(CASE_ID));

--aud table changes

ALTER TABLE AUD_DIARY_NOTE_ENTRY ADD CASE_ID NUMBER(8);

@@xhb_diary_note_entry_bur_tr.sql;

commit;