##
# The xml configuration file to use to define the valid event levels and the
# instances of CjseEventLevelPopulator that support them.
#
# Positive number event levels are 'valid' level for writing the CJSE event to the database
#
# Where events are defined with a level of -1 the populator class will contain logic
# to determine which of the 'valid' levels are appropriate for this event.
##

#Deportation level event definition
define.class.DEPORTATION=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.DeportationCjseEventLevelPopulator
define.level.DEPORTATION=1

#Case level event definition.
define.class.CASE=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.CaseCjseEventLevelPopulator
define.level.CASE=1

#Defendant level event definition.
define.class.DEFENDANT=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.DefendantCjseEventLevelPopulator
define.level.DEFENDANT=3

#CRN level event definition.
define.class.CRN=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.CrnCjseEventLevelPopulator
define.level.CRN=2

#Joinder indictment level event definition. equivalent to case level.
define.class.JOINDER=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.JoinderCjseEventLevelPopulator
define.level.JOINDER=-1

#Trial Witness Sworn event definition. equivalent to defendant or case level depending on the sub event.
define.class.TRIAL_WITNESS_SWORN=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.TrialWitnessSwornCjseEventLevelPopulator
define.level.TRIAL_WITNESS_SWORN=-1

#Trial Witness Read event definition. equivalent to defendant or case level depending on the sub event.
define.class.TRIAL_WITNESS_READ=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.TrialWitnessReadCjseEventLevelPopulator
define.level.TRIAL_WITNESS_READ=-1

#Appeal Witness Sworn event definition. equivalent to defendant or case level depending on the sub event.
define.class.APPEAL_WITNESS_SWORN=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.AppealWitnessSwornCjseEventLevelPopulator
define.level.APPEAL_WITNESS_SWORN=-1

#Appeal Witness Read event definition. equivalent to defendant or case level depending on the sub event.
define.class.APPEAL_WITNESS_READ=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.AppealWitnessReadCjseEventLevelPopulator
define.level.APPEAL_WITNESS_READ=-1

#Long Adjourn event definition. equivalent to defendant or case level depending on the sub event.
define.class.LONG_ADJOURN=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.LongAdjournCjseEventLevelPopulator
define.level.LONG_ADJOURN=-1

#Plea event definition. equivalent to defendant or crn level depending on the sub event.
define.class.PLEA=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.PleaCjseEventLevelPopulator
define.level.PLEA=-1

#Unrelated disposal event definition. equivalent to defendant or crn level depending on whether a defendant on offence id is passed.
define.class.UNRELATED_DISPOSAL=uk.gov.courtservice.xhibit.courtlog.cjse.eventlevel.UnrelatedDisposalCjseEventLevelPopulator
define.level.UNRELATED_DISPOSAL=-1