identifiedXpath=/event/Direction_By_Defendant_Options/E40704_Identification/text()
isIdentified=E40704_Defendant_Identified

arraignedXpath=/event/Direction_By_Defendant_Options/E40705_Arraignment/text()

bailConditionsXpath=/event/Direction_By_Defendant_Options/E40706_Bail_Or_Custody/E40706_Bail_Or_Custody_Conditions/text()

bailStatusXpath=/event/Direction_By_Defendant_Options/E40706_Bail_Or_Custody/E40706_Bail_Or_Custody_Options/text()
ric=E40706_RIC
bailAsBefore=E40706_Bail_As_Before

certOfAttendXpath=/event/Direction_By_Defendant_Options/E40707_Certificate_Of_Attendance/text()
granted=E40707_Granted
refused=E40707_Refused

formBXpath=/event/Direction_By_Defendant_Options/E40708_Form_B/E40708_Form_B_Options/text()
formBDateXpath=/event/Direction_By_Defendant_Options/E40708_Form_B/E40708_To_Be_Filed_Date/text()
filed=E40708_Filed


panddXpath=/event/Directions_By_Case_Options/E40710_P_And_D/text() 
hasPandD=E40710_Form_Handed_In

timeEstXpath=/event/Directions_By_Case_Options/E40711_Time_Estimate/E40711_Time/text()

timeEstUnitsXpath=/event/Directions_By_Case_Options/E40711_Time_Estimate/E40711_Time_Estimate_Options/text() 
trialTimeDays=E40711_Days
trialTimeWeeks=E40711_Weeks

directionsXpath=/event/Directions_By_Case_Options/E40712_Directions/text()

