version = v@xhibit.version@
full_version = @xhibit.version@
build = @xhibit.build@
releaseDate = @xhibit.releasedate@
copyright = Copyright CGI 2025

# These properties can be commented out to turn off internal debuging or use of dummy data

# XHIBITConstant.testTeamReport = As long as this property key is present, the testTeamReport is on/will be showing on exceptions in the gui.


#           XPanel.internalDebug = As long as this property key is present, the XPanel internal debug is on
#          XDialog.internalDebug = As long as this property key is present, the XDialog internal debug is on
#          XAction.internalDebug = As long as this property key is present, the XAction internal debug is on, detaling (e.g.) setModel(Object) and xActionPerformed(ActionEvent) methods
#   XHIBITConstant.internalDebug = As long as this property key is present, the XHIBITConstant internal debug is on
#     XHIBITSearch.internalDebug = As long as this property key is present, the XHIBITSearch internal debug is on
# XHIBITTableModel.internalDebug = As long as this property key is present, the XHIBITTableModel internal debug is on
# XSortableTableModel.internalDebug = As long as this property key is present, the XHIBITTableModel internal debug is on
# SortButtonRenderer.internalDebug = As long as this property key is present, the XHIBITTableModel internal debug is on

#              UpdateCase.useDummyData = as long as this property key is present, the update case component will not interact with mid tier, rather create dummy data.
#OpenAmendDefendantAction.useDummyData = as long as this property key is present, the update defendant component will not interact with mid tier, rather create dummy data.
#            XHIBITSearch.useDummyData = as long as this property key is present, the xhibit searh component will not interact with mid tier, rather create dummy data.




