ALTER TABLE XHB_DEF_HEARING_RECORD ADD
(S41_APPLICATION  VARCHAR2(1),
S41_GRANTED  VARCHAR2(1),
S41_APPLICATION_MADE  VARCHAR2(2)
);
ALTER TABLE AUD_DEF_HEARING_RECORD ADD
(S41_APPLICATION  VARCHAR2(1),
S41_GRANTED  VARCHAR2(1),
S41_APPLICATION_MADE  VARCHAR2(2)
);

@@xhb_def_hearing_record_bur_tr.sql;
COMMIT;