INSERT INTO XHB_REF_DISP_RETENTION_POLICY
(DISPOSAL_CODE, REF_DAR_RETENTION_POLICY_ID, HAS_DURATION, HAS_LIFE, ALLOWS_CONSECUTIVE)
SELECT X1.DISPOSAL_CODE, R1.REF_DAR_RETENTION_POLICY_ID, X1.HAS_DURATION, X1.HAS_LIFE, X1.ALLOWS_CONSECUTIVE  FROM (
SELECT 'SVRO'  DISPOSAL_CODE, 3 POLICY_NO, 'Y' HAS_DURATION, NULL HAS_LIFE, NULL ALLOWS_CONSECUTIVE FROM DUAL 
) X1, XHB_REF_DAR_RETENTION_POLICIES R1
WHERE R1.POLICY_NO = X1.POLICY_NO 
 AND NOT EXISTS (SELECT NULL FROM XHB_REF_DISP_RETENTION_POLICY X2
                  WHERE X2.DISPOSAL_CODE = X1.DISPOSAL_CODE)
ORDER BY X1.DISPOSAL_CODE;

COMMIT;