-- REMOVE PRIMARY CONSTRAINT
ALTER TABLE XHB_REF_CALENDAR DROP CONSTRAINT XHB_REF_CALENDAR_PK;
-- ADD COLUMN
ALTER TABLE XHB_REF_CALENDAR ADD REF_CALENDAR_ID NUMBER (8);
-- ADD COLUMN TO AUDIT
ALTER TABLE AUD_REF_CALENDAR ADD REF_CALENDAR_ID NUMBER (8);
-- CREATE SEQ
@@xhb_ref_calendar_sequence_create.sql;

-- UPDATE COLUMN
@@xhb_ref_calendar_update.sql

-- MAKE COLUMN NOT NULL
ALTER TABLE XHB_REF_CALENDAR MODIFY REF_CALENDAR_ID NOT NULL;
-- MAKE PRIMARY KEY FOR TABLE
ALTER TABLE XHB_REF_CALENDAR ADD CONSTRAINT XHB_REF_CALENDAR PRIMARY KEY (REF_CALENDAR_ID);

@@xhb_ref_calendar_bir_tr.sql
@@xhb_ref_calendar_bur_tr.sql

COMMIT;