CREATE OR REPLACE TRIGGER XHB_SITTING_ON_LIST_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_SITTING_ON_LIST
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_SITTING_ON_LIST') = 1) THEN
	INSERT INTO AUD_SITTING_ON_LIST
		(SITTING_ON_LIST_ID,
		SITTING_NUMBER,
		LIST_ID,
		TIME_MARKING_ID,
		TIME_LISTED,
		JUDGE_REF_ID,
		JP1,
		JP2,
		JP3,
		JP4,
		LIST_NOTE_PRE_DEFINED_ID,
		LIST_NOTE_TEXT,
		PRE_DEF_NOTE_CLASSIFICATION_ID, 
		FREE_TEXT_NOTE_CLASS_ID, 
		OBS_IND,
		LAST_UPDATE_DATE,
		CREATION_DATE,
		LAST_UPDATED_BY,
		CREATED_BY,
		VERSION,
		INSERT_EVENT)
	VALUES (:OLD.SITTING_ON_LIST_ID,
		:OLD.SITTING_NUMBER,
		:OLD.LIST_ID,
		:OLD.TIME_MARKING_ID,
		:OLD.TIME_LISTED,
		:OLD.JUDGE_REF_ID,
		:OLD.JP1,
		:OLD.JP2,
		:OLD.JP3,
		:OLD.JP4,
		:OLD.LIST_NOTE_PRE_DEFINED_ID,
		:OLD.LIST_NOTE_TEXT,
		:OLD.PRE_DEF_NOTE_CLASSIFICATION_ID, 
		:OLD.FREE_TEXT_NOTE_CLASS_ID, 
		:OLD.OBS_IND,
		:OLD.LAST_UPDATE_DATE,
		:OLD.CREATION_DATE,
		:OLD.LAST_UPDATED_BY,
		:OLD.CREATED_BY,
		:OLD.VERSION,
		l_trig_event);
  END IF;
END;
/
