CREATE OR REPLACE TRIGGER "XHIBIT".XHB_FIXTURE_DEFT_ATTEND_BIR_TR
  BEFORE INSERT ON XHB_FIXTURE_DEFT_ATTENDING
  REFERENCING NEW AS NEW
  FOR EACH ROW

BEGIN

  IF :NEW.FIXTURE_DEFT_ATTENDING_ID IS NULL THEN

    SELECT XHB_FIXTURE_DEFT_ATTENDING_SEQ.NEXTVAL
    INTO   :NEW.FIXTURE_DEFT_ATTENDING_ID
    FROM   DUAL;

  END IF;

  IF ((:NEW.LAST_UPDATED_BY IS NULL) OR
      (:NEW.CREATED_BY IS NULL)) THEN

    SELECT SYS_CONTEXT('USERENV', 'SESSION_USER'),
           SYS_CONTEXT('USERENV', 'SESSION_USER')
    INTO   :NEW.LAST_UPDATED_BY,
           :NEW.CREATED_BY
    FROM   DUAL;

  END IF;

  SELECT SYSDATE,
         SYSDATE,
         1
  INTO   :NEW.LAST_UPDATE_DATE,
         :NEW.CREATION_DATE,
         :NEW.VERSION
  FROM   DUAL;

END XHB_FIXTURE_DEFT_ATTEND_BIR_TR;
/