UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=330
WHERE DISPOSAL_CODE='SHPO'
AND DIL_SEQ_NO=320;

UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=310
WHERE DISPOSAL_CODE='SHPO'
AND DIL_SEQ_NO=300;

UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=290
WHERE DISPOSAL_CODE='SHPO'
AND DIL_SEQ_NO=280;

COMMIT;
/