UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=170
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=130;

UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=150
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=120;

UPDATE XHB_REF_DISPOSAL_LINE
SET DIL_SEQ_NO=130
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=115;

UPDATE XHB_REF_DISPOSAL_LINE
SET DATA = 'On the day it is made.'
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=65;

UPDATE XHB_REF_DISPOSAL_LINE
SET DATA = 'Not until the defendant is released from custody.'
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=70;
	
UPDATE XHB_REF_DISPOSAL_LINE
SET DATA = 'Not until the defendant ceases to be subject to a custodial sentence.'
WHERE DISPOSAL_CODE='SVRO'
AND DIL_SEQ_NO=75;

COMMIT;
/