package uk.gov.courtservice.xhibit.client.print;

import java.io.InputStream;
import java.util.Map;

import uk.gov.courtservice.framework.exception.CSRecoverableException;
import uk.gov.courtservice.xhibit.client.print.exception.FOPCreateDocumentException;
import uk.gov.courtservice.xhibit.client.util.XAction;

/**
 * <p>
 * Title: Xhibit2 FOPInterface
 * </p>
 * <p>
 * Description: Interface for FOP printing and creating files. PFD creating is
 * the only format currently supported, although FOP will support othyer
 * renderings.
 * </p>
 * <p>
 * Copyright: Copyright (c) 2003
 * </p>
 * <p>
 * Company: EDS
 * </p>
 * 
 * @author Neil Entwistle
 * @version 1.0
 */

public interface FOPInterface {
    /**
     * This method provides support for direct printing of an XSL-FO document.
     * The preview and show dialog are independant of each other.
     * 
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param preview
     *            Whether to display a print preview frame.
     * @param showDialog
     *            Whether to show the print dialog or print directly
     * @throws CSRecoverableException
     */
    public void printDocument(String xslFO, boolean preview, boolean showDialog) throws CSRecoverableException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param preview
     *            Whether to display a print preview frame.
     * @throws CSRecoverableException
     */
    public void printDocument(String xslFO, boolean preview) throws CSRecoverableException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xmlIS
     *            the InputStream for the XML.
     * @param xslIS
     *            the InputStream for the XSL.
     * @throws CSRecoverableException
     */
    public void printDocument(InputStream xmlIS, InputStream xslIS) throws CSRecoverableException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param preview
     *            Whether to display a print preview frame.
     * @param title
     *            the title of the preview dialog.
     * @throws CSRecoverableException
     */
    public void printDocument(String xslFO, boolean preview, String title) throws CSRecoverableException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xmlIS
     *            the InputStream for the XML.
     * @param xslIS
     *            the InputStream for the XSL.
     * @param title
     *            the title of the preview dialog.
     * @throws CSRecoverableException
     */
    
    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param preview
     *            Whether to display a print preview frame.
     * @param title
     *            the title of the preview dialog.
     * @param action           
     *            the action of the preview dialog
     * @throws CSRecoverableException
     */
    public void printDocument(String xslFO, boolean preview, String title, XAction action) throws CSRecoverableException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param preview
     *            Whether to display a print preview frame.
     * @param title
     *            the title of the preview dialog.
     * @param map           
     *            fop map
     * @throws CSRecoverableException
     */
    
    public void printDocument(InputStream xmlIS, InputStream xslIS, String title) throws CSRecoverableException;

    /**
     * This method provides support for getting a PDF, HTML, RTF etc. formatted
     * document.
     * 
     * @return A byte array containing the document generated by the XSL-FOP
     *         engine.
     * @param xslFO
     *            the xsl-FO to be rendered.
     * @param DocumentType
     *            The type of document that needs to be generated.
     */
    public byte[] createDocument(String xslFO, int DocumentType) throws FOPCreateDocumentException;

    /**
     * This method provides support for direct printing of an XSL-FO document.
     * 
     * @param xmlIS
     *            the InputStream for the XML.
     * @param xslIS
     *            the InputStream for the XSL.
     * @throws CSRecoverableException
     */
    public void printDocument(String xmlIS, InputStream xslIS) throws CSRecoverableException;

}