DECLARE

  OBJECT_ALREADY_EXISTS EXCEPTION;
  PRAGMA EXCEPTION_INIT(OBJECT_ALREADY_EXISTS, -955);
  
  PROCEDURE run_sql(p_sql IN VARCHAR2) IS
  BEGIN
    EXECUTE IMMEDIATE p_sql; 
  -- Ignore ORA-00955: name is already used by an existing object
  EXCEPTION WHEN OBJECT_ALREADY_EXISTS THEN NULL;
  END run_sql;
BEGIN
  run_sql('CREATE INDEX XHB_D20_OFFENCE_LINK_DOCID ON XHB_D20_OFFENCE_LINK (DEFENDANT_ON_CASE_ID)');
  run_sql('CREATE INDEX XHB_REFAPPRESD20_RESCODE ON XHB_REF_APP_RES_D20_MAP (APP_RESULT_CODE)');
END;
/