update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='BA40';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='BA60';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='CD40';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='CD50';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='CD70';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='DD10';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='DD40';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='DD60';
update xhb_d20_offence_codes set mand_disq='Y', mand_dtetp='Y' where offence_code='DD80';

update xhb_d20_offence_codes set mand_disq='Y', mand_alc_drug_level='Y', mand_dtetp='Y' where offence_code='CD60';
update xhb_d20_offence_codes set mand_disq='Y', mand_alc_drug_level='Y', mand_dtetp='Y' where offence_code='DG60';

update xhb_d20_offence_codes set mand_disq='Y', mand_alc_drug_level='Y' where offence_code='DG10';
update xhb_d20_offence_codes set mand_disq='Y', mand_alc_drug_level='Y' where offence_code='DR10';

update xhb_d20_offence_codes set mand_alc_drug_level='Y' where offence_code='DG40';
update xhb_d20_offence_codes set mand_alc_drug_level='Y' where offence_code='DR40';

update xhb_d20_offence_codes set mand_disq='Y' where offence_code='BA42';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='BA46';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='BA62';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='BA66';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD42';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD46';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD52';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD56';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD62';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD66';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD72';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD76';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD82';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD80';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD86';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD90';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD92';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='CD96';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD12';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD16';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD42';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD46';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD62';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD66';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD82';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DD86';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DG12';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DG16';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DG62';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DG66';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR12';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR16';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR20';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR22';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR26';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR30';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR31';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR32';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR36';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR80';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR82';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='DR86';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='MS50';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='MS52';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='MS56';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='TT99';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='UT50';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='UT52';
update xhb_d20_offence_codes set mand_disq='Y' where offence_code='UT56';

commit;
