INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (12311,'Capture Sentence', 'DISOBLG', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (12312,'Capture Sentence', 'DISDISC', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (12313,'Capture Sentence', 'DISTOT', 'Y');
INSERT INTO XHB_REF_EVENT_DESCRIPTION (EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS) VALUES (12314,'Capture Sentence', 'DISINT', 'Y');

commit;
