-- Create Sequence
CREATE SEQUENCE  HK3_RUN_ID_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE NOORDER  NOCYCLE;

-- Results Table
CREATE TABLE XHB_HK3_RESULTS (
	HK3_RUN_ID					NUMBER(10)	PRIMARY KEY,
	RUN_TYPE					VARCHAR2(1)	NOT NULL,
	RUN_START_DATE				DATE,
	RUN_END_DATE				DATE,
	JUDGE_USAGE_STATUS			VARCHAR2(1),
	JUDGE_USAGE_ERROR_MESSAGE	VARCHAR2(2000),
	JUDGE_USAGE_DELETED			NUMBER(6),
	JUDGE_USAGE_ERROR			NUMBER(6),
	CRTRM_USAGE_STATUS			VARCHAR2(1),
	CRTRM_USAGE_ERROR_MESSAGE	VARCHAR2(2000),
	CRTRM_USAGE_RECS_DELETED	NUMBER(6),
	CRTRM_USAGE_RECS_ERROR		NUMBER(6),
	REF_JUDGE_STATUS			VARCHAR2(1),
	REF_JUDGE_ERROR_MESSAGE		VARCHAR2(2000),
	REF_JUDGES_DELETED			NUMBER(6),
	REF_JUDGES_ERROR			NUMBER(6),
	JUDGE_USAGE_LIMIT			NUMBER(6),
	CRTRM_USAGE_LIMIT			NUMBER(6),
	REF_JUDGE_LIMIT				NUMBER(6)
);

-- Error Table
CREATE TABLE XHB_HK3_ERROR_LOG (
	HK3_RUN_ID		NUMBER(10)	NOT NULL,
	ERROR_MESSAGE	VARCHAR2(500)
);