## Stores properties

# Properties for the ldap not set in WL
ldap.userPrincipalAttribute=samAccountName
ldap.userDisplayAttribute=displayName
ldap.userForenameAttribute=givenName
ldap.userSurnameAttribute=sn
ldap.groupPrincipalAttribute=cn
ldap.groupMemberOfAttribute=memberOf
ldap.groupRootPrincipal=XHIBIT User

ldap.host=10.63.127.14
ldap.port=389
ldap.principal=weblogic
ldap.credential=password
ldap.connectionPoolSize=10
ldap.cacheEnabled=true
ldap.cacheSize=32
ldap.cacheTTL=160
ldap.followReferrals=true
ldap.bindAnonymouslyOnReferrals=false
ldap.resultsTimeLimit=0
ldap.connectTimeout=0
ldap.parallelConnectDelay=0
ldap.userBaseDN=DC=ops,DC=cs,DC=root
ldap.userSearchScope=2
ldap.userFromNameFilter=(&(sAMAccountName=%u)(objectclass=user))
ldap.groupBaseDN=DC=ops,DC=cs,DC=root
ldap.groupSearchScope=2
ldap.groupFromNameFilter=(&(cn=%g)(objectclass=group))

ldap.test.host=10.63.127.14
ldap.test.port=389
ldap.test.principal=weblogic
ldap.test.credential=password
ldap.test.connectionPoolSize=10
ldap.test.cacheEnabled=true
ldap.test.cacheSize=32
ldap.test.cacheTTL=160
ldap.test.followReferrals=true
ldap.test.bindAnonymouslyOnReferrals=false
ldap.test.resultsTimeLimit=0
ldap.test.connectTimeout=0
ldap.test.parallelConnectDelay=0
ldap.test.userBaseDN=DC=ops,DC=cs,DC=root
ldap.test.userSearchScope=2
ldap.test.userFromNameFilter=(&(sAMAccountName=%u)(objectclass=user))
ldap.test.groupBaseDN=DC=ops,DC=cs,DC=root
ldap.test.groupSearchScope=2
ldap.test.groupFromNameFilter=(&(cn=%g)(objectclass=group))

ldap.nle.host=xhibitads_nle
ldap.nle.port=389
ldap.nle.principal=logicaweblogic
ldap.nle.credential=password
ldap.nle.connectionPoolSize=10
ldap.nle.cacheEnabled=true
ldap.nle.cacheSize=32
ldap.nle.cacheTTL=160
ldap.nle.followReferrals=true
ldap.nle.bindAnonymouslyOnReferrals=false
ldap.nle.resultsTimeLimit=0
ldap.nle.connectTimeout=0
ldap.nle.parallelConnectDelay=0
ldap.nle.userBaseDN=DC=ops,DC=cs,DC=root
ldap.nle.userSearchScope=2
ldap.nle.userFromNameFilter=(&(sAMAccountName=%u)(objectclass=user))
ldap.nle.groupBaseDN=DC=ops,DC=cs,DC=root
ldap.nle.groupSearchScope=2
ldap.nle.groupFromNameFilter=(&(cn=%g)(objectclass=group))