SELECT_GROUP_ROLE_ALL=SELECT B.ROLE_NAME, A.GROUP_NAME FROM XHB_SECURITY_GROUP A, XHB_SECURITY_ROLE B, XHB_SECURITY_GROUP_ROLE C WHERE A.GROUP_NAME = C.GROUP_NAME AND B.ROLE_NAME = C.ROLE_NAME ORDER BY 1, 2
SELECT_GROUP_ROLE_ENABLED=SELECT B.ROLE_NAME, A.GROUP_NAME FROM XHB_SECURITY_GROUP A, XHB_SECURITY_ROLE B, XHB_SECURITY_GROUP_ROLE C WHERE A.GROUP_NAME = C.GROUP_NAME AND B.ROLE_NAME = C.ROLE_NAME AND C.IS_ENABLED = 'Y' ORDER BY 1, 2

SELECT_GROUP_PK=SELECT 1 FROM XHB_SECURITY_GROUP WHERE GROUP_NAME = ?
SELECT_ROLE_PK=SELECT 1 FROM XHB_SECURITY_ROLE WHERE ROLE_NAME = ?
SELECT_GROUP_ROLE_PK=SELECT 1 FROM XHB_SECURITY_GROUP_ROLE WHERE GROUP_NAME = ? AND ROLE_NAME = ?

INSERT_GROUP=INSERT INTO XHB_SECURITY_GROUP (GROUP_NAME, DESCRIPTION) VALUES (?, ?)
INSERT_ROLE=INSERT INTO XHB_SECURITY_ROLE (ROLE_NAME, SYSTEM_ROLE) VALUES (?, ?)
INSERT_GROUP_ROLE=INSERT INTO XHB_SECURITY_GROUP_ROLE (GROUP_NAME, ROLE_NAME, IS_ENABLED, IS_ENABLED_BY_DEFAULT) VALUES (?, ?, 'Y', 'Y')


