CREATE OR REPLACE TRIGGER XHB_CHARGES_LOG_AI_TR
  AFTER INSERT
  ON XHIBIT.XHB_CHARGES_LOG
  FOR EACH ROW

BEGIN

 IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_CHARGES_LOG') = 1) THEN
	INSERT INTO AUD_CHARGES_LOG
     		(CHARGES_LOG_ID,
		CASE_ID,
		SEQUENCE_NO,
		CHARGES_INFO,
		OBS_IND,
		CREATED_BY,
		LAST_UPDATED_BY,
		CREATION_DATE,
		LAST_UPDATE_DATE,
		VERSION,
		INSERT_EVENT)
	VALUES (:new.CHARGES_LOG_ID,
		:new.CASE_ID,
		:new.SEQUENCE_NO,
		:new.CHARGES_INFO,
		:new.OBS_IND,
		:new.CREATED_BY,
		:new.LAST_UPDATED_BY,
		:new.CREATION_DATE,
		:new.LAST_UPDATE_DATE,
		:new.VERSION,
		'I');
  END IF;

END;
/
