CREATE OR REPLACE TRIGGER XHB_CASEDIARYTIMERQMT_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CASE_DIARY_TIME_RQMT
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_CASE_DIARY_TIME_RQMT') = 1) THEN
	INSERT INTO AUD_CASE_DIARY_TIME_RQMT
     	(CASE_DIARY_TIME_RQMT_ID,
		CASE_LISTING_ENTRY_ID,
		FIRST_LISTING_DATE,
		FINAL_LISTING_DATE,
		TIME_ESTIMATE_HOURS,
		TIME_ESTIMATE_DAYS,
		TIME_ESTIMATE_WEEKS,
		FIXTURE_NOTICE_REQUIRED,
		HEARING_TYPE_ID,
		LIST_NOTE_PRE_DEFINED_ID,
		LIST_NOTE_TEXT ,
		CREATED_BY,
		LAST_UPDATED_BY,
		CREATION_DATE,
		LAST_UPDATE_DATE,
		VERSION,
		INSERT_EVENT)
	VALUES (:old.CASE_DIARY_TIME_RQMT_ID,
		:old.CASE_LISTING_ENTRY_ID,
		:old.FIRST_LISTING_DATE,
		:old.FINAL_LISTING_DATE,
		:old.TIME_ESTIMATE_HOURS,
		:old.TIME_ESTIMATE_DAYS,
		:old.TIME_ESTIMATE_WEEKS,
		:old.FIXTURE_NOTICE_REQUIRED,
		:old.HEARING_TYPE_ID,
		:old.LIST_NOTE_PRE_DEFINED_ID,
		:old.LIST_NOTE_TEXT ,
		:old.CREATED_BY,
		:old.LAST_UPDATED_BY,
		:old.CREATION_DATE,
		:old.LAST_UPDATE_DATE,
		:old.VERSION,
		l_trig_event);
  END IF;


END;
/
