#
# Title:       Actions
#
# Description: This is used by the.class factory to determine how to map requests to.classs.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      Edward Cawley, Xdevelopment LLP (2003)
#
# $Revision: 1.3 $
# $Log: Action.properties,v $
# Revision 1.3  2005/04/27 08:26:58  bzjrnl
# Manual Merge From BRANCH_7_X
#
# Revision 1.1.2.1  2005/04/25 13:37:41  bzjrnl
# Changes to move jspc into the framework.
#
# Revision 1.21  2004/11/04 14:35:16  bzjrnl
# Changes to correct problems with cookie access.
#
# Revision 1.20  2004/09/24 06:49:50  tzj8k5
# CR65 - All Case Status Page ThinClient
#
# Revision 1.19  2004/08/12 15:56:22  zz7n1c
# Merged from 6_X_BRANCH on 12/08/2004
#
# Revision 1.18.98.1  2004/08/05 15:50:15  tzj8k5
# 56014 - Amendment to error handling in the thinclient
#
# Revision 1.18  2003/06/26 11:30:30  cawleye
# factorised bits to shared
#
# Revision 1.17  2003/05/16 08:59:39  fz0n8j
# Added logout button.
#
# Revision 1.16  2003/05/14 13:09:56  fz0n8j
# Bug fixes and first version of print by day.
#
# Revision 1.15  2003/05/13 12:55:31  fz0n8j
# Adding print for schedule by week.
#
# Revision 1.14  2003/05/02 15:33:55  fz0n8j
# *** empty log message ***
#
# Revision 1.13  2003/05/01 15:51:40  fz0n8j
# Added terminal selection to witness.
#
# Revision 1.12  2003/04/30 11:43:59  qzd3k3
# Merge from dev branch.
#
# Revision 1.11.2.4  2003/04/25 15:33:26  hzf3bb
# no message
#
# Revision 1.11.2.3  2003/04/23 14:17:41  fz0n8j
# Added edit case details.
#
# Revision 1.11.2.2  2003/04/22 17:35:12  hzf3bb
# *** empty log message ***
#
# Revision 1.11.2.1  2003/04/14 13:25:13  fz0n8j
# Now possible to view all witnesses.
#
# Revision 1.11  2003/04/04 11:13:39  fz0n8j
# Security Changes and Misc Fixs
#
# Revision 1.10  2003/04/04 08:35:15  fz0n8j
# merged.
#
# Revision 1.9  2003/04/04 08:31:06  hzf3bb
# no message
#
# Revision 1.8  2003/04/02 15:40:11  hzf3bb
# added new properties
#
# Revision 1.7  2003/04/02 09:07:26  hzf3bb
# no message
#
# Revision 1.6  2003/04/01 13:59:52  fz0n8j
# Added actions again and modified jsps/properites.
#
# Revision 1.5  2003/03/28 12:17:26  fz0n8j
# Added print for witness details.
#
# Revision 1.4  2003/03/28 11:33:11  fz0n8j
# Added witness sign in.
#
# Revision 1.3  2003/03/28 10:07:37  fz0n8j
# *** empty log message ***
#
# Revision 1.2  2003/03/28 09:58:46  fz0n8j
# Added witness details and court status.
#
# Revision 1.1  2003/03/27 11:01:23  fz0n8j
# Added to cvs
#


actions = default;viewsummarybyname;viewallcourtstatus;maintainwitnessdetails;maintainwitnessdetailsall;maintainwitnessdetailsfuture;viewdailylist;witnesssignin;witnesssigninedit;printwitnessdetailsfuture;printwitnessdetailsall;printwitnessdetails;editwitness;deletewitness;addwitness;confirmdeletewitness;viewwitnessbycaseref;viewcaseskeletons;caseskeletonschedule;printskeleton;viewtrialsession;addtrialsession;edittrialsession;deletetrialsession;insertwitness;inserttrialsession;saveedittrialsession;confirmdeletetrialsession;editcasedetails;updatecasedetails;saveeditwitness;searchcases;printskeletonbyweek;printskeletonbyday;viewallcasestatus

#
# Default Mapping
#

default.request = /home
default.class = uk.gov.courtservice.xhibit.web.wf.action.DefaultAction

viewsummarybyname.request = /viewsummarybyname
viewsummarybyname.class = uk.gov.courtservice.xhibit.web.wf.action.ViewSummaryByNameAction

#
#  View all court status
#

viewallcourtstatus.request = /viewallcourtstatus
viewallcourtstatus.class = uk.gov.courtservice.xhibit.web.wf.action.ViewAllCourtStatusAction

#
#  View all case status
#

viewallcasestatus.request = /viewallcasestatus
viewallcasestatus.class = uk.gov.courtservice.xhibit.web.wf.action.ViewAllCaseStatusAction

#
#
#  View daily list
#

viewdailylist.request = /viewdailylist
viewdailylist.class = uk.gov.courtservice.xhibit.web.wf.action.ViewDailyListAction

#
#  Print Witness Details
#

printwitnessdetails.request = /printwitnessdetails
printwitnessdetails.class = uk.gov.courtservice.xhibit.web.wf.action.PrintWitnessDetailsAction

#
#  Print Witness Details
#

printwitnessdetailsfuture.request = /printwitnessdetailsfuture
printwitnessdetailsfuture.class = uk.gov.courtservice.xhibit.web.wf.action.PrintWitnessDetailsFutureAction

#
#  Print Witness Details all
#

printwitnessdetailsall.request = /printwitnessdetailsall
printwitnessdetailsall.class = uk.gov.courtservice.xhibit.web.wf.action.PrintWitnessDetailsAllAction

#
#  Maintain Witness Details
#

maintainwitnessdetails.request = /maintainwitnessdetails
maintainwitnessdetails.class = uk.gov.courtservice.xhibit.web.wf.action.MaintainWitnessDetailsAction

#
#  Maintain Witness Details
#

maintainwitnessdetailsfuture.request = /maintainwitnessdetailsfuture
maintainwitnessdetailsfuture.class = uk.gov.courtservice.xhibit.web.wf.action.MaintainWitnessDetailsFutureAction

#
#  Maintain Witness Details All
#

maintainwitnessdetailsall.request = /maintainwitnessdetailsall
maintainwitnessdetailsall.class = uk.gov.courtservice.xhibit.web.wf.action.MaintainWitnessDetailsAllAction

#
#  Witness Sign In
#

witnesssignin.request = /witnesssignin
witnesssignin.class = uk.gov.courtservice.xhibit.web.wf.action.WitnessSignInAction

#
#  Witness Sign In Edit
#

witnesssigninedit.request = /witnesssigninedit
witnesssigninedit.class = uk.gov.courtservice.xhibit.web.wf.action.WitnessSignInEditAction

#
#  Edit Witness
#

editwitness.request = /editwitness
editwitness.class = uk.gov.courtservice.xhibit.web.wf.action.EditWitnessAction

#
#  Delete Witness
#

deletewitness.request = /deletewitness
deletewitness.class = uk.gov.courtservice.xhibit.web.wf.action.DeleteWitnessAction

#
#  Add Witness
#

addwitness.request = /addwitness
addwitness.class = uk.gov.courtservice.xhibit.web.wf.action.AddWitnessAction

#
#  Confirm Delete Witness
#

confirmdeletewitness.request = /confirmdeletewitness
confirmdeletewitness.class = uk.gov.courtservice.xhibit.web.wf.action.ConfirmDeleteWitnessAction
errordetails.class = uk.gov.courtservice.xhibit.web.wf.action.ErrorDetailsAction

#
#  View Witness By Case Ref
#

viewwitnessbycaseref.request = /viewwitnessbycaseref
viewwitnessbycaseref.class = uk.gov.courtservice.xhibit.web.wf.action.ViewWitnessByCaseRefAction

#
#  View Case Skeletons
#

viewcaseskeletons.request = /viewcaseskeletons
viewcaseskeletons.class = uk.gov.courtservice.xhibit.web.wf.action.ViewCaseSkeletonsAction

#
#  Case Skeleton Schedule
#

caseskeletonschedule.request = /caseskeletonschedule
caseskeletonschedule.class = uk.gov.courtservice.xhibit.web.wf.action.CaseSkeletonScheduleAction

#
#  Case Skeleton Schedule
#

printskeleton.request = /printskeleton
printskeleton.class = uk.gov.courtservice.xhibit.web.wf.action.PrintSkeletonAction

#
#  View Trial Session
#

viewtrialsession.request = /viewtrialsession
viewtrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.ViewTrialSessionAction

#
#  Add Trial Session
#

addtrialsession.request = /addtrialsession
addtrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.AddTrialSessionAction

#
#  Edit Trial Session
#

edittrialsession.request = /edittrialsession
edittrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.EditTrialSessionAction

#
#  Delete Trial Session
#

deletetrialsession.request = /deletetrialsession
deletetrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.DeleteTrialSessionAction

#
#  Insert Witness Action
#

insertwitness.request = /insertwitness
insertwitness.class = uk.gov.courtservice.xhibit.web.wf.action.InsertWitnessAction

#
#  Insert Trial Session Action
#

inserttrialsession.request = /inserttrialsession
inserttrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.InsertTrialSessionAction

#
#  Save Edit Trial Session Action

saveedittrialsession.request = /saveedittrialsession
saveedittrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.SaveEditTrialSessionAction

#
#  Confirm Delete Trial Session Action
#

confirmdeletetrialsession.request = /confirmdeletetrialsession
confirmdeletetrialsession.class = uk.gov.courtservice.xhibit.web.wf.action.ConfirmDeleteTrialSessionAction

#
#  Edit Case Details
#

editcasedetails.request = /editcasedetails
editcasedetails.class = uk.gov.courtservice.xhibit.web.wf.action.EditCaseDetailsAction

#
#  Update Case Details
#

updatecasedetails.request = /updatecasedetails
updatecasedetails.class = uk.gov.courtservice.xhibit.web.wf.action.UpdateCaseDetailsAction

#
# Save Edit Witness
#
saveeditwitness.request = /saveeditwitness
saveeditwitness.class = uk.gov.courtservice.xhibit.web.wf.action.SaveEditWitnessAction

#
#  Search Cases
#

searchcases.request = /searchcases
searchcases.class = uk.gov.courtservice.xhibit.web.wf.action.SearchCasesAction

#
#  Print skeleton by week
#

printskeletonbyweek.request = /printskeletonbyweek
printskeletonbyweek.class = uk.gov.courtservice.xhibit.web.wf.action.PrintSkeletonByWeekAction

#
#  Print skeleton by day
#

printskeletonbyday.request = /printskeletonbyday
printskeletonbyday.class = uk.gov.courtservice.xhibit.web.wf.action.PrintSkeletonByDayAction


