#
# Title:       Pages
#
# Description: This is the default Pages property file, it forms part of an
#              i18n resource bundle. ALL page urls should be accessed through
#              here this means if more complex i18n is required the jsps used
#              can be overriden by implementing a specific instance of the
#              Pages bundle. The preference is to use the same jsps and the
#              messages resource bundle.
#
# Example:     <!- Include the JSTL tag library -->
#              <%@ taglib uri="http://java.sun.com/jstl/fmt" prefix="fmt" %>
#              <!- As pages is not the default message bundle must specify -->
#              <fmt:bundle basename="Pages">
#                  <!- Retrieve the localised page url -->
#                  <fmt:message key="header.text"/>
#              </fmt:bundle>
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      Edward Cawley, Xdevelopment LLP (2003)
# $Revision: 1.3 $
#

#
# Application Pages
#

home = home.jsp
editcasedetailscomplete = editcasedetails.jsp
viewdailylist = viewdailylist.jsp
viewallcourtstatus = viewallcourtstatus.jsp
viewsummarybyname = viewsummarybyname.jsp
maintainwitnessdetails = maintainwitnessdetails.jsp
maintainwitnessdetailsfuture = maintainwitnessdetailsfuture.jsp
maintainwitnessdetailsall = maintainwitnessdetailsall.jsp
witnesssignin = witnesssignin.jsp
editwitness = editwitness.jsp
deletewitness = deletewitness.jsp
addwitness = addwitness.jsp
confirmdeletewitness = confirmdeletewitness.jsp
viewwitnessbycaseref = viewwitnessbycaseref.jsp
viewcaseskeletons = viewcaseskeletons.jsp
caseskeletonschedule = caseskeletonschedule.jsp
printskeleton = printskeleton.jsp
viewtrialsession = viewtrialsession.jsp
addtrialsession = addtrialsession.jsp
edittrialsession = edittrialsession.jsp
deletetrialsession = deletetrialsession.jsp
searchcasescomplete = searchcases.jsp
viewallcasestatus = viewallcasestatus.jsp
