#
# Title:       Responses
#
# Description: This is used by the Response Factory to control how to respond to requests.
#
# Copyright:   Copyright (c) 2003
# Company:     EDS
#
# Author:      Edward Cawley, Xdevelopment LLP (2003)
#
# $Revision: 1.3 $
#
# $Log: Response.properties,v $
# Revision 1.3  2005/04/27 08:26:58  bzjrnl
# Manual Merge From BRANCH_7_X
#
# Revision 1.1.2.1  2005/04/25 13:37:42  bzjrnl
# Changes to move jspc into the framework.
#
# Revision 1.25  2004/09/24 06:49:50  tzj8k5
# CR65 - All Case Status Page ThinClient
#
# Revision 1.24  2004/08/12 15:56:22  zz7n1c
# Merged from 6_X_BRANCH on 12/08/2004
#
# Revision 1.23.98.1  2004/08/05 15:50:15  tzj8k5
# 56014 - Amendment to error handling in the thinclient
#
# Revision 1.23  2003/06/26 11:30:30  cawleye
# factorised bits to shared
#
# Revision 1.22  2003/05/16 08:59:40  fz0n8j
# Added logout button.
#
# Revision 1.21  2003/05/14 13:09:57  fz0n8j
# Bug fixes and first version of print by day.
#
# Revision 1.20  2003/05/13 14:42:52  fz0n8j
# More updates to print schedule by week.
#
# Revision 1.19  2003/05/13 12:55:32  fz0n8j
# Adding print for schedule by week.
#
# Revision 1.18  2003/05/02 15:33:55  fz0n8j
# *** empty log message ***
#
# Revision 1.17  2003/05/01 19:10:32  fz0n8j
# *** empty log message ***
#
# Revision 1.16  2003/05/01 15:51:40  fz0n8j
# Added terminal selection to witness.
#
# Revision 1.15  2003/04/30 11:43:59  qzd3k3
# Merge from dev branch.
#
# Revision 1.14.2.5  2003/04/25 15:33:26  hzf3bb
# no message
#
# Revision 1.14.2.4  2003/04/23 14:17:41  fz0n8j
# Added edit case details.
#
# Revision 1.14.2.3  2003/04/22 17:35:27  hzf3bb
# *** empty log message ***
#
# Revision 1.14.2.2  2003/04/14 13:25:14  fz0n8j
# Now possible to view all witnesses.
#
# Revision 1.14.2.1  2003/04/09 16:17:49  fz0n8j
# Changed print to pdf printing (xsl needs more work).
#
# Revision 1.14  2003/04/04 08:38:17  fz0n8j
# Merged
#
# Revision 1.13  2003/04/04 08:30:50  hzf3bb
# no message
#
# Revision 1.12  2003/04/02 15:40:11  hzf3bb
# added new properties
#
# Revision 1.11  2003/04/02 09:27:17  hzf3bb
# *** empty log message ***
#
# Revision 1.10  2003/04/02 09:11:15  hzf3bb
# added new properties
#
# Revision 1.9  2003/04/02 09:07:26  hzf3bb
# no message
#
# Revision 1.8  2003/04/01 13:59:52  fz0n8j
# Added actions again and modified jsps/properites.
#
# Revision 1.7  2003/03/28 12:17:26  fz0n8j
# Added print for witness details.
#
# Revision 1.6  2003/03/28 11:33:11  fz0n8j
# Added witness sign in.
#
# Revision 1.5  2003/03/28 10:18:11  hzf3bb
# added view daily list messages
#
# Revision 1.4  2003/03/28 10:14:20  fz0n8j
# *** empty log message ***
#
# Revision 1.3  2003/03/28 10:07:37  fz0n8j
# *** empty log message ***
#
# Revision 1.2  2003/03/28 09:58:46  fz0n8j
# Added witness details and court status.
#
# Revision 1.1  2003/03/27 11:01:23  fz0n8j
# Added to cvs
#
#


responses = home;viewsummarybynamecomplete;viewallcourtstatuscomplete;maintainwitnessdetailscomplete;viewdailylistcomplete;witnesssignincomplete;printwitnessdetailscomplete;editwitnesscomplete;deletewitnesscomplete;addwitnesscomplete;confirmdeletewitnesscomplete;maintainwitnessdetailsfuturecomplete;maintainwitnessdetailsallcomplete;viewwitnessbycaserefcomplete;viewcaseskeletonscomplete;caseskeletonschedulecomplete;printskeletoncomplete;viewtrialsessioncomplete;addtrialsessioncomplete;edittrialsessioncomplete;deletetrialsessioncomplete;printwitnessdetailspdfcomplete;editcasedetailscomplete;searchcasescomplete;printskeletonbyweekcomplete;printskeletonbydaycomplete;viewallcasestatuscomplete

#
# Default Mapping
#

home.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
home.page = normal.jsp
home.skeletonBodyKey = home
home.skeletonTitleKey = home.title

#
# View Summary by name . . .
#

viewsummarybynamecomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewsummarybynamecomplete.page = normal.jsp
viewsummarybynamecomplete.skeletonBodyKey = viewsummarybyname
viewsummarybynamecomplete.skeletonTitleKey = viewsummarybyname.title

#
# View all court status
#

viewallcourtstatuscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewallcourtstatuscomplete.page = normal.jsp
viewallcourtstatuscomplete.skeletonBodyKey = viewallcourtstatus
viewallcourtstatuscomplete.skeletonTitleKey = viewallcourtstatus.title

#
# View all case status
#

viewallcasestatuscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewallcasestatuscomplete.page = normal.jsp
viewallcasestatuscomplete.skeletonBodyKey = viewallcasestatus
viewallcasestatuscomplete.skeletonTitleKey = viewallcasestatus.title

#
# Maintain Witness Details
#

maintainwitnessdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
maintainwitnessdetailscomplete.page = normal.jsp
maintainwitnessdetailscomplete.skeletonBodyKey = maintainwitnessdetails
maintainwitnessdetailscomplete.skeletonTitleKey = maintainwitnessdetails.title

#
# Maintain Witness Details Future
#

maintainwitnessdetailsfuturecomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
maintainwitnessdetailsfuturecomplete.page = normal.jsp
maintainwitnessdetailsfuturecomplete.skeletonBodyKey = maintainwitnessdetailsfuture
maintainwitnessdetailsfuturecomplete.skeletonTitleKey = maintainwitnessdetailsfuture.title

#
# Maintain Witness Details All
#

maintainwitnessdetailsallcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
maintainwitnessdetailsallcomplete.page = normal.jsp
maintainwitnessdetailsallcomplete.skeletonBodyKey = maintainwitnessdetailsall
maintainwitnessdetailsallcomplete.skeletonTitleKey = maintainwitnessdetailsall.title

#
# View Daily List
#

viewdailylistcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewdailylistcomplete.page = normal.jsp
viewdailylistcomplete.skeletonBodyKey = viewdailylist
viewdailylistcomplete.skeletonTitleKey = viewdailylist.title

#
# Witness Sign In
#

witnesssignincomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
witnesssignincomplete.page = normal.jsp
witnesssignincomplete.skeletonBodyKey = witnesssignin
witnesssignincomplete.skeletonTitleKey = witnesssignin.title

#
# Print Witness Details
#

printwitnessdetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
printwitnessdetailscomplete.page = printwitnessdetails.jsp

#
# Print witness Details PDF
#

printwitnessdetailspdfcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.PDFResponse
printwitnessdetailspdfcomplete.xslStyleSheet = witness.xsl

#
# Edit Witness
#

editwitnesscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editwitnesscomplete.page = normal.jsp
editwitnesscomplete.skeletonBodyKey = editwitness
editwitnesscomplete.skeletonTitleKey = editwitness.title

#
# Delete Witness
#

deletewitnesscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deletewitnesscomplete.page = normal.jsp
deletewitnesscomplete.skeletonBodyKey = deletewitness
deletewitnesscomplete.skeletonTitleKey = deletewitness.title

#
# Add Witness
#

addwitnesscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
addwitnesscomplete.page = normal.jsp
addwitnesscomplete.skeletonBodyKey = addwitness
addwitnesscomplete.skeletonTitleKey = addwitness.title

#
# Confirm Delete
#

confirmdeletewitnesscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
confirmdeletewitnesscomplete.page = normal.jsp
confirmdeletewitnesscomplete.skeletonBodyKey = confirmdeletewitness
confirmdeletewitnesscomplete.skeletonTitleKey = confirmdeletewitness.title

#
# View Witness By Case Ref
#

viewwitnessbycaserefcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewwitnessbycaserefcomplete.page = normal.jsp
viewwitnessbycaserefcomplete.skeletonBodyKey = viewwitnessbycaseref
viewwitnessbycaserefcomplete.skeletonTitleKey = viewwitnessbycaseref.title

#
# View Case Skeletons
#

viewcaseskeletonscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewcaseskeletonscomplete.page = normal.jsp
viewcaseskeletonscomplete.skeletonBodyKey = viewcaseskeletons
viewcaseskeletonscomplete.skeletonTitleKey = viewcaseskeletons.title

#
#  Case Skeleton Schedule
#

caseskeletonschedulecomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
caseskeletonschedulecomplete.page = normal.jsp
caseskeletonschedulecomplete.skeletonBodyKey = caseskeletonschedule
caseskeletonschedulecomplete.skeletonTitleKey = caseskeletonschedule.title

#
#  Case Skeleton Schedule
#

printskeletoncomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
printskeletoncomplete.page = normal.jsp
printskeletoncomplete.skeletonBodyKey = printskeleton
printskeletoncomplete.skeletonTitleKey = printskeleton.title

#
#  View Trial Session
#

viewtrialsessioncomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
viewtrialsessioncomplete.page = normal.jsp
viewtrialsessioncomplete.skeletonBodyKey = viewtrialsession
viewtrialsessioncomplete.skeletonTitleKey = viewtrialsession.title

#
#  Add Trial Session
#

addtrialsessioncomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
addtrialsessioncomplete.page = normal.jsp
addtrialsessioncomplete.skeletonBodyKey = addtrialsession
addtrialsessioncomplete.skeletonTitleKey = addtrialsession.title

#
#  Edit Trial Day Session
#

edittrialsessioncomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
edittrialsessioncomplete.page = normal.jsp
edittrialsessioncomplete.skeletonBodyKey = edittrialsession
edittrialsessioncomplete.skeletonTitleKey = edittrialsession.title

#
#  Delete Trial Session
#

deletetrialsessioncomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
deletetrialsessioncomplete.page = normal.jsp
deletetrialsessioncomplete.skeletonBodyKey = deletetrialsession
deletetrialsessioncomplete.skeletonTitleKey = deletetrialsession.title

#
# Edit case details
#

editcasedetailscomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
editcasedetailscomplete.page = normal.jsp
editcasedetailscomplete.skeletonBodyKey = editcasedetailscomplete
editcasedetailscomplete.skeletonTitleKey = editcasedetailscomplete.title

#
# Edit case details
#

searchcasescomplete.class = uk.gov.courtservice.xhibit.web.framework.response.NormalResponse
searchcasescomplete.page = normal.jsp
searchcasescomplete.skeletonBodyKey = searchcasescomplete
searchcasescomplete.skeletonTitleKey = searchcasescomplete.title

#
# Print schedule by week
#

printskeletonbyweekcomplete.class = uk.gov.courtservice.xhibit.web.framework.response.PDFResponse
printskeletonbyweekcomplete.xslStyleSheet = schedulebyweek.xsl

#
# Print schedule by week
#

printskeletonbydaycomplete.class = uk.gov.courtservice.xhibit.web.framework.response.PDFResponse
printskeletonbydaycomplete.xslStyleSheet = schedulebyday.xsl

