<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Surtar Bachra (Electronic Data Systems LTD) -->
<xs:schema targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:apd="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:include schemaLocation="OrderTypes.xsd"/>
	<xs:import namespace="http://www.govtalk.gov.uk/people/AddressAndPersonalDetails" schemaLocation="courtService/apd.xsd"/>
	<xs:complexType name="RemandOrderStructure">
		<xs:sequence>
			<xs:element name="OrderHeader" type="XHIBITCourtOrderHeaderStructure"/>
			<xs:element name="CustodyLocation" type="xs:string"/>
			<xs:element name="ReportDetails">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attributeGroup ref="ConditionAttributeGroup"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="NextAppearance" type="XHIBITCourtAppearanceStructure"/>
			<xs:element name="RemandReason">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="CommitSent">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="committed"/>
									<xs:enumeration value="sent"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="IsBefore">
							<xs:complexType>
								<xs:attributeGroup ref="ConditionAttributeGroup"/>
							</xs:complexType>
						</xs:element>
						<xs:sequence>
							<xs:element name="CrownCourt">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CourtHouse" type="CourtHouseStructure"/>
										<xs:element name="Date" type="apd:DateType"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="VoluntaryBillOfIndictment">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:date">
											<xs:attributeGroup ref="ConditionAttributeGroup"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="CertificateOfTransfer">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:date">
											<xs:attributeGroup ref="ConditionAttributeGroup"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
							<xs:element name="AppealAgainstBailGranted">
								<xs:complexType>
									<xs:attributeGroup ref="ConditionAttributeGroup"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:sequence>
					<xs:attributeGroup ref="ConditionAttributeGroup"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="RemandType" type="RemandType"/>
			<xs:element name="AdditionalInfo">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attributeGroup ref="ConditionAttributeGroup"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="AssociatedCases" type="AssociatedCaseStructure"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>
