<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 rel. 2 U (http://www.xmlspy.com) by Surtar Bachra (Electronic Data Systems LTD) -->
<xsd:schema targetNamespace="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://www.courtservice.gov.uk/schemas/courtservice/xhibit/orders" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:include schemaLocation="OrderTypes.xsd"/>
	<xsd:include schemaLocation="ImprisonmentOrder.xsd"/>
	<xsd:complexType name="YoungOffenderOrderStructure">
		<xsd:complexContent>
			<xsd:extension base="ImprisonmentOrderStructure"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="YoungOffenderOrder" type="YoungOffenderOrderStructure"/>
</xsd:schema>
