select count(*) from cji_document;
update cji_cjip_message set status_id = 6 where correlation_id in (select correlation_id from cji_cjip_message where sent_date +&1< sysdate);
commit;
select count(*) from cji_cjip_message where status_id=6;
update cji_document set status_id = 8 where document_id in (select document_id from cji_document where creation_date + &1 <sysdate);
commit;
delete from cji_bits_message where document_id in (select document_id from cji_document where status_id = 8);
commit;
update cji_event set status_id = 3 where event_id in (select event_id from cji_cjip_message where sent_date + &1 + 1 < sysdate and event_id is not null);
commit;
delete from cji_cjip_message where status_id = 6;
commit;
delete from cji_document where status_id = 8;
commit;
delete from cji_event where status_id=3;
commit;
select count(*) from cji_cjip_message where status_id=6;
select count(*) from cji_document;
exit;
