DROP TABLE XHB_ORDER_DISPOSAL;
DROP TABLE XHB_ORDER;
DROP TABLE XHB_ORDER_TEMPLATE;
DROP TABLE XHB_ORDER_DELIVERY_STATUS;
DROP TABLE XHB_ORDER_STATUS;
DROP TABLE XHB_ORDER_TYPE;

CREATE TABLE XHB_ORDER_TYPE
	(
		ORDER_TYPE_ID			NUMBER(9)	CONSTRAINT XOT_ID_PK			PRIMARY KEY,
		CODE				VARCHAR2(20)	CONSTRAINT XOT_CODE_NN			NOT NULL,
		LAST_UPDATE_DATE		DATE		CONSTRAINT XOT_LAST_UPDATE_DATE_NN	NOT NULL,
		CREATION_DATE			DATE		CONSTRAINT XOT_CREATION_DATE_NN		NOT NULL,
		CREATED_BY			VARCHAR2(30)	CONSTRAINT XOT_CREATED_BY_NN		NOT NULL,
		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XOT_LAST_UPDATED_BY_NN	NOT NULL,
		VERSION				NUMBER		CONSTRAINT XOT_VERSION_NN		NOT NULL,
		OBS_IND				VARCHAR2(1)
	);

INSERT INTO XHB_ORDER_TYPE
SELECT	1,
	'BAILORDER',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
COMMIT;

CREATE TABLE XHB_ORDER_STATUS
	(
		ORDER_STATUS_ID			NUMBER(9)	CONSTRAINT XOS_ID_PK			PRIMARY KEY,
		CODE				VARCHAR2(20)	CONSTRAINT XOS_CODE_NN			NOT NULL,
		LAST_UPDATE_DATE		DATE		CONSTRAINT XOS_LAST_UPDATE_DATE_NN	NOT NULL,
		CREATION_DATE			DATE		CONSTRAINT XOS_CREATION_DATE_NN		NOT NULL,
		CREATED_BY			VARCHAR2(30)	CONSTRAINT XOS_CREATED_BY_NN		NOT NULL,
		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XOS_LAST_UPDATED_BY_NN	NOT NULL,
		VERSION				NUMBER		CONSTRAINT XOS_VERSION_NN		NOT NULL,
		OBS_IND				VARCHAR2(1)
	);

INSERT INTO XHB_ORDER_STATUS
SELECT	1,
	'SAVED',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
INSERT INTO XHB_ORDER_STATUS
SELECT	2,
	'PRINTED',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
INSERT INTO XHB_ORDER_STATUS
SELECT	3,
	'SIGNED',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
COMMIT;

CREATE TABLE XHB_ORDER_DELIVERY_STATUS
	(
		ORDER_DELIVERY_STATUS_ID	NUMBER(9)	CONSTRAINT XODS_ID_PK			PRIMARY KEY,
		CODE				VARCHAR2(20)	CONSTRAINT XODS_CODE_NN			NOT NULL,
		LAST_UPDATE_DATE		DATE		CONSTRAINT XODS_LAST_UPDATE_DATE_NN	NOT NULL,
		CREATION_DATE			DATE		CONSTRAINT XODS_CREATION_DATE_NN	NOT NULL,
		CREATED_BY			VARCHAR2(30)	CONSTRAINT XODS_CREATED_BY_NN		NOT NULL,
		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XODS_LAST_UPDATED_BY_NN	NOT NULL,
		VERSION				NUMBER		CONSTRAINT XODS_VERSION_NN		NOT NULL,
		OBS_IND				VARCHAR2(1)
	);
INSERT INTO XHB_ORDER_DELIVERY_STATUS
SELECT	1,
	'NOTREADY',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
INSERT INTO XHB_ORDER_DELIVERY_STATUS
SELECT	2,
	'READY',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
INSERT INTO XHB_ORDER_DELIVERY_STATUS
SELECT	3,
	'DELIVERED',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
INSERT INTO XHB_ORDER_DELIVERY_STATUS
SELECT	4,
	'FAILED',
	SYSDATE,
	SYSDATE,
	USER,
	USER,
	1,
	null
FROM DUAL;
COMMIT;


CREATE TABLE XHB_ORDER_TEMPLATE
	(
		ORDER_TEMPLATE_ID		NUMBER(9)	CONSTRAINT XOTMP_ID_PK				PRIMARY KEY,
		EDITOR_TEMPLATE_NAME		VARCHAR2(255)	CONSTRAINT XOTMP_EDITOR_TEMPLATE_NAME_NN	NOT NULL,
		NARRATIVE_TEMPLATE_NAME		VARCHAR2(255)	CONSTRAINT XOTMP_NARRATIVE_TMPLT_NAME_NN	NOT NULL,
		DISPLAY_TRANSFORM_NAME		VARCHAR2(255)	CONSTRAINT XOTMP_DISPLAY_TRNSFRM_NAME_NN	NOT NULL,
		ORDER_TYPE			NUMBER(9)	CONSTRAINT XOTMP_ORDER_TYPE_NN			NOT NULL,
		LAST_UPDATE_DATE		DATE		CONSTRAINT XOTMP_LAST_UPDATE_DATE_NN		NOT NULL,
		CREATION_DATE			DATE		CONSTRAINT XOTMP_CREATION_DATE_NN		NOT NULL,
		CREATED_BY			VARCHAR2(30)	CONSTRAINT XOTMP_CREATED_BY_NN			NOT NULL,
		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XOTMP_LAST_UPDATED_BY_NN		NOT NULL,
		VERSION				NUMBER		CONSTRAINT XOTMP_VERSION			NOT NULL,
		OBS_IND				VARCHAR2(1),
		CONSTRAINT	XOTMP_ORDER_TYPE_FK
			FOREIGN KEY (ORDER_TYPE)
			REFERENCES XHB_ORDER_TYPE(ORDER_TYPE_ID),
		CONSTRAINT      XOTMP_UNIQUENESS UNIQUE
					(EDITOR_TEMPLATE_NAME, NARRATIVE_TEMPLATE_NAME, DISPLAY_TRANSFORM_NAME, ORDER_TYPE)
	);

CREATE TABLE XHB_ORDER
	(
		ORDER_ID			NUMBER(9)	CONSTRAINT XO_ID_PK			PRIMARY KEY,
		DATA_XML			CLOB		CONSTRAINT XO_DATA_XML_NN		NOT NULL,
		SIGNING_DATE			DATE,
		SIGNED_BY			VARCHAR2(30),
		DELIVERY_DATE			DATE,
		ORDER_STATUS			NUMBER(9)	CONSTRAINT XO_STATUS_NN			NOT NULL,
		ORDER_DELIVERY_STATUS		NUMBER(9)	CONSTRAINT XO_DELIVERY_STATUS_NN	NOT NULL,
		ORDER_TEMPLATE			NUMBER(9)	CONSTRAINT XO_TEMPLATE_NN		NOT NULL,
		LAST_UPDATE_DATE		DATE		CONSTRAINT XO_LAST_UPDATE_DATE_NN	NOT NULL,
		CREATION_DATE			DATE		CONSTRAINT XO_CREATION_DATE_NN		NOT NULL,
		CREATED_BY			VARCHAR2(30)	CONSTRAINT XO_CREATED_BY_NN		NOT NULL,
		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XO_LAST_UPDATED_BY_NN	NOT NULL,
		VERSION				NUMBER		CONSTRAINT XO_VERSION			NOT NULL,
		OBS_IND				VARCHAR2(1),
		CONSTRAINT	XO_ORDER_STATUS_FK
			FOREIGN KEY (ORDER_STATUS)
			REFERENCES XHB_ORDER_STATUS(ORDER_STATUS_ID),
		CONSTRAINT	XO_ORDER_DELIVERY_STATUS_FK
			FOREIGN KEY (ORDER_DELIVERY_STATUS)
			REFERENCES XHB_ORDER_DELIVERY_STATUS(ORDER_DELIVERY_STATUS_ID),
		CONSTRAINT	XO_ORDER_TEMPLATE_FK
			FOREIGN KEY (ORDER_TEMPLATE)
			REFERENCES XHB_ORDER_TEMPLATE(ORDER_TEMPLATE_ID)
	);

--CREATE TABLE XHB_ORDER_DISPOSAL
--	(
--		ORDER_DISPOSAL_ID		NUMBER(9)	CONSTRAINT XOD_ID_PK			PRIMARY KEY,
--		ORDER				NUMBER(9)	CONSTRAINT XOD_ORDER_NN			NOT NULL,
--		DISPOSAL			NUMBER(9)	CONSTRAINT XOD_DISPOSAL_NN		NOT NULL,
--		LAST_UPDATE_DATE		DATE		CONSTRAINT XOD_LAST_UPDATE_DATE_NN	NOT NULL,
--		CREATION_DATE			DATE		CONSTRAINT XOD_CREATION_DATE_NN		NOT NULL,
--		CREATED_BY			VARCHAR2(30)	CONSTRAINT XOD_CREATED_BY_NN		NOT NULL,
--		LAST_UPDATED_BY			VARCHAR2(30)	CONSTRAINT XOD_LAST_UPDATED_BY_NN	NOT NULL,
--		VERSION				NUMBER		CONSTRAINT XOD_VERSION			NOT NULL,
--		OBS_IND				VARCHAR2(1)
--		CONSTRAINT	XOD_ORDER_FK
--			FOREIGN KEY (ORDER)
--			REFERENCES XHB_ORDER(ORDER_ID),
--		CONSTRAINT	XOD_DISPOSAL_FK
--			FOREIGN KEY (DISPOSAL)
--			REFERENCES ??(??),
--		CONSTRAINT      XOD_UNIQUENESS UNIQUE
--					(ORDER, DISPOSAL)
--	);
