CREATE TABLE XHBSTG_CASE_HEARING_DAY_DM
(
CHD_ID                                  NUMBER (8) NOT NULL,
CASE_NO                                 NUMBER (8) NOT NULL,
CASE_TYPE                               VARCHAR2(1) NOT NULL,
LIST_DATE                               DATE     ,
OLD_CHD_ID                              NUMBER (8)   ,
LFXC_JOB_ID                             NUMBER (8)   ,
TIME_MARKING                            VARCHAR2(78)   ,
PRIORITY                                VARCHAR2(1)   ,
COURT_LIST_IND                          VARCHAR2(1)   ,
NHA_JOB_ID                              NUMBER (8)   ,
HWLET_JOB_ID                            NUMBER (8)   ,
HFLET_JOB_ID                            NUMBER (8)   ,
CC_IND                                  VARCHAR2(2)   ,
CHD_SITE_CODE                           VARCHAR2(1)   ,
REASON_REMOVED                          VARCHAR2(80)   ,
FXL_JOB_ID                              NUMBER (8)   ,
CTD_ID                                  NUMBER (8)   ,
UNREC_CASE_TITLE                        VARCHAR2(72)   ,
UNREC_CASE_NO                           VARCHAR2(10)   ,
LIST_NOTES                              VARCHAR2(78)   ,
LIST_TYPE                               VARCHAR2(1)   ,
LIST_SEQUENCE                           NUMBER (3)   ,
DATE_REMOVED                            DATE     ,
DURATION                                NUMBER (3)   ,
DATE_PUBLISHED                          DATE     ,
FIX_AUTHORITY                           VARCHAR2(1)   ,
HEARING_TYPE                            VARCHAR2(3)   ,
DATE_LISTED                             DATE     ,
EFFECTIVE_IND                           VARCHAR2(3)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
