CREATE TABLE XHBSTG_CHARGE_DM
(
CASE_TYPE                               VARCHAR2(1) NOT NULL,
CASE_NO                                 NUMBER (8) NOT NULL,
SUB_ID                                  NUMBER (8) NOT NULL,
CHARGE_TYPE                             VARCHAR2(1) NOT NULL,
CHARGE_NO                               NUMBER (2) NOT NULL,
HO_PROC_TYPE                            VARCHAR2(2)   ,
OFFENCE_CODE                            VARCHAR2(8)   ,
PLEA                                    VARCHAR2(3)   ,
HO_CLASS                                VARCHAR2(3)   ,
DVLC_CODE                               VARCHAR2(4)   ,
OFFENCE_DESCRIPTION                     VARCHAR2(240)   ,
APPEAL_TYPE                             VARCHAR2(1)   ,
APP_RESULT_CODE                         VARCHAR2(8)   ,
CHG_ID                                  NUMBER (8) NOT NULL,
LESSER_OFF                              VARCHAR2(240)   ,
CHG_DATE                                DATE     ,
HO_SUB_CLASS                            VARCHAR2(2)   ,
MULTIPLE                                NUMBER (2)   ,
BCH_ID                                  NUMBER (8)   ,
ARREST_SUMMONS_NUMBER                   VARCHAR2(23)   ,
SEQUENCE_NO                             NUMBER (3)   ,
ADDR1                                   VARCHAR2(30)   ,
ADDR2                                   VARCHAR2(30)   ,
ADDR3                                   VARCHAR2(30)   ,
ADDR4                                   VARCHAR2(30)   ,
TOWN                                    VARCHAR2(30)   ,
COUNTY                                  VARCHAR2(30)   ,
POSTCODE                                VARCHAR2(8)   ,
FORCE_LOCATION_CODE                     VARCHAR2(4)   ,
OFFENCE_START_DATE                      DATE     ,
OFFENCE_END_DATE                        DATE     ,
ARREST_DATE                             DATE     ,
CHARGE_DATE                             DATE     ,
COMMITTED_ON_BAIL                       VARCHAR2(1)   ,
OFFENCE_START_TIME                      VARCHAR2(5)   ,
OFFENCE_END_TIME                        VARCHAR2(5)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
