CREATE TABLE XHBSTG_DATA_MIGRATION_LOG
(
	"DATA_MIGRATION_LOG_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"COURT_ID" NUMBER(8,0) NOT NULL ENABLE, 
	"ACTION_NAME" VARCHAR2(500 BYTE) NOT NULL ENABLE, 
	"RUN_TIME" DATE, 
	"LOG_MESSAGE_TYPE" VARCHAR2(10 BYTE), 
	"LOG_MESSAGE" VARCHAR2(500 BYTE), 
	"ERROR_ROW_COUNT" NUMBER, 
	"SUCCESS_ROW_COUNT" NUMBER, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 BYTE) NOT NULL ENABLE
)
/
