CREATE TABLE XHBSTG_DISPOSAL_DM
(
DIS_ID                                  NUMBER (8) NOT NULL,
DISPOSAL_CODE                           VARCHAR2(7) NOT NULL,
CASE_TYPE                               VARCHAR2(1) NOT NULL,
CASE_NO                                 NUMBER (8) NOT NULL,
MENU_GROUP                              VARCHAR2(3) NOT NULL,
TEMPLATE_VERSION                        NUMBER (3) NOT NULL,
SUB_ID                                  NUMBER (8) NOT NULL,
UNITS2                                  VARCHAR2(8)   ,
EFFECTIVE                               VARCHAR2(1)   ,
OUTCOME_DATE                            DATE     ,
COURT_TYPE                              VARCHAR2(1)   ,
CHG_ID                                  NUMBER (8)   ,
LINE_AVAIL                              NUMBER (2)   ,
MO_ACKNOWLEDGEMENT_DATE                 DATE     ,
DOCUMENT_DATE                           DATE     ,
AMOUNT1                                 NUMBER (10,2)   ,
PSD_CT_CODE                             VARCHAR2(4)   ,
CCC_STATS_CODE                          VARCHAR2(3)   ,
CTL_ID                                  NUMBER (8)   ,
MO_OTHER                                NUMBER (10,2)   ,
MO_CONFISCATION                         NUMBER (10,2)   ,
MO_COSTS                                NUMBER (10,2)   ,
MO_COMPENSATION                         NUMBER (10,2)   ,
UNITS1                                  VARCHAR2(8)   ,
AMOUNT2                                 NUMBER (10,2)   ,
MO_FINE                                 NUMBER (10,2)   ,
APP_RESULT_CODE                         VARCHAR2(8)   ,
PSD_DIS_ID                              NUMBER (8)   ,
COU_ID                                  NUMBER (8)   ,
CONV_RECORDED                           VARCHAR2(1)   ,
DISPOSAL_REPLACED                       VARCHAR2(1)   ,
GUARD_FLAG                              VARCHAR2(1)   ,
DEFENDANT_CONVICTED                     VARCHAR2(1)   ,
ELECTRONIC_MONITORING                   VARCHAR2(1)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
