OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)

LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_HOME_COURT_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
NAME                                    ,
WARNED_PERIOD_CV                        ,
DX_REF                                  ,
PASSWORD_CHANGE_DATE                    ,
PASSWORD_AGE_LIMIT                      ,
SYSAC_END_TIME                          ,
SYSAC_START_TIME                        ,
LCD_STATS_CODE                          ,
CURRENT_RTP_NO                          ,
WARNED_PERIOD                           ,
HCC_WARNED_PERIOD                       ,
NAME_PREFIX                             ,
HO_POL_FORCE_CODE                       ,
POL_FORCE_NAME                          ,
FAX_NO                                  ,
CIVIL_STAFF                             ,
CRIMINAL_STAFF                          ,
COMBINED_COURT_IND                      ,
PMG_ACC_CODE                            ,
TEL_NO                                  ,
POSTCODE                                ,
COUNTY                                  ,
TOWN                                    ,
ADDR4                                   ,
ADDR3                                   ,
ADDR2                                   ,
FIRM_PERIOD                             ,
FIRM_PERIOD_CV                          ,
FIRM_PERIOD_CO                          ,
WL_REP_PERIOD                           ,
WL_REP_TIME                             ,
WL_TEXT1                                ,
WL_TEXT2                                ,
WL_TEXT3                                ,
ADDR1                                   ,
MAX_VOUCHER_NO                          ,
COURT_START_TIME                        ,
CRREP_MAX_DATE                          ,
CCREP_MAX_DATE                          ,
TIER                                    ,
WGREP_MAX_DATE                          ,
OVNITE_PROS                             ,
PERFORM_BKUP                            ,
PERFORM_PWRDWN                          ,
REDO_DIR                                ,
COUNTY_LCD_STATS_CODE                   ,
WL_REP_PERIOD_CV                        ,
WL_REP_TIME_CV                          ,
WL_TEXT1_CV                             ,
WL_TEXT2_CV                             ,
WL_TEXT3_CV                             ,
PERFORM_XFER                            ,
HCC_FL_ORDER                            ,
CR_FL_ORDER                             ,
CO_FL_ORDER                             ,
FIN_YEAR_CURR                           ,
PERFORM_EXPIMP                          ,
PERFORM_HK                              ,
LIX_IND                                 ,
CCS_INDEX_FREE                          ,
CROWN_LOC_CODE                          ,
COUNTY_LOC_CODE                         ,
CRIMINAL_AREA                           ,
CIVIL_AREA                              ,
EMAIL_LISTS                             ,
EMAIL_HOST                              ,
EMAIL_USERS                             ,
EXPENSES_THRESHOLD                      ,
SOL_CLAIM_SORT                          ,
GEN_CLAIM_SORT                          ,
CRIME_MONITORING_SITE                   ,
XHIBIT_COURT                            ,
WARNED_LIST_PARAM                       ,
FIRM_LIST_PARAM                         ,
DAILY_LIST_PARAM                        ,
DEFAULT_LIST_PARAM                      ,
CASE_HK_PARAM                           ,
ROWNUM_PARAM                            ,
CREST_COURT_ID                           
)
