OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_case_opposer_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_TYPE,
OPP_ID,
CASE_NO,
OPPOSER_TYPE,
OPPOSER_CASE_REF,
COLLECTING_COURT,
CREST_COURT_ID
)
