OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE XHBSTG_BW_HISTORY_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_TYPE,
CASE_NO,
SUB_ID,
BC_STATUS_BW_ISSUED,
BC_STATUS_BW_EXECUTED,
BW_ISSUE_DATE, 
BW_EXEC_DATE,
BW_INPUT_DATE,  
CREST_COURT_ID
)
