OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_WARNED_LIST_DETAILS_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CC_IND,
WARNED_PERIOD,
WL_REP_PERIOD,
WL_REP_TIME,
WL_TEXT1,
WL_TEXT2,
WL_TEXT3,
WL_REP_SORT,
CREST_COURT_ID                         
)
