OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_CASE_HISTORY_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_TYPE,
CASE_NO,
PSD_CT_CODE,
COMM_DATE,
DATE_CLOSED,
REASON_DELETED,
CASE_TITLE,
DATE_ARCHIVED,
SENT_FOR_TRIAL_DATE,
CREST_COURT_ID                         
)
