OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_judge_ticket_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
JUD_ID,
TICKET_TYPE,
CREST_COURT_ID
)
