OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_CHARGE_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_TYPE,
CASE_NO,
SUB_ID,
CHARGE_TYPE,
CHARGE_NO,
HO_PROC_TYPE,
OFFENCE_CODE,
PLEA,
HO_CLASS,
DVLC_CODE,
OFFENCE_DESCRIPTION,
APPEAL_TYPE,
APP_RESULT_CODE,
CHG_ID,
LESSER_OFF,
CHG_DATE,
HO_SUB_CLASS,
MULTIPLE,
BCH_ID,
ARREST_SUMMONS_NUMBER,
SEQUENCE_NO,
ADDR1,
ADDR2,
ADDR3,
ADDR4,
TOWN,
COUNTY,
POSTCODE,
FORCE_LOCATION_CODE,
OFFENCE_START_DATE,
OFFENCE_END_DATE,
ARREST_DATE,
CHARGE_DATE,
COMMITTED_ON_BAIL,
OFFENCE_START_TIME,
OFFENCE_END_TIME,
CREST_COURT_ID                         
)
