OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_COURTROOM_DAY_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CTD_ID,
JP1_NAME,
JUD_ID,
JP2_NAME,
JP4_NAME,
SITTING_NOTE,
LIST_TYPE,
COMMIT_FLAG,
START_TIME,
OLD_CTD_ID,
JUD_SEQ_NO,
JUD_SIT_TYPE,
JP3_NAME,
LIST_DATE,
COURTROOM_NO,
SITE_CODE,
JUD_SIT_IND,
CREST_COURT_ID                         
)
