OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_CASE_HEARING_DAY_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CHD_ID,
CASE_NO,
CASE_TYPE,
LIST_DATE,
OLD_CHD_ID,
LFXC_JOB_ID,
TIME_MARKING,
PRIORITY,
COURT_LIST_IND,
NHA_JOB_ID,
HWLET_JOB_ID,
HFLET_JOB_ID,
CC_IND,
CHD_SITE_CODE,
REASON_REMOVED,
FXL_JOB_ID,
CTD_ID,
UNREC_CASE_TITLE,
UNREC_CASE_NO,
LIST_NOTES,
LIST_TYPE,
LIST_SEQUENCE,
DATE_REMOVED,
DURATION,
DATE_PUBLISHED,
FIX_AUTHORITY,
HEARING_TYPE,
DATE_LISTED,
EFFECTIVE_IND,
CREST_COURT_ID                         
)
