OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)

LOAD DATA
INFILE '$xhb_in_file'  
APPEND
INTO TABLE DATA_MIG.XHBSTG_CASE_SUBJECT_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_NO                                 ,
SUB_ID                                  ,
CASE_TYPE                               ,
CCC_TRANS_TO                            ,
LIF_REC_DATE                            ,
ANT_PLEA                                ,
SODPA_DATE                              ,
CACD_RESULT1                            ,
CACD_RESULT2                            ,
CACD_RESULT3                            ,
CACD_RESULT4                            ,
DEF_CASE_IND                            ,
DATE_TRANS_TO                           ,
CACD_APPEAL_RESULT                      ,
DATE_TRANS_TO_RECORDED                  ,
BC_STATUS_BW_ISSUED                     ,
COMM_BC_STATUS                          ,
BC_STATUS_BW_EXECUTED                   ,
MED_REP_IND                             ,
MED_REP_TYPE                            ,
MED_REP_AVAIL_DATE                      ,
SEC_10_ADMIT_IND                        ,
ADD_LIST_INFO                           ,
CACD_FORMS_DATE                         ,
COMM_LA_STATUS                          ,
HIGHER_COURT_NOTE                       ,
LAST_CONV_DATE                          ,
LIVE_STATUS                             ,
PSD_LA_REF                              ,
CACD_APPEAL_RESULT_DATE                 ,
D_PB_ADV2_TELNO                         ,
D_PB_ADV1_TELNO                         ,
JUVENILE_IND                            ,
DEFENDANT_NO                            ,
FORM_NG_SENT_DATE                       ,
D_PB_ADV2                               ,
D_PB_ADV1                               ,
COLLECTING_COURT                        ,
LIF_SENT_DATE                           ,
BENCH_WARRANT_EXEC_DATE                 ,
CURRENT_BC_STATUS                       ,
HRG_LEN_DSOL_UNIT                       ,
CORROB_WITS_IND                         ,
PLEA_ALT_CHARGE                         ,
LIST_FOR_PLEA                           ,
PRLIS_JOB_ID                            ,
BW_INPUT_DATE                           ,
NO_DEF_WITS                             ,
NO_PROF_WITS                            ,
HRG_LEN_DSOL                            ,
HIGHER_CT_REQ_DATE                      ,
HIGHER_CT_NAME                          ,
HO_TICS                                 ,
HO_FINAL_LICENCE_STATUS                 ,
FIRST_MAG_HRG_DATE                      ,
LAST_MAG_HRG_DATE                       ,
SPECIAL_CIR_FOUND                       ,
CTL_APPLIES                             ,
CTL_EXPIRY_DATE                         ,
CTL_FREE_TEXT                           ,
DATE_NON_HRG_DISP                       ,
ETHNIC_APPEARANCE                       ,
ETHNIC_CLASSIFICATION                   ,
PERSISTENT_OFFENDER_IND                 ,
POLICE_NATIONAL_COMPUTER                ,
PTIURN                                  ,
ARREST_SUMMONS_NUMBER                   ,
CACD_STATUS                             ,
NHD_STATUS                              ,
NATIONALITY                             ,
CUSTODIAL                               ,
SUSPENDED                               ,
DRUGS                                   ,
DEPORTATION                             ,
RS_PORTAL_DATE                          ,
RS_AMENDED_PORTAL_DATE                  ,
RS_AMEND_REASON                         ,
HATE_IND                                ,
HATE_TYPE                               ,
HATE_SENT_IND                           ,
CREST_COURT_ID                         
)
