OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_LISTS_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
LST_ID,
START_DATE,
END_DATE,
DATE_PUBLISHED,
LIST_TYPE,
CC_IND,
LIST_STATUS,
EDITION_NO,
FCL_START_TIME,
CREST_COURT_ID                         
)
