OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_SOLICITOR_FIRM_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
SOF_ID,
FIRM_NAME,
ADDR1,
ADDR2,
ADDR3,
ADDR4,
TOWN,
COUNTY,
POSTCODE,
TEL_NO,
VAT_NO,
LA_CODE,
LONDON_WEIGHTING,
FAX_NO,
OBS_IND,
CREATOR_ID,
DATE_CREATED,
DX_REF,
SHORT_NAME,
SOF_EMAIL,
SOF_EMAIL_SECURE,
CREST_COURT_ID                         
)
