OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_non_avail_dates_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
NAD_ID,
CASE_NO,
CASE_TYPE,
REASON,
START_DATE,
END_DATE,
CREST_COURT_ID
)
