OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_CASE_SUB_APPEARANCE_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CASE_TYPE,
CASE_NO,
CHD_ID,
SUB_ID,
DEFENDANT_NO,
COURT_LIST_IND,
NOTIF_JOB_ID,
COPY_DW_DEFT,
CREST_COURT_ID                         
)
