OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file' 
APPEND
INTO TABLE xhbstg_disposal_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
DIS_ID, 
DISPOSAL_CODE, 
CASE_TYPE, 
CASE_NO, 
MENU_GROUP, 
TEMPLATE_VERSION, 
SUB_ID, 
UNITS2, 
EFFECTIVE, 
OUTCOME_DATE, 
COURT_TYPE, 
CHG_ID, 
LINE_AVAIL, 
MO_ACKNOWLEDGEMENT_DATE, 
DOCUMENT_DATE, 
AMOUNT1, 
PSD_CT_CODE, 
CCC_STATS_CODE, 
CTL_ID, 
MO_OTHER, 
MO_CONFISCATION, 
MO_COSTS, 
MO_COMPENSATION, 
UNITS1, 
AMOUNT2, 
MO_FINE, 
APP_RESULT_CODE, 
PSD_DIS_ID, 
COU_ID, 
CONV_RECORDED, 
DISPOSAL_REPLACED, 
GUARD_FLAG, 
DEFENDANT_CONVICTED, 
ELECTRONIC_MONITORING, 
CREST_COURT_ID
)
