OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_case_party_sof_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CPF_ID,
CASE_TYPE,
CASE_NO,
REP_ST_DATE,
REP_END_DATE,
LEO_SEQ,
LIF_REC_DATE,
LIF_SENT_DATE,
LEO_ID,
REP_TYPE,
SOL_REF,
SUB_OPP_ID,
PARTY_TYPE,
SOF_ID,
CREST_COURT_ID
)
