OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_case_note_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CAN_ID,
NOTE,
CASE_NO,
DIARY_DATE,
NOTE_TYPE,
CASE_TYPE,
NOTE_DATE,
NOTE_PRINT_IND,
CREST_COURT_ID
)
