OPTIONS (
SKIP=1,
READSIZE=5000000,
BINDSIZE=5000000,
ROWS=1000
)
LOAD data
INFILE '$xhb_in_file'
APPEND
INTO TABLE xhbstg_legal_aid_order_dm
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
LEO_ID,
CASE_TYPE,
PARTY_TYPE,
COL_IND,
SUB_OPP_ID,
CASE_NO,
LA_DATE,
NO_OF_COUNSEL,
PSD_CROWN_CT_IND,
DATE_REFUSED_SUB_OPP,
NO_OF_QC,
REFUSAL_COURT,
REFUSAL_DATE,
LA_RETURNED,
LA_REMITTED,
REVOC_REASON,
REVOC_DATE,
NO_OF_SOLS,
PSD_LA_REF,
PRINT_JOB_ID,
CREST_COURT_ID
)
