OPTIONS (SKIP=1, READSIZE=5000000, BINDSIZE=5000000, ROWS=1000)
LOAD DATA
INFILE '$xhb_in_file'
APPEND
INTO TABLE DATA_MIG.XHBSTG_CHAMBERS_DM
WHEN (CREST_COURT_ID != '')
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
CHA_ID,
OBS_IND,
LOCATION_CODE,
POSTCODE,
CREATOR_ID,
TEL_NO,
FAX_NO,
DATE_CREATED,
ADDR1,
ADDR2,
ADDR3,
ADDR4,
TOWN,
COUNTY,
CLERK_NAME,
DX_REF,
CENTRAL_IND,
FIRM_NAME,
CHA_EMAIL,
CHA_EMAIL_SECURE,
HEAD_OF_CHAMBERS,
CREST_COURT_ID                         
)

