CREATE TABLE XHBSTG_COURTROOM_LOCATION_DM
(
CTL_ID                                  NUMBER (8) NOT NULL,
SITE_NAME                               VARCHAR2(35)   ,
ADDR1                                   VARCHAR2(30)   ,
ADDR2                                   VARCHAR2(30)   ,
ADDR3                                   VARCHAR2(30)   ,
ADDR4                                   VARCHAR2(30)   ,
POSTCODE                                VARCHAR2(8)   ,
TEL_NO                                  VARCHAR2(14)   ,
TOWN                                    VARCHAR2(30)   ,
COUNTY                                  VARCHAR2(30)   ,
OBS_IND                                 VARCHAR2(1)   ,
FAX_NO                                  VARCHAR2(14)   ,
SITE_CODE                               VARCHAR2(1)   ,
LCD_STATS_CODE                          VARCHAR2(3)   ,
LIST_NAME                               VARCHAR2(39)   ,
SITE_GROUP                              NUMBER (2)   ,
FLOATER_TEXT                            VARCHAR2(88)   ,
TIER                                    VARCHAR2(1)   ,
IND_ONLY_ALLOWED                        VARCHAR2(1)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
