CREATE TABLE XHBSTG_CASE_SUBJECT_DM
(
CASE_NO                                 NUMBER (8) NOT NULL,
SUB_ID                                  NUMBER (8) NOT NULL,
CASE_TYPE                               VARCHAR2(1) NOT NULL,
CCC_TRANS_TO                            VARCHAR2(3)   ,
LIF_REC_DATE                            DATE     ,
ANT_PLEA                                VARCHAR2(2)   ,
SODPA_DATE                              DATE     ,
CACD_RESULT1                            VARCHAR2(60)   ,
CACD_RESULT2                            VARCHAR2(60)   ,
CACD_RESULT3                            VARCHAR2(60)   ,
CACD_RESULT4                            VARCHAR2(60)   ,
DEF_CASE_IND                            VARCHAR2(1)   ,
DATE_TRANS_TO                           DATE     ,
CACD_APPEAL_RESULT                      VARCHAR2(2)   ,
DATE_TRANS_TO_RECORDED                  DATE     ,
BC_STATUS_BW_ISSUED                     VARCHAR2(1)   ,
COMM_BC_STATUS                          VARCHAR2(1)   ,
BC_STATUS_BW_EXECUTED                   VARCHAR2(1)   ,
MED_REP_IND                             VARCHAR2(1)   ,
MED_REP_TYPE                            VARCHAR2(240)   ,
MED_REP_AVAIL_DATE                      DATE     ,
SEC_10_ADMIT_IND                        VARCHAR2(1)   ,
ADD_LIST_INFO                           VARCHAR2(240)   ,
CACD_FORMS_DATE                         DATE     ,
COMM_LA_STATUS                          VARCHAR2(2)   ,
HIGHER_COURT_NOTE                       VARCHAR2(240)   ,
LAST_CONV_DATE                          DATE     ,
LIVE_STATUS                             VARCHAR2(1)   ,
PSD_LA_REF                              VARCHAR2(20)   ,
CACD_APPEAL_RESULT_DATE                 DATE     ,
D_PB_ADV2_TELNO                         VARCHAR2(14)   ,
D_PB_ADV1_TELNO                         VARCHAR2(14)   ,
JUVENILE_IND                            VARCHAR2(1)   ,
DEFENDANT_NO                            NUMBER (3)   ,
FORM_NG_SENT_DATE                       DATE     ,
D_PB_ADV2                               VARCHAR2(20)   ,
D_PB_ADV1                               VARCHAR2(20)   ,
COLLECTING_COURT                        VARCHAR2(4)   ,
LIF_SENT_DATE                           DATE     ,
BENCH_WARRANT_EXEC_DATE                 DATE     ,
CURRENT_BC_STATUS                       VARCHAR2(1)   ,
HRG_LEN_DSOL_UNIT                       VARCHAR2(6)   ,
CORROB_WITS_IND                         VARCHAR2(2)   ,
PLEA_ALT_CHARGE                         VARCHAR2(1)   ,
LIST_FOR_PLEA                           VARCHAR2(1)   ,
PRLIS_JOB_ID                            NUMBER (8)   ,
BW_INPUT_DATE                           DATE     ,
NO_DEF_WITS                             NUMBER (3)   ,
NO_PROF_WITS                            NUMBER (3)   ,
HRG_LEN_DSOL                            NUMBER (3,1)   ,
HIGHER_CT_REQ_DATE                      DATE     ,
HIGHER_CT_NAME                          VARCHAR2(35)   ,
HO_TICS                                 NUMBER (4)   ,
HO_FINAL_LICENCE_STATUS                 NUMBER (1)   ,
FIRST_MAG_HRG_DATE                      DATE     ,
LAST_MAG_HRG_DATE                       DATE     ,
SPECIAL_CIR_FOUND                       VARCHAR2(1) NOT NULL,
CTL_APPLIES                             VARCHAR2(1)   ,
CTL_EXPIRY_DATE                         DATE     ,
CTL_FREE_TEXT                           VARCHAR2(78)   ,
DATE_NON_HRG_DISP                       DATE     ,
ETHNIC_APPEARANCE                       VARCHAR2(1) NOT NULL,
ETHNIC_CLASSIFICATION                   VARCHAR2(2) NOT NULL,
PERSISTENT_OFFENDER_IND                 VARCHAR2(1) NOT NULL,
POLICE_NATIONAL_COMPUTER                VARCHAR2(10)   ,
PTIURN                                  VARCHAR2(11)   ,
ARREST_SUMMONS_NUMBER                   VARCHAR2(20)   ,
CACD_STATUS                             VARCHAR2(1)   ,
NHD_STATUS                              VARCHAR2(1)   ,
NATIONALITY                             VARCHAR2(3)   ,
CUSTODIAL                               VARCHAR2(1)   ,
SUSPENDED                               VARCHAR2(1)   ,
DRUGS                                   VARCHAR2(1)   ,
DEPORTATION                             VARCHAR2(1)   ,
RS_PORTAL_DATE                          DATE     ,
RS_AMENDED_PORTAL_DATE                  DATE     ,
RS_AMEND_REASON                         VARCHAR2(100)   ,
HATE_IND                                VARCHAR2(1)   ,
HATE_TYPE                               VARCHAR2(2)   ,
HATE_SENT_IND                           VARCHAR2(1)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
