CREATE TABLE XHBSTG_CHAMBERS_DM
(
CHA_ID                                  NUMBER (8) NOT NULL,
ADDR1                                   VARCHAR2(30)   ,
ADDR2                                   VARCHAR2(30)   ,
ADDR3                                   VARCHAR2(30)   ,
ADDR4                                   VARCHAR2(30)   ,
TOWN                                    VARCHAR2(30)   ,
COUNTY                                  VARCHAR2(30)   ,
POSTCODE                                VARCHAR2(8)   ,
TEL_NO                                  VARCHAR2(14)   ,
CLERK_NAME                              VARCHAR2(35)   ,
OBS_IND                                 VARCHAR2(1)   ,
FAX_NO                                  VARCHAR2(14)   ,
DX_REF                                  VARCHAR2(35)   ,
LOCATION_CODE                           VARCHAR2(2)   ,
CREATOR_ID                              VARCHAR2(10)   ,
DATE_CREATED                            VARCHAR2(17)   ,
CENTRAL_IND                             VARCHAR2(1)   ,
FIRM_NAME                               VARCHAR2(35)   ,
CHA_EMAIL                               VARCHAR2(255)   ,
CHA_EMAIL_SECURE                        VARCHAR2(255)   ,
HEAD_OF_CHAMBERS                        VARCHAR2(35)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
