CREATE TABLE XHBSTG_SUBJECT_DM
(
SUB_ID                                  NUMBER (8) NOT NULL,
CURRENT_PRISON_STATUS                   VARCHAR2(1)   ,
DRIVING_LICENCE_NO                      VARCHAR2(16)   ,
SURNAME                                 VARCHAR2(35)   ,
FORENAME2                               VARCHAR2(35)   ,
FORENAME1                               VARCHAR2(35)   ,
TOWN                                    VARCHAR2(30)   ,
COMM_PSD_LA_REF                         VARCHAR2(30)   ,
GUARDIAN_NAME                           VARCHAR2(35)   ,
HOSP_POSTCODE                           VARCHAR2(8)   ,
HOSP_ADDR4                              VARCHAR2(30)   ,
HOSP_ADDR3                              VARCHAR2(30)   ,
HOSP_ADDR2                              VARCHAR2(30)   ,
HOSP_ADDR1                              VARCHAR2(30)   ,
HOSP_COUNTY                             VARCHAR2(30)   ,
HOSP_TOWN                               VARCHAR2(30)   ,
COUNTY                                  VARCHAR2(30)   ,
HOSPITAL_NAME                           VARCHAR2(35)   ,
CRO_NO                                  VARCHAR2(9)   ,
DOB                                     DATE     ,
SEX                                     VARCHAR2(1)   ,
POSTCODE                                VARCHAR2(8)   ,
ADDR4                                   VARCHAR2(30)   ,
ADDR3                                   VARCHAR2(30)   ,
ADDR2                                   VARCHAR2(30)   ,
ADDR1                                   VARCHAR2(30)   ,
INITIALS                                VARCHAR2(4)   ,
REMAND_PRISON                           VARCHAR2(35)   ,
AGE                                     NUMBER (2)   ,
FORMER_SURNAME                          VARCHAR2(35)   ,
PRISONER_NO                             VARCHAR2(8)   ,
GUARDIAN_STATUS                         VARCHAR2(1)   ,
ETHNIC_APPEARANCE                       VARCHAR2(1)   ,
PRISON_ID                               VARCHAR2(4)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
