ALTER TABLE XHB_COURTEL_LIST MODIFY 
(
COURTEL_RESPONSE_SERVER_1 VARCHAR2(3000),
COURTEL_RESPONSE_SERVER_2 VARCHAR2(3000)
);
ALTER TABLE AUD_COURTEL_LIST MODIFY
(
COURTEL_RESPONSE_SERVER_1 VARCHAR2(3000),
COURTEL_RESPONSE_SERVER_2 VARCHAR2(3000)
);

COMMIT;