<?xml version="1.0" encoding="UTF-8"?>

<project basedir="." default="all" name="ThickClientTestingFramework">
    <description>
        Testing framework classes for the rich client
    </description>

    <import file="./../../tools/ant/framework.xml" />
    
    <property name="project.type.builds.jar" value="set" />
    <property name="project.type.requires.compilation" value="set" />

    <!--
      =======================================================================
        Initialise Override
      =======================================================================
      -->
    <target name="initialise" unless="skip.initialise" depends="framework.initialise">
        <log target="initialise"/>
        <path id="compile.classpath">
            <path refid="lib.classpath"/>
            <fileset dir="${build.dest.dir}">
                <include name="Framework.jar" />
                <include name="ThickClientFramework.jar" />
            </fileset>
        </path>
    </target>
</project>
