CREATE TABLE XHBSTG_CASE_DM
(
CASE_NO                                 NUMBER (8) NOT NULL,
CASE_TYPE                               VARCHAR2(1) NOT NULL,
PROS_PB_ADV1_TELNO                      VARCHAR2(14)   ,
DATE_IND_SIGNED                         DATE     ,
DATE_IND_REC                            DATE     ,
DATE_CONCLUDED                          DATE     ,
DATE_CLOSED                             DATE     ,
CTL_ID                                  NUMBER (8)   ,
COMM_DATE                               DATE     ,
CLASS                                   NUMBER (1)   ,
CCC_TRANS_TO                            VARCHAR2(3)   ,
DATE_TRANS_TO_RECORDED                  DATE     ,
DATE_TRANS_TO                           DATE     ,
DATE_TRANS_FROM                         DATE     ,
DATE_REOPENED                           DATE     ,
DATE_RECEIVED                           DATE     ,
DATE_INPUT                              DATE     ,
CCC_TRANS_FROM                          VARCHAR2(3)   ,
PROS_PB_ADV2                            VARCHAR2(20)   ,
PROS_PB_ADV2_TELNO                      VARCHAR2(14)   ,
PSD_CT_CODE                             VARCHAR2(4)   ,
PSD_REFERENCE                           VARCHAR2(30)   ,
RECEIPT_TYPE                            VARCHAR2(2)   ,
REQ_JUDGE_TYPE                          VARCHAR2(2)   ,
RE_TRIAL                                VARCHAR2(1)   ,
RL_END_DATE                             DATE     ,
SECURITY_IND                            VARCHAR2(1)   ,
TOTAL_DEFTS                             NUMBER (3)   ,
TRIAL_EXT_DATE                          DATE     ,
TRIAL_LAST_DATE                         DATE     ,
VIDEO_IND                               VARCHAR2(1)   ,
DS_IND                                  VARCHAR2(1)   ,
PRLIS_JOB_ID                            NUMBER (8)   ,
BW_DS_IND                               VARCHAR2(1)   ,
WL_REVIEW_DATE                          DATE     ,
EITHER_WAY_TYPE                         VARCHAR2(2)   ,
FCIR_JOB_ID                             NUMBER (8)   ,
FIX_CONF_DATE                           DATE     ,
FIX_REQ_IND                             VARCHAR2(1)   ,
HO_POL_FORCE                            VARCHAR2(2)   ,
HO_PSD_HRG_TYPE                         NUMBER (1)   ,
HRG_LEN_LO                              NUMBER (3,1)   ,
HRG_LEN_LO_UNIT                         VARCHAR2(1)   ,
HRG_LEN_PSOL                            NUMBER (3,1)   ,
HRG_LEN_PSOL_UNIT                       VARCHAR2(1)   ,
INDICT_RESP                             VARCHAR2(50)   ,
IND_COMMENTS1                           VARCHAR2(78)   ,
IND_COMMENTS2                           VARCHAR2(78)   ,
CASE_TITLE                              VARCHAR2(72)   ,
IND_COMMENTS3                           VARCHAR2(78)   ,
IND_COMMENTS4                           VARCHAR2(78)   ,
IND_COMMENTS5                           VARCHAR2(78)   ,
IND_COMMENTS6                           VARCHAR2(78)   ,
INIT_HRG_TYPE                           VARCHAR2(3)   ,
ITLIM_JOB_ID                            NUMBER (8)   ,
LC_CONV_DATE                            DATE     ,
LC_SENT_DATE                            DATE     ,
LG010_EDITION_NO                        NUMBER (4)   ,
LIVE_STATUS                             VARCHAR2(1)   ,
NEW_APPEAL_TYPE                         VARCHAR2(1)   ,
NO_CB_WITS                              NUMBER (3)   ,
NO_FB_WITS                              NUMBER (3)   ,
NO_PROF_WITS                            NUMBER (3)   ,
OBS_BW                                  VARCHAR2(1)   ,
ORIGINAL_CASE_NO                        VARCHAR2(9)   ,
ORIG_JP1_NAME                           VARCHAR2(35)   ,
ORIG_JP2_NAME                           VARCHAR2(35)   ,
ORIG_JP3_NAME                           VARCHAR2(35)   ,
ORIG_JP4_NAME                           VARCHAR2(35)   ,
OTHER_PROS_WITS                         NUMBER (3)   ,
PROS_PB_ADV1                            VARCHAR2(20)   ,
ANT_DELAY_REASONS                       VARCHAR2(78)   ,
APPEAL_DESCRIPT                         VARCHAR2(70)   ,
APPEAL_TYPE                             VARCHAR2(1)   ,
APP_RESULT                              VARCHAR2(3)   ,
APP_RESULT_DATE                         DATE     ,
BC_STATUS                               VARCHAR2(1)   ,
BW_IND                                  VARCHAR2(1)   ,
CASE_GROUP                              NUMBER (7)   ,
LIST_AVAIL                              VARCHAR2(1)   ,
PLEA_DIRECTION_DATE                     DATE     ,
DEFAULT_LIST_NOTE                       VARCHAR2(78)   ,
UNLINK_REASON_CODE                      VARCHAR2(1)   ,
SEVERED_IND                             VARCHAR2(1)   ,
PAGES_EVIDENCE                          NUMBER (6)   ,
PDH_ESTIMATE                            NUMBER (3)   ,
FULL_TRIAL_STATUS_DATE                  DATE     ,
SENT_FOR_TRIAL_DATE                     DATE     ,
PROS_PAPERS_SERVED_DATE                 DATE     ,
OFFENCE_GROUP_UPGRADE                   VARCHAR2(1)   ,
DATE_CTL_REMINDER_PRINTED               DATE     ,
CRIME_MONITORING_CATEGORY               VARCHAR2(2) NOT NULL,
TICKET_REQD                             VARCHAR2(1)   ,
TICKET_TYPE                             VARCHAR2(3)   ,
INTIMIDATED_WITNESS                     VARCHAR2(1)   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
