CREATE TABLE XHBSTG_HOME_COURT_DM
(
NAME                                    VARCHAR2(35) NOT NULL,
WARNED_PERIOD_CV                        NUMBER (2)   ,
DX_REF                                  VARCHAR2(35)   ,
PASSWORD_CHANGE_DATE                    DATE     ,
PASSWORD_AGE_LIMIT                      NUMBER (4)   ,
SYSAC_END_TIME                          VARCHAR2(4)   ,
SYSAC_START_TIME                        VARCHAR2(4)   ,
LCD_STATS_CODE                          VARCHAR2(3)   ,
CURRENT_RTP_NO                          NUMBER (7)   ,
WARNED_PERIOD                           NUMBER (2)   ,
HCC_WARNED_PERIOD                       NUMBER (2)   ,
NAME_PREFIX                             VARCHAR2(14)   ,
HO_POL_FORCE_CODE                       VARCHAR2(2)   ,
POL_FORCE_NAME                          VARCHAR2(60)   ,
FAX_NO                                  VARCHAR2(14)   ,
CIVIL_STAFF                             NUMBER (3)   ,
CRIMINAL_STAFF                          NUMBER (3)   ,
COMBINED_COURT_IND                      VARCHAR2(1)   ,
PMG_ACC_CODE                            VARCHAR2(5)   ,
TEL_NO                                  VARCHAR2(14)   ,
POSTCODE                                VARCHAR2(8)   ,
COUNTY                                  VARCHAR2(30)   ,
TOWN                                    VARCHAR2(30)   ,
ADDR4                                   VARCHAR2(30)   ,
ADDR3                                   VARCHAR2(30)   ,
ADDR2                                   VARCHAR2(30)   ,
FIRM_PERIOD                             NUMBER (2)   ,
FIRM_PERIOD_CV                          NUMBER (2)   ,
FIRM_PERIOD_CO                          NUMBER (2)   ,
WL_REP_PERIOD                           NUMBER (2)   ,
WL_REP_TIME                             VARCHAR2(8)   ,
WL_TEXT1                                VARCHAR2(80)   ,
WL_TEXT2                                VARCHAR2(80)   ,
WL_TEXT3                                VARCHAR2(80)   ,
ADDR1                                   VARCHAR2(30)   ,
MAX_VOUCHER_NO                          NUMBER (7)   ,
COURT_START_TIME                        VARCHAR2(8)   ,
CRREP_MAX_DATE                          VARCHAR2(20)   ,
CCREP_MAX_DATE                          VARCHAR2(20)   ,
TIER                                    VARCHAR2(1)   ,
WGREP_MAX_DATE                          VARCHAR2(20)   ,
OVNITE_PROS                             VARCHAR2(4)   ,
PERFORM_BKUP                            VARCHAR2(1)   ,
PERFORM_PWRDWN                          VARCHAR2(1)   ,
REDO_DIR                                VARCHAR2(1)   ,
COUNTY_LCD_STATS_CODE                   VARCHAR2(3)   ,
WL_REP_PERIOD_CV                        NUMBER (2)   ,
WL_REP_TIME_CV                          VARCHAR2(8)   ,
WL_TEXT1_CV                             VARCHAR2(80)   ,
WL_TEXT2_CV                             VARCHAR2(80)   ,
WL_TEXT3_CV                             VARCHAR2(80)   ,
PERFORM_XFER                            VARCHAR2(1)   ,
HCC_FL_ORDER                            VARCHAR2(1)   ,
CR_FL_ORDER                             VARCHAR2(1)   ,
CO_FL_ORDER                             VARCHAR2(1)   ,
FIN_YEAR_CURR                           DATE     ,
PERFORM_EXPIMP                          VARCHAR2(1)   ,
PERFORM_HK                              VARCHAR2(1)   ,
LIX_IND                                 VARCHAR2(1)   ,
CCS_INDEX_FREE                          NUMBER (2)   ,
CROWN_LOC_CODE                          VARCHAR2(5)   ,
COUNTY_LOC_CODE                         VARCHAR2(5)   ,
CRIMINAL_AREA                           NUMBER (3)   ,
CIVIL_AREA                              NUMBER (3)   ,
EMAIL_LISTS                             VARCHAR2(1)   ,
EMAIL_HOST                              VARCHAR2(8)   ,
EMAIL_USERS                             VARCHAR2(1)   ,
EXPENSES_THRESHOLD                      NUMBER (6,2)   ,
SOL_CLAIM_SORT                          VARCHAR2(1) NOT NULL,
GEN_CLAIM_SORT                          VARCHAR2(1) NOT NULL,
CRIME_MONITORING_SITE                   VARCHAR2(1) NOT NULL,
XHIBIT_COURT                            VARCHAR2(1)   ,
WARNED_LIST_PARAM                       NUMBER (3)   ,
FIRM_LIST_PARAM                         NUMBER (3)   ,
DAILY_LIST_PARAM                        NUMBER (3)   ,
DEFAULT_LIST_PARAM                      NUMBER (3)   ,
CASE_HK_PARAM                           NUMBER (3)   ,
ROWNUM_PARAM                            NUMBER   ,
CREST_COURT_ID                          VARCHAR2(3),
XHIBIT_COURT_ID                         VARCHAR2(3),
XHIBIT_ETL_STATUS                       CHAR(1),
XHIBIT_LOADED_DATE                      DATE DEFAULT SYSDATE,
XHIBIT_ENRICH_DATE                      DATE,
XHIBIT_ETL_DATE                         DATE,
XHIBIT_ETL_ERR_MESSAGE                  VARCHAR2(500)
)
/
