SCJRequestId: string requestId
SCJSourceId: string sourceId
SCJDestinationId: string destId
SCJExecMode: string ASYNCH
SCJTimestamp: string 20060202 151327
SCJType: string EXCEPTION
SCJAckRequested: string true
SCJMessageIdentifier: string identifier
SCJRequestingSystemEnvironment: string requestingSysEnv
SCJRequestingSystemName: string requestingSysEnv
SCJRequestingSystemOrgUnitCode: string requestingSysOrgUnitCode
SCJCreationDateTime: string 20060202
SCJExpiryDateTime: string 20060715
SCJOriginatingSystemName: string originatingSysName
SCJOriginatingSystemOrgUnitCode: string originatingSysOrgUnitCode
SCJOriginatingSystemEnvironment: string originatingSysEnv
SCJMessageSchemaIdentifier: string messageSchemaIdentifier
SCJMessageSchemaNamespace: string messageSchemaNamespace
SCJMessageSchemaVersion: string messageSchemaVersion
SCJMessageTypeType: string messageTypeType
SCJMessageTypeVersion: string messageTypeversion
SCJCrestCourtId: string 453
SCJCorrelationId: long 18