/*    ------------------------------------------------------------------
*     Add columns to XHB_LEGAL_AID_ORDER table
*/    ------------------------------------------------------------------

ALTER TABLE XHB_LEGAL_AID_ORDER ADD(
CASE_PROS_AGENCY_ID NUMBER(8),
ORDER_DATE DATE,
GRANTED_BY VARCHAR2(2),
PSD_RO_REF VARCHAR2(20),
NUMBER_OF_ADVOCATES NUMBER(2),
NUMBER_OF_QCS NUMBER(2),
SOLICITOR_REFERENCE VARCHAR2(255),
REF_SOLICITOR_FIRM_ID NUMBER(8),
DATE_OF_REVOCATION DATE,
REASON_FOR_REVOCATION_ID NUMBER(8),
REP_START_DATE DATE,
REP_END_DATE DATE
);

-- Create/Recreate primary, unique and foreign key constraints 
ALTER TABLE XHB_LEGAL_AID_ORDER ADD (CONSTRAINT XHB_CASE_PROS_AGENCY_ID_FK FOREIGN KEY (CASE_PROS_AGENCY_ID) REFERENCES XHB_CASE_PROSECUTOR_AGENCY(CASE_PROS_AGENCY_ID));
ALTER TABLE XHB_LEGAL_AID_ORDER ADD (CONSTRAINT XHB_REF_SOLICITOR_FIRM_ID_FK FOREIGN KEY (REF_SOLICITOR_FIRM_ID) REFERENCES XHB_REF_SOLICITOR_FIRM(REF_SOLICITOR_FIRM_ID));
ALTER TABLE XHB_LEGAL_AID_ORDER ADD (CONSTRAINT XHB_REASON_FOR_REV_ID_FK FOREIGN KEY (REASON_FOR_REVOCATION_ID) REFERENCES XHB_REF_SYSTEM_CODE(REF_SYSTEM_CODE_ID));


/*    ------------------------------------------------------------------
*     Add columns to AUD_LEGAL_AID_ORDER table
*/    ------------------------------------------------------------------

ALTER TABLE AUD_LEGAL_AID_ORDER ADD (
CASE_PROS_AGENCY_ID NUMBER(8),
ORDER_DATE DATE,
GRANTED_BY VARCHAR2(2),
PSD_RO_REF VARCHAR2(20),
NUMBER_OF_ADVOCATES NUMBER(2),
NUMBER_OF_QCS NUMBER(2),
SOLICITOR_REFERENCE VARCHAR2(255),
REF_SOLICITOR_FIRM_ID NUMBER(8),
DATE_OF_REVOCATION DATE,
REASON_FOR_REVOCATION_ID NUMBER(8),
REP_START_DATE DATE,
REP_END_DATE DATE);



/*    ------------------------------------------------------------------
*     CREATE DATABASE TRIGGERS
*/    ------------------------------------------------------------------

@@XHB_LEGAL_AID_ORDER_bur_tr.sql;


commit;
/