/*ctx-1915*/
ALTER TABLE XHB_DEFENDANT_ON_CASE ADD(DATE_RCPT_NOTICE_APPEAL DATE);
ALTER TABLE XHB_DEFENDANT_ON_CASE ADD(CACD_APPEAL_RESULT VARCHAR2(240));
ALTER TABLE XHB_DEFENDANT_ON_CASE ADD(COA_STATUS VARCHAR2(1));

ALTER TABLE AUD_DEFENDANT_ON_CASE ADD(DATE_RCPT_NOTICE_APPEAL DATE);
ALTER TABLE AUD_DEFENDANT_ON_CASE ADD(CACD_APPEAL_RESULT VARCHAR2(240));
ALTER TABLE AUD_DEFENDANT_ON_CASE ADD(COA_STATUS VARCHAR2(1));
 
@@xhb_defendantoncase_bur_tr.sql;

commit;