/* xhb_case_listing_entry */
CREATE INDEX XHB_CLE_COURT_SITE_FK ON xhb_case_listing_entry(COURT_SITE_ID);
CREATE INDEX XHB_CLE_REF_JUDGE_TYPE_FK ON xhb_case_listing_entry(REF_JUDGE_TYPE_ID);
CREATE INDEX XHB_CLE_JUDGE_FK ON xhb_case_listing_entry(JUDGE_ID);
CREATE INDEX XHB_CLE_CASE_FK ON xhb_case_listing_entry(CASE_ID); 
CREATE INDEX XHB_CLE_COURT_FK ON xhb_case_listing_entry(COURT_ID); 

/* xhb_diary_note_entry */
CREATE INDEX XHB_DNE_CASE_LISTING_ENTRY_FK ON xhb_diary_note_entry(CASE_LISTING_ENTRY_ID);
CREATE INDEX XHB_DNE_NOTE_TYPE_FK ON xhb_diary_note_entry(NOTE_TYPE_ID);
CREATE INDEX XHB_DNE_DIARY_NOTE_CLASS_FK ON xhb_diary_note_entry(NOTE_CLASSIFICATION_ID);
CREATE INDEX XHB_DNE_DIARY_NOTE_PRE_DEF_FK ON xhb_diary_note_entry(DIARY_NOTE_PRE_DEFINED_ID);
CREATE INDEX XHB_DNE_COURT_ID_FK ON xhb_diary_note_entry(COURT_ID);

/* xhb_case_diary_fixture */
CREATE INDEX XHB_CDF_CASE_LISTING_ENTRY_FK ON xhb_case_diary_fixture(CASE_LISTING_ENTRY_ID);
CREATE INDEX XHB_CDF_HEARING_TYPE_FK ON xhb_case_diary_fixture(HEARING_TYPE_ID);
CREATE INDEX XHB_CDF_LIST_NOTE_PRE_DEF_FK ON xhb_case_diary_fixture(LIST_NOTE_PRE_DEFINED_ID);
CREATE INDEX XHB_CDF_PRE_DEF_NOTE_CLASS_FK ON xhb_case_diary_fixture(PRE_DEF_NOTE_CLASS_ID);
CREATE INDEX XHB_CDF_FREE_TXT_NOTE_CLASS_FK ON xhb_case_diary_fixture(FREE_TEXT_NOTE_CLASS_ID);
CREATE INDEX XHB_CDF_VAC_PRE_DEFINE_RSON_FK ON xhb_case_diary_fixture(VACATION_PRE_DEFINED_RSON_ID);

/* xhb_fixture_deft_attending */
CREATE INDEX XHB_FDA_DEFENDANT_ON_CASE_FK ON xhb_fixture_deft_attending(DEFENDANT_ON_CASE_ID);
CREATE INDEX XHB_FDA_CASE_DIARY_FIXTURE_FK ON xhb_fixture_deft_attending(CASE_DIARY_FIXTURE_ID); 

/* xhb_case_non_avail_days */
CREATE INDEX XHB_CNAD_CASE_ID_FK ON xhb_case_non_avail_days(CASE_ID);

/* xhb_list */
CREATE INDEX XHB_LIST_COURT_FK ON xhb_list(COURT_ID);
CREATE INDEX XHB_LIST_LIST_TYPE_FK ON xhb_list(LIST_TYPE_ID); 
CREATE INDEX XHB_LIST_LIST_PARENT_ID_FK ON xhb_list(LIST_PARENT_ID);

/* xhb_case_on_list */
CREATE INDEX XHB_CASE_ON_LIST_CASE_FK ON xhb_case_on_list(CASE_ID);
CREATE INDEX XHB_CASE_ON_LIST_COURT_ROOM_FK ON xhb_case_on_list(COURT_ROOM_ID);
CREATE INDEX XHB_CASE_ON_LIST_COURT_SITE_FK ON xhb_case_on_list(COURT_SITE_ID);
CREATE INDEX XHB_CASE_ON_LIST_LIST_FK ON xhb_case_on_list(LIST_ID);
CREATE INDEX XHB_CASE_ON_LIST_HEAR_TYPE_FK ON xhb_case_on_list(HEARING_TYPE_ID);
CREATE INDEX XHB_CASE_ON_LIST_SITTING_FK ON xhb_case_on_list(SITTING_ID);
CREATE INDEX XHB_CASE_ON_LIST_TM_MARKING_FK ON xhb_case_on_list(TIME_MARKING_ID);
CREATE INDEX XHB_CASE_ON_LIST_CRACK_INE_FK ON xhb_case_on_list(CRACKED_INEFFECTIVE_ID);

/* xhb_sitting_on_list */
CREATE INDEX XHB_SOL_FREE_TXT_NOTE_CLASS_FK ON xhb_sitting_on_list(FREE_TEXT_NOTE_CLASS_ID);
CREATE INDEX XHB_SOL_JUDGE_REF_FK ON xhb_sitting_on_list(JUDGE_REF_ID);
CREATE INDEX XHB_SOL_LIST_NOTE_PRE_DEF_FK ON xhb_sitting_on_list(LIST_NOTE_PRE_DEFINED_ID);
CREATE INDEX XHB_SOL_LIST_FK ON xhb_sitting_on_list(LIST_ID);
CREATE INDEX XHB_SOL_PRE_DEF_NOTE_CLASS_FK ON xhb_sitting_on_list(PRE_DEF_NOTE_CLASSIFICATION_ID);
CREATE INDEX XHB_SOL_TIME_MARKING_FK ON xhb_sitting_on_list(TIME_MARKING_ID);