ALTER TABLE XHB_CASE_LISTING_ENTRY DROP 
(TICKET_TYPE_ID, INTERPRETER);

ALTER TABLE AUD_CASE_LISTING_ENTRY DROP 
(TICKET_TYPE_ID, INTERPRETER);
  
ALTER TABLE XHB_CASE_LISTING_ENTRY ADD
(COURT_ID NUMBER(8) NOT NULL);

ALTER TABLE AUD_CASE_LISTING_ENTRY ADD
(COURT_ID NUMBER(8) NOT NULL);
  
ALTER TABLE XHB_CASE_LISTING_ENTRY MODIFY 
(VERSION NUMBER(5) NOT NULL);

ALTER TABLE AUD_CASE_LISTING_ENTRY MODIFY 
(VERSION NUMBER(5) NOT NULL);
  
@@xhb_case_listing_entry_bur_tr.sql;

commit;