ALTER TABLE XHB_REF_JUDGE_TICKET ADD
(	COURT_ID NUMBER NOT NULL,
	OBS_IND VARCHAR2(1)
);

ALTER TABLE XHB_REF_JUDGE_TICKET
ADD CONSTRAINT REF_JUDGE_TICKET_COURT_ID_FK FOREIGN KEY (court_id) REFERENCES XHB_COURT(court_id); 

ALTER TABLE AUD_REF_JUDGE_TICKET ADD
(
	COURT_ID NUMBER NOT NULL,
	OBS_IND VARCHAR2(1)
);

@@xhb_ref_judge_ticket_bur_tr.sql;

COMMIT;
/