ALTER TABLE XHB_CASE ADD
(SECTION28_NAME1 VARCHAR2(50),
 SECTION28_NAME2 VARCHAR2(50),
 SECTION28_PHONE1 VARCHAR2(15),
 SECTION28_PHONE2 VARCHAR2(15));
 
ALTER TABLE AUD_CASE ADD
(SECTION28_NAME1 VARCHAR2(50),
 SECTION28_NAME2 VARCHAR2(50),
 SECTION28_PHONE1 VARCHAR2(15),
 SECTION28_PHONE2 VARCHAR2(15));
 
ALTER TABLE XHB_CASE DROP CONSTRAINT CASE_DEFAULT_HEARING_TYPE_FK;

ALTER TABLE XHB_CASE ADD CONSTRAINT CASE_DEFAULT_HEARING_TYPE_FK
	FOREIGN KEY(DEFAULT_HEARING_TYPE)
	REFERENCES XHB_REF_HEARING_TYPE(REF_HEARING_TYPE_ID);
 
@@xhb_case_bur_tr.sql;

commit;