CREATE OR REPLACE TRIGGER XHB_CASEDIARYFIXTURE_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_CASE_DIARY_FIXTURE
  FOR EACH ROW

DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  /* Determine whether UPDATING or DELETING */
  IF UPDATING THEN

    l_trig_event := 'U';

    /* If the user is the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN
      /* Someone has pulled the rug out from below! */

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    /* If the user is not the connection pool user as defined in XHB_SYS_USER_INFORMATION */
    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_CASE_DIARY_FIXTURE') = 1) THEN
	INSERT INTO AUD_CASE_DIARY_FIXTURE
		(CASE_DIARY_FIXTURE_ID,
		CASE_LISTING_ENTRY_ID,
		LISTING_DATE,
		FIXTURE_NOTICE_REQUIRED,
		HEARING_TYPE_ID,
		LIST_NOTE_PRE_DEFINED_ID,
		LIST_NOTE_TEXT,
		PRE_DEF_NOTE_CLASS_ID,
		FREE_TEXT_NOTE_CLASS_ID,
		VACATION_PRE_DEFINED_RSON_ID,
		VACATION_FREETEXT_REASON,
		STATUS,
		OBS_IND,
		CREATED_BY,
		LAST_UPDATED_BY,
		CREATION_DATE,
		LAST_UPDATE_DATE,
		VERSION,
		DATE_VACATED,
		INSERT_EVENT)
	VALUES (:OLD.CASE_DIARY_FIXTURE_ID,
		:OLD.CASE_LISTING_ENTRY_ID,
		:OLD.LISTING_DATE,
		:OLD.FIXTURE_NOTICE_REQUIRED,
		:OLD.HEARING_TYPE_ID,
		:OLD.LIST_NOTE_PRE_DEFINED_ID,
		:OLD.LIST_NOTE_TEXT,
		:OLD.PRE_DEF_NOTE_CLASS_ID,
		:OLD.FREE_TEXT_NOTE_CLASS_ID,
		:OLD.VACATION_PRE_DEFINED_RSON_ID,
		:OLD.VACATION_FREETEXT_REASON,
		:OLD.STATUS,
		:OLD.OBS_IND,
		:OLD.CREATED_BY,
		:OLD.LAST_UPDATED_BY,
		:OLD.CREATION_DATE,
		:OLD.LAST_UPDATE_DATE,
		:OLD.VERSION,
		:OLD.DATE_VACATED,
		l_trig_event);
  END IF;
END;
/
