------------------------------------------------------------------------------
--CHANGES TO UPDATE THE VERSION NUMBER FOR THE SCHEMAS WHICH ARE SENT TO EXISS 
------------------------------------------------------------------------------

-- UPDATE the EXISS database, on the table EXI_REF_TYPE

--AppealRecordSheet
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='AR'; 

--CommittalRecordSheet
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='SR';  

--BailOrder
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='BO';  

--Bench Warrant
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='BW';  

--Community Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='CO'; 

--Community Punishment Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='CPR';

--Daily List
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='DL';

--Firm List
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='FL';

--Prison Daily List
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='DLP';

--Running List
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='RL';

--Remand Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='RO';

--Skeleton Schedule
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='SS';

--Trial Record Sheet
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='TR';

--Warned List
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='WL';

--Young Offender Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='YOI';

--Imprisonment Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='IO';

--Community Punishment Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='CPO';

--Community Rehab Order
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='CRO';

--Charges
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='CH';

--Pre Sentence Report
UPDATE EXI_REF_TYPE SET VERSION='5.2' WHERE INTERNAL_CODE='PSR';

COMMIT;
