INSERT INTO XHB_REF_EVENT_DESCRIPTION 
(EXTERNAL_EVENT_CODE, EVENT_DESCRIPTION, EVENT_SUB_DESCRIPTION, SEND_TO_MIS)
SELECT subqry.EXTERNAL_EVENT_CODE, 'Capture Sentence' EVENT_DESCRIPTION, subqry.DISPOSAL_CODE EVENT_SUB_DESCRIPTION, 'Y' SEND_TO_MIS FROM (
	SELECT 13822 EXTERNAL_EVENT_CODE, 'SVRO'   DISPOSAL_CODE FROM DUAL
) subqry 
WHERE NOT EXISTS (SELECT 1 FROM XHB_REF_EVENT_DESCRIPTION x2 
                   WHERE x2.EXTERNAL_EVENT_CODE = subqry.EXTERNAL_EVENT_CODE
                     AND x2.EVENT_SUB_DESCRIPTION = subqry.DISPOSAL_CODE);
commit;