@drop_court_data.SQL

--_________________________
--Set up the Rotation Sets.
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
--Need to think about how to clear down the tables
--before inserting the data contained here...
--Probably 'delete from XHB_ROTATION_SET WHERE DEFAULT_YN='Y';'
--which means that user specified rotation sets will be left
--alone.
INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  1,
        C.COURT_ID,
        'Public View',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  2,
        C.COURT_ID,
        'Court Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  3,
        C.COURT_ID,
        'Jury Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  4,
        C.COURT_ID,
        'All Lists',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)SELECT  5,
        C.COURT_ID,
        'Public View',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  6,
        C.COURT_ID,
        'Court Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  7,
        C.COURT_ID,
        'Jury Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  8,
        C.COURT_ID,
        'All Lists',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  9,
        C.COURT_ID,
        'Public View',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  10,
        C.COURT_ID,
        'Court Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  11,
        C.COURT_ID,
        'Jury Room',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';

INSERT INTO XHB_ROTATION_SETS
(
    ROTATION_SET_ID,
    COURT_ID,
    DESCRIPTION,
    DEFAULT_YN
)
SELECT  12,
        C.COURT_ID,
        'All Lists',
        'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';

--___________________________
--Assign Display Documents to
--the Rotation Sets.
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    1,
    1, --public_view_rs --Snaresbrook
    4, --AllCourtStatus
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    2,
    1, --public_view_rs --Snaresbrook
    5, --SummaryByName
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    3,
    1, --public_view_rs --Snaresbrook
    3, --DailyList
    20,
    3
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    4,
    2, --court_room_rs --Snaresbrook
    2, --CourtList
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    5,
    2, --court_room_rs --Snaresbrook
    1, --CourtDetail
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    6,
    3, --jury_room_rs --Snaresbrook
    6, --JuryCurrentStatus
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    7,
    4, --all_list_rs --Snaresbrook
    1, --JuryCurrentStatus
    20,
    1
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    8,
    4, --all_list_rs --Snaresbrook
    2, --JuryCurrentStatus
    20,
    2
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    9,
    4, --all_list_rs --Snaresbrook
    3, --JuryCurrentStatus
    20,
    3
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    10,
    4, --all_list_rs --Snaresbrook
    4, --JuryCurrentStatus
    20,
    4
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    11,
    4, --all_list_rs --Snaresbrook
    5, --JuryCurrentStatus
    20,
    5
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    12,
    4, --all_list_rs --Snaresbrook
    6, --JuryCurrentStatus
    20,
    6
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    13,
    5, --public_view_rs --Dockford
    4, --AllCourtStatus
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    14,
    5, --public_view_rs --Dockford
    5, --SummaryByName
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    15,
    5, --public_view_rs --Dockford
    3, --DailyList
    20,
    3
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    16,
    6, --court_room_rs --Dockford
    2, --CourtList
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    17,
    6, --court_room_rs --Dockford
    1, --CourtDetail
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    18,
    7, --jury_room_rs --Dockford
    6, --JuryCurrentStatus
    20,
    1
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    19,
    8, --all_list_rs --Dockford
    1, --JuryCurrentStatus
    20,
    1
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    20,
    8, --all_list_rs --Dockford
    2, --JuryCurrentStatus
    20,
    2
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    21,
    8, --all_list_rs --Dockford
    3, --JuryCurrentStatus
    20,
    3
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    22,
    8, --all_list_rs --Dockford
    4, --JuryCurrentStatus
    20,
    4
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    23,
    8, --all_list_rs --Dockford
    5, --JuryCurrentStatus
    20,
    5
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    24,
    8, --all_list_rs --Dockford
    6, --JuryCurrentStatus
    20,
    6
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    25,
    9, --public_view_rs --I
    4, --AllCourtStatus
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    26,
    9, --public_view_rs --I
    5, --SummaryByName
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    27,
    9, --public_view_rs --I
    3, --DailyList
    20,
    3
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    28,
    10, --court_room_rs --I
    2, --CourtList
    20,
    1
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    29,
    10, --court_room_rs --I
    1, --CourtDetail
    20,
    2
);

INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    30,
    11, --jury_room_rs --I
    6, --JuryCurrentStatus
    20,
    1
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    31,
    12, --all_list_rs --Dockford
    1, --JuryCurrentStatus
    20,
    1
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    32,
    12, --all_list_rs --Dockford
    2, --JuryCurrentStatus
    20,
    2
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    33,
    12, --all_list_rs --Dockford
    3, --JuryCurrentStatus
    20,
    3
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    34,
    12, --all_list_rs --Dockford
    4, --JuryCurrentStatus
    20,
    4
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    35,
    12, --all_list_rs --Dockford
    5, --JuryCurrentStatus
    20,
    5
);
INSERT INTO XHB_ROTATION_SET_DD
(
    ROTATION_SET_DD_ID,
    ROTATION_SET_ID,
    DISPLAY_DOCUMENT_ID,
    PAGE_DELAY,
    ORDERING
)
VALUES
(
    36,
    12, --all_list_rs --Dockford
    6, --JuryCurrentStatus
    20,
    6
);
--_____________________________
--Set up the Display Locations.
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  1,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  2,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  3,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  4,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  5,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  6,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  7,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  8,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  9,
        'court_room_9',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  10,
        'court_room_10',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  11,
        'court_room_11',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  12,
        'court_room_12',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  13,
        'court_room_13',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  14,
        'court_room_14',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  15,
        'court_room_15',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  16,
        'court_room_16',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  17,
        'court_room_17',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  18,
        'court_room_18',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  19,
        'court_room_19',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  20,
        'court_room_20',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  21,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  22,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  23,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  24,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  25,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  26,
        'police_room_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  27,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  28,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  29,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  30,
        'j_l_a_b',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  31,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  32,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  33,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  34,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  35,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  36,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  37,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  38,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  39,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  40,
        'court_room_9',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  41,
        'court_room_10',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  42,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  43,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  44,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  45,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  46,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  47,
        'police_room_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  48,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  49,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  50,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  51,
        'j_l_a_b',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  52,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  53,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  54,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  55,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  56,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  57,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  58,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  59,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  60,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  61,
        'court_room_9',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  62,
        'court_room_10',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  63,
        'court_room_11',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  64,
        'court_room_12',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  65,
        'court_room_13',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  66,
        'court_room_14',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  67,
        'court_room_15',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  68,
        'court_room_16',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  69,
        'court_room_17',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  70,
        'court_room_18',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  71,
        'court_room_19',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  72,
        'court_room_20',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  73,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  74,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  75,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  76,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  77,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  78,
        'police_room_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  79,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  80,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  81,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  82,
        'j_l_a_b',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  83,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

--______________________
--Set up the displays...
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    1,
    1,
    1,
    2,
    'display_outside_court_room_1',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    2,
    1,
    2,
    2,
    'display_outside_court_room_2',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    3,
    1,
    3,
    2,
    'display_outside_court_room_3',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    4,
    1,
    4,
    2,
    'display_outside_court_room_4',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    5,
    1,
    5,
    2,
    'display_outside_court_room_5',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    6,
    1,
    6,
    2,
    'display_outside_court_room_6',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    7,
    1,
    7,
    2,
    'display_outside_court_room_7',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    8,
    1,
    8,
    2,
    'display_outside_court_room_8',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    9,
    1,
    9,
    2,
    'display_outside_court_room_9',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    10,
    1,
    10,
    2,
    'display_outside_court_room_10',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    11,
    1,
    11,
    2,
    'display_outside_court_room_11',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    12,
    1,
    12,
    2,
    'display_outside_court_room_12',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    13,
    1,
    13,
    2,
    'display_outside_court_room_13',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    14,
    1,
    14,
    2,
    'display_outside_court_room_14',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    15,
    1,
    15,
    2,
    'display_outside_court_room_15',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    16,
    1,
    16,
    2,
    'display_outside_court_room_16',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    17,
    1,
    17,
    2,
    'display_outside_court_room_17',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    18,
    1,
    18,
    2,
    'display_outside_court_room_18',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    19,
    1,
    19,
    2,
    'display_outside_court_room_19',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    20,
    1,
    20,
    2,
    'display_outside_court_room_20',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    21,
    2,
    21,
    1,
    'e_v_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    22,
    2,
    22,
    1,
    'reception_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    23,
    1,
    23,
    1,
    'public_restaurant_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    24,
    1,
    23,
    1,
    'public_restaurant_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    25,
    1,
    24,
    3,
    'jury_lounge_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    26,
    1,
    24,
    3,
    'jury_lounge_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    27,
    1,
    25,
    1,
    'witness_service_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    28,
    1,
    26,
    1,
    'police_room_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    29,
    1,
    27,
    1,
    'ps_secretary_office_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    30,
    2,
    28,
    1,
    'n_w_c_w_a_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    31,
    1,
    29,
    1,
    'b_a_s_r_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    32,
    1,
    30,
    3,
    'j_l_a_b_18in_display_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    33,
    1,
    30,
    3,
    'j_l_a_b_18in_display_2',
    'enGB',
    'Y'
);


INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    34,
    3,
    31,
    4,
    'v_i_p',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    41,
    1,
    32,
    6,
    'display_outside_court_room_1',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    42,
    1,
    33,
    6,
    'display_outside_court_room_2',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    43,
    1,
    34,
    6,
    'display_outside_court_room_3',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    44,
    1,
    35,
    6,
    'display_outside_court_room_4',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    45,
    1,
    36,
    6,
    'display_outside_court_room_5',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    46,
    1,
    37,
    6,
    'display_outside_court_room_6',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    47,
    1,
    38,
    6,
    'display_outside_court_room_7',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    48,
    1,
    39,
    6,
    'display_outside_court_room_8',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    49,
    1,
    40,
    6,
    'display_outside_court_room_9',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    50,
    1,
    41,
    6,
    'display_outside_court_room_10',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    51,
    2,
    42,
    5,
    'e_v_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    52,
    2,
    43,
    5,
    'reception_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    53,
    1,
    44,
    5,
    'public_restaurant_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    54,
    1,
    44,
    5,
    'public_restaurant_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    55,
    1,
    45,
    7,
    'jury_lounge_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    56,
    1,
    45,
    7,
    'jury_lounge_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    57,
    1,
    46,
    5,
    'witness_service_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    58,
    1,
    47,
    5,
    'police_room_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    59,
    1,
    48,
    5,
    'ps_secretary_office_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    60,
    2,
    49,
    5,
    'n_w_c_w_a_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    61,
    1,
    50,
    5,
    'b_a_s_r_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    62,
    1,
    51,
    7,
    'j_l_a_b_18in_display_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    63,
    1,
    51,
    7,
    'j_l_a_b_18in_display_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    64,
    3,
    52,
    8,
    'v_i_p',
    'enGB',
    'Y'
);


INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    71,
    1,
    53,
    10,
    'display_outside_court_room_1',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    72,
    1,
    54,
    10,
    'display_outside_court_room_2',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    73,
    1,
    55,
    10,
    'display_outside_court_room_3',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    74,
    1,
    56,
    10,
    'display_outside_court_room_4',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    75,
    1,
    57,
    10,
    'display_outside_court_room_5',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    76,
    1,
    58,
    10,
    'display_outside_court_room_6',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    77,
    1,
    59,
    10,
    'display_outside_court_room_7',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    78,
    1,
    60,
    10,
    'display_outside_court_room_8',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    79,
    1,
    61,
    10,
    'display_outside_court_room_9',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    80,
    1,
    62,
    10,
    'display_outside_court_room_10',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    81,
    1,
    63,
    10,
    'display_outside_court_room_11',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    82,
    1,
    64,
    10,
    'display_outside_court_room_12',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    83,
    1,
    65,
    10,
    'display_outside_court_room_13',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    84,
    1,
    66,
    10,
    'display_outside_court_room_14',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    85,
    1,
    67,
    10,
    'display_outside_court_room_15',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    86,
    1,
    68,
    10,
    'display_outside_court_room_16',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    87,
    1,
    69,
    10,
    'display_outside_court_room_17',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    88,
    1,
    70,
    10,
    'display_outside_court_room_18',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    89,
    1,
    71,
    10,
    'display_outside_court_room_19',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    90,
    1,
    72,
    10,
    'display_outside_court_room_20',
    'enGB',
    'N'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    91,
    2,
    73,
    9,
    'e_v_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    92,
    2,
    74,
    9,
    'reception_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    93,
    1,
    75,
    9,
    'public_restaurant_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    94,
    1,
    75,
    9,
    'public_restaurant_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    95,
    1,
    76,
    11,
    'jury_lounge_18in_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    96,
    1,
    76,
    11,
    'jury_lounge_18in_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    97,
    1,
    77,
    9,
    'witness_service_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    98,
    1,
    78,
    9,
    'police_room_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    99,
    1,
    79,
    9,
    'ps_secretary_office_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    100,
    2,
    80,
    9,
    'n_w_c_w_a_plasma_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    101,
    1,
    81,
    9,
    'b_a_s_r_18in_display',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    102,
    1,
    82,
    11,
    'j_l_a_b_18in_display_1',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    103,
    1,
    82,
    11,
    'j_l_a_b_18in_display_2',
    'enGB',
    'Y'
);

INSERT INTO XHB_DISPLAY
(
    DISPLAY_ID,
    DISPLAY_TYPE_ID,
    DISPLAY_LOCATION_ID,
    ROTATION_SET_ID,
    DESCRIPTION_CODE,
    LOCALE,
    SHOW_UNASSIGNED_YN
)
VALUES
(
    104,
    3,
    83,
    12,
    'v_i_p',
    'enGB',
    'Y'
);
--________________________________
--
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  1,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  2,
        2
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  3,
        3
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  4,
        4
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  5,
        5
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  6,
        6
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  7,
        7
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  8,
        8
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  9,
        9
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  10,
        10
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  11,
        11
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  12,
        12
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  13,
        13
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  14,
        14
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  15,
        15
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  16,
        16
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  17,
        17
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  18,
        18
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  19,
        19
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  20,
        20
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        2
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        3
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        4
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        5
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        6
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        7
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        8
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        9
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        10
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        11
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        12
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        13
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        14
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        15
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        16
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        17
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        18
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        19
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  21,
        20
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  22,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  23,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  24,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  25,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  26,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  27,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  28,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  29,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  30,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  31,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  32,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  33,
        1
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  41,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  42,
        22
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  43,
        23
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  44,
        24
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  45,
        25
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  46,
        26
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  47,
        27
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  48,
        28
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  49,
        29
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  50,
        30
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        22
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        23
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        24
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        25
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        26
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        27
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        28
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        29
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  51,
        30
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  52,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  53,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  54,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  55,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  56,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  57,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  58,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  59,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  60,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  61,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  62,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  63,
        21
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  71,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  72,
        32
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  73,
        33
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  74,
        34
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  75,
        35
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  76,
        36
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  77,
        37
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  78,
        38
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  79,
        39
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  80,
        40
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  81,
        41
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  82,
        42
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  83,
        43
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  84,
        44
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  85,
        45
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  86,
        46
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  87,
        47
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  88,
        48
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  89,
        49
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  90,
        50
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        32
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        33
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        34
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        35
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        36
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        37
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        38
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        39
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        40
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        41
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        42
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        43
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        44
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        45
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        46
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        47
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        48
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        49
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  91,
        50
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  92,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  93,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  94,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  95,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  96,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  97,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  98,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  99,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  100,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  101,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  102,
        31
FROM DUAL;

INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
)
SELECT  103,
        31
FROM DUAL;

-- Data required for assigning all court rooms to view information pages
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,1);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,2);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,3);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,4);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,5);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,6);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,7);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,8);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,9);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,10);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,11);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,12);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,13);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,14);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,15);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,16);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,17);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,18);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,19);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (34,20);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,21);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,22);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,23);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,24);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,25);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,26);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,27);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,28);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,29);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (64,30);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,31);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,32);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,33);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,34);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,35);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,36);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,37);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,38);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,39);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,40);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,41);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,42);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,43);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,44);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,45);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,46);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,47);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,48);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,49);
INSERT INTO XHB_DISPLAY_COURT_ROOM
(
     DISPLAY_ID,
     COURT_ROOM_ID
) VALUES (104,50);
COMMIT;