DELETE FROM XHB_DISPLAY_COURT_ROOM;

DELETE FROM XHB_DISPLAY;

DELETE FROM XHB_DISPLAY_LOCATION;

DELETE FROM XHB_ROTATION_SET_DD
WHERE ROTATION_SET_ID IN
    (SELECT rotation_set_id FROM XHB_ROTATION_SETS WHERE DEFAULT_YN='Y');

DELETE FROM XHB_ROTATION_SETS WHERE DEFAULT_YN='Y';

COMMIT;
