#!/bin/ksh

# This script will zip,backup and ftp LAA data to Staging Server
SCRIPT_HOME=/opt/moj/home/wmbroker/bin/cron/LAA
. $SCRIPT_HOME/../setEnv.sh

ROOT_FOLDER=/var/mqsi
# Folder where files are generated by App
SOURCE_FOLDER=$ROOT_FOLDER/LAA/outbound

# Folder where files are zipped and backed up. Though this is not required, I have seen incidents where LAA have requested old files in the past
ARCHIVAL_FOLDER=$ROOT_FOLDER/LAA/outbound_archive

# Folder where files will be kept for confirmation and deletion via getConfirmationFromLAA.sh script
STAGING_FOLDER=$ROOT_FOLDER/LAA/staging
STAGING2_FOLDER=$ROOT_FOLDER/LAA/staging2
STAGING3_FOLDER=$ROOT_FOLDER/LAA/staging3
LOG_FILE_FOLDER=$SCRIPT_HOME
STAGING_SERVER=x.y.198.9
STAGING_SERVER_USERID=XHIBIT2LAA
CURRENT_TIMESTAMP=`date +"%d%m%y%H%M%S"`
CURRENT_DATE=`date +"%d%m%y"`
LOG_FILE=$LOG_FILE_FOLDER/sendDataToLAA.log

echo "" >> $LOG_FILE
echo "Starting zipAndSendToLAA.sh script at $CURRENT_TIMESTAMP" >> $LOG_FILE
#Create folders
mkdir -p $STAGING_FOLDER
mkdir -p $SOURCE_FOLDER
mkdir -p $LOG_FILE_FOLDER
mkdir -p $ARCHIVAL_FOLDER
mkdir -p $ARCHIVAL_FOLDER/$CURRENT_DATE
mkdir -p $STAGING2_FOLDER
mkdir -p $STAGING3_FOLDER

# Delete old files
echo "Deleting old files.." >> $LOG_FILE
find $ARCHIVAL_FOLDER/ -name "XHIBIT_*.zip" -type f -mtime +100 |xargs rm
echo "Deleted old files.." >> $LOG_FILE

#Move all files present in staging2 folder to staging2 folder
mv $STAGING2_FOLDER/* $STAGING3_FOLDER/

#Zip the source files
echo "Zipping files.." >> $LOG_FILE
cd $STAGING3_FOLDER
zip -jr $STAGING3_FOLDER/XHIBIT_$CURRENT_TIMESTAMP.zip *

ERROR_CODE=$?

if [ "$ERROR_CODE" != 0 ]; then
	echo "ERROR: Unable to zip files. error code=$ERROR_CODE" >> $LOG_FILE
	exit 1
fi

echo "Zipped files.." >> $LOG_FILE

echo "Copying combined zip file for archiving" >> $LOG_FILE
#Keep a copy in archive
cp $STAGING3_FOLDER/XHIBIT_$CURRENT_TIMESTAMP.zip $ARCHIVAL_FOLDER/$CURRENT_DATE/
echo "Copied combined zip file for archiving" >> $LOG_FILE

echo "sftping file.." >> $LOG_FILE
sftp $STAGING_SERVER_USERID@$STAGING_SERVER <<EOF
lcd $STAGING3_FOLDER
put XHIBIT_$CURRENT_TIMESTAMP.zip
EOF
ERROR_CODE=$?

if [ "$ERROR_CODE" != 0 ]; then
	echo "ERROR: Unable to sftp file. error code=$ERROR_CODE" >> $LOG_FILE
	touch /opt/moj/home/wmbroker/bin/cron/LAA/workspace/sftpfailed.txt
	exit 1
fi

echo "sftp complete.." >> $LOG_FILE

#Once ftp'ed, remove the source files
echo "Removing processed files.." >> $LOG_FILE
rm $STAGING3_FOLDER/*

echo "Removed processed files.." >> $LOG_FILE
CURRENT_TIMESTAMP=`date +"%d%m%y%H%M%S"`
echo "Finishing zipAndSendToLAA.sh script at $CURRENT_TIMESTAMP" >> $LOG_FILE
echo "" >> $LOG_FILE
exit 0

