<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:msg="http://schemas.cjse.gov.uk/messages/messaging/2006-05" xmlns="http://schemas.cjse.gov.uk/messages/format/2006-05" targetNamespace="http://schemas.cjse.gov.uk/messages/format/2006-05" elementFormDefault="qualified" attributeFormDefault="unqualified" version="0.3">
	<xs:import namespace="http://schemas.cjse.gov.uk/messages/messaging/2006-05" schemaLocation="MessagingTypes-v1-0.xsd"/>
	<xs:element name="MessageFormat" type="MessageFormatStructure"/>
	<xs:complexType name="MessageFormatStructure">
		<xs:annotation>
			<xs:documentation>
				This structure carries information about a particular message's content and format.
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="MessageType" type="msg:MessageTypeStructure"/>
			<xs:element name="MessageSchema" type="msg:MessageSchemaStructure"/>
			<xs:any namespace="##other" processContents="lax" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="SchemaVersion" type="xs:string" use="required" fixed="1.0" />
		<xs:anyAttribute namespace="##other" processContents="lax"/>
	</xs:complexType>
</xs:schema>
