CREATE OR REPLACE PROCEDURE load_xhb_ref_hearing_types (p_court_id IN XHB_REF_HEARING_TYPE.COURT_ID%TYPE) AS 
/**
  * DESCRIPTION :
  *   Procedure                      Purpose
  *   ==========================     =======
  *   load_xhb_ref_hearing_types  	CTX-3332
  *  Assumptions                     This package will need an execution call too.
  *  Functionality                   Load hearing types
***/
BEGIN
    DBMS_OUTPUT.PUT_LINE('Executing load_xhb_ref_hearing_types for court ID: '||p_court_id||'.  Start Time: '||to_char(sysdate,'DD-MM-YYYY HH24:MI:SS')||'.');
    

INSERT INTO XHB_REF_HEARING_TYPE (COURT_ID, CATEGORY, HEARING_TYPE_CODE, HEARING_TYPE_DESC, SEQ_NO, LIST_SEQUENCE)
SELECT subqry.* FROM (SELECT p_court_id COURT_ID, 'X' CATEGORY, keyed_data.* FROM (
SELECT 'ABG' HEARING_TYPE_CODE, 'For Appeal under the Betting, Gaming and Lotteries Act 1963' HEARING_TYPE_DESC, 70 SEQ_NO, 510 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ACF' HEARING_TYPE_CODE, 'For Appeal in respect of Firearms Certificate' HEARING_TYPE_DESC, 90 SEQ_NO, 530 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ACN' HEARING_TYPE_CODE, 'For Appeal against Conviction' HEARING_TYPE_DESC, 30 SEQ_NO, 450 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ACO' HEARING_TYPE_CODE, 'For Appeal against Compensation Order' HEARING_TYPE_DESC, 60 SEQ_NO, 500 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ACS' HEARING_TYPE_CODE, 'For Appeal against Conviction and Sentence' HEARING_TYPE_DESC, 40 SEQ_NO, 460 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ACY' HEARING_TYPE_CODE, 'For Appeal under the Children and Young Persons Act 1969' HEARING_TYPE_DESC, 80 SEQ_NO, 520 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ADJ' HEARING_TYPE_CODE, 'For Appeal against District Judge''s Order' HEARING_TYPE_DESC, 30 SEQ_NO, 600 LIST_SEQUENCE FROM DUAL UNION
SELECT 'AEH' HEARING_TYPE_CODE, 'Admissibility of Evidence - Half day' HEARING_TYPE_DESC, 80 SEQ_NO, 1050 LIST_SEQUENCE FROM DUAL UNION
SELECT 'AEW' HEARING_TYPE_CODE, 'Admissibility of Evidence - Whole Day' HEARING_TYPE_DESC, 90 SEQ_NO, 1060 LIST_SEQUENCE FROM DUAL UNION
SELECT 'AGA' HEARING_TYPE_CODE, 'For Appeal under the Gaming Act 1968' HEARING_TYPE_DESC, 100 SEQ_NO, 540 LIST_SEQUENCE FROM DUAL UNION
SELECT 'AHA' HEARING_TYPE_CODE, 'For Appeal under the Housing Act 1957' HEARING_TYPE_DESC, 120 SEQ_NO, 560 LIST_SEQUENCE FROM DUAL UNION
SELECT 'AHC' HEARING_TYPE_CODE, 'For Appeal in respect of Hackney Carriage Licence' HEARING_TYPE_DESC, 110 SEQ_NO, 550 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ALA' HEARING_TYPE_CODE, 'For Appeal under the Lotteries and Amusements Act 1976' HEARING_TYPE_DESC, 150 SEQ_NO, 590 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ALD' HEARING_TYPE_CODE, 'For Appeal under the Land Drainage Act 1976' HEARING_TYPE_DESC, 130 SEQ_NO, 570 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ALJ' HEARING_TYPE_CODE, 'For Appeal against Licensing Justices Decision' HEARING_TYPE_DESC, 140 SEQ_NO, 580 LIST_SEQUENCE FROM DUAL UNION
SELECT 'APH' HEARING_TYPE_CODE, 'Appeal (Part Heard)' HEARING_TYPE_DESC, 20 SEQ_NO, 490 LIST_SEQUENCE FROM DUAL UNION
SELECT 'APL' HEARING_TYPE_CODE, 'For Appeal' HEARING_TYPE_DESC, 10 SEQ_NO, 480 LIST_SEQUENCE FROM DUAL UNION
SELECT 'APN' HEARING_TYPE_CODE, 'For Application' HEARING_TYPE_DESC, 10 SEQ_NO, 1300 LIST_SEQUENCE FROM DUAL UNION
SELECT 'ASE' HEARING_TYPE_CODE, 'For Appeal against Sentence' HEARING_TYPE_DESC, 50 SEQ_NO, 470 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BAC' HEARING_TYPE_CODE, 'Breach of Attendance Centre Order' HEARING_TYPE_DESC, 10 SEQ_NO, 1610 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BBO' HEARING_TYPE_CODE, 'Breach of Bind Over' HEARING_TYPE_DESC, 20 SEQ_NO, 1620 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BCD' HEARING_TYPE_CODE, 'Breach of Conditional Discharge' HEARING_TYPE_DESC, 40 SEQ_NO, 1640 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BCF' HEARING_TYPE_CODE, 'Breach of Requirements of Curfew Order' HEARING_TYPE_DESC, 45 SEQ_NO, 1650 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BCP' HEARING_TYPE_CODE, 'Breach of Requirements of Community Service Order and Probation Order' HEARING_TYPE_DESC, 80 SEQ_NO, 1690 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BCS' HEARING_TYPE_CODE, 'Breach of Requirements of Community Service Order' HEARING_TYPE_DESC, 30 SEQ_NO, 1630 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BEX' HEARING_TYPE_CODE, 'Breach of Exclusion Order' HEARING_TYPE_DESC, 50 SEQ_NO, 1660 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BFA' HEARING_TYPE_CODE, 'For Application to Break Fixture' HEARING_TYPE_DESC, 60 SEQ_NO, 1320 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BLA' HEARING_TYPE_CODE, 'For Application for Bail' HEARING_TYPE_DESC, 30 SEQ_NO, 1210 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BOO' HEARING_TYPE_CODE, 'Breach of Order' HEARING_TYPE_DESC, 60 SEQ_NO, 1600 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BPS' HEARING_TYPE_CODE, 'Breach of Partly Suspended Sentence' HEARING_TYPE_DESC, 90 SEQ_NO, 1700 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BRG' HEARING_TYPE_CODE, 'For Application to Rescind Grant of Bail' HEARING_TYPE_DESC, 40 SEQ_NO, 1220 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BRP' HEARING_TYPE_CODE, 'Breach of Requirements of Probation Order' HEARING_TYPE_DESC, 70 SEQ_NO, 1680 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BSS' HEARING_TYPE_CODE, 'Breach of Suspended Sentence' HEARING_TYPE_DESC, 100 SEQ_NO, 1710 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BVA' HEARING_TYPE_CODE, 'For Application to Vary Bail Conditions' HEARING_TYPE_DESC, 50 SEQ_NO, 1230 LIST_SEQUENCE FROM DUAL UNION
SELECT 'BWR' HEARING_TYPE_CODE, 'Review of Bench Warrant' HEARING_TYPE_DESC, 850 SEQ_NO, 1950 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CBR' HEARING_TYPE_CODE, 'Committal for Breaches' HEARING_TYPE_DESC, 175 SEQ_NO, 430 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CCT' HEARING_TYPE_CODE, 'Contempt of Court Proceedings' HEARING_TYPE_DESC, 200 SEQ_NO, 1800 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CMA' HEARING_TYPE_CODE, 'For Application to Commit' HEARING_TYPE_DESC, 170 SEQ_NO, 1470 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CON' HEARING_TYPE_CODE, 'Continued' HEARING_TYPE_DESC, 300 SEQ_NO, 760 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CPT' HEARING_TYPE_CODE, 'For Contempt' HEARING_TYPE_DESC, 210 SEQ_NO, 1810 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CSE' HEARING_TYPE_CODE, 'Committal for Sentence' HEARING_TYPE_DESC, 150 SEQ_NO, 410 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CSP' HEARING_TYPE_CODE, 'Committal for Sentence (Part Heard)' HEARING_TYPE_DESC, 170 SEQ_NO, 420 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CSS' HEARING_TYPE_CODE, 'Committals for Sentence' HEARING_TYPE_DESC, 160 SEQ_NO, 400 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CTA' HEARING_TYPE_CODE, 'For Application to Extend Custody Time Limit' HEARING_TYPE_DESC, 340 SEQ_NO, 1250 LIST_SEQUENCE FROM DUAL UNION
SELECT 'CTL' HEARING_TYPE_CODE, 'Custody Time Limit application' HEARING_TYPE_DESC, 120 SEQ_NO, 1260 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DCA' HEARING_TYPE_CODE, 'For Application for Dismissal of Charges' HEARING_TYPE_DESC, 860 SEQ_NO, 320 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DIR' HEARING_TYPE_CODE, 'For Directions' HEARING_TYPE_DESC, 300 SEQ_NO, 810 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DPR' HEARING_TYPE_CODE, 'For Deferred Sentence (Prosecution Released)' HEARING_TYPE_DESC, 260 SEQ_NO, 960 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DRA' HEARING_TYPE_CODE, 'For Application under the Drug Trafficking Act 1994' HEARING_TYPE_DESC, 85 SEQ_NO, 1375 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DRR' HEARING_TYPE_CODE, 'For Deferred Sentence (Respondent Released)' HEARING_TYPE_DESC, 410 SEQ_NO, 970 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DRS' HEARING_TYPE_CODE, 'For Application under the Drug Trafficking Act 1994, and Sentence' HEARING_TYPE_DESC, 95 SEQ_NO, 1385 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DSE' HEARING_TYPE_CODE, 'For Deferred Sentence' HEARING_TYPE_DESC, 250 SEQ_NO, 950 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DTA' HEARING_TYPE_CODE, 'For Application under the Drug Trafficking Offences Act 1986' HEARING_TYPE_DESC, 80 SEQ_NO, 1370 LIST_SEQUENCE FROM DUAL UNION
SELECT 'DTS' HEARING_TYPE_CODE, 'For Application under Drug Trafficking Offences Act 1986, and Sentence' HEARING_TYPE_DESC, 90 SEQ_NO, 1380 LIST_SEQUENCE FROM DUAL UNION
SELECT 'EBW' HEARING_TYPE_CODE, 'For Execution of Bench Warrant' HEARING_TYPE_DESC, 350 SEQ_NO, 1240 LIST_SEQUENCE FROM DUAL UNION
SELECT 'EGP' HEARING_TYPE_CODE, 'For Early Guilty Plea' HEARING_TYPE_DESC, 35 SEQ_NO, 5 LIST_SEQUENCE FROM DUAL UNION
SELECT 'FCM' HEARING_TYPE_CODE, 'Further Case Management' HEARING_TYPE_DESC, 860 SEQ_NO, 1970 LIST_SEQUENCE FROM DUAL UNION
SELECT 'FHA' HEARING_TYPE_CODE, 'For Application to Fix Hearing Date' HEARING_TYPE_DESC, 130 SEQ_NO, 1340 LIST_SEQUENCE FROM DUAL UNION
SELECT 'GRH' HEARING_TYPE_CODE, 'For Ground Rules Hearing' HEARING_TYPE_DESC, 1030 SEQ_NO, 1980 LIST_SEQUENCE FROM DUAL UNION
SELECT 'HRG' HEARING_TYPE_CODE, 'For Hearing' HEARING_TYPE_DESC, 400 SEQ_NO, 700 LIST_SEQUENCE FROM DUAL UNION
SELECT 'INJ' HEARING_TYPE_CODE, 'For Application for Injunction' HEARING_TYPE_DESC, 110 SEQ_NO, 1540 LIST_SEQUENCE FROM DUAL UNION
SELECT 'JGT' HEARING_TYPE_CODE, 'For Judgment' HEARING_TYPE_DESC, 410 SEQ_NO, 1000 LIST_SEQUENCE FROM DUAL UNION
SELECT 'LAA' HEARING_TYPE_CODE, 'For Application to Add to List' HEARING_TYPE_DESC, 140 SEQ_NO, 1350 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MAA' HEARING_TYPE_CODE, 'For Mention (Appellant to Attend)' HEARING_TYPE_DESC, 570 SEQ_NO, 1090 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MAP' HEARING_TYPE_CODE, 'For Mention (All Parties to Attend)' HEARING_TYPE_DESC, 770 SEQ_NO, 1050 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MBO' HEARING_TYPE_CODE, 'For Motion By Order' HEARING_TYPE_DESC, 550 SEQ_NO, 650 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MDA' HEARING_TYPE_CODE, 'For Mention (Defendant to Attend)' HEARING_TYPE_DESC, 520 SEQ_NO, 1060 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MEF' HEARING_TYPE_CODE, 'For Mention and to Fix' HEARING_TYPE_DESC, 510 SEQ_NO, 1040 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MEN' HEARING_TYPE_CODE, 'For Mention' HEARING_TYPE_DESC, 450 SEQ_NO, 1030 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MNW' HEARING_TYPE_CODE, 'For Mention (No Witnesses Required)' HEARING_TYPE_DESC, 790 SEQ_NO, 1070 LIST_SEQUENCE FROM DUAL UNION
SELECT 'MOA' HEARING_TYPE_CODE, 'For Mention (Officer to Attend)' HEARING_TYPE_DESC, 530 SEQ_NO, 1080 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PAD' HEARING_TYPE_CODE, 'For Plea and Directions' HEARING_TYPE_DESC, 30 SEQ_NO, 220 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PAF' HEARING_TYPE_CODE, 'For Plea and to Fix' HEARING_TYPE_DESC, 40 SEQ_NO, 230 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PCA' HEARING_TYPE_CODE, 'For Application under the Police and Criminal Evidence Act' HEARING_TYPE_DESC, 100 SEQ_NO, 1390 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PCM' HEARING_TYPE_CODE, 'Plea and Case Management' HEARING_TYPE_DESC, 35 SEQ_NO, 225 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PHD' HEARING_TYPE_CODE, 'Part Heard' HEARING_TYPE_DESC, 500 SEQ_NO, 750 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PLE' HEARING_TYPE_CODE, 'For Plea' HEARING_TYPE_DESC, 10 SEQ_NO, 200 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PLY' HEARING_TYPE_CODE, 'For Preliminary Hearing' HEARING_TYPE_DESC, 600 SEQ_NO, 800 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PPH' HEARING_TYPE_CODE, 'Plea (Part Heard)' HEARING_TYPE_DESC, 20 SEQ_NO, 210 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PPT' HEARING_TYPE_CODE, 'For Plea/Pre-Trial Review' HEARING_TYPE_DESC, 70 SEQ_NO, 260 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PRA' HEARING_TYPE_CODE, 'For Application under the Proceeds of Crime Act 2002' HEARING_TYPE_DESC, 105 SEQ_NO, 1490 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PRY' HEARING_TYPE_CODE, 'For Preparatory Hearing' HEARING_TYPE_DESC, 850 SEQ_NO, 310 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PTN' HEARING_TYPE_CODE, 'For Plea to be Taken' HEARING_TYPE_DESC, 50 SEQ_NO, 240 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PTP' HEARING_TYPE_CODE, 'Plea and Trial Preparation' HEARING_TYPE_DESC, 33 SEQ_NO, 223 LIST_SEQUENCE FROM DUAL UNION
SELECT 'PTR' HEARING_TYPE_CODE, 'For Pre-Trial Review' HEARING_TYPE_DESC, 610 SEQ_NO, 300 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RBA' HEARING_TYPE_CODE, 'For Application to Revoke Community Service Order and Probation Order' HEARING_TYPE_DESC, 320 SEQ_NO, 1480 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RCA' HEARING_TYPE_CODE, 'For Application to Revoke Community Service Order' HEARING_TYPE_DESC, 290 SEQ_NO, 1420 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RCF' HEARING_TYPE_CODE, 'For Application to Revoke Curfew Order' HEARING_TYPE_DESC, 300 SEQ_NO, 1430 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RDA' HEARING_TYPE_CODE, 'For Application to Remove Driving Disqualification' HEARING_TYPE_DESC, 270 SEQ_NO, 1360 LIST_SEQUENCE FROM DUAL UNION
SELECT 'REP' HEARING_TYPE_CODE, 'For Plea and Reparation' HEARING_TYPE_DESC, 60 SEQ_NO, 250 LIST_SEQUENCE FROM DUAL UNION
SELECT 'REV' HEARING_TYPE_CODE, 'For Review' HEARING_TYPE_DESC, 550 SEQ_NO, 1020 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RIN' HEARING_TYPE_CODE, 'For Return Injunction' HEARING_TYPE_DESC, 630 SEQ_NO, 1550 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RJT' HEARING_TYPE_CODE, 'For Reserved Judgment' HEARING_TYPE_DESC, 620 SEQ_NO, 1010 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RLA' HEARING_TYPE_CODE, 'For Application to Remove from List' HEARING_TYPE_DESC, 70 SEQ_NO, 1330 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RPA' HEARING_TYPE_CODE, 'For Application to Revoke Probation Order' HEARING_TYPE_DESC, 310 SEQ_NO, 1450 LIST_SEQUENCE FROM DUAL UNION
SELECT 'RVA' HEARING_TYPE_CODE, 'For Application for Review' HEARING_TYPE_DESC, 180 SEQ_NO, 1430 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SAC' HEARING_TYPE_CODE, 'For Sentence (at another Court)' HEARING_TYPE_DESC, 650 SEQ_NO, 945 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SCE' HEARING_TYPE_CODE, 'To Show Cause' HEARING_TYPE_DESC, 800 SEQ_NO, 1900 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SCJ' HEARING_TYPE_CODE, 'For Juror to Show Cause' HEARING_TYPE_DESC, 810 SEQ_NO, 1910 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SCS' HEARING_TYPE_CODE, 'For Solicitor to Show Cause' HEARING_TYPE_DESC, 820 SEQ_NO, 1920 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SCW' HEARING_TYPE_CODE, 'For Witness to Show Cause' HEARING_TYPE_DESC, 840 SEQ_NO, 1940 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SCY' HEARING_TYPE_CODE, 'For Surety to Show Cause' HEARING_TYPE_DESC, 830 SEQ_NO, 1930 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SDA' HEARING_TYPE_CODE, 'For Application to Suspend Driving Disqualification' HEARING_TYPE_DESC, 280 SEQ_NO, 1410 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SEN' HEARING_TYPE_CODE, 'For Sentence' HEARING_TYPE_DESC, 600 SEQ_NO, 900 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SOA' HEARING_TYPE_CODE, 'For Sentence (Officer to Attend)' HEARING_TYPE_DESC, 620 SEQ_NO, 920 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SPA' HEARING_TYPE_CODE, 'For Sentence (Prosecution to Attend)' HEARING_TYPE_DESC, 610 SEQ_NO, 910 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SPO' HEARING_TYPE_CODE, 'For Sentence (Prosecution and Officer to Attend)' HEARING_TYPE_DESC, 630 SEQ_NO, 930 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SPR' HEARING_TYPE_CODE, 'For Sentence (Prosecution Released)' HEARING_TYPE_DESC, 640 SEQ_NO, 940 LIST_SEQUENCE FROM DUAL UNION
SELECT 'STE' HEARING_TYPE_CODE, 'For Section 28 Hearing (Pre-Recording of Cross-Examination)' HEARING_TYPE_DESC, 1040 SEQ_NO, 1990 LIST_SEQUENCE FROM DUAL UNION
SELECT 'SUB' HEARING_TYPE_CODE, 'For Surrender to Bail' HEARING_TYPE_DESC, 650 SEQ_NO, 1200 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TBK' HEARING_TYPE_CODE, 'For Trial (Backer)' HEARING_TYPE_DESC, 200 SEQ_NO, 80 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TFL' HEARING_TYPE_CODE, 'For Trial (Floater)' HEARING_TYPE_DESC, 180 SEQ_NO, 60 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TFW' HEARING_TYPE_CODE, 'For Trial (First Warning)' HEARING_TYPE_DESC, 170 SEQ_NO, 50 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TIS' HEARING_TYPE_CODE, 'For Trial of Issue' HEARING_TYPE_DESC, 130 SEQ_NO, 100 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TNW' HEARING_TYPE_CODE, 'For Trial (No Witnesses)' HEARING_TYPE_DESC, 120 SEQ_NO, 90 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TPH' HEARING_TYPE_CODE, 'Trial (Part Heard)' HEARING_TYPE_DESC, 110 SEQ_NO, 110 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TPI' HEARING_TYPE_CODE, 'For Trial of Preliminary Issue' HEARING_TYPE_DESC, 820 SEQ_NO, 120 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TPR' HEARING_TYPE_CODE, 'For Trial (Priority)' HEARING_TYPE_DESC, 150 SEQ_NO, 20 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TPW' HEARING_TYPE_CODE, 'For Trial (Previously Warned)' HEARING_TYPE_DESC, 160 SEQ_NO, 30 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TRA' HEARING_TYPE_CODE, 'For Application to Terminate Restriction Order' HEARING_TYPE_DESC, 280 SEQ_NO, 1400 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TRE' HEARING_TYPE_CODE, 'For Trial (Reserve)' HEARING_TYPE_DESC, 190 SEQ_NO, 70 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TRL' HEARING_TYPE_CODE, 'For Trial' HEARING_TYPE_DESC, 100 SEQ_NO, 40 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TRN' HEARING_TYPE_CODE, 'For Trial' HEARING_TYPE_DESC, 105 SEQ_NO, 45 LIST_SEQUENCE FROM DUAL UNION
SELECT 'TWC' HEARING_TYPE_CODE, 'For Trial (Fixed for this Week)' HEARING_TYPE_DESC, 140 SEQ_NO, 10 LIST_SEQUENCE FROM DUAL UNION
SELECT 'XPA' HEARING_TYPE_CODE, 'For Application (Ex Parte)' HEARING_TYPE_DESC, 20 SEQ_NO, 1310 LIST_SEQUENCE FROM DUAL) keyed_data) subqry 
WHERE NOT EXISTS (SELECT 1 FROM XHB_REF_HEARING_TYPE xrht 
                   WHERE xrht.HEARING_TYPE_CODE = subqry.HEARING_TYPE_CODE
                     AND xrht.COURT_ID = subqry.COURT_ID
                     AND xrht.CATEGORY = subqry.CATEGORY);
					 
COMMIT;
    DBMS_OUTPUT.PUT_LINE('Executed load_xhb_ref_hearing_types.  End Time: '||to_char(sysdate,'DD-MM-YYYY HH24:MI:SS')||'.');

EXCEPTION
     WHEN OTHERS THEN
          raise_application_error(-20001,'Error in load_xhb_ref_hearing_types :- ' || SQLCODE || ' : ' || SQLERRM);

END load_xhb_ref_hearing_types;
/