
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * @author ewingsg
 * 
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DARTSServiceXHB", targetNamespace = "http://com.synapps.mojdarts.service.com", wsdlLocation = "DARTSServiceXHB.wsdl")
public class DARTSServiceXHB
    extends Service
{

    private final static URL DARTSSERVICEXHB_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.DARTSServiceXHB.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.DARTSServiceXHB.class.getResource(".");
            url = new URL(baseUrl, "/F:/XHIBIT/XHIBIT_8_2/midtier/darts/resources/DARTSServiceXHB.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'DARTSServiceXHB.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DARTSSERVICEXHB_WSDL_LOCATION = url;
    }

    public DARTSServiceXHB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DARTSServiceXHB() {
        super(DARTSSERVICEXHB_WSDL_LOCATION, new QName("http://com.synapps.mojdarts.service.com", "DARTSServiceXHB"));
    }

    /**
     * 
     * @return
     *     returns DARTSServiceXHBPort
     */
    @WebEndpoint(name = "DARTSServiceXHBPort")
    public DARTSServiceXHBPort getDARTSServiceXHBPort() {
        return super.getPort(new QName("http://com.synapps.mojdarts.service.com", "DARTSServiceXHBPort"), DARTSServiceXHBPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DARTSServiceXHBPort
     */
    @WebEndpoint(name = "DARTSServiceXHBPort")
    public DARTSServiceXHBPort getDARTSServiceXHBPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.synapps.mojdarts.service.com", "DARTSServiceXHBPort"), DARTSServiceXHBPort.class, features);
    }

}
