
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import uk.gov.courtservice.framework.services.CSServices;
import uk.gov.courtservice.xhibit.business.services.darts.DartsConfiguration;
import uk.gov.courtservice.xhibit.business.services.darts.DartsException;
import uk.gov.courtservice.xhibit.business.services.dartsmessagesender.WSDartsSenderControllerBean;


/**
 * @author ewingsg
 * 
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DARTSService", targetNamespace = "http://com.synapps.mojdarts.service.com", wsdlLocation = "DARTSService.wsdl")
@HandlerChain(file="handler-chain.xml")
public class DARTSService
    extends Service
{
    protected static final org.apache.log4j.Logger logging = CSServices.getLogger(DARTSService.class);

    private final static URL DARTSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.DARTSService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlLocation = WSDartsSenderControllerBean.getDartsWsdlLocation();
            url = new URL("file://"+ wsdlLocation);
        } catch (MalformedURLException e) {
        	logging.debug("Failed to create URL for the wsdl Location: 'DARTSService.wsdl'");
        	logging.debug(e.getMessage());
        }
        logging.debug("DARTS LOGGER IS "+url);
        DARTSSERVICE_WSDL_LOCATION = url;
    }

    public DARTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DARTSService() {
    	
        super(DARTSSERVICE_WSDL_LOCATION, new QName("http://com.synapps.mojdarts.service.com", "DARTSService"));
    }

    /**
     * 
     * @return
     *     returns DARTSServicePort
     */
    @WebEndpoint(name = "DARTSServicePort")
    public DARTSServicePort getDARTSServicePort() {
        return super.getPort(new QName("http://com.synapps.mojdarts.service.com", "DARTSServicePort"), DARTSServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DARTSServicePort
     */
    @WebEndpoint(name = "DARTSServicePort")
    public DARTSServicePort getDARTSServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.synapps.mojdarts.service.com", "DARTSServicePort"), DARTSServicePort.class, features);
    }

}
