
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://com.synapps.mojdarts.service.com")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.Exception faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Exception_Exception(String message, uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Exception_Exception(String message, uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.service.mojdarts.synapps.com.Exception
     */
    public uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service.Exception getFaultInfo() {
        return faultInfo;
    }

}
