
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.DARTSService.service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ServiceException", targetNamespace = "http://rt.fs.documentum.emc.com/")
public class ServiceException
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.ServiceException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ServiceException(String message, uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.ServiceException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ServiceException(String message, uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.ServiceException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.emc.documentum.fs.rt.ServiceException
     */
    public uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.ServiceException getFaultInfo() {
        return faultInfo;
    }

}
