/*CTX-2342*/
UPDATE XHB_DISPOSAL2 SET DIS_ID = DISPOSAL2_ID WHERE DIS_ID IS NULL;

/* UPDATE AUD_DISPOSAL2 SET DIS_ID = DISPOSAL2_ID WHERE DIS_ID IS NULL; */

ALTER TABLE XHB_DISPOSAL2 MODIFY
(dis_id NUMBER(8) NOT NULL
);
 
/* ALTER TABLE AUD_DISPOSAL2 MODIFY (dis_id NUMBER(8)); */
 
commit;
