--2332--
ALTER TABLE XHB_REF_CRACKED_EFFECTIVE
ADD (TRIAL_CODE_TYPE VARCHAR2(1));

ALTER TABLE AUD_REF_CRACKED_EFFECTIVE
ADD (TRIAL_CODE_TYPE VARCHAR2(1));

@@xhb_ref_cracked_effect_bur_tr.sql;

COMMIT;

