/*ctx-2341 & ctx2124*/
ALTER TABLE xhb_court 
 ADD (IS_PILOT VARCHAR2(1) DEFAULT 'N' NOT NULL,
	DX_REF VARCHAR2(35),
	COUNTY_LOC_CODE VARCHAR2(5),
	TIER VARCHAR2(1) );

ALTER TABLE aud_court 
 ADD (IS_PILOT VARCHAR2(1),
	DX_REF VARCHAR2(35),
	COUNTY_LOC_CODE VARCHAR2(5),
	TIER VARCHAR2(1) );
     
@@xhb_court_bur_tr;

COMMIT;