CREATE OR REPLACE TRIGGER XHB_DEF_CASE_SOL_FIRM_BUR_TR
  BEFORE UPDATE OR DELETE
  ON XHB_DEF_ON_CASE_REF_SOL_FIRM
  FOR EACH ROW
DECLARE

  l_trig_event VARCHAR2(1) := NULL;

  OPTIMISTIC_LOCK_PROB EXCEPTION;
  PRAGMA EXCEPTION_INIT(OPTIMISTIC_LOCK_PROB, -20101);

BEGIN

  IF UPDATING THEN

    l_trig_event := 'U';

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 1) THEN

      IF (:OLD.VERSION != :NEW.VERSION) THEN

        RAISE OPTIMISTIC_LOCK_PROB;

      END IF;

    END IF;

    SELECT :OLD.VERSION + 1,
           SYSDATE
    INTO   :NEW.VERSION,
           :NEW.LAST_UPDATE_DATE
    FROM   DUAL;

    IF (XHB_CUSTOM_PKG.IS_CONNECTION_POOL_USER = 0) THEN

      SELECT SYS_CONTEXT('USERENV', 'SESSION_USER')
      INTO   :NEW.LAST_UPDATED_BY
      FROM   DUAL;

    END IF;

  ELSE -- Must be DELETING

    l_trig_event := 'D';

  END IF;

  /* Is Auditing on this table required */
  IF (XHB_CUSTOM_PKG.IS_AUDIT_REQUIRED('XHB_DEF_ON_CASE_REF_SOL_FIRM') = 1) THEN

    INSERT INTO AUD_DEF_ON_CASE_REF_SOL_FIRM (
	    DEF_ON_CASE_REF_SOL_FIRM_ID,
            DEFENDANT_ON_CASE_ID,
            REF_SOLICITOR_FIRM_ID,
            CREST_CPF_ID,
            REP_TYPE,
            REP_ST_DATE,
	    REP_END_DATE,
            LAST_UPDATE_DATE,
            CREATION_DATE,
            CREATED_BY,
            LAST_UPDATED_BY,
            VERSION,
	    SOLICITOR_REF, 
	    LIST_DATE_SENT, 
	    LIST_DATE_RECEIVED,
	    INSERT_EVENT)
    VALUES (:OLD.DEF_ON_CASE_REF_SOL_FIRM_ID,
            :OLD.DEFENDANT_ON_CASE_ID,
            :OLD.REF_SOLICITOR_FIRM_ID,
            :OLD.CREST_CPF_ID,
            :OLD.REP_TYPE,
            :OLD.REP_ST_DATE,
	    :OLD.REP_END_DATE,
            :OLD.LAST_UPDATE_DATE,
            :OLD.CREATION_DATE,
            :OLD.CREATED_BY,
            :OLD.LAST_UPDATED_BY,
            :OLD.VERSION,
	    :OLD.SOLICITOR_REF, 
	    :OLD.LIST_DATE_SENT, 
	    :OLD.LIST_DATE_RECEIVED,
            l_trig_event);

  END IF;

END;
/