/* Hearing Types -  PreDefined Reason On Deletion */
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRN', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRL', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TNW', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TIS', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TWC', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TPR', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TPW', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TFW', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TFL', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TRE', 'N');
INSERT INTO XHB_REF_LISTING_DATA (ref_listing_data_id, ref_data_type, ref_data_value, obs_ind) VALUES (XHB_REF_LISTING_DATA_SEQ.NEXTVAL, 'PREDEFINED_DELETION_REASON_HEARING_TYPES', 'TBK', 'N');

COMMIT;