/*
 * FILE_NAME:          XHIBIT2_Standing_PublicDisplay_Court.sql
 *
 * ENVIRONMENT:        
 *
 * DESCRIPTION:        
 *
 * STATUS DESCRIPTION: 
 *
 * DEPENDENCIES:       
 *
 * OWNER:              Rakesh Lakhani
 */ 

DELETE FROM XHB_DISPLAY_COURT_ROOM;

DELETE FROM XHB_DISPLAY;

DELETE FROM XHB_DISPLAY_LOCATION;

DELETE FROM XHB_ROTATION_SET_DD
WHERE  ROTATION_SET_ID IN (SELECT rotation_set_id
                           FROM   XHB_ROTATION_SETS
                           WHERE  DEFAULT_YN = 'Y');

DELETE FROM XHB_ROTATION_SETS WHERE DEFAULT_YN='Y';

COMMIT;

--_________________________
--Set up the Rotation Sets.
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  1, C.COURT_ID, 'Public View', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  2, C.COURT_ID, 'Court Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  3, C.COURT_ID, 'Jury Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  4, C.COURT_ID, 'Summary By Name', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  5, C.COURT_ID, 'Status', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  6, C.COURT_ID, 'Daily List', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  7, C.COURT_ID, 'All Lists', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '453';

INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  8, C.COURT_ID, 'Public View', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  9, C.COURT_ID, 'Court Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  10, C.COURT_ID, 'Jury Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  11, C.COURT_ID, 'Summary By Name', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  12, C.COURT_ID, 'Status', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  13, C.COURT_ID, 'Daily List', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  14, C.COURT_ID, 'All Lists', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '499';

INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  15, C.COURT_ID, 'Public View', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  16, C.COURT_ID, 'Court Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  17, C.COURT_ID, 'Jury Room', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  18, C.COURT_ID, 'Summary By Name', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  19, C.COURT_ID, 'Status', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  20, C.COURT_ID, 'Daily List', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';
INSERT INTO XHB_ROTATION_SETS ( ROTATION_SET_ID, COURT_ID, DESCRIPTION, DEFAULT_YN ) 
SELECT  21, C.COURT_ID, 'All Lists', 'Y'
FROM    XHB_COURT C
WHERE   C.CREST_COURT_ID = '475';

COMMIT;

INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (1, 1, 3, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (2, 1, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (3, 2, 1, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (4, 2, 2, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (5, 3, 6, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (6, 4, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (7, 5, 4, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (8, 6, 3, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (9, 7, 1, 10, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (10, 7, 2, 10, 3); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (11, 7, 3, 10, 4); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (12, 7, 4, 10, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (13, 7, 5, 10, 6); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (14, 7, 6, 10, 5);
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (15, 7, 7, 10, 7);

INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (16, 8, 3, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (17, 8, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (18, 9, 1, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (19, 9, 2, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (20, 10, 6, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (21, 11, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (22, 12, 4, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (23, 13, 3, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (24, 14, 1, 10, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (25, 14, 2, 10, 3); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (26, 14, 3, 10, 4); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (27, 14, 4, 10, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (28, 14, 5, 10, 6); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (29, 14, 6, 10, 5);
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (30, 14, 7, 10, 7);

INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (31, 15, 3, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (32, 15, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (33, 16, 1, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (34, 16, 2, 20, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (35, 17, 6, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (36, 18, 5, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (37, 19, 4, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (38, 20, 3, 20, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (39, 21, 1, 10, 2); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (40, 21, 2, 10, 3); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (41, 21, 3, 10, 4); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (42, 21, 4, 10, 1); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (43, 21, 5, 10, 6); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (44, 21, 6, 10, 5); 
INSERT INTO XHB_ROTATION_SET_DD ( ROTATION_SET_DD_ID, ROTATION_SET_ID, DISPLAY_DOCUMENT_ID, PAGE_DELAY, ORDERING ) 
VALUES (45, 21, 7, 10, 7);
COMMIT;

--_____________________________
--Set up the Display Locations.
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  1,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  2,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  3,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  4,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  5,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  6,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  7,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  8,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  9,
        'court_room_9',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  10,
        'court_room_10',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  11,
        'court_room_11',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  12,
        'court_room_12',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  13,
        'court_room_13',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  14,
        'court_room_14',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  15,
        'court_room_15',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  16,
        'court_room_16',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  17,
        'court_room_17',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  18,
        'court_room_18',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  19,
        'court_room_19',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  20,
        'court_room_20',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  21,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  22,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  23,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  24,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  25,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  26,
        'police_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  27,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  28,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  29,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  30,
        'j_l_a_b',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  31,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '453' --Snaresbrook
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  32,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  33,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  34,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  35,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  36,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  37,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  38,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  39,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  40,
        'court_room_9',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  41,
        'court_room_10',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  42,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  43,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  44,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  45,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  46,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  47,
        'police_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  48,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  49,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  50,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  51,
        'j_l_a_b',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  52,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '499' --Dockford
AND     CS.COURT_SITE_CODE = 'A';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  53,
        'court_room_1',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  54,
        'court_room_2',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  55,
        'court_room_3',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  56,
        'court_room_4',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  57,
        'court_room_5',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  58,
        'court_room_6',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  59,
        'court_room_7',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
    DISPLAY_LOCATION_ID,
    DESCRIPTION_CODE,
    COURT_SITE_ID
)
SELECT  60,
        'court_room_8',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  73,
        'e_v',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  74,
        'reception',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  75,
        'public_restaurant',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  76,
        'jury_lounge',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  77,
        'witness_service',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  78,
        'police_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  79,
        'ps_s_o_1st_floor',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  80,
        'n_w_c_w_a',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  81,
        'b_a_s_r',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

INSERT INTO XHB_DISPLAY_LOCATION
(
	DISPLAY_LOCATION_ID,
	DESCRIPTION_CODE,
	COURT_SITE_ID
)
SELECT  83,
        'v_i_p',
        CS.COURT_SITE_ID
FROM    XHB_COURT_SITE CS,
        XHB_COURT C
WHERE   C.COURT_ID = CS.COURT_ID
AND     C.CREST_COURT_ID = '475' --I
AND     CS.COURT_SITE_CODE = 'I';

--______________________
--Set up the displays...
--¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯¯
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
1, 1, 1, 2, 'courtroom_1_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
2, 1, 2, 2, 'courtroom_2_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
3, 1, 3, 2, 'courtroom_3_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
4, 1, 4, 2, 'courtroom_4_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
5, 1, 5, 2, 'courtroom_5_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
6, 1, 6, 2, 'courtroom_6_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
7, 1, 7, 2, 'courtroom_7_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
8, 1, 8, 2, 'courtroom_8_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
9, 1, 9, 2, 'courtroom_9_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
10, 1, 10, 2, 'courtroom_10_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
11, 1, 11, 2, 'courtroom_11_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
12, 1, 12, 2, 'courtroom_12_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
13, 1, 13, 2, 'courtroom_13_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
14, 1, 14, 2, 'courtroom_14_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
15, 1, 15, 2, 'courtroom_15_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
16, 1, 16, 2, 'courtroom_16_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
17, 1, 17, 2, 'courtroom_17_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
18, 1, 18, 2, 'courtroom_18_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
19, 1, 19, 2, 'courtroom_19_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
20, 1, 20, 2, 'courtroom_20_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
21, 2, 21, 4, 'e_v_plasma_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
22, 2, 22, 6, 'reception_42_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
23, 1, 23, 1, 'public_rest_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
24, 1, 23, 1, 'public_rest_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
25, 1, 24, 3, 'jury_lounge_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
26, 1, 24, 3, 'jury_lounge_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
27, 1, 25, 1, 'witness_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
28, 1, 26, 1, 'police_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
29, 1, 27, 1, 'ps_sec_off_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
30, 2, 28, 5, 'nwcwa_plasma_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
31, 1, 29, 1, 'b_a_s_r_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
32, 2, 29, 1, 'b_a_s_r_42in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
33, 1, 30, 3, 'jl_ab_18in_display_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
34, 1, 30, 3, 'jl_ab_18in_display_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
35, 3, 31, 7, 'v_i_p', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
41, 1, 32, 9, 'courtroom_1_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
42, 1, 33, 9, 'courtroom_2_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
43, 1, 34, 9, 'courtroom_3_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
44, 1, 35, 9, 'courtroom_4_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
45, 1, 36, 9, 'courtroom_5_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
46, 1, 37, 9, 'courtroom_6_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
47, 1, 38, 9, 'courtroom_7_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
48, 1, 39, 9, 'courtroom_8_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
49, 1, 40, 9, 'courtroom_9_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
50, 1, 41, 9, 'courtroom_10_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
51, 2, 42, 11, 'e_v_plasma_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
52, 2, 43, 13, 'reception_42_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
53, 1, 44, 8, 'public_rest_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
54, 1, 44, 8, 'public_rest_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
55, 1, 45, 10, 'jury_lounge_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
56, 1, 45, 10, 'jury_lounge_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
57, 1, 46, 8, 'witness_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
58, 1, 47, 8, 'police_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
59, 1, 48, 8, 'ps_sec_off_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
60, 2, 49, 12, 'nwcwa_plasma_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
61, 1, 50, 8, 'b_a_s_r_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
62, 2, 50, 8, 'b_a_s_r_42in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
63, 1, 51, 10, 'jl_ab_18in_display_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
64, 1, 51, 10, 'jl_ab_18in_display_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
65, 3, 52, 14, 'v_i_p', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
71, 1, 53, 16, 'courtroom_1_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
72, 1, 54, 16, 'courtroom_2_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
73, 1, 55, 16, 'courtroom_3_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
74, 1, 56, 16, 'courtroom_4_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
75, 1, 57, 16, 'courtroom_5_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
76, 1, 58, 16, 'courtroom_6_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
77, 1, 59, 16, 'courtroom_7_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
78, 1, 60, 16, 'courtroom_8_display', 'enGB', 'N'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
91, 2, 73, 18, 'e_v_plasma_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
92, 2, 74, 20, 'reception_42_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
93, 1, 75, 15, 'public_rest_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
94, 1, 75, 15, 'public_rest_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
95, 1, 76, 17, 'jury_lounge_18in_1', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
96, 1, 76, 17, 'jury_lounge_18in_2', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
97, 1, 77, 15, 'witness_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
98, 1, 78, 15, 'police_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
99, 1, 79, 15, 'ps_sec_off_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
100, 2, 80, 19, 'nwcwa_plasma_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
101, 1, 81, 15, 'b_a_s_r_18in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
102, 2, 81, 15, 'b_a_s_r_42in_display', 'enGB', 'Y'); 
INSERT INTO XHB_DISPLAY ( DISPLAY_ID, DISPLAY_TYPE_ID, DISPLAY_LOCATION_ID, ROTATION_SET_ID,
DESCRIPTION_CODE, LOCALE, SHOW_UNASSIGNED_YN ) VALUES ( 
105, 3, 83, 21, 'v_i_p', 'enGB', 'Y'); 
COMMIT;

INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (1, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (2, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (3, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (4, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (5, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (6, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (7, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (8, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (9, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (10, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (11, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (12, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (13, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (14, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (15, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (16, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (17, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (18, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (19, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (20, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (21, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (22, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (23, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (24, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (25, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (26, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (27, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (28, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (29, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (30, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (31, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (32, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (33, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (34, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 1); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 2); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 3); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 4); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 5); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 6); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 7); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 8); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 9); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 10); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 11); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 12); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 13); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 14); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 15); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 16); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 17); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 18); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 19); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (35, 20); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (41, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (42, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (43, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (44, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (45, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (46, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (47, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (48, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (49, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (50, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (51, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (52, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (53, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (54, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (55, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (55, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (55, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (55, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (55, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (56, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (56, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (56, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (56, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (56, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (57, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (58, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (59, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (60, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (61, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (62, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (63, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (63, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (63, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (63, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (63, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (64, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (64, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (64, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (64, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (64, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 21); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 22); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 23); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 24); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 25); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 26); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 27); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 28); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 29); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (65, 30); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (71, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (72, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (73, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (74, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (75, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (76, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (77, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (78, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (91, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (92, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (93, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (94, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (95, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (96, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (97, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (98, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (99, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (100, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (101, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (102, 38); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 31); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 32); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 33); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 34); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 35); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 36); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 37); 
INSERT INTO XHB_DISPLAY_COURT_ROOM ( DISPLAY_ID, COURT_ROOM_ID ) VALUES (105, 38); 
COMMIT;

-- Reset sequences
DECLARE
	CURSOR c1 IS SELECT utc.table_name, utc.column_name AS PRIMARY_KEY_COLUMN_NAME,
		   	  	 		us.sequence_name, us.increment_by, us.last_number 
		   	  	 FROM   user_tab_columns utc, user_sequences us
				 WHERE  utc.table_name = SUBSTR(us.sequence_name, 0, LENGTH(us.sequence_name) - 4)
				 AND	   utc.column_id = 1
				 AND	   (utc.table_name LIKE 'XHB_REF%'
				 OR		    utc.table_name IN ('XHB_ROTATION_SETS', 'XHB_ROTATION_SET_DD', 'XHB_DISPLAY_LOCATION',
				 						   	   'XHB_DISPLAY'));
    l_max_id NUMBER;
BEGIN
	 FOR rec IN c1 LOOP
	 	 EXECUTE IMMEDIATE 'SELECT MAX(' || rec.primary_key_column_name || ') FROM ' || rec.table_name
		 INTO l_max_id;
		 
		 IF (l_max_id > rec.last_number) THEN
		 	l_max_id := l_max_id - rec.last_number + 1;
			EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || rec.sequence_name || ' INCREMENT BY ' || l_max_id;
			EXECUTE IMMEDIATE 'SELECT ' || rec.sequence_name || '.NEXTVAL FROM dual' INTO l_max_id;
			EXECUTE IMMEDIATE 'ALTER SEQUENCE ' || rec.sequence_name || ' INCREMENT BY ' || rec.increment_by;
		 END IF;
	 END LOOP;
END;