--  FILE_NAME:         XHIBIT2_Standing_PublicDisplayConfigStaticData.sql                                                     
--  ENVIRONMENT:       Live, System, Pre-production, Integration, Development                                                 
--  DESCRIPTION:       This script populates tables that provide the Public Displays with information 
--                     about each display and what information should be shown on each display. 
--                     This is configurable using the Public Display administrator in the rich client.                        
--  STATUS DESCRIPTION:Script is suitable for running initially on set-up of the database on any environment.
--                     Adds data for three possible rotation sets on all screen.
--	14/07/2003 CO - Added configuration information for Court 1 (SNARESBROOK), Court 2 (DOCKFORD) and Court 3(ISELWORTH)
--	14/08/2003 CO - Added more rotation sets
--  DEPENDENCIES:      It assumes there is court data in XHB_COURT and XHB_COURT_ROOM and 
--                     Note. THIS SCRIPT SHOULD ONLY BE RUN ONCE ON INITIAL SET-UP OF THE DATABASE                   
--  OWNER:             Rakesh Lakhani, Ben Briggs, Cag Onganer
--


/**
	Delete Tables
*/

DELETE FROM XHB_PAGE_PANEL;
DELETE FROM XHB_ATTRIBUTE;
DELETE FROM XHB_EVENT;
DELETE FROM XHB_PANEL;
DELETE FROM XHB_PAGE_ROTATION_SET;
DELETE FROM XHB_PAGE; 

DELETE FROM XHB_SCREEN_COURT_ROOM;
DELETE FROM XHB_SCREEN;

DELETE FROM XHB_ROTATION_SET;

DELETE FROM XHB_SCREEN_LOCATION;

COMMIT;

/**
	Panel Standing Data
*/
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
1, 'allCourtStatus', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.AllCourtStatusPanelGenerator'); 
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
2, 'summaryByName', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.SummaryByNamePanelGenerator');
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
3, 'dailyList', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.DailyListPanelGenerator'); 
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
4, 'courtList', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.CourtListPanelGenerator'); 
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
5, 'courtDetail', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.CourtDetailPanelGenerator'); 
INSERT INTO XHB_PANEL ( PANEL_ID, TITLE, CLASS_SOURCE ) VALUES ( 
6, 'juryCurrentStatus', 'uk.gov.courtservice.xhibit.web.publicdisplay.cma.panels.JuryCurrentStatusPanelGenerator'); 
COMMIT;

DROP SEQUENCE XHB_PANEL_SEQ;
CREATE SEQUENCE XHB_PANEL_SEQ START WITH 7 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;


/**
	JMS Notification Events and Attirbutes
*/
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
1, 'DAILY_SCHEDULE_CHANGED', 1); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
2, 'COURT_LOG_CHANGED', 1); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
3, 'CASE_STARTED_IN_COURT', 1); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
4, 'CASE_FINISHED_IN_COURT', 1); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
5, 'DEFENDANT_CHANGED', 1); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
6, 'DAILY_SCHEDULE_CHANGED', 2); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
7, 'CASE_MOVED', 2); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
8, 'DEFENDANT_CHANGED', 2); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
9, 'DAILY_SCHEDULE_CHANGED', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
10, 'CASE_STARTED_IN_COURT', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
11, 'CASE_FINISHED_IN_COURT', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
12, 'DEFENDANT_CHANGED', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
13, 'JUDGE_CHANGED', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
14, 'CASE_MOVED', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
15, 'HEARING_PROGRESS_CHANGED', 3); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
16, 'DAILY_SCHEDULE_CHANGED', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
17, 'CASE_STARTED_IN_COURT', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
18, 'CASE_FINISHED_IN_COURT', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
19, 'DEFENDANT_CHANGED', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
20, 'JUDGE_CHANGED', 4);
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
21, 'CASE_MOVED', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
22, 'HEARING_PROGRESS_CHANGED', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
23, 'PUBLIC_NOTICE_CHANGED', 4); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
24, 'DAILY_SCHEDULE_CHANGED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
25, 'COURT_LOG_CHANGED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
26, 'CASE_STARTED_IN_COURT', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
27, 'CASE_FINISHED_IN_COURT', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
28, 'PUBLIC_NOTICE_CHANGED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
29, 'JUDGE_CHANGED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
30, 'DEFENDANT_CHANGED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
31, 'CASE_MOVED', 5); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
32, 'DAILY_SCHEDULE_CHANGED', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
33, 'CASE_STARTED_IN_COURT', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
34, 'CASE_FINISHED_IN_COURT', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
35, 'JUDGE_CHANGED', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
36, 'DEFENDANT_CHANGED', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
37, 'CASE_MOVED', 6); 
INSERT INTO XHB_EVENT ( EVENT_ID, NAME, PANEL_ID ) VALUES ( 
38, 'HEARING_PROGRESS_CHANGED', 6); 
COMMIT;

DROP SEQUENCE XHB_EVENT_SEQ;
CREATE SEQUENCE XHB_EVENT_SEQ START WITH 39 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
1, 'courtHouse', 1); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
2, 'courtHouse', 2); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
3, 'courtHouse', 3); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
4, 'courtHouse', 4); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
5, 'courtHouse', 5); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
6, 'courtHouse', 6); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
7, 'courtHouse', 7); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
8, 'courtHouse', 8); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
9, 'courtHouse', 9); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
10, 'courtHouse', 10); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
11, 'courtHouse', 11); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
12, 'courtHouse', 12); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
13, 'courtHouse', 13); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
14, 'courtHouse', 14); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
15, 'courtHouse', 15); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
16, 'courtHouse', 16); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
17, 'courtHouse', 17); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
18, 'courtHouse', 18); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
19, 'courtHouse', 19); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
20, 'courtHouse', 20); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
21, 'courtHouse', 21); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
22, 'courtHouse', 22); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
23, 'courtHouse', 23); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
24, 'courtHouse', 24); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
25, 'courtHouse', 25); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
26, 'courtHouse', 26); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
27, 'courtHouse', 27); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
28, 'courtHouse', 28); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
29, 'courtHouse', 29); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
30, 'courtHouse', 30); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
31, 'courtHouse', 31); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
32, 'courtHouse', 32); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
33, 'courtHouse', 33); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
34, 'courtHouse', 34); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
35, 'courtHouse', 35); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
36, 'courtHouse', 36); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
37, 'courtHouse', 37); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
38, 'courtHouse', 38); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
39, 'courtRoom', 16); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
40, 'courtRoom', 17); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
41, 'courtRoom', 18); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
42, 'courtRoom', 19); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
43, 'courtRoom', 20); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
44, 'courtRoom', 21); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
45, 'courtRoom', 22); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
46, 'courtRoom', 23); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
47, 'courtRoom', 24); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
48, 'courtRoom', 25); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
49, 'courtRoom', 26); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
50, 'courtRoom', 27); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
51, 'courtRoom', 28); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
52, 'courtRoom', 29); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
53, 'courtRoom', 30); 
INSERT INTO XHB_ATTRIBUTE ( ATTRIBUTE_ID, NAME, EVENT_ID ) VALUES ( 
54, 'courtRoom', 31); 
COMMIT;

DROP SEQUENCE XHB_ATTRIBUTE_SEQ;
CREATE SEQUENCE XHB_ATTRIBUTE_SEQ START WITH 55 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

/**
	SNARESBROOK
*/

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 1, 'Court Room 1', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 2, 'Court Room 2', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 3, 'Court Room 3', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 4, 'Court Room 4', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 5, 'Court Room 5', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 6, 'Court Room 6', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 7, 'Court Room 7', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 8, 'Court Room 8', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 9, 'Court Room 9', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 10, 'Court Room 10', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 11, 'Court Room 11', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 12, 'Court Room 12', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 13, 'Court Room 13', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 14, 'Court Room 14', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 15, 'Court Room 15', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 16, 'Court Room 16', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 17, 'Court Room 17', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 18, 'Court Room 18', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 19, 'Court Room 19', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 20, 'Court Room 20', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 101, 'Entrance Vestibule', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 102, 'Reception', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 103, 'Public Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 104, 'Jury Lounge', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 105, 'Witness Service', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 106, 'Police Room 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 107, 'Probation Service Secretary Office 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 108, 'North Wing Common Waiting Area', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 109, 'Barristers and Staff Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 110, 'Jury Lounge Annex Building', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 453;
COMMIT;

DROP SEQUENCE XHB_SCREEN_LOCATION_SEQ;
CREATE SEQUENCE XHB_SCREEN_LOCATION_SEQ START WITH 111 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 1, 'PublicViewRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 2, 'CourtRoomRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 3, 'JuryRoomRS', '10:30'); 
COMMIT;

DROP SEQUENCE XHB_ROTATION_SET_SEQ;
CREATE SEQUENCE XHB_ROTATION_SET_SEQ START WITH 4 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;


INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (1, 'SNARSNARE~Ascr1','18in','Screen Outside Court 1',2,1);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (2, 'SNARSNARE~Ascr2','18in','Screen Outside Court 2',2,2);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (3, 'SNARSNARE~Ascr3','18in','Screen Outside Court 3',2,3);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (4, 'SNARSNARE~Ascr4','18in','Screen Outside Court 4',2,4);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 5, 'SNARSNARE~Ascr5','18in','Screen Outside Court 5',2,5);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 6, 'SNARSNARE~Ascr6','18in','Screen Outside Court 6',2,6);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 7, 'SNARSNARE~Ascr7','18in','Screen Outside Court 7',2,7);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 8, 'SNARSNARE~Ascr8','18in','Screen Outside Court 8',2,8);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 9, 'SNARSNARE~Ascr9','18in','Screen Outside Court 9',2,9);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 10, 'SNARSNARE~Ascr10','18in','Screen Outside Court 10',2,10);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 11, 'SNARSNARE~Ascr11','18in','Screen Outside Court 11',2,11);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 12, 'SNARSNARE~Ascr12','18in','Screen Outside Court 12',2,12);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 13, 'SNARSNARE~Ascr13','18in','Screen Outside Court 13',2,13);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 14, 'SNARSNARE~Ascr14','18in','Screen Outside Court 14',2,14);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 15, 'SNARSNARE~Ascr15','18in','Screen Outside Court 15',2,15);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 16, 'SNARSNARE~Ascr16','18in','Screen Outside Court 16',2,16);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 17, 'SNARSNARE~Ascr17','18in','Screen Outside Court 17',2,17);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 18, 'SNARSNARE~Ascr18','18in','Screen Outside Court 18',2,18);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 19, 'SNARSNARE~Ascr19','18in','Screen Outside Court 19',2,19);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 20, 'SNARSNARE~Ascr20','18in','Screen Outside Court 20',2,20);

INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 101, 'SNARSNARE~Ascr21','plasma','Entrance Vestibule Plasma Display',1,101);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 102, 'SNARSNARE~Ascr22','plasma','Reception Plasma Display',1,102);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 103, 'SNARSNARE~Ascr23','18in','Public Restaurant 18in #1',1,103);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 104, 'SNARSNARE~Ascr24','18in','Public Restaurant 18in #2',1,103);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 105, 'SNARSNARE~Ascr25','18in','Jury Lounge 18in #1',3,104);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 106, 'SNARSNARE~Ascr26','18in','Jury Lounge 18in #2',3,104);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 107, 'SNARSNARE~Ascr27','18in','Witness Service 18in Display',1,105);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 108, 'SNARSNARE~Ascr28','18in','Police Room 18in Display',1,106);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 109, 'SNARSNARE~Ascr29','18in','Probation Service Secretary Office Display',1,107);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 110, 'SNARSNARE~Ascr30','plasma','North Wing Common Waiting Area Plasma Display',1,108);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 111, 'SNARSNARE~Ascr31','18in','Barristers and Staff Restaurant 18in Display',1,109);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 112, 'SNARSNARE~Ascr32','plasma','Barristers and Staff Restaurant Plasma Display',1,109);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 113, 'SNARSNARE~Ascr33','18in','Jury Lounge Annex Building 18in Display #1',3,110);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 114, 'SNARSNARE~Ascr34','18in','Jury Lounge Annex Building 18in Display #2',3,110);

COMMIT;

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (1,1);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (2,2);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (3,3);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (4,4);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (5,5);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (6,6);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (7,7);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (8,8);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (9,9);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (10,10 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (11,11 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (12,12 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (13,13 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (14,14 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (15,15 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (16,16 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (17,17 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (18,18 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (19,19 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (20,20 );

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,1 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,2 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,3 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,4 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,5 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,6 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,7 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,8 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,9 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,10 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,11 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,12 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,13 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,14 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,15 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,16 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,17 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,18 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,19 );
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (101,20 );

COMMIT;

INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 1, c.short_name || '~' || cs.court_site_code || '_AllCourtStatus_1', 'All Court Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1; 
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 2, c.short_name || '~' || cs.court_site_code || '_SummaryByName_1', 'Summary By Name', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 3, c.short_name || '~' || cs.court_site_code || '_DailyList_1', 'Daily List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 4, c.short_name || '~' || cs.court_site_code || '_CourtList_1', 'Court List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 5, c.short_name || '~' || cs.court_site_code || '_CourtDetail_1', 'Court Detail', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 6, c.short_name || '~' || cs.court_site_code || '_JuryCurrentStatus_1', 'Jury Current Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 1;  
COMMIT;

DROP SEQUENCE XHB_PAGE_SEQ;
CREATE SEQUENCE XHB_PAGE_SEQ START WITH 7 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;
 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (1,1); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (2,1); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (3,1); 

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (4,2); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (5,2);  

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (6,3); 

COMMIT;


INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
1, 1); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
2, 2); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
3, 3); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
4, 4); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
5, 5); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
6, 6); 
COMMIT;


/**
	DOCKFORD
*/

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 21, 'Court Room 1', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 22, 'Court Room 2', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 23, 'Court Room 3', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 24, 'Court Room 4', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 25, 'Court Room 5', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 26, 'Court Room 6', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 27, 'Court Room 7', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 28, 'Court Room 8', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 29, 'Court Room 9', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 30, 'Court Room 10', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 201, 'Entrance Vestibule', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 202, 'Reception', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 203, 'Public Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 204, 'Jury Lounge', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 205, 'Witness Service', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 206, 'Police Room 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 207, 'Probation Service Secretary Office 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 208, 'North Wing Common Waiting Area', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 209, 'Barristers and Staff Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 210, 'Jury Lounge Annex Building', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 499;
COMMIT;

DROP SEQUENCE XHB_SCREEN_LOCATION_SEQ;
CREATE SEQUENCE XHB_SCREEN_LOCATION_SEQ START WITH 211 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 21, 'PublicViewRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 22, 'CourtRoomRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 23, 'JuryRoomRS', '10:30'); 
COMMIT;

DROP SEQUENCE XHB_ROTATION_SET_SEQ;
CREATE SEQUENCE XHB_ROTATION_SET_SEQ START WITH 24 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (21, 'DOCKDOCKF~Ascr1','18in','Screen Outside Court 1',22,21);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (22, 'DOCKDOCKF~Ascr2','18in','Screen Outside Court 2',22,22);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (23, 'DOCKDOCKF~Ascr3','18in','Screen Outside Court 3',22,23);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (24, 'DOCKDOCKF~Ascr4','18in','Screen Outside Court 4',22,24);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 25, 'DOCKDOCKF~Ascr5','18in','Screen Outside Court 5',22,25);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 26, 'DOCKDOCKF~Ascr6','18in','Screen Outside Court 6',22,26);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 27, 'DOCKDOCKF~Ascr7','18in','Screen Outside Court 7',22,27);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 28, 'DOCKDOCKF~Ascr8','18in','Screen Outside Court 8',22,28);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 29, 'DOCKDOCKF~Ascr9','18in','Screen Outside Court 9',22,29);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 30, 'DOCKDOCKF~Ascr10','18in','Screen Outside Court 10',22,30);

INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 201, 'DOCKDOCKF~Ascr11','plasma','Entrance Vestibule Plasma Display',21,201);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 202, 'DOCKDOCKF~Ascr12','plasma','Reception Plasma Display',21,202);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 203, 'DOCKDOCKF~Ascr13','18in','Public Restaurant 18in #1',21,203);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 204, 'DOCKDOCKF~Ascr14','18in','Public Restaurant 18in #2',21,203);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 205, 'DOCKDOCKF~Ascr15','18in','Jury Lounge 18in #1',23,204);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 206, 'DOCKDOCKF~Ascr16','18in','Jury Lounge 18in #2',23,204);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 207, 'DOCKDOCKF~Ascr17','18in','Witness Service 18in Display',21,205);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 208, 'DOCKDOCKF~Ascr18','18in','Police Room 18in Display',21,206);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 209, 'DOCKDOCKF~Ascr19','18in','Probation Service Secretary Office Display',21,207);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 210, 'DOCKDOCKF~Ascr20','plasma','North Wing Common Waiting Area Plasma Display',21,208);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 211, 'DOCKDOCKF~Ascr21','18in','Barristers and Staff Restaurant 18in Display',21,209);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 212, 'DOCKDOCKF~Ascr22','plasma','Barristers and Staff Restaurant Plasma Display',21,209);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 213, 'DOCKDOCKF~Ascr23','18in','Jury Lounge Annex Building 18in Display #1',23,210);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 214, 'DOCKDOCKF~Ascr24','18in','Jury Lounge Annex Building 18in Display #2',23,210);

COMMIT;

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (21,21);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (22,22);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (23,23);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (24,24);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (25,25);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (26,26);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (27,27);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (28,28);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (29,29);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (30,30);

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,21);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,22);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,23);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,24);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,25);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,26);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,27);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,28);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,29);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (201,30);

COMMIT;

INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 21, c.short_name || '~' || cs.court_site_code || '_AllCourtStatus_1', 'All Court Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2; 
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 22, c.short_name || '~' || cs.court_site_code || '_SummaryByName_1', 'Summary By Name', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 23, c.short_name || '~' || cs.court_site_code || '_DailyList_1', 'Daily List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 24, c.short_name || '~' || cs.court_site_code || '_CourtList_1', 'Court List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 25, c.short_name || '~' || cs.court_site_code || '_CourtDetail_1', 'Court Detail', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 26, c.short_name || '~' || cs.court_site_code || '_JuryCurrentStatus_1', 'Jury Current Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 2;  
COMMIT;

DROP SEQUENCE XHB_PAGE_SEQ;
CREATE SEQUENCE XHB_PAGE_SEQ START WITH 27 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (21,21); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (22,21); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (23,21); 

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (24,22); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (25,22);  

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (26,23); 

COMMIT;


INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
21,1); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
22, 2); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
23, 3); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
24, 4); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
25, 5); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
26, 6); 
COMMIT;


/**
	ISELWORTH
*/

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 31, 'Court Room 1', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 32, 'Court Room 2', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 33, 'Court Room 3', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 34, 'Court Room 4', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 35, 'Court Room 5', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 36, 'Court Room 6', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 37, 'Court Room 7', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 38, 'Court Room 8', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;

INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 301, 'Entrance Vestibule', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 302, 'Reception', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 303, 'Public Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 304, 'Jury Lounge', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 305, 'Witness Service', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 306, 'Police Room 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 307, 'Probation Service Secretary Office 1st Floor', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 308, 'North Wing Common Waiting Area', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 309, 'Barristers and Staff Restaurant', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
INSERT INTO XHB_SCREEN_LOCATION ( SCREEN_LOCATION_ID, DESCRIPTION, COURT_SITE_ID )  
	   SELECT 310, 'Jury Lounge Annex Building', CS.COURT_SITE_ID FROM XHB_COURT_SITE CS, XHB_COURT C 
           WHERE C.COURT_ID = CS.COURT_ID 
           AND C.CREST_COURT_ID = 475;
COMMIT;

DROP SEQUENCE XHB_SCREEN_LOCATION_SEQ;
CREATE SEQUENCE XHB_SCREEN_LOCATION_SEQ START WITH 310 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 31, 'PublicViewRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 32, 'CourtRoomRS', '10:30'); 
INSERT INTO XHB_ROTATION_SET ( ROTATION_SET_ID, DESCRIPTION, DISPLAY_TIMES ) 
VALUES ( 33, 'JuryRoomRS', '10:30'); 
COMMIT;

DROP SEQUENCE XHB_ROTATION_SET_SEQ;
CREATE SEQUENCE XHB_ROTATION_SET_SEQ START WITH 34 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (31, 'ISLEISLEW~Iscr1','18in','Screen Outside Court 1',32,31);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (32, 'ISLEISLEW~Iscr2','18in','Screen Outside Court 2',32,32);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (33, 'ISLEISLEW~Iscr3','18in','Screen Outside Court 3',32,33);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES (34, 'ISLEISLEW~Iscr4','18in','Screen Outside Court 4',32,34);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 35, 'ISLEISLEW~Iscr5','18in','Screen Outside Court 5',32,35);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 36, 'ISLEISLEW~Iscr6','18in','Screen Outside Court 6',32,36);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 37, 'ISLEISLEW~Iscr7','18in','Screen Outside Court 7',32,37);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 38, 'ISLEISLEW~Iscr8','18in','Screen Outside Court 8',32,38);

INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 301, 'ISLEISLEW~Iscr21','plasma','Entrance Vestibule Plasma Display',31,301);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 302, 'ISLEISLEW~Iscr22','plasma','Reception Plasma Display',31,302);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 303, 'ISLEISLEW~Iscr23','18in','Public Restaurant 18in #1',31,303);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 304, 'ISLEISLEW~Iscr24','18in','Public Restaurant 18in #2',31,303);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 305, 'ISLEISLEW~Iscr25','18in','Jury Lounge 18in #1',33,304);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 306, 'ISLEISLEW~Iscr26','18in','Jury Lounge 18in #2',33,304);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 307, 'ISLEISLEW~Iscr27','18in','Witness Service 18in Display',31,305);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 308, 'ISLEISLEW~Iscr28','18in','Police Room 18in Display',31,306);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 309, 'ISLEISLEW~Iscr29','18in','Probation Service Secretary Office Display',31,307);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 310, 'ISLEISLEW~Iscr30','plasma','North Wing Common Waiting Area Plasma Display',31,308);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 311, 'ISLEISLEW~Iscr31','18in','Barristers and Staff Restaurant 18in Display',31,309);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 312, 'ISLEISLEW~Iscr32','plasma','Barristers and Staff Restaurant Plasma Display',31,309);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 313, 'ISLEISLEW~Iscr33','18in','Jury Lounge Annex Building 18in Display #1',33,310);
INSERT INTO XHB_SCREEN (SCREEN_ID, NAME, TYPE, DESCRIPTION, ROTATION_SET_ID, SCREEN_LOCATION_ID )
VALUES ( 314, 'ISLEISLEW~Iscr34','18in','Jury Lounge Annex Building 18in Display #2',33,310);

COMMIT;

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (31,31);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (32,32);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (33,33);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (34,34);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (35,35);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (36,36);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (37,37);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (38,38);

INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,31);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,32);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,33);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,34);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,35);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,36);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,37);
INSERT INTO XHB_SCREEN_COURT_ROOM ( SCREEN_ID, COURT_ROOM_ID ) VALUES (301,38);

COMMIT;

INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 31, c.short_name || '~' || cs.court_site_code || '_AllCourtStatus_1', 'All Court Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3; 
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 32, c.short_name || '~' || cs.court_site_code || '_SummaryByName_1', 'Summary By Name', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 33, c.short_name || '~' || cs.court_site_code || '_DailyList_1', 'Daily List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY )
	SELECT 34, c.short_name || '~' || cs.court_site_code || '_CourtList_1', 'Court List', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 35, c.short_name || '~' || cs.court_site_code || '_CourtDetail_1', 'Court Detail', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3;  
INSERT INTO XHB_PAGE ( PAGE_ID, NAME, DESCRIPTION, DELAY ) 
	SELECT 36, c.short_name || '~' || cs.court_site_code || '_JuryCurrentStatus_1', 'Jury Current Status', 20
	FROM XHB_COURT c, XHB_COURT_SITE cs
	WHERE c.COURT_ID = cs.COURT_ID
        AND C.COURT_ID = 3;  
COMMIT;

DROP SEQUENCE XHB_PAGE_SEQ;
CREATE SEQUENCE XHB_PAGE_SEQ START WITH 37 INCREMENT BY 1 MINVALUE 1 NOCACHE  NOCYCLE  NOORDER ;
COMMIT;

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (31,31); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (32,31); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (33,31); 

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (34,32); 
INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (35,32);  

INSERT INTO XHB_PAGE_ROTATION_SET ( PAGE_ID, ROTATION_SET_ID ) 
VALUES (36,33); 

COMMIT;

INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
31, 1); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
32, 2); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
33, 3); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
34, 4); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
35, 5); 
INSERT INTO XHB_PAGE_PANEL ( PAGE_ID, PANEL_ID ) VALUES ( 
36, 6); 
COMMIT;