INSERT INTO MTBL_HTTP_RETRY ( MAPNAME, ATTEMPTS, FREQUENCY ) VALUES ( 
'Resynch_Refresh_Caller.mmc', 5, 2); 
INSERT INTO MTBL_HTTP_RETRY ( MAPNAME, ATTEMPTS, FREQUENCY ) VALUES ( 
'Pre_Hearing_Initial_Upload_Split.mmc', 5, 2); 
INSERT INTO MTBL_HTTP_RETRY ( MAPNAME, ATTEMPTS, FREQUENCY ) VALUES ( 
'Exp_Res_CRN.mmc', 5, 2); 
COMMIT;
