
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.services;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import uk.gov.courtservice.xhibit.business.services.dartsmessagesender.WSDartsSenderControllerBean;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ContextRegistryService", targetNamespace = "http://services.rt.fs.documentum.emc.com/", wsdlLocation = "ContextRegistryService.wsdl")
@HandlerChain(file="handler-chain.xml")
public class ContextRegistryService
    extends Service
{

    private final static URL CONTEXTREGISTRYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.services.ContextRegistryService.class.getName());

    static {
        URL url = null;
        try {
       	
        	 String wsdlLocation = WSDartsSenderControllerBean.getContextRegWsdlLocation();
             url = new URL("file://"+ wsdlLocation);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'ContextRegistryService.wsdl'");
            logger.warning(e.getMessage());
        }
        CONTEXTREGISTRYSERVICE_WSDL_LOCATION = url;
    }

    public ContextRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ContextRegistryService() {
        super(CONTEXTREGISTRYSERVICE_WSDL_LOCATION, new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryService"));
    }

    /**
     * 
     * @return
     *     returns ContextRegistryServicePort
     */
    @WebEndpoint(name = "ContextRegistryServicePort")
    public ContextRegistryServicePort getContextRegistryServicePort() {
        return super.getPort(new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryServicePort"), ContextRegistryServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ContextRegistryServicePort
     */
    @WebEndpoint(name = "ContextRegistryServicePort")
    public ContextRegistryServicePort getContextRegistryServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.rt.fs.documentum.emc.com/", "ContextRegistryServicePort"), ContextRegistryServicePort.class, features);
    }

}
