
package uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.context.ServiceContext;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ContextRegistryServicePort", targetNamespace = "http://services.rt.fs.documentum.emc.com/")
@XmlSeeAlso({
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.content.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.context.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.profiles.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.properties.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.datamodel.core.query.ObjectFactory.class,
	uk.gov.courtservice.xhibit.business.services.dartsjaxwswebserviceclient.documentum.rt.ObjectFactory.class
})
public interface ContextRegistryServicePort {


    /**
     * 
     * @param host
     * @param context
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "register", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.Register")
    @ResponseWrapper(localName = "registerResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.RegisterResponse")
    public String register(
        @WebParam(name = "context", targetNamespace = "")
        ServiceContext context,
        @WebParam(name = "host", targetNamespace = "")
        String host);

    /**
     * 
     * @param token
     * @return
     *     returns com.emc.documentum.fs.datamodel.core.context.ServiceContext
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "lookup", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.Lookup")
    @ResponseWrapper(localName = "lookupResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.LookupResponse")
    public ServiceContext lookup(
        @WebParam(name = "token", targetNamespace = "")
        String token);

    /**
     * 
     * @param token
     */
    @WebMethod
    @RequestWrapper(localName = "unregister", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.Unregister")
    @ResponseWrapper(localName = "unregisterResponse", targetNamespace = "http://services.rt.fs.documentum.emc.com/", className = "com.emc.documentum.fs.rt.services.UnregisterResponse")
    public void unregister(
        @WebParam(name = "token", targetNamespace = "")
        String token);

}
