host: 130.177.1.35
port: 389
principal: weblogic
credential: password
poolEnabled: true
initialPoolSize: 6
maximumPoolSize: 12
cacheEnabled: true
cacheSize: 32
cacheTTL: 60
followReferrals: false
bindAnonymouslyOnReferrals: false
pageSize: 1000
sizeLimit: 1000
batchSize: 1
timeLimit: 0
connectTimeout: 0
parallelConnectDelay: 0
userSearchBase: DC=ops,DC=cs,DC=root
userSearchScope: subtree
userFilterExtension: (objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))
userPrincipalAttribute: samAccountName
userDisplayAttribute: displayName
userForenameAttribute: givenName
userSurnameAttribute: sn
groupSearchBase: DC=ops,DC=cs,DC=root
groupSearchScope: subtree
groupFilterExtension: (objectClass=group)
groupPrincipalAttribute: cn
groupMemberOfAttribute: memberOf
groupRootPrincipal: XHIBIT User
terminalSearchBase: DC=ops,DC=cs,DC=root
terminalSearchScope: subtree
terminalFilterExtension: (objectClass=computer)
terminalNameAttribute: cn
terminalLocationAttribute: description

