################################################################################
# Application configuration properties
################################################################################

# Timeout for commands in seconds
command.timeout=30

# IP address details which restrict which are considered to be unregistered cdus
cdu.network=192.168.1
cdu.host.min=208
cdu.host.max=239

# Operating system specific commands to get the list of unregistered cdus
# Linux mock command
#cdu.list.command=cat /opt/moj/tomcat/conf/ipn-mock.txt
# Linux live command
cdu.list.command=ip n

# Operating system specific commands to manage cdus
cdu.register.command=/usr/bin/registerCDU.sh
cdu.unregister.command=/usr/bin/unregisterCDU.sh

# Operating system specific command to restart cdu
# Linux mock command to return 0 (success)
#cdu.restart.command=true
# Linux mock command to return >0 (false)
#cdu.restart.command=false
# Linux live live command which allows 15 seconds for each CDU to respond
cdu.restart.command=ssh -o ConnectTimeout=15 -o StrictHostKeyChecking=no xhibit@{0} "nohup sudo reboot &>/dev/null & exit"

# Operating system specific command to retrieve the CDU screenshot
cdu.screenshot.command=curl -s --max-time 20 http://{0}/screenshot.php -o {1}

# Location of application.log for determining CDU ragstatus of green or amber
cdu.ragstatus.applog.location=/var/log/application.log

# Operating system specific command for determining CDU ragstatus of red
# Linux mock command to return 0 (success)
#cdu.ragstatus.red.command=true
# Linux mock command to return >0 (false)
#cdu.ragstatus.red.command=false
# Linux live live command which allows 15 seconds for each CDU to respond
cdu.ragstatus.red.command=ssh -o ConnectTimeout=15 -o StrictHostKeyChecking=no xhibit@{0} exit
cdu.ragstatus.red.delay=60000

# Number of complete cycles through a CDU and all it's URLs
cdu.ragstatus.amber.count=3
# Text found in application.log that represents an Amber status for a CDU
cdu.ragstatus.amber.text=INVALID_SERVER_RESPONSE
# Text found in application.log that represents an Green status for a CDU
cdu.ragstatus.green.text=SUCCESS: using stylesheet

# Operating system specific commands to manage dhcp
dhcp.restart.command=/usr/bin/restartDHCP.sh

# Operating system specific commands to get the host name (short) the local proxy
localproxy.hostname.command=hostname -s

# Operating system specific commands to determine the ragstatus of the local proxy
localproxy.ragstatus.command=curl -s --max-time 10 http://192.168.1.254/proxy/xhibit_proxy.php